### PR TITLE
Fix escaped like wildcards in `like_utf8` / `nlike_utf8` kernels

### LINKED ISSUE #415: like / nlike_utf8 do not allow escaping `%`
**Describe the bug**

`like_utf8`  and `nlike_utf8`  and scalar variants don't take care of escaping the wildcard character.

**To Reproduce**

```
    test_utf8_scalar!(
        test_utf8_scalar_escape,
        vec!["a%", "a\\x"],
        "a\\%",
        like_utf8_scalar,
        vec![true, false]
    );

This fails in master, returning false / true.
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by daniel-martinez-maqueda-sap**
# Which issue does this PR close?

Closes #415

# Rationale for this change
 
It is explained in the Issues linked above.

# What changes are included in this PR?

Added a new function that replaces the like wildcards '%' and '_' for the regex counterparts before executing them. It also takes into account that the wildcards can be escaped, in that case, it does remove the escape characters and leaves the wildcards so that they are matched against the raw character.

This is implemented iterating over all the characters of the pattern to figure out when it needs to be transformed or not.

# Are there any user-facing changes?
N/A

### CODE REVIEW

File: arrow/src/compute/kernels/comparison.rs [hunk 1]
```diff
@@ -296,6 +298,41 @@ pub fn like_utf8_scalar<OffsetSize: OffsetSizeTrait>(
     Ok(BooleanArray::from(data))
 }
 
+fn replace_like_wildcards(text: &str) -> Result<String> {
+    let text = escape(text);
```
Comment (jhorstmann) [inline arrow/src/compute/kernels/comparison.rs:302]: There is the `regex_syntax::is_meta_character` function, which is used by `escape`, using that we could handle both regex and like pattern characters in one loop. I think that could simplify the logic quite a bit.

Pseudocode, not yet handling that `next` could be `None`:

```rust
let mut chars_iter = text.chars().peekable()
for c in chars_iter {
    if c == '\\' {
        append('\\'); 
        append('\\'); 
        let next = chars_iter.peek();
        if next == '%' || next == '_' {
           chars_iter.next(); // consume next, like character does not need to be transformed
            append(next);
        }
    } else if regex_syntax::is_meta_character(c) {
        append('\\');
        append(c);
    } else if c == '%' {
        append(".*");
    } else if c == '_' {
        append(".");
    } else {
        append(c);
    }
}
```

Comment (jhorstmann) [reply arrow/src/compute/kernels/comparison.rs:302]: Maybe this function could also already return whether we have one of the special cases "starts with", "ends with" or "contains". But I think the regex engine already contains some of those optimizations so maybe we don't really need to special case them in the kernels. Might be out of scope for this ticket.

Comment (daniel-martinez-maqueda-sap) [reply arrow/src/compute/kernels/comparison.rs]: Thanks for the comments.

This approach is much more readable. Already applied in the next commit.

Regarding the second comment. I also think it is outside of the scope of this PR.

File: arrow/Cargo.toml [hunk 2]
```diff
@@ -49,6 +49,7 @@ half = { version = "2.0", default-features = false }
 hashbrown = { version = "0.12", default-features = false }
 csv_crate = { version = "1.1", default-features = false, optional = true, package="csv" }
 regex = { version = "1.5.6", default-features = false, features = ["std", "unicode"] }
+regex-syntax = { version = "0.6.27", default-features = false, features = ["unicode"] }
```
Comment (alamb) [inline arrow/Cargo.toml:52]: I am always worried about new dependencies in arrow but I double checked and this is already a dependency of `regex` so I don't think it is "net-new" to arrow. 👍 

https://crates.io/crates/regex-syntax/reverse_dependencies

File: arrow/src/compute/kernels/comparison.rs [hunk 3]
```diff
@@ -296,6 +298,39 @@ pub fn like_utf8_scalar<OffsetSize: OffsetSizeTrait>(
     Ok(BooleanArray::from(data))
 }
 
+fn replace_like_wildcards(text: &str) -> Result<String> {
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:301]: It would help me review this code if we can include a docstring on this function explaining what replacements it was doing.

Like explaining it was trying to escape `%` with `\\%` perhaps

File: arrow/src/compute/kernels/comparison.rs [hunk 4]
```diff
@@ -342,7 +377,7 @@ pub fn nlike_utf8_scalar<OffsetSize: OffsetSizeTrait>(
             result.append(!left.value(i).ends_with(&right[1..]));
         }
     } else {
-        let re_pattern = escape(right).replace('%', ".*").replace('_', ".");
+        let re_pattern = replace_like_wildcards(right)?;
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:380]: I really like how you have refactored this code 👍

File: arrow/src/compute/kernels/comparison.rs [hunk 5]
```diff
@@ -3740,6 +3775,50 @@ mod tests {
         vec![false, true, false, false]
     );
 
+    test_utf8_scalar!(
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:3778]: ❤️ these test are very nice

File: arrow/src/compute/kernels/comparison.rs [hunk 6]
```diff
@@ -3740,6 +3775,50 @@ mod tests {
...
+        vec!["%%%"],
+        vec![r#"\%_\%"#],
+        ilike_utf8,
+        vec![true]
+    );
+
+    #[test]
+    fn test_replace_like_wildcards() {
+        let a_eq = "_%";
+        let expected = String::from("..*");
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:3797]: You can probably do like this for some brevity:

```suggestion
        let expected = "..*";
```

And if the assert below gives you issues, maybe it needs something like an extra `&`:

```rust
        assert_eq!(&replace_like_wildcards(a_eq).unwrap(), expected);
```

File: arrow/src/compute/kernels/comparison.rs [hunk 7]
```diff
@@ -3740,6 +3775,50 @@ mod tests {
...
+    #[test]
+    fn test_replace_like_wildcards_leave_like_meta_chars() {
+        let a_eq = "\\%\\_";
+        let expected = String::from("%_");
+        assert_eq!(replace_like_wildcards(a_eq).unwrap(), expected);
+    }
+
+    #[test]
+    fn test_replace_like_wildcards_with_multiple_escape_chars() {
+        let a_eq = "\\\\%";
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:3810]: I think it may be worth testing `\\\%` (aka unbalanced, three slashes)

**Review by alamb — APPROVED** [review]
Thank you @daniel-martinez-maqueda-sap  -- this looks like an improvement to me for sure. I  left some suggestions but I think this PR is already better than master and I think it could be merged as is

File: arrow/Cargo.toml (hunk 2 above)
Comment (daniel-martinez-maqueda-sap) [reply arrow/Cargo.toml:52]: Yep, this is a dependency of `regex` and the function used, was already indirectly called. :)

File: arrow/src/compute/kernels/comparison.rs (hunk 3 above)
Comment (daniel-martinez-maqueda-sap) [reply arrow/src/compute/kernels/comparison.rs:301]: Yes, that makes sense. I usually follow the rule of documenting all the public functions but that doesn't mean that the rest should not be documented. Adding it in the next commit!

File: arrow/src/compute/kernels/comparison.rs (hunk 7 above)
Comment (daniel-martinez-maqueda-sap) [reply arrow/src/compute/kernels/comparison.rs:3810]: Rust complains with: `Syntax error: invalid escape`

File: arrow/src/compute/kernels/comparison.rs (hunk 6 above)
Comment (daniel-martinez-maqueda-sap) [reply arrow/src/compute/kernels/comparison.rs:3797]: It works without adding `&`. :)

File: arrow/src/compute/kernels/comparison.rs [hunk 8]
```diff
@@ -298,10 +298,15 @@ pub fn like_utf8_scalar<OffsetSize: OffsetSizeTrait>(
     Ok(BooleanArray::from(data))
 }
 
-fn replace_like_wildcards(text: &str) -> Result<String> {
+/// Transforms a like `pattern` to a regex compatible pattern. To achieve that, it does:
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:301]: ❤️

**Review by alamb — APPROVED** [review]

File: arrow/src/compute/kernels/comparison.rs (hunk 5 above)
Comment (daniel-martinez-maqueda-sap) [reply arrow/src/compute/kernels/comparison.rs:3788]: Thanks! :1st_place_medal:

**Review by alamb — APPROVED** [review]
