### PR TITLE
fix: add missing precision overflow checking for `cast_string_to_decimal`

### LINKED ISSUE #4829: cast_string_to_decimal should check precision overflow
**Describe the bug**
Casting from string to decimal does not perform a precision overflow check.

**To Reproduce**
```rust
use arrow::array::types::Decimal128Type;
use arrow::array::{AsArray, StringArray};
use arrow::compute::{cast_with_options, CastOptions};
use arrow::datatypes::DataType;

fn main() {
    let str_array = StringArray::from(vec!["1000".to_string()]);
    let output_type = DataType::Decimal128(10, 8);
    let mut option = CastOptions::default();
    option.safe = false;
    let casted_array = cast_with_options(&str_array, &output_type, &option).unwrap();
    let decimal_array = casted_array.as_primitive::<Decimal128Type>();
    println!("{:?}", decimal_array.value_as_string(0));
}

```
The execution result of the above program is "10.00000000".

**Expected behavior**

It should panic and report an overflow.

**Additional context**

### PR DESCRIPTION
**Pull request by jonahgao**
# Which issue does this PR close?

Closes #4829.

# Rationale for this change
 
Perform a precision overflow check when casting from a string to a decimal.
# What changes are included in this PR?

# Are there any user-facing changes?
No

### CODE REVIEW

File: arrow-cast/src/cast.rs [hunk 1]
```diff
@@ -2801,6 +2801,11 @@ where
     if cast_options.safe {
         let iter = from.iter().map(|v| {
             v.and_then(|v| parse_string_to_decimal_native::<T>(v, scale as usize).ok())
+                .and_then(|v| {
+                    T::validate_decimal_precision(v, precision)
+                        .is_ok()
+                        .then_some(v)
+                })
```
Comment (viirya) [inline arrow-cast/src/cast.rs:2808]: I believe that the original idea is to avoid this validation and leave the decision to the caller. But after several rounds of revamp on decimal, I'm not sure if that is still kept and we want to add validation now.

Comment (jonahgao) [reply arrow-cast/src/cast.rs:2808]: @viirya I noticed that casting from integers has this validation, which is inconsistent with the behavior of casting from strings.

There is an intuitive example in Datafusion.
```
DataFusion CLI v31.0.0
❯ select cast(1000 as decimal(10,8));
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Invalid argument error: 100000000000 is too large to store in a Decimal128 of precision 10. Max is 9999999999

❯ select cast('1000' as decimal(10,8));
+--------------+
| Utf8("1000") |
+--------------+
| 10.00000000  |
+--------------+
```
If they could have a unified behavior, it would be preferable.

Comment (tustvold) [reply arrow-cast/src/cast.rs:2808]: I don't feel strongly here, casting in general does tend to check for overflow, and given it is parsing a string is unlikely to massively regress performance. I defer to you @viirya

File: arrow-cast/src/cast.rs [hunk 2]
```diff
@@ -8097,6 +8106,32 @@ mod tests {
         test_cast_string_to_decimal(array);
     }
 
+    #[test]
+    fn test_cast_string_to_decimal128_precision_overflow() {
```
Comment (viirya) [inline arrow-cast/src/cast.rs:8110]: cast_string_to_decimal is not only for decimal128 but also for decimal256, do you want to add a test for decimal256 too?

Comment (jonahgao) [reply arrow-cast/src/cast.rs]: @viirya I think it is necessary, and a new test has been added for decimal256.

Comment (viirya) [reply arrow-cast/src/cast.rs]: Thank you.

**Review by viirya — APPROVED** [review]
