### PR TITLE
Fix signed decimal e-notation parsing

### LINKED ISSUE #6728: Signed decimal e-notation parsing bug
**Describe the bug**
Parsing signed decimal numbers in e-notation has a bug, whereby the parsed values is magnified by an order of magnitude (leading to potential false overflows).

**To Reproduce**
Run the following test (e.g. in `arrow-cast/src/parse.rs`)
```rust
    #[test]
    fn test_negative_decimal_e_notation() {
        assert_eq!(
            parse_decimal::<Decimal128Type>("-1e3", 38, 6).unwrap(),
            -1000000000i128,
        );

        assert_eq!(
            parse_decimal::<Decimal128Type>("-1e31", 38, 6).unwrap(),
            -10000000000000000000000000000000000000i128,
        );
    }
```
The first assertion will fail, as the parsed value is erroneously `-11000000000`, while the second example will panic with `parse decimal overflow (-1e31)`, even though the value fits in the specified precision/scale range.

**Expected behavior**
The first test case above should return `-1000000000i128` (i.e. 3 zeros from `e3` + additional 6 zeros from the scale).

The seconds case shouldn't overflow and should instead return `-10000000000000000000000000000000000000i128` (i.e. 31 zeros from `e31` + additional 6 zeros from the scale).

**Additional context**

### PR DESCRIPTION
**Pull request by gruuya**
# Which issue does this PR close?

Closes #6728.

# Rationale for this change
When parsing signed decimal numbers the leading sign is stripped from the raw value bytes, and the `e` index is passed relative to the stripped slice.

However, the full value is passed into `parse_e_notation`, leading to a off-by-one error of the index for the signed numbers.

# What changes are included in this PR?
Do not strip the sign when parsing, and make the `e` index relative to the full value, thus aligning `parse_e_notation` and `parse_decimal`.

# Are there any user-facing changes?
None

### CODE REVIEW

File: arrow-select/src/zip.rs [hunk 1]
```diff
@@ -53,7 +53,7 @@ pub fn zip(
             "all arrays should have the same length".into(),
         ));
     }
-    if truthy_is_scalar && truthy.len() != 1 {
+    if falsy_is_scalar && falsy.len() != 1 {
```
Comment (gruuya) [inline arrow-select/src/zip.rs:56]: This is just a drive-by validation fix.

**Review by waynexia — APPROVED** [review]
This is a clear fix, LGTM 👍
