### PR TITLE
Fix min/max computation for sliced arrays (#2779)

### LINKED ISSUE #2779: min compute kernel is incorrect with sliced buffers in arrow 23
**Describe the bug**

When operating on an array that was `slice`ed, the result of `min` is incorrect

```
min([Null, 4.0] --> should be 4.0
```

However, 
```
min([Null, Null, Null, Null, Null, Null, 4.0].slice(4,2)) --> should be 4.0 as well but returns None
```
**To Reproduce**

Use this program:

```rust
use arrow::{array::{Float64Array, Array, as_primitive_array}, datatypes::Float64Type};



fn main() {
    // behavior of sliced min changed (TODO make a demonstration)

    // Input is [None, 4.0], min value should be 4.0
    let expected_min = Some(4.0);
    let input: Float64Array = vec![None, Some(4.0)].into_iter().collect();
    let min = arrow::compute::min(&input);

    assert_eq!(min, expected_min);

    // however, when sliced the min value is incorrect
    let sliced_input: Float64Array = vec![None, None, None, None, None, Some(4.0)].into_iter().collect();
    let sliced_input = sliced_input.slice(4, 2);
    let sliced_input = as_primitive_array::<Float64Type>(&sliced_input);

    // The array valare are equal
    assert_eq!(sliced_input, &input);

    // but the minimum is not
    let sliced_min = arrow::compute::min(&sliced_input);
    assert_eq!(sliced_min, expected_min);

}
```

**Expected behavior**
The example should pass. It passes on arrow `22.0.0` but fails on arrow `23.0.0` like this:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(4.0)`', src/main.rs:25:5
stack backtrace:
```

**Additional context**
Found while debugging upgrade in IOx: https://github.com/influxdata/influxdb_iox/pull/5694

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2779

# Rationale for this change
 

The previous logic was incorrect

# What changes are included in this PR?

https://github.com/apache/arrow-rs/pull/2675 introduced a bug when computing the min or max for sliced arrays, FYI @viirya 

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/compute/kernels/aggregate.rs [hunk 1]
```diff
@@ -124,10 +124,7 @@ where
             .map(|i| unsafe { array.value_unchecked(i) })
             .reduce(|acc, item| if cmp(&acc, &item) { item } else { acc })
     } else {
-        let null_buffer = array
-            .data_ref()
-            .null_buffer()
-            .map(|b| b.bit_slice(array.offset(), array.len()));
+        let null_buffer = array.data_ref().null_buffer();
```
Comment (tustvold) [inline arrow/src/compute/kernels/aggregate.rs:127]: As an added bonus this will be faster

File: arrow/src/compute/kernels/aggregate.rs [hunk 2]
```diff
@@ -1130,4 +1128,22 @@ mod tests {
         let array = dict_array.downcast_dict::<Float32Array>().unwrap();
         assert_eq!(2.0_f32, min_array::<Float32Type, _>(array).unwrap());
     }
+
+    #[test]
+    fn test_min_max_sliced() {
```
Comment (alamb) [inline arrow/src/compute/kernels/aggregate.rs:1133]: I suggest some coverage for `max` as well.

Also, shall we try the min/max for `utf8` and `boolean`?

File: arrow/src/compute/kernels/aggregate.rs (hunk 1 above)
Comment (alamb) [inline arrow/src/compute/kernels/aggregate.rs:127]: Is there any other kernel that might have the same issue?

There appear to be a few other similar uses:

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/apache/arrow-rs%24+bit_slice&patternType=standard

**Review by alamb — APPROVED** [review]
super speed. Thanks @tustvold !

**Comment by alamb** [comment]
I will try and test this against my upgrade PR as well

**Comment by alamb** [comment]
Update is I have verified that this change fixes the regression in https://github.com/influxdata/influxdb_iox/pull/5694
