### PR TITLE
Fix `filter_record_batch` panics with empty struct array

### LINKED ISSUE #7538: filter_record_batch panics with empty struct array.
If you call `filter_record_batch` with a record that has an empty struct array, the `filter_struct` function will panic because it will call `StructArray::new_unchecked` which throws panic because the columns have no length.

**To Reproduce**
```rust
   #[test]
    fn test_filter_empty_struct() {
        /*
            "a": {
                "b": int64,
                "c": {}
            },
        */
        let fields = arrow_schema::Field::new(
            "a",
            arrow_schema::DataType::Struct(arrow_schema::Fields::from(vec![
                arrow_schema::Field::new("b", arrow_schema::DataType::Int64, true),
                arrow_schema::Field::new(
                    "c",
                    arrow_schema::DataType::Struct(arrow_schema::Fields::empty()),
                    true,
                ),
            ])),
            true,
        );

        /* Test record
            {"a":{"c": {}}}
            {"a":{"c": {}}}
            {"a":{"c": {}}}
        */

        // Create the record batch with the nested struct array
        let schema = Arc::new(Schema::new(vec![fields]));

        let b = Arc::new(Int64Array::from(vec![None, None, None]));
        let c = Arc::new(StructArray::new_empty_fields(
            3,
            Some(NullBuffer::from(vec![true, true, true])),
        ));
        let a = StructArray::new(
            vec![
                Field::new("b", DataType::Int64, true),
                Field::new("c", DataType::Struct(Fields::empty()), true),
            ]
            .into(),
            vec![b.clone(), c.clone()],
            Some(NullBuffer::from(vec![true, true, true])),
        );
        let record_batch = RecordBatch::try_new(schema, vec![Arc::new(a)]).unwrap();
        println!("{record_batch:?}");

        // Apply the filter
        let predicate = BooleanArray::from(vec![true, false, true]);
        let filtered_batch = filter_record_batch(&record_batch, &predicate).unwrap();

        // The filtered batch should have 2 rows (the 1st and 3rd)
        assert_eq!(filtered_batch.num_rows(), 2);
    }
```

**Expected behavior**
I expect it to correctly filter the record.

**Additional context**
First noticed in delta-rs library https://github.com/delta-io/delta-rs/issues/3237

### PR DESCRIPTION
**Pull request by thorfour**
# Which issue does this PR close?

- Closes #7538 

# Rationale for this change
 
This prevents a panic that can happen with empty struct arrays.

# What changes are included in this PR?

Small unit test that exacerbates the panic by attempting to filter a struct array with no columns. 
Fix was to call `StructArray:new_unchecked_with_length` since the predicate of the filter contains the number rows the array requires.

# Are there any user-facing changes?
No

### CODE REVIEW

File: arrow-select/src/filter.rs [hunk 1]
```diff
@@ -2067,4 +2074,59 @@ mod tests {
 
         assert_eq!(result.to_data(), expected.to_data());
     }
+
+    #[test]
+    fn test_filter_empty_struct() {
```
Comment (alamb) [inline arrow-select/src/filter.rs:2079]: I verified that this test fails without the code in this PR: 

```
thread 'filter::tests::test_filter_empty_struct' panicked at arrow-array/src/array/struct_array.rs:224:51:
cannot use StructArray::new_unchecked if there are no fields, length is unknown
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think this is additional fallout from a new panic we introduced in this PR from @westonpace 
- #7247

**Review by alamb — APPROVED** [review]
Thank you @thorfour  and @brancz  -- this makes sense to me

File: arrow-select/src/filter.rs (hunk 1 above)
Comment (thorfour) [reply arrow-select/src/filter.rs:2079]: That's correct however without that panic the bug was much more subtle as it created an invalid record batch that would panic when slicing elsewhere.

**Comment by alamb** [comment]
Thanks again @thorfour
