### PR TITLE
Use IPC row count info in IPC reader

### LINKED ISSUE #1783: `flight_data_to_arrow_batch` does not support `RecordBatch`es with no columns
**Describe the bug**

Attempting to use `flight_data_to_arrow_batch` on flight data that does not have any columns returns an `InvalidArgumentError("must either specify a row count or at least one column")`.

**To reproduce**

Call `flight_data_to_arrow_batch` on a `FlightData` and `Schema` that does not have any columns.

**Expected behavior**

Calling `flight_data_to_arrow_batch` should use the row information in the RecordBatch header and return a valid record batch instead of returning an error.

**Additional context**

Support for `RecordBatch`es with no columns but with a row count was already added in #1552. `flight_data_to_arrow_batch` already has the row count information provided as an argument. It gets read there in `message.header_as_record_batch()`, but then the subsequent `reader::read_record_batch` call seems to discard that info.

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1783.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — APPROVED** [review]

File: arrow/src/ipc/reader.rs [hunk 1]
```diff
@@ -608,6 +608,11 @@ pub fn read_record_batch(
     let mut node_index = 0;
     let mut arrays = vec![];
 
+    let options = RecordBatchOptions {
+        match_field_names: true,
+        row_count: Some(batch.length() as usize),
+    };
```
Comment (tustvold) [inline arrow/src/ipc/reader.rs:614]:
```suggestion
    let options = RecordBatchOptions {
        row_count: Some(batch.length() as usize),
        ..Default::default()
    };
```
