### PR TITLE
Fix negative decimal string

### LINKED ISSUE #5127: cast `Utf8` to decimal failure
**Describe the bug**

arrow cannot cast `Utf8` to decimal correctly in #8326.
```
// Negative number is wrong
❯ select '-1.23499999'::DECIMAL(4,3);
+---------------------+
| Utf8("-1.23499999") |
+---------------------+
| -0.765              |
+---------------------+
1 row in set. Query took 0.032 seconds.
```

The problem is that arrow does not parse the string correctly.
[fn parse_string_to_decimal_native<T: DecimalType>(](https://github.com/apache/arrow-rs/blob/df69ef57d055453c399fa925ad315d19211d7ab2/arrow-cast/src/cast.rs#L2629-L2632)

**To Reproduce**

``` rust
    #[test]
    fn test() {
        let array = LargeStringArray::from(vec![Some("-0.12345")]);

        // Decimal128
        let output_type = DataType::Decimal128(38, 2);
        assert!(can_cast_types(array.data_type(), &output_type));

        let casted_array = cast(&array, &output_type).unwrap();
        let decimal_arr = casted_array.as_primitive::<Decimal128Type>();

        assert_eq!("-0.12", decimal_arr.value_as_string(0));

        // Decimal256
        let output_type = DataType::Decimal256(76, 3);
        assert!(can_cast_types(array.data_type(), &output_type));

        let casted_array = cast(&array, &output_type).unwrap();
        let decimal_arr = casted_array.as_primitive::<Decimal256Type>();

        assert_eq!("-0.123.", decimal_arr.value_as_string(0));
    }
```

**Expected behavior**

pass the test

**Additional context**

[#8326
](https://github.com/apache/arrow-datafusion/issues/8326#issue-2011408399)

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #5127.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-cast/src/cast.rs [hunk 1]
```diff
@@ -2642,7 +2642,18 @@ where
     }
 
     let integers = parts[0].trim_start_matches('0');
-    let decimals = if parts.len() == 2 { parts[1] } else { "" };
+
+    let (decimals, negative) = if parts.len() == 2 {
+        (parts[1], integers.starts_with('-'))
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:2647]: Should this after the trim_start_matches above? I think this will parse `000-1.343`

File: arrow-cast/src/cast.rs [hunk 2]
```diff
@@ -2642,7 +2642,18 @@ where
...
+    } else {
+        ("", false)
+    };
+
+    let integers = if negative {
+        integers.trim_start_matches('-')
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:2653]: Should this be trim_start_matches or just a single strip_prefix?

File: arrow-cast/src/cast.rs [hunk 3]
```diff
@@ -2677,7 +2688,17 @@ where
...
 
-        format!("{}", integers.add_wrapping(adjusted))
+        let integers = if negative {
+            integers.neg_wrapping()
+        } else {
+            integers
+        };
+
+        if negative {
+            format!("{}", integers.sub_wrapping(adjusted))
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:2698]: Not related to this PR, but I wonder if we need to format to a string and then convert back

File: arrow-cast/src/cast.rs [hunk 4]
```diff
@@ -8304,6 +8331,8 @@ mod tests {
             Some(""),
             Some(" "),
             None,
+            Some("-1.23499999"),
+            Some("-1.23599999"),
```
[the remark this answers is not in the document]
Comment (Weijun-H) [reply arrow-cast/src/cast.rs:8335]: -+123.45 should be failed, but pass.

File: arrow-cast/src/cast.rs (hunk 1 above)
Comment (viirya) [reply arrow-cast/src/cast.rs]: Yea

File: arrow-cast/src/cast.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (viirya) [reply arrow-cast/src/cast.rs:8379]: Added the test case (and others).

File: arrow-cast/src/cast.rs (hunk 3 above)
Comment (viirya) [reply arrow-cast/src/cast.rs]: Hmm, I forgot why we did the conversion at first. Maybe we can get rid of it. As it is not part of this PR, I will do it later.

File: arrow-cast/src/cast.rs [hunk 5]
```diff
@@ -2641,11 +2641,33 @@ where
         )));
     }
 
-    let integers = parts[0].trim_start_matches('0');
+    let (negative, first_part) = if parts[0].is_empty() {
+        (false, parts[0])
+    } else {
+        match parts[0].as_bytes()[0] {
+            b'-' => (true, parts[0].strip_prefix('-').unwrap()),
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:2648]:
```suggestion
            b'-' => (true, &parts[0][1..]),
```

File: arrow-cast/src/cast.rs [hunk 6]
```diff
@@ -2641,11 +2641,33 @@ where
...
+            b'+' => (false, parts[0].strip_prefix('+').unwrap()),
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:2649]:
```suggestion
            b'+' => (false, &parts[0][1..]),
```

**Review by tustvold — APPROVED** [review]

File: arrow-cast/src/cast.rs [hunk 7]
```diff
@@ -8282,6 +8338,21 @@ mod tests {
...
+            Some("-000.123"),
+            Some("+1.23499999"),
+            Some("+1.23599999"),
+            Some("+0.00001"),
+            Some("+123"),
+            Some("+123.234000"),
+            Some("+000.123"),
+            Some("1.-23499999"),
+            Some("-1.-23499999"),
+            Some("--1.23499999"),
```
Comment (Weijun-H) [inline arrow-cast/src/cast.rs:8355]: Why these cases are null instead of error?

Comment (viirya) [reply arrow-cast/src/cast.rs:8355]: When `CastOptions.safe` is true (default), cast failure returns NULL.
