### PR TITLE
[parquet] Add a sync fn to ArrowWriter that flushes Writer

### LINKED ISSUE #8534: [Parquet] ArrowWriter flush does not work
When working with `ArrowWriter` I would like to flush buffered rows onto the disk. However, when calling `ArrowWriter<W>::flush()` only part of the data is flushed. The reason is that `parquet::file::writer::TrackedWrite` that is used by `ArrowWriter` inserts `BufWriter` on top of user supplied writer `W`. This `BufWriter` is not flushed() when `ArrowWriter<W>::flush()` is called. 

The best solution to this problem would be to remove `BufWriter` from `TrackedWrite` and just use the user supplied `Writer`. The `BufWriter` suppose to buffer small writes, but this function is not needed when writing to memory and most operating systems employ this sort of mechanism. Thus, it is redundant. Maybe, `BufWriter` could be beneficial when working with bare-metal system, but then a user could just wrap its writer in `BufWriter` and give it to `ArrowWriter`. Nonetheless, I guess that DataFusion is not ofter run on bare-metal.

### PR DESCRIPTION
**Pull request by PiotrSrebrny**
# Which issue does this PR close?

- Closes #8534.

# Are these changes tested?

Changes where not tested and should be covered by existing. 

# Are there any user-facing changes?

* added the `ArrowWriter::sync()` function that flushes the underlying writer
* added the `SerializedFileWriter::flush()` function that flushes the underlying writer

### CODE REVIEW

File: parquet/src/arrow/arrow_writer/mod.rs [hunk 1]
```diff
@@ -348,6 +348,11 @@ impl<W: Write + Send> ArrowWriter<W> {
         self.writer.write_all(buf)
     }
 
+    /// Flushes underlying writer
+    pub fn sync(&mut self) -> std::io::Result<()> {
```
Comment (alamb) [inline parquet/src/arrow/arrow_writer/mod.rs:358]: technically speaking you can achieve this with `inner_writer().flush()` but I think this API is nicer and less easy to abuse 👍

Comment (PiotrSrebrny) [reply parquet/src/arrow/arrow_writer/mod.rs:358]: Hmm, there is no `inner_writer()`. However, `ArrowWriter::inner().flush()` will flush the user provided writer bypassing `BufWriter`, which does not help as data is stucked in `BufWriter`.

Comment (alamb) [reply parquet/src/arrow/arrow_writer/mod.rs:358]: That is a great point. 👍

**Comment by PiotrSrebrny** [comment]
Hmm, this is my first PR, is there anything missing here in order to merge this in?

**Comment by alamb** [comment]
> Hmm, this is my first PR, is there anything missing here in order to merge this in?

Nope, sorry @PiotrSrebrny  -- I plan to leave this open for another few days to ensure anyone who is interested has a chance to review it before merging

**Comment by PiotrSrebrny** [comment]
No hurry

**Comment by etseidl** [comment]
I think it is worth modifying the documentation on `ArrowWriter::flush` to make clear that the underlying writer is not flushed, and point to `sync` if such a flush is desired. Can be a followup PR.

**Comment by PiotrSrebrny** [comment]
I added a comment you suggested. I think it is nice to have it.

**Comment by etseidl** [comment]
Thanks @PiotrSrebrny!

**Comment by alamb** [comment]
Thanks @etseidl  and @PiotrSrebrny 🚀
