### PR TITLE
fix(ipc): set correct row count when reading struct arrays with zero fields

### LINKED ISSUE #4643: IPC reader fails to decode a struct array with zero fields
**Describe the bug**
Encoding succeeds, but decoding fails with an error `InvalidArgumentError("all columns in a record batch must have the specified row count")`.

**To Reproduce**

```rust
// add to arrow-ipc/src/writer.rs
#[test]
fn ipc_struct_array_with_zero_fields() {
    let record_batch = {
        let struct_ty = DataType::Struct(Vec::<Field>::new().into());
        let structs = ArrayDataBuilder::new(struct_ty.clone())
            .len(3)
            .build()
            .unwrap();
        RecordBatch::try_new_with_options(
            Arc::new(Schema::new(vec![Field::new("field", struct_ty, false)])),
            vec![make_array(structs)],
            &RecordBatchOptions::new().with_row_count(Some(3)),
        )
        .unwrap()
    };
    let deserialized_batch = deserialize(serialize(&record_batch));

    let structs = deserialized_batch
        .column(0)
        .as_any()
        .downcast_ref::<StructArray>()
        .unwrap();

    assert_eq!(structs.len(), 3);
}
```

```
thread 'writer::tests::ipc_struct_array_with_zero_fields' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("all columns in a record batch must have the specified row count")', arrow-ipc\src\writer.rs:1816:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library\std\src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library\core\src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library\core\src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643\library\core\src/result.rs:1076:23
   4: arrow_ipc::writer::tests::deserialize
             at .\src\writer.rs:1816:9
   5: arrow_ipc::writer::tests::ipc_struct_array_with_zero_fields
             at .\src\writer.rs:1976:34
   6: arrow_ipc::writer::tests::ipc_struct_array_with_zero_fields::{{closure}}
             at .\src\writer.rs:1962:44
   7: core::ops::function::FnOnce::call_once
             at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643\library\core\src\ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library\core\src\ops/function.rs:250:5
```

**Expected behavior**
Successful roundtrip conversion

**Additional context**

### PR DESCRIPTION
**Pull request by kawadakk**
# Which issue does this PR close?

Closes #4643.

# Rationale for this change
 
Fixing a bug

# What changes are included in this PR?

Introduces a special case of `arrow_ipc::reader::create_array` for reading a struct array with zero fields. Since `<StructArray as From<Vec<_>>>::from` cannot infer the row count from zero child arrays, we call `StructArray::new_empty_fields` to set it explicitly.

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-ipc/src/reader.rs [hunk 1]
```diff
@@ -1699,6 +1708,18 @@ mod tests {
         check_union_with_builder(UnionBuilder::new_sparse());
     }
 
+    #[test]
+    fn test_roundtrip_struct_empty_fields() {
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:1712]: I ran this test without the code in this PR and it failed as expected. Thus I conclude this test covers the newly added code

```
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("all columns in a record batch must have the specified row count")
thread 'reader::tests::test_roundtrip_struct_empty_fields' panicked at arrow-ipc/src/reader.rs:1609:32:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("all columns in a record batch must have the specified row count")
```

**Review by alamb — APPROVED** [review]
Thank you @kawadakk 

This looks good to me

**Comment by alamb** [comment]
cc @viirya  in case you have time and interest to review

**Comment by alamb** [comment]
Thank you @kawadakk  and @tustvold
