### PR TITLE
fix: Fix a bug in how filter indices are calculated

### LINKED ISSUE #1184: Writing structs nested in lists produces an incorrect output
**Describe the bug**
Writing an arrow record batch with structs nested within lists using the parquet writer produces a parquet file with incorrect values when there are null or empty lists present.

**To Reproduce**
The following program produces a parquet file `out.parquet`.

```rust
use std::sync::Arc;

use arrow::array::{Int32Builder, ListBuilder, StructBuilder};
use arrow::datatypes::{DataType, Field, Schema};
use arrow::record_batch::RecordBatch;

fn main() {
    // define schema
    let int_field = Field::new("a", DataType::Int32, true);
    let item_field = Field::new("item", DataType::Struct(vec![int_field.clone()]), true);
    let list_field = Field::new("list", DataType::List(Box::new(item_field)), true);

    let int_builder = Int32Builder::new(10);
    let struct_builder = StructBuilder::new(vec![int_field], vec![Box::new(int_builder)]);
    let mut list_builder = ListBuilder::new(struct_builder);

    // [{a: 1}], [], null, [null, null], [{a: null}], [{a: 2}]
    //
    // [{a: 1}]
    let values = list_builder.values();
    values
        .field_builder::<Int32Builder>(0)
        .unwrap()
        .append_value(1)
        .unwrap();
    values.append(true).unwrap();
    list_builder.append(true).unwrap();

    // []
    list_builder.append(true).unwrap();

    // null
    list_builder.append(false).unwrap();

    // [null, null]
    let values = list_builder.values();
    values
        .field_builder::<Int32Builder>(0)
        .unwrap()
        .append_null()
        .unwrap();
    values.append(false).unwrap();
    values
        .field_builder::<Int32Builder>(0)
        .unwrap()
        .append_null()
        .unwrap();
    values.append(false).unwrap();
    list_builder.append(true).unwrap();

    // [{a: null}]
    let values = list_builder.values();
    values
        .field_builder::<Int32Builder>(0)
        .unwrap()
        .append_null()
        .unwrap();
    values.append(true).unwrap();
    list_builder.append(true).unwrap();

    // [{a: 2}]
    let values = list_builder.values();
    values
        .field_builder::<Int32Builder>(0)
        .unwrap()
        .append_value(2)
        .unwrap();
    values.append(true).unwrap();
    list_builder.append(true).unwrap();

    let array = Arc::new(list_builder.finish());

    let schema = Arc::new(Schema::new(vec![list_field]));

    let rb = RecordBatch::try_new(schema, vec![array]).unwrap();

    let out = std::fs::File::create("out.parquet").unwrap();
    let mut writer = parquet::arrow::ArrowWriter::try_new(out, rb.schema(), None).unwrap();
    writer.write(&rb).unwrap();
    writer.close().unwrap();
}
```

Running `parquet-dump` on `out.parquet` produces the following output

```
value 1: R:0 D:4 V:1
value 2: R:0 D:1 V:<null>
value 3: R:0 D:0 V:<null>
value 4: R:0 D:2 V:<null>
value 5: R:1 D:2 V:<null>
value 6: R:0 D:3 V:<null>
value 7: R:0 D:4 V:0
```

**Expected behavior**
The last value (value 7) should have been a 2
```
value 1: R:0 D:4 V:1
value 2: R:0 D:1 V:<null>
value 3: R:0 D:0 V:<null>
value 4: R:0 D:2 V:<null>
value 5: R:1 D:2 V:<null>
value 6: R:0 D:3 V:<null>
value 7: R:0 D:4 V:2
```

**Additional context**
`filter_array_indices` function in https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/levels.rs#L760 produces incorrect indices when the immediate parent of a field is not a list. In the writer https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/arrow_writer.rs#L244, those indices are then used to produce the values to write at https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/arrow_writer.rs#L284 causing the incorrect behavior described above.

### PR DESCRIPTION
**Pull request by helgikrs**
# Which issue does this PR close?

Closes #1184.

# What changes are included in this PR?

Using the definition level and the nullability of the column only produces the
correct indices if `max_definition - 1` is the list level.  For deeper nesting
(struct in a list) this produces incorrect indices, silently causing incorrect
data to be written.

This PR fixes the bug by using the array offsets to compute the indices
instead, also adds a regression test.

# Are there any user-facing changes?

No.

### CODE REVIEW

File: parquet/src/arrow/levels.rs [hunk 1]
```diff
@@ -780,17 +773,25 @@ impl LevelInfo {
...
+        let mut definition_levels = self.definition.iter();
         let mut index = 0;
-        self.definition.iter().for_each(|def| {
-            if *def == self.max_definition {
-                filtered.push(index);
-            }
-            if *def >= self.max_definition - is_nullable as i16 {
-                index += 1;
+
+        for len in self.array_offsets.windows(2).map(|s| s[1] - s[0]) {
```
Comment (tustvold) [inline parquet/src/arrow/levels.rs:781]: I'm not hugely familiar with this code, but the below is my attempt to describe what is going on here.

The parquet writer iterates through all the leaf arrays in a potentially nested arrow array, producing a list of `LevelInfo` that it then writes. Each `LevelInfo` identifies for that leaf, what repetition and definition levels to write. This method is then used to compute which non-null indices from the source primitive array to write that correspond to this information.

It therefore iterates through the definition levels and where `def == self.max_definition` it records that index as one that needs to be written to parquet. 

The problem with the previous logic was it assumed that only a null or value at the leaf level, i.e. `def >= max_def - is_nullable` would increase the index position in the source primitive array. 

Whilst this is the case for a parent nullable ListArray, it is not for a parent nullable StructArray. Critically, **a null in a ListArray may not take up space in its child array, but a null in a StructArray does**. 

By using the `array_offsets` instead of the nesting level, we can handle both cases by distinguishing list array nulls that don't take up space  :+1:

**Review by tustvold — COMMENTED** [review]
Mega kudos for working this one out, my head hurts now :laughing: 

_I'm afraid I can't approve PRs on this repo, but if I could I'd give it a :heavy_check_mark: _

File: parquet/src/arrow/levels.rs [hunk 2]
```diff
@@ -780,17 +773,25 @@ impl LevelInfo {
...
+            if len == 0 {
+                // Skip this definition level (it should be less than max_definition)
```
Comment (tustvold) [inline parquet/src/arrow/levels.rs:783]: Perhaps this code should verify that it is indeed a null? :thinking:

File: parquet/src/arrow/levels.rs [hunk 3]
```diff
@@ -759,13 +759,6 @@ impl LevelInfo {
     /// Given a level's information, calculate the offsets required to index an array correctly.
     pub(crate) fn filter_array_indices(&self) -> Vec<usize> {
         // happy path if not dealing with lists
-        let is_nullable = match self.level_type {
-            LevelType::Primitive(is_nullable) => is_nullable,
-            _ => panic!(
```
[the remark this answers is not in the document]
Comment (helgikrs) [reply parquet/src/arrow/levels.rs:764]: Makes sense. Added the assertion back.

File: parquet/src/arrow/levels.rs (hunk 2 above)
Comment (helgikrs) [reply parquet/src/arrow/levels.rs]: Added an assert :)

**Review by alamb — APPROVED** [review]
While I don't follow the details of this PR fully, I trust that @tustvold  and @helgikrs  know what they are doing

Thank you both for the contributions
