### PR TITLE
Encode UUID as FixedLenByteArray in parquet_derive

### LINKED ISSUE #5254: parquet_derive: UUID should not be a ByteArray
**Describe the bug**

`ParquetRecordWriter` is marking UUID as a `ByteArray` which causes a panic.

```
General("Cannot annotate Uuid from BYTE_ARRAY for field 'session_id'")
```

**To Reproduce**

```
#[derive(parquet_derive::ParquetRecordWriter)]
struct RequestData {
    session_id: uuid::Uuid,
}

fn main() {
    let data: &[RequestData] = &[];
    let _schema = data.schema();
}
```

**Expected behavior**

UUID should be typed as a `FixedLenByteArray` with length 16.

**Additional context**

https://github.com/apache/arrow-rs/blob/3cd6da0a6b97056f3717d3491c84ec6d734aa262/parquet_derive/src/parquet_field.rs#L641

### PR DESCRIPTION
**Pull request by conradludgate**
# Which issue does this PR close?

Closes #5254.

# Rationale for this change
 

UUIDs are specified to be FixedByteArray(16), not ByteArray.

# What changes are included in this PR?

Adds support for defining type builders with a length field. Fixes mapping for uuid to encoded type.

# Are there any user-facing changes?

This is likely a breaking change as it is no longer compatible with prior parquet encodings generated with this lib.

### CODE REVIEW

File: parquet_derive/src/parquet_field.rs [hunk 1]
```diff
@@ -638,11 +636,40 @@ impl Type {
...
+            }
+            Type::Vec(ref first_type) | Type::Slice(ref first_type) => {
+                if let Type::TypePath(_) = **first_type {
+                    if last_part == "u8" {
+                        return None;
+                    }
+                }
+            }
+            _ => (),
+        }
```
Comment (tustvold) [inline parquet_derive/src/parquet_field.rs:665]: What is this logic for?

Comment (conradludgate) [reply parquet_derive/src/parquet_field.rs:665]: Good question. It seems I copied it from `fn logical_type()` below

Comment (conradludgate) [reply parquet_derive/src/parquet_field.rs:665]: Ok, it seems the intention was for `[u8; N]` to be length N, but it seems incorrect. It also seems like `[u8; N]` just isn't supported either in my testing.

**Comment by tustvold** [comment]
Thank you
