### PR TITLE
type_id and value_offset are incorrect for sliced UnionArray

### LINKED ISSUE #2086: `type_id` and `value_offset` are incorrect for sliced UnionArray
**Describe the bug**

`UnionArray.value` has considered slicing case so it adjusts given `index` with `self.offset()` when calling type_id` and `value_offset`. But `type_id` and `value_offset` are incorrect by itself when they are called separately. We should fix them.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #2086.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/array/array_union.rs [hunk 1]
```diff
@@ -383,6 +383,7 @@ mod tests {
     use crate::array::*;
     use crate::buffer::Buffer;
     use crate::datatypes::{DataType, Field};
+    use crate::record_batch::RecordBatch;
```
Comment (tustvold) [inline arrow/src/array/array_union.rs:386]: ?

File: arrow/src/array/array_union.rs [hunk 2]
```diff
@@ -956,4 +957,79 @@ mod tests {
...
+            builder.append::<Float64Type>("c", 3.0).unwrap();
+            builder.append_null::<Float64Type>("c").unwrap();
+            builder.append::<Int32Type>("a", 4).unwrap();
+            builder.build().unwrap()
+        }
+
+        // [1, null, 3.0, null, 4]
+        fn create_dense_union() -> UnionArray {
+            let mut builder = UnionBuilder::new_dense(5);
+            builder.append::<Int32Type>("a", 1).unwrap();
```
Comment (tustvold) [inline arrow/src/array/array_union.rs:977]: Could conceivably rejig these methods to share the append code, but don't feel strongly

**Review by tustvold — APPROVED** [review]

File: arrow/src/array/array_union.rs (hunk 1 above)
Comment (viirya) [reply arrow/src/array/array_union.rs:386]: Hm? I need use `RecordBatch`, otherwise:

```
error[E0412]: cannot find type `RecordBatch` in this scope
   --> arrow/src/array/array_union.rs:994:49
    |
994 |         fn test_slice_union(record_batch_slice: RecordBatch) {
    |                                                 ^^^^^^^^^^^ not found in this scope
```

Comment (tustvold) [reply arrow/src/array/array_union.rs:386]: Oh, the diff rendered strangely on my phone - made it look like there were no other changes to this file
