### PR TITLE
Fix reading nested lists from parquet files 

### LINKED ISSUE #1515: cannot read parquet file
**Describe the bug**
I want to read the parquet I generated, which get the error when I use the "get_row_iter" api, I get this error:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/yzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-11.0.0/src/record/reader.rs:132:52

**To Reproduce**
This is my schema:
message table {
  REPEATED group table_info {
    REQUIRED BYTE_ARRAY name;
    REPEATED group cols {
      REQUIRED BYTE_ARRAY name;
      REQUIRED INT32 type;
      OPTIONAL INT32 length;
    }
    REPEATED group tags {
      REQUIRED BYTE_ARRAY name;
      REQUIRED INT32 type;
      OPTIONAL INT32 length;
    }
  }
}

I can successfully read the parquet if I change the schema to :
message table {
  REPEATED group table_info {
    REQUIRED BYTE_ARRAY name;
    REPEATED group cols {
      REQUIRED BYTE_ARRAY name;
      REQUIRED INT32 type;
      OPTIONAL INT32 length;
    }
  }
}

**Expected behavior**
For my generated parquet file, I can successfully use mac's parquet-tools to read them:
Screen Shot 2022-04-01 at 10 50 44 AM

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1515.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: parquet/src/arrow/array_reader/builder.rs [hunk 1]
```diff
@@ -698,7 +700,12 @@ impl<'a> ArrayReaderBuilder {
                         ArrowType::Struct(fields) => {
                             field = fields.iter().find(|f| f.name() == part)
                         }
-                        ArrowType::List(list_field) => field = Some(list_field.as_ref()),
+                        ArrowType::List(list_field) => match list_field.data_type() {
+                            ArrowType::Struct(fields) => {
+                                field = fields.iter().find(|f| f.name() == part)
+                            }
+                            _ => field = Some(list_field.as_ref()),
+                        },
```
Comment (viirya) [inline parquet/src/arrow/array_reader/builder.rs:708]: This was tested by using the example in #1515. Not sure if it is easy to add a unit test.

Comment (viirya) [reply parquet/src/arrow/array_reader/builder.rs:708]: Shall we put the example parquet file into `parquet-testing` too?

Comment (alamb) [reply parquet/src/arrow/array_reader/builder.rs:708]: I think ideally we would construct a parquet file with this pattern programmatically (aka write it out in a test and then read it back in). 

if that is not possible / feasible, adding an example in parquet-testing would be second best

**Review by alamb — COMMENTED** [review]
Thank you for driving this @viirya

File: parquet/src/arrow/array_reader/builder.rs (hunk 1 above)
Comment (viirya) [reply parquet/src/arrow/array_reader/builder.rs:708]: Sounds good. Let me try to make one. Thanks.

**Comment by viirya** [comment]
Interesting, I cannot reproduce the Parquet file by writing a simple Parquet file in test.

The main difference is:

For the original Parquet file, the path to the `name` column is:

```
 ["table", "table_info", "name"]
```

Because `table_info` is a list of struct, so we need the change in this PR.

I use the same message type to write out a Parquet file in test. But when I read it back. For the same `name` column, the column path is different:

```
parts: ["arrow_schema", "table_info", "table_info", "name"]
```

For the first `table_info`, `get_arrow_field` will simply pick up same name field from arrow schema, which is the list field. Then moving to next `table_info`, it picks the struct field from there. Next part is `name`, and current field is struct, it can get the correct field.

I checked the arrow schema for the Parquet file and the one I wrote in test, they are the same. So I am currently not sure why the column paths for same column `name` could be different for two cases.

**Comment by viirya** [comment]
Let me dig why there is the difference.

File: parquet/src/arrow/array_reader/builder.rs [hunk 2]
```diff
@@ -321,70 +323,71 @@ impl<'a> TypeVisitor<Option<Box<dyn ArrayReader>>, &'a ArrayReaderBuilderContext
             _ => (),
         }
 
-        let item_reader = self
-            .dispatch(item_type.clone(), &new_context)
-            .unwrap()
-            .unwrap();
```
Comment (viirya) [inline parquet/src/arrow/array_reader/builder.rs:327]: When a column is not included, `dispatch` will return None. `unwrap` here will get unexpected error.

File: parquet/src/arrow/array_reader.rs [hunk 3]
```diff
@@ -2268,4 +2272,67 @@ mod tests {
...
+                    OPTIONAL INT32 length;
+                }
+                REPEATED group tags {
+                    REQUIRED BYTE_ARRAY name;
+                    REQUIRED INT32 type;
+                    OPTIONAL INT32 length;
+                }
+            }
+        }
+        ";
```
Comment (viirya) [inline parquet/src/arrow/array_reader.rs:2295]: This message type is copied from the issue.

File: parquet/src/arrow/array_reader.rs [hunk 4]
```diff
@@ -2268,4 +2272,67 @@ mod tests {
             &PrimitiveArray::<ArrowInt32>::from(vec![Some(3), Some(4)])
         );
     }
+
+    #[test]
+    fn test_nested_lists() {
```
Comment (alamb) [inline parquet/src/arrow/array_reader.rs:2277]: I tested running this test without the rest of the code change in this PR and I got:

```
---- arrow::array_reader::tests::test_nested_lists stdout ----
thread 'arrow::array_reader::tests::test_nested_lists' panicked at 'called `Option::unwrap()` on a `None` value', parquet/src/arrow/array_reader/builder.rs:327:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File: parquet/src/arrow/array_reader/builder.rs (hunk 2 above)
Comment (alamb) [reply parquet/src/arrow/array_reader/builder.rs:327]: 👍  I found using a whitespace blind diff made the changes easier to understand: https://github.com/apache/arrow-rs/pull/1517/files?w=1

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @viirya

**Comment by alamb** [comment]
Thanks @viirya

**Comment by viirya** [comment]
Thank you @alamb !
