### PR TITLE
Fix decoding long and/or padded RLE data (#3029) (#3035)

### LINKED ISSUE #3029: RLEDecoder::get_batch_with_dict may panic on bit-packed runs longer than 1024
**Describe the bug**

Reading a specific parquet file triggers: thread 'main' panicked at 'index out of bounds: the len is 1024 but the index is 1024', /Users/wolfvollprecht/Programs/arrow-rs/parquet/src/encodings/rle.rs:492:25

The max-index size computation is wrong.

### LINKED ISSUE #3035: RLEDecoder Panics on Null Padded Pages
**Describe the bug**

Some decoders add 0-padding at the end of an RLE page. This is technically not spec-compliant, but the C++ decoder has [logic](https://github.com/apache/arrow/blob/8074496cb41bc8ec8fe9fc814ca5576d89a6eb94/cpp/src/arrow/util/rle_encoding.h#L653) to handle this case, so we should do likewise

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3029 
Closes #3035

# Rationale for this change
 

See tickets

# What changes are included in this PR?

Fixes two bugs around decoding RLE data that prevent handling `https://s3.amazonaws.com/anaconda-package-data/conda/monthly/2022/2022-05.parquet`

This appears to be a file written by fastparquet, which might explain why it has a somewhat different interpretation of the parquet specification as some other writers.

# Are there any user-facing changes?

### CODE REVIEW

File: parquet/src/encodings/rle.rs [hunk 1]
```diff
@@ -473,13 +473,18 @@ impl RleDecoder {
...
                     self.bit_reader.as_mut().expect("bit_reader should be set");
 
-                let mut num_values =
-                    cmp::min(max_values - values_read, self.bit_packed_left as usize);
-
-                num_values = cmp::min(num_values, index_buf.len());
                 loop {
-                    num_values = bit_reader.get_batch::<i32>(
-                        &mut index_buf[..num_values],
+                    let to_read = index_buf
```
Comment (tustvold) [inline parquet/src/encodings/rle.rs:477]: This is the fix for #3029

File: parquet/src/encodings/rle.rs [hunk 2]
```diff
@@ -509,6 +514,12 @@ impl RleDecoder {
         let bit_reader = self.bit_reader.as_mut().expect("bit_reader should be set");
 
         if let Some(indicator_value) = bit_reader.get_vlq_int() {
+            // fastparquet adds padding to the end of pages. This is not spec-compliant
```
Comment (tustvold) [inline parquet/src/encodings/rle.rs:517]: This is the fix for #3035

Comment (tustvold) [reply parquet/src/encodings/rle.rs:517]: Looking at the fastparquet code, the bitpacking logic appears like it would pad to 4-byte boundaries as a consequence of it using a 32-bit accumulator

https://github.com/dask/fastparquet/blob/main/fastparquet/cencoding.pyx#L277

**Comment by wolfv** [comment]
Awesome, thanks for tackling this!

**Comment by wolfv** [comment]
I tested this locally for our project and it appears to work fine :)

**Review by alamb — APPROVED** [review]
The code and changes make sense to me, and  I verified that without the code changes the tests fail like:

```
---- encodings::rle::tests::test_rle_padded stdout ----
thread 'encodings::rle::tests::test_rle_padded' panicked at 'assertion failed: self.current_value.is_some()', parquet/src/encodings/rle.rs:518:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: parquet::encodings::rle::RleDecoder::reload
             at ./src/encodings/rle.rs:518:17
   4: parquet::encodings::rle::RleDecoder::get_batch
             at ./src/encodings/rle.rs:408:24
   5: parquet::encodings::rle::tests::test_rle_padded
             at ./src/encodings/rle.rs:922:17
   6: parquet::encodings::rle::tests::test_rle_padded::{{closure}}
             at ./src/encodings/rle.rs:904:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- encodings::rle::tests::test_long_run stdout ----
thread 'encodings::rle::tests::test_long_run' panicked at 'index out of bounds: the len is 2002 but the index is 2002', parquet/src/encodings/rle.rs:491:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:84:5
   3: parquet::encodings::rle::RleDecoder::get_batch_with_dict
             at ./src/encodings/rle.rs:491:25
   4: parquet::encodings::rle::tests::test_long_run
             at ./src/encodings/rle.rs:965:17
   5: parquet::encodings::rle::tests::test_long_run::{{closure}}
             at ./src/encodings/rle.rs:935:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    encodings::rle::tests::test_long_run
    encodings::rle::tests::test_rle_padded

test result: FAILED. 577 passed; 2 failed; 1 ignored; 0 measured; 0 filtered out; finished in 11.52s

error: test failed, to rerun pass `-p parquet --lib`
```

However, if someone else with some expertise has time to review that would be great.

**Review by sunchao — APPROVED** [review]
LGTM too
