### PR TITLE
Verify ArrayData::data_type compatible in PrimitiveArray::from

### LINKED ISSUE #3439: PrimitiveArray from ArrayData Unsound For IntervalArray
**Describe the bug**

Creating a `PrimitiveArray` from `ArrayData` validates that the `DataType` has the same discriminant as expected. For almost all types this is sufficient, with exception to `DataType::Interval`.

This is because `DataType::Interval` has a different backing primitive depending on the value of `IntervalUnit`

**To Reproduce**

```
#[test]
fn test_invalid_interval_type() {
    let array = IntervalDayTimeArray::from(vec![1, 2, 3]);
    let _ = IntervalMonthDayNanoArray::from(array.into_data());
}
```

The above should panic, but doesn't

**Expected behavior**

**Additional context**

This is a follow on to #2834

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3439

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-array/src/array/primitive_array.rs [hunk 1]
```diff
@@ -2205,4 +2218,13 @@ mod tests {
         let c = array.unary_mut(|x| x * 2 + 1).unwrap();
         assert_eq!(c, Int32Array::from(vec![Some(11), Some(15), None]));
     }
+
+    #[test]
+    #[should_panic(
+        expected = "PrimitiveArray expected ArrayData with type Interval(MonthDayNano) got Interval(DayTime)"
+    )]
+    fn test_invalid_interval_type() {
+        let array = IntervalDayTimeArray::from(vec![1, 2, 3]);
```
Comment (tustvold) [inline arrow-array/src/array/primitive_array.rs:2227]: This change will also prevent coercing `TimeUnit`, etc... but this is the only one with potential soundness implications

**Review by viirya — APPROVED** [review]
