### PR TITLE
Ensure addition/multiplications in when allocating buffers don't overflow

### LINKED ISSUE #5412: OOB access in `Buffer::from_iter`
**Describe the bug**
When overflow checks are disabled, `<Buffer as FromIterator<T>>::from_iter` may construct `MutableBuffer` with a smaller capacity due to wrap-around arithmetic, causing out-of-bounds write.
<https://github.com/apache/arrow-rs/blob/5bb226cc791adfd6903497cbb8fcd8285fe6f298/arrow-buffer/src/buffer/immutable.rs#L424-L438>
<https://github.com/apache/arrow-rs/blob/5bb226cc791adfd6903497cbb8fcd8285fe6f298/arrow-buffer/src/buffer/mutable.rs#L71-L72>
<https://github.com/apache/arrow-rs/blob/5bb226cc791adfd6903497cbb8fcd8285fe6f298/arrow-buffer/src/util/bit_util.rs#L32-L43>

**To Reproduce**
The following code segfaults in release build:

```rust
// Trigger wrap-wround in `Buffer::from_iter`
arrow_buffer::buffer::Buffer::from_iter(
    std::iter::repeat(42u64).take(usize::MAX / std::mem::size_of::<u64>() + 1));
```

```rust
// Trigger wrap-wround in `bit_util::round_upto_multiple_of_64`
arrow_buffer::buffer::Buffer::from_iter(
    std::iter::repeat(42u64).take(usize::MAX / std::mem::size_of::<u64>()));
```

**Expected behavior**
Panicking, aborting, or successful UB-free execution

**Additional context**

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5412

# Rationale for this change
 

Ensure addition and multiplication saturate instead of overflowing (especially for release builds). This will ensure we panic instead of segfaulting.

# What changes are included in this PR?

# Are there any user-facing changes?

Update doc on panic behaviour

### CODE REVIEW

File: arrow-buffer/src/buffer/mutable.rs [hunk 1]
```diff
@@ -67,10 +67,16 @@ impl MutableBuffer {
...
+    /// # Panics
+    ///
+    /// If `capacity`, when rounded up to a multiple of 64, is larger than `isize::MAX`
+    /// then this function will panic. Avoid allocating capacities above this limit.
     #[inline]
     pub fn with_capacity(capacity: usize) -> Self {
         let capacity = bit_util::round_upto_multiple_of_64(capacity);
-        let layout = Layout::from_size_align(capacity, ALIGNMENT).unwrap();
+        let layout = Layout::from_size_align(capacity, ALIGNMENT)
+            .expect("failed to create layout for MutableBuffer");
```
Comment (Jefffrey) [inline arrow-buffer/src/buffer/mutable.rs:79]: Panic should come here. Add some documentation around this, and switch to expect for a slightly better message

File: arrow-buffer/src/util/bit_util.rs [hunk 2]
```diff
@@ -117,6 +117,8 @@ mod tests {
         assert_eq!(64, round_upto_multiple_of_64(64));
         assert_eq!(128, round_upto_multiple_of_64(65));
         assert_eq!(192, round_upto_multiple_of_64(129));
+        // TODO: investigate why this is failing
+        // assert_eq!(usize::MAX, round_upto_multiple_of_64(usize::MAX));
```
Comment (Jefffrey) [inline arrow-buffer/src/util/bit_util.rs:121]: Found this edge case, don't think it's relevant to the original issue but might be interesting to check out (since looks like function will round down if `num` is large enough)

Comment (Jefffrey) [reply arrow-buffer/src/util/bit_util.rs:121]: On the other hand, without the saturating add it would've just overflowed so would get an ever lower number (in release mode at least)

I think the bit manipulation involved doesn't handle it well when input is maxed out

Comment (Jefffrey) [reply arrow-buffer/src/util/bit_util.rs:121]: > Or check the value is sufficiently small at the start?

Probably this, as `usize::MAX` would have no greater value that is also a multiple of two. I'll add this

**Comment by Jefffrey** [comment]
I removed the panic doc as I figured that even if they supply the maximum capacity to not cause a panic, it would probably cause an OOM considering the amount of memory they'd probably be trying to allocate... not to mention the max amount would actually depend on the ALIGNMENT which varies by arch. Let me know if it would be better to have this doc in spite of that :thinking:

File: arrow-buffer/src/util/bit_util.rs [hunk 3]
```diff
@@ -39,7 +39,12 @@ pub fn round_upto_multiple_of_64(num: usize) -> usize {
 /// be a power of 2.
 pub fn round_upto_power_of_2(num: usize, factor: usize) -> usize {
     debug_assert!(factor > 0 && (factor & (factor - 1)) == 0);
-    (num + (factor - 1)) & !(factor - 1)
+    let rounded = (num.saturating_add(factor - 1)) & !(factor - 1);
```
Comment (jhorstmann) [inline arrow-buffer/src/util/bit_util.rs:42]: I would maybe go with `checked_add` instead of saturation + assert:

```
(num.checked_add(factor - 1).expect("failed to round to next power of 2")) & !(factor - 1)
```

The formatting of the assert message bloats the assembly a little bit. This is probably not an issue, but might interact with inlining decisions via `MutableBuffer::push -> MutableBuffer::reserve -> round_upto_multiple_of_64`.

**Comment by jhorstmann** [comment]
Looks good, nice test.

File: arrow-buffer/src/util/bit_util.rs (hunk 3 above)
Comment (Jefffrey) [reply arrow-buffer/src/util/bit_util.rs:42]: Yeah this makes sense, thanks will try it out :+1:
