### PR TITLE
Split object_store into separate workspace

### LINKED ISSUE #3414: Release tarballs can not be build standalone
**Describe the bug**
As we saw in https://github.com/apache/arrow-rs/pull/3413, the contents of the arrow-rs release tarballs do not work when used alone. When uploaded to crates.io things work fine as crates.io modifies the `Cargo.toml` files. 

Since almost everyone uses the crates.io distribution this issue is likely not a big deal. 

**To Reproduce**
1. Download a tarball such as https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-rs-30.0.0-rc1/apache-arrow-rs-30.0.0.tar.gz
2. try to build the parquet parquet crate: `(cd parquet && cargo build)`

This will fail with a message like

```
error: failed to get `object_store` as a dependency of package `parquet v30.0.0 (/tmp/arrow/parquet)`
```

**Expected behavior**
The build should work

**Additional context**

I think (and @tustvold  suggested) is that we should apply the fix in https://github.com/apache/arrow-rs/pull/3413 to the tarball creation rather than during verification

So that would mean  something like rewriting

```toml
object_store = { version = "0.5", path = "../object_store", default-features = false, optional = true }
```

To remove the `path = "../object_store"`

```toml
object_store = { version = "0.5", default-features = false, optional = true }
```

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Relates to #4030
Closes #3414

# Rationale for this change
 

`object_store` follows a separate release cycle and is distributed independently, having it in the same workspace creates friction and requires workarounds that then cause their own issues. Simpler to just keep it separate.

# What changes are included in this PR?

Splits object_store into its own workspace

# Are there any user-facing changes?

### CODE REVIEW

File: dev/release/verify-release-candidate.sh [hunk 1]
```diff
@@ -105,26 +105,15 @@ test_source_distribution() {
...
-  (cd arrow && cargo build && cargo test)
-  (cd arrow-flight && cargo build && cargo test)
-  # To avoid https://github.com/apache/arrow-rs/issues/3410,
-  # remove path reference from parquet:
-  # object_store = { version = "0.5", path = "../object_store", default-features = false, optional = true }
-  # object_store = { version = "0.5", default-features = false, optional = true }
-  sed -i -e 's/\(^object_store.*\)\(path = ".*", \)/\1/g' parquet/Cargo.toml
-  (cd parquet && cargo build && cargo test)
-  (cd parquet_derive && cargo build && cargo test)
+  cargo test --all
```
Comment (tustvold) [inline dev/release/verify-release-candidate.sh:116]: As an added bonus this is a more thorough verification, as it will run the tests for the child crates

File: dev/release/create-tarball.sh [hunk 2]
```diff
@@ -117,14 +117,11 @@ echo "---------------------------------------------------------"
...
 # the files in the tarball are prefixed with {tag} (e.g. 4.0.1)
-# use --delete to filter out:
-# 1. `object_store` files
-# 2. Workspace `Cargo.toml` file (which refers to object_store)
+# use --delete to filter out `object_store` files
 mkdir -p ${distdir}
 (cd "${SOURCE_TOP_DIR}" && \
      git archive ${release_hash} --prefix ${release}/ \
          | $tar --delete ${release}/'object_store' \
-         | $tar --delete ${release}/'Cargo.toml' \
```
Comment (tustvold) [inline dev/release/create-tarball.sh:127]: Following #3936 this causes issues, as it removes the workspace from which the properties are derived

File: parquet/Cargo.toml [hunk 3]
```diff
@@ -43,7 +43,8 @@ arrow-data = { workspace = true, optional = true }
 arrow-schema = { workspace = true, optional = true }
 arrow-select = { workspace = true, optional = true }
 arrow-ipc = { workspace = true, optional = true }
-object_store = { version = "0.5", path = "../object_store", default-features = false, optional = true }
+# Intentionally not a path dependency as object_store is released separately
+object_store = { version = "0.5", default-features = false, optional = true }
```
Comment (tustvold) [inline parquet/Cargo.toml:47]: This fixes #3414

File: dev/release/verify-release-candidate.sh (hunk 1 above)
Comment (tustvold) [reply dev/release/verify-release-candidate.sh:116]: I do wonder if we should be passing more features to this, but this is strictly better than it was before

**Review by alamb — APPROVED** [review]
makes sense to me -- thank you @tustvold
