### PR TITLE
Support StringViewArray interop with python: fix lingering C Data Interface issues for *ViewArray

### LINKED ISSUE #6366: Exporting Binary/Utf8View from arrow-rs to pyarrow fails
**Describe the bug**
Exporting binaryview arrow to pyarrow fails with 

`Expected at least 3 buffers for imported type binary_view, ArrowArray struct has 2`

**To Reproduce**
Construct binaryview array and export it over c data interface to pyarrow 

**Expected behavior**
Export should succeed without error

**Additional context**
I think there's ambiguity in the spec https://github.com/apache/arrow/issues/43989. However, regardless of that issue it seems that export binaryview array has to do a bit extra work to produce buffer lengths

### PR DESCRIPTION
**Pull request by a10y**
# Which issue does this PR close?

Closes #6366 

# Rationale for this change

Previously, StringViewArrays and BinaryViewArrays sent to PyArrow will panic.

If you use the updated `test_to_pyarrow()` from this PR without the additional changes, it will fail.

# What changes are included in this PR?

The specification states that the C Data Interface format for StringViewArray and BinaryViewArray includes an extra `variadic_buffer_sizes` buffer at the end of the various output values.

We were not including that before. There was a prior PR to add it for the IPC format, but not for the C Data Interface.

I cribbed the relevant C++ code for this: https://github.com/apache/arrow/blob/ab0a40ee34217070f14027776682074c55d0b507/cpp/src/arrow/c/bridge.cc#L584-L609

# Are there any user-facing changes?

It should now be possible to share StringViewArray and BinaryViewArray over C Data Interface.

### CODE REVIEW

File: arrow-buffer/src/buffer/immutable.rs [hunk 1]
```diff
@@ -203,7 +203,9 @@ impl Buffer {
     pub fn advance(&mut self, offset: usize) {
         assert!(
             offset <= self.length,
-            "the offset of the new Buffer cannot exceed the existing length"
+            "the offset of the new Buffer cannot exceed the existing length: offset={} length={}",
```
Comment (alamb) [inline arrow-buffer/src/buffer/immutable.rs:206]: 👍

File: arrow-array/src/ffi.rs [hunk 2]
```diff
@@ -373,13 +380,30 @@ impl<'a> ImportedArrowArray<'a> {
 
     /// returns all buffers, as organized by Rust (i.e. null buffer is skipped if it's present
     /// in the spec of the type)
-    fn buffers(&self, can_contain_null_mask: bool) -> Result<Vec<Buffer>> {
+    fn buffers(&self, can_contain_null_mask: bool, variadic: bool) -> Result<Vec<Buffer>> {
```
Comment (alamb) [inline arrow-array/src/ffi.rs:383]: Can you please add a unit test for this code similar to `round_trip_string_array` to match the existing test coverage that round trips 3 string view arrays:
1. No variadic buffers (all strings short (less than 12 bytes) )
2. 1 variadic buffer (at least one long string (greater than 12 bytes))
3. 2 variadic buffers (example below)

File: arrow/tests/pyarrow.rs [hunk 3]
```diff
@@ -27,7 +28,9 @@ fn test_to_pyarrow() {
 
     let a: ArrayRef = Arc::new(Int32Array::from(vec![1, 2]));
     let b: ArrayRef = Arc::new(StringArray::from(vec!["a", "b"]));
-    let input = RecordBatch::try_from_iter(vec![("a", a), ("b", b)]).unwrap();
+    // The "very long string" will not be inlined, and force the creation of a data buffer.
```
Comment (alamb) [inline arrow/tests/pyarrow.rs:31]: Could you also test this with two other StringViewArrays so the total coverage is:

1. No variadic buffers (all strings short (less than 12 bytes) ) -- currently not covered
2. 1 variadic buffer (at least one long string (greater than 12 bytes)) -- covered
3. 2 variadic buffers (example below)

You can create a StringViewArray with multiple variadic buffers via `with_fixed_block_size` like this:

https://github.com/apache/arrow-rs/blob/4295d37b8e2737fe7ef9870effa1c2053c674e34/arrow-array/src/builder/generic_bytes_view_builder.rs#L558-L575

**Review by alamb — COMMENTED** [review]
Thank you @a10y  -- this code looks great to me. I am not a low level expert in this area but I read it closely and it looks good. I found the code clear and easy to follow and the comments really helped. 🏆 

I think the PR needs a few more tests (I commented on which below) but otherwise is ready to go.

File: arrow/tests/pyarrow.rs (hunk 3 above)
Comment (alamb) [reply arrow/tests/pyarrow.rs:31]: Also, can you please add a test for `BinaryViewArray as well?

File: arrow-array/src/ffi.rs (hunk 2 above)
Comment (alamb) [reply arrow-array/src/ffi.rs:383]: Also for BinaryViewArray as well, please 🙏

Comment (a10y) [reply arrow-array/src/ffi.rs:383]: Done!

File: arrow/tests/pyarrow.rs (hunk 3 above)
Comment (a10y) [reply arrow/tests/pyarrow.rs:32]: Done!

**Comment by a10y** [comment]
@alamb I believe I've implemented all of the requested tests, thanks for reviewing!

File: arrow-array/src/ffi.rs [hunk 4]
```diff
@@ -1551,4 +1602,93 @@ mod tests_from_ffi {
...
+                builder.append_value(T::Native::from_str("inlined"));
+                let block_id =
+                    builder.append_block(Buffer::from("non-inlined-string-buffer".as_bytes()));
+                builder.try_append_view(block_id, 0, 25).unwrap();
+                builder.finish()
+            };
+            assert_eq!(mixed_one_variadic.data_buffers().len(), 1);
+            run_test_case!(mixed_one_variadic);
+
+            // inlined + non-inlined, 2 variadic buffers.
```
Comment (alamb) [inline arrow-array/src/ffi.rs:1674]: 👍

File: arrow/tests/pyarrow.rs [hunk 5]
```diff
@@ -40,3 +44,66 @@ fn test_to_pyarrow() {
...
+            RecordBatch::from_pyarrow_bound(py_records.bind(py))
+        })
+        .unwrap();
+
+        assert_eq!(input, res);
+    }
+}
+
+fn binary_view_column(num_variadic_buffers: usize) -> BinaryViewArray {
+    let long_scalar = b"but soft what light through yonder window breaks".as_slice();
```
Comment (alamb) [inline arrow/tests/pyarrow.rs:76]: 👍  nice choice

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @a10y

**Comment by alamb** [comment]
Thanks again @a10y
