### PR TITLE
Fix decimals min max statistics

### LINKED ISSUE #1532: Incorrect min/max statistics for decimals with byte-array notation
**Describe the bug**
When dealing with decimals built with byte-array notation, the min/max comparison should be based on the logical type and not on the physical type.
Integers that are provided as converted types and without specifying the logical type, unsigned comparison should be applied.

**To Reproduce**
1) Decimals with byte-array notation: 
a. Create a decimal column (as logical type) with a fixed length byte array type.
b. Write the following values to the column: [2.11, 3.22, 4.33, -5.44]
2) Integers specified using the converted type only (No logical type provided): 
a. Create an integer column (as converted type) with an unsigned int physical type.
b. Write the following values to the column: [1, 2, 3, -1] 

**Expected behavior**
1) Reading the statistics of the first row group in the column with the decimal type:
Expected: min=-5.44, max=4.33
Actual: min=2.11, max=-5.44
2) Reading the statistics of the first row group in the column with the integer:
Expected: min=-1, max=3
Actual: min=1, max=-1

**Additional context**

### PR DESCRIPTION
**Pull request by atefsawaed**
# Which issue does this PR close?

Closes #1532.

# Rationale for this change
 

# What changes are included in this PR?

Added a suitable comparator for Decimals that are built with byte arrays.

# Are there any user-facing changes?
No.

### CODE REVIEW

File: parquet/src/column/writer.rs [hunk 1]
```diff
@@ -1006,6 +1057,42 @@ impl<T: DataType> ColumnWriterImpl<T> {
...
+            ConvertedType::UINT_8
+            | ConvertedType::UINT_16
+            | ConvertedType::UINT_32
+            | ConvertedType::UINT_64 => {
+                return a.as_u64().unwrap() > b.as_u64().unwrap();
+            }
+            _ => {}
+        };
+
+        if let Some(LogicalType::DECIMAL(_)) = self.descr.logical_type() {
```
Comment (viirya) [inline parquet/src/column/writer.rs:1071]: A few compilation errors:

```
error[E0599]: no variant or associated item named `DECIMAL` found for enum `basic::LogicalType` in the current scope
    --> parquet/src/column/writer.rs:1071:34
     |
1071 |         if let Some(LogicalType::DECIMAL(_)) = self.descr.logical_type() {
```

File: parquet/src/column/writer.rs [hunk 2]
```diff
@@ -2153,4 +2296,49 @@ mod tests {
...
+
+    /// Returns descriptor for Decimal type with primitive column.
+    fn get_test_decimals_column_descr<T: DataType>(
+        max_def_level: i16,
+        max_rep_level: i16,
+    ) -> ColumnDescriptor {
+        let path = ColumnPath::from("col");
+        let tpe = SchemaType::primitive_type_builder("col", T::get_physical_type())
+            .with_length(16)
+            .with_logical_type(Some(LogicalType::DECIMAL(parquet_format::DecimalType::new(2, 3))))
```
Comment (viirya) [inline parquet/src/column/writer.rs:2337]:
```suggestion
            .with_logical_type(Some(LogicalType::Decimal {
                scale: 2,
                precision: 3,
            }))
```

File: parquet/src/column/writer.rs [hunk 3]
```diff
@@ -998,6 +998,57 @@ impl<T: DataType> ColumnWriterImpl<T> {
         }
     }
 
+    fn compare_greater_byte_array_decimals(&self, a: &[u8], b: &[u8]) -> bool {
```
Comment (viirya) [inline parquet/src/column/writer.rs:1001]: Would be nice if we can have some tests for this function.

File: parquet/src/column/writer.rs [hunk 4]
```diff
@@ -1006,6 +1057,42 @@ impl<T: DataType> ColumnWriterImpl<T> {
...
+
+        match self.descr.converted_type() {
+            ConvertedType::UINT_8
+            | ConvertedType::UINT_16
+            | ConvertedType::UINT_32
+            | ConvertedType::UINT_64 => {
+                return a.as_u64().unwrap() > b.as_u64().unwrap();
+            }
+            _ => {}
+        };
```
[the remark this answers is not in the document]
Comment (atefsawaed) [reply parquet/src/column/writer.rs:1069]: No. This is to capture Integers specified using their converted type only (No logical type provided).

File: parquet/src/column/writer.rs (hunk 3 above)
Comment (viirya) [reply parquet/src/column/writer.rs:1001]: I don't see it needs to access `self`, so maybe you can move it out of `ColumnWriterImpl`?

File: parquet/src/column/writer.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (viirya) [reply parquet/src/column/writer.rs:1069]: So this is another issue?

[the remark this answers is not in the document]
Comment (viirya) [reply parquet/src/column/writer.rs:1069]: Oh, I saw you have listed it in the issue description. nvm

Maybe you can mention it in the PR title too.

[the remark this answers is not in the document]
Comment (viirya) [reply parquet/src/column/writer.rs:1069]: Is it possible to add test for this too?

File: parquet/src/column/writer.rs (hunk 3 above)
Comment (atefsawaed) [reply parquet/src/column/writer.rs:1001]: Yes, I will move it and write a test for it.

File: parquet/src/column/writer.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (atefsawaed) [reply parquet/src/column/writer.rs:1069]: Yes.

**Comment by HaoYang670** [comment]
Hi @viirya, could you please help to trigger the CI processes? Thank you!

File: parquet/src/column/writer.rs [hunk 5]
```diff
@@ -2153,4 +2346,94 @@ mod tests {
...
+            }))
+            .with_scale(2)
+            .with_precision(3)
+            .build()
+            .unwrap();
+        ColumnDescriptor::new(Arc::new(tpe), max_def_level, max_rep_level, path)
+    }
+
+    /// Returns column writer for UINT32 Column (Provided as ConvertedType without specifying the LogicalType).
+    fn get_test_unsigned_int_given_as_converted_column_writer<T: DataType>(
```
Comment (viirya) [inline parquet/src/column/writer.rs:2399]: Hmm, where is this used?

Comment (atefsawaed) [reply parquet/src/column/writer.rs:2389]: Sorry, I missed it. I am using it now.

File: parquet/src/column/writer.rs [hunk 6]
```diff
@@ -1006,6 +1006,41 @@ impl<T: DataType> ColumnWriterImpl<T> {
...
+            | ConvertedType::UINT_16
+            | ConvertedType::UINT_32
+            | ConvertedType::UINT_64 => {
+                return a.as_u64().unwrap() > b.as_u64().unwrap();
+            }
+            _ => {}
+        };
+
+        if let Some(LogicalType::Decimal { .. }) = self.descr.logical_type() {
+            match self.descr.physical_type() {
```
Comment (sunchao) [inline parquet/src/column/writer.rs:1021]: Decimals can be represented via `INT32` and `INT64` too.

Comment (atefsawaed) [reply parquet/src/column/writer.rs:1021]: That's right. In this case, signed comparison of the integer values produces the correct ordering and will be done in line 1044.

Comment (sunchao) [reply parquet/src/column/writer.rs:1021]: Ah you are right.

File: parquet/src/column/writer.rs [hunk 7]
```diff
@@ -1049,6 +1084,54 @@ fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
...
+
+    let first_a: u8 = a[0];
+    let first_b: u8 = b[0];
+
+    // We can short circuit for different signed numbers or
+    // for equal length bytes arrays that have different first bytes.
+    // The equality requirement is necessary for sign extension cases.
+    // 0xFF10 should be equal to 0x10 (due to big endian sign extension).
+    if (0x80 & first_a) != (0x80 & first_b)
+        || (a_length == b_length && first_a != first_b)
```
Comment (sunchao) [inline parquet/src/column/writer.rs:1104]: Hmm why we need this second condition?

File: parquet/src/column/writer.rs [hunk 8]
```diff
@@ -1049,6 +1084,54 @@ fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
...
+
+    // When the lengths are unequal and the numbers are of the same
+    // sign we need to do comparison by sign extending the shorter
+    // value first, and once we get to equal sized arrays, lexicographical
+    // unsigned comparison of everything but the first byte is sufficient.
+
+    let extension: u8 = if (first_a as i8) < 0 { 0xFF } else { 0 };
+
+    if a_length != b_length {
+        let not_equal: Option<bool> = if a_length > b_length {
```
Comment (sunchao) [inline parquet/src/column/writer.rs:1117]: why this is a `Option`? seems it is always `Some`.

File: parquet/src/column/writer.rs [hunk 9]
```diff
@@ -2153,4 +2336,94 @@ mod tests {
...
+                precision: 3,
+            }))
+            .with_scale(2)
+            .with_precision(3)
+            .build()
+            .unwrap();
+        ColumnDescriptor::new(Arc::new(tpe), max_def_level, max_rep_level, path)
+    }
+
+    /// Returns column writer for UINT32 Column (Provided as ConvertedType without specifying the LogicalType).
```
Comment (sunchao) [inline parquet/src/column/writer.rs:2388]: nit: can we limit line length to 90 characters?

File: parquet/src/column/writer.rs [hunk 10]
```diff
@@ -1049,6 +1084,54 @@ fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
...
+            Some((&a[0..lead_length]).iter().any(|&x| x != extension))
+        } else {
+            let lead_length = b_length - a_length;
+            Some((&b[0..lead_length]).iter().any(|&x| x != extension))
+        };
+
+        if not_equal.is_some() && not_equal.unwrap() {
+            let negative_values: bool = (first_a as i8) < 0;
+            let a_longer: bool = a_length > b_length;
+            return negative_values != a_longer;
```
Comment (sunchao) [inline parquet/src/column/writer.rs:1128]: personally I feel it's easier to read via:
```rust
return if negative_values { !a_longer } else { a_longer };
```

File: parquet/src/column/writer.rs [hunk 11]
```diff
@@ -1049,6 +1084,54 @@ fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
     }
 }
 
+/// Signed comparison of bytes arrays
+fn compare_greater_byte_array_decimals(a: &[u8], b: &[u8]) -> bool {
```
Comment (viirya) [inline parquet/src/column/writer.rs:1088]: For reference: Java Parquet's implementation: https://github.com/apache/parquet-mr/blob/06bb358bcf8a0855c54f20122a57a88d9fde16c1/parquet-column/src/main/java/org/apache/parquet/schema/PrimitiveComparator.java#L213

File: parquet/src/column/writer.rs (hunk 7 above)
Comment (atefsawaed) [reply parquet/src/column/writer.rs:1104]: In case of equal length bytes arrays with different first bytes, it is enough to compare the first bytes in order to determine the ordering.

File: parquet/src/column/writer.rs (hunk 11 above)
Comment (atefsawaed) [reply parquet/src/column/writer.rs:1088]: Do you want me to add this as comment?

File: parquet/src/column/writer.rs (hunk 8 above)
Comment (atefsawaed) [reply parquet/src/column/writer.rs:1117]: Updated.

File: parquet/src/column/writer.rs (hunk 11 above)
Comment (viirya) [reply parquet/src/column/writer.rs:1088]: No, I just post it for other reviewers as a reference. But it might also be good to add into the comment.

File: parquet/src/column/writer.rs [hunk 12]
```diff
@@ -1049,6 +1084,54 @@ fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
...
+    let a_length = a.len();
+    let b_length = b.len();
+
+    if a_length == 0 || b_length == 0 {
+        return a_length > 0 && b_length == 0;
+    }
```
Comment (viirya) [inline parquet/src/column/writer.rs:1094]: Hmm, I don't see corresponding code for this in Java's implementation.

File: parquet/src/column/writer.rs [hunk 13]
```diff
@@ -1049,6 +1084,54 @@ fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
...
+    // sign we need to do comparison by sign extending the shorter
+    // value first, and once we get to equal sized arrays, lexicographical
+    // unsigned comparison of everything but the first byte is sufficient.
+
+    let extension: u8 = if (first_a as i8) < 0 { 0xFF } else { 0 };
+
+    if a_length != b_length {
+        let not_equal = if a_length > b_length {
+            let lead_length = a_length - b_length;
+            Some((&a[0..lead_length]).iter().any(|&x| x != extension))
```
Comment (sunchao) [inline parquet/src/column/writer.rs:1119]: nit: you can just do
```
            (&a[0..lead_length]).iter().any(|&x| x != extension)
```
so `not_equal` is not an option.

File: parquet/src/column/writer.rs [hunk 14]
```diff
@@ -1049,6 +1084,54 @@ fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
     }
 }
 
+/// Signed comparison of bytes arrays
+fn compare_greater_byte_array_decimals(a: &[u8], b: &[u8]) -> bool {
+    let a_length = a.len();
+    let b_length = b.len();
+
+    if a_length == 0 || b_length == 0 {
+        return a_length > 0 && b_length == 0;
```
Comment (sunchao) [inline parquet/src/column/writer.rs:1093]: nit: can this just be `return a_length > 0;`?

**Review by sunchao — APPROVED** [review]
LGTM

File: parquet/src/column/writer.rs [hunk 15]
```diff
@@ -1049,6 +1084,54 @@ fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
...
+        };
+
+        if not_equal.unwrap() {
+            let negative_values: bool = (first_a as i8) < 0;
+            let a_longer: bool = a_length > b_length;
+            return if negative_values { !a_longer } else { a_longer };
+        }
+    }
+
+    (a[1..]) > (b[1..])
```
Comment (viirya) [inline parquet/src/column/writer.rs:1132]: If the beginning of the longer buffer equals to the padding, do we need to compare leading bytes again?

**Review by viirya — APPROVED** [review]
Looks good with one question.

File: parquet/src/column/writer.rs (hunk 12 above)
Comment (atefsawaed) [reply parquet/src/column/writer.rs:1094]: Sort of. This is a safe check for empty buffers (that can represent null values).

File: parquet/src/column/writer.rs (hunk 14 above)
Comment (atefsawaed) [reply parquet/src/column/writer.rs:1093]: Yes, good catch!

**Comment by alamb** [comment]
I will hold off on making the 13.0.0 release candidate to include this fix

**Comment by alamb** [comment]
Since the MIRI test takes a while to run (and it will run again on the branch prior to release) I am going to merge this PR in even before it is complete so I can make the release candidate. 🚀

**Comment by alamb** [comment]
Thanks @viirya  and @atefsawaed

**Comment by viirya** [comment]
Thanks @alamb @atefsawaed @sunchao @HaoYang670
