### PR TITLE
Mark `BufferBuilder::new_from_buffer` as unsafe

### LINKED ISSUE #9287: arrow-buffer: Potential Undefined Behavior Reported by Miri
Hi!

We are a team of researchers studying the memory safety problem in Rust. As part of our ongoing research, we performed random testing on arrow-buffer(version:57.2.0) and found that the following code snippet is reported as undefined behavior by Miri:
**Describe the bug**

```rust
#![feature(allocator_api)]
use arrow_buffer::*;
fn main() {
    let v6 = [112, -26, -47];
    let v7 = Vec::from(v6);
    let mut v8 = <buffer::MutableBuffer as std::convert::From<std::vec::Vec::<i32, std::alloc::Global>>>::from(v7);
    let v24 = builder::BufferBuilder::<i128>::new_from_buffer(v8);
    let v25: &'_ builder::BufferBuilder::<i128> = &v24;
    let v26 = builder::BufferBuilder::<i128>::as_slice(v25);
}

```

The error message miri report is as follows:

```rust
error: Undefined Behavior: constructing invalid value: encountered an unaligned reference (required 16 byte alignment but found 8)
   --> /home/chenyl/projects/check_UB/arrow-buffer-57.2.0/src/builder/mod.rs:274:18
    |
274 |         unsafe { std::slice::from_raw_parts(self.buffer.as_ptr() as _, self.len) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE:
    = note: inside `arrow_buffer::BufferBuilder::<i128>::as_slice` at /home/chenyl/projects/check_UB/arrow-buffer-57.2.0/src/builder/mod.rs:274:18: 274:81
note: inside `main`
   --> src/main.rs:9:15
    |
  9 |     let v26 = builder::BufferBuilder::<i128>::as_slice(v25);
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error; 2 warnings emitted
```

It seems that `as_slice` doesn't check the alignment of given buffer, thus causing the undefined behaviour.

**To Reproduce**

1. Copy the code snippet.
2. choose the rust toolchain:nightly-2025-12-06-x86_64-unknown-linux-gnu
3. install miri and run `cargo miri run`

**Expected behavior**

There should not be any undefined behaviour.

**Additional context**

The OS I use is Linux Unbutu.

We’d appreciate it if you could take a look and confirm whether this behavior indicates a real issue, or if it’s a false positive or an expected limitation of Miri.
Thank you very much!

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

- Closes #9287

# Rationale for this change

As identified by the issue, it is possible to use safe APIs to produce an unaligned buffer in `BufferBuilder`.

# What changes are included in this PR?

Mark `BufferBuilder::new_from_buffer` as unsafe since there are alignment invariants that must be upheld to use it correctly.

Also fix some docstrings.

# Are these changes tested?

Marking API unsafe only.

# Are there any user-facing changes?

Yes.

### CODE REVIEW

File: arrow-buffer/src/builder/mod.rs [hunk 1]
```diff
@@ -95,7 +94,11 @@ impl<T: ArrowNativeType> BufferBuilder<T> {
     }
 
     /// Creates a new builder from a [`MutableBuffer`]
-    pub fn new_from_buffer(buffer: MutableBuffer) -> Self {
+    ///
+    /// # Safety
+    ///
+    /// - `buffer` bytes must be aligned to type `T`
+    pub unsafe fn new_from_buffer(buffer: MutableBuffer) -> Self {
```
Comment (Jefffrey) [inline arrow-buffer/src/builder/mod.rs:101]: Main change here

File: arrow-buffer/src/builder/mod.rs [hunk 2]
```diff
@@ -231,12 +228,12 @@ impl<T: ArrowNativeType> BufferBuilder<T> {
     ///
     /// ```
     /// # use arrow_buffer::builder::BufferBuilder;
-    ///
     /// let mut builder = BufferBuilder::<u32>::new(10);
     /// builder.append_n_zeroed(3);
     ///
     /// assert_eq!(builder.len(), 3);
     /// assert_eq!(builder.as_slice(), &[0, 0, 0])
+    /// ```
```
Comment (Jefffrey) [inline arrow-buffer/src/builder/mod.rs:236]: Drive by cleanup of these empty lines in the docstring, see how they currently look like:

Image

Also fix missing closing block syntax here.

File: arrow-buffer/src/builder/mod.rs [hunk 3]
```diff
@@ -402,7 +395,10 @@ impl<T: ArrowNativeType> Extend<T> for BufferBuilder<T> {
 
 impl<T: ArrowNativeType> From<Vec<T>> for BufferBuilder<T> {
     fn from(value: Vec<T>) -> Self {
-        Self::new_from_buffer(MutableBuffer::from(value))
+        let buffer = MutableBuffer::from(value);
+        // SAFETY
+        // - buffer is aligned to T
+        unsafe { Self::new_from_buffer(buffer) }
```
Comment (Jefffrey) [inline arrow-buffer/src/builder/mod.rs:401]: This is the only usage of this API in our codebase, which already upholds the invariants

**Comment by Jefffrey** [comment]
I wouldn't mind making this API private if thats preferred (since its only used in one place) 🤔

File: arrow-buffer/src/builder/mod.rs
Comment (alamb) [inline arrow-buffer/src/builder/mod.rs:65]: I think we have discovered over time that BufferBuilder is typically not as performant as using `Vec` -- but maybe that is a comment for a different day

**Comment by alamb** [comment]
fyi @viirya

File: arrow-buffer/src/builder/mod.rs [hunk 4]
```diff
@@ -78,7 +78,6 @@ impl<T: ArrowNativeType> BufferBuilder<T> {
     ///
     /// ```
     /// # use arrow_buffer::builder::BufferBuilder;
-    ///
```
Comment (viirya) [inline arrow-buffer/src/builder/mod.rs:81]: unnecessary change.

Comment (viirya) [reply arrow-buffer/src/builder/mod.rs:81]: Oh, I saw your comment now.

**Comment by alamb** [comment]
Thanks @viirya and @Jefffrey

**Comment by Jefffrey** [comment]
Thanks @yilin0518 for reporting this

**Comment by alamb** [comment]
I think we should backport this to the 57 release
- https://github.com/apache/arrow-rs/issues/9240

The only thing I worry about is that it is technically a breaking API change

**Comment by Jefffrey** [comment]
I think breaking changes are fine if its for the sake of fixing unsound behaviour 🤔

**Comment by alamb** [comment]
I will plan to back port it then

**Comment by alamb** [comment]
Backport PR: 
- https://github.com/apache/arrow-rs/pull/9312
