### PR TITLE
Use littleendian arrow files for `projection_should_work`

### LINKED ISSUE #1548: Output of `ipc::reader::tests::projection_should_work` fails validation
**Describe the bug**
The `force_validate` check added in https://github.com/apache/arrow-rs/pull/1546 reveals that some array created as part of `projection_should_work` test fails validation. 

It is not clear if the validation is incorrect or something about ipc

**To Reproduce**
Uncomment the
```rust
    #[cfg(not(feature = "force_validate"))]
``` 

And then run the test like:
```shell
cargo test --features=force_validate -p arrow
```

lines for the following tests and the will fail:

```
---- ipc::reader::tests::projection_should_work stdout ----
thread 'ipc::reader::tests::projection_should_work' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Last offset 251658240 of List(Field { name: \"item\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }) is larger than values length 15")', arrow/src/array/data.rs:301:34

```

**Expected behavior**
The tests should pass when force_validate is on

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1548.

# Rationale for this change
 
 

Currently by enabling `force_validate`, the test `projection_should_work` fails.
```
cargo test --features=force_validate -p arrow
```

```
---- ipc::reader::tests::projection_should_work stdout ----
thread 'ipc::reader::tests::projection_should_work' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Last offset 251658240 of List(Field { name: \"item\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }) is larger than values length 15")', arrow/src/array/data.rs:301:34
```

It is because the arrow files used in the test is bigendian, but currently the IPC reader doesn't translate big endian offsets (#859). As that's a known issue, I change the test to use littleendian arrow files, and add a comment there to explain the reason.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/ipc/reader.rs [hunk 1]
```diff
@@ -1108,15 +1108,13 @@ mod tests {
...
     #[test]
-    // https://github.com/apache/arrow-rs/issues/1548
-    #[cfg(not(feature = "force_validate"))]
     fn projection_should_work() {
         // complementary to the previous test
         let testdata = crate::util::test_util::arrow_test_data();
         let paths = vec![
             "generated_interval",
             "generated_datetime",
-            // "generated_map", Err: Last offset 872415232 of Utf8 is larger than values length 52 (https://github.com/apache/arrow-rs/issues/859)
```
Comment (viirya) [inline arrow/src/ipc/reader.rs:1119]: This is also due to bigendian offsets. So I uncomment it too.

**Review by tustvold — APPROVED** [review]
TIL https://arrow.apache.org/docs/format/Columnar.html#byte-order-endianness

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
Thanks for fixing, this was an oversight of me!

**Comment by viirya** [comment]
Thanks @tustvold @Dandandan !
