### PR TITLE
Fix reading dictionaries from nested structs in ipc `StreamReader`

### LINKED ISSUE #1549: Read dictionary from nested struct in ipc stream reader panics
**Describe the bug**
We have an application that reads  ipc stream data, and it panicked while reading a record batch that contains a dictionary in a nested struct:

```
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic_bounds_check
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:84:5
   3: arrow::ipc::reader::read_dictionary
             at /home/pi/src/github/dispanser/arrow-rs/arrow/src/ipc/reader.rs:573:13
   4: arrow::ipc::reader::StreamReader<R>::maybe_next
             at /home/pi/src/github/dispanser/arrow-rs/arrow/src/ipc/reader.rs:983:17
   5: <arrow::ipc::reader::StreamReader<R> as core::iter::traits::iterator::Iterator>::next
             at /home/pi/src/github/dispanser/arrow-rs/arrow/src/ipc/reader.rs:1004:9
```

This is caused by an incorrectly sized `dictionaries_by_field` in the stream reader. PR is ready, opening this for tracking purposes.

**To Reproduce**

Create a record batch containing a nested struct with a dictionary in last position, write to IPC and attempt to read back using `ipc::reader::StreamReader`.

**Expected behavior**

A record batch instead of a panic :)

### PR DESCRIPTION
**Pull request by dispanser**
# Which issue does this PR close?

Closes #1549.

# Rationale for this change
 
Fixing a bug in the ipc stream reader, aligning with the `FileReader` implementation.

# What changes are included in this PR?

The actual bugfix is 4 characters, but this PR also includes a test to reproduce the bug.

# Are there any user-facing changes?

No documetation changes needed.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @dispanser ! @viirya  I wonder if you might have a chance to review this PR?

**Review by viirya — COMMENTED** [review]
I think the fix is correct as we do

```rust
for (i, field) in schema.all_fields().iter().enumerate() {
   dictionaries_by_field[i] = ...
}
```

Actually, in `FileReader`, it does the same:

```rust
let mut dictionaries_by_field = vec![None; schema.all_fields().len()];
```

File: arrow/src/ipc/reader.rs [hunk 1]
```diff
@@ -1394,4 +1407,36 @@ mod tests {
...
+                .into_iter()
+                .collect::<DictionaryArray<datatypes::Int8Type>>(),
+        );
+        let string_array: ArrayRef = Arc::new(StringArray::from(xs.clone()));
+        let struct_array = StructArray::from(vec![
+            (Field::new("f1.1", DataType::Utf8, false), string_array),
+            (
+                Field::new("f1.2_struct", dict.data_type().clone(), false),
+                dict.clone() as ArrayRef,
+            ),
```
Comment (viirya) [inline arrow/src/ipc/reader.rs:1425]: nit: as they are put under `f2_struct`, I guess `f2.1` and `f2.2_struct` look more appropriate?

**Review by viirya — APPROVED** [review]
lgtm, only one minor comment.

**Review by viirya — APPROVED** [review]
lgtm

**Review by tustvold — APPROVED** [review]
Looks good to me, thank you @dispanser
