### PR TITLE
fix: take_run return empty array instead of panic.

### LINKED ISSUE #9179: take_run panics when given empty indicies
**Describe the bug**
`index out of bounds: the len is 0 but the index is 18446744073709551615`

**To Reproduce**
```rust
    #[test]
    #[should_panic(expected = "attempt to subtract with overflow")]
    fn test_take_run_empty_indices() {
        let mut builder = PrimitiveRunBuilder::<Int32Type, Int32Type>::new();
        builder.extend([Some(1), Some(1), Some(2), Some(2)]);
        let run_array = builder.finish();

        let logical_indices: PrimitiveArray<Int32Type> = PrimitiveArray::from(Vec::<i32>::new());

        let _ = take_run(&run_array, &logical_indices);
    }
```

**Expected behavior**
I would expect either an empty array returned or an invalid argument error.

**Additional context**
We have a call to `take_record_batch` that is somehow causing `take_run` to be called with an empty indices array and causing this panic. Note that our call to `take_record_batch` does not use an empty indices array.

### PR DESCRIPTION
**Pull request by thorfour**
If empty indices were passed into take_run it would panic with an index out of bounds error. Instead of panicing return an empty array.

This was happening when a list array with empty entries were taken.

# Which issue does this PR close?

- Closes #9179.

# Rationale for this change

Causing unexpected panics to occur and is different behavior than `take_impl` for other types.

# What changes are included in this PR?

Check to return an empty run array if no indices are given for take, and a unit test that validates this behavior.

# Are these changes tested?

Yes

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by Jefffrey** [comment]
This seems like something we should check once in `take_impl` instead of having it inside `take_run` specifically 🤔

File: arrow-select/src/take.rs [hunk 1]
```diff
@@ -786,6 +786,11 @@ fn take_run<T: RunEndIndexType, I: ArrowPrimitiveType>(
     run_array: &RunArray<T>,
     logical_indices: &PrimitiveArray<I>,
 ) -> Result<RunArray<T>, ArrowError> {
+    if logical_indices.is_empty() {
```
Comment (alamb) [inline arrow-select/src/take.rs]: I agree with @Jefffrey  it would be great to move this check up into `take` 

However, given this PR is better than what is on main, I think we could also merge it as is

**Review by alamb — APPROVED** [review]
Thank you @thorfour  and @Jefffrey

File: arrow-select/src/take.rs (hunk 1 above)
Comment (thorfour) [reply arrow-select/src/take.rs]: I'm happy to move the check up.

Comment (thorfour) [reply arrow-select/src/take.rs]: Moved.

**Comment by thorfour** [comment]
I actually hit another bug with this. The run array that it creates is invalid.

**Comment by thorfour** [comment]
Okay, expanded the unit test to validate the run array created. Added a fix for the empty null run array case.

File: arrow-select/src/take.rs [hunk 2]
```diff
@@ -214,6 +214,10 @@ fn take_impl<IndexType: ArrowPrimitiveType>(
     values: &dyn Array,
     indices: &PrimitiveArray<IndexType>,
 ) -> Result<ArrayRef, ArrowError> {
+    if indices.is_empty() {
+        let data = ArrayData::new_empty(values.data_type());
+        return Ok(Arc::new(make_array(data)));
```
Comment (Jefffrey) [inline arrow-select/src/take.rs]: Can use `new_empty_array` here

- https://docs.rs/arrow/latest/arrow/array/fn.new_empty_array.html

**Review by Jefffrey — APPROVED** [review]
Nice pickup on the zero len issue for run arrays

File: arrow-select/src/take.rs (hunk 2 above)
Comment (thorfour) [reply arrow-select/src/take.rs]: Oh thanks! Will add

**Comment by Jefffrey** [comment]
Thanks @thorfour & @alamb

**Comment by alamb** [comment]
Thanks also @Jefffrey  for helping with reviews in arrow-rs -- there seems to be a really large  number of PRs recently. And as fast as we review and merge them, they keep coming
