### PR TITLE
GH-7686: [Parquet] Fix int96 min/max stats

### LINKED ISSUE #7686: Parquet: Incorrect min/max stats for int96 columns
Parquet write implementation currently emits incorrect min/max stats for int96 timestamp columns. 

**To Reproduce**
Create a parquet file with int96 timestamp columns and observe the statistics.

**Expected behavior**

**Additional context**
See also:
https://github.com/apache/parquet-java/issues/3242

### PR DESCRIPTION
**Pull request by rahulketch**
# Which issue does this PR close?

- Closes #7686

# Rationale for this change

int96 min/max statistics emitted by arrow-rs are incorrect. 

# What changes are included in this PR?

1. Fix the int96 stats
2. Add round-trip test to verify the behavior

# Not included in this PR:
1. Read stats only from known good writers. This will be implemented after a new arrow-rs release. 

# Are there any user-facing changes?
The int96 min/max statistics will be different and correct.

### CODE REVIEW

File: parquet/src/data_type.rs [hunk 1]
```diff
@@ -33,7 +33,7 @@ use crate::util::bit_util::FromBytes;
 
 /// Rust representation for logical type INT96, value is backed by an array of `u32`.
 /// The type only takes 12 bytes, without extra padding.
-#[derive(Clone, Copy, Debug, PartialOrd, Default, PartialEq, Eq)]
+#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
 pub struct Int96 {
     value: [u32; 3],
```
Comment (alkis) [inline parquet/src/data_type.rs:38]: If we store days `i32` and nanos `i64` here, I feel the rest of the code will be a lot simpler.

Comment (mbutrovich) [reply parquet/src/data_type.rs:38]: Doesn't this change the alignment of Int96 from 4 bytes to 8 bytes? What are the broader implications of that, particularly in an array/vector of Int96? Won't there be 4 bytes of padding?

Comment (rahulketch) [reply parquet/src/data_type.rs:38]: I did make the change in this commit, but I am not sure if it's a good approach. @alkis : what do you think?
https://github.com/apache/arrow-rs/pull/7687/commits/6036398bd7a37f6f3bd824c5198fd0e7785f9526

**Comment by etseidl** [comment]
I tend to agree with @emkornfield (https://github.com/apache/parquet-java/pull/3243#issuecomment-2970911010) that this is a bit of putting the cart before the horse. The sort order for `INT96` is currently undefined so statistics should be ignored. I think we need changes to the Parquet spec before proceeding with this.

**Comment by emkornfield** [comment]
I think the plan is to also open a PR for the spec change, IIUC @alkis or @rahulketch will propose a PR there and start discussion thread (this second implementation is to fulfill the two implementation requirement).

**Comment by etseidl** [comment]
> I think the plan is to also open a PR for the spec change, IIUC @alkis or @rahulketch will propose a PR there and start discussion thread (this second implementation is to fulfill the two implementation requirement).

Any objection to marking this "draft" then?

File: parquet/src/data_type.rs (hunk 1 above)
Comment (alkis) [reply parquet/src/data_type.rs:38]: To preserve alignment to 4 byte boundary we can use `#[repr(packed)]` and let the compiler do the bit fiddling.

File: parquet/src/data_type.rs [hunk 2]
```diff
@@ -59,19 +62,25 @@ const NANOSECONDS_IN_DAY: i64 = SECONDS_IN_DAY * NANOSECONDS;
...
     /// Creates new INT96 type struct with no data set.
     pub fn new() -> Self {
-        Self { value: [0; 3] }
+        Self { nanos: 0, days: 0 }
     }
 
-    /// Returns underlying data as slice of [`u32`].
+    /// Returns underlying data as slice of [`u32`] for compatibility with Parquet format
     #[inline]
     pub fn data(&self) -> &[u32] {
```
Comment (alkis) [inline parquet/src/data_type.rs]: Can we change `set_data` to take a slice of `u8`? Then we can read the first 8 bytes as *little* endian nanos and the last 4 bytes as *little* endian julian date. We should remove `data` and make it do the inverse and output into a slice of `u8`.

What is done here today is wrong in terms of endianess.

File: parquet/src/data_type.rs [hunk 3]
```diff
@@ -59,19 +62,25 @@ const NANOSECONDS_IN_DAY: i64 = SECONDS_IN_DAY * NANOSECONDS;
...
-        &self.value
+        // SAFETY: We're reinterpreting the bytes of our struct as [u32; 3]
+        // This is safe because:
+        // 1. The memory layout is compatible (12 bytes total)
+        // 2. The alignment requirements are met (u32 requires 4-byte alignment)
+        // 3. We maintain the invariant that the bytes are always valid u32s
+        unsafe { std::slice::from_raw_parts(self as *const Int96 as *const u32, 3) }
```
Comment (alkis) [inline parquet/src/data_type.rs]: This is not safe because the ordering of Rust structs is not guaranteed.

File: parquet/src/data_type.rs (hunk 1 above)
Comment (etseidl) [reply parquet/src/data_type.rs:38]: That will lead to misaligned `i64` fields. From the ML it seems like this is a fix for legacy data while trying to convince the spark crowd to stop producing `INT96` timestamps. As such, I'd opt for the minimum set of changes needed and leave `value` as it was.

**Comment by alamb** [comment]
Thank you @rahulketch 

Here is a related issue PR in Spark to stop writing INT96 timestamps
- https://github.com/apache/spark/pull/50215

I am kind of confused about the current status of Int96 -- the parquet spec says they are deprecated but spark keeps writing them and this PR (and others) seem to imply Spark / Databricks plans to keep writing INT96 timestamps indefinitely. 

Here is a related mailing list discussion on this topic: https://lists.apache.org/thread/6fm50b3pmh6mz659jb5wx5vzmvwccz1n

As @emkornfield pointed out on that discussion, the spec explicitly says the sort order for INT96 types is undefined:

https://github.com/apache/parquet-format/blob/87f2c8bf77eefb4c43d0ebaeea1778bd28ac3609/src/main/thrift/parquet.thrift#L1079

Perhaps we should also update the spec to reflect whatever is desired as part of change the parquet writers?

**Review by emkornfield — CHANGES_REQUESTED** [review]
Sorry if I missed it but does Rust RS already filter have an allow/deny list for int96 stats when reading them?  If not it seems like that needs to be added to the PR (or we can wait to resolve the higher level concerns on the mailing list)

**Comment by alamb** [comment]
> Sorry if I missed it but does Rust RS already filter have an allow/deny list for int96 stats when reading them? If not it seems like that needs to be added to the PR (or we can wait to resolve the higher level concerns on the mailing list)

I am not aware of any such feature, but I am not quite sure what an `allow/deny list` means

The low level API will return the values as written, see https://docs.rs/parquet/latest/parquet/file/statistics/enum.Statistics.html

Specifically it will return `Statistics::Int96(ValueStatistics<Int96>)` I believe

**Comment by etseidl** [comment]
I think @emkornfield means will parquet-rs ignore `INT96` statistics on read and not write them. The sort order is undefined, so I think _any_ behavior, so long as it's consistent, is ok per the spec. But, as with many things, I think there's an inconsistency between the arrow and record APIs. It seems the arrow API will refuse to write `INT96` https://github.com/apache/arrow-rs/blob/1bed04c1e053e52575c6476f592c5aca3de7310f/parquet/src/arrow/arrow_writer/mod.rs#L1141-L1143

AFAICT the record API _will_, and the statistics written will be ordered as `Vec<u32>`, which is not what's desired here. (see [this](https://github.com/apache/arrow-rs/blob/1bed04c1e053e52575c6476f592c5aca3de7310f/parquet/src/column/writer/mod.rs#L2517) test for instance).

On read I believe both will treat statistics "properly" (i.e. the `Int96` type will be interpreted as little endian int96, with 4 byte days followed by 8 byte nanos), but the arrow API will promptly cast to some type of timestamp or error.

In the short term it might be best to have this crate mimic parquet-java and ignore `INT96` statistics if present and refuse to write them at all. We can revisit this PR if the community comes to a consensus and un-deprecates the type, or at least standardizes it rather than relying on Spark's or Impala's implementation.

**Comment by emkornfield** [comment]
>  am not aware of any such feature, but I am not quite sure what an allow/deny list means

@etseidl had a good summary, https://github.com/apache/parquet-java/pull/3243/files#r2155295422 effectively we want to look at writer versions to determine if statistics are valid.  See the [corresponding java PR](https://github.com/apache/parquet-java/pull/3243/files#r2155295422) as an example.

File: parquet/src/data_type.rs (hunk 1 above)
Comment (rahulketch) [reply parquet/src/data_type.rs:38]: I have made the changes minimal for the data_type.rs

File: parquet/src/data_type.rs [hunk 4]
```diff
@@ -132,6 +132,23 @@ impl Int96 {
     }
 }
 
+impl PartialOrd for Int96 {
```
Comment (alamb) [inline parquet/src/data_type.rs:137]: In my mind this rationale for this code is super unobvious from the code and it would be great to document the rationale as a comment. 

Thus I would like to request to add some documentation explaining that this is implementing comparisons using the logical timestamp type semantics with a link to the relevant portion of the spec?

I think it is https://github.com/apache/parquet-format/blob/cf943c197f4fad826b14ba0c40eb0ffdab585285/src/main/thrift/parquet.thrift#L1079

Perhaps something like
```suggestion
/// Order `Int96` correctly for (deprecated) timestamp types
///
/// Note: this is done even though the Int96 type is deprecated and the 
///  [spec does not define the sort order]
/// because some engines, notably Spark and DataBricks photon still write
/// Int96 timestamps and rely on their order for optimization. 
///
/// [spec does not define the sort order]: https://github.com/apache/parquet-format/blob/cf943c197f4fad826b14ba0c40eb0ffdab585285/src/main/thrift/parquet.thrift#L1079
impl PartialOrd for Int96 {
```

**Review by alamb — COMMENTED** [review]
I think the change in this PR is fine and thank you for the contribution @rahulketch . I think adding the rationale for the choice of sorting is super important and I left a suggestion

Once this PR passes the CI tests I would be fine with merging it

The only thing I am not clear about is how other readers will know if a particular parquet file has correctly (per the definition in this PR) written Int96 timestamp statistics.

Is the plan just to hard code the writer version string to known good writers?

**Comment by alamb** [comment]
I also filed a PR in the parquet-format repo to try and clarify the meaning
- https://github.com/apache/parquet-format/pull/504

File: parquet/src/data_type.rs [hunk 5]
```diff
@@ -132,6 +132,23 @@ impl Int96 {
...
+        Some(self.cmp(other))
+    }
+}
+
+impl Ord for Int96 {
+    fn cmp(&self, other: &Self) -> Ordering {
+        let (self_days, self_nanos) = self.data_as_days_and_nanos();
+        let (other_days, other_nanos) = other.data_as_days_and_nanos();
+
+        match self_days.cmp(&other_days) {
```
Comment (etseidl) [inline parquet/src/data_type.rs]: Micro-optimization: we could add `get_days` and `get_nanos` to `Int96`, and then change this to
```rust
match self.get_days().cmp(&other.get_days()) {
    Ordering::Equal => self.get_nanos().cmp(&other.get_nanos()),
    ord => ord,
}
```
That would save a few instructions when the days are not equal.

**Comment by etseidl** [comment]
I think we've achieved sufficient consensus to move forward with this. @rahulketch do you have time to address the outstanding issues here (@alamb's suggestion, CI errors, etc)? I have cycles to clean this up if you're short on time.  Thanks!

**Comment by rahulketch** [comment]
@etseidl I have pushed the changes which I believe address the open concerns. 

There is still the task of adding an allow/deny list to only accept the statistics from known good writer. See the corresponding [change](https://github.com/apache/parquet-java/pull/3243/files#diff-5a411f9c4979615ddc34eb42a939d5de3c2a3cd50face8647eeaec203d1fc98b) in parquet-java. 

My suggestion for that is:
1. Merge this change and make a new arrow-rs release `56.0.0`
2. After the new release add a check which allows reading the stats from:
- parquet-java 1.15.0+
- arrow-rs 56.0.0+
- photon 

What do you think?

PS: I will be on vacation 4th July - 15th July, so I'll only be able to make more changes after that.

**Comment by etseidl** [comment]
Thanks @rahulketch! I've taken the liberty of fixing the remaining lint errors.

> There is still the task of adding an allow/deny list to only accept the statistics from known good writer.

I agree that this is a follow on task and can be done after this PR merges. I think it will need to be part of a larger review of statistics handling to see if other types with undefined sort orders are also ignored.

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @rahulketch and @etseidl

File: parquet/src/data_type.rs [hunk 6]
```diff
@@ -118,14 +118,44 @@ impl Int96 {
...
+        Some(self.cmp(other))
     }
 }
 
+impl Ord for Int96 {
+    /// Order `Int96` correctly for (deprecated) timestamp types.
+    ///
+    /// Note: this is done even though the Int96 type is deprecated and the
+    /// [spec does not define the sort order]
+    /// because some engines, notably Spark and DataBricks photon still write
```
Comment (alkis) [inline parquet/src/data_type.rs]:
```suggestion
    /// because some engines, notably Spark and Databricks Photon still write
```

**Review by mbrobbel — APPROVED** [review]

**Comment by alamb** [comment]
@emkornfield this PR looks good to merge from my perspective and has several approvals and I think addresses your feedback.

If you would like more time to review, please let us know, otherwise I plan to merge this PR tomorrow

**Comment by emkornfield** [comment]
At the last sync we went back and forth on what was required for this from a spec perspective.

I think general consensus is we should update the spec (I think there is a PR open for this).

Beyond that there was discussion on whether we should have a new sort order or just rely on versions.  I'll start a thread but https://github.com/apache/arrow-rs/issues/7909 is pertinent to a discussion on on how much effort adding a SortOrder would be.

**Comment by alamb** [comment]
@emkornfield  are you opposed to merging this PR? I can't quite tell from the comments

> I think general consensus is we should update the spec (I think there is a PR open for this).

I did make a PR here to clarify the spec about Int96 stats (with a recommendation, not with any actual change):
- https://github.com/apache/parquet-format/pull/504

> Beyond that there was discussion on whether we should have a new sort order or just rely on versions. I'll start a thread but #7909 is pertinent to a discussion on on how much effort adding a SortOrder would be.

In my opinion, there is no reason to hold up this PR (which improves compatibility for an "implementation defined" part of the spec) on actually changing the spec. We can proceed with actually defining a SortOrder / fixing the spec in parallel

**Comment by emkornfield** [comment]
Yes, I'm fine to merge this PR.  It seems like a strict improvement.

File: parquet/src/file/statistics.rs [hunk 7]
```diff
@@ -209,9 +209,6 @@ pub fn from_thrift(
                     old_format,
                 ),
                 Type::INT96 => {
-                    // INT96 statistics may not be correct, because comparison is signed
```
Comment (emkornfield) [inline parquet/src/file/statistics.rs:212]: I don't think we should remove this until we have a filter on known good statistics.

Comment (alamb) [reply parquet/src/file/statistics.rs:212]:
```suggestion
                    // INT96 statistics may not be correct, because comparison is signed
```

**Comment by alamb** [comment]
Thanks again everyone for all your help and patience

File: parquet/src/file/statistics.rs (hunk 7 above)
Comment (alamb) [reply parquet/src/file/statistics.rs:212]: I forgot to merge this one. so I made a follow on PR:
- https://github.com/apache/arrow-rs/pull/7975
