### PR TITLE
fix: Ensure Flight schema includes parent metadata

### LINKED ISSUE #3779: Schema-level metadata is not encoded in Flight responses
**Describe the bug**

When preparing schema for encoding into a Flight response, the schema-level metadata from the source schema is dropped:

https://github.com/apache/arrow-rs/blob/e7eb304dac442a943c434f8ea248de909f82aa88/arrow-flight/src/encode.rs#L326

**To Reproduce**

```patch
Index: arrow-flight/src/encode.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/arrow-flight/src/encode.rs b/arrow-flight/src/encode.rs
--- a/arrow-flight/src/encode.rs	(revision e7eb304dac442a943c434f8ea248de909f82aa88)
+++ b/arrow-flight/src/encode.rs	(date 1677611826249)
@@ -453,6 +453,7 @@
 
 #[cfg(test)]
 mod tests {
+    use std::collections::HashMap;
     use arrow::{
         array::{UInt32Array, UInt8Array},
         compute::concat_batches,
@@ -502,6 +503,16 @@
         );
     }
 
+    #[test]
+    fn test_schema_metadata_encoded() {
+        let schema = Schema::new(vec![
+            Field::new("data", DataType::Int32, false),
+        ]).with_metadata(HashMap::from([("some_key".to_owned(), "some_value".to_owned())]));
+
+        let got = prepare_schema_for_flight(&schema);
+        assert!(got.metadata().contains_key("some_key"));
+    }
+
     #[test]
     fn test_encode_no_column_batch() {
         let batch = RecordBatch::try_new_with_options(
```

**Expected behavior**

Schema-level metadata should be included permitting test to pass.

**Additional context**

### PR DESCRIPTION
**Pull request by stuartcarnie**
# Which issue does this PR close?

Closes #3779

# Rationale for this change
 
Ensures that schema-level metadata is included when encoding the schema for a Flight response.

# What changes are included in this PR?

The `prepare_schema_for_flight` function in the `encode` module of the `arrow-flight` crate was amended to include the schema from the parent.

# Are there any user-facing changes?

No

### CODE REVIEW

File: arrow-flight/src/encode.rs [hunk 1]
```diff
@@ -502,6 +503,16 @@ mod tests {
         );
     }
 
+    #[test]
+    fn test_schema_metadata_encoded() {
```
Comment (alamb) [inline arrow-flight/src/encode.rs:507]: 👍

**Review by alamb — APPROVED** [review]
Thanks @stuartcarnie. Looks good to me.

I think we should add a higher level test  in encode_decode.rs  (so if /when we remove this "prepare schema for flight" to support dictionary encoded arrays, we will still have coverage for metadata) 

Here is a small PR (targeting this pR) to add one:
https://github.com/stuartcarnie/arrow-rs/pull/1/files

If you prefer we can also merge this PR and I can make a separate PR to arrow-rs

**Comment by alamb** [comment]
@stuartcarnie  this PR is failing the 'cargo fmt' CI check: https://github.com/apache/arrow-rs/actions/runs/4351021747/jobs/7602273280

**Comment by stuartcarnie** [comment]
@alamb thank you for the review and your PR, which I merged into this one.
