### PR TITLE
Fix some clippy lints in parquet crate, rename `LevelEncoder` variants to conform to Rust standards

### LINKED ISSUE #1254: Fix all clippy lints in parquet crate
**Describe the bug**
Due to "historical reasons" there are several clippy lints that are disabled in the parquet crate
https://github.com/apache/arrow-rs/blob/master/parquet/src/lib.rs#L18-L36

```rust
#![allow(incomplete_features)]
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(
    clippy::approx_constant,
    clippy::cast_ptr_alignment,
    clippy::float_cmp,
    clippy::float_equality_without_abs,
    clippy::from_over_into,
    clippy::many_single_char_names,
    clippy::needless_range_loop,
    clippy::new_without_default,
    clippy::or_fun_call,
    clippy::same_item_push,
    clippy::too_many_arguments,
    clippy::transmute_ptr_to_ptr,
    clippy::upper_case_acronyms,
    clippy::vec_init_then_push
)]
```

It would be great to clean up the code to pass these lints for tidiness

**To Reproduce**
Remove one of the `#[allow]` lines above, run `clippy`

**Expected behavior**
Clippy runs cleanly without blank `#allow` across the whole crate

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
# Which issue does this PR close?

Re #1254. Partially close it

# Rationale for this change
 
 

In this PR, we remove some disabled clippy lints and refactor the code, which includes:
- vec_init_then_push
- upper_case_acronyms
- transmute_ptr_ti_ptr
- same_item_push
- approx_constant
- cast_ptr_alignment
- float_cmp
- float_equality_without_abs
- incomplete_features
- single_char_names
- needless_range_loop

# What changes are included in this PR?

# Are there any user-facing changes?

Some enums are renamed.

### CODE REVIEW

**Comment by alamb** [comment]
@HaoYang670  this PR is marked "draft" - is it ready for review?

**Comment by HaoYang670** [comment]
Yes, ready for review.

File: parquet/src/encodings/decoding.rs [hunk 1]
```diff
@@ -1340,11 +1340,11 @@ mod tests {
         #[allow(clippy::wrong_self_convention)]
         fn to_byte_array(data: &[bool]) -> Vec<u8> {
             let mut v = vec![];
-            for i in 0..data.len() {
+            for (i, item) in data.iter().enumerate() {
                 if i % 8 == 0 {
                     v.push(0);
                 }
-                if data[i] {
+                if *item {
```
Comment (alamb) [inline parquet/src/encodings/decoding.rs:1347]: this type of change is not only more "idiomatic" I think it will also be faster (as bounds checks aren't being done on each access of `data` 👍 )

File: parquet/src/encodings/levels.rs [hunk 2]
```diff
@@ -50,11 +50,11 @@ pub fn max_buffer_size(
 }
 
 /// Encoder for definition/repetition levels.
-/// Currently only supports RLE and BIT_PACKED (dev/null) encoding, including v2.
+/// Currently only supports Rle and BitPacked (dev/null) encoding, including v2.
 pub enum LevelEncoder {
```
Comment (alamb) [inline parquet/src/encodings/levels.rs:54]: This is technically a breaking API change, but I think it is ok

File: parquet/src/lib.rs [hunk 3]
```diff
@@ -30,24 +30,13 @@
 //!
 //! 3. [arrow::async_reader] for `async` reading and writing parquet
 //! files to Arrow `RecordBatch`es (requires the `async` feature).
-#![allow(incomplete_features)]
 #![allow(dead_code)]
 #![allow(non_camel_case_types)]
 #![allow(
```
Comment (alamb) [inline parquet/src/lib.rs:35]: 🎉

**Review by alamb — APPROVED** [review]
Thank you @HaoYang670 

Looks really nice to me ❤️

File: parquet/src/encodings/levels.rs (hunk 2 above)
Comment (alamb) [reply parquet/src/encodings/levels.rs:54]: cc @tustvold

Comment (tustvold) [reply parquet/src/encodings/levels.rs:54]: The encodings module is experimental and so this isn't actually a breaking change. Clippy ignores proposing breaking changes to the API (at least for this lint because the salt was strong).
