### PR TITLE
Fix clippy by avoiding deprecated functions in chrono

### LINKED ISSUE #3097: Clippy failing on master : error: use of deprecated associated function chrono::NaiveDate::from_ymd: use from_ymd_opt() instead
**Describe the bug**

Clippy failing on master https://github.com/apache/arrow-rs/actions/runs/3452655275/jobs/5762703673

```
error: use of deprecated associated function `chrono::NaiveDate::from_ymd`: use `from_ymd_opt()` instead
   --> arrow-array/src/timezone.rs:303:28
    |
303 |         let t = NaiveDate::from_ymd(2000, 1, 1);
    |                            ^^^^^^^^
```

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #3097.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
cc @tustvold @alamb

**Review by tustvold — APPROVED** [review]

File: arrow-array/src/delta.rs [hunk 1]
```diff
@@ -105,75 +105,186 @@ mod tests {
...
+        );
     }
 
     #[test]
     fn test_shift_months_with_overflow() {
-        let base = NaiveDate::from_ymd(2020, 12, 31);
+        let base = NaiveDate::from_ymd_opt(2020, 12, 31).unwrap();
 
         assert_eq!(shift_months(base, 0), base);
-        assert_eq!(shift_months(base, 1), NaiveDate::from_ymd(2021, 1, 31));
```
Comment (alamb) [inline arrow-array/src/delta.rs:147]: 🤔  this feels very familiar / similar to the work in https://github.com/apache/arrow-datafusion/pull/4189/files#diff-880863b84a09b210db1fc00012b1f3fbf0ade7f23c4297e15b54474ec65cb814R107

I'll see if I can find a way to remove the copy in DataFusion

**Comment by alamb** [comment]
Thanks @viirya
