### PR TITLE
Fix reading/writing nested null arrays (#1480) (#1036) (#1399)

### LINKED ISSUE #1036: JSON input barfs on {"emptylist":[]}
**Describe the bug**
JSON inuput barfs on {"emptylist":[]}

```bash
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/core/src/panicking.rs:107:14
   2: parquet::arrow::levels::LevelInfo::filter_array_indices
   3: parquet::arrow::arrow_writer::write_leaf
   4: parquet::arrow::arrow_writer::write_leaves
   5: parquet::arrow::arrow_writer::write_leaves
   6: parquet::arrow::arrow_writer::ArrowWriter<W>::write
   7: json2parquet::main
```

I was driving the library with https://github.com/domoritz/json2parquet

```bash
thread 'main' panicked at 'Cannot filter indices on a non-primitive array, found List(true)', /PATH/parquet-6.1.0/src/arrow/levels.rs:757:18
```

**To Reproduce**
{"emptylist":[]}

**Expected behavior**
Same as pyarrow, it does not barf the Parquet writer.

```bash
pyarrow.Table
emptylist: list<item: null>
  child 0, item: null
----
emptylist: [[0 nulls]]
```

**Additional context**

### LINKED ISSUE #1399: Parquet reader fails to read null list.
**Describe the bug**
Parquet reader fails to read a parquet file that is generated from this json:
```
{"emptylist":[]}
```

**To Reproduce**
I have written a test on a branch to reproduce this failure. 

1. Generated a parquet-file from the aforementioned json. See https://github.com/apache/arrow-rs/pull/1063#issuecomment-1053939744 and the related issue for context. Verified that this parquet file can be read using pyarrow as the following arrow table:

```
>>> empty_table = pq.read_table("empty_table.parquet")
>>> empty_table
pyarrow.Table
emptylist: list<item: null>
  child 0, item: null
----
emptylist: [[0 nulls]]
```
2. Added this parquet file to a branch of my fork of `parquet-testing` https://github.com/novemberkilo/parquet-testing/commit/a827b12cd0985ef2d6d89534a405e64d55a40140

3. Wrote a test that reads this file. 

Test: https://github.com/novemberkilo/arrow-rs/commit/e5952ae74344d253fad7212ec46cb913d5e4f1cb
~~Failure: https://github.com/novemberkilo/arrow-rs/runs/5431110483?check_suite_focus=true#step:4:1999~~
Failure: https://github.com/novemberkilo/arrow-rs/runs/5431134675?check_suite_focus=true#step:7:1944

**Expected behavior**
Should read the file (like pyarrow can)

**Additional context**
This is all related to this original issue #1036 // @alamb

### LINKED ISSUE #1480: Parquet Writer Incorrect Definition Levels for Nested NullArray
**Describe the bug**

Currently when a nested NullArray is written to parquet the definition levels are such that not all values are actually null. This is currently masked by bugs that prevent reading such arrays (fixes in flight) and also because `NullArrayReader` ignores any value data that may be present.

**To Reproduce**

```
#[test]
fn foo() {
    let null_field = Field::new("item", DataType::Null, true);
    let list_field = Field::new("emptylist", DataType::List(Box::new(null_field)), true);

    let schema = Schema::new(vec![list_field]);

    // Build [[], null, [null, null]]
    let a_values = NullArray::new(2);
    let a_value_offsets = arrow::buffer::Buffer::from(&[0, 0, 0, 2].to_byte_slice());
    let a_list_data = ArrayData::builder(DataType::List(Box::new(Field::new(
        "item",
        DataType::Null,
        true,
    ))))
    .len(3)
    .add_buffer(a_value_offsets)
    .null_bit_buffer(Buffer::from(vec![0b00000101]))
    .add_child_data(a_values.data().clone())
    .build()
    .unwrap();

    let a = ListArray::from(a_list_data);

    assert_eq!(a.is_valid(0), true);
    assert_eq!(a.is_valid(1), false);
    assert_eq!(a.is_valid(2), true);

    assert_eq!(a.value(0).len(), 0);
    assert_eq!(a.value(2).len(), 2);
    assert_eq!(a.value(2).null_count(), 2);

    let batch = RecordBatch::try_new(Arc::new(schema), vec![Arc::new(a)]).unwrap();

    let file = File::create("temp.parquet").unwrap();
    let mut writer = ArrowWriter::try_new(file, batch.schema(), None).unwrap();
    writer.write(&batch).unwrap();
    writer.close().unwrap();
}
```

Then read the file using duckdb

```
duckdb.query(f"select * from 'temp.parquet'").fetchall()
[(None,), (None,), ([0, 0],)]
```

We mysteriously have a null array containing non-null data :scream:

**Expected behavior**

```
>>> duckdb.query(f"select * from 'temp.parquet'").fetchall()
[(None,), (None,), ([None, None],)]
```

**Additional context**

This is likely to be a consequence of a somewhat surprising quirk of NullArrays which is that they don't actually contain a null bitmask, as they don't contain any buffers at all.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1480 
Closes #1036 
Closes #1399

# Rationale for this change

See tickets

# What changes are included in this PR?

Fixes various bugs in handling of null arrays

# Are there any user-facing changes?

Previous incorrect behaviour is now fixed

### CODE REVIEW

File: parquet/src/arrow/levels.rs [hunk 1]
```diff
@@ -200,9 +200,8 @@ impl LevelInfo {
                 );
 
                 match child_array.data_type() {
-                    // TODO: The behaviour of a <list<null>> is untested
-                    DataType::Null => vec![list_level],
-                    DataType::Boolean
+                    DataType::Null
```
Comment (tustvold) [inline parquet/src/arrow/levels.rs:203]: This is the fix for #1036

File: parquet/src/arrow/levels.rs [hunk 2]
```diff
@@ -677,8 +676,9 @@ impl LevelInfo {
         len: usize,
     ) -> (Vec<i64>, Vec<bool>) {
         match array.data_type() {
-            DataType::Null
-            | DataType::Boolean
+            // A NullArray is entirely nulls, despite not containing a null buffer
+            DataType::Null => ((0..=(len as i64)).collect(), vec![false; len]),
```
Comment (tustvold) [inline parquet/src/arrow/levels.rs:680]: This is the fix for #1480

File: parquet/src/arrow/array_reader.rs [hunk 3]
```diff
@@ -225,11 +225,10 @@ where
 
     /// Reads at most `batch_size` records into array.
     fn next_batch(&mut self, batch_size: usize) -> Result<ArrayRef> {
-        let records_read =
-            read_records(&mut self.record_reader, self.pages.as_mut(), batch_size)?;
+        read_records(&mut self.record_reader, self.pages.as_mut(), batch_size)?;
 
         // convert to arrays
-        let array = arrow::array::NullArray::new(records_read);
+        let array = arrow::array::NullArray::new(self.record_reader.num_values());
```
Comment (tustvold) [inline parquet/src/arrow/array_reader.rs:231]: This was a bug, the NullArray should have the value count number of elements, i.e. the same number of elements as the definition/repetition levels if any. 

In the non-nested case the two quantities will be the same, but in the event of a nested array a single record might correspond to 1 or more values.

This would then cause this line to fire - https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/array_reader.rs#L930

**Review by nevi-me — APPROVED** [review]
I went through the PR, the changes that you made make sense to me, and I can see how they address the issues that you've listed.

File: parquet/src/arrow/array_reader.rs [hunk 4]
```diff
@@ -887,7 +886,7 @@ fn remove_indices(
                 Ok(Arc::new(StructArray::from((new_columns, valid.finish()))))
             }
         }
-        ArrowType::Null => Ok(Arc::new(NullArray::new(arr.len()))),
+        ArrowType::Null => Ok(Arc::new(NullArray::new(arr.len() - indices.len()))),
```
[the remark this answers is not in the document]
Comment (tustvold) [reply parquet/src/arrow/array_reader.rs:889]: That was caused by https://github.com/apache/arrow-rs/pull/1448#discussion_r831229793 if I'm not mistaken

[the remark this answers is not in the document]
Comment (viirya) [reply parquet/src/arrow/array_reader.rs:889]: Maybe it is affected by https://github.com/apache/arrow-rs/pull/1481/files#diff-0d6bed48d78c5a2472b7680a8185cabdc0bd259d6484e184439ed7830060661fR231?

**Comment by alamb** [comment]
Thanks all@
