### PR TITLE
Don't overwrite existing data on snappy decompress (#1806)

### LINKED ISSUE #1806: Parquet Snappy Codec Tramples Existing Data in Decompressed Buffer
**Describe the bug**

Calling `SnappyCodec::decompress` with a non-empty `output_buf` will trample any data that already exists in the buffer.

**To Reproduce**

Calling `SnappyCodec::decompress` with a non-empty `output_buf` will trample any data that already exists in the buffer.

**Expected behavior**

It should append to the end of the passed `Vec`

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1806

# Rationale for this change
 
Fixes a bug

# What changes are included in this PR?

Makes it so SnappyCodec doesn't trample existing data in the passed output buffer

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/compression.rs [hunk 1]
```diff
@@ -340,26 +341,46 @@ mod tests {
...
         c2.compress(data, &mut compressed)
             .expect("Error when compressing");
 
         // Decompress with c1
-        decompressed_size = c1
+        let decompressed_size = c1
             .decompress(compressed.as_slice(), &mut decompressed)
             .expect("Error when decompressing");
         assert_eq!(data.len(), decompressed_size);
-        decompressed.truncate(decompressed_size);
```
Comment (tustvold) [inline parquet/src/compression.rs:361]: This test was actually incorrect, it never cleared `decompressed` and so this was effectively just checking the same bytes it checked in the test above (except for Snappy which would truncate and trample)

File: parquet/src/compression.rs [hunk 2]
```diff
@@ -340,26 +341,46 @@ mod tests {
...
         assert_eq!(data, decompressed.as_slice());
+
```
Comment (alamb) [inline parquet/src/compression.rs:363]: I went through the changes in this test carefully and they look good to me 👍

**Review by alamb — APPROVED** [review]
I recommend updating the comments on the `Codec` trait to be explicit that the data is appended to the end of `output` and not the beginning

https://github.com/apache/arrow-rs/blob/91d12ec/parquet/src/compression.rs#L52-L61

**Comment by alamb** [comment]
Nice work @tustvold

**Review by viirya — APPROVED** [review]
