### PR TITLE
Fix sparse union array equality (#4044)

### LINKED ISSUE #4044: Sparse UnionArray Equality Incorrect Offset Handling
**Describe the bug**

**To Reproduce**

```
#[test]
fn test_union_equal_sparse_slice() {
    let mut builder = UnionBuilder::new_sparse();
    builder.append::<Int32Type>("a", 1).unwrap();
    builder.append::<Int32Type>("a", 2).unwrap();
    builder.append::<Int32Type>("b", 3).unwrap();
    let a1 = builder.build().unwrap();

    let mut builder = UnionBuilder::new_sparse();
    builder.append::<Int32Type>("a", 2).unwrap();
    builder.append::<Int32Type>("b", 3).unwrap();
    let a2 = builder.build().unwrap();

    test_equal(&a1.slice(1, 2), &a2, true)
}
```

The above should pass, it currently does not

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4044

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-data/src/equal/union.rs [hunk 1]
```diff
@@ -70,7 +70,13 @@ fn equal_sparse(
         .iter()
         .zip(rhs.child_data())
         .all(|(lhs_values, rhs_values)| {
-            equal_range(lhs_values, rhs_values, lhs_start, rhs_start, len)
+            equal_range(
+                lhs_values,
+                rhs_values,
+                lhs_start + lhs.offset(),
```
Comment (alamb) [inline arrow-data/src/equal/union.rs:76]: offsets!

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thank you @tustvold
