### PR TITLE
fix: nanosecond timestamp scaling during string conversion (#780)

### LINKED ISSUE #780: Converting from string to timestamp uses microseconds instead of milliseconds
**Describe the bug**
Calls to `string_to_timestamp_nanos` may parse fractional part of a second as  nanoseconds instead of microseconds or milliseconds.

**To Reproduce**
Call `string_to_timestamp_nanos("1970-01-01T00:00:00.123")`, it produces a timestamps of `123` nanoseconds since UNIX epoch. 
Local timezone must be UTC.

**Expected behavior**
A timestamps of `123` milliseconds since UNIX Epoch is returned.

**Additional context**
I have prepared a fix too, sending it out soon.

### PR DESCRIPTION
**Pull request by ilya-biryukov**
Some datetime formats passed to `string_to_timestamp_nanos` were parsing
milliseconds as nanoseconds.

E.g. `1970-01-01 00:00:00.123` would parse as `123` nanoseconds instead
of milliseconds.

# Which issue does this PR close?

Closes #780.

### CODE REVIEW

File: arrow/src/compute/kernels/cast_utils.rs [hunk 1]
```diff
@@ -227,7 +227,7 @@ mod tests {
         // somewhat suceptable to bugs in the use of chrono
         let naive_datetime = NaiveDateTime::new(
             NaiveDate::from_ymd(2020, 9, 8),
-            NaiveTime::from_hms_nano(13, 42, 29, 190855),
+            NaiveTime::from_hms_nano(13, 42, 29, 190855000),
```
Comment (alamb) [inline arrow/src/compute/kernels/cast_utils.rs:230]: This is a compelling bug in the test that is fixed.

**Review by alamb — APPROVED** [review]
Thank you @ilya-biryukov 

It is very non obvious to me that `%.f` and `.%f` are so different from reading the chrono manual https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html but the test case is quite compelling evidence

cc @jhorstmann

**Comment by ilya-biryukov** [comment]
Was also surprised how deceitfully similar the formats are. We happened to pre-parse the format strings (for performance, this function is on hot path in CubeStore) and the difference is [easy to spot](https://github.com/cube-js/arrow-rs/commit/0293429456f4464c7065075d909dce4269e477c4?branch=0293429456f4464c7065075d909dce4269e477c4&diff=unified#diff-2e91ef6c992ac2ad5db111bda8eb9fdb056a7849df85ba378d39f47a00a85704L156) there.

**Comment by jhorstmann** [comment]
Wow, that's a big foot-gun in chrono. Fix looks good to me.

**Comment by alamb** [comment]
Thanks @ilya-biryukov  and @jhorstmann
