### PR TITLE
fix parquet max_definition for non-null structs

### LINKED ISSUE #244: Unable to write non-null Arrow structs to Parquet
**Describe the bug**

Unable to correctly write nested structs where a struct is non-nullable.
I've noticed this behaviour before, but couldn't quite reproduce it easily.

**To Reproduce**

If we have the below test case (in `parquet/src/arrow/arrow_writer.rs`:

```rust
#[test]
fn arrow_writer_complex_mixed() {
    // define schema
    let offset_field = Field::new("offset", DataType::Int32, true);
    let partition_field = Field::new("partition", DataType::Int64, true);
    let topic_field = Field::new("topic", DataType::Utf8, true);
    let schema = Schema::new(vec![
        Field::new("some_nested_object", DataType::Struct(
            vec![
                offset_field.clone(),
                partition_field.clone(),
                topic_field.clone()
            ]
        ), false), // NOTE: this being false results in the array not being written correctly
    ]);

    // create some data
    let offset = Int32Array::from(vec![1, 2, 3, 4, 5]);
    let partition = Int64Array::from(vec![Some(1), None, None, Some(4), Some(5)]);
    let topic = StringArray::from(vec![Some("A"), None, Some("A"), Some(""), None]);

    let some_nested_object = StructArray::from(vec![
        (offset_field, Arc::new(offset) as ArrayRef),
        (partition_field, Arc::new(partition) as ArrayRef),
        (topic_field, Arc::new(topic) as ArrayRef),
    ]);

    // build a record batch
    let batch = RecordBatch::try_new(
        Arc::new(schema),
        vec![Arc::new(some_nested_object)],
    )
    .unwrap();

    roundtrip("test_arrow_writer_complex_mixed.parquet", batch);
}
```

We get a failure:

```rust
thread 'arrow::arrow_writer::tests::arrow_writer_complex_mixed' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', parquet/src/util/bit_util.rs:332:9
test arrow::arrow_writer::tests::arrow_writer_complex_mixed ... FAILED
```

When the struct is nullable, the file is written correctly.

**Expected behavior**

The batch should be written without errors.

**Additional context**

From inspecting the levels that are generated for the passing and failing scenarios, they look identical (https://www.diffchecker.com/89qWByeI). It looks like the bug is with how levels of non-null structs are generated.

### PR DESCRIPTION
**Pull request by nevi-me**
# Which issue does this PR close?

Closes #244 .

 # Rationale for this change

This fixes a bug

# What changes are included in this PR?

* The calculation of levels for non-null structs has been fixed.
* I also refer to #245 where more investigations about parquet & arrow struct compatibility are needed.
* I added a test, and ignored one that was failing before this PR

# Are there any user-facing changes?

No, changes made to crate-level structs, that are not publicly exposed

### CODE REVIEW

File: parquet/src/arrow/levels.rs [hunk 1]
```diff
@@ -311,11 +333,20 @@ impl LevelInfo {
                 } else if self.is_list {
                     // second exception, always increment after a list
                     self.max_definition + 1
+                } else if is_parent_struct && !self.is_nullable {
+                    // if the parent is a non-null struct, don't increment
```
Comment (jorgecarleitao) [inline parquet/src/arrow/levels.rs:337]: I am trying to wrap my head around this comment: `self.is_nullable` is the nullability of the `parent` in this case?

I would expect something like `is_parent_struct_null` computed from the nullability of the parent?

**Review by jorgecarleitao — COMMENTED** [review]
Thanks a lot for taking this on, @nevi-me !

I started reviewing this. I can see where the problem may lie, but I am still trying to understand the logic.

File: parquet/src/arrow/levels.rs (hunk 1 above)
Comment (nevi-me) [reply parquet/src/arrow/levels.rs:337]: Yes, self is the parent, so if the parent is a null struct ...

Interestingly, I don't need the 'is_parent_steuct' variable, because '!self.is_list' means that self is a struct at this point in the code. I'll tweak the logic later tonight

File: parquet/src/arrow/arrow_writer.rs [hunk 2]
```diff
@@ -881,10 +927,14 @@ mod tests {
...
         // create data
+        // When the null buffer of the struct is created, this test fails.
+        // It appears that the nullness of the struct is ignored when the
+        // struct is read back.
+        // See https://github.com/apache/arrow-rs/issues/245
         let c = Int32Array::from(vec![1, 2, 3, 4, 5, 6]);
         let b_data = ArrayDataBuilder::new(field_b.data_type().clone())
             .len(6)
-            .null_bit_buffer(Buffer::from(vec![0b00100111]))
+            // .null_bit_buffer(Buffer::from(vec![0b00100111]))
```
Comment (alamb) [inline parquet/src/arrow/arrow_writer.rs:937]: I think this is ok (given the test didn't pass previously anyways) so this isn't a regression

File: parquet/src/arrow/levels.rs [hunk 3]
```diff
@@ -97,10 +97,20 @@ impl LevelInfo {
     /// Compute nested levels of the Arrow array, recursing into lists and structs.
     ///
     /// Returns a list of `LevelInfo`, where each level is for nested primitive arrays.
+    ///
+    /// The parent struct's nullness is tracked, as it determines whether the child
+    /// max_deginition should be incremented.
```
Comment (alamb) [inline parquet/src/arrow/levels.rs:102]:
```suggestion
    /// max_definition should be incremented.
```

File: parquet/src/arrow/levels.rs [hunk 4]
```diff
@@ -195,11 +208,12 @@ impl LevelInfo {
                             child_offsets,
                             child_mask,
                             false,
+                            false, // always false
                             list_field.is_nullable(),
                         )]
                     }
                     DataType::List(_) | DataType::LargeList(_) | DataType::Struct(_) => {
-                        list_level.calculate_array_levels(&child_array, list_field)
+                        list_level.calculate_array_levels(&child_array, list_field, false)
```
Comment (alamb) [inline parquet/src/arrow/levels.rs:216]: if the data type is `DataType::Struct(_)`, wouldn't `is_parent_struct` be true? I probably misunderstand

**Review by alamb — APPROVED** [review]
I can't say I understand the intricacies of this logic, but I did read the PR and it seems to me that the PR is a step in the right direction and can be merged as is:
1. Some tests pass now that did not pass previously
2. The additional cases which may require more work are tracked by an issue.

File: parquet/src/arrow/levels.rs (hunk 4 above)
Comment (nevi-me) [reply parquet/src/arrow/levels.rs:216]: In this case, this is an immediate struct of a parent list, so it's false.

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Thanks @nevi-me !

File: parquet/src/arrow/levels.rs (hunk 1 above)
Comment (nevi-me) [reply parquet/src/arrow/levels.rs:337]: I checked this, trying to rely on the `!self.is_list` doesn't always work, so I'm leaving the logic as is for now.
