### PR TITLE
Move tests which require chrono-tz feature from `arrow-cast` to `arrow`

### LINKED ISSUE #3219: Re-enable some tests in `arrow-cast` crate
**Describe the bug**

We split out `arrow-cast` crate. Some tests moved to the crate need feature `chrono-tz`, but the crate don't have it. So these tests are not run in CI.

**To Reproduce**

Run `cargo test --features chrono-tz test_can_cast_types -- --nocapture`. 

On master branch, the test is not run.

Normally we should see such output:

```
running 1 test
Test casting Binary --> Null
Test casting Binary --> Boolean
Test casting Binary --> Int8
Test casting Binary --> Int16
Test casting Binary --> Int32
Test casting Binary --> UInt64
Test casting Binary --> UInt8
Test casting Binary --> UInt16
```

**Expected behavior**

**Additional context**

### LINKED ISSUE #3220: Utf8 and LargeUtf8 cannot cast from/to Float16 but can_cast_types returns true
**Describe the bug**

`can_cast_types` returns true for casting between Utf8/LargeUtf8 and Float16, but actually cast kernel cannot cast them.

**To Reproduce**

**Expected behavior**

**Additional context**

### LINKED ISSUE #3221: bool should cast from/to Float16Type as `can_cast_types` returns true
**Describe the bug**

`can_cast_types` returns true for casting between bool and Float16, but actually cast kernel doesn't cast them.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #3219.
Closes #3220.
Closes #3221.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — COMMENTED** [review]
Could we instead move these to be integration tests in arrow-rs. Otherwise the inconsistent feature flags will result lots of recompilation when switching crates and targets?

File: arrow-cast/src/cast.rs [hunk 1]
```diff
@@ -3614,7 +3616,6 @@ mod tests {
     }
 
     #[test]
-    #[cfg(not(feature = "force_validate"))]
```
Comment (viirya) [inline arrow-cast/src/cast.rs:3617]: For the tests which depend on not "force_validate", I just removed the effectless `cfg`.

File: arrow/tests/array_cast.rs [hunk 2]
```diff
@@ -0,0 +1,417 @@
...
+                }
+                // otherwise it was a match
+                _ => {}
+            };
+        }
+    }
+}
+
+/// Create instances of arrays with varying types for cast tests
+#[cfg(feature = "chrono-tz")]
```
Comment (tustvold) [inline arrow/tests/array_cast.rs:100]: Rather than putting these here, can we maybe add to `Cargo.toml` something like

```
[[test]]
name = "array_cast"
required-features = ["chrono-tz"]
```
?

**Review by tustvold — APPROVED** [review]
Minor nit concerning feature compilation

File: arrow/tests/array_cast.rs (hunk 2 above)
Comment (viirya) [reply arrow/tests/array_cast.rs]: Okay. Moved.

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
Strangely I can't see this in the CI output, but running `cargo test -p arrow --features=force_validate,prettyprint,ipc_compression,ffi,dyn_cmp_dict,dyn_arith_dict,chrono-tz` locally it runs the test?

**Comment by viirya** [comment]
I see it in the CI output at https://github.com/apache/arrow-rs/actions/runs/3586065699/jobs/6034811204:

```
     Running tests/array_cast.rs (target/debug/deps/array_cast-6a755e3bff422147)

running 3 tests
test test_cast_timestamp_to_string ... ok
test test_timestamp_cast_utf8 ... ok
test test_can_cast_types ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

**Comment by tustvold** [comment]
Aah I was using the browser search not the one built into the UI :+1:
