### PR TITLE
Validate dictionary key in TypedDictionaryArray (#2578)

### LINKED ISSUE #2564: Why do we check for null in TypedDictionaryArray value function
**Which part is this question about**
Code base: https://github.com/apache/arrow-rs/blob/master/arrow/src/array/array_dictionary.rs#L498.

**Describe your question**
In TypedDictionaryArray value function why do we check for null , we could instead assert if the index is less than keys.len() right?

**Additional context**
the trait documentation states the below, due to which I felt it was bizzare that we are checking for null.

```
/// A generic trait for accessing the values of an [`Array`]
pub trait ArrayAccessor: Array {
    type Item: Send + Sync;

    /// Returns the element at index `i`
    /// # Panics
    /// Panics if the value is outside the bounds of the array
    fn value(&self, index: usize) -> Self::Item;
```

**Proposal**
We can instead rewrite it as below

```
fn value(&self, index: usize) -> Self::Item {
        assert!(
            index < self.dictionary.keys().len(),
            "TypedDictionaryArray out of bounds access {}",
            index
        );

        // Dictionary indexes should be valid
        unsafe { self.values.value_unchecked(index) }
    }
```

### LINKED ISSUE #2578: Potential OOB Access in Unreleased Comparison Kernels
**Describe the bug**

https://github.com/apache/arrow-rs/pull/2533 introduced a potential OOB access as described [here](https://github.com/apache/arrow-rs/pull/2533#discussion_r953949061). This should be fixed prior to the next release

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2578 
Closes #2564 

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/array/array_dictionary.rs [hunk 1]
```diff
@@ -491,21 +490,30 @@ where
...
 
     unsafe fn value_unchecked(&self, index: usize) -> Self::Item {
         let val = self.dictionary.keys.value_unchecked(index);
         let value_idx = val.to_usize().unwrap();
-        // Dictionary indexes should be valid
-        self.values.value_unchecked(value_idx)
+
+        // As dictionary keys are only verified for non-null indexes
+        // we must check the value is within bounds
+        match value_idx < self.dictionary.len() {
```
Comment (tustvold) [inline arrow/src/array/array_dictionary.rs:513]: As pointed out by @crepererum the fact the value is in a dictionary in the first place likely indicates that operations on it are likely to be non-trival (i.e. it is likely a string). Therefore the cost of this bound check is likely irrelevant, especially since because of #1918 we are doing checked conversion to usize anyway.

File: arrow/src/array/array_dictionary.rs [hunk 2]
```diff
@@ -491,21 +490,30 @@ where
     K: ArrowPrimitiveType,
     V: Sync + Send,
     &'a V: ArrayAccessor,
+    <&'a V as ArrayAccessor>::Item: Default,
```
Comment (tustvold) [inline arrow/src/array/array_dictionary.rs:493]: As we don't currently support dictionaries containing complex types such as ListArray, etc... (neither does C++) nor even implement ArrayAccessor for those types, this restriction is unlikely to matter in practice

**Review by viirya — APPROVED** [review]

File: arrow/src/array/array_dictionary.rs [hunk 3]
```diff
@@ -491,21 +490,30 @@ where
...
         let val = self.dictionary.keys.value_unchecked(index);
         let value_idx = val.to_usize().unwrap();
-        // Dictionary indexes should be valid
-        self.values.value_unchecked(value_idx)
+
+        // As dictionary keys are only verified for non-null indexes
+        // we must check the value is within bounds
+        match value_idx < self.values.len() {
+            true => self.values.value_unchecked(value_idx),
+            false => Default::default(),
```
Comment (viirya) [inline arrow/src/array/array_dictionary.rs:515]: Looks good. This is less or zero performance impact.
