### PR TITLE
Fix take string on sliced indices

### LINKED ISSUE #1049: Take on strings incorrect on slices
**Describe the bug**

```
#[test]
fn test_take_slice_string() {
    let strings =
        StringArray::from(vec![Some("hello"), None, Some("world"), None, Some("hi")]);
    let indices = Int32Array::from(vec![Some(0), Some(1), None, Some(0), Some(2)]);
    let indices_slice = indices.slice(1, 4);
    let indices_slice = indices_slice
        .as_ref()
        .as_any()
        .downcast_ref::<Int32Array>()
        .unwrap();

    let expected = StringArray::from(vec![None, None, Some("hello"), Some("world")]);
    let result = take(&strings, indices_slice, None).unwrap();
    assert_eq!(result.as_ref(), &expected);
}
```

```
thread 'compute::kernels::take::tests::test_take_slice_string' panicked at 'assertion failed: `(left == right)`
  left: `StringArray
[
  null,
  null,
  null,
  "world",
]`,
 right: `StringArray
[
  null,
  null,
  "hello",
  "world",
]`', arrow/src/compute/kernels/take.rs:1950:9
```

**To Reproduce**

See test. It looks like the null bits aren't being properly shifted when used in the take kernel.

**Expected behavior**

Test passes.

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1049

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-select/src/take.rs [hunk 1]
```diff
@@ -675,12 +673,7 @@ where
             *offset = length_so_far;
         }
 
-        nulls = match indices.data_ref().null_buffer() {
-            Some(buffer) => {
-                Some(buffer_bin_and(buffer, 0, &null_buf.into(), 0, data_len))
```
Comment (tustvold) [inline arrow-select/src/take.rs:680]: The bug is that this doesn't take into account any offset that indices may have.

However, this code is completely redundant as we already check the validity of indices when constructing this mask, and so we can just remove this

**Review by viirya — APPROVED** [review]
