### PR TITLE
fix: Adjust FFI_ArrowArray offset based on the offset of offset buffer

### LINKED ISSUE #5896: Out of range when extending on a slice of string array imported through FFI
**Describe the bug**

We move buffer pointer of offset buffer when slicing a string array and keep data buffer pointer unchanged. When exporting it through FFI, we simply export the moved pointer of the offset buffer.

When importing the array, we calculate the length of data buffer by taking the difference of last offset and first offset in the (slice) offset buffer. Note that the calculated length is not correct.

For example, the original string array's data buffer is 346536 bytes, last offset is 346536. We take a slice of 8192 strings from it, the slice of offsets are `[147456, ..., 294912]`. The calculated length is `294912 - 147456 = 147456`. But actually the length of data buffer is `346536`. So the data buffer of the imported array has incorrect length.

It doesn't cause issues so far because we access imported data buffer using pointers at most time (and we don't actually check the range). But for some cases where we access the data as slice (i.e., `[]`), it will cause runtime panic like:

```
---- ffi::tests_from_ffi::test_extend_imported_string_slice stdout ----
thread 'ffi::tests_from_ffi::test_extend_imported_string_slice' panicked at arrow-data/src/transform/variable_size.rs:38:29:
range end index 10890 out of range for slice of length 5500
``` 

Note `test_extend_imported_string_slice` is new test I added in #5895.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #5896.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-array/src/ffi.rs [hunk 1]
```diff
@@ -1458,4 +1460,58 @@ mod tests_from_ffi {
...
+        let len = array.len();
+        let data = array.to_data();
+
+        let mut mutable = MutableArrayData::new(vec![&data], false, len);
+        mutable.extend(0, 0, len);
+        make_array(mutable.freeze())
+    }
+
+    #[test]
+    fn test_extend_imported_string_slice() {
```
Comment (alamb) [inline arrow-array/src/ffi.rs:1484]: I ran this test without the code changes in this PR and it fails like

```shell
range end index 10890 out of range for slice of length 5500
thread 'ffi::tests_from_ffi::test_extend_imported_string_slice' panicked at arrow-data/src/transform/variable_size.rs:38:29:
range end index 10890 out of range for slice of length 5500
stack backtrace:
```

Thus I believe the test correctly covers the new code

File: arrow-array/src/ffi.rs [hunk 2]
```diff
@@ -1458,4 +1460,58 @@ mod tests_from_ffi {
 
         test_round_trip(&imported_array.consume()?)
     }
+
+    fn export_string(array: StringArray) -> StringArray {
```
Comment (alamb) [inline arrow-array/src/ffi.rs:1464]: Perhaps calling this function  "roundtrip_string_array" would better describe what it does

File: arrow-data/src/ffi.rs [hunk 3]
```diff
@@ -131,6 +131,45 @@ impl FFI_ArrowArray {
...
+        let offset_offset = match data.data_type() {
+            DataType::Utf8 | DataType::Binary => {
+                // Offset buffer is possible a slice of the buffer.
+                // If we use slice pointer as exported buffer pointer, it will cause
+                // the consumer to calculate incorrect length of data buffer (buffer 1).
+                // We need to get the offset of the offset buffer and fill it in
+                // the `FFI_ArrowArray` offset field.
+                Some(unsafe {
+                    let b = &data.buffers()[0];
+                    b.as_ptr().offset_from(b.get_bytes().ptr().as_ptr()) as usize
```
Comment (alamb) [inline arrow-data/src/ffi.rs:144]: I think this calculation assumes that the string data begins at the start of the buffer (aka `b.as_ptr()` is the base). 

I double checked and the comments seem to imply that that is always the case
https://github.com/apache/arrow-rs/blob/c096172b769da8003ea7816086df60f38229a891/arrow-buffer/src/bytes.rs#L40-L39

Since this is calculating on internal state of `Buffer`, I think this code would be easier to understand / document if we added a method to `Buffer` that did the calculation and could be documented better:

Something like
```rust
impl Buffer {
  .. 
  /// Returns the offset, in bytes, of `Self::ptr` to `Self::data`
  ///
  /// self.ptr and self.data can be different in the following cases:
  /// TODO
  fn ptr_offset(&self) -> usize {
...
  }
```

I was non obvious to me when reading the `Buffer` code that it was possible for `ptr` and `data` to be different

File: arrow-buffer/src/buffer/immutable.rs [hunk 4]
```diff
@@ -71,6 +71,11 @@ impl Buffer {
         }
     }
 
+    /// Returns the internal byte buffer.
+    pub fn get_bytes(&self) -> Arc<Bytes> {
```
Comment (alamb) [inline arrow-buffer/src/buffer/immutable.rs:75]: Rather than exposing an internal detail, perhaps we can move the offset calculation into `Buffer` (see suggestion below). In addition to keeping the code more encapsulated, I think it would also likely be faster as it would avoid the Arc clone.

**Review by alamb — APPROVED** [review]
Thank you @viirya  -- I verified that this PR fixes the test case and therefore I think it is an improvement. 

However, I am a bit confused about how the pointer and data buffer can be different so I left some additional comments / suggestions on how we might make that better

**Comment by andygrove** [comment]
Thanks for review @alamb. This is a blocking issue for our first Comet release. Do you think it would be possible to create a patch release of arrow-rs to include this fix (once we are through the review process)?

**Comment by alamb** [comment]
> Thanks for review @alamb. This is a blocking issue for our first Comet release. Do you think it would be possible to create a patch release of arrow-rs to include this fix (once we are through the review process)?

For sure -- I filed https://github.com/apache/arrow-rs/issues/5906 to track the idea

File: arrow-array/src/ffi.rs (hunk 2 above)
Comment (viirya) [reply arrow-array/src/ffi.rs:1464]: Yes, it looks better.

File: arrow-buffer/src/buffer/immutable.rs (hunk 4 above)
Comment (viirya) [reply arrow-buffer/src/buffer/immutable.rs:75]: Good suggestion.

File: arrow-buffer/src/buffer/immutable.rs [hunk 5]
```diff
@@ -71,6 +71,24 @@ impl Buffer {
         }
     }
 
+    /// Returns the offset, in bytes, of `Self::ptr` to `Self::data`
```
Comment (alamb) [inline arrow-buffer/src/buffer/immutable.rs:74]: 👍

File: arrow-data/src/ffi.rs [hunk 6]
```diff
@@ -131,6 +131,43 @@ impl FFI_ArrowArray {
             data.buffers().iter().map(|b| Some(b.clone())).collect()
         };
 
+        // Handle buffer offset for offset buffer.
+        let offset_offset = match data.data_type() {
+            DataType::Utf8 | DataType::Binary => {
+                // Offset buffer is possible a slice of the buffer.
```
Comment (alamb) [inline arrow-data/src/ffi.rs:137]: I think this looks much nicer now

**Review by alamb — APPROVED** [review]

File: arrow-buffer/src/buffer/immutable.rs [hunk 7]
```diff
@@ -71,6 +71,24 @@ impl Buffer {
...
+    ///
+    /// self.ptr and self.data can be different after slicing or advancing the buffer.
+    ///
+    /// # Safety
+    ///
+    /// This function is unsafe as it uses unsafe function `offset_from`. Under certain
+    /// conditions, this function can cause undefined behavior. See the documentation of
+    /// `offset_from` for more information.
+    pub unsafe fn ptr_offset(&self) -> usize {
```
Comment (jhorstmann) [inline arrow-buffer/src/buffer/immutable.rs:83]: I'm wondering if this function should be `unsafe`. The `ptr` should always be in bounds of `data`, any safe function that modifies `ptr` should uphold that invariant. If it is not in bounds then nearly all other methods of `Buffer` would also expose UB.

Comment (viirya) [reply arrow-buffer/src/buffer/immutable.rs:83]: Makes sense. `slice`, `advance` and `slice_with_length` even `as_ptr` are all safe functions.

**Comment by viirya** [comment]
Thanks @alamb @andygrove @jhorstmann

**Comment by tustvold** [comment]
I intend to take a closer look at this tomorrow, as I'm not entirely sure it is correct

**Comment by viirya** [comment]
Let me know if you have any question about the issue we encountered.
