### PR TITLE
Return an error instead of a panic when reading a corrupted Parquet file with mismatched column counts

### LINKED ISSUE #5315: `ParquetRecordBatchStreamBuilder::new()` panics instead of erroring out when opening a corrupted file
When opening a corrupted Parquet file where one of the row groups is missing a column, `ParquetRecordBatchStreamBuilder::new()` panics instead of returning an error:

```
 A panic occurred at (...)\parquet-50.0.0\src\file\metadata.rs:352: assertion `left == right` failed
  left: 2
 right: 1
```

This is due to the `RowGroupMetaData::from_thrift()` validating column counts using the `assert_eq!()` macro:
https://github.com/apache/arrow-rs/blob/639e81e98c0962a2401f542dc1b7abcac4d3ea25/parquet/src/file/metadata.rs#L352

Could the check be replaced by an `if` statement returning an error? If that sounds OK, I can prepare a PR for review.

As workaround, it is possible to unwind the panic and handle it almost like a regular error. Unwinding async code is not straightforward though and it would be simpler to allow consistent error handling.

```rust
    let async_panic_handler = AssertUnwindSafe(async { ParquetRecordBatchStreamBuilder::new(blob_reader).await }).catch_unwind().await;
    if async_panic_handler.is_err() {
        info!("Skipping Blob (invalid metadata)");
        return Ok(())
    }
    let parquet_builder = async_panic_handler.unwrap()?;
```

### PR DESCRIPTION
**Pull request by mmaitre314**
# Which issue does this PR close?

Closes #5315

# Rationale for this change

Data pipelines reading Parquet files may encounter corrupted Parquet files as part of their regular activities and be resilient to them through graceful handling (ex: emit telemetry and skip the files). This behavior is more natural to implement when the Parquet crate returns an error instead of a panic.

# What changes are included in this PR?

Replace an assert with an if statement.

# Are there any user-facing changes?

Caller receives an error instead of a panic.

### CODE REVIEW

File: parquet/src/file/metadata.rs [hunk 1]
```diff
@@ -349,7 +349,13 @@ impl RowGroupMetaData {
 
     /// Method to convert from Thrift.
     pub fn from_thrift(schema_descr: SchemaDescPtr, mut rg: RowGroup) -> Result<RowGroupMetaData> {
-        assert_eq!(schema_descr.num_columns(), rg.columns.len());
+        if schema_descr.num_columns() != rg.columns.len() {
+            return Err(general_err!(
+                "Column length mismatch. Schema has {} columns while Row Group has {}",
```
Comment (Jefffrey) [inline parquet/src/file/metadata.rs:354]:
```suggestion
                "Column count mismatch. Schema has {} columns while Row Group has {}",
```

nit: count seems a better descriptor than length (column length made me first think of size of column, instead of number of columns)

**Review by Jefffrey — APPROVED** [review]
Looks good :+1:
