### PR TITLE
Preserve empty list array elements in take kernel

### LINKED ISSUE #3471: take kernel on List array introduces nulls instead of empty lists
**Describe the bug**
In looking into https://github.com/apache/arrow-datafusion/issues/4828, I came across what I think is an issue with the `take` kernel when operating on List arrays.  It seems that when a taken element of the list array is an empty list, the value becomes `null` in the result of take.

I think this is a bug, but let me know if it's the intended behavior.

**To Reproduce**
Here is an example that stats with the list array: `[[0], [], [1]]` and takes elements `[0, 1, 2]`.

```rust
use arrow::array::{Int32Array, Int32Builder, ListBuilder};
use arrow::compute::take;

#[test]
fn test_take() {
    let mut val_builder = Int32Builder::new();
    let mut list_builder = ListBuilder::new(val_builder);
    list_builder.values().append_value(0);
    list_builder.append(true);
    list_builder.append(true);
    list_builder.values().append_value(1);
    list_builder.append(true);
    let list = list_builder.finish();

    println!("list: {:?}", list);
    let indices = Int32Array::from(vec![0, 1, 2]);
    let taken = take(&list, &indices, None).unwrap();

    println!("taken: {:?}", taken);
}
```
output
```
list: ListArray
[
  PrimitiveArray<Int32>
[
  0,
],
  PrimitiveArray<Int32>
[
],
  PrimitiveArray<Int32>
[
  1,
],
]

taken: ListArray
[
  PrimitiveArray<Int32>
[
  0,
],
  null,
  PrimitiveArray<Int32>
[
  1,
],
]
```

**Expected behavior**
I would expect the result to be the same as the input (`[[0], [], [1]]`), but instead the result is `[[0], null, [1]`.

**Additional context**
It looks like this behavior is the result of 

https://github.com/apache/arrow-rs/blob/2d2d0a3ba72efb5ee82324064f7c7678c2dd8336/arrow-select/src/take.rs#L706-L710

### PR DESCRIPTION
**Pull request by jonmmease**
# Which issue does this PR close?

Closes #3471.

# What changes are included in this PR?

74bad75429f52cda53f66a2b4a794ec6d56ef5ff update the `test_take_slice_string` test to include an extra empty list element. This fails on its own as the empty list is converted to a `null` in `take`

290d6cca64c89b415abe52c279ec903f888c9568 and b01f9e59d1c15fcc757adf4569a936594a7b449b fix the null buffer for the input data in `test_take_list_with_nulls` and `test_take_list_with_value_nulls` respectively.  The previous implementation of `take` for lists actually ignores the null mask of the input list array, so my guess is that it why it wasn't noticed that these masks don't match the intended arrays expressed in the surrounding comments. Without these fixes the change below causes these tests to fail, but I think that's expected given the null masks that were previously provided.

2ff14fa4cda8e77fd4c23b2f9951f437225b74d5 moves the calculation of the null buffer into `take_value_indices_from_list` where we have access to the null info of both the indices and list array.

# Are there any user-facing changes?
This is a bug fix, but could be considered breaking as it's been around for a while and downstream code has likely adapted to the behavior.

### CODE REVIEW

File: arrow-select/src/take.rs [hunk 1]
```diff
@@ -1682,7 +1685,7 @@ mod tests {
             let list_data = ArrayData::builder(list_data_type.clone())
                 .len(4)
                 .add_buffer(value_offsets)
-                .null_bit_buffer(Some(Buffer::from([0b01111101])))
+                .null_bit_buffer(Some(Buffer::from([0b11111011])))
```
Comment (jonmmease) [inline arrow-select/src/take.rs:1688]: The intended array here is `[[0,null,0], [-1,-2,3], null, [5,null]]`, where only the third element is `null`.

File: arrow-select/src/take.rs [hunk 2]
```diff
@@ -831,10 +815,18 @@ where
 /// Where a list array has indices `[0,2,5,10]`, taking indices of `[2,0]` returns
 /// an array of the indices `[5..10, 0..2]` and offsets `[0,5,7]` (5 elements and 2
 /// elements)
+#[allow(clippy::type_complexity)]
```
Comment (jonmmease) [inline arrow-select/src/take.rs:818]: Let me know if you'd like the return type here refactored with `type` definitions instead of ignoring the clippy lint

Comment (tustvold) [reply arrow-select/src/take.rs:818]: I think it would be helpful to at least have some documentation of what the various fields are.

File: arrow-select/src/take.rs [hunk 3]
```diff
@@ -850,6 +842,12 @@ where
     let mut current_offset = OffsetType::Native::zero();
     // add first offset
     new_offsets.push(OffsetType::Native::zero());
+
+    // Initialize null buffer
+    let num_bytes = bit_util::ceil(indices.len(), 8);
+    let mut null_buf = MutableBuffer::new(num_bytes).with_bitset(num_bytes, true);
+    let null_slice = null_buf.as_slice_mut();
+
```
Comment (tustvold) [inline arrow-select/src/take.rs:850]: Rather than moving this into here, I think it might be faster and simpler to use `take_bits` on the list null buffer

File: arrow-select/src/take.rs [hunk 4]
```diff
@@ -691,27 +691,11 @@ where
...
-                if window[0] == window[1] {
-                    // offsets are equal, slot is null
-                    bit_util::unset_bit(null_slice, i);
-                    null_count += 1;
-                }
-            },
-        );
-    }
-    let value_offsets = Buffer::from_slice_ref(&offsets);
+    let value_offsets = Buffer::from_slice_ref(offsets);
```
Comment (tustvold) [inline arrow-select/src/take.rs:698]: Not something from this PR, but it occurs to me that it would be better for take_value_indices_from_list to simply build and return this buffer, e.g. using BufferBuilder, instead of this additional copy.

**Review by tustvold — APPROVED** [review]
Thank you for this, this looks good to me. I left some minor comments on how it could be improved further, but I'm happy for this to go in as is

**Comment by jonmmease** [comment]
Thanks for looking it over and for the comments @tustvold, I'll give it another pass in a few hours

**Comment by jonmmease** [comment]
I added a comment on the return types, but I wasn't confident in making the other changes.  Feel free to commit onto this branch if you want to do any other cleanup. Thanks again!

File: arrow-select/src/take.rs (hunk 3 above)
Comment (jonmmease) [reply arrow-select/src/take.rs:850]: I thought about this, but we also need to handle the indices being null. So I think we'd need to perform an AND operation between the result of `take_bits` on the list's null buffer and the indices null buffer. And that seemed a bit more complex.

Comment (tustvold) [reply arrow-select/src/take.rs:850]: I thought that is what take_bits did, but my memory is a little hazy

**Comment by tustvold** [comment]
Thanks again, if I have some spare cycles I'll take a stab at using take_bits, but I think regardless this PR represents a major improvement :+1:
