### PR TITLE
Return NotFound for directories in Head and Get (#4230)

### LINKED ISSUE #4230: ObjectStore::head Returns Directory for LocalFileSystem and Hierarchical Azure
**Describe the bug**

ObjectStore::head returns an `ObjectMeta` for directories in `LocalFileSystem` and hierarchical azure namespaces

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4230

# Rationale for this change
 

I spent a non-trivial amount of time helping diagnose an issue with https://github.com/apache/arrow-datafusion/pull/6183 that boiled down to a head request being made instead of a list request, because the `ListingTableUrl` didn't end with a `/`. Normally this would have returned a 404 NotFound which would have made the issue easy to identify, however, because it was an Azure hierarchical namespace this didn't occur.

LocalFileSystem also runs into a similar issue.

# What changes are included in this PR?

# Are there any user-facing changes?

LocalFileSystem and MicrosoftAzure will no longer return directories for get and head requests

### CODE REVIEW

File: object_store/src/local.rs [hunk 1]
```diff
@@ -878,19 +883,25 @@ fn read_range(file: &mut File, path: &PathBuf, range: Range<usize>) -> Result<By
 }
 
 fn open_file(path: &PathBuf) -> Result<File> {
-    let file = File::open(path).map_err(|e| {
-        if e.kind() == std::io::ErrorKind::NotFound {
-            Error::NotFound {
+    let file = match File::open(path).and_then(|f| Ok((f.metadata()?, f))) {
```
Comment (tustvold) [inline object_store/src/local.rs:886]: This is potentially slightly unfortunate, in that we require an additional syscall, but I couldn't find a mechanism to only open files

File: object_store/src/azure/client.rs [hunk 2]
```diff
@@ -257,7 +257,19 @@ impl AzureClient {
                 path: path.as_ref(),
             })?;
 
-        Ok(response)
+        match response.headers().get("x-ms-resource-type") {
+            Some(resource) if resource.as_ref() != b"file" => {
+                Err(crate::Error::NotFound {
+                    path: path.to_string(),
+                    source: format!(
+                        "Not a directory, got x-ms-resource-type: {}",
```
Comment (kylebrooks-8451) [inline object_store/src/azure/client.rs:265]: Should this be, "Not a file"?

Comment (tustvold) [reply object_store/src/azure/client.rs:265]: Oops lol

**Review by wjones127 — APPROVED** [review]
