### PR TITLE
Fix LocalFileSystem with range request that ends beyond end of file

### LINKED ISSUE #6749: LocalFileSystem errors with satisfiable range request
**Describe the bug**

The `LocalFileSystem` fails to return data when a byte range starts before the end of the file.

**To Reproduce**

```rs
    #[tokio::test]
    async fn range_request_beyond_end_of_file() {
        let root = TempDir::new().unwrap();
        let integration = LocalFileSystem::new_with_prefix(root.path()).unwrap();

        let location = Path::from("some_file");

        let data = Bytes::from("arbitrary data");

        integration
            .put(&location, data.clone().into())
            .await
            .unwrap();

        let read_data = integration.get_range(&location, 0..100).await.unwrap();
        assert_eq!(&*read_data, data);
    }
```

This currently fails with

```
called `Result::unwrap()` on an `Err` value: Generic { store: "LocalFileSystem", source: OutOfRange { path: "/private/var/folders/42/5jr6891d4ds4xysz7q0rsghw0000gn/T/.tmpK2eHCc/some_file", expected: 100, actual: 14 } }
```

**Expected behavior**

In line with the HTTP spec and other object stores, the `LocalFileSystem` should return the satisfiable part of the range request.

**Additional context**

Some discussion in Discord: https://discord.com/channels/885562378132000778/885562378132000781/1308082632898248836

### PR DESCRIPTION
**Pull request by kylebarron**
# Which issue does this PR close?

Closes #6749.

# Rationale for this change

Make `LocalFileSystem` act the same as other object store backends. 

# What changes are included in this PR?

Allow `LocalFileSystem` to return a satisfiable byte range beyond the end of the file.

Add new test for satisfiable and non-satisfiable byte range.

# Are there any user-facing changes?

No.

### CODE REVIEW

File: object_store/src/local.rs [hunk 1]
```diff
@@ -897,23 +897,26 @@ pub(crate) fn chunked_stream(
...
 
-    let mut buf = Vec::with_capacity(to_read);
-    let read = file
-        .take(to_read as u64)
-        .read_to_end(&mut buf)
-        .context(UnableToReadBytesSnafu { path })?;
-
     ensure!(
-        read == to_read,
+        seek_idx == range.start as u64,
```
Comment (etseidl) [inline object_store/src/local.rs:905]: It appears this will always be true, even if seeking beyond EOF.

File: object_store/src/local.rs [hunk 2]
```diff
@@ -897,23 +897,26 @@ pub(crate) fn chunked_stream(
...
-            actual: read
+            expected: range.start,
+            actual: seek_idx as usize
         }
     );
+
+    let mut buf = Vec::with_capacity(to_read);
+    file.take(to_read as u64)
+        .read_to_end(&mut buf)
+        .context(UnableToReadBytesSnafu { path })?;
```
Comment (etseidl) [inline object_store/src/local.rs:916]: Likewise, this read will simply return 0 when reading beyond EOF.

**Review by etseidl — COMMENTED** [review]
It seems like several tests are failing because neither the seek nor the read return an error when seeking/reading beyond the end of the file. The `Seek` and `Read` traits seem to allow operations beyond EOF...read in particular will simply return 0 rather than produce an error. Perhaps `read_range` should not test the number of bytes returned at all and return what it can, leaving it up to the caller to detect when a read returns fewer bytes than requested and act accordingly. 🤷

**Comment by alamb** [comment]
🤔  the CI failures appear to be real

**Comment by kylebarron** [comment]
I updated this to use `File::metadata` to access the length of the file and tests now pass locally for me.

**Review by etseidl — APPROVED** [review]
Looks good to me, and is now passing tests.

**Comment by alamb** [comment]
❤️  --- thanks @kylebarron  and @etseidl for the review!
