### PR TITLE
fix: export record batch through stream

### LINKED ISSUE #4805: pyarrow module can't roundtrip tensor arrays
**Describe the bug**

When exporting a tensor array (a kind of extension array) as a record batch, PyArrow segfaults. This does not happen if the batch is exported as a stream.

**To Reproduce**

The following test will fail in `arrow-pyarrow-integration-testing/tests/test_sql.py`:

```python
def test_tensor_array():
    tensor_type = pa.fixed_shape_tensor(pa.float32(), [2, 3])
    inner = pa.array([float(x) for x in range(1, 7)] + [None] * 12, pa.float32())
    storage = pa.FixedSizeListArray.from_arrays(inner, 6)
    f32_array = pa.ExtensionArray.from_storage(tensor_type, storage)

    # Round-tripping as an array gives back storage type, because arrow-rs has
    # no notion of extension types.
    b = rust.round_trip_array(f32_array)
    assert b == f32_array.storage

    batch = pa.record_batch([f32_array], ["tensor"])
    b = rust.round_trip_record_batch(batch)
    assert b == batch

    del b
```

**Expected behavior**

We should round trip the array type successfully.

**Additional context**

The record batch exporting is done by exporting each individual array, but this separates the extension arrays from their metadata. I suspect PyArrow segfaults because it is receiving a plain array and then later told it is an extension in the final schema.

### PR DESCRIPTION
**Pull request by wjones127**
# Which issue does this PR close?

Closes #4805.

# Rationale for this change
 
To export extension arrays properly, we need to expose the arrays together *with* the schema, not separately.

# What changes are included in this PR?

RecordBatch is now exported to PyArrow using an array stream rather than exporting each array individually.

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/pyarrow.rs [hunk 1]
```diff
@@ -270,25 +270,13 @@ impl FromPyArrow for RecordBatch {
...
-            py_arrays.push(array.to_data().to_pyarrow(py)?);
-        }
-
-        let py_schema = schema.to_pyarrow(py)?;
-
-        let module = py.import("pyarrow")?;
-        let class = module.getattr("RecordBatch")?;
-        let args = (py_arrays,);
-        let kwargs = PyDict::new(py);
-        kwargs.set_item("schema", py_schema)?;
```
Comment (tustvold) [inline arrow/src/pyarrow.rs:288]: Why doesn't this work? Surely this should set the schema appropriately?

File: arrow-pyarrow-integration-testing/tests/test_sql.py [hunk 2]
```diff
@@ -393,6 +393,23 @@ def test_sparse_union_python():
     del a
     del b
 
+def test_tensor_array():
+    tensor_type = pa.fixed_shape_tensor(pa.float32(), [2, 3])
+    inner = pa.array([float(x) for x in range(1, 7)] + [None] * 12, pa.float32())
+    storage = pa.FixedSizeListArray.from_arrays(inner, 6)
+    f32_array = pa.ExtensionArray.from_storage(tensor_type, storage)
+
+    # Round-tripping as an array gives back storage type, because arrow-rs has
```
Comment (tustvold) [inline arrow-pyarrow-integration-testing/tests/test_sql.py:402]: I think I must be missing something fundamental here, an array can only have the storage type??

File: arrow-pyarrow-integration-testing/tests/test_sql.py [hunk 3]
```diff
@@ -393,6 +393,23 @@ def test_sparse_union_python():
     del a
     del b
 
+def test_tensor_array():
+    tensor_type = pa.fixed_shape_tensor(pa.float32(), [2, 3])
+    inner = pa.array([float(x) for x in range(1, 7)] + [None] * 12, pa.float32())
+    storage = pa.FixedSizeListArray.from_arrays(inner, 6)
+    f32_array = pa.ExtensionArray.from_storage(tensor_type, storage)
```
Comment (tustvold) [inline arrow-pyarrow-integration-testing/tests/test_sql.py:400]: Just as an observation, it is rather strange to me that extension arrays would be a first-class abstraction and in so doing erase the underlying storage type

Comment (wjones127) [reply arrow-pyarrow-integration-testing/tests/test_sql.py:400]: > it is rather strange to me that extension arrays would be a first-class abstraction and in so doing obfuscate the underlying storage type

I think for systems where RecordBatch is a type exposed to end-users at the interface, the obfuscation is a feature, not a bug.

File: arrow/src/pyarrow.rs (hunk 1 above)
Comment (wjones127) [reply arrow/src/pyarrow.rs:288]: Basically, PyArrow considers there to be a mismatch if passed a schema with an extension type but the arrays passed are all storage arrays. 

I created an issue in PyArrow's tracker to fix this:
https://github.com/apache/arrow/issues/37669

In theory, this code should be fine, so we can consider this a workaround for a bug in PyArrow 😁

File: arrow-pyarrow-integration-testing/tests/test_sql.py (hunk 2 above)
Comment (wjones127) [reply arrow-pyarrow-integration-testing/tests/test_sql.py:402]: You mean because the extension metadata is in the field metadata, and thus separate from the Array? Arrays typically have a DataType associated with it, so this depends on whether your Arrow implementation has an `Extension` variant of `DataType` or not. Arrow C++ and arrow2 do, arrow-rs doesn't.

It actually looks like Arrow C++ exports `DataType` with the extension metadata:

https://github.com/apache/arrow/blob/b7581fee01ed0d111d5a0361c2f05779aa3c33e8/cpp/src/arrow/c/bridge.cc#L189
https://github.com/apache/arrow/blob/b7581fee01ed0d111d5a0361c2f05779aa3c33e8/cpp/src/arrow/c/bridge.cc#L243-L252

So if arrow-rs had an `Extension` variant of data type, we could do the same and thus arrays themselves could be exported as extension arrays. Of course, that opens whole different can or worms, as discussed in https://github.com/apache/arrow-rs/issues/4472

File: arrow/src/pyarrow.rs (hunk 1 above)
Comment (tustvold) [reply arrow/src/pyarrow.rs:288]: Perhaps we could link to the upstream bug in the code? So that we can potentially avoid this at some point in the future

File: arrow-pyarrow-integration-testing/tests/test_sql.py (hunk 3 above)
Comment (tustvold) [reply arrow-pyarrow-integration-testing/tests/test_sql.py:400]: Yeah, it is unfortunate that arrow doesn't have a clear separation between logical and physical types. IMO DataType is a physical type, whereas extension types are definitely in the category of logical types, it's a bit of a mess :sweat_smile:

File: arrow/src/pyarrow.rs [hunk 4]
```diff
@@ -270,25 +270,13 @@ impl FromPyArrow for RecordBatch {
...
-        let record = class.call_method("from_arrays", args, Some(kwargs))?;
-
-        Ok(PyObject::from(record))
+        // arrow::ffi is implemented for Arrays not RecordBatches, so the next
+        // best thing is to wrap it in a RecordBatchIterator and export that.
```
Comment (tustvold) [inline arrow/src/pyarrow.rs:274]:
```suggestion
        // Workaround apache/arrow#37669 by returning RecordBatchIterator
```
