### PR TITLE
Fix multipart uploads with checksums on object locked buckets

### LINKED ISSUE #6793: Multi-part s3 uploads fail when using checksum
**Describe the bug**

`with_checksum_algorithm()` fails when used in with `put_multipart_opts()` on large files

**To Reproduce**

1. Set standard AWS env vars
2. Run test
3. observe:

```
message: "Checksum Type mismatch occurred, expected checksum Type: null, actual checksum Type: sha256
```

**Expected behavior**

It should write the file

**Additional context**

See PR for failing test

### PR DESCRIPTION
**Pull request by avantgardnerio**
# Which issue does this PR close?

Closes #6793.

# Rationale for this change
 
Described in issue

# What changes are included in this PR?

A failing test

# Are there any user-facing changes?

Multipart uploads fail

### CODE REVIEW

**Comment by thinkharderdev** [comment]
So there are a couple of issues with how multi-part upload is implemented:

1. The initial `PUT` request to `CreateMultipartUpload` must specify the checksum algo or else calling `PutPart` with the checksum will fail
2. When calling `CompleteMultipartUpload` we need to send all the part checksums in the request (see `https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html)

So this means that we need to keep the checksums in the `PartId` for when we complete the upload

**Comment by tustvold** [comment]
I'm not sure about this, an AWS specific detail now leaks into the public trait for all stores... It also is not immediately obvious when the checksums are needed or not...

I think this needs a bit more thought, I'll try to find some time in the next few weeks

**Comment by avantgardnerio** [comment]
> this, an AWS specific detail now leaks into the public trait for all stores... It also is not immediately obvious when the checksums are needed or not...

FWIW: I verified in the new tests we are now writing the checksums at the correct times for when the digest functionality is enabled. 

Now I am just trying to get the original tests working for when it isn't.

File: object_store/src/multipart.rs [hunk 1]
```diff
@@ -21,18 +21,36 @@
...
 
+/// Represents a part of a file that has been successfully uploaded in a multipart upload process.
+#[derive(Debug)]
+pub struct MultipartInfo {
+    /// Id of this part
+    pub e_tag: String,
+    /// Index of the part + 1
+    pub part_number: usize,
+    /// 256 bit SHA of the contents
+    pub checksum_sha256: Option<String>,
```
Comment (thinkharderdev) [inline object_store/src/multipart.rs:43]: Probably shouldn't assume this is a `sha256` checksum. Maybe just rename to `checksum` and let it be opaque.

**Comment by thinkharderdev** [comment]
> It also is not immediately obvious when the checksums are needed or not...

The AWS docs are not very helpful here but we pieced together that to write to an S3 bucket using multi-part with object locking enabled you need to:

1. Specify the checksum algo in the initial API call to `CreateMultiPartUpload`
2. Send the checksum for each part while calling `PutPart`
3. When calling `CompleteMultipartUpload` you need to send the checksum again for each part that was uploaded

The current implementation does 2 but not 1 or 3.

**Comment by avantgardnerio** [comment]
> The current implementation does 2 but not 1 or 3.

I'd like to re-iterate that this PR is functionally complete. Although I am unsure about the docs, I am sure it works.

Now I'm just trying to fix the existing `s3_test`.

**Comment by thinkharderdev** [comment]
> > The current implementation does 2 but not 1 or 3.
> 
> I'd like to re-iterate that this PR is functionally complete. Although I am unsure about the docs, I am sure it works.
> 
> Now I'm just trying to fix the existing `s3_test`.

Sorry, by current implementation I meant what is on `master` not what is in this PR (which does it correctly) 😄 

Was just trying to clarify for @tustvold based on his earlier comment

**Comment by tustvold** [comment]
> Was just trying to clarify for @tustvold based on his earlier comment

Right, my comment pertained to the changes to the public API, we now have a somewhat peculiar quirk of AWS leaking out into the public API in a manner that also makes it very unclear when or if I need to specify the checksum or not. I need to find some time to sit down and think about how we could support this, ideally without making a breaking API change.

**Comment by tustvold** [comment]
So I think there is an less intrusive way to support this.

UploadPart is not an issue as the per-part meta is never exposed.

The issue solely concerns MultipartStore, in particular how to carry the checksum through https://docs.rs/object_store/latest/object_store/multipart/struct.PartId.html.

Now we could add a checksum field to this, but this would be a breaking change. However, the content id is intentionally opaque. We could therefore just use the XML encoded https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompletedPart.html instead of an ETag when necessary.

There would need to still be logic to handle an ETag based PartId, as these may have been stored in a database, but when checksums, but detecting this should be trivial e.g. by attempting to decode the XML.

This would avoid needing to make any breaking changes, whilst also being future proof for any of the other checksum types

File: object_store/src/aws/client.rs [hunk 2]
```diff
@@ -645,9 +670,13 @@ impl S3Client {
     ) -> Result<PartId> {
         let is_copy = matches!(data, PutPartPayload::Copy(_));
         let part = (part_idx + 1).to_string();
+        let config = S3Config {
+            checksum: Some(Checksum::SHA256),
+            ..self.config.clone()
+        };
```
Comment (tustvold) [inline object_store/src/aws/client.rs:676]: Why this change?

File: object_store/src/aws/client.rs [hunk 3]
```diff
@@ -616,9 +637,13 @@ impl S3Client {
         &self,
         location: &Path,
         opts: PutMultipartOpts,
+        checksum: bool,
```
Comment (tustvold) [inline object_store/src/aws/client.rs:640]: Why can't we inspect `self.config`?

File: object_store/src/aws/client.rs (hunk 2 above)
Comment (avantgardnerio) [reply object_store/src/aws/client.rs:676]: Put multipart won't pass on object locked buckets without it, so I figured may as well just always add it, lest we have more plumbing (which is also fine with me) to selectively enable it.

File: object_store/src/aws/client.rs (hunk 3 above)
Comment (tustvold) [reply object_store/src/aws/client.rs:640]: Why does it need to be false?

File: object_store/src/aws/client.rs (hunk 2 above)
Comment (tustvold) [reply object_store/src/aws/client.rs:676]: Surely we should only specify it if checksums have been enabled on the builder?

File: object_store/src/aws/client.rs [hunk 4]
```diff
@@ -682,6 +716,10 @@ impl S3Client {
                 response.e_tag
             }
         };
+
+        let meta = PartMetadata { e_tag, checksum };
+        let content_id = quick_xml::se::to_string(&meta).unwrap();
```
Comment (tustvold) [inline object_store/src/aws/client.rs:721]: This logic should only be enabled if checksums are enabled

**Review by tustvold — COMMENTED** [review]
I think it is important we don't add implicit checksum enablement, not only because this could break workloads (e.g. those that aren't actually S3), but also because S3 recently added a load of new checksum algorithms

File: object_store/src/aws/client.rs (hunk 3 above)
Comment (avantgardnerio) [reply object_store/src/aws/client.rs:640]: When you're uploading parts, it seems to want it set to the checksum of the data in the part. When you're doing a copy, it does not

Comment (avantgardnerio) [reply object_store/src/aws/client.rs]: I was wrong. This code has been removed.

File: object_store/src/aws/client.rs [hunk 5]
```diff
@@ -669,8 +672,13 @@ impl S3Client {
             request = request.with_encryption_headers();
         }
         let response = request.send().await?;
+        let checksum = response
+            .headers()
+            .get(SHA256_CHECKSUM)
+            .and_then(|v| v.to_str().ok())
```
Comment (avantgardnerio) [inline object_store/src/aws/client.rs:678]: Do we need to unwind these errors or swallow them?

File: object_store/src/aws/client.rs [hunk 6]
```diff
@@ -682,6 +690,14 @@ impl S3Client {
                 response.e_tag
             }
         };
+
+        let content_id = if self.config.checksum == Some(Checksum::SHA256) {
+            let meta = PartMetadata { e_tag, checksum };
```
Comment (avantgardnerio) [inline object_store/src/aws/client.rs:695]: For future proofing, we might want to set `PartMetadata::algorithm`...

File: object_store/src/aws/client.rs [hunk 7]
```diff
@@ -617,8 +617,11 @@ impl S3Client {
         location: &Path,
         opts: PutMultipartOpts,
     ) -> Result<MultipartId> {
-        let response = self
-            .request(Method::POST, location)
+        let mut reqquest = self.request(Method::POST, location);
+        if let Some(algorithm) = self.config.checksum {
+            reqquest = reqquest.header(ALGORITHM, &algorithm.to_string().to_uppercase());
```
[the remark this answers is not in the document]
Comment (Dandandan) [reply object_store/src/aws/client.rs:622]: * AFAIK you can do `algorithm.to_uppercase()` to avoid one allocation
* I think it's better to match against `algorithm` to create a `SHA256`

File: object_store/src/client/s3.rs [hunk 8]
```diff
@@ -106,14 +106,32 @@ pub(crate) struct CompleteMultipartUpload {
     pub part: Vec<MultipartPart>,
 }
 
+#[derive(Serialize, Deserialize)]
+pub(crate) struct PartMetadata {
+    pub e_tag: String,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub checksum: Option<String>,
```
Comment (tustvold) [inline object_store/src/client/s3.rs:113]:
```suggestion
    pub checksum_sha256: Option<String>,
```

File: object_store/src/aws/client.rs [hunk 9]
```diff
@@ -617,8 +617,15 @@ impl S3Client {
         location: &Path,
         opts: PutMultipartOpts,
     ) -> Result<MultipartId> {
-        let response = self
-            .request(Method::POST, location)
+        let mut reqquest = self.request(Method::POST, location);
```
Comment (tustvold) [inline object_store/src/aws/client.rs:620]:
```suggestion
        let mut request = self.request(Method::POST, location);
```

**Review by tustvold — APPROVED** [review]
Just some minor nits

**Comment by avantgardnerio** [comment]
@tustvold some unrelated tests started failing. Do you know what's up?

https://github.com/apache/arrow-rs/actions/runs/12221975779/job/34091689971?pr=6794

**Review by thinkharderdev — APPROVED** [review]
