### PR TITLE
Infer timestamps from CSV files

### LINKED ISSUE #1060: csv reader does not detect ISO date strings as timestamps
**Describe the bug**
If a column has dates like "2021-12-19 13:12:30.921" they are not treated as dates/timestamps by the reader (unlike in other clients like python or javascript)

**To Reproduce**
I ran into this trying to run csv2parquet on a csv with dates formatted as above
https://github.com/domoritz/csv2parquet

**Expected behavior**
Expect to get TIMESTAMP values

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #1060

# Rationale for this change
 

Like Pyarrow, be able to infer timestamps from CSV files (with a bit more flexibility in the default format that is used for inferring from values)

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-csv/src/reader.rs [hunk 1]
```diff
@@ -70,9 +70,11 @@ lazy_static! {
         .case_insensitive(true)
         .build()
         .unwrap();
-    static ref DATE_RE: Regex = Regex::new(r"^\d{4}-\d\d-\d\d$").unwrap();
+    static ref DATE32_RE: Regex = Regex::new(r"^\d{4}-\d\d-\d\d$").unwrap();
+    static ref DATE64_RE: Regex =
+        Regex::new(r"^\d{4}-\d\d-\d\d(T|\s)\d\d:\d\d:\d\d$").unwrap();
     static ref DATETIME_RE: Regex =
-        Regex::new(r"^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d$").unwrap();
+        Regex::new(r"^\d{4}-\d\d-\d\d(T|\s)\d\d:\d\d:\d\d(.\d{1,9})?$").unwrap();
```
Comment (tustvold) [inline arrow-csv/src/reader.rs:77]:
```suggestion
        Regex::new(r"^\d{4}-\d\d-\d\d[T ]\d\d:\d\d:\d\d(.\d{1,9})?$").unwrap();
```

Or at the very least a non-capturing group. I also think it should probably be ` ` instead of `\s` as things like `\n` or `\t` I don't think would parse correctly.

File: arrow-csv/src/reader.rs [hunk 2]
```diff
@@ -90,10 +92,12 @@ fn infer_field_schema(string: &str, datetime_re: Option<Regex>) -> DataType {
         DataType::Float64
     } else if INTEGER_RE.is_match(string) {
         DataType::Int64
-    } else if datetime_re.is_match(string) {
-        DataType::Date64
-    } else if DATE_RE.is_match(string) {
+    } else if DATE32_RE.is_match(string) {
```
Comment (tustvold) [inline arrow-csv/src/reader.rs:95]: FWIW I created #3211 to track using a RegexSet here, as the current code is rather wasteful, perhaps something for a follow on PR?

File: arrow-csv/src/reader.rs [hunk 3]
```diff
@@ -70,9 +70,11 @@ lazy_static! {
         .case_insensitive(true)
         .build()
         .unwrap();
-    static ref DATE_RE: Regex = Regex::new(r"^\d{4}-\d\d-\d\d$").unwrap();
+    static ref DATE32_RE: Regex = Regex::new(r"^\d{4}-\d\d-\d\d$").unwrap();
+    static ref DATE64_RE: Regex =
+        Regex::new(r"^\d{4}-\d\d-\d\d(T|\s)\d\d:\d\d:\d\d$").unwrap();
```
Comment (tustvold) [inline arrow-csv/src/reader.rs:75]:
```suggestion
        Regex::new(r"^\d{4}-\d\d-\d\d[T ]\d\d:\d\d:\d\d$").unwrap();
```

**Review by tustvold — APPROVED** [review]
Minor nit to remove unnecessary capture groups

File: arrow-csv/src/reader.rs (hunk 2 above)
Comment (Jefffrey) [reply arrow-csv/src/reader.rs:95]: Ah didn't know about RegexSet, I can give it a shot in this PR a bit later
