### PR TITLE
 parquet: Optimized ByteArrayReader, Add UTF-8 Validation (#1040) 

### LINKED ISSUE #786: Soundness: reading parquet with invalid utf8 results in UB
```rust
use std::sync::Arc;

use parquet::arrow::*;
use parquet::file::reader::SerializedFileReader;
use parquet::file::serialized_reader::SliceableCursor;

fn read(buffer: Arc<Vec<u8>>, column: usize) {
    let file = SliceableCursor::new(buffer);

    let file_reader = SerializedFileReader::new(file).unwrap();
    let mut arrow_reader = ParquetFileArrowReader::new(Arc::new(file_reader));

    let mut record_batch_reader = arrow_reader
        .get_record_reader_by_columns(vec![column], 10)
        .unwrap();

    let batch = record_batch_reader.next().unwrap().unwrap();
    println!("{:?}", batch.column(0));
}

fn main() {
    // a parquet file with 1 column with invalid utf8
    let data = vec![
        80, 65, 82, 49, 21, 6, 21, 22, 21, 22, 92, 21, 2, 21, 0, 21, 2, 21, 0, 21, 4, 21,
        0, 18, 28, 54, 0, 40, 5, 104, 101, 255, 108, 111, 24, 5, 104, 101, 255, 108, 111,
        0, 0, 0, 3, 1, 5, 0, 0, 0, 104, 101, 255, 108, 111, 38, 110, 28, 21, 12, 25, 37,
        6, 0, 25, 24, 2, 99, 49, 21, 0, 22, 2, 22, 102, 22, 102, 38, 8, 60, 54, 0, 40, 5,
        104, 101, 255, 108, 111, 24, 5, 104, 101, 255, 108, 111, 0, 0, 0, 21, 4, 25, 44,
        72, 4, 114, 111, 111, 116, 21, 2, 0, 21, 12, 37, 2, 24, 2, 99, 49, 37, 0, 76, 28,
        0, 0, 0, 22, 2, 25, 28, 25, 28, 38, 110, 28, 21, 12, 25, 37, 6, 0, 25, 24, 2, 99,
        49, 21, 0, 22, 2, 22, 102, 22, 102, 38, 8, 60, 54, 0, 40, 5, 104, 101, 255, 108,
        111, 24, 5, 104, 101, 255, 108, 111, 0, 0, 0, 22, 102, 22, 2, 0, 40, 44, 65, 114,
        114, 111, 119, 50, 32, 45, 32, 78, 97, 116, 105, 118, 101, 32, 82, 117, 115, 116,
        32, 105, 109, 112, 108, 101, 109, 101, 110, 116, 97, 116, 105, 111, 110, 32, 111,
        102, 32, 65, 114, 114, 111, 119, 0, 130, 0, 0, 0, 80, 65, 82, 49,
    ];

    read(Arc::new(data), 0)
}
```

miri output

```
cargo miri run --example unsafe

StringArray
[
error: Undefined Behavior: type validation failed: encountered 0x001ecbc0, but expected a valid unicode scalar value (in `0..=0x10FFFF` but not in `0xD800..=0xDFFF`)
  --> /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/char/convert.rs:94:78
   |
94 |     if cfg!(debug_assertions) { char::from_u32(i).unwrap() } else { unsafe { transmute(i) } }
   |                                                                              ^^^^^^^^^^^^ type validation failed: encountered 0x001ecbc0, but expected a valid unicode scalar value (in `0..=0x10FFFF` but not in `0xD800..=0xDFFF`)
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
           
   = note: inside `std::char::from_u32_unchecked` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/char/convert.rs:94:78
   = note: inside closure at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/iter.rs:43:22
   = note: inside `std::option::Option::<u32>::map::<char, [closure@<std::str::Chars as std::iter::Iterator>::next::{closure#0}]>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:489:29
   = note: inside `<std::str::Chars as std::iter::Iterator>::next` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/iter.rs:41:9
   = note: inside `<std::str::CharIndices as std::iter::Iterator>::next` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/iter.rs:140:15
   = note: inside `<str as std::fmt::Debug>::fmt` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2079:23
   = note: inside `<&str as std::fmt::Debug>::fmt` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2033:62
   = note: inside closure at /home/azureuser/projects/arrow-rs/arrow/src/array/array_string.rs:277:13
   = note: inside `arrow::array::array::print_long_array::<arrow::array::array_string::GenericStringArray<i32>, [closure@<arrow::array::array_string::GenericStringArray<i32> as std::fmt::Debug>::fmt::{closure#0}]>` at /home/azureuser/projects/arrow-rs/arrow/src/array/array.rs:561:13
   = note: inside `<arrow::array::array_string::GenericStringArray<i32> as std::fmt::Debug>::fmt` at /home/azureuser/projects/arrow-rs/arrow/src/array/array_string.rs:276:9
   = note: inside `<std::sync::Arc<dyn arrow::array::array::Array> as std::fmt::Debug>::fmt` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:2266:9
   = note: inside `<&std::sync::Arc<dyn arrow::array::array::Array> as std::fmt::Debug>::fmt` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2033:62
   = note: inside `std::fmt::write` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:1112:17
   = note: inside `<std::io::StdoutLock as std::io::Write>::write_fmt` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/mod.rs:1640:15
   = note: inside `<&std::io::Stdout as std::io::Write>::write_fmt` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:657:9
   = note: inside `<std::io::Stdout as std::io::Write>::write_fmt` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:631:9
   = note: inside `std::io::stdio::print_to::<std::io::Stdout>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:934:21
   = note: inside `std::io::_print` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:947:5
note: inside `read` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs:97:9
  --> parquet/examples/unsafe.rs:18:5
   |
18 |     println!("{:?}", batch.column(0));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `main` at parquet/examples/unsafe.rs:38:5
  --> parquet/examples/unsafe.rs:38:5
   |
38 |     read(Arc::new(data), 0)
   |     ^^^^^^^^^^^^^^^^^^^^^^^
   = note: inside `<fn() as std::ops::FnOnce<()>>::call_once - shim(fn())` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   = note: inside `std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
   = note: inside closure at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:63:18
   = note: inside `std::ops::function::impls::<impl std::ops::FnOnce<()> for &dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe>::call_once` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:259:13
   = note: inside `std::panicking::r#try::do_call::<&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe, i32>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:401:40
   = note: inside `std::panicking::r#try::<i32, &dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:365:19
   = note: inside `std::panic::catch_unwind::<&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe, i32>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:434:14
   = note: inside closure at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:45:48
   = note: inside `std::panicking::r#try::do_call::<[closure@std::rt::lang_start_internal::{closure#2}], isize>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:401:40
   = note: inside `std::panicking::r#try::<isize, [closure@std::rt::lang_start_internal::{closure#2}]>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:365:19
   = note: inside `std::panic::catch_unwind::<[closure@std::rt::lang_start_internal::{closure#2}], isize>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:434:14
   = note: inside `std::rt::lang_start_internal` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:45:20
   = note: inside `std::rt::lang_start::<()>` at /home/azureuser/.rustup/toolchains/nightly-2021-07-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:62:5
   = note: this error originates in the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by tustvold**
~Draft as builds on #1054~

# Which issue does this PR close?

Adds an optimized ByteArrayReader as part of proving out the generics added in #1041, and as a precursor to #171.

This also adds UTF-8 validation and support for `DELTA_BYTE_ARRAY`, neither of which are currently supported.

Closes #786 

# Rationale for this change
 
Depending on the benchmark, this can be anything from approximately the same to significantly (2x) faster than the ArrowArrayReader implementation added in #384. This is largely down to slightly more efficient null padding, and avoiding dynamic dispatch. The dominating factor in the benchmarks is the string value copy, which is makes me optimistic for the returns #171 wil yield.

_I didn't benchmark the results for `DELTA_BYTE_ARRAY` encoding but the returns are likely to be even more significant, as the layout is more optimal for decode_

The major benefit over the ArrowArrayReader implementation, aside from the speed bump, is the ability to share the existing ColumnReaderImpl and RecordReader logic, and the ability to work with all types of variable length strings and byte arrays.

This logic also forms the basis for #1180 

# What changes are included in this PR?

Adds a new `ByteArrayReader` that implements `ArrayReader` for variable length byte arrays

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by yordan-pavlov** [comment]
@tustvold this sounds exciting, would you be able to share some performance benchmark results?

File: parquet/src/arrow/array_reader/byte_array.rs [hunk 1]
```diff
@@ -0,0 +1,639 @@
...
+        self
+    }
+
+    fn get_data_type(&self) -> &ArrowType {
+        &self.data_type
+    }
+
+    fn next_batch(&mut self, batch_size: usize) -> crate::errors::Result<ArrayRef> {
+        let data = match &mut self.record_reader {
+            Reader::Binary(r) | Reader::Utf8(r) => {
```
Comment (yordan-pavlov) [inline parquet/src/arrow/array_reader/byte_array.rs:133]: can't this choice be made when the `ByteArrayReader` is created instead of every time `next_batch` is called?

File: parquet/src/arrow/array_reader/byte_array.rs [hunk 2]
```diff
@@ -0,0 +1,639 @@
...
+        len: usize,
+    ) -> Result<usize> {
+        let mut values_read = 0;
+
+        while values_read != len {
+            if self.index_offset == self.index_buf.len() {
+                let decoded = self.decoder.get_batch(self.index_buf.as_mut())?;
+                self.index_offset = 0;
+                if decoded != self.index_buf.len() && decoded < len - values_read {
+                    return Err(ParquetError::EOF(
```
Comment (yordan-pavlov) [inline parquet/src/arrow/array_reader/byte_array.rs:612]: isn't it a valid use case that less values can be returned than requested / `len`? (e.g. at end of file)

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 1 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs:133]: I wasn't sure how to achieve that without either leaking the index type into ByteArrayReader, or creating some sort of trait and using dynamic dispatch. An enumeration seemed like the simplest approach, and is likely to have negligible performance implications?

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 2 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs:612]: Quite possibly, although these structs are intended for general consumption - and RecordReader should be handling requesting only the correct amount. Further refinement is definitely likely if/when this gets closer to being review ready

**Comment by tustvold** [comment]
> would you be able to share some performance benchmark results?

They're very preliminary at this stage, I'm not totally confident this code is correct nor have I spent any time trying to optimise it, but here you go. My primary focus has been proving out the interface from #1041, not polishing up the specific optimisations yet.

"Old" is the new ByteArrayReader, "new" is the StringArrayReader

```
arrow_array_reader/read StringArray, plain encoded, mandatory, no NULLs - old                                                                            
                        time:   [110.98 us 111.00 us 111.03 us]
arrow_array_reader/read StringArray, plain encoded, mandatory, no NULLs - new                                                                            
                        time:   [124.77 us 124.99 us 125.32 us]
arrow_array_reader/read StringArray, plain encoded, optional, no NULLs - old                                                                            
                        time:   [122.15 us 122.17 us 122.20 us]
arrow_array_reader/read StringArray, plain encoded, optional, no NULLs - new                                                                            
                        time:   [136.72 us 136.76 us 136.81 us]
arrow_array_reader/read StringArray, plain encoded, optional, half NULLs - old                                                                            
                        time:   [117.26 us 117.35 us 117.43 us]
arrow_array_reader/read StringArray, plain encoded, optional, half NULLs - new                                                                            
                        time:   [258.05 us 258.17 us 258.30 us]
arrow_array_reader/read StringArray, dictionary encoded, mandatory, no NULLs - old                                                                            
                        time:   [145.30 us 145.35 us 145.41 us]
arrow_array_reader/read StringArray, dictionary encoded, mandatory, no NULLs - new                                                                            
                        time:   [117.14 us 117.18 us 117.22 us]
arrow_array_reader/read StringArray, dictionary encoded, optional, no NULLs - old                                                                            
                        time:   [159.07 us 159.11 us 159.15 us]
arrow_array_reader/read StringArray, dictionary encoded, optional, no NULLs - new                                                                            
                        time:   [134.39 us 134.41 us 134.43 us]
arrow_array_reader/read StringArray, dictionary encoded, optional, half NULLs - old                                                                            
                        time:   [108.28 us 108.30 us 108.33 us]
arrow_array_reader/read StringArray, dictionary encoded, optional, half NULLs - new                                                                            
                        time:   [230.15 us 230.23 us 230.32 us]
```

Aside from dictionary encoded columns with no nulls, it performs better. This is probably just something suboptimal in the way I'm decoding RLE data, and should be rectifiable.

**Comment by yordan-pavlov** [comment]
@tustvold  what about performance with primitive types (e.g. int32)? - this is where I have been struggling to make the `ArrowArrayReader` faster (compare to old array reader) for dictionary-encoded primitive values

**Comment by tustvold** [comment]
> what about performance with primitive types (e.g. int32)

This PR builds on #1054 which yields a 2-6x speed up when using PrimitiveArrayReader on non-nested columns compared to current master. This is purely through better null handling, which this PR also benefits from.

I do have some reservations about drawing too much from these benchmarks, I have found them to have strange interactions with my system's memory allocator, but its certainly not slower and is likely significantly faster.

> compared to old array reader implementation

That's the key thing about #1041 it doesn't replace this array reader implementation, it just adds the ability to extend it. For primitive types the performance of #1041 is therefore unchanged, it just gives the ability to add optimisations such as #1054

**Comment by yordan-pavlov** [comment]
@tustvold you are probably aware about this, but just to make sure it's not missed, when I run this branch with datafusion against a parquet file I get an error `Parquet argument error: Parquet error: unsupported encoding for byte array: PLAIN_DICTIONARY`

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 1 above)
Comment (yordan-pavlov) [reply parquet/src/arrow/array_reader/byte_array.rs:133]: I think it would be natural to make `ByteArrayReader` generic on `I: OffsetSizeTrait` similar to `consume_array_data` - then creating it wouldn't be more complex than it already is (for `ComplexObjectArrayReader`) but the `ByteArrayReader` itself would become much simpler and probably a bit faster

File: parquet/src/arrow/array_reader/byte_array.rs [hunk 3]
```diff
@@ -0,0 +1,639 @@
...
+                let data = consume_array_data(self.data_type.clone(), r)?;
+                self.def_levels_buffer = r.consume_def_levels()?;
+                self.rep_levels_buffer = r.consume_rep_levels()?;
+                r.reset();
+                data
+            }
+        };
+
+        Ok(match &self.record_reader {
+            Reader::Binary(_) => Arc::new(BinaryArray::from(data)),
```
Comment (yordan-pavlov) [inline parquet/src/arrow/array_reader/byte_array.rs:152]: I wonder if the the type of array to create should be a generic parameter as well?

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 1 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs:133]: Perhaps it is a hold over from my experience with C++ templates, but it has generally been my experience that generic code is tricky to use and even more tricky to maintain. I therefore am loathe to resort to it in places where it isn't strictly necessary. 

Adding a generic argument to `ByteArrayReader` would require a conditional block in the caller, and therefore the additional code saving is likely to be small. Additionally the cost of the conditional jump in `next_batch` is going to be completely dwarfed by the conditionals and memory allocations inherent in reading variable length string data, especially if using a reasonable batch_size.

Comment (yordan-pavlov) [reply parquet/src/arrow/array_reader/byte_array.rs:133]: My thinking in proposing adding generic type parameters, is that this `next_batch` method is part of the hot path in decoding arrow arrays from parquet files and the more conditions can be eliminated from the hot path, the better. I might be wrong, may be replacing the conditions with generic type parameters will not yield any performance improvements. But it should be easy to test - it should be a small code change and easy to run benchmarks against it.

File: parquet/src/arrow/array_reader.rs [hunk 4]
```diff
@@ -1663,69 +1699,58 @@ impl<'a> ArrayReaderBuilder {
...
-                        column_desc,
-                        converter,
-                        arrow_type,
-                    )?))
                 }
-            }
+                _ => Ok(Box::new(ByteArrayReader::new(
+                    page_iterator,
+                    column_desc,
+                    arrow_type,
```
Comment (yordan-pavlov) [inline parquet/src/arrow/array_reader.rs:1751]: why not use `null_mask_only` here for `ByteArrayReader` as well?

Comment (tustvold) [reply parquet/src/arrow/array_reader.rs:1751]: Pure oversight - good spot :+1:

**Comment by tustvold** [comment]
I've added UTF-8 validation, including @jorgecarleitao 's very helpful test case, so this should fix that also :tada:

File: parquet/src/arrow/array_reader/byte_array.rs [hunk 5]
```diff
@@ -192,7 +211,16 @@ impl<I: OffsetSizeTrait + ScalarValue> OffsetBuffer<I> {
         self.offsets.len() - 1
     }
 
-    fn try_push(&mut self, data: &[u8]) -> Result<()> {
+    fn try_push(&mut self, data: &[u8], validate_utf8: bool) -> Result<()> {
+        if validate_utf8 {
+            if let Err(e) = std::str::from_utf8(data) {
```
Comment (yordan-pavlov) [inline parquet/src/arrow/array_reader/byte_array.rs:216]: I wonder if something like https://github.com/rusticstuff/simdutf8 could be used for faster UTF8 validation

Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs:216]: Definitely something to look into. It would also be interesting to see if it is faster to validate the entire string buffer and do codepoint validation at the offsets separately, or to validate each individual string as is done here. I'm not honestly sure which will be faster

Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs]: So I did some experimentation:

It is **significantly** faster to verify on push that the first byte is a valid start UTF-8 codepoint, and then do UTF-8 validation on the larger buffer in one go, it takes the performance hit on PLAIN encoded strings to ~1.1x down from ~2x.

With this optimisation applied, changing to simdutf8 made only a very minor ~6% improvement on PLAIN encoded strings, which reduced to no appreciable difference with RLE encoded strings. This may be my machine, or the lack of non-ASCII characters in the input, but I'm going to leave this out for now.

Comment (Dandandan) [reply parquet/src/arrow/array_reader/byte_array.rs]: I think we tried to do something similar with parquet2 but concluded that the individual strings should be checked instead. `simdutf8` is more impressive at checking non ASCII strings btw.
Checking the code points at the offsets seems an interesting approach!
Also FYI @jorgecarleitao

File: parquet/src/column/reader.rs [hunk 6]
```diff
@@ -258,11 +258,15 @@ where
             // At this point we have read values, definition and repetition levels.
             // If both definition and repetition levels are defined, their counts
             // should be equal. Values count is always less or equal to definition levels.
-            if num_def_levels != 0 && num_rep_levels != 0 {
-                assert_eq!(
```
Comment (tustvold) [inline parquet/src/column/reader.rs:262]: Drive by fix, a bad parquet file shouldn't trigger a panic

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 5 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs]: I _think_ this should be sufficient, but I'm not an expert on UTF-8. My reasoning is that when you slice a `str` all it validates are that the start and end offsets pass `std::str::is_char_boundary` - [here](https://doc.rust-lang.org/std/primitive.str.html#panics-3). Taking that the standard library is correct, and the only invariant of `str` is that the bytes are UTF-8 as a whole, I think this is no different?

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 7]
```diff
@@ -0,0 +1,211 @@
...
+        self.values.extend_from_slice(data);
+
+        let index_offset = I::from_usize(self.values.len())
+            .ok_or_else(|| general_err!("index overflow decoding byte array"))?;
+
+        self.offsets.push(index_offset);
+        Ok(())
+    }
+
+    pub fn extend_from_dictionary<K: ArrowNativeType, V: ArrowNativeType>(
```
Comment (tustvold) [inline parquet/src/arrow/array_reader/offset_buffer.rs:76]: This is split out so that it can be used by #1180

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 3 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs]: I ended up doing exactly this :+1:

**Comment by tustvold** [comment]
I'm going to continue to write tests for various parts of this, but I think the main bulk is ready for review and has fairly good coverage from the fuzz tests.

Unfortunately this ended up a wee bit chonkier than I had hoped, if this is a problem let me know and I can try to split some stuff out.

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 1 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs]: Switched to using generics as it made #1180 easier to implement, I ended up with a combinatorial explosion of key and value types :sweat_smile:

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 2 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs]: I removed this logic, and added checks higher up in RecordReader

File: parquet/benches/arrow_array_reader.rs [hunk 8]
```diff
@@ -366,10 +366,10 @@ fn add_benches(c: &mut Criterion) {
                     mandatory_int32_column_desc.clone(),
                 );
                 count = bench_array_reader(array_reader);
+                assert_eq!(count, EXPECTED_VALUE_COUNT);
```
Comment (yordan-pavlov) [inline parquet/benches/arrow_array_reader.rs:369]: with this change, doesn't `assert_eq!(count, EXPECTED_VALUE_COUNT);` become part of the benchmarked code? yes, it should have minimal to no impact, but my concern is more about keeping the benchmark as clean as possible.

Comment (tustvold) [reply parquet/benches/arrow_array_reader.rs:369]: This was so that you can run a subset of the benchmarks, let me try lifting them out of the iter block but still within the bench_function :thinking:

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 9]
```diff
@@ -68,6 +77,16 @@ impl<I: OffsetSizeTrait + ScalarValue> OffsetBuffer<I> {
         Ok(())
     }
 
+    /// Returns the values buffer as a string slice, returning an error
+    /// if it is invalid UTF-8
+    ///
+    /// `start_offset` is the offset in bytes from the start
+    pub fn values_as_str(&self, start_offset: usize) -> Result<&str> {
+        std::str::from_utf8(&self.values.as_slice()[start_offset..]).map_err(|e| {
```
Comment (yordan-pavlov) [inline parquet/src/arrow/array_reader/offset_buffer.rs:108]: if the &str result is not actually used, does this method need to return it? e.g. why not change to `-> Result<()>` and possibly even change the method name to something like `check_valid_utf8`.

Comment (tustvold) [reply parquet/src/arrow/array_reader/offset_buffer.rs]: Done

File: parquet/benches/arrow_array_reader.rs [hunk 10]
```diff
@@ -273,7 +274,7 @@ fn build_dictionary_encoded_string_page_iterator(
     InMemoryPageIterator::new(schema, column_desc, pages)
 }
 
-fn bench_array_reader(mut array_reader: impl ArrayReader) -> usize {
+fn bench_array_reader(mut array_reader: Box<dyn ArrayReader>) -> usize {
```
Comment (tustvold) [inline parquet/benches/arrow_array_reader.rs:277]: This change is necessary because byte_array_reader hides its implementing type, this is both to make the API more ergonomic for clients and also to aid future crate evolution

File: parquet/benches/arrow_array_reader.rs [hunk 11]
```diff
@@ -368,10 +366,10 @@ fn add_benches(c: &mut Criterion) {
                     mandatory_int32_column_desc.clone(),
                 );
                 count = bench_array_reader(array_reader);
-            })
+            });
+            assert_eq!(count, EXPECTED_VALUE_COUNT);
```
Comment (tustvold) [inline parquet/benches/arrow_array_reader.rs:370]: This change allows for running a subset of the benchmarks, without this the assertion fails if the bench function is filtered out.

For example, this would run just the string array benchmarks
```
cargo criterion --bench arrow_array_reader --features test_common,experimental -- StringArray
```

File: parquet/src/arrow/array_reader.rs [hunk 12]
```diff
@@ -1749,57 +1753,43 @@ impl<'a> ArrayReaderBuilder {
...
-                        };
-                        let converter = StringArrayConverter::new();
-                        Ok(Box::new(ArrowArrayReader::try_new(
-                            *page_iterator,
-                            column_desc,
-                            converter,
-                            arrow_type,
-                        )?))
+            PhysicalType::BYTE_ARRAY => match arrow_type {
+                // TODO: Replace with optimised dictionary reader (#171)
```
Comment (tustvold) [inline parquet/src/arrow/array_reader.rs:1757]: See #1180

File: parquet/src/column/reader/decoder.rs [hunk 13]
```diff
@@ -95,11 +95,22 @@ pub trait ColumnValueDecoder {
     ) -> Result<()>;
 
     /// Set the current data page
+    ///
+    /// - `encoding` - the encoding of the page
+    /// - `data` - a point to the page's uncompressed value data
+    /// - `num_levels` - the number of levels contained within the page, i.e. values including nulls
+    /// - `num_values` - the number of non-null values contained within the page (V2 page only)
+    ///
+    /// Note: data encoded with [`Encoding::RLE`] may not know its exact length, as the final
```
Comment (tustvold) [inline parquet/src/column/reader/decoder.rs:104]: I wanted to be explicit about this to avoid a resurgence of this style of bug - https://github.com/apache/arrow-rs/issues/1111

This is a crate-private API, and the necessary null counting dance is performed by RecordReader, but I wanted to call it out for the avoidance of confusion.

File: parquet/src/arrow/arrow_reader.rs [hunk 14]
```diff
@@ -968,4 +969,40 @@ mod tests {
         assert_eq!(batch.num_rows(), 4);
         assert_eq!(batch.column(0).data().null_count(), 2);
     }
+
+    #[test]
+    fn test_invalid_utf8() {
```
Comment (tustvold) [inline parquet/src/arrow/arrow_reader.rs:974]: Test sourced from #786

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 15]
```diff
@@ -0,0 +1,337 @@
...
+};
+use crate::column::reader::decoder::ValuesBufferSlice;
+use crate::errors::{ParquetError, Result};
+use arrow::array::{make_array, ArrayDataBuilder, ArrayRef, OffsetSizeTrait};
+use arrow::buffer::Buffer;
+use arrow::datatypes::{ArrowNativeType, DataType as ArrowType};
+
+/// A buffer of variable-sized byte arrays that can be converted into
+/// a corresponding [`ArrayRef`]
+pub struct OffsetBuffer<I: ScalarValue> {
```
Comment (alamb) [inline parquet/src/arrow/array_reader/offset_buffer.rs:29]: I almost wonder if this is valuable itself to put into the `arrow` crate and use to create `GenericStringArray`s from iterators of `&str` etc. Not for this PR, I am just musing

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 16]
```diff
@@ -0,0 +1,337 @@
...
+    ///
+    /// Note: This does not verify that the entirety of `data` is valid
+    /// UTF-8. This should be done by calling [`Self::values_as_str`] after
+    /// all data has been written
+    pub fn try_push(&mut self, data: &[u8], validate_utf8: bool) -> Result<()> {
+        if validate_utf8 {
+            if let Some(&b) = data.first() {
+                // A valid code-point iff it does not start with 0b10xxxxxx
+                // Bit-magic taken from `std::str::is_char_boundary`
+                if (b as i8) < -0x40 {
```
Comment (alamb) [inline parquet/src/arrow/array_reader/offset_buffer.rs:62]: https://doc.rust-lang.org/src/core/str/mod.rs.html#218 👍

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 17]
```diff
@@ -0,0 +1,337 @@
...
+    }
+
+    /// If `validate_utf8` this verifies that the first character of `data` is
+    /// the start of a UTF-8 codepoint
+    ///
+    /// Note: This does not verify that the entirety of `data` is valid
+    /// UTF-8. This should be done by calling [`Self::values_as_str`] after
+    /// all data has been written
+    pub fn try_push(&mut self, data: &[u8], validate_utf8: bool) -> Result<()> {
+        if validate_utf8 {
```
Comment (alamb) [inline parquet/src/arrow/array_reader/offset_buffer.rs:58]: for anyone else following along, I double checked the code and `validate_utf8` is disabled for `DataType::Binary` as one would expect. It is always enabled for `DataType::Utf8`

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 18]
```diff
@@ -0,0 +1,337 @@
...
+        make_array(data)
+    }
+}
+
+impl<I: OffsetSizeTrait + ScalarValue> BufferQueue for OffsetBuffer<I> {
+    type Output = Self;
+    type Slice = Self;
+
+    fn split_off(&mut self, len: usize) -> Self::Output {
+        let remaining_offsets = self.offsets.len() - len - 1;
```
Comment (alamb) [inline parquet/src/arrow/array_reader/offset_buffer.rs:146]: recommend an assert here that `self.offsets.len() > len` for clarity, but I think that the `offsets[len]` would panic below if this were not the case, so I don't think it is a safety issue

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 19]
```diff
@@ -0,0 +1,337 @@
...
+        let offsets = self.offsets.as_slice();
+
+        let end_offset = offsets[len];
+
+        let mut new_offsets = ScalarBuffer::new();
+        new_offsets.reserve(remaining_offsets + 1);
+        for v in &offsets[len..] {
+            new_offsets.push(*v - end_offset)
```
Comment (alamb) [inline parquet/src/arrow/array_reader/offset_buffer.rs:154]: nice

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 20]
```diff
@@ -0,0 +1,337 @@
...
+        }
+
+        self.offsets.resize(len + 1);
+
+        Self {
+            offsets: std::mem::replace(&mut self.offsets, new_offsets),
+            values: self.values.take(end_offset.to_usize().unwrap()),
```
Comment (alamb) [inline parquet/src/arrow/array_reader/offset_buffer.rs:161]: I found it a little confusing that `values.take()` does the same thing as `split_off` -- maybe it is worth renaming `ScalarBuffer<T>::take()` to `ScalarBuffer<T>::split_off()`?

File: parquet/src/arrow/array_reader/offset_buffer.rs [hunk 21]
```diff
@@ -0,0 +1,337 @@
...
+        self.offsets.resize(read_offset + levels_read + 1);
+
+        let offsets = self.offsets.as_slice_mut();
+
+        let mut last_pos = read_offset + levels_read + 1;
+        let mut last_start_offset = I::from_usize(self.values.len()).unwrap();
+
+        let values_range = read_offset..read_offset + values_read;
+        for (value_pos, level_pos) in values_range.clone().rev().zip(rev_position_iter) {
+            assert!(level_pos >= value_pos);
```
Comment (alamb) [inline parquet/src/arrow/array_reader/offset_buffer.rs:192]: this is definitely a tricky bit of logic, looks reasonable to me

File: parquet/src/arrow/array_reader/byte_array.rs [hunk 22]
```diff
@@ -0,0 +1,669 @@
...
+        let mem_tracker = Arc::new(MemTracker::new());
+        let mut encoder =
+            get_encoder::<ByteArrayType>(descriptor, encoding, mem_tracker).unwrap();
+
+        encoder.put(data).unwrap();
+        encoder.flush_buffer().unwrap()
+    }
+
+    #[test]
+    fn test_byte_array_decoder() {
```
Comment (alamb) [inline parquet/src/arrow/array_reader/byte_array.rs:614]: Is NULL covered anywhere? If not I think that might be valuable to cover here too

**Review by alamb — APPROVED** [review]
I went through this PR pretty thoroughly -- and while I am not anywhere near as much of an expert as  it is my judgement that this is ready to merge.

What is the plan for the `ArrowArrayReader` implementation added in #384? Should we plan to remove it from this crate (if so I can file a ticket)

Thank you very much @tustvold  and for the effort in reviewing @yordan-pavlov.

Any remaining thoughts or people who want to comment prior to merging?

File: parquet/src/arrow/array_reader/offset_buffer.rs (hunk 15 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/offset_buffer.rs:29]: I thought similar, lifting this and ScalarBuffer into arrow-rs would likely remove a non-trivial amount of unsafe

File: parquet/src/arrow/array_reader/byte_array.rs (hunk 22 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/byte_array.rs:614]: The null padding is technically handled and tested as part of OffsetBuffer, but I'll add something here

File: parquet/src/arrow/array_reader/offset_buffer.rs (hunk 20 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/offset_buffer.rs:161]: This is a backwards compatibility thing, `ScalarBuffer::Output` must be Buffer to avoid changing the API of `ColumnReaderImpl`. Perhaps this could be included in a future breaking change cleanup PR :thinking:

File: parquet/src/arrow/array_reader/offset_buffer.rs (hunk 21 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/offset_buffer.rs:192]: There was much wailing and gnashing of teeth in its creation :sweat_smile:

File: parquet/src/arrow/array_reader/offset_buffer.rs (hunk 18 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/offset_buffer.rs:147]: Added

**Comment by tustvold** [comment]
> What is the plan for the ArrowArrayReader implementation

I don't think there is a particular reason for it to stay, but I defer the final decision to @yordan-pavlov

**Comment by yordan-pavlov** [comment]
> What is the plan for the `ArrowArrayReader` implementation added in #384? Should we plan to remove it from this crate (if so I can file a ticket)

I am happy for `ArrowArrayReader` to be removed - I have ran the benchmarks against the latest code and @tustvold 's work is now often several times faster in almost all cases and in the one or two cases where it isn't the difference is small - congratulations @tustvold ; plus I think @tustvold 's array reader could be made faster still

**Comment by alamb** [comment]
I also ran the tests from the latest master branch of datafusion against this branch and they all passed. Not that it is the most thorough coverage of the parquet format, but it adds some.

👍

**Comment by alamb** [comment]
https://github.com/apache/arrow-rs/issues/1197 tracks ArrowArrayReader removal
