### PR TITLE
Fix page size on dictionary fallback

### LINKED ISSUE #2853: `parquet::arrow::arrow_writer::ArrowWriter` ignores page size properties
**Describe the bug**

`ArrowWrites` ignores page size properties when writing to parquet. It also seems to always write just two pages, the first one a normal sized page and all the remaining data in the second page. 

**To Reproduce**

```
    #[test]
    fn arrow_writer_page_size() {
        let mut rng = thread_rng();
        let schema = Arc::new(Schema::new(vec![Field::new("col", DataType::Utf8, false)]));

        let mut builder = StringBuilder::with_capacity(10_000, 2 * 10_0000);

        for _ in 0..100_000 {
            let value = (0..200)
                .map(|_| rng.gen_range(b'a'..=b'z') as char)
                .collect::<String>();

            builder.append_value(value);
        }

        let array = Arc::new(builder.finish());

        let batch = RecordBatch::try_new(schema, vec![array]).unwrap();

        let file = tempfile::tempfile().unwrap();

        let props = WriterProperties::builder()
            .set_max_row_group_size(usize::MAX)
            .set_data_pagesize_limit(512)
            .set_write_batch_size(512)
            .build();

        let mut writer = ArrowWriter::try_new(
            file.try_clone().unwrap(),
            batch.schema(),
            Some(props),
        )
            .expect("Unable to write file");
        writer.write(&batch).unwrap();
        writer.close().unwrap();

        let reader = SerializedFileReader::new(file.try_clone().unwrap()).unwrap();

        let column = reader.metadata().row_group(0).columns();

        let page_locations = read_pages_locations(&file, column).unwrap();

        let offset_index = page_locations[0].clone();

        assert!(offset_index.len() > 2, "Expected more than two pages but got {:#?}", offset_index);
    }
```

This outputs 
```
thread 'arrow::arrow_writer::tests::arrow_writer_page_size' panicked at 'Expected more than two pages but got [
    PageLocation {
        offset: 1148953,
        compressed_page_size: 9595,
        first_row_index: 0,
    },
    PageLocation {
        offset: 1158548,
        compressed_page_size: 19251505,
        first_row_index: 5632,
    },
]'
```

**Expected behavior**

The writer should respect the page size properties and write similarly sized pages. 

**Additional context**

### PR DESCRIPTION
**Pull request by thinkharderdev**
# Which issue does this PR close?

Closes #2853 

# Rationale for this change
 

On fallback `ByteArrayEncoder` wasn't tracking the number of values written so when the dictionary page hits the limit and we fallback, all remaining data was written in a single data page. 

# What changes are included in this PR?

Make sure `ByteArrayEncoder` tracks the number of encoded values after it falls back to the fallback encoder

# Are there any user-facing changes?

This will change the way data pages are laid out in some cases. 

No

No

### CODE REVIEW

File: parquet/src/arrow/arrow_writer/mod.rs [hunk 1]
```diff
@@ -1108,6 +1110,55 @@ mod tests {
         roundtrip(batch, Some(SMALL_SIZE / 2));
     }
 
+    #[test]
+    fn arrow_writer_page_size() {
+        let mut rng = thread_rng();
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/mod.rs:1115]: I think we should either seed this, or loosen the assert below. Otherwise I worry that depending on what values are generated, we may end up with more or less pages (as the dictionary page will only spill once it has seen sufficient different values, which technically could occur at any point)

File: parquet/src/arrow/arrow_writer/mod.rs [hunk 2]
```diff
@@ -1108,6 +1110,55 @@ mod tests {
...
+
+        let array = Arc::new(builder.finish());
+
+        let batch = RecordBatch::try_new(schema, vec![array]).unwrap();
+
+        let file = tempfile::tempfile().unwrap();
+
+        let props = WriterProperties::builder()
+            .set_max_row_group_size(usize::MAX)
+            .set_data_pagesize_limit(256)
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/mod.rs:1137]: You could potentially set the dictionary page size smaller to verify that as well, but up to you

**Review by tustvold — APPROVED** [review]
Thank you :+1:

File: parquet/src/arrow/arrow_writer/byte_array.rs [hunk 3]
```diff
@@ -551,7 +551,10 @@ where
 
     match &mut encoder.dict_encoder {
         Some(dict_encoder) => dict_encoder.encode(values, indices),
-        None => encoder.fallback.encode(values, indices),
+        None => {
+            encoder.num_values += indices.len();
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/byte_array.rs:555]: I'm guessing the problem was that whilst the estimated_data_page_size would increase, the lack of any values would cause it to erroneously not try to flush the page

Comment (thinkharderdev) [reply parquet/src/arrow/arrow_writer/byte_array.rs:555]: yep, exactly

Comment (tustvold) [inline parquet/src/arrow/arrow_writer/byte_array.rs:555]: Should we be doing this regardless of if we've fallen back?

Comment (thinkharderdev) [reply parquet/src/arrow/arrow_writer/byte_array.rs:555]: Maybe, when we do it that way it causes a panic which may also be a bug. 

`General("Must flush data pages before flushing dictionary")'`

File: parquet/src/arrow/arrow_writer/mod.rs (hunk 2 above)
Comment (thinkharderdev) [reply parquet/src/arrow/arrow_writer/mod.rs:1133]: So I think there are still some issues here. It is still ignoring the size limit. It is at least respecting the `write_batch_size` though.

Comment (tustvold) [reply parquet/src/arrow/arrow_writer/mod.rs:1133]: That is expected and I believe consistent with other parquet writers. The limit is best effort

File: parquet/src/arrow/arrow_writer/byte_array.rs (hunk 3 above)
Comment (tustvold) [reply parquet/src/arrow/arrow_writer/byte_array.rs:555]: I think we need to reset num_values to 0 when we flush a data page

Comment (thinkharderdev) [reply parquet/src/arrow/arrow_writer/byte_array.rs:555]: I think it already does that right? https://github.com/apache/arrow-rs/blob/2ae23093c3f7edc278fe6daf57daf167c430143b/parquet/src/arrow/arrow_writer/byte_array.rs#L313

**Review by Ted-Jiang — APPROVED** [review]
👍
