### PR TITLE
Fix Parquet reader for null list

### LINKED ISSUE #1399: Parquet reader fails to read null list.
**Describe the bug**
Parquet reader fails to read a parquet file that is generated from this json:
```
{"emptylist":[]}
```

**To Reproduce**
I have written a test on a branch to reproduce this failure. 

1. Generated a parquet-file from the aforementioned json. See https://github.com/apache/arrow-rs/pull/1063#issuecomment-1053939744 and the related issue for context. Verified that this parquet file can be read using pyarrow as the following arrow table:

```
>>> empty_table = pq.read_table("empty_table.parquet")
>>> empty_table
pyarrow.Table
emptylist: list<item: null>
  child 0, item: null
----
emptylist: [[0 nulls]]
```
2. Added this parquet file to a branch of my fork of `parquet-testing` https://github.com/novemberkilo/parquet-testing/commit/a827b12cd0985ef2d6d89534a405e64d55a40140

3. Wrote a test that reads this file. 

Test: https://github.com/novemberkilo/arrow-rs/commit/e5952ae74344d253fad7212ec46cb913d5e4f1cb
~~Failure: https://github.com/novemberkilo/arrow-rs/runs/5431110483?check_suite_focus=true#step:4:1999~~
Failure: https://github.com/novemberkilo/arrow-rs/runs/5431134675?check_suite_focus=true#step:7:1944

**Expected behavior**
Should read the file (like pyarrow can)

**Additional context**
This is all related to this original issue #1036 // @alamb

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1399.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: parquet/src/arrow/arrow_reader.rs [hunk 1]
```diff
@@ -1210,4 +1210,19 @@ mod tests {
         assert_eq!(get_dict(&batches[3]), get_dict(&batches[4]));
         assert_eq!(get_dict(&batches[4]), get_dict(&batches[5]));
     }
+
+    #[test]
+    fn test_read_null_list() {
+        let testdata = arrow::util::test_util::parquet_test_data();
+        let path = format!("{}/null_list.parquet", testdata);
```
Comment (viirya) [inline parquet/src/arrow/arrow_reader.rs:1217]: I downloaded the test parquet file from @novemberkilo's `parquet-testing` fork. Not sure how we can put the file there?

**Review by viirya — COMMENTED** [review]
I'm not sure if I understand correctly Parquet's behavior for this case. It looks like `next` should return None. cc @sunchao

File: parquet/src/arrow/array_reader.rs [hunk 2]
```diff
@@ -924,7 +927,7 @@ impl<OffsetSize: OffsetSizeTrait> ArrayReader for ListArrayReader<OffsetSize> {
             && (rep_levels.len() == next_batch_array.len()))
         {
             return Err(ArrowError(
-                "Expected item_reader def_levels and rep_levels to be same length as batch".to_string(),
+                format!("Expected item_reader def_levels {} and rep_levels {} to be same length as batch {}", def_levels.len(), rep_levels.len(), next_batch_array.len()),
```
Comment (viirya) [inline parquet/src/arrow/array_reader.rs:930]: Purely for debugging purpose. I feel it is clear.

File: parquet/src/arrow/arrow_reader.rs (hunk 1 above)
Comment (novemberkilo) [reply parquet/src/arrow/arrow_reader.rs:1217]: You could point to my parquet-testing fork like I have done here https://github.com/novemberkilo/arrow-rs/commit/e5952ae74344d253fad7212ec46cb913d5e4f1cb#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584

**Comment by novemberkilo** [comment]
Thanks for taking this on @viirya -- I'm following along with interest :)

File: parquet/src/arrow/arrow_reader.rs (hunk 1 above)
Comment (viirya) [reply parquet/src/arrow/arrow_reader.rs:1217]: Okay, I think it works for CI purpose in the PR. Not sure if we can merge into master like that. Anyway, let me point to your fork first to test it. Thanks.

Comment (viirya) [reply parquet/src/arrow/arrow_reader.rs:1217]: yea, I think it is good idea.

Comment (viirya) [reply parquet/src/arrow/arrow_reader.rs:1217]: Hmm, seems updating `.gitmodules` doesn't work? I also updated it locally and do `git submodule update --init` again, but I don't see the file in `parquet-testing/data`.

Comment (novemberkilo) [reply parquet/src/arrow/arrow_reader.rs:1217]: @sunchao https://github.com/apache/parquet-testing/pull/23

Comment (novemberkilo) [reply parquet/src/arrow/arrow_reader.rs:1217]: @viirya fwiw I did something like:

- delete the parquet-testing submodule
- `git submodule add -b topic/null-list-reader git@github.com:novemberkilo/parquet-testing`

Comment (viirya) [reply parquet/src/arrow/arrow_reader.rs:1217]: Oh, I see. Thanks. I added the file manually to test it before.

And seems updating `.gitmodules` doesn't work for CI here. We may need to wait for the test file being merged in `parquet-testing`.

File: parquet/src/arrow/array_reader.rs [hunk 3]
```diff
@@ -885,6 +885,9 @@ fn remove_indices(
                 Ok(Arc::new(StructArray::from((new_columns, valid.finish()))))
             }
         }
+        ArrowType::Null => {
```
Comment (tustvold) [inline parquet/src/arrow/array_reader.rs:888]: Probably beyond the scope of this PR, but it occurs to me that this `remove_indices` function is basically an inverse of the arrow `take` kernel. I wonder if we could flip the construction of `null_list_indices` to be instead the non-null positions - and just use a regular take kernel?

I might have a play with this :thinking:

File: parquet/src/arrow/array_reader.rs [hunk 4]
```diff
@@ -1984,12 +1990,14 @@ impl<'a> ArrayReaderBuilder {
                     field = self.arrow_schema.field_with_name(part).ok();
```
Comment (tustvold) [inline parquet/src/arrow/array_reader.rs:1990]: Not part of this PR, but I wonder why this doesn't just initialize `field` to be `self.arrow_schema.field_with_name(parts[1]).ok()` and then do `skip(2)` given it has already done the length check above...

File: parquet/src/arrow/array_reader.rs [hunk 5]
```diff
@@ -1984,12 +1990,14 @@ impl<'a> ArrayReaderBuilder {
...
                 } else if let Some(f) = field {
                     if let ArrowType::Struct(fields) = f.data_type() {
-                        field = fields.iter().find(|f| f.name() == part)
+                        field = fields.iter().find(|f| f.name() == part);
+                    } else if let ArrowType::List(list_field) = f.data_type() {
```
Comment (tustvold) [inline parquet/src/arrow/array_reader.rs:1994]: If I'm not mistaken this change is necessary to support a StructArray containing a ListArray in general, without being specific to nulls?

File: parquet/src/arrow/arrow_reader.rs (hunk 1 above)
Comment (tustvold) [reply parquet/src/arrow/arrow_reader.rs:1217]: I will have a play with creating a test that generates a parquet file, so that we can get this PR in without waiting for parquet-testing. I will also file a ticket to start a discussion on a faster way to get parquet test files checked in, without relying on an upstream repo

**Review by tustvold — COMMENTED** [review]
This looks good to me, thanks - I will see if I can't create some minimal test cases so that we can get this one in (and to check I fully understand the problems)

File: parquet/src/arrow/array_reader.rs [hunk 6]
```diff
@@ -964,7 +967,10 @@ impl<OffsetSize: OffsetSizeTrait> ArrayReader for ListArrayReader<OffsetSize> {
                 cur_offset += OffsetSize::one();
             }
         });
-        offsets.push(cur_offset);
+
+        if !cur_offset.is_zero() {
```
Comment (tustvold) [inline parquet/src/arrow/array_reader.rs:971]: I'm not sure this is correct, I think it will convert an array containing no non-null values, into an empty array?

File: parquet/src/arrow/arrow_reader.rs (hunk 1 above)
Comment (viirya) [reply parquet/src/arrow/arrow_reader.rs:1217]: Thanks @tustvold. The parquet file was merged. It'd be great to get testing parquet test files checked in faster.

File: parquet/src/arrow/array_reader.rs (hunk 5 above)
Comment (viirya) [reply parquet/src/arrow/array_reader.rs:1994]: Yea, this is not specific to nulls.

File: parquet/src/arrow/array_reader.rs (hunk 3 above)
Comment (viirya) [reply parquet/src/arrow/array_reader.rs:888]: Yea, seems so.

**Review by tustvold — APPROVED** [review]
Thank you for this, unless anybody else chimes in with a review I'll get this merged this afternoon :+1:
