### PR TITLE
check sign_payload instead of skip_signature before computing checksum

### LINKED ISSUE #6697: `with_unsigned_payload` shouldn't generate payload hash
**Describe the bug**
The AWS S3 variant of the interface has an option to do an unsigned payload, which should skip computing the payload checksum. However, in reality, the checksum is computed but then discarded, negating all performance improvements one should get by choosing to do an unsigned payload.

The issue lies in this line: https://github.com/apache/arrow-rs/blob/37cd34dfb199474053c2ca578c6c2d79296e1540/object_store/src/aws/client.rs#L353

I believe it should be checking `self.config.sign_payload` instead of `!self.config.skip_signature`

**To Reproduce**
Build a new amazon s3 object store with unsigned payloads
```
let store = AmazonS3Builder::new()
    .with_unsigned_payload(true)
    ...
```
Then put an object in the store. The outgoing request to s3 is correct, but the payload checksum generated here
https://github.com/apache/arrow-rs/blob/37cd34dfb199474053c2ca578c6c2d79296e1540/object_store/src/aws/client.rs#L355
as a pre calculated digset is then discarded here
https://github.com/apache/arrow-rs/blob/37cd34dfb199474053c2ca578c6c2d79296e1540/object_store/src/aws/credential.rs#L167

**Expected behavior**
The checksum of the payload should never be computed if the unsigned payload config is set, even if the http request to s3 doesn't include the payload checksum

### PR DESCRIPTION
**Pull request by mherrerarendon**
# Which issue does this PR close?
Closes #6697

# What changes are included in this PR?
Checks for `sign_payload` instead of `!skip_signature` before generating the payload checksum

# Are there any user-facing changes?
Yes

### CODE REVIEW

File: object_store/src/aws/client.rs [hunk 1]
```diff
@@ -350,7 +350,7 @@ impl<'a> Request<'a> {
     }
 
     pub(crate) fn with_payload(mut self, payload: PutPayload) -> Self {
-        if !self.config.skip_signature || self.config.checksum.is_some() {
+        if self.config.sign_payload || self.config.checksum.is_some() {
```
Comment (tustvold) [inline object_store/src/aws/client.rs:353]:
```suggestion
        if (!self.config.skip_signature && self.config.sign_payload) || self.config.checksum.is_some() {
```

We should compute the checksum if we are signing the request and payload signing is enabled

Comment (andrebsguedes) [reply object_store/src/aws/client.rs:353]: Got bit by this too a while ago and my solution was the one @tustvold suggests

Comment (mherrerarendon) [reply object_store/src/aws/client.rs]: Thanks! I applied your suggestion
