### PR TITLE
fix(object_store,aws,gcp): multipart upload enforce size limit of 5 MiB not 5MB

### LINKED ISSUE #3233: object_store(aws): EntityTooSmall error on multi-part upload
**Describe the bug**

Our multi-part upload pieces are too small for the AWS API's liking. Currently, it is using 5,000,000 byte parts, but minimum is either 5 MB or 5 MiB (not sure).

Example error:

```
thread 'aws::tests::s3_test' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: Generic { store: "S3", source: CompleteMultipartRequest { source: Error { retries: 0, message: "<Error><Code>EntityTooSmall</Code><Message>Your proposed upload is smaller than the minimum allowed size</Message><ProposedSize>5123000</ProposedSize><MinSizeAllowed>5242880</MinSizeAllowed><PartNumber>1</PartNumber><ETag>dac58c3bc3316365210fc576472b529a</ETag><RequestId>NAFF7PP64BMSNE2N</RequestId><HostId>r7Fu4+ISmVItLuVku0lD+SZFlQmQFskejoOBwSru7JzJ/KFNQ7/Ae/nyszZGtNhWAaMqrmLXuqk=</HostId></Error>", source: Some(reqwest::Error { kind: Status(400), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("s3.us-west-2.amazonaws.com")), port: None, path: "/wjones127-test-object-store/test_dir/test_upload_file.txt", query: Some("uploadId=mQw8lAvgQI8SFAosOZgucoX80ZC0yf6j6lBctI_CoiM09jg5TVGOHnaOy7QVUARnH2FrxjPOMc8g892B4qK_7CWYhHRU9wzcGTzBLvGKAYI-"), fragment: None } }) } } } }', object_store/src/lib.rs:778:33
```

**To Reproduce**

**Expected behavior**

**Additional context**

Reported in delta-rs: https://github.com/delta-io/delta-rs/issues/890#issuecomment-1331457717

### PR DESCRIPTION
**Pull request by wjones127**
# Which issue does this PR close?

Closes #3233.

# Rationale for this change
 
Bumping up the size of the test data as well, so it's easier to catch this. However, I think the localstack emulator might not enforce this limit, which is why we didn't catch this earlier.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: object_store/src/lib.rs [hunk 1]
```diff
@@ -769,7 +769,7 @@ mod tests {
         assert_eq!(bytes_expected, bytes_written);
 
         // Can overwrite some storage
-        let data = get_vec_of_bytes(5_000, 5);
+        let data = get_vec_of_bytes(1_123_000, 5);
```
Comment (tustvold) [inline object_store/src/lib.rs:772]: This test doesn't seem to "work" in that it passes even when it should fail. Investigating

**Review by tustvold — APPROVED** [review]

File: object_store/src/lib.rs (hunk 1 above)
Comment (wjones127) [reply object_store/src/lib.rs]: Thanks for checking that; I lowered it after I reproduced earlier but didn't retest.
