### PR TITLE
Fix max and min decimal for max precision

### LINKED ISSUE #1916: Incorrect max and min decimals
**Describe the bug**

We define `MAX_DECIMAL_FOR_EACH_PRECISION` and `MIN_DECIMAL_FOR_EACH_PRECISION` for max/min decimals per precision. But the max/min for precision 38 looks incorrect.

**To Reproduce**

**Expected behavior**

For example, according to https://impala.apache.org/docs/build/html/topics/impala_decimal.html,  the range of DECIMAL type is -10^38 +1 through 10^38 –1, if max precision is 38.

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1916.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/datatypes/datatype.rs [hunk 1]
```diff
@@ -238,7 +238,7 @@ pub const MAX_DECIMAL_FOR_EACH_PRECISION: [i128; 38] = [
     99999999999999999999999999999999999,
     999999999999999999999999999999999999,
     9999999999999999999999999999999999999,
-    170141183460469231731687303715884105727,
```
Comment (viirya) [inline arrow/src/datatypes/datatype.rs:241]: This is max value of i128, not max value of decimal of precision 38.

Comment (liukun4515) [reply arrow/src/datatypes/datatype.rs:241]: @viirya 
This is a mistake when i create this table and use the max or min of i128.

**Review by liukun4515 — APPROVED** [review]
Thanks for your fix.
LGTM

**Comment by viirya** [comment]
Thank you @liukun4515
