### PR TITLE
Fix primitive sort when input contains more nulls than the given sort limit

### LINKED ISSUE #953: Incorrect sort result with primitive array that contain more nulls than the sort limit
**Describe the bug**
When sorting with a limit that is lower than the number of null, the sorting code calculates an incorrect length
(`len.saturating_sub(nulls_len)`, which results in 0), the `partial_sort` function then still partitions the data but does not fully sort it.

Instead the formula should take the minimum of the length of valid indices and the given limit.

**To Reproduce**
Sort an array that contains many nulls. A minimal testcase is not that easy to create since the partion/select_nth_unstable_by step still does a partal sort.

### PR DESCRIPTION
**Pull request by jhorstmann**
# Which issue does this PR close?

Closes #953.

# Rationale for this change
 
 
This fixes the calculation for the number of elements that need to be sorted by `sort_unstable_by`

### CODE REVIEW

**Review by andreluecke-signavio — APPROVED** [review]
🚀

File: arrow/src/compute/kernels/sort.rs [hunk 1]
```diff
@@ -1555,6 +1553,19 @@ mod tests {
...
+    #[test]
+    fn test_sort_to_indices_primitive_more_nulls_than_limit() {
+        test_sort_to_indices_primitive_arrays::<Int32Type>(
+            vec![None, None, Some(3), None, Some(1), None, Some(2)],
+            Some(SortOptions {
+                descending: false,
+                nulls_first: false,
+            }),
+            Some(2),
+            vec![4, 6],
```
Comment (alamb) [inline arrow/src/compute/kernels/sort.rs:1565]: 👍
