### PR TITLE
Parquet: Ensure page statistics are written only when conifgured from the Arrow Writer

### LINKED ISSUE #5162: EnabledStatistics::Page  does not take effect on ByteArrayEncoder
**Describe the bug**
when I used below WriterProperties to close column Statistics
```
let w_opt = WriterProperties::builder()
.set_compression(Compression::SNAPPY)
.set_max_row_group_size(1024 * 1024)
.set_data_page_row_count_limit(1024)
.set_statistics_enabled(EnabledStatistics::None)
.set_column_statistics_enabled("taskId".into(), EnabledStatistics::Page) // the only column I want to build ColumnIndex, in Page level
.build();
```

**actual behavior**
I find all column which type is string build ColumnIndex, but I set it did not build.
```
    let mut file = tokio::fs::File::open(file_path).await.unwrap();
    let metadata =
        ArrowReaderMetadata::load_async(&mut file, ArrowReaderOptions::new().with_page_index(true))
            .await
            .unwrap();

use this get metadata like below:
                }), NONE, BYTE_ARRAY(NativeIndex { indexes: [PageIndex { min: Some(ByteArray { data: "ok"
                            }), max: Some(ByteArray { data: "ok"
                            }), null_count: Some(0)
                        }, PageIndex { min: Some(ByteArray { data: "ok"
                            }), max: Some(ByteArray { data: "ok"
                            }), null_count: Some(0)
                        }
                    ], boundary_order: BoundaryOrder(0)
                }), BYTE_ARRAY(NativeIndex { indexes: [PageIndex { min: Some(ByteArray { data: "ok"
                            }), max: Some(ByteArray { data: "ok"
                            }), null_count: Some(0)
                        }, PageIndex { min: Some(ByteArray { data: "ok"
                            }), max: Some(ByteArray { data: "ok"
                            }), null_count: Some(0)
                        }
                    ], boundary_order: BoundaryOrder(0)
                }), BYTE_ARRAY(NativeIndex { indexes: [PageIndex { min: Some(ByteArray { data: "60b6a5dd99c75"
                            }), max: Some(ByteArray { data: "60b6a5dd99c75"
                            }), null_count: Some(0)
                        }, PageIndex { min: Some(ByteArray { data: "60b6a5dd99c75"
                            }), max: Some(ByteArray { data: "60b6a5dd99c75"
                            }), null_count: Some(0)
                        }
                    ], boundary_order: BoundaryOrder(0)
```

**Expected behavior**

I found [ByteArrayEncoder](https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/arrow_writer/byte_array.rs#L501) not use EnabledStatistics value to control that, 
image
like [ColumnValueEncoderImpl](https://github.com/apache/arrow-rs/blob/master/parquet/src/column/writer/encoder.rs#L139) 
image

### PR DESCRIPTION
**Pull request by AdamGS**
# Which issue does this PR close?

Closes #5162.

# Rationale for this change
Currently, he ArrowWriter writes page-level statistics for byte-array-encoded types whether its configured to do so or not.
 

# What changes are included in this PR?

# Are there any user-facing changes?
No

### CODE REVIEW

File: parquet/src/column/writer/mod.rs [hunk 1]
```diff
@@ -764,19 +764,22 @@ impl<'a, E: ColumnValueEncoder> GenericColumnWriter<'a, E> {
...
-                Some(ValueStatistics::new(
-                    Some(min),
-                    Some(max),
-                    None,
-                    self.page_metrics.num_page_nulls,
-                    false,
-                ))
-            }
-            _ => None,
+        let page_statistics = if let (Some(min), Some(max)) =
```
Comment (tustvold) [inline parquet/src/column/writer/mod.rs:767]: Looking at the code it would appear the way this was intended to work is for the encoder itself to not compute page statistics unless EnabledStatistics::Page. If `EnabledStatistics::Chunk` the column stats are computed at a higher-level in write_batch_internal. What do you think about pushing this condition into `ByteArrayEncoder` like it is for `ColumnValueEncoderImpl`?

Comment (AdamGS) [reply parquet/src/column/writer/mod.rs:767]: There's [this](https://github.com/apache/arrow-rs/blob/490c080e5ba7a50efc862da9508e6669900549ee/parquet/src/column/writer/mod.rs#L347) branch to calculate chunk statistics directly when `EnabledStatistics::Chunk`. I think that just having it as the default (For both `Page` and `Chunk`) will probably simplify the code as you don't have to keep track of the chunk-level metadata when adding pages, but it might require a bit more work which is why I didn't end up going that way.
