### PR TITLE
[Parquet] Use `u64` for `SerializedPageReaderState.offset` & `remaining_bytes`, instead of `usize`

### LINKED ISSUE #7910: [Parquet] [Question / Potential Bug Report] Should `SerializedPageReaderState.offset` & `remaining_bytes` be `u64` instead of `usize`?
Hi, I'm raising this both as a question and a possible bug. I'd appreciate your feedback to determine whether this is a confirmed issue.

# The Question

https://github.com/apache/arrow-rs/blob/2be261b78b16a4aa7b5b9aece648bec663c0dbf1/parquet/src/file/serialized_reader.rs#L471-L472

My concern is about the type of `offset` in `SerializedPageReaderState`. Should it be `u64` instead of `usize`? If I understand correctly, this offset represents a global position within a Parquet file, which can easily exceed 4 GB. On 32-bit environments (e.g., WebAssembly), `usize` is limited to `u32`'s max, which could lead to problems with larger files.

# The Potential Bug

As a frequent user of [Parquet viewer](https://parquet-viewer.xiangpeng.systems/) with 32bit WebAssembly, I encountered an error with a file larger than 4 GB. The offset I read exceeded u32's max, resulting in the following error:
```
Integer overflow: out of range integral type conversion attempted
```
I traced this to the line where the exception was triggered, and verified that the offset causing the issue is global and indeed exceeds `u32`'s max.

https://github.com/apache/arrow-rs/blob/2be261b78b16a4aa7b5b9aece648bec663c0dbf1/parquet/src/file/serialized_reader.rs#L604

### PR DESCRIPTION
**Pull request by JigaoLuo**
# Which issue does this PR close?

- Closes #7910

# Rationale for this change

There is a copy from my issue page:
https://github.com/apache/arrow-rs/blob/2be261b78b16a4aa7b5b9aece648bec663c0dbf1/parquet/src/file/serialized_reader.rs#L471-L472
> My concern is about the type of offset in SerializedPageReaderState. Should it be u64 instead of usize? If I understand correctly, this offset represents a global position within a Parquet file, which can easily exceed 4 GB. On 32-bit environments (e.g., WebAssembly), usize is limited to u32's max, which could lead to problems with larger files.

# What changes are included in this PR?

This PR does type changes only for  `SerializedPageReaderState.offset` & `remaining_bytes`

# Are these changes tested?

I can pass with local unit tests via `cargo test -p parquet`

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/file/serialized_reader.rs [hunk 1]
```diff
@@ -469,10 +469,10 @@ pub(crate) fn decode_page(
 enum SerializedPageReaderState {
     Values {
         /// The current byte offset in the reader
```
Comment (XiangpengHao) [inline parquet/src/file/serialized_reader.rs:471]:
```suggestion
        /// The current byte offset in the reader
        /// Note that offset is u64 (i.e., not usize) to support 32-bit architectures such as WASM
```

File: parquet/src/file/serialized_reader.rs [hunk 2]
```diff
@@ -469,10 +469,10 @@ pub(crate) fn decode_page(
...
-        offset: usize,
+        offset: u64,
 
         /// The length of the chunk in bytes
```
Comment (XiangpengHao) [inline parquet/src/file/serialized_reader.rs:475]:
```suggestion
        /// The length of the chunk in bytes
        /// Note that remaining_bytes is u64 (i.e., not usize) to support 32-bit architectures such as WASM
```

**Comment by JigaoLuo** [comment]
Thank you @XiangpengHao for reviewing. I have updated the doc.

**Comment by jhorstmann** [comment]
Looks good to me, thanks!

**Review by mbrobbel — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @JigaoLuo and thanks @mbrobbel and @jhorstmann

**Comment by JigaoLuo** [comment]
Thank you to all the reviewers
