### PR TITLE
Include footer key metadata when writing encrypted Parquet with a plaintext footer

### LINKED ISSUE #7599: When writing parquet plaintext footer files `footer_signing_key_metadata` is not included, encryption alghoritm is always written in footer
**Describe the bug**
When writing plaintext footer `footer_signing_key_metadata` is not included. This means a key retriever cannot be used to read files with plaintext footers.

Additionally, the footer encryption algorithm is currently written inside the footer even when the footer is encrypted but this is redundant and goes against the spec:
https://github.com/apache/parquet-format/blob/f1fd3b9171aec7a7f0106e0203caef88d17dda82/src/main/thrift/parquet.thrift#L1294-L1298

**To Reproduce**
Written plaintext footer file will not include `footer_signing_key_metadata`.
Written encrypted non-plaintext footer files shouldn't include `encryption_algorithm`.

**Additional context**
This is was caused by https://github.com/apache/arrow-rs/pull/7439

### PR DESCRIPTION
**Pull request by rok**
# Which issue does this PR close?

Closes #7599.

# Rationale for this change

Written plaintext footer file will not include `footer_signing_key_metadata`, see proposed test for reproduction.
Written encrypted non-plaintext footer files shouldn't include `encryption_algorithm`, see proposed test for reproduction.

# What changes are included in this PR?

`footer_signing_key_metadata` is now included in plaintext footer file and `encryption_algorithm` is not included in the footer if footer is non-plaintext.

# Are there any user-facing changes?

This doesn't change user facing API.

### CODE REVIEW

File: parquet/src/file/metadata/writer.rs [hunk 1]
```diff
@@ -635,11 +636,17 @@ impl MetadataObjectWriter {
         }
     }
 
-    fn get_footer_encryption_algorithm(&self) -> Option<EncryptionAlgorithm> {
-        if let Some(file_encryptor) = &self.file_encryptor {
-            return Some(Self::encryption_algorithm_from_encryptor(file_encryptor));
+    fn get_plaintext_footer_metadata(&self) -> (Option<EncryptionAlgorithm>, Option<Vec<u8>>) {
```
Comment (adamreeve) [inline parquet/src/file/metadata/writer.rs]: Nitpicking but I think this should have something encryption related in the name even though it's already quite long... How about `get_plaintext_footer_crypto_metadata`? Or it could be `get_footer_crypto_metadata` and have a comment that the footer only contains encryption metadata when using plaintext footers?

File: parquet/tests/encryption/encryption.rs [hunk 2]
```diff
@@ -256,6 +256,72 @@ fn test_non_uniform_encryption_plaintext_footer_with_key_retriever() {
...
+    let path = format!("{test_data}/encrypt_columns_plaintext_footer.parquet.encrypted");
+    let file = File::open(path).unwrap();
+    let temp_file = tempfile::tempfile().unwrap();
+
+    let key_retriever = TestKeyRetriever::new()
+        .with_key("kf".to_owned(), b"0123456789012345".to_vec())
+        .with_key("kc1".to_owned(), b"1234567890123450".to_vec())
+        .with_key("kc2".to_owned(), b"1234567890123451".to_vec());
+
+    let encryption_properties = FileEncryptionProperties::builder(b"0123456789012345".to_vec())
```
Comment (adamreeve) [inline parquet/tests/encryption/encryption.rs:284]: This test is a bit confusing to follow. Eg. `temp_file` and these encryption properties aren't used until later when we rewrite the data. Could we move them down and define them closer to where they're used, and maybe add some brief comments about what's going on?

File: parquet/tests/encryption/encryption.rs [hunk 3]
```diff
@@ -256,6 +256,72 @@ fn test_non_uniform_encryption_plaintext_footer_with_key_retriever() {
...
+        Some(props),
+    )
+    .unwrap();
+    for batch in batches {
+        writer.write(&batch).unwrap();
+    }
+
+    writer.close().unwrap();
+
+    let key_retriever = TestKeyRetriever::new()
```
Comment (adamreeve) [inline parquet/tests/encryption/encryption.rs]: Rather than creating a new `key_retriever` here, we could create it inside an `Arc` initially and then clone it.

File: parquet/src/file/metadata/writer.rs (hunk 1 above)
Comment (rok) [reply parquet/src/file/metadata/writer.rs]: Good point! Went with `get_plaintext_footer_crypto_metadata` and comment:
```rust
// Only plaintext footers may contain encryption algorithm and footer key metadata.
```

File: parquet/tests/encryption/encryption.rs (hunk 2 above)
Comment (rok) [reply parquet/tests/encryption/encryption.rs:284]: Indeed, moved things into a more logical order and added comments.

File: parquet/tests/encryption/encryption.rs (hunk 3 above)
Comment (rok) [reply parquet/tests/encryption/encryption.rs]: Oh, wasn't aware of that mechanism. Done.

**Review by adamreeve — APPROVED** [review]
Looks good to me thanks Rok

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @rok and @adamreeve
