### PR TITLE
Do not print compression level in schema printer

### LINKED ISSUE #6270: Printing schema metadata includes possibly incorrect compression level
**Describe the bug**
`print_parquet_metadata` always reports ZSTD compression level 1, regardless of the level used when creating the file:
```
compression: ZSTD(ZstdLevel(1))
```
The cause is that the compression level is not actually stored anywhere. The value `1` is just the `Default` of `ZstdLevel`, needed to construct the `Compression` enum.

**To Reproduce**
Call `print_parquet_metadata` on a file using `ZSTD` compression using a non-default level. E.g. I used level 6.

**Expected behavior**
```
compression: ZSTD
```

**Additional context**
Discovered on https://github.com/manojkarthick/pqrs/issues/53.

### PR DESCRIPTION
**Pull request by ttencate**
The compression level is only used during compression, not decompression, and isn't actually stored in the metadata. Printing it is misleading.

# Which issue does this PR close?

Closes #6270.

# Rationale for this change
 
Theoretically, there should be a `Compression` enum that doesn't store the level, but that doesn't seem worth the trouble and API breakage.

Instead, I just added a method `codec_to_string()` that returns the `Debug` output up to the first `(`. This is easier to maintain and hopefully less error-prone than adding a `match`. It's less efficient, but efficiency doesn't matter much here.

# Are there any user-facing changes?

No. The output of `print_parquet_metadata` is neither documented nor tested, and should therefore not be considered stable.

### CODE REVIEW

File: parquet/src/basic.rs [hunk 1]
```diff
@@ -358,6 +358,14 @@ pub enum Compression {
     LZ4_RAW,
 }
 
+impl Compression {
+    /// Returns the codec type of this compression setting as a string, without the compression
+    /// level.
+    pub(crate) fn codec_to_string(self) -> String {
+        format!("{:?}", self).split('(').next().unwrap().to_owned()
```
Comment (alamb) [inline parquet/src/basic.rs:365]: It would be nice to avoid panic'ing here if there is no `(` in the string -- I think this will panic if it is called on `CompressionLevel::UNCOMPRESSED` for example

**Review by alamb — COMMENTED** [review]
Thanks for the contribution @ttencate  -- I think this PR needs some test coverage (unit tests for `CompressionLevel::codec_to_string`. 

I also think it is going to panic for certain compression types

File: parquet/src/basic.rs (hunk 1 above)
Comment (ttencate) [reply parquet/src/basic.rs:365]: If there is no `(`, then `split()` will return just one component – the entire string (even if it's empty). There is no way this can panic. But I've added a test anyway.

**Comment by ttencate** [comment]
Thanks for the review! Added some simple tests. (I initially had doctests, but they won't work on `pub(crate)` functions. Should have just turned them into regular unit tests straight away...)

**Comment by alamb** [comment]
Thanks again @ttencate
