### PR TITLE
Fix simd comparison kernels

### LINKED ISSUE #1285: Mistake in chunked part of comparison kernels
**Describe the bug**
Comparison kernels seem to return incorrect results

**To Reproduce**
Noticed when updating arrow version in our code. Issue seems to only occur with larger data sets and only with simd feature active. Comparison tests do not seem to cover any arrays > 64 elements, so probably the bug is in the chunked part of the comparison logic.

### PR DESCRIPTION
**Pull request by jhorstmann**
# Which issue does this PR close?

Closes #1285 .

# Rationale for this change
 
The refactoring of the simd comparison in #1146 introduced silly mistake that was not noticed due to missing test coverage.

# What changes are included in this PR?

Apart from the bugfix, this adjusts the tests so they automatically also test a larger version of the test input and so cover the chunked part.

### CODE REVIEW

**Comment by jhorstmann** [comment]
@alamb I'm sorry for only noticing this issue so late. Would be nice if we could still include it in the 9.0 release.

File: arrow/src/compute/kernels/comparison.rs [hunk 1]
```diff
@@ -2442,6 +2442,20 @@ mod tests {
             let b = b.slice(0, b.len());
             let c = $DYN_KERNEL(a.as_ref(), b.as_ref()).unwrap();
             assert_eq!(BooleanArray::from($EXPECTED), c);
+
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:2445]: 👍  in case anyone else is curious, without the code fix, this test fails like this:

```shell

---- compute::kernels::comparison::tests::test_primitive_array_eq stdout ----
thread 'compute::kernels::comparison::tests::test_primitive_array_eq' panicked at 'assertion failed: `(left == right)`
  left: `BooleanArray
[
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  true,
  false,
  false,
  ...80 elements...,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  true,
  false,
  false,
]`,
 right: `BooleanArray
[
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  ...80 elements...,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  true,
  false,
  false,
]`', arrow/src/compute/kernels/comparison.rs:2486:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
...

```

**Review by alamb — APPROVED** [review]
Thank you @jhorstmann
