### PR TITLE
Optionally require alignment when reading IPC, respect alignment when writing

### LINKED ISSUE #5553: IPC code writes data with insufficient alignment
**Describe the bug**

`FileWriter` and `StreamWriter` should ensure that the data is written with appropriate alignment such that arrays can be used without copying to a more-aligned buffer.

In particular, as of [Rust 1.77.0](https://github.com/rust-lang/rust/releases/tag/1.77.0) and [LLVM 18](https://reviews.llvm.org/D86310), `i128` now has a 16-byte alignment requirement even on x86 (ARM always had this requirement), i.e. `std::mem::align_of::<i128> == 16`. So `Decimal128Array`s must be aligned to a 16-byte boundary when serialized into an IPC buffer. The `pad_to_8` used everywhere in the IPC code causes it to pad insufficiently.

This prevents readers of the IPC data generated by this crate from doing _true_ zero-copy reads (e.g. mmapping) since the data may be insufficiently aligned.

On some platforms, SIMD may also be significantly slower if the beginning of the IPC block isn't aligned to a 16-, 32-, or 64- byte boundary (as discussed in the [Arrow spec document](https://arrow.apache.org/docs/format/Columnar.html#buffer-alignment-and-padding)).

**To Reproduce**

See the test `test_decimal128_alignment8_is_unaligned` in PR #5554 - the fact that this test throws an error shows that `alignment` is not currently respected.

**Expected behavior**

See the test `test_decimal128_alignment16` in PR #5554 - increasing alignment should allow us to do "true" zero-copy reads.

**Additional context**

`IpcWriteOptions` already has an "alignment" field but it is not being respected throughout the IPC code.

Related PRs and issues:
- https://github.com/apache/arrow-rs/pull/2884
- https://github.com/apache/arrow-rs/commit/32c9dea9c3003e114b9981cae15acdfc8448971b
- https://github.com/apache/arrow-rs/issues/2882
- https://github.com/apache/arrow-rs/pull/2883

### PR DESCRIPTION
**Pull request by hzuo**
# Which issue does this PR close?

Closes #5553

# Rationale for this change
 
`FileWriter` and `StreamWriter` should ensure that the data is written with appropriate alignment such that arrays can be used without copying to a more-aligned buffer.

In particular, as of [Rust 1.77.0](https://github.com/rust-lang/rust/pull/116672/) and [LLVM 18](https://reviews.llvm.org/D86310), `i128` now has a 16-byte alignment requirement even on x86 (ARM always had this requirement), i.e. `std::mem::align_of::<i128> == 16`. So `Decimal128Array`s must be aligned to a 16-byte boundary when serialized into an IPC buffer. The `pad_to_8` used everywhere in the IPC code causes it to pad insufficiently.

This prevents readers of the IPC data generated by this crate from doing _true_ zero-copy reads (e.g. mmapping) since the data may be insufficiently aligned. See #5165, #5153.

On some platforms, SIMD may also be significantly slower if the beginning of the IPC block isn't aligned to a 16-, 32-, or 64- byte boundary (as discussed in the [Arrow spec document](https://arrow.apache.org/docs/format/Columnar.html#buffer-alignment-and-padding)).

(copied from issue)

# What changes are included in this PR?

- Make all the IPC code actually respect the `alignment` specified in `IpcWriteOptions`
- Add new `require_alignment` option to `FileDecoder`, `read_record_batch`, and `read_dictionary`, which enforces that the read is a zero-copy read. Previously if the buffer was unaligned then the code automatically allocates an aligned buffer and performs a memcpy (`build_aligned` => `align_buffers`), which users of Arrow as a zero-copy format may not expect / may want to enforce does not happen.

# Are there any user-facing changes?

Yes:
- `alignment` in `IpcWriteOptions::try_with` cannot be larger than 64 bytes - previously unbounded (breaking but minor)
- New `require_alignment` argument on `read_record_batch` and `read_dictionary` (breaking but minor)
- New option `with_require_alignment` to FileDecoder (non-breaking)

### CODE REVIEW

File: arrow-ipc/src/writer.rs [hunk 1]
```diff
@@ -2234,4 +2270,124 @@ mod tests {
...
+
+            let batch2 = decoder.read_record_batch(block, &data).unwrap().unwrap();
+
+            assert_eq!(batch, batch2);
+        }
+    }
+
+    #[test]
+    fn test_decimal128_alignment8_is_unaligned() {
+        const IPC_ALIGNMENT: u8 = 8;
```
Comment (hzuo) [inline arrow-ipc/src/writer.rs:2333]: This test is equivalent to the current behavior without the changes in this PR, it's equivalent to using `pad_to_8` everywhere.

File: arrow-buffer/src/buffer/scalar.rs [hunk 2]
```diff
@@ -63,9 +63,15 @@ impl<T: ArrowNativeType> ScalarBuffer<T> {
...
     /// * `offset` or `len` would result in overflow
-    /// * `buffer` is not aligned to a multiple of `std::mem::size_of::<T>`
+    /// * `buffer` is not aligned to a multiple of `std::mem::align_of::<T>`
     /// * `bytes` is not large enough for the requested slice
     pub fn new(buffer: Buffer, offset: usize, len: usize) -> Self {
+        assert_eq!(
+            buffer.as_ptr().align_offset(std::mem::align_of::<T>()),
+            0,
+            "buffer is not aligned"
+        );
```
Comment (hzuo) [inline arrow-buffer/src/buffer/scalar.rs:73]: This was not previously checked even though the docs said it was checked.

File: arrow-ipc/src/writer.rs [hunk 3]
```diff
@@ -1406,17 +1437,20 @@ fn write_buffer(
...
+    // padding and make offset aligned
+    let pad_len = pad_to_alignment(alignment, len as usize);
+    arrow_data.extend_from_slice(&PADDING[..pad_len]);
 
-    Ok(offset + len + pad_len)
+    Ok(offset + len + (pad_len as i64))
 }
 
-/// Calculate an 8-byte boundary and return the number of bytes needed to pad to 8 bytes
+const PADDING: [u8; 64] = [0; 64];
```
Comment (hzuo) [inline arrow-ipc/src/writer.rs:1447]: previously a Vec was being allocated every time padding was needed

File: arrow-buffer/src/buffer/scalar.rs (hunk 2 above)
Comment (tustvold) [reply arrow-buffer/src/buffer/scalar.rs:73]: It is checked in the from conversion

**Comment by tustvold** [comment]
I'm travelling for the next few days, but will try to get to this on my return if nobody else gets there first

File: arrow-buffer/src/buffer/scalar.rs (hunk 2 above)
Comment (hzuo) [reply arrow-buffer/src/buffer/scalar.rs:73]: but a user could call `new` without going through the From conversion, right? and the docs are specifically talking about `new`?

also looks like `From<Buffer> for ScalarBuffer<T>` doesn't go through `new` so this wouldn't add any additional overhead

but not opinionated about this at all - happy to remove if you'd like

Comment (tustvold) [reply arrow-buffer/src/buffer/scalar.rs:73]: The `.into()` call a few lines below invokes the From conversion

Comment (hzuo) [reply arrow-buffer/src/buffer/scalar.rs:73]: ah ok, great catch! will remove it

File: arrow-ipc/src/reader.rs [hunk 4]
```diff
@@ -71,7 +71,11 @@ fn read_buffer(
 ///     - check if the bit width of non-64-bit numbers is 64, and
 ///     - read the buffer as 64-bit (signed integer or float), and
 ///     - cast the 64-bit array to the appropriate data type
-fn create_array(reader: &mut ArrayReader, field: &Field) -> Result<ArrayRef, ArrowError> {
+fn create_array(
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:74]: Can you please add some documentation on what `enforce_zero_copy` does to the docstrings?

File: arrow-ipc/src/reader.rs [hunk 5]
```diff
@@ -628,6 +688,19 @@ impl FileDecoder {
         self
     }
 
+    /// Specify whether to enforce zero copy, which means the array data inside the record batches
+    /// produced by this decoder will always reference the input buffer.
+    ///
+    /// In particular, this means that if there is data that is not aligned properly in the
+    /// input buffer, the decoder will throw rather than copy the data to an aligned buffer.
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:695]:
```suggestion
    /// input buffer, the decoder will return an error rather than copy the data to an aligned buffer.
```

File: arrow-ipc/src/reader.rs [hunk 6]
```diff
@@ -628,6 +688,19 @@ impl FileDecoder {
         self
     }
 
+    /// Specify whether to enforce zero copy, which means the array data inside the record batches
+    /// produced by this decoder will always reference the input buffer.
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:692]: What do you think about calling this concept / field `require_alignment` which describes what is required (rather than how it is enforced)?

It might also help make the intent clearer to users (that the IPC decoder will error if the buffers are not aligned properly)

I don't feel super strongly about this, but I was a little confused about what `enforce_zero_copy` meant until I found this comment

File: arrow-ipc/src/reader.rs [hunk 7]
```diff
@@ -1801,11 +1878,56 @@ mod tests {
             &Default::default(),
             None,
             &message.version(),
+            false,
         )
         .unwrap();
         assert_eq!(batch, roundtrip);
     }
 
+    #[test]
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:1887]: ❤️

File: arrow-integration-testing/src/flight_server_scenarios/integration_test.rs [hunk 8]
```diff
@@ -308,6 +308,7 @@ async fn record_batch_from_message(
         dictionaries_by_id,
         None,
         &message.version(),
+        false,
```
Comment (alamb) [inline arrow-integration-testing/src/flight_server_scenarios/integration_test.rs:311]: if these are true, do the tests fail?

File: arrow-ipc/src/reader.rs [hunk 9]
```diff
@@ -1801,11 +1878,56 @@ mod tests {
             &Default::default(),
             None,
             &message.version(),
+            false,
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:1881]: does this fail if you pass `true`?

File: arrow-ipc/src/reader.rs [hunk 10]
```diff
@@ -396,6 +451,7 @@ pub fn read_record_batch(
     dictionaries_by_id: &HashMap<i64, ArrayRef>,
     projection: Option<&[usize]>,
     metadata: &MetadataVersion,
+    enforce_zero_copy: bool,
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:454]: Since `read_record_batch` is `pub` I think we should also document the parameter here as well (maybe link back to the array builder's docs)

https://docs.rs/arrow-ipc/latest/arrow_ipc/reader/fn.read_record_batch.html

File: arrow-ipc/src/reader.rs [hunk 11]
```diff
@@ -456,6 +512,7 @@ pub fn read_dictionary(
     schema: &Schema,
     dictionaries_by_id: &mut HashMap<i64, ArrayRef>,
     metadata: &MetadataVersion,
+    enforce_zero_copy: bool,
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:515]: likewise this is a public function as well so I think the parameter should be documented

File: arrow-ipc/src/reader.rs [hunk 12]
```diff
@@ -1801,11 +1878,56 @@ mod tests {
...
+        let mut dict_tracker = DictionaryTracker::new(false);
+        let (_, encoded) = gen
+            .encoded_batch(&batch, &mut dict_tracker, &Default::default())
+            .unwrap();
+
+        let message = root_as_message(&encoded.ipc_message).unwrap();
+
+        // Construct an unaligned buffer
+        let mut buffer = MutableBuffer::with_capacity(encoded.arrow_data.len() + 1);
+        buffer.push(0_u8);
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:1905]: 👍

File: arrow-ipc/src/reader.rs [hunk 13]
```diff
@@ -1801,11 +1878,56 @@ mod tests {
...
+        );
+
+        let error = result.unwrap_err();
+        match error {
+            ArrowError::InvalidArgumentError(e) => {
+                assert!(e.contains("Misaligned"));
+                assert!(e.contains("offset from expected alignment of"));
+            }
+            _ => panic!("Expected InvalidArgumentError"),
+        }
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:1928]: Another way to test this is to do something like 
```rust
let err = result.unwrap_err();
assert_eq!(err.to_string(), "expected error string")
```
This also works I just figured I would pass it along

File: arrow-ipc/src/writer.rs [hunk 14]
```diff
@@ -2234,4 +2270,128 @@ mod tests {
...
+
+    #[test]
+    fn test_decimal128_alignment16() {
+        const IPC_ALIGNMENT: u8 = 16;
+
+        // Test a bunch of different dimensions to ensure alignment is never an issue.
+        // For example, if we only test `num_cols = 1` then even with alignment 8 this
+        // test would _happen_ to pass, even though for different dimensions like
+        // `num_cols = 2` it would fail.
+        for num_cols in 1..100 {
```
Comment (alamb) [inline arrow-ipc/src/writer.rs:2282]: do we really need to test 100 columns? That seems overly compute sensitive for relatively small additional coverage.  Maybe we could use a few  few distinct ones like `1, 17, 23, 73` ?

File: arrow-ipc/src/writer.rs [hunk 15]
```diff
@@ -83,13 +84,13 @@ impl IpcWriteOptions {
     }
     /// Try create IpcWriteOptions, checking for incompatible settings
     pub fn try_new(
-        alignment: usize,
+        alignment: u8,
```
Comment (alamb) [inline arrow-ipc/src/writer.rs:87]: this is a breaking API change. Since it is fallable anyways, could you perhaps leave the argument a `usize` and throw an error if it is out of range (aka `let alignment = u8::try_from(alignment).map_err(|e| ...)`?)

File: arrow-ipc/src/writer.rs [hunk 16]
```diff
@@ -2234,4 +2270,128 @@ mod tests {
...
+
+            let buffer = Buffer::from_vec(out);
+            let trailer_start = buffer.len() - 10;
+            let footer_len =
+                read_footer_length(buffer[trailer_start..].try_into().unwrap()).unwrap();
+            let footer =
+                root_as_footer(&buffer[trailer_start - footer_len..trailer_start]).unwrap();
+
+            let schema = fb_to_schema(footer.schema().unwrap());
+            assert_eq!(&schema, batch.schema().as_ref());
```
Comment (alamb) [inline arrow-ipc/src/writer.rs:2315]: I am not sure how much value these checks add -- they are redundant with other code I think and somewhat obscure the point of the test (to set with_enforce_zero_copy and read the data back without error)

File: arrow-ipc/src/writer.rs [hunk 17]
```diff
@@ -2234,4 +2270,128 @@ mod tests {
...
+
+            let decoder =
```
Comment (alamb) [inline arrow-ipc/src/writer.rs:2317]: Maybe worth a comment here that the test is that the validation is happening here

**Review by alamb — APPROVED** [review]
Thank you very much for this contribution @huzo 🙏 

I think it looks great overall and makes sense. I had a few small comments but I also think this PR could be merged as is.

It would probably be good to get someone else like @tustvold t give it a review prior to merge, but all in all very nice

File: arrow-ipc/src/reader.rs (hunk 6 above)
Comment (hzuo) [reply arrow-ipc/src/reader.rs:692]: Yeah I agree, will make this change.

My original thinking was that there might be a variety of reasons why IPC decoders may need to create a copy of the input data, and this would be a catch-all so that the users don't have to understand the intricacies of why or why not copies need to be made.

But agree that it ends up being kinda vague, and in the future if there are other reasons copies need to be made, probably better to expose each of the "reasons" as a granular "requirement" - if there ends up being a ton, we can expose a catch-all, but no reason to anticipate that today at the expense of clarity.

File: arrow-integration-testing/src/flight_server_scenarios/integration_test.rs (hunk 8 above)
Comment (hzuo) [reply arrow-integration-testing/src/flight_server_scenarios/integration_test.rs:311]: Probably wouldn't fail - I didn't read through the full integration test but as long as it's not using Decimal128 then 8-byte alignment is sufficient, so it should succeed even with `require_alignment=true`.

Passing `false` is equivalent to the previous behavior where a copy was automatically made if the data was unaligned, so I didn't want to introduce new behavior to existing tests.

Comment (alamb) [reply arrow-integration-testing/src/flight_server_scenarios/integration_test.rs:311]: makes sense

File: arrow-ipc/src/reader.rs (hunk 13 above)
Comment (hzuo) [reply arrow-ipc/src/reader.rs:1928]: for sure - but the error message is dynamic so I figured a strict equality check was too strict - e.g. if the error message formatting or some debug impl changes, should I care about that in this test?

happy to do a strict equality check if that's generally the style in this repo!

Comment (hzuo) [reply arrow-ipc/src/reader.rs]: doing strict equality checks now!

**Comment by alamb** [comment]
so close!

File: arrow-ipc/src/reader.rs [hunk 18]
```diff
@@ -428,14 +485,24 @@ impl<'a> ArrayReader<'a> {
...
+/// (Properly aligned array data will remain zero-copy.)
+/// Under the hood it will use [`arrow_data::ArrayDataBuilder::build_aligned`] to construct [`arrow_data::ArrayData`].
 pub fn read_record_batch(
     buf: &Buffer,
     batch: crate::RecordBatch,
     schema: SchemaRef,
     dictionaries_by_id: &HashMap<i64, ArrayRef>,
     projection: Option<&[usize]>,
     metadata: &MetadataVersion,
+    require_alignment: bool,
```
Comment (tustvold) [inline arrow-ipc/src/reader.rs:505]: This is a breaking change to a public method, I think it would be good to find a way to avoid this. Perhaps by encapsulating some or all of the arguments onto a struct or something?

**Review by tustvold — APPROVED** [review]
This looks good, my only concern is the breaking API change, where feedback from the community has been requesting we reduce the frequency of these - #5368

File: arrow-ipc/src/reader.rs (hunk 18 above)
Comment (alamb) [reply arrow-ipc/src/reader.rs:505]: Perhaps we could do:

```rust
pub fn read_record_batch_with_options(buf: &Buffer, opts: &SomeNewOptsStruct) { ...

}
```

And then have `read_record_batch` call that new function?

Comment (tustvold) [reply arrow-ipc/src/reader.rs:505]: Yeah something like that, or possibly some sort of `Decoder` struct with a member function on it...

Ideally it would be designed so that it could be shared across things like `StreamDecoder` and `FileDecoder`

Comment (hzuo) [reply arrow-ipc/src/reader.rs:505]: That makes sense. I think you guys will have a vision around what goes into the struct vs what doesn't, and where throughout the codebase that struct should be passed (probably it isn't specific to read_record_batch).

To keep this PR bounded, what I'll propose for now is just make a private version, e.g. `read_record_batch2` with this extra `require_alignment: bool` arg, and keep the signature of the `pub fn read_record_batch` exactly as-is - the public one calls the private one with `false` to keep the behavior the same.

Once merged, you guys can spin up the work to figure out struct to collect the various parameters, and the `require_alignment` functionality can eventually be exposed through that options struct.

Does keeping this PR bounded in this way sound good?

Comment (hzuo) [reply arrow-ipc/src/reader.rs:534]: okay pushed the above - lmk if you would prefer a different approach

File: arrow-ipc/src/reader.rs [hunk 19]
```diff
@@ -495,7 +524,7 @@ impl<'a> ArrayReader<'a> {
 /// and copy over the data if any array data in the input `buf` is not properly aligned.
 /// (Properly aligned array data will remain zero-copy.)
 /// Under the hood it will use [`arrow_data::ArrayDataBuilder::build_aligned`] to construct [`arrow_data::ArrayData`].
-pub fn read_record_batch(
```
Comment (tustvold) [inline arrow-ipc/src/reader.rs:432]: Can we keep the doc comment on the non-private version?

File: arrow-ipc/src/reader.rs (hunk 18 above)
Comment (alamb) [reply arrow-ipc/src/reader.rs:536]: Filed https://github.com/apache/arrow-rs/issues/5588 to track a potentially new API. Thanks @hzuo  and @tustvold
