### PR TITLE
Include line and field number in CSV UTF-8 error (#3656)

### LINKED ISSUE #3656: Regression in CSV reader error handling
**Describe the bug**

I have a tool that reads CSV files using DataFusion. I have a file with an invalid UTF-8 character, apparently.

With DataFusion 16.1.0 (Arrow 29), I get this error:

```
Arrow error: Parser error: Error parsing line 27: Error(Utf8 { pos: Some(Position { byte: 3458, line: 28, record: 27 }), err: Utf8Error { field: 14, valid_up_to: 1 } })"))
```

With DataFusion 17.0.0 (Arrow 31), I get this error:

```
ArrowError("underlying Arrow error: Csv error: Encountered invalid UTF-8 data: invalid utf-8 sequence of 1 bytes from index 2911"))
```

The first error is much more helpful because it gives me the line and field numbers. I was quickly able to locate the bad character.

**To Reproduce**

Try reading a CSV file with invalid UTF-8 characters (perhaps try reading some random binary file).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3656

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-csv/src/reader/mod.rs [hunk 1]
```diff
@@ -2231,4 +2231,37 @@ mod tests {
...
     }
+
+    fn err_test(csv: &[u8], expected: &str) {
+        let schema = Arc::new(Schema::new(vec![
+            Field::new("text1", DataType::Utf8, false),
+            Field::new("text2", DataType::Utf8, false),
+        ]));
+        let buffer = std::io::BufReader::with_capacity(2, Cursor::new(csv));
+        let b = ReaderBuilder::new()
+            .with_schema(schema)
```
Comment (tustvold) [inline arrow-csv/src/reader/mod.rs:2242]: We need to provide the schema here, as otherwise the schema inference code produces the error

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @tustvold!
