### PR TITLE
Restrict RecordReader and friends to scalar types (#1132)

### LINKED ISSUE #1132: RecordReader Permits Illegal Types
**Describe the bug**

Originally pointed out by @jorgecarleitao [here](https://github.com/apache/arrow-rs/pull/1041#discussion_r778438011).

It is currently possible to construct `RecordReader<T>` and by extension `PrimitiveArrayReader` with any `T: DataType`. This is despite an explicit assumption in `RecordReader`'s buffering logic that `DataType::T` can be zero-initialized and stored in `MutableBuffer`.

Fortunately `DataType::T: ParquetValueType` which is a sealed trait, however, `ParquetValueType` is implemented for types such as `Int96` and `ByteArray` which aren't POD. 

**To Reproduce**

```
PrimitiveArrayReader::<ByteArrayType>::new(...)
```

**Expected behavior**

It shouldn't be possible to construct `PrimitiveArrayReader` with invalid types

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1132.

# Rationale for this change
 
See ticket

# What changes are included in this PR?

This restricts RecordReader and friends to only permit legal types

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/data_type.rs [hunk 1]
```diff
@@ -1032,6 +1033,21 @@ pub(crate) mod private {
...
+
+    /// A marker trait for [`DataType`] with a [scalar] physical type
+    ///
+    /// This means that a `[Self::T::default()]` of length `len` can be safely created from a
+    /// zero-initialized `[u8]` with length `len * Self::get_type_size()` and
+    /// alignment of `Self::get_type_size()`
+    ///
+    /// [scalar]: https://doc.rust-lang.org/book/ch03-02-data-types.html#scalar-types
+    ///
+    pub trait ScalarDataType: DataType {}
```
Comment (tustvold) [inline parquet/src/data_type.rs:1045]: I also considered `PrimitiveDataType` or `PlainOldDataType` but thought this was less overloaded, and corresponds to the Rust nomenclature

**Comment by alamb** [comment]
Looks like a good change to me.

FYI @yordan-pavlov
