### PR TITLE
Fix casting floats to Decimal64

### LINKED ISSUE #8362: Casting floating point numbers fails for Decimal64 but works for other variants
**Describe the bug**
Casting a floating point number like `1.1_f64` to decimal64 fails. 

**To Reproduce**
The following test fails, but only for `Decimal64`.
```rust
    #[test]
    fn test_cast_floating_to_decimals() {
        for output_type in [
            DataType::Decimal32(9, 3),
            DataType::Decimal64(9, 3),
            DataType::Decimal128(9, 3),
            DataType::Decimal256(9, 3),
        ] {
            let input_type = DataType::Float64;
            assert!(can_cast_types(&input_type, &output_type));

            let array = vec![Some(1.1_f64)];
            let array = PrimitiveArray::<Float64Type>::from_iter(array);
            let result = cast_with_options(
                &array,
                &output_type,
                &CastOptions {
                    safe: false,
                    format_options: FormatOptions::default(),
                },
            );
            assert!(
                result.is_ok(),
                "Failed to cast to {output_type} with: {}",
                result.unwrap_err().to_string()
            );
        }
    }
```

**Expected behavior**
This cast operation should work for all decimal types.

**Additional context**

### PR DESCRIPTION
**Pull request by AdamGS**
# Which issue does this PR close?
Closes #8362

# Rationale for this change
Fixes casting codepaths that currently fail.

# What changes are included in this PR?

# Are these changes tested?

yes

If tests are not included in your PR, please explain why (for example, are they covered by existing tests)?

# Are there any user-facing changes?

Code should now behave as expected

### CODE REVIEW

File: arrow-cast/src/cast/decimal.rs [hunk 1]
```diff
@@ -81,7 +81,7 @@ impl DecimalCast for i64 {
     }
 
     fn from_f64(n: f64) -> Option<Self> {
-        n.to_i64()
+        num::traits::ToPrimitive::to_i64(&n)
```
Comment (AdamGS) [inline arrow-cast/src/cast/decimal.rs:86]: Otherwise, compiler goes to a `to_i64` from `arrow-buffer` that behaves differently.

Comment (alamb) [reply arrow-cast/src/cast/decimal.rs:86]: It might be nice to add a comment here explaining the non obvious rationale:

```suggestion
        // Call implementation explicitly otherwise this resolves to `to_i64` 
        // in arrow-buffer that behaves differently.
        num::traits::ToPrimitive::to_i64(&n)
```

**Comment by alamb** [comment]
FWIW the new test fails like this without the changes to the code

```
Failed to cast to Decimal64(9, 3) with: Cast error: Cannot cast to Decimal64(9, 3). Overflowing on 1.1
thread 'cast::tests::test_cast_floating_to_decimals' panicked at arrow-cast/src/cast/mod.rs:3125:13:
Failed to cast to Decimal64(9, 3) with: Cast error: Cannot cast to Decimal64(9, 3). Overflowing on 1.1
stack backtrace:
```
