### PR TITLE
fix: bug when struct nullability determined from `Dict<_, ByteArray>>` column

### LINKED ISSUE #8404: Column with List(Struct) causes failed to decode level data for struct array
**Describe the bug**

I have a file generated using polars which polars, duckdb and other tools read fine. arrow-rs fails with a `Failed to decode level data for struct array` error.

**To Reproduce**

Try to read the following file: https://storage.googleapis.com/ids-next/arrow-bug-dremel-encoding.parquet e.g. via

```
pub(crate) fn bug() -> () {
    let src = "https://storage.googleapis.com/ids-next/arrow-bug-dremel-encoding.parquet";
    let mut reader = File::open(src.strip_prefix("file://").unwrap()).unwrap();

    let metadata = ArrowReaderMetadata::load(&mut reader, ArrowReaderOptions::default()).unwrap();

    let mut market_reader =
        ParquetRecordBatchReaderBuilder::new_with_metadata(reader, metadata.clone())
            .build()
            .unwrap();

    let mut count = 0;

    while let Some(batch) = market_reader.next() {
        let batch = batch.unwrap();
        count += batch.num_rows();
    }

    println!("Read {} rows", count);

    ()
}
```

**Expected behavior**

The file should read or provide a better error if the file contains something unsupported.

**Additional context**

I tried to come up with a unit test for struct_array.rs but ran out of time.
I tried this with a struct of only ints, but that didn't trigger the bug; thus, I assume the dict might be part of the cause.

### PR DESCRIPTION
**Pull request by albertlockett**
# Which issue does this PR close?

- Closes #8404

# Rationale for this change

A regression was reported in issue #8404 which was introduced in https://github.com/apache/arrow-rs/pull/7585. This PR resolves the issue.

# What changes are included in this PR?

The root cause of the issue was that the behaviour of `ByteArrayDictionaryReader` is to return a new empty length array of values if the record reader has already been consumed. The problem was that the repetition and definition level buffers were not being advanced in this early return case.

https://github.com/apache/arrow-rs/blob/521f219e308613811aeae11300bf7a7b0fb5ec29/parquet/src/arrow/array_reader/byte_array_dictionary.rs#L167-L183

The `StructArrayReader` reads the repetition and definition levels from the first child to determine the nullability of the struct array. When we returned the empty values buffer for the child, without advancing the repetition and definition buffers, the `StructArrayReader` a length mismatch between the empty child array and the non-empty nullability bitmask, and this produces the error.

https://github.com/apache/arrow-rs/blob/521f219e308613811aeae11300bf7a7b0fb5ec29/parquet/src/arrow/array_reader/struct_array.rs#L137-L170

The fix is simple, always have `ByteArrayDictionaryReader` advance the repetition and definition level buffers when `consume_next_batch` is called.

# Are these changes tested?

Yes, a new unit test was added `test_read_nullable_structs_with_binary_dict_as_first_child_column`, which before the changes introduced in this PR would replicate the issue.

# Are there any user-facing changes?
No

### CODE REVIEW

File: parquet/src/arrow/array_reader/byte_array_dictionary.rs [hunk 1]
```diff
@@ -175,9 +179,6 @@ where
         let buffer = self.record_reader.consume_record_data();
         let null_buffer = self.record_reader.consume_bitmap_buffer();
         let array = buffer.into_array(null_buffer, &self.data_type)?;
-
-        self.def_levels_buffer = self.record_reader.consume_def_levels();
-        self.rep_levels_buffer = self.record_reader.consume_rep_levels();
         self.record_reader.reset();
```
Comment (valkum) [inline parquet/src/arrow/array_reader/byte_array_dictionary.rs:182]: Thanks for the quick action on this.
During my debugging of the bug, I also came to the conclusion that advancing the rep and buffers would make sense, but I am lacking familiarity with these internals.

The docs for `reset` state that this should be called after consuming data. This isn't called in the shortcut case now. I am lacking a bit of context here, and the docs of GenericRecordReader aren't helping.

During my debug session, in the error case, `num_values()` and `num_records()` were both 0 already at that point. So resetting isn't doing much. 
But I am wondering if we can get to a state where `num_records > num_values`.

File: parquet/src/arrow/arrow_reader/mod.rs [hunk 2]
```diff
@@ -2359,6 +2360,63 @@ mod tests {
         assert_eq!(&batch, &read[0])
     }
 
+    #[test]
+    fn test_read_nullable_structs_with_binary_dict_as_first_child_column() {
```
Comment (valkum) [inline parquet/src/arrow/arrow_reader/mod.rs:2364]: I verified that this test fails without the fix in `parquet/src/arrow/array_reader/byte_array_dictionary.rs`

File: parquet/src/arrow/array_reader/byte_array_dictionary.rs (hunk 1 above)
Comment (etseidl) [reply parquet/src/arrow/array_reader/byte_array_dictionary.rs:182]: Perhaps `reset` could also be called before the early exit.

**Comment by valkum** [comment]
Just tested this PR with a larger file that caused this error. Works with this fix 👍

**Comment by alamb** [comment]
I'll plan to merge this PR in the next day or two unless anyone else would like a chance to review

File: parquet/src/arrow/array_reader/byte_array_dictionary.rs [hunk 3]
```diff
@@ -165,6 +165,10 @@ where
     }
 
     fn consume_batch(&mut self) -> Result<ArrayRef> {
+        // advance the def & rep level buffers
+        self.def_levels_buffer = self.record_reader.consume_def_levels();
+        self.rep_levels_buffer = self.record_reader.consume_rep_levels();
```
Comment (etseidl) [inline parquet/src/arrow/array_reader/byte_array_dictionary.rs:170]: I'm still trying to understand the issue and the fix. Is the following reasoning correct?

When struct array calls `consume_batch` on its children, the level buffers are set to the levels for the current batch. A subsequent call to `consume_batch` sees that num values is 0 and returns an empty array...but the level buffers still contain the levels from the already consumed batch. So this fix here is to ensure that on a subsequent call, the level buffers will be set to the empty ones from the `consume_xxx_levels` calls?

Comment (albertlockett) [reply parquet/src/arrow/array_reader/byte_array_dictionary.rs:170]: Hey @etseidl exactly, that is the correct reasoning

**Comment by etseidl** [comment]
Thanks @albertlockett @valkum @alamb!
