### PR TITLE
fix: entries field is non-nullable

### LINKED ISSUE #4807: MapArray::new_from_strings creates nullable entries field
**Describe the bug**

This line creates a nullable entries field:

https://github.com/apache/arrow-rs/blob/878217b9e330b4f1ed13e798a214ea11fbeb2bbb/arrow-array/src/array/map_array.rs#L330-L334

The Arrow spec dictates this should not be nullable:

https://github.com/apache/arrow/blob/c4b01c60fba85bbfc3a1b1510e179153c0f79515/format/Schema.fbs#L124

**To Reproduce**

**Expected behavior**

Creates a compliant map array.

**Additional context**

### PR DESCRIPTION
**Pull request by wjones127**
# Which issue does this PR close?

Closes #4807.

# Rationale for this change
 
The "entries" field shouldn't be nullable:

https://github.com/apache/arrow/blob/c4b01c60fba85bbfc3a1b1510e179153c0f79515/format/Schema.fbs#L124

Elsewhere, we have this as false already:

https://github.com/apache/arrow-rs/blob/master/arrow-schema/src/field.rs#L230

The inconsistency on this causes schema mismatch issues, such as those documented in:

https://github.com/delta-io/delta-rs/issues/1619

# What changes are included in this PR?

Changes all functions that construct the `"entries"` field to be non-nullable.

# Are there any user-facing changes?

Yes, this will change the type output by the `MapType::new_from_strings()` and `canonicalize_schema()` functions.

### CODE REVIEW

File: arrow-ipc/src/reader.rs [hunk 1]
```diff
@@ -1487,7 +1487,7 @@ mod tests {
         let keys_field = Arc::new(Field::new_dict(
             "keys",
             DataType::Dictionary(Box::new(DataType::Int8), Box::new(DataType::Utf8)),
-            true,
+            true, // It is technically not legal for this field to be null.
```
Comment (viirya) [inline arrow-ipc/src/reader.rs:1490]: This cannot be false?

**Review by viirya — APPROVED** [review]
Looks correct as this follows the spec.

File: arrow-ipc/src/reader.rs (hunk 1 above)
Comment (wjones127) [reply arrow-ipc/src/reader.rs:1490]: The test itself has null values in the test case. Perhaps I should modify the test case?

Comment (viirya) [reply arrow-ipc/src/reader.rs:1490]: Oh, I got what you mean. Okay to keep it as is.
