### PR TITLE
fix: issue introduced in #6833 -  less than equal check for scale in decimal conversion

### LINKED ISSUE #7069: Decimal cast to smaller precision gives invalid (off-by-one) result in some cases
**Describe the bug**

See practical examples in https://github.com/apache/datafusion/issues/14450.
Somehow a regression caused by https://github.com/apache/arrow-rs/issues/6833.

**To Reproduce**

Adding this into `arrow-cast/src/cast/mod.rs`:
```
    #[test]
    fn test_decimal_to_decimal() {
        let array = vec![Some(520)];
        let array = create_decimal_array(array, 4, 2).unwrap();
        let input_type = DataType::Decimal128(4, 2);
        let output_type = DataType::Decimal128(3, 2);
        assert!(can_cast_types(&input_type, &output_type));

        let options = CastOptions {
            safe: false,
            ..Default::default()
        };
        let result = cast_with_options(&array, &output_type, &options);
        assert_eq!(result.unwrap().as_primitive::<Decimal128Type>().value(0), 520);
    }
```

passes on 84dba34e6754b34baf19bd694506278cdc176a2e, but fails on https://github.com/apache/arrow-rs/commit/eb7ab83aab6b54897b00da1eb739c863d61445a2 with 
```
assertion `left == right` failed
  left: 521
 right: 520
```

Somehow something in the code adds an extra `1` to the value?

**Expected behavior**

Test passes

**Additional context**

Fyi @himadripal @andygrove @findepi @viirya @tustvold as you were involved in that earlier change. I tried to look at it but don't understand how it'd go wrong myself, maybe you know?

### PR DESCRIPTION
**Pull request by himadripal**
# Which issue does this PR close?

- Follow on to #6833
- Closes #7069

Closes #.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-cast/src/cast/mod.rs [hunk 1]
```diff
@@ -9980,7 +9980,26 @@ mod tests {
         };
         let result = cast_with_options(&array, &output_type, &options);
         assert_eq!(result.unwrap_err().to_string(),
-                   "Invalid argument error: 123456790 is too large to store in a Decimal128 of precision 6. Max is 999999");
+                   "Invalid argument error: 123456789 is too large to store in a Decimal128 of precision 6. Max is 999999");
+    }
+
+    #[test]
+    fn test_decimal_to_decimal() {
```
Comment (Blizzara) [inline arrow-cast/src/cast/mod.rs:9987]: might wanna give this a better name than what I came up with :D 

```suggestion
    fn test_decimal_to_decimal_same_scale() {
```
maybe?

**Comment by Blizzara** [comment]
LGTM, thanks!

**Comment by himadripal** [comment]
@andygrove

**Review by kazuyukitanimura — APPROVED** [review]
LGTM

File: arrow-cast/src/cast/decimal.rs [hunk 2]
```diff
@@ -167,7 +167,7 @@ where
     let array: PrimitiveArray<T> =
         if input_scale == output_scale && input_precision <= output_precision {
             array.clone()
-        } else if input_scale < output_scale {
+        } else if input_scale <= output_scale {
             // the scale doesn't change, but precision may change and cause overflow
             convert_to_bigger_or_equal_scale_decimal::<T, T>(
```
Comment (viirya) [inline arrow-cast/src/cast/decimal.rs:172]: As the call is to `convert_to_bigger_or_equal_scale_decimal`, looks like the condition was not correct before. Btw, the above comment is "the scale doesn't change...", however, the scale is actually changed, no?

Comment (himadripal) [reply arrow-cast/src/cast/decimal.rs:171]: Yes. Previous PR introduced this bug and this is to fixing it. Removed comment.

**Review by andygrove — APPROVED** [review]
Thanks @himadripal

**Comment by alamb** [comment]
Thank you @himadripal  @Blizzara @andygrove and @viirya

**Comment by findepi** [comment]
thanks for fixing this!

additional test case would be nice. casting from value 0 of decimal(3,0) type to decimal(2,0) type used to produce 1 before this fix. it sounds like a test case that should be in the code base (will add)

@himadripal would you want to backport this fix to the `53.0.0_maintenance` branch? latest 53.4.0 is affected by this bug

(assuming we would want to release 53.5.0 release. for a correctness bug like this i think we should, but not my call)

**Comment by findepi** [comment]
> additional test case would be nice. casting from value 0 of decimal(3,0) type to decimal(2,0) type used to produce 1 before this fix. it sounds like a test case that should be in the code base (will add)

-> https://github.com/apache/arrow-rs/pull/7078

**Comment by Blizzara** [comment]
@alamb et al, would it be possible to get a release with this fix in? Given it's a very clear correctness issue and regression, I'd feel that should warrant a fix release, but I'm not sure of the process or customs here..

**Comment by alamb** [comment]
> @alamb et al, would it be possible to get a release with this fix in? Given it's a very clear correctness issue and regression, I'd feel that should warrant a fix release, but I'm not sure of the process or customs here..

@Blizzara  yes I think we can make a release with the fix given that the issue was a regression -- let's move the conversation to https://github.com/apache/arrow-rs/issues/7083#issuecomment-2647769248
