### PR TITLE
Return null for overflow when casting string to integer under safe option enabled

### LINKED ISSUE #5397: Cast kernel doesn't return null for string to integral cases when overflowing under safe option enabled
**Describe the bug**

We found that cast kernel doesn't return null for string to integral cases when overflowing: https://github.com/apache/arrow-datafusion-comet/issues/15

`lexical_core` parser doesn't actually do the overflow check.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #5397.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-cast/src/parse.rs [hunk 1]
```diff
@@ -438,7 +438,7 @@ macro_rules! parser_primitive {
     ($t:ty) => {
         impl Parser for $t {
             fn parse(string: &str) -> Option<Self::Native> {
-                lexical_core::parse::<Self::Native>(string.as_bytes()).ok()
+                string.parse::<Self::Native>().ok()
```
Comment (viirya) [inline arrow-cast/src/parse.rs:441]: Only touched integer parser.

Comment (viirya) [reply arrow-cast/src/parse.rs:441]: Not sure if floating parser also has same issue.

Comment (viirya) [reply arrow-cast/src/parse.rs:441]: We can wait for a fix at the upstream crate. But the ticket is open for more than 6 months, and no progress so far. I think we may need to fix here directly.

**Review by Jefffrey — APPROVED** [review]
This makes sense in terms of correctness

Looks like this was added by https://github.com/apache/arrow-rs/pull/4050 which boasted a non-trivial speedup, so I guess this correctness fix will cause a performance regression :thinking: 

I wouldn't mind trying to take a look at the core issue in `lexical_core` but I can't promise anything :sweat_smile:

**Comment by viirya** [comment]
Hmm, polars uses `atoi_simd::parse`, maybe it is a good choice for both correctness and performance.

File: arrow-cast/Cargo.toml [hunk 2]
```diff
@@ -49,6 +49,7 @@ chrono = { workspace = true }
 half = { version = "2.1", default-features = false }
 num = { version = "0.4", default-features = false, features = ["std"] }
 lexical-core = { version = "^0.8", default-features = false, features = ["write-integers", "write-floats", "parse-integers", "parse-floats"] }
+atoi_simd = "0.15.6"
```
Comment (tustvold) [inline arrow-cast/Cargo.toml:52]: I'm a little concerned that this crate does not seem to have a very large community around it.

How does it compare to atoi?

Comment (tustvold) [reply arrow-cast/Cargo.toml:52]: > Community size seems not a big concern to me

Given the motivating factor for switching is a bug not getting attention, I am concerned. I'd be willing to sacrifice performance, for a better long-term maintenance story.

**Comment by viirya** [comment]
Hmm, that’s good point. Although I also think maintenance is not highly
related to community size?

Anyway, I will try atoi once I return to my laptop later.

**Comment by viirya** [comment]
`atoi` encounters more regression as expected, although looks like it is not as worse as `str.parse`:
 
```
4096 u64(0) - 128       time:   [202.56 µs 203.03 µs 203.43 µs]                                                    
                        change: [+15.998% +16.532% +17.063%] (p = 0.00 < 0.05)                                     
                        Performance has regressed.
                                                                                                                   
4096 u64(0) - 1024      time:   [181.58 µs 181.95 µs 182.37 µs]                                                    
                        change: [+16.615% +17.517% +18.295%] (p = 0.00 < 0.05)
                        Performance has regressed.                                                                 
Found 9 outliers among 100 measurements (9.00%)       
  5 (5.00%) high mild                            
  4 (4.00%) high severe  
                                                         
4096 u64(0) - 4096      time:   [197.34 µs 198.98 µs 201.23 µs]                                                    
                        change: [+25.579% +28.243% +31.146%] (p = 0.00 < 0.05)                                     
                        Performance has regressed.                                                                 
Found 21 outliers among 100 measurements (21.00%)                                                                  
  4 (4.00%) low severe                                
  2 (2.00%) low mild                           
  3 (3.00%) high mild
  12 (12.00%) high severe                                
                                                                                                                   
4096 i64_small(0) - 128 time:   [120.70 µs 121.20 µs 121.76 µs]               
                        change: [+3.6602% +4.1249% +4.5580%] (p = 0.00 < 0.05)                                     
                        Performance has regressed.                                                                 
                                                         
4096 i64_small(0) - 1024                                 
                        time:   [103.90 µs 105.02 µs 106.38 µs]
                        change: [+9.7972% +12.351% +15.643%] (p = 0.00 < 0.05)
                        Performance has regressed.                                                                 
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe                                                                                            
```

File: arrow-cast/Cargo.toml [hunk 3]
```diff
@@ -49,6 +49,7 @@ chrono = { workspace = true }
 half = { version = "2.1", default-features = false }
 num = { version = "0.4", default-features = false, features = ["std"] }
 lexical-core = { version = "^0.8", default-features = false, features = ["write-integers", "write-floats", "parse-integers", "parse-floats"] }
+atoi = "2.0.0"
```
Comment (viirya) [inline arrow-cast/Cargo.toml:52]: Hmm, atoi seems not working as expected. For an invalid string like `9.1`, it will simply parse `9` and ignore string after it.

**Comment by viirya** [comment]
Due to `atoi` not work as expected, and the concern around `atoi_simd`, I changed it back to `str.parse`.

**Comment by tustvold** [comment]
By default `atoi` allows for trailing content, the following ensures there is none.

```
macro_rules! parser_primitive {
    ($t:ty) => {
        impl Parser for $t {
            fn parse(string: &str) -> Option<Self::Native> {
                match atoi::FromRadix10SignedChecked::from_radix_10_signed_checked(string.as_bytes()) {
                    (Some(n), x) if x == string.len() => Some(n),
                    _ => None,
                }
            }
        }
    };
}
```

**Comment by viirya** [comment]
Thank you @tustvold @Jefffrey
