### PR TITLE
Use FixedSizeListArray::new in FixedSizeListBuilder

### LINKED ISSUE #5614: FixedSizeListArray::try_new Errors on Entirely Null Array With Size 0
**Describe the bug**

**To Reproduce**

```
#[test]
fn empty_fixed_size_list() {
    let field = Arc::new(Field::new("item", DataType::Int32, true));
    let nulls = NullBuffer::new_null(2);
    let values = new_empty_array(&DataType::Int32);
    let list = FixedSizeListArray::new(field.clone(), 0, values, Some(nulls));
    assert_eq!(list.len(), 2);
}
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #5614

# Rationale for this change
 

Follow up to #5541 that avoids some code duplication

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-array/src/array/fixed_size_list_array.rs [hunk 1]
```diff
@@ -152,16 +152,22 @@ impl FixedSizeListArray {
...
 
-        let len = values.len() / s.max(1);
-        if let Some(n) = nulls.as_ref() {
-            if n.len() != len {
-                return Err(ArrowError::InvalidArgumentError(format!(
-                    "Incorrect length of null buffer for FixedSizeListArray, expected {} got {}",
-                    len,
-                    n.len(),
-                )));
+        let len = match s {
```
Comment (tustvold) [inline arrow-array/src/array/fixed_size_list_array.rs:155]: This is the fix for #5614

File: arrow-array/src/array/fixed_size_list_array.rs [hunk 2]
```diff
@@ -662,7 +662,7 @@ mod tests {
         );
 
         let list = FixedSizeListArray::new(field.clone(), 0, values.clone(), None);
-        assert_eq!(list.len(), 6);
+        assert_eq!(list.len(), 0);
```
Comment (tustvold) [inline arrow-array/src/array/fixed_size_list_array.rs:665]: This is technically incorrect, in a FixedSizeListArray with size 0, the length of the values has no bearing on the length of the array

**Review by crepererum — APPROVED** [review]
