### PR TITLE
sort_primitive result is capped to the min of limit or values.len

### LINKED ISSUE #235: Sort with limit panics for the limit includes some but not all nulls, for large arrays
**Describe the bug**
We are getting the following panic:
`thread panicked at 'source slice length (139885) does not match destination slice length (239865)'` at `https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/sort.rs#L516`
when we are trying to sort a large array with a large limit that includes some but not all of the nulls. We are on commit `0d1697f619c1bff8f64b19df5d4ec66634eaecf9`.

**To Reproduce**
We have tried to reproduce this with smaller datasets but have been unable to. The smallest dataset we have confirmed this to happen on had 1mil rows.

**Expected behavior**
Sorting should work normally without panicing.

**Additional context**
We plan to work on this tomorrow (CET).

### PR DESCRIPTION
**Pull request by medwards**
Closes #235

# What changes are included in this PR?

The result slice in `sort_primitive` is the size of all the values being sorted even when a limit is provided. Change the size to be the maximum possible result (thus avoiding the panic in #235)

There are other slice size errors as well (such as when the number of nulls exceeds the limit) that are included.

# Are there any user-facing changes?

No

###  Notes

I've provided a reproducing test, but skipped other variants of limits /w nulls. Those should be easy so let me know if they're of interest. Additionally it is possible that `result` is intentionally over-large in which case I can try alternative fixes.

### CODE REVIEW

File: arrow/src/compute/kernels/sort.rs [hunk 1]
```diff
@@ -487,24 +487,27 @@ where
         len = limit.min(len);
     }
     if !descending {
-        sort_by(&mut valids, len - nulls_len, |a, b| cmp(a.1, b.1));
+        sort_by(&mut valids, len.saturating_sub(nulls_len), |a, b| {
```
Comment (alamb) [inline arrow/src/compute/kernels/sort.rs:490]: Silently ignoring  the case where  ` nulls_len`is greater than the total length being sorted seems wrong to me. 

It seems like the issue may be that `nulls_len` is not being updated correctly to take the limit into account. In other words if there is a limit the code should only look at the first `limit` rows to see if there are any nulls present. 

I figured it might be easier to try this out myself than to try and explain it; Here is my proposed fix (to your fix) for your consideration: https://github.com/medwards/arrow-rs/pull/1

**Review by alamb — COMMENTED** [review]
Nice find @medwards  -- thank you for the contribution. I am not sure about the use of `saturating_sub` but I have another  idea too (see https://github.com/medwards/arrow-rs/pull/1). 

👍 

FYI @sundy-li who I think contributed the original limit code in https://github.com/apache/arrow/pull/9602

File: arrow/src/compute/kernels/sort.rs (hunk 1 above)
Comment (medwards) [reply arrow/src/compute/kernels/sort.rs:490]: Looking at your diff I think one of us has misunderstood the expected behaviour. I think the result should be `ArrayData` truncated to the limit as if the full input was sorted, with some control over whether nulls are ordered before or after real values.

Comment (alamb) [reply arrow/src/compute/kernels/sort.rs:490]: 🤔  I think you are right.... Let me take a closer look

File: arrow/src/compute/kernels/sort.rs [hunk 2]
```diff
@@ -487,24 +487,27 @@ where
...
     // collect results directly into a buffer instead of a vec to avoid another aligned allocation
-    let mut result = MutableBuffer::new(values.len() * std::mem::size_of::<u32>());
+    let result_capacity = len * std::mem::size_of::<u32>();
+    let mut result = MutableBuffer::new(result_capacity);
     // sets len to capacity so we can access the whole buffer as a typed slice
-    result.resize(values.len() * std::mem::size_of::<u32>(), 0);
+    result.resize(result_capacity, 0);
     let result_slice: &mut [u32] = result.typed_data_mut();
 
-    debug_assert_eq!(result_slice.len(), nulls_len + valids_len);
```
Comment (jorgecarleitao) [inline arrow/src/compute/kernels/sort.rs:503]: There is still some invariant around here (may not exactly this one). Should we still try to assert it, for readability purposes?

File: arrow/src/compute/kernels/sort.rs [hunk 3]
```diff
@@ -1556,6 +1559,28 @@ mod tests {
             Some(3),
             vec![Some(1.0), Some(2.0), Some(3.0)],
         );
+
+        // limit that includes some extra nulls
+        test_sort_primitive_arrays::<Float64Type>(
```
Comment (jorgecarleitao) [inline arrow/src/compute/kernels/sort.rs:1564]: I would try to test the 4 branches:

* `(len < null.count(), null_first)`
* `(len < null.count(), null_last)`
* `(len > null.count(), null_first)`
* `(len > null.count(), null_last)`

just to make sure we cover all of them correctly.

**Review by jorgecarleitao — COMMENTED** [review]
Hi, @medwards , thanks a lot for this PR! It looks great to me 💯 

I left two comments that I think we may aim to, but please do challenge them if you disagree :)

**Comment by alamb** [comment]
BTW we are working on the `Dev PR / Process` failing check in #242

File: arrow/src/compute/kernels/sort.rs (hunk 3 above)
Comment (medwards) [reply arrow/src/compute/kernels/sort.rs:1564]: Added
```
(len < null.count(), null_last)
(len > null.count(), null_first)
```

I believe the other new tests cover the remaining cases you mentioned.

File: arrow/src/compute/kernels/sort.rs (hunk 2 above)
Comment (medwards) [reply arrow/src/compute/kernels/sort.rs:503]: I'm having difficulty imagining an alternative here, what did you have in mind?

`result_slice.len()` can now equal two values potentially: `values.len()` or `limit`. If it is the former then the old debug assert applies, but if it is the latter, it does not apply.

Alternatively we can make the size of `result_slice` always equal `values.len()`, this requires some changing some ranges further down (have to more carefully define start/end indices) and will result in an unnecessarily large result. I don't know if that's a big deal, I might have prematurely optimized by limiting the size of `result`.

Comment (jorgecarleitao) [reply arrow/src/compute/kernels/sort.rs:503]: You are right, sorry for the confusion.

**Review by jorgecarleitao — APPROVED** [review]
This looks great! Thanks a lot for solving this and for your contribution 👍

**Comment by alamb** [comment]
Thanks again @medwards !
