### PR TITLE
Fix CI with new valid certificates and add script for future usage

### LINKED ISSUE #6568: Arrow flight CI test failing on `master`
**Describe the bug**

Arrow flight CI test failing on master 

Example: 
https://github.com/apache/arrow-rs/actions/runs/11354119801/job/31580643040

```

running 3 tests
test tests::test_execute_update ... FAILED
test tests::test_select ... FAILED
test tests::test_auth ... FAILED

failures:

---- tests::test_execute_update stdout ----
testing uds client
Client finished!
=======
testing http client
Client finished!
=======
testing https client
thread 'tests::test_execute_update' panicked at arrow-flight/examples/flight_sql_server.rs:834:65:
called `Result::unwrap()` on an `Err` value: IpcError("Can't handshake status: Unknown, message: \"transport error\", details: [], metadata: MetadataMap { headers: {} }")
stack backtrace:
```

**To Reproduce**
RunC CI

**Expected behavior**
Should pass

**Additional context**

### PR DESCRIPTION
**Pull request by itsjunetime**
# Which issue does this PR close?

Closes #6568 

# Rationale for this change
 
CI needs to get going again and we need new certificates to do that. Also a script is useful for those who run into this in the future.

# What changes are included in this PR?

This includes newly generates certs and keys for the arrow-flight CI test as well as a script to regenerate these certificates and keys in the future

# Are there any user-facing changes?

No

### CODE REVIEW

**Review by tustvold — APPROVED** [review]

**Comment by alamb** [comment]
Thank you @itsjunetime  🙏

File: arrow-flight/examples/data/gen_certs.sh [hunk 1]
```diff
@@ -0,0 +1,30 @@
+#!/bin/sh
+
+# source: https://users.rust-lang.org/t/use-tokio-tungstenite-with-rustls-instead-of-native-tls-for-secure-websockets/90130
```
Comment (alamb) [inline arrow-flight/examples/data/gen_certs.sh:3]: 💯
