### PR TITLE
Infer 2020-03-19 00:00:00 as timestamp not Date64 in CSV (#3744)

### LINKED ISSUE #3744: CSV reader infers Date64 type for fields like "2020-03-19 00:00:00" that it can't parse to Date64
# Describe the bug

Starting with version 0.6.1 of [csv2parquet](https://github.com/domoritz/csv2parquet) (which upgraded its arrow-rs dependency from 24.0 to 30.0.1), input CSV files that were converting just fine are now failing with errors like this one:

```
Error: External(ParseError("Error while parsing value 2020-03-19 00:00:00 for column 4 at line 2"))
```

The csv2parquet tool is a very thin wrapper around arrow-rs that basically

1. Calls `arrow::csv::reader::infer_file_schema` to infer a schema for the input file;
2. Builds an `arrow::csv::Reader` from that schema and uses it to read the file;
3. Outputs a Parquet file.

The tool has a command line option that prints out the inferred schemas, and input values like that are being inferred into Date64:

```
    {
      "name": "Sample Date",
      "data_type": "Utf8",
      "nullable": false,
      "dict_id": 0,
      "dict_is_ordered": false,
      "metadata": {}
    }
```

And I've written a unit test case that demonstrates that 

1. Arrow-rs is inferring Date64 type for input values like "2020-03-19 00:00:00"
2. ...but attempting to parse them as Date64 fails

# To Reproduce

I wrote a couple of very simple test cases illustrating the problem:

* https://github.com/sacundim/arrow-rs/commit/e29fe220305cd9a83dbd713343058bec9c89fc5c

My `test_can_parse_inferred_date64` in `arrow-csv/src/reader/mod.rs` specifically shows how `infer_field_schema` returns `Date64` for the example string and yet when we feed it to `parse_item::<Date64Type>` we get `None`.   

# Expected behavior

I see that the various Timestamp types are able to parse strings like that correctly, so I don't understand whether the more correct behavior for this library would be to infer a Timestamp type for these strings instead of the Date64 type. It does seem clear to me that however that it should be possible to parse these strings as Date64.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3744

# Rationale for this change
 

As per https://lists.apache.org/thread/q036r1q3cw5ysn3zkpvljx3s9ho18419 Date64 should not be used for time data.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-csv/src/reader/mod.rs [hunk 1]
```diff
@@ -62,44 +61,68 @@ use crate::reader::records::{RecordDecoder, StringRecords};
...
-    match matches {
-        Some(ix) => MATCH_DATA_TYPE[ix].clone(),
-        None => {
-            let datetime_re = datetime_re.unwrap_or_else(|| DATETIME_RE.clone());
-            if datetime_re.is_match(string) {
-                DataType::Timestamp(TimeUnit::Nanosecond, None)
-            } else {
-                DataType::Utf8
+#[derive(Default, Copy, Clone)]
+struct InferredDataType {
```
Comment (tustvold) [inline arrow-csv/src/reader/mod.rs:80]: This logic should be significantly faster as an added bonus

**Review by viirya — APPROVED** [review]

File: arrow-csv/src/reader/mod.rs (hunk 1 above)
Comment (viirya) [reply arrow-csv/src/reader/mod.rs:80]: 👍
