### PR TITLE
Fix reading encrypted Parquet pages when using the page index

### LINKED ISSUE #7629: Cannot read encrypted Parquet file if page index reading is enabled
**Describe the bug**

Trying to read a Parquet file that uses modular encryption when page indices are enabled in the `ArrowReaderOptions` results in an error like:
```
ArrowError("Parquet argument error: External: bad data")
```

**To Reproduce**

This test reproduces the issue when added to `parquet/tests/encryption/encryption_async.rs`:
```rust
#[tokio::test]
async fn test_read_with_page_index() {
    let test_data = arrow::util::test_util::parquet_test_data();
    let path = format!("{test_data}/uniform_encryption.parquet.encrypted");
    let mut file = File::open(&path).await.unwrap();

    let key_code: &[u8] = "0123456789012345".as_bytes();
    let decryption_properties = FileDecryptionProperties::builder(key_code.to_vec())
        .build()
        .unwrap();

    let options = ArrowReaderOptions::new()
        .with_file_decryption_properties(decryption_properties)
        .with_page_index(true);

    let arrow_metadata = ArrowReaderMetadata::load_async(&mut file, options)
        .await
        .unwrap();

    let record_reader = ParquetRecordBatchStreamBuilder::new_with_metadata(
        file,
        arrow_metadata,
    )
    .build()
    .unwrap();
    let _record_batches = record_reader.try_collect::<Vec<_>>().await.unwrap();
}
```

**Expected behavior**
Data should be read successfully, and give the same results as when `with_page_index(false)` is used.

**Additional context**

This was encountered by @corwinjoy when integrating encryption support in DataFusion. Page indexes are enabled when data is queried with a filter predicate.

### PR DESCRIPTION
**Pull request by adamreeve**
# Which issue does this PR close?

Closes #7629.

I also noticed that skipping pages in encrypted files was broken so have fixed that too.

# What changes are included in this PR?

* Refactors `SerializedPageReader` to reduce the use of `#[cfg(...)]` inline. To work with the borrow checker, I created a new `SerializedPageReaderContext` type to hold the `CryptoContext`.
* Updates `SerializedPageReader::get_next_page` so that page headers and page data are decrypted when page indexes are used.
* Updates `SerializedPageReader::skip_next_page` to update the page index so that encryption AADs are calculated correctly.
* Adds new unit tests for reading with a page index and skipping pages in encrypted files.

# Are there any user-facing changes?

Only bug fixes.

### CODE REVIEW

**Review by rok — APPROVED** [review]
Nice that `#[cfg(feature = "encryption")]` macros are now enabling full functions. `page_ordinal` -> `page_index` is great for consistency too. I'm cringing a little bit that index and skipping was broken, sorry about that.
No comments for changes.

**Comment by etseidl** [comment]
Thanks @adamreeve! This looks nice as is. I left you a question in the form of a PR against your branch.

File: parquet/src/file/serialized_reader.rs [hunk 1]
```diff
@@ -651,6 +582,8 @@ impl<R: ChunkReader> SerializedPageReader<R> {
 
         let state = match page_locations {
             Some(locations) => {
+                // If the offset of the first page doesn't match the start of the column chunk
+                // then the preceding space must contain a dictionary page.
```
Comment (etseidl) [inline parquet/src/file/serialized_reader.rs:586]: ❤️

**Review by etseidl — APPROVED** [review]
Looks good, thanks @adamreeve!

**Comment by adamreeve** [comment]
Would you like to review this too @alamb or are you happy for me to merge?

**Comment by alamb** [comment]
> Would you like to review this too @alamb or are you happy for me to merge?

Unless you have something specific you would like me to review, I am very happy to have you merge it -- I think @etseidl 's review is more than adequate. 

Thank you for checking. 

BTW in this repo we just hit the green button on the github UI (no extra merge scripts, etc)

**Comment by adamreeve** [comment]
> Unless you have something specific you would like me to review, I am very happy to have you merge it -- I think @etseidl 's review is more than adequate.

OK great, thanks. I didn't have anything specific in mind but just wasn't sure about the process and how widely my Arrow committer privileges should be used :)
