### PR TITLE
Fix comparison of dictionaries with different values arrays (#332)

### LINKED ISSUE #332: Dictionary Comparison Uses Wrong Values Array
compare_dict_string always uses the values array of the left operand. This is incorrect.

```
fn compare_dict_string<'a, T>(left: &'a Array, right: &'a Array) -> DynComparator<'a>
where
    T: ArrowDictionaryKeyType,
{
    let left = left.as_any().downcast_ref::<DictionaryArray<T>>().unwrap();
    let right = right.as_any().downcast_ref::<DictionaryArray<T>>().unwrap();
    let left_keys = left.keys_array();
    let right_keys = right.keys_array();

    let left_values = StringArray::from(left.values().data().clone());
    let right_values = StringArray::from(left.values().data().clone());

    Box::new(move |i: usize, j: usize| {
        let key_left = left_keys.value(i).to_usize().unwrap();
        let key_right = right_keys.value(j).to_usize().unwrap();
        let left = left_values.value(key_left);
        let right = right_values.value(key_right);
        left.cmp(&right)
    })
}
```

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #332.

 # Rationale for this change

Currently when comparing dictionaries it will use the values array from the left operand with the keys of the right operand. Not only could this lead to invalid indexes, but it will commonly lead to incorrect results

# Are there any user-facing changes?

Comparison should now behave as the user would expect

### CODE REVIEW

File: arrow/src/array/ord.rs [hunk 1]
```diff
@@ -94,7 +94,7 @@ where
     let right_keys = right.keys_array();
 
     let left_values = StringArray::from(left.values().data().clone());
-    let right_values = StringArray::from(left.values().data().clone());
+    let right_values = StringArray::from(right.values().data().clone());
```
Comment (tustvold) [inline arrow/src/array/ord.rs:97]: Here's the copypasta

Comment (alamb) [reply arrow/src/array/ord.rs:97]: image

🤦

**Review by alamb — APPROVED** [review]
Thank you @tustvold  -- FYI @jorgecarleitao  / @nevi-me
