### PR TITLE
Fix take_bytes Null and Overflow Handling (#4576)

### LINKED ISSUE #4576: Panic `assertion failed: idx < self.len` when casting DictionaryArrays with nulls
**Describe the bug**
When casting Dictionary --> StringArray the `cast` kernel panics with 

```
thread 'main' panicked at 'assertion failed: idx < self.len', /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-buffer-44.0.0/src/buffer/boolean.rs:133:9
```

**To Reproduce**
Run this program:

```toml
[package]
name = "rust_arrow_playground"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = {version = "44.0.0", default-features = false }
```

```rust
use std::{sync::Arc};

use arrow::{array::{StringArray, DictionaryArray, Int32Array, Array}, datatypes::{Int32Type, DataType}, buffer::{NullBuffer, BooleanBuffer}};




fn main() {
    let expected = vec![Some("a"), Some("a"), None, Some("c")];

    // Note that values must contain NULL to trigger this
    let values = StringArray::from(vec![Some("a"), Some("b"), Some("c"), None]);

    // third element is out of bounds in the values, but is also nulls so it should not cause issues
    let keys = Int32Array::from(vec![0, 0, 1000, 2]);
    let keys = set_null(keys, 2);

    let array = DictionaryArray::<Int32Type>::try_new(keys, Arc::new(values)).unwrap();

    let expected_array: DictionaryArray::<Int32Type> = expected.clone().into_iter().collect();
    assert_eq!(&array, &expected_array);

    // expand out to strings
    let new_array = arrow::compute::cast(&array, &DataType::Utf8).unwrap();
    let expected_array: StringArray = expected.clone().into_iter().collect();

    assert_eq!(new_array.as_ref(), &expected_array as &dyn Array);

    println!("Done!")
}


/// Sets the specific index to null and everything else non-null
fn set_null(keys: Int32Array, index: usize) -> Int32Array {
    let len = keys.len();

    let nulls: Vec<bool> = (0..len).map(|i| i != index).collect();
    let nulls = BooleanBuffer::from(nulls);

    let (_data_type, buffer, _old_nulls) = keys.into_parts();
    Int32Array::new(buffer, Some(NullBuffer::from(nulls)))

}
```

This results in 
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.81s
     Running `/Users/alamb/Software/target-df/debug/rust_arrow_playground`
thread 'main' panicked at 'assertion failed: idx < self.len', /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-buffer-44.0.0/src/buffer/boolean.rs:133:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
   3: arrow_buffer::buffer::boolean::BooleanBuffer::value
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-buffer-44.0.0/src/buffer/boolean.rs:133:9
   4: arrow_buffer::buffer::null::NullBuffer::is_valid
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-buffer-44.0.0/src/buffer/null.rs:145:9
   5: arrow_buffer::buffer::null::NullBuffer::is_null
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-buffer-44.0.0/src/buffer/null.rs:151:10
   6: arrow_array::array::Array::is_null::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-44.0.0/src/array/mod.rs:193:30
   7: core::option::Option<T>::map
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1075:29
   8: arrow_array::array::Array::is_null
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-44.0.0/src/array/mod.rs:193:9
   9: arrow_array::array::Array::is_valid
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-44.0.0/src/array/mod.rs:210:10
  10: arrow_select::take::take_bytes
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-select-44.0.0/src/take.rs:404:16
  11: arrow_select::take::take_impl
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-select-44.0.0/src/take.rs:126:25
  12: arrow_select::take::take
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-select-44.0.0/src/take.rs:81:5
  13: arrow_cast::cast::unpack_dictionary
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-cast-44.0.0/src/cast.rs:3095:13
  14: arrow_cast::cast::dictionary_cast
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-cast-44.0.0/src/cast.rs:3074:14
  15: arrow_cast::cast::cast_with_options
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-cast-44.0.0/src/cast.rs:779:22
  16: arrow_cast::cast::cast
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-cast-44.0.0/src/cast.rs:296:5
  17: rust_arrow_playground::main
             at ./src/main.rs:24:21
  18: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Expected behavior**
The program should not panic and should print `Done`

**Additional context**
We found this error using internal data

@tustvold says he thinks the condition is backwards

```

for (i, offset) in offsets.iter_mut().skip(1).enumerate() {
            let index = indices.value(i).to_usize().ok_or_else(|| {
                ArrowError::ComputeError("Cast to usize failed".to_string())
            })?;

            if array.is_valid(index) && indices.is_valid(i) {
```

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4576

# Rationale for this change
 

This fixes the overflow and null checking behaviour of take_bytes. This does regress the performance slightly, but I think this is acceptable given the prior logic was incorrect.

```
take str 512            time:   [3.8135 µs 3.8144 µs 3.8155 µs]
                        change: [+8.1351% +8.5262% +8.8652%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 10 outliers among 100 measurements (10.00%)
  2 (2.00%) low mild
  6 (6.00%) high mild
  2 (2.00%) high severe

take str 1024           time:   [6.6656 µs 6.6665 µs 6.6675 µs]
                        change: [+10.429% +10.776% +10.972%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 7 outliers among 100 measurements (7.00%)
  6 (6.00%) high mild
  1 (1.00%) high severe

take str null indices 512
                        time:   [3.2013 µs 3.2048 µs 3.2081 µs]
                        change: [+6.4883% +6.7476% +7.0323%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

take str null indices 1024
                        time:   [6.3864 µs 6.4001 µs 6.4149 µs]
                        change: [+8.6045% +9.0105% +9.4405%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

take str null values 1024
                        time:   [6.9174 µs 6.9204 µs 6.9236 µs]
                        change: [-3.4004% -3.0300% -2.7115%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe

take str null values null indices 1024
                        time:   [5.5812 µs 5.5842 µs 5.5873 µs]
                        change: [+2.1866% +2.5807% +2.9030%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 9 outliers among 100 measurements (9.00%)
  6 (6.00%) high mild
  3 (3.00%) high severe
```

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-select/src/take.rs [hunk 1]
```diff
@@ -331,94 +331,68 @@ fn take_bytes<T: ByteArrayType, IndexType: ArrowPrimitiveType>(
...
-            let index = indices.value(i).to_usize().ok_or_else(|| {
-                ArrowError::ComputeError("Cast to usize failed".to_string())
-            })?;
-
+        offsets.extend(indices.values().iter().enumerate().map(|(i, index)| {
+            let index = index.as_usize();
             if array.is_valid(index) {
                 let s: &[u8] = array.value(index).as_ref();
-
-                length_so_far += T::Offset::from_usize(s.len()).unwrap();
```
Comment (tustvold) [inline arrow-select/src/take.rs:370]: This wasn't performing checked arithmetic and so could silently overflow

File: arrow-select/src/take.rs [hunk 2]
```diff
@@ -331,94 +331,68 @@ fn take_bytes<T: ByteArrayType, IndexType: ArrowPrimitiveType>(
...
                 values.extend_from_slice(s.as_ref());
```
Comment (tustvold) [inline arrow-select/src/take.rs:356]: We piggy back on the fact this already does checked arithmetic

File: arrow-select/src/take.rs [hunk 3]
```diff
@@ -1949,4 +1923,16 @@ mod tests {
             .collect::<Vec<_>>();
         assert_eq!(&values, &[Some(23), Some(4), None, None])
     }
+
+    #[test]
+    fn test_take_bytes_null_indices() {
+        let indices = Int32Array::new(
```
Comment (alamb) [inline arrow-select/src/take.rs:1929]:
```suggestion
        // Build indices with values that out of bounds, but NULL so they 
        // will not be checked
        let indices = Int32Array::new(
```

File: arrow-select/src/take.rs [hunk 4]
```diff
@@ -331,94 +331,68 @@ fn take_bytes<T: ByteArrayType, IndexType: ArrowPrimitiveType>(
...
-
-        for (i, offset) in offsets.iter_mut().skip(1).enumerate() {
-            let index = indices.value(i).to_usize().ok_or_else(|| {
-                ArrowError::ComputeError("Cast to usize failed".to_string())
-            })?;
-
-            if array.is_valid(index) && indices.is_valid(i) {
+        offsets.extend(indices.values().iter().enumerate().map(|(i, index)| {
+            let index = index.as_usize();
+            if indices.is_valid(i) && array.is_valid(index) {
```
Comment (alamb) [inline arrow-select/src/take.rs:379]: this is the actual fix for the bug, right? that `indices.is_valid` is checked prior to `array.is_valid`?

```suggestion
            // check index is valid before using index. The value in
            // NULL index slots may not be within bounds of array
            if indices.is_valid(i) && array.is_valid(index) {
```

File: arrow-select/src/take.rs [hunk 5]
```diff
@@ -331,94 +331,68 @@ fn take_bytes<T: ByteArrayType, IndexType: ArrowPrimitiveType>(
...
             }
-            *offset = length_so_far;
-        }
+            T::Offset::usize_as(values.len())
+        }));
         nulls = Some(null_buf.into());
     } else if array.null_count() == 0 {
-        for (i, offset) in offsets.iter_mut().skip(1).enumerate() {
+        offsets.extend(indices.values().iter().enumerate().map(|(i, index)| {
             if indices.is_valid(i) {
```
Comment (alamb) [inline arrow-select/src/take.rs:365]:
```suggestion
            // check index is valid before using index. The value in
            // NULL index slots may not be within bounds of array
            if indices.is_valid(i) {
```

**Review by alamb — APPROVED** [review]
Thank you @tustvold  -- I went through this PR carefully and it looks good to me logic wise. I defer to you and others for performance.

Maybe this is something @jhorstmann  or @viirya are interested in reviewing as well


I also verified that without the code changes in this PR the test fails like

```
---- take::tests::test_take_bytes_null_indices stdout ----
thread 'take::tests::test_take_bytes_null_indices' panicked at 'assertion failed: idx < self.len', /Users/alamb/Software/arrow-rs2/arrow-buffer/src/buffer/boolean.rs:133:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
   3: arrow_buffer::buffer::boolean::BooleanBuffer::value
             at /Users/alamb/Software/arrow-rs2/arrow-buffer/src/buffer/boolean.rs:133:9
   4: arrow_buffer::buffer::null::NullBuffer::is_valid
             at /Users/alamb/Software/arrow-rs2/arrow-buffer/src/buffer/null.rs:145:9
   5: arrow_buffer::buffer::null::NullBuffer::is_null
             at /Users/alamb/Software/arrow-rs2/arrow-buffer/src/buffer/null.rs:151:10
   6: arrow_array::array::Array::is_null::{{closure}}
             at /Users/alamb/Software/arrow-rs2/arrow-array/src/array/mod.rs:193:30
   7: core::option::Option<T>::map
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1075:29
   8: arrow_array::array::Array::is_null
             at /Users/alamb/Software/arrow-rs2/arrow-array/src/array/mod.rs:193:9
   9: arrow_array::array::Array::is_valid
             at /Users/alamb/Software/arrow-rs2/arrow-array/src/array/mod.rs:210:10
  10: arrow_select::take::take_bytes
             at ./src/take.rs:404:16
  11: arrow_select::take::take_impl
             at ./src/take.rs:126:25
  12: arrow_select::take::take
             at ./src/take.rs:81:5
  13: arrow_select::take::tests::test_take_bytes_null_indices
             at ./src/take.rs:1960:17
  14: arrow_select::take::tests::test_take_bytes_null_indices::{{closure}}
             at ./src/take.rs:1954:39
  15: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
