### PR TITLE
parquet: fix panic in DeltaByteArrayDecoder on invalid prefix lengths

### LINKED ISSUE #9796: DeltaByteArrayDecoder panics on invalid prefix lengths
### Problem
`DeltaByteArrayDecoder::get` assumes decoded prefix lengths are always valid and directly slices:

    self.previous_value[0..prefix_len]

If the decoded `prefix_len` is negative (after decoding) or larger than
`previous_value.len()`, this results in a slice bounds panic.

### Expected Behavior
The decoder should return `Err` on invalid input instead of panicking.

### Actual Behavior
Invalid prefix lengths can cause a panic such as:

    range end index X out of range for slice of length Y

### Reproduction
This can be reproduced by:
- encoding valid DELTA_BYTE_ARRAY data
- modifying the prefix-length stream (DELTA_BINARY_PACKED)
- decoding using `DeltaByteArrayDecoder::get`

This leads to a panic instead of returning an error.

### Notes
- There is currently no validation for:
  - negative prefix lengths
  - prefix lengths exceeding `previous_value.len()`
- Other decoders (e.g., DELTA_BINARY_PACKED) perform validation on decoded values,
  but this check is missing here.

### Impact
This can cause unexpected panics when reading invalid or unexpected encoded data,
instead of returning a controlled error.

### PR DESCRIPTION
**Pull request by pchintar**
# Which issue does this PR close?

- Closes #9796 .

# Rationale for this change

Currently, `DeltaByteArrayDecoder::get` assumes prefix lengths are always valid and directly slices `previous_value`. Invalid prefix lengths (negative or exceeding previous value length) can cause a panic instead of returning an error.

# What changes are included in this PR?

* Add validation for decoded prefix lengths:

  * reject negative values
  * reject values exceeding `previous_value.len()`
* Return `Err` instead of panicking on invalid input
* Add a regression test using corrupted encoded data

# Are these changes tested?

Yes.

* Added `test_delta_byte_array_invalid_prefix_len_returns_error`
* Test:

  * encodes valid data
  * corrupts prefix-length stream
  * verifies decoder returns `Err` (previously panicked)
* All the other existing tests pass

# Are there any user-facing changes?

No.

* No API changes
* Only improves error handling for invalid input

### CODE REVIEW

File: parquet/src/encodings/decoding.rs [hunk 1]
```diff
@@ -1134,7 +1134,22 @@ impl<T: DataType> Decoder<T> for DeltaByteArrayDecoder<T> {
...
                     // Extract current prefix length, can be 0
-                    let prefix_len = self.prefix_lengths[self.current_idx] as usize;
+                    let prefix_len_i32 = self.prefix_lengths[self.current_idx];
+                    if prefix_len_i32 < 0 {
+                        return Err(general_err!(
+                            "Invalid DELTA_BYTE_ARRAY prefix length {}",
+                            prefix_len_i32
+                        ));
+                    }
+                    let prefix_len = prefix_len_i32 as usize;
```
Comment (etseidl) [inline parquet/src/encodings/decoding.rs]:
```suggestion
                    let prefix_len = usize::try_from(self.prefix_lengths[self.current_idx])?;
```

A little less verbose. 😄 

I notice the added test doesn't cover this possibility.

**Review by etseidl — COMMENTED** [review]
Thanks @pchintar, this seems like a sensible fix. One nit and I think this needs a bit more test coverage.

File: parquet/src/encodings/decoding.rs (hunk 1 above)
Comment (pchintar) [reply parquet/src/encodings/decoding.rs]: Thanks  @etseidl for the suggestion — updated to use `usize::try_from(...)` with proper error mapping.
Also added an additional test `test_delta_byte_array_negative_prefix_len_returns_error` to cover the negative prefix length case so that path is now exercised as well.

**Comment by etseidl** [comment]
run benchmark parquet_round_trip
env:
  BENCH_FILTER:read.*delta_byte

**Comment by etseidl** [comment]
run benchmark parquet_round_trip
```yaml
env:
  BENCH_FILTER:read.*delta_byte
```

**Comment by etseidl** [comment]
run benchmark parquet_round_trip

```yaml
env:
  BENCH_FILTER: read.*delta_byte
```

**Review by etseidl — APPROVED** [review]
There doesn't appear to be any impact on read performance. Looks good to me. Thanks @pchintar

**Comment by pchintar** [comment]
Thank you @etseidl

**Comment by alamb** [comment]
Thanks @pchintar and @etseidl
