### PR TITLE
Read/write nested dictionary in ipc stream reader/writer

### LINKED ISSUE #1565: Read/write nested dictionary in ipc stream reader/writer
**Describe the bug**
This is encountered when I'm looking at `generate_nested_dictionary_case` in integration test failures. Similar to #1549 but this is both related to writer and reader. Currently the write doesn't produce nested dictionaries too, so the reader cannot read nested dictionaries.

**To Reproduce**
Put a test in the PR.

**Expected behavior**
Can write/read nested dictionary correctly.

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1565.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/ipc/reader.rs [hunk 1]
```diff
@@ -1439,4 +1440,42 @@ mod tests {
         let output_batch = roundtrip_ipc_stream(&input_batch);
         assert_eq!(input_batch, output_batch);
     }
+
+    #[test]
+    fn test_roundtrip_stream_nested_dict_dict() {
```
Comment (alamb) [inline arrow/src/ipc/reader.rs:1445]: I tried running this test without the code changes in this PR and it failed thusly. 👍 

```
---- ipc::reader::tests::test_roundtrip_stream_nested_dict_dict stdout ----
thread 'ipc::reader::tests::test_roundtrip_stream_nested_dict_dict' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("dictionary id not found in schema")', arrow/src/ipc/reader.rs:1331:32
```
when I removed the field code

 
and  like this when I removed the writer support
```
---- ipc::reader::tests::test_roundtrip_stream_nested_dict_dict stdout ----
thread 'ipc::reader::tests::test_roundtrip_stream_nested_dict_dict' panicked at 'called `Option::unwrap()` on a `None` value', arrow/src/ipc/reader.rs:176:64
```

File: arrow/src/ipc/writer.rs [hunk 2]
```diff
@@ -175,13 +186,37 @@ impl IpcDataGenerator {
                     )?;
                 }
             }
+            _ => (),
```
Comment (alamb) [inline arrow/src/ipc/writer.rs:189]: maybe this should return an error for unsupported nested types

**Review by alamb — APPROVED** [review]
Look good to me -- thank you @viirya

File: arrow/src/datatypes/field.rs [hunk 3]
```diff
@@ -116,14 +116,25 @@ impl Field {
...
+        match dt {
             DataType::Struct(fields) | DataType::Union(fields, _) => {
                 collected_fields.extend(fields.iter().flat_map(|f| f.fields()))
             }
             DataType::List(field)
             | DataType::LargeList(field)
             | DataType::FixedSizeList(field, _)
             | DataType::Map(field, _) => collected_fields.push(field),
+            DataType::Dictionary(_, value_field) => {
+                collected_fields.append(&mut self._fields(value_field.as_ref()))
```
[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/datatypes/field.rs:136]: Yea, this is key part here to get fields inside dictionary type.

File: arrow/src/ipc/writer.rs (hunk 2 above)
Comment (viirya) [reply arrow/src/ipc/writer.rs:189]: Hmm, I guess that it doesn't just returning an error, is because if no dictionaries exist inside the fields of these nested types, then the ipc writer still can work. To return an error for dictionaries existing inside unsupported nested types, we need to look into them as supported types, so it's basically almost near to implement them.

I may take some time continuing the work to add more supports (map, etc) here.
