### PR TITLE
Fix several bugs in parquet writer statistics generation, add `EnabledStatistics` to control level of statistics generated

### LINKED ISSUE #2015: `ColumnWriterImpl::write_batch_with_statistics` can write incorrect page statistics
**Describe the bug**

If calls to `write_batch_with_statistics` are mixed with calls to `write_batch` it can lead to invalid page statistics, as they will only be computed for the data passed to `write_batch`.

**To Reproduce**

Inspect code

**Expected behavior**

These methods should behave consistently

**Additional context**

### LINKED ISSUE #2016: `ColumnWriterImpl::write_batch_with_statistics` incorrect distinct count in statistics
**Describe the bug**

Calling write_batch_with_statistics twice with a non-zero distinct count will compute the sum of the distinct counts. In most cases this will be incorrect.

Similarly calling write_batch having called write_batch_with_statistics will not clear the distinct count.

**To Reproduce**

Inspect code

**Expected behavior**

We should only set distinct count when it is known

**Additional context**

#2015

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2015
Closes #2016 

# Rationale for this change
 
Fixes a number of bugs

# What changes are included in this PR?

Removes max_statistics_size as it isn't used, and changes statistics to be enabled based on an enumeration. This allows consistently only producing chunk level statistics, potentially precomputed, or not.

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/file/properties.rs [hunk 1]
```diff
@@ -394,23 +376,33 @@ impl WriterPropertiesBuilder {
...
     ) -> Self {
-        self.get_mut_props(col).set_max_statistics_size(value);
+        self.get_mut_props(col).set_statistics_enabled(value);
         self
     }
 }
 
+/// Controls the level of statistics to be computed by the writer
+#[derive(Debug, Clone, Copy, Eq, PartialEq)]
+pub enum EnabledStatistics {
```
Comment (tustvold) [inline parquet/src/file/properties.rs:391]: I'm not a massive fan of this, but it was the only way I could think of to preserve the existing behaviour whilst also fixing the related bugs

File: parquet/src/column/writer.rs [hunk 2]
```diff
@@ -302,61 +308,85 @@ impl<'a, T: DataType> ColumnWriterImpl<'a, T> {
...
+                        }
+                    }
+                }
+            };
         }
 
-        if let Some(distinct) = distinct_count {
-            self.column_distinct_count =
-                Some(self.column_distinct_count.unwrap_or(0) + distinct);
+        // We can only set the distinct count if there are no other writes
```
Comment (tustvold) [inline parquet/src/column/writer.rs:372]: This is the fix for #2016

File: parquet/src/column/writer.rs [hunk 3]
```diff
@@ -678,14 +708,15 @@ impl<'a, T: DataType> ColumnWriterImpl<'a, T> {
...
 
-        // always update column NULL count, no matter if page stats are used
         self.num_column_nulls += self.num_page_nulls;
 
-        let page_statistics = if calculate_page_stat {
-            self.update_column_min_max();
-            Some(self.make_page_statistics())
-        } else {
-            None
+        let has_min_max = self.min_page_value.is_some() && self.max_page_value.is_some();
```
Comment (tustvold) [inline parquet/src/column/writer.rs:713]: This logic is moved from flush_data_pages

File: parquet/src/arrow/schema.rs [hunk 4]
```diff
@@ -152,7 +152,10 @@ pub(crate) fn add_encoded_arrow_schema_to_metadata(
         value: Some(encoded),
     };
 
-    let mut meta = props.key_value_metadata.clone().unwrap_or_default();
+    let meta = props
```
Comment (alamb) [inline parquet/src/arrow/schema.rs:155]: Does this change have any effect (other than to make the code more readable)?

File: parquet/src/file/properties.rs (hunk 1 above)
Comment (alamb) [reply parquet/src/file/properties.rs:391]: I actually like this API -- as for some use cases page level statistics are likely to have a higher overhead in storage and writing than benefit (e.g. large string columns for small row groups)

File: parquet/src/column/writer.rs [hunk 5]
```diff
@@ -302,61 +308,52 @@ impl<'a, T: DataType> ColumnWriterImpl<'a, T> {
...
-        // Process pre-calculated statistics
-        match (min, max) {
-            (Some(min), Some(max)) => {
-                if self
-                    .min_column_value
-                    .as_ref()
-                    .map_or(true, |v| self.compare_greater(v, min))
-                {
-                    self.min_column_value = Some(min.clone());
+        if self.statistics_enabled == EnabledStatistics::Chunk {
```
Comment (alamb) [inline parquet/src/column/writer.rs:321]: I would personally find `match self.statistics_enabled` ... to be easier to validate that other variants of `EnabledStatistics::Chunk` did not apply.

Or perhaps a function `EnabledStatistics::compute_chunk_statistics()`.

Basically I am thinking about "what if someone adds a new variant" -- it would be nice if the compiler told them where to update

File: parquet/src/column/writer.rs [hunk 6]
```diff
@@ -302,61 +308,52 @@ impl<'a, T: DataType> ColumnWriterImpl<'a, T> {
...
+                    panic!("min/max should be both set or both None")
                 }
-            }
-            (None, Some(_)) | (Some(_), None) => {
-                panic!("min/max should be both set or both None")
-            }
-            (None, None) => {}
+                (None, None) => {
+                    for val in values {
+                        Self::update_min(&self.descr, val, &mut self.min_column_value);
```
Comment (alamb) [inline parquet/src/column/writer.rs:332]: Is this the fix for https://github.com/apache/arrow-rs/issues/2015?

File: parquet/src/column/writer.rs [hunk 7]
```diff
@@ -393,9 +389,11 @@ impl<'a, T: DataType> ColumnWriterImpl<'a, T> {
         self.write_batch_internal(values, def_levels, rep_levels, None, None, None, None)
     }
 
-    /// Writer may optionally provide pre-calculated statistics for this batch, in which case we do
-    /// not calculate page level statistics as this will defeat the purpose of speeding up the write
-    /// process with pre-calculated statistics.
+    /// Writer may optionally provide pre-calculated statistics for this batch
+    ///
+    /// Note: Unless disabled using by using [`WriterProperties`] to set
+    /// enabled statistics to [`EnabledStatistics::Chunk`], this will still compute
```
Comment (alamb) [inline parquet/src/column/writer.rs:395]: This comment almost reads the opposite of what I think the code is doing (using the passed in pre-calculated statistics or computing them if passed in)

File: parquet/src/column/writer.rs (hunk 5 above)
Comment (alamb) [reply parquet/src/column/writer.rs:321]: In fact, no that I re-read this, shouldn't this also be set if we are computing page level statistics?

File: parquet/src/file/properties.rs (hunk 1 above)
Comment (alamb) [reply parquet/src/file/properties.rs:391]: It would be good to clarify in here if `Page` also computes `Chunk` level statistics.

If `Page` does not also include `Chunk` that seems strange to me (as I would expect lower level stats to also have coarser grained statistics).

File: parquet/src/file/properties.rs [hunk 8]
```diff
@@ -463,15 +453,10 @@ impl ColumnProperties {
     }
 
     /// Sets whether or not statistics are enabled for this column.
-    fn set_statistics_enabled(&mut self, enabled: bool) {
+    fn set_statistics_enabled(&mut self, enabled: EnabledStatistics) {
         self.statistics_enabled = Some(enabled);
     }
 
-    /// Sets max size for statistics for this column.
```
Comment (alamb) [inline parquet/src/file/properties.rs:470]: I don't see any mention of `max_statistics_size` in this PR description or the linked tickets. 

I think it is a reasonable feature (to limit bloating parquet files). Is the issue that it was ignored? If so perhaps we can leave the API in with a `warn` or `deprecate` that it is ignored and file a ticket to properly support it?

File: parquet/src/column/writer.rs [hunk 9]
```diff
@@ -1029,59 +1025,58 @@ impl<'a, T: DataType> ColumnWriterImpl<'a, T> {
...
+    }
+
+    fn update_max(descr: &ColumnDescriptor, val: &T::T, max: &mut Option<T::T>) {
+        Self::update_stat(val, max, |cur| Self::compare_greater(descr, val, cur))
+    }
+
+    /// Perform a conditional update of `cur`, skipping any NaN values
+    ///
+    /// If `cur` is `None`, sets `cur` to `Some(val)`, otherwise calls `should_update` with
+    /// the value of `cur`, and updates `cur` to `Some(val)` if it returns `true`
```
Comment (alamb) [inline parquet/src/column/writer.rs:1052]: cc @crepererum as I think you added the initial `NaN` handling a while ago

File: parquet/src/column/writer.rs [hunk 10]
```diff
@@ -1754,6 +1753,56 @@ mod tests {
...
+        .unwrap();
+
+        let pages = reader.collect::<Result<Vec<_>>>().unwrap();
+        assert_eq!(pages.len(), 2);
+
+        assert_eq!(pages[0].page_type(), PageType::DICTIONARY_PAGE);
+        assert_eq!(pages[1].page_type(), PageType::DATA_PAGE);
+
+        let page_statistics = pages[1].statistics().unwrap();
+        assert_eq!(page_statistics.min_bytes(), 1_i32.to_le_bytes());
```
Comment (alamb) [inline parquet/src/column/writer.rs:1800]: 👍

**Review by alamb — APPROVED** [review]
I had some comments on the API design and deprecation, but the actual code looks good and like a significant improvement to me. 👍

File: parquet/src/column/writer.rs (hunk 9 above)
Comment (crepererum) [reply parquet/src/column/writer.rs:1052]: If I read this correctly the NaN handling here is to avoid "poisoning" which is OK.

IMHO the stats should include a flag if there were any NaN values, but this is far outside the scope of this PR since this would affect the parquet format as a whole.

File: parquet/src/file/properties.rs (hunk 8 above)
Comment (tustvold) [reply parquet/src/file/properties.rs:470]: I will back out this change

File: parquet/src/column/writer.rs (hunk 5 above)
Comment (tustvold) [reply parquet/src/column/writer.rs:321]: I'll add a comment explaining why we only care if it is exactly this variant, any other variants would need to be computed at a different level

File: parquet/src/file/properties.rs (hunk 1 above)
Comment (tustvold) [reply parquet/src/file/properties.rs:391]: Glad one of us likes it :laughing: 

FWIW at least in the case of the column index, parquet allows using truncated values in statistics
