### PR TITLE
Bugfix in parquet writing empty lists of structs

### LINKED ISSUE #703: Empty or null list of struct cannot be written to parquet
**Describe the bug**
When writing arrow batch with empty or null list struct, it fails with `General("Inconsistent length of definition and repetition levels: 0 != 1")`

**To Reproduce**
Write record batch which contain empty or null list of struct. Here's the PR with full repro behaviour https://github.com/apache/arrow-rs/pull/704

**Expected behavior**
The batch is successfully written

**Additional context**
WHat I could debug is that this line should fail https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/levels.rs#L646, because at some point the `array_mask` becomes empty slice which leads to the _Inconsistent length of definition and repetition levels_

I feel like this might be somehow connected https://github.com/apache/arrow-rs/issues/594.

### PR DESCRIPTION
**Pull request by helgikrs**
# Which issue does this PR close?

Closes #703 

# What changes are included in this PR?

Fix a bug in the definition level calculation for fields nested within a struct and a list. When a list is empty or null in parquet the nested field gets a null value. However, in arrow, the value is simply missing.  When serializing an immediate child of the list, the list offsets are used to calculate the correct definition level for its children, but it is not carried further to fields nested deeper (e.g., fields on a struct within a list).  This (somewhat hacky) fix treats a struct within a list as if it were a list.

# Are there any user-facing changes?

No.

### CODE REVIEW

File: parquet/src/arrow/levels.rs [hunk 1]
```diff
@@ -1675,4 +1682,95 @@ mod tests {
...
+
+        let schema = Arc::new(Schema::new(vec![list_field]));
+
+        let rb = RecordBatch::try_new(schema, vec![array]).unwrap();
+
+        let batch_level = LevelInfo::new(0, rb.num_rows());
+        let list_level =
+            &batch_level.calculate_array_levels(rb.column(0), rb.schema().field(0))[0];
+
+        let expected_level = LevelInfo {
```
Comment (alamb) [inline parquet/src/arrow/levels.rs:1763]: it would be great if someone else who knew this better than I could double check this

File: parquet/src/arrow/levels.rs [hunk 2]
```diff
@@ -1675,4 +1682,95 @@ mod tests {
...
+
+        // [{a: 2}]
+        let values = list_builder.values();
+        values
+            .field_builder::<Int32Builder>(0)
+            .unwrap()
+            .append_value(2)
+            .unwrap();
+        values.append(true).unwrap();
+        list_builder.append(true).unwrap();
```
Comment (alamb) [inline parquet/src/arrow/levels.rs:1751]: I double checked that the code matches the comments about what structure is intended to be created

**Review by alamb — APPROVED** [review]
I am not an expert in this area -- I would definitely appreciate a review from @nevi-me  (or @tustvold as I blieve he has been ~cursing~ studying )

However, even if this case has some other subtlety we missed, I think the added coverage in this PR means the overall code is better than without so I approve.

Thank you @helgikrs  -- very helpful to have someone else looking at this stuff. 🏆

**Comment by alamb** [comment]
cc @mosyp and @chadbrewbaker

File: parquet/src/arrow/levels.rs (hunk 1 above)
Comment (tustvold) [reply parquet/src/arrow/levels.rs:1763]: Can confirm, these numbers check out :+1:

**Comment by alamb** [comment]
Thanks @helgikrs !
