### PR TITLE
Fix RowConverter panic when encoding `DictionaryArray`s in `StructArray` / `ListArray`

### LINKED ISSUE #7165: `RowConverter::convert_rows` panics when decoding `List(Dictionary)`
**Describe the bug**
`RowConverter::convert_rows` panics when decoding rows of type `List(Dictionary(Int32, Int32))`.

**To Reproduce**
```rust
#[test]
fn test_list_of_primitive_dictionary() {
    let mut builder =
        ListBuilder::<PrimitiveDictionaryBuilder<Int32Type, Int32Type>>::default();
    builder.values().append(2).unwrap();
    builder.values().append(3).unwrap();
    builder.values().append(0).unwrap();
    builder.values().append_null();
    builder.values().append(5).unwrap();
    builder.values().append(3).unwrap();
    builder.values().append(-1).unwrap();
    builder.append(true);

    let a = Arc::new(builder.finish()) as ArrayRef;
    let data_type = a.data_type().clone();

    let field = SortField::new(data_type.clone());
    let converter = RowConverter::new(vec![field]).unwrap();
    let rows = converter.convert_columns(&[Arc::clone(&a)]).unwrap();

    let back = converter.convert_rows(&rows).unwrap();
    assert_eq!(back.len(), 1);
    back[0].to_data().validate_full().unwrap();
    assert_eq!(&back[0], &a);
}
```

```
thread 'tests::test_list_of_primitive_dictionary' panicked at arrow-array/src/array/list_array.rs:429:14:
Expected infallible creation of GenericListArray from ArrayDataRef failed: InvalidArgumentError("[Large]ListArray's child datatype Int32 does not correspond to the List's datatype Dictionary(Int32, Int32)")
```

**Expected behavior**
Not panicking

**Additional context**

### LINKED ISSUE #7169: `RowConverter::convert_rows` returns an invalid array if the original array contained a dictionary type
**Describe the bug**
`RowConverter::convert_rows` flattens all dictionary arrays, but the `data_type` of the returned array still contain `Dictionary`.

**To Reproduce**
```rust
#[test]
fn test_dictionary_in_struct() {
    let ty = DataType::Struct(
        vec![Field::new_dictionary(
            "foo",
            DataType::Int32,
            DataType::Int32,
            false,
        )]
        .into(),
    );
    let s = arrow_array::new_empty_array(&ty);

    let sort_fields = vec![SortField::new(s.data_type().clone())];
    let converter = RowConverter::new(sort_fields).unwrap();
    let r = converter.convert_columns(&[Arc::clone(&s)]).unwrap();

    let back = converter.convert_rows(&r).unwrap();
    let [s2] = back.try_into().unwrap();
    assert_eq!(&s2, &s);

    println!("s2 = {s2:?}, s2.ty = {}", s2.data_type());

    s2.to_data().validate_full().unwrap();
}
```

```
s2 = StructArray
-- validity: 
[
]
[
-- child 0: "foo" (Int32)
PrimitiveArray<Int32>
[
]
], s2.ty = Struct([Field { name: "foo", data_type: Dictionary(Int32, Int32), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }])
thread 'tests::test_dictionary_in_struct' panicked at arrow-row/src/lib.rs:1884:38:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Child type mismatch for Struct([Field { name: \"foo\", data_type: Dictionary(Int32, Int32), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }]). Expected Dictionary(Int32, Int32) but child data had Int32")
```

**Expected behavior**
- The decoded array passes validation
- One of the following is true:
    - The first child of `s2` is `DictionaryArray`, and the first subfield of `s2.data_type()` is `Dictionary(_, Int32)`.
    - The first child of `s2` is `Int32Array`, and the first subfield of `s2.data_type()` is `Int32`.

**Additional context**

### PR DESCRIPTION
**Pull request by ding-young**
# Which issue does this PR close?
- Closes #7165 
- Closes #7169

# Rationale for this change
Although `RowConverter` flattens data type on converting columns into rows, it builds array with original `SortField` which contains unflattened types when converting rows back into columns. Therefore, output array has inconsistent data type although it is actually flattened. 

# What changes are included in this PR?
When decoding columns, instead of using original `SortField`, it uses new field with updated data type of child `ArrayData`, which is flattened.  

I've also considered alternative approaches like recursively modify all the `fields` on `convert_rows` or `convert_raw`, but considering that we already visit each field recursively, I just corrected the field in `decode_column` for simplicity. 

I'd be happy to hear about the feedback on correctness of this pr and any other suggestions. 

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-row/src/lib.rs [hunk 1]
```diff
@@ -1863,6 +1887,64 @@ mod tests {
...
+        let ty = DataType::Struct(
+            vec![Field::new_dictionary(
+                "foo",
+                DataType::Int32,
+                DataType::Int32,
+                false,
+            )]
+            .into(),
+        );
+        let s = arrow_array::new_empty_array(&ty);
```
Comment (alamb) [inline arrow-row/src/lib.rs:2241]: Can you please also add a test that round trips an actual struct with dictionary through the converter? Testing with an empty array is also a good test, but I think we need to verify that the data is the same too

File: arrow-row/src/lib.rs [hunk 2]
```diff
@@ -1863,6 +1887,64 @@ mod tests {
...
+        let r = converter.convert_columns(&[Arc::clone(&s)]).unwrap();
+
+        let back = converter.convert_rows(&r).unwrap();
+        let [s2] = back.try_into().unwrap();
+
+        // RowConverter flattens Dictionary
+        // s.ty = Struct(foo Dictionary(Int32, Int32)), s2.ty = Struct(foo Int32)
+        assert_ne!(&s.data_type(), &s2.data_type());
+
+        s2.to_data().validate_full().unwrap();
```
Comment (alamb) [inline arrow-row/src/lib.rs:2253]: Can you also add an assert that verifies the arrays made it through without modification (e.g. `assert_eq!(s1, s2)`)?

File: arrow-row/src/lib.rs [hunk 3]
```diff
@@ -1863,6 +1887,64 @@ mod tests {
...
+        let mut builder =
+            ListBuilder::<PrimitiveDictionaryBuilder<Int32Type, Int32Type>>::default();
+        builder.values().append(2).unwrap();
+        builder.values().append(3).unwrap();
+        builder.values().append(0).unwrap();
+        builder.values().append_null();
+        builder.values().append(5).unwrap();
+        builder.values().append(3).unwrap();
+        builder.values().append(-1).unwrap();
+        builder.append(true);
```
Comment (alamb) [inline arrow-row/src/lib.rs:2269]: Can you please update the test to include:
1. A null (`builder.append(false)`)
2. a second row with values

File: arrow-row/src/lib.rs [hunk 4]
```diff
@@ -1863,6 +1887,64 @@ mod tests {
...
+        let converter = RowConverter::new(vec![field]).unwrap();
+        let rows = converter.convert_columns(&[Arc::clone(&a)]).unwrap();
+
+        let back = converter.convert_rows(&rows).unwrap();
+        assert_eq!(back.len(), 1);
+        let [a2] = back.try_into().unwrap();
+
+        // RowConverter flattens Dictionary
+        // a.ty: List(Dictionary(Int32, Int32)), a2.ty: List(Int32)
+        assert_ne!(&a.data_type(), &a2.data_type());
```
Comment (alamb) [inline arrow-row/src/lib.rs:2291]: this seems incorrect -- I would expect that I get the same kind and values of array back from the RowConverter as went int

**Review by alamb — COMMENTED** [review]
Thank you for the contribution @ding-young  

I am sorry I don't fully understand what is wrong and what this PR is proposing. 

> Although RowConverter flattens data type on converting columns into rows, it builds array with original SortField which contains unflattened types when converting rows back into columns. 

I believe the intention is to build arrays with the original `DataType`s.

Specifically, I expect the RowConverter to have the property that if you convert `Array`s to `Rows` and then those `Rows` back to `Array`s, the arrays are the same that went in

**Comment by alamb** [comment]
Marking as draft as I think this PR is no longer waiting on feedback and I am trying to make it easier to find PRs in need of review. Please mark it as ready for review when it is ready for another look

**Comment by LiaCastaneda** [comment]
👋 @ding-young what is the status of this PR? do you mind if I give it a shot? it is causing errors in `DataFusion` https://github.com/apache/datafusion/issues/17012

**Comment by ding-young** [comment]
Hi @LiaCastaneda :)

I just ran the reproducer test, and it passes without error on the fix-row-converter branch.
image

However, this PR takes the approach of correcting the data type, rather than preserving the original dictionary encoding. So https://github.com/apache/arrow-rs/pull/7627#discussion_r2143655781 the resulting type is flattened, like mentioned here https://github.com/apache/arrow-rs/issues/7169#issuecomment-2675211398.  

I can easily follow up on the minor review comments in a day, but currently I don’t have time to rewrite the decoding logic to preserve the original encoding like @alamb suggested.

What kind of solution were you thinking of? If your main goal is just to suppress the warning and run the reproducer query, then I can quickly finish up this PR and ping you again. But if you’re planning to work on a solution that preserves the original dictionary encoding, feel free to take it over!

Let me know what you think :)

**Comment by LiaCastaneda** [comment]
Guiding myself on @alamb 's comment, I understand the correct solution is to preserve Dict encoding so I was looking into following that approach.

**Comment by LiaCastaneda** [comment]
I'm sketching a solution for this, and I'm wondering if we want to keep the exact same encoding, one thing that I think we could do is manually build a Dictionary using a DictionaryBuilder or perform a cast using `arrow_cast::cast` which does [the same](https://github.com/apache/arrow-rs/blob/c25c5a74c1c70cee57558e81a66a2e44725a67a6/arrow-cast/src/cast/dictionary.rs#L323) under the hood. This would keep the DataType but i'm not sure it will have the exact same encoding as the original Dict Array. If we want to keep the exact same Dict encoding then we would probably need to keep the original `DictionaryArray` values somewhere before/during encoding the Array to rows.
 
 Update: I tried the cast approach here https://github.com/apache/arrow-rs/pull/8067/files and I believe the encoding would be the same, if not the test I included would not pass. I will try to open the PR later today or tomorrow

File: arrow-row/src/lib.rs (hunk 3 above)
Comment (ding-young) [reply arrow-row/src/lib.rs:2269]: Done.

**Comment by ding-young** [comment]
If https://github.com/apache/arrow-rs/pull/8067#issuecomment-3160907785 that's the case, would you @tustvold mind taking a look when you get a chance?

Plus, let me know if there’s anything else I can help with :) @LiaCastaneda .

**Comment by LiaCastaneda** [comment]
Thanks readressing the PR @ding-young 🙇‍♀️

**Comment by LiaCastaneda** [comment]
Thanks for readressing the PR @ding-young 🙇‍♀️

File: arrow-row/src/lib.rs (hunk 4 above)
Comment (gabotechs) [reply arrow-row/src/lib.rs:2291]: 🤔 I think technically they do are the same values, they just happen to be encoded differently (Dictionary encoded VS raw).

Probably this test should be asserting that the data remains the same on both ends regardless of the encoding.

File: arrow-row/src/lib.rs (hunk 2 above)
Comment (ding-young) [reply arrow-row/src/lib.rs:2253]: Done

File: arrow-row/src/lib.rs (hunk 4 above)
Comment (ding-young) [reply arrow-row/src/lib.rs:2291]: Done

File: arrow-row/src/lib.rs [hunk 5]
```diff
@@ -2148,6 +2172,166 @@ mod tests {
...
+        let values = a1_idx_0.values().as_primitive::<Int32Type>();
+
+        for i in 0..keys.len() {
+            if keys.is_null(i) {
+                assert!(a2_idx_0.is_null(i));
+            } else {
+                let dict_index = keys.value(i) as usize;
+                assert_eq!(values.value(dict_index), a2_idx_0.value(i));
+            }
+        }
```
Comment (ding-young) [inline arrow-row/src/lib.rs]: Here

File: arrow-row/src/lib.rs [hunk 6]
```diff
@@ -2148,6 +2172,166 @@ mod tests {
...
+
+        let back = converter.convert_rows(&r).unwrap();
+        let [s2] = back.try_into().unwrap();
+
+        // RowConverter flattens Dictionary
+        // s.ty = Struct(foo Dictionary(Int32, Int32)), s2.ty = Struct(foo Int32)
+        assert_ne!(&s.data_type(), &s2.data_type());
+        s2.to_data().validate_full().unwrap();
+
+        // Check if the logical data remains the same
```
Comment (ding-young) [inline arrow-row/src/lib.rs:2207]: And here too

**Comment by alamb** [comment]
> I updated the unit tests to compare each value and check if the data (logically) remains the same. thanks @gabotechs @alamb

Yes, I think keeping the values logically the same (with the same datatype) is what is desired

**Comment by alamb** [comment]
I am starting to check this PR out

File: arrow-row/src/lib.rs [hunk 7]
```diff
@@ -1668,8 +1668,21 @@ unsafe fn decode_column(
...
-            let builder = ArrayDataBuilder::new(field.data_type.clone())
+            let child_data: Vec<ArrayData> = children.iter().map(|c| c.to_data()).collect();
+            // Since RowConverter flattens certian data types (i.e. Dictionary),
+            // we need to use updated data type instead of original field
+            let corrected_fields: Vec<Field> = match &field.data_type {
+                DataType::Struct(struct_fields) => struct_fields
+                    .iter()
+                    .zip(child_data.iter())
+                    .map(|(orig_field, child_array)| {
+                        rebuild_field_with_child_type(orig_field, child_array)
```
Comment (alamb) [inline arrow-row/src/lib.rs]: I think this is the same as using `Field::with_data_type` which I think is more explicit

```suggestion
                        orig_field.clone().with_data_type(child_array.data_type().clone())
```

File: arrow-row/src/lib.rs [hunk 8]
```diff
@@ -1668,8 +1668,21 @@ unsafe fn decode_column(
             rows.iter_mut().for_each(|row| *row = &row[1..]);
             let children = converter.convert_raw(rows, validate_utf8)?;
 
-            let child_data = children.iter().map(|c| c.to_data()).collect();
-            let builder = ArrayDataBuilder::new(field.data_type.clone())
+            let child_data: Vec<ArrayData> = children.iter().map(|c| c.to_data()).collect();
+            // Since RowConverter flattens certian data types (i.e. Dictionary),
```
Comment (alamb) [inline arrow-row/src/lib.rs]:
```suggestion
            // Since RowConverter flattens certain data types (i.e. Dictionary),
```

File: arrow-row/src/lib.rs (hunk 2 above)
Comment (alamb) [reply arrow-row/src/lib.rs:2253]: I don't see an assert that the values came through correctly -- it is only checking the length)

File: arrow-row/src/lib.rs (hunk 7 above)
Comment (alamb) [reply arrow-row/src/lib.rs]: The same comment applies below as well

File: arrow-row/src/lib.rs [hunk 9]
```diff
@@ -2148,6 +2172,166 @@ mod tests {
...
+        let back = converter.convert_rows(&r).unwrap();
+        let [s2] = back.try_into().unwrap();
+
+        // RowConverter flattens Dictionary
+        // s.ty = Struct(foo Dictionary(Int32, Int32)), s2.ty = Struct(foo Int32)
+        assert_ne!(&s.data_type(), &s2.data_type());
+        s2.to_data().validate_full().unwrap();
+        assert_eq!(s.len(), s2.len());
+
+        // Test Case 2. None empty array
```
Comment (alamb) [inline arrow-row/src/lib.rs]: Can you please break test case 2 into its own `#test` function so it is easier to see?

File: arrow-row/src/lib.rs [hunk 10]
```diff
@@ -2148,6 +2172,166 @@ mod tests {
...
+            vec![Field::new_dictionary(
+                "foo",
+                DataType::Int32,
+                DataType::Int32,
+                false,
+            )],
+            vec![Box::new(builder)],
+        );
+        let dict_builder = struct_builder
+            .field_builder::<PrimitiveDictionaryBuilder<Int32Type, Int32Type>>(0)
```
Comment (alamb) [inline arrow-row/src/lib.rs]: Can we please change this so it uses different types for the keys and values -- otherwise it is hard to keep track of the key and values in the code below

File: arrow-row/src/list.rs [hunk 11]
```diff
@@ -179,7 +182,20 @@ pub unsafe fn decode<O: OffsetSizeTrait>(
 
     let child_data = child[0].to_data();
 
-    let builder = ArrayDataBuilder::new(field.data_type.clone())
+    // Since RowConverter flattens certian data types (i.e. Dictionary),
```
Comment (alamb) [inline arrow-row/src/list.rs]:
```suggestion
    // Since RowConverter flattens certain data types (i.e. Dictionary),
```

File: arrow-row/src/lib.rs (hunk 2 above)
Comment (ding-young) [reply arrow-row/src/lib.rs:2253]: Since this test uses an empty array, I updated the test to only check both lengths are 0. Other tests handle value level assertions.

File: arrow-row/src/lib.rs (hunk 10 above)
Comment (ding-young) [reply arrow-row/src/lib.rs]: I changed the dictionary type to `Dictionary(Int32, Utf8)` to improve readability. Let me know if anything in the test is still confusing or hard to follow.
