### PR TITLE
fix ownership of c stream error

### LINKED ISSUE #4659: Double free in C Stream Interface
**Describe the bug**

Got a double free when consuming a stream and trying to return the error. Right now the C Stream Interface import tries to take ownership of the error string, but once the release callback is called that string gets freed.

https://github.com/apache/arrow-rs/blob/f16ceedf981c7230167ff858eabb9a8cdc87ffda/arrow/src/ffi_stream.rs#L317-L327

From [the C stream interface docs](https://arrow.apache.org/docs/format/CStreamInterface.html#c.ArrowArrayStream.get_last_error):

> The returned pointer is only guaranteed to be valid until the next call of one of the stream’s callbacks. The character string it points to should be copied to consumer-managed storage if it is intended to survive longer.

**To Reproduce**

**Expected behavior**

We should probably clone the string as suggested by the interface docs.

**Additional context**

### PR DESCRIPTION
**Pull request by wjones127**
# Which issue does this PR close?

Closes #4659.

# Rationale for this change
 
The current implementation doesn't obey the ownership semantics laid out in the spec. When exporting to other Arrow implementations, it will leak memory through the `get_last_error()` method. When importing from other Arrow implementations, it will cause a double free. Also, null pointers aren't being handled.

# What changes are included in this PR?

Changes `get_last_error` implementations to treat the returned value as a borrowed and not owned string.

# Are there any user-facing changes?

I don't think so. It's possible that someone using the C Stream Interface to move data between an older version of arrow-rs and one after this change may face some FFI issues, but I doubt anyone is doing that.

### CODE REVIEW

File: arrow/src/ffi_stream.rs [hunk 1]
```diff
@@ -142,8 +143,12 @@ unsafe extern "C" fn get_next(
...
 unsafe extern "C" fn get_last_error(stream: *mut FFI_ArrowArrayStream) -> *const c_char {
     let mut ffi_stream = ExportedArrayStream { stream };
-    let last_error = ffi_stream.get_last_error();
-    CString::new(last_error.as_str()).unwrap().into_raw()
+    // The consumer should not take ownership of this string, we should return
+    // a const pointer to it.
+    match ffi_stream.get_last_error() {
+        Some(err_string) => err_string.as_ptr(),
+        None => std::ptr::null(),
+    }
```
Comment (viirya) [inline arrow/src/ffi_stream.rs:151]: 👍 nice catch

File: arrow/src/ffi_stream.rs [hunk 2]
```diff
@@ -503,4 +512,32 @@ mod tests {
 
         _test_round_trip_import(vec![array.clone(), array.clone(), array])
     }
+
+    #[test]
+    fn test_error_import() -> Result<()> {
```
Comment (viirya) [inline arrow/src/ffi_stream.rs:517]: Hmm, this test also passes in current branch without the fix. No?

**Review by viirya — APPROVED** [review]
The fix looks good to me. Just a question about the added test.

File: arrow/src/ffi_stream.rs (hunk 2 above)
Comment (wjones127) [reply arrow/src/ffi_stream.rs:517]: Yes that is true. We export an owned string, and then import an owned string. So round tripping to ourselves works. But other implementations (such as PyArrow) export a borrowed string, so our current implementation will raise a double free. To reproduce, within our implementation, add the changes for export at the top of the file, but leave out the changes for import. You should get a double free.

Comment (wjones127) [reply arrow/src/ffi_stream.rs:517]: I've added a PyArrow integration test that will fail on master.

Comment (viirya) [reply arrow/src/ffi_stream.rs:517]: Thank you.
