### PR TITLE
Prevent FlightSQL server panics for `do_put` when stream is empty or 1st stream element is an Err

### LINKED ISSUE #7329: [Bug] Ingestion with Arrow Flight Sql panic when the input stream is empty or fallible
**Describe the bug**

Arrow Flight Sql provides an ingest API for bulk ingestion. Specifically, the flight sql server should implement the `do_put_statement_ingest` and the flight sql client should call `FlightSqlServiceClient::execute_ingest` to ingest a stream of record batches.

The ingestion works well for non-empty infallible stream. However, the server will panic if the stream is fallible or empty.
The panic position is: 
https://github.com/apache/arrow-rs/blob/9f1ab95511e1eba21445426884bdbcad1cdac9d6/arrow-flight/src/sql/server.rs#L713

**To Reproduce**

I have written a test to reproduce the bug:

``` rust
#[cfg(test)]
mod tests {
    use std::net::SocketAddr;
    use std::str::FromStr;
    use std::sync::Arc;

    use arrow::array::{Int32Array, StringArray};
    use arrow::datatypes::{DataType, Field, Schema};
    use arrow::record_batch::RecordBatch;
    use arrow_flight::decode::FlightRecordBatchStream;
    use arrow_flight::error::FlightError;
    use arrow_flight::sql::CommandStatementIngest;
    use arrow_flight::sql::SqlInfo;
    use arrow_flight::sql::client::FlightSqlServiceClient;
    use arrow_flight::sql::server::PeekableFlightDataStream;
    use arrow_flight::{flight_service_server::FlightServiceServer, sql::server::FlightSqlService};
    use futures::TryStreamExt;
    use tokio::sync::oneshot;
    use tonic::transport::Endpoint;
    use tonic::{Request, Status, transport::Server};

    #[derive(Clone)]
    struct DummyFlightSqlServer;

    #[tonic::async_trait]
    impl FlightSqlService for DummyFlightSqlServer {
        type FlightService = DummyFlightSqlServer;

        /// Execute a bulk ingestion.
        async fn do_put_statement_ingest(
            &self,
            _ticket: CommandStatementIngest,
            request: Request<PeekableFlightDataStream>,
        ) -> Result<i64, Status> {
            let stream = FlightRecordBatchStream::new_from_flight_data(
                request.into_inner().map_err(FlightError::from),
            );
            let batches = stream
                .try_collect::<Vec<_>>()
                .await
                .map_err(|e| Status::unknown(e.to_string()))?;
            let affected_rows = batches.iter().map(|b| b.num_rows()).sum::<usize>();
            Ok(affected_rows as i64)
        }

        async fn register_sql_info(&self, _id: i32, _result: &SqlInfo) {}
    }

    #[tokio::test]
    async fn test_flight_sql_ingest() {
        // 1. Create a dummy Flight SQL server
        let server = DummyFlightSqlServer {};

        // 2. Start the server on port 4000
        let addr: SocketAddr = "127.0.0.1:4000".parse().unwrap();
        let (tx, rx) = oneshot::channel::<()>();

        let server_handle = tokio::spawn(async move {
            Server::builder()
                .add_service(FlightServiceServer::new(server))
                .serve_with_shutdown(addr, async {
                    rx.await.ok();
                })
                .await
                .unwrap();
        });

        // Wait for the server to start
        tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;

        // 3. Create a Flight SQL client and connect to the server
        let channel = Endpoint::from_str("http://127.0.0.1:4000")
            .unwrap()
            .connect()
            .await
            .unwrap();
        let mut client = FlightSqlServiceClient::new(channel);

        // 4. Prepare data for ingestion
        let schema = Arc::new(Schema::new(vec![
            Field::new("id", DataType::Int32, false),
            Field::new("name", DataType::Utf8, false),
        ]));
        let batch = RecordBatch::try_new(
            schema.clone(),
            vec![
                Arc::new(Int32Array::from(vec![1, 2, 3])),
                Arc::new(StringArray::from(vec!["Alice", "Bob", "Charlie"])),
            ],
        )
        .unwrap();

        // 5. Execute ingestion
        let stream = futures::stream::iter(vec![Ok(batch)]);
        let affected_rows = client
            .execute_ingest(
                CommandStatementIngest {
                    catalog: None,
                    schema: None,
                    table: "t".into(),
                    ..Default::default()
                },
                stream,
            )
            .await
            .unwrap();
        assert_eq!(affected_rows, 3);

        // 6. Execute ingestion with a fallible stream.
        let stream = futures::stream::iter(vec![Err(FlightError::ProtocolError("error".into()))]);
        let result = client
            .execute_ingest(
                CommandStatementIngest {
                    catalog: None,
                    schema: None,
                    table: "t".into(),
                    ..Default::default()
                },
                stream,
            )
            .await;
        if let Err(e) = result {
            println!("ingest error: {}", e);
        }

        // 7. Execute ingestion with an empty stream.
        let stream = futures::stream::empty();
        let result = client
            .execute_ingest(
                CommandStatementIngest {
                    catalog: None,
                    schema: None,
                    table: "t".into(),
                    ..Default::default()
                },
                stream,
            )
            .await;
        if let Err(e) = result {
            println!("ingest error: {}", e);
        }

        // Shutdown the server
        tx.send(()).unwrap();
        server_handle.await.unwrap();
    }
}
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by superserious-dev**
# Which issue does this PR close?
Closes #7329 .

# Rationale for this change
 When executing a `do_put` call, there are currently 2 cases that will cause the FlightSQL server to panic:
- the request stream is empty
- the first element of the request stream is an Err

This change stops the FlightSQL server from panicking in both cases.

# Are there any user-facing changes?

- If the client sends an empty request stream, the server reports that 0 records were affected.
- If the client sends a stream where the first element is an Err, the Err is reported back by the client and stream processing stops. This is the same as the current behavior when the Err is not the first element.

The server does not panic in either case.

### CODE REVIEW

File: arrow-flight/src/sql/server.rs [hunk 1]
```diff
@@ -710,10 +710,21 @@ where
...
+
+        // If the stream is empty or the first item is an Err,
+        // return early with 0 records affected
+        let peeked_item = stream.peek().await.cloned();
+        let Some(cmd) = peeked_item else {
+            let result = DoPutUpdateResult { record_count: 0 };
+            let output = futures::stream::iter(vec![Ok(PutResult {
+                app_metadata: result.encode_to_vec().into(),
+            })]);
+            return Ok(Response::new(Box::pin(output)));
```
Comment (alamb) [inline arrow-flight/src/sql/server.rs:723]: II the client is not sending a command, it probably is making a mistake, and returning an `Ok` will mask the problem rather than failing fast

Rather than return an Ok, I recommend  invoking `do_put_fallback` in this case which will error by default, and lets users override the behavior if they wish.

File: arrow-flight/tests/flight_sql_client.rs [hunk 2]
```diff
@@ -116,6 +116,53 @@ pub async fn test_execute_ingest_error() {
...
+    ))];
+
+    // make sure the client error was returned
+    let err = flight_sql_client
+        .execute_ingest(cmd, futures::stream::iter(batches))
+        .await
+        .unwrap_err();
+    assert_eq!(
+        err.to_string(),
+        "External error: Not yet implemented: Client error message"
```
Comment (alamb) [inline arrow-flight/tests/flight_sql_client.rs:163]: I think this error never makes it to the server -- it is redirected client side in https://github.com/apache/arrow-rs/blob/87ff531f0b4e109c2166c548d20c850e6b2c8fc5/arrow-flight/src/sql/client.rs#L269-L268

I think you'll have to create a manual FlightClient and send the error directly to exercise the server code

**Review by alamb — COMMENTED** [review]
Thank you @superserious-dev  -- this is a nice contribution; I left some suggestions, let me know what you think

File: arrow-flight/src/sql/server.rs (hunk 1 above)
Comment (superserious-dev) [reply arrow-flight/src/sql/server.rs:723]: That makes sense. It looks like [`do_put_fallback`](https://github.com/apache/arrow-rs/blob/1f15130414bdfc01c8989ec95702655bf553c5c5/arrow-flight/src/sql/server.rs#L378-L382) requires providing a message of type `Any`. What do you recommend passing in for the message? 

Here are a few potential options that pop out to me:
- Make the message an Option. Unfortunately this would be user-facing modification of the callback function signature. 
- Create a new variant on the [Command enum](https://github.com/apache/arrow-rs/blob/1f15130414bdfc01c8989ec95702655bf553c5c5/arrow-flight/src/sql/mod.rs#L165-L173) like `Command::Missing` and add a corresponding protobuf message type. 
- Create a new callback for unrecoverable errors, eg. `do_put_error`, which doesn't require passing in a message. It could take some kind of error enum with different types of errors, eg `DoPutError::MissingCommand`.

File: arrow-flight/src/sql/server.rs [hunk 3]
```diff
@@ -710,10 +710,21 @@ where
...
+        };
 
         let message =
-            Any::decode(&*cmd.flight_descriptor.unwrap().cmd).map_err(decode_error_to_status)?;
+            Any::decode(&*cmd?.flight_descriptor.unwrap().cmd).map_err(decode_error_to_status)?;
```
[the remark this answers is not in the document]
Comment (superserious-dev) [reply arrow-flight/src/sql/server.rs:727]: Yes, looks like it. Should this also get routed through `do_put_fallback` like the other 2 server panic cases?

File: arrow-flight/tests/flight_sql_client.rs (hunk 2 above)
Comment (superserious-dev) [reply arrow-flight/tests/flight_sql_client.rs:163]: Would it make sense to update the test's comment to something like "make sure the request-side client error is redirected"? 
My intent with this test is to verify that the client error in the batch gets surfaced. The current behavior is that a tonic error is being surfaced from the server panic.

Comment (alamb) [reply arrow-flight/tests/flight_sql_client.rs:163]: > Would it make sense to update the test's comment to something like "make sure the request-side client error is redirected"?

perhaps -- I am pretty sure that behavior was already covered by an existing test (though I didn't try and find it)

Comment (alamb) [reply arrow-flight/tests/flight_sql_client.rs:163]: > My intent with this test is to verify that the client error in the batch gets surfaced. The current behavior is that a tonic error is being surfaced from the server panic.

I guess I am saying that the error redirection is only happening in the rust client. If the actual server got an Error (maybe a network error or something) this test doesn't cover it, nor does the code int his PR cover it.

I don't think this PR needs to handle that case (as it isn't handled today) but I thought this test was misleading as it implies (at least to me) that the server is handling an error sent from the client, when that is not the case

File: arrow-flight/src/sql/server.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (alamb) [reply arrow-flight/src/sql/server.rs:727]: if possible, yes

File: arrow-flight/src/sql/server.rs (hunk 1 above)
Comment (alamb) [reply arrow-flight/src/sql/server.rs:723]: I recommend a new callback for unrecoverable errors as that would be a backwards compatible API change that we could release in the next release (not have to wait for the next major release)

File: arrow-flight/src/streams.rs [hunk 4]
```diff
@@ -32,15 +32,16 @@ use std::task::{ready, Poll};
 ///
 /// This can be used to accept a stream of `Result<_>` from a client API and send
 /// them to the remote server that wants only the successful results.
-pub(crate) struct FallibleRequestStream<T, E> {
+pub struct FallibleRequestStream<T, E> {
```
Comment (superserious-dev) [inline arrow-flight/src/streams.rs:35]: Changed the visibility of this in order to create the test that validates the bug fix.

File: arrow-flight/src/streams.rs [hunk 5]
```diff
@@ -32,15 +32,16 @@ use std::task::{ready, Poll};
...
     /// sender to notify error
     sender: Option<Sender<E>>,
     /// fallible stream
     fallible_stream: Pin<Box<dyn Stream<Item = std::result::Result<T, E>> + Send + 'static>>,
 }
 
 impl<T, E> FallibleRequestStream<T, E> {
-    pub(crate) fn new(
+    /// Create a FallibleRequestStream
+    pub fn new(
```
Comment (superserious-dev) [inline arrow-flight/src/streams.rs:44]: Same here: visibility change.

File: arrow-flight/tests/flight_sql_client.rs [hunk 6]
```diff
@@ -126,20 +124,26 @@ pub async fn test_execute_ingest_empty_stream() {
...
         .await
-        .expect("ingest should succeed");
-    assert_eq!(actual_rows, 0);
-
-    // make sure there were no batches sent to the server
-    let ingested_batches = test_server.ingested_batches.lock().await.clone();
-    assert_eq!(ingested_batches, vec![]);
+        .unwrap_err();
+    assert!(
+        err.to_string().contains("Unhandled Error: Command is missing."),
```
Comment (superserious-dev) [inline arrow-flight/tests/flight_sql_client.rs:141]: Currently only checking that the string contains the expected error. The full error appears to be something like an ArrowError::IpcError that holds a stringified Tonic Status::Unimplemented error.

File: arrow-flight/tests/flight_sql_client.rs (hunk 2 above)
Comment (superserious-dev) [reply arrow-flight/tests/flight_sql_client.rs]: Thank you for the additional context. I modified the tests to call `do_put` directly and verified that the new custom errors are emitted instead of the server panicking.
The caveat is that it required changing the visibility of `FallibleRequestStream` from pub(crate) to pub in order to construct a problematic stream for a test. Please let me know if there is a better way to do this.

File: arrow-flight/src/sql/server.rs (hunk 1 above)
Comment (superserious-dev) [reply arrow-flight/src/sql/server.rs]: Implemented this.

**Review by alamb — APPROVED** [review]
Thank you @superserious-dev  -- this looks really nice to me now. 👍

**Comment by alamb** [comment]
I merged up from main and ran `cargo fmt` to hopefully get a clean CI run

**Comment by alamb** [comment]
Thanks again @superserious-dev
