### PR TITLE
Ignore Field Metadata in equals_datatype for Dictionary, RunEndEncoded, Map and Union

### LINKED ISSUE #4110: Equality of nested data types
**Describe the bug**
The function `equals_datatype` checks the field name of data types `Dictionary`, `RunEndEncoded`, `Union` and `Map`. Like other nested data types, they shouldn't do this.

**To Reproduce**
```
use arrow::datatypes::{DataType, Field, UnionFields, UnionMode};
use std::sync::Arc;

fn main() {
    assert!(
        &DataType::List(Field::new("a", DataType::Int64, true).into()).equals_datatype(
            &DataType::List(Field::new("b", DataType::Int64, true).into())
        )
    );

    assert!(
        &DataType::Map(Arc::new(Field::new("a", DataType::Int64, true)), true).equals_datatype(
            &DataType::Map(Arc::new(Field::new("a", DataType::Int64, true)), true)
        )
    );

    assert!(!&DataType::Dictionary(
        Box::new(DataType::UInt8),
        Box::new(DataType::List(
            Field::new("a", DataType::Int64, true).into()
        ))
    )
    .equals_datatype(&DataType::Dictionary(
        Box::new(DataType::UInt8),
        Box::new(DataType::List(
            Field::new("b", DataType::Int64, true).into()
        ))
    )));
    assert!(!&DataType::RunEndEncoded(
        Arc::new(Field::new("aa", DataType::Int64, true)),
        Arc::new(Field::new("ab", DataType::Utf8, true))
    )
    .equals_datatype(&DataType::RunEndEncoded(
        Arc::new(Field::new("ba", DataType::Int64, true)),
        Arc::new(Field::new("bb", DataType::Utf8, true))
    )));
    assert!(!&DataType::Union(
        UnionFields::new(
            vec![1, 2],
            vec![
                Field::new("field1", DataType::UInt8, false),
                Field::new("field2", DataType::Utf8, false),
            ],
        ),
        UnionMode::Sparse,
    )
    .equals_datatype(&DataType::Union(
        UnionFields::new(
            vec![1, 2],
            vec![
                Field::new("field3", DataType::UInt8, false),
                Field::new("field4", DataType::Utf8, false),
            ],
        ),
        UnionMode::Sparse,
    )));
}
```

**Expected behavior**
```
use arrow::datatypes::{DataType, Field, UnionFields, UnionMode};
use std::sync::Arc;

fn main() {
    assert!(
        &DataType::List(Field::new("a", DataType::Int64, true).into()).equals_datatype(
            &DataType::List(Field::new("b", DataType::Int64, true).into())
        )
    );

    assert!(
        !&DataType::Map(Arc::new(Field::new("a", DataType::Int64, true)), true).equals_datatype(
            &DataType::Map(Arc::new(Field::new("b", DataType::Int64, true)), true)
        )
    );

    assert!(&DataType::Dictionary(
        Box::new(DataType::UInt8),
        Box::new(DataType::List(
            Field::new("a", DataType::Int64, true).into()
        ))
    )
    .equals_datatype(&DataType::Dictionary(
        Box::new(DataType::UInt8),
        Box::new(DataType::List(
            Field::new("b", DataType::Int64, true).into()
        ))
    )));
    assert!(&DataType::RunEndEncoded(
        Arc::new(Field::new("aa", DataType::Int64, true)),
        Arc::new(Field::new("ab", DataType::Utf8, true))
    )
    .equals_datatype(&DataType::RunEndEncoded(
        Arc::new(Field::new("ba", DataType::Int64, true)),
        Arc::new(Field::new("bb", DataType::Utf8, true))
    )));
    assert!(&DataType::Union(
        UnionFields::new(
            vec![1, 2],
            vec![
                Field::new("field1", DataType::UInt8, false),
                Field::new("field2", DataType::Utf8, false),
            ],
        ),
        UnionMode::Sparse,
    )
    .equals_datatype(&DataType::Union(
        UnionFields::new(
            vec![1, 2],
            vec![
                Field::new("field3", DataType::UInt8, false),
                Field::new("field4", DataType::Utf8, false),
            ],
        ),
        UnionMode::Sparse,
    )));
}
```

**Additional context**

### PR DESCRIPTION
**Pull request by izveigor**
# Which issue does this PR close?

Closes #4110.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?
Yes

### CODE REVIEW

File: arrow-schema/src/datatype.rs [hunk 1]
```diff
@@ -664,6 +701,90 @@ mod tests {
...
+        let list_s =
+            DataType::Dictionary(Box::new(DataType::UInt8), Box::new(list_b.clone()));
+        let list_t = DataType::Dictionary(Box::new(DataType::Int8), Box::new(list_b));
+        let list_u = DataType::Dictionary(Box::new(DataType::UInt8), Box::new(list_c));
+
+        assert!(list_r.equals_datatype(&list_s));
+        assert!(!list_r.equals_datatype(&list_t));
+        assert!(!list_r.equals_datatype(&list_u));
+
+        let list_v = DataType::Union(
```
Comment (tustvold) [inline arrow-schema/src/datatype.rs:728]:
```suggestion
        let union_a = DataType::Union(
```
And same below

File: arrow-schema/src/datatype.rs [hunk 2]
```diff
@@ -628,10 +661,14 @@ mod tests {
         assert!(!list_b.equals_datatype(&list_c));
```
Comment (tustvold) [inline arrow-schema/src/datatype.rs:661]: Could possibly add some tests for differing nullability

**Review by tustvold — APPROVED** [review]
Just some minor comments about test coverage, but this looks good to me, thank you.

As this is technically a breaking change, I have labelled it as such
