### PR TITLE
object_store: fix: Incorrect parsing of https Path Style S3 url

### LINKED ISSUE #4078: object_store: Incorrect parsing of https Path Style S3 url
**Description**
Currently, the S3 bucket URL parsing for AWS [here](https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.with_url)  is mistakenly parsing the bucket out of URL `https://s3.bucket.amazonaws.com`. However, this URL does not represent a valid S3 bucket URL format. The correct format should be `https://s3.region.amazonaws.com/bucket` for Path style as mentioned in AWS user guide [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html)

**Expected behavior**
The `parse_url` method on builder should correctly parse the S3 bucket URL and set region and bucket accordingly.

**Additional context**
[Invalid URL in Test](https://docs.rs/object_store/latest/src/object_store/aws/mod.rs.html#1414)
[parse_url](https://docs.rs/object_store/latest/src/object_store/aws/mod.rs.html#759-762)

### PR DESCRIPTION
**Pull request by roeap**
# Which issue does this PR close?

Closes #4078

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by roeap** [comment]
Not sure, but happy to add it.

Guess it makes sense, since we cannot work without a bucket. Haven't considered it so far, since we were only processing the host.

**Comment by roeap** [comment]
We are now also checking if the first path segment exists, and assigning it to the bucket.

File: object_store/src/aws/mod.rs [hunk 1]
```diff
@@ -758,12 +758,16 @@ impl AmazonS3Builder {
...
-
         match parsed.scheme() {
             "s3" | "s3a" => self.bucket_name = Some(host.to_string()),
             "https" => match host.splitn(4, '.').collect_tuple() {
-                Some(("s3", bucket, "amazonaws", "com")) => {
-                    self.bucket_name = Some(bucket.to_string());
+                Some(("s3", region, "amazonaws", "com")) => {
+                    self.region = Some(region.to_string());
+                    if let Some(bucket) =
+                        parsed.path_segments().and_then(|mut path| path.next())
```
Comment (tustvold) [inline object_store/src/aws/mod.rs:767]: Could we get a test of this perhaps?

**Review by tustvold — APPROVED** [review]
