### PR TITLE
fix: binary_mut should work if only one input array has null buffer

### LINKED ISSUE #6374: `compute::binary_mut` returns `Err(PrimitiveArray<T>)` only with certain arrays
**Describe the bug**
[`compute::binary_mut`](https://docs.rs/arrow/latest/arrow/compute/fn.binary_mut.html) returns `Err(PrimitiveArray<T>)` in cases when the underlying buffer is not shared (as described in [the documentation](https://docs.rs/arrow/latest/arrow/compute/fn.binary_mut.html#buffer-reuse)). It only happens when passing certain arrays.

**To Reproduce**

- Err case:
```
let a = Int32Array::from(vec![
    Some(3),
    Some(4),
    Some(5),
    Some(6),
    None,
]);

let b = Int32Array::from(vec![
    Some(10),
    Some(11),
    Some(12),
    Some(13),
    Some(14),
]);

let a = binary_mut(a, &b, |a, b| a + b);
```
produces
```
Err(PrimitiveArray<Int32>
[
  3,
  4,
  5,
  6,
  null,
])
```
- Ok case:
```
let a = Int32Array::from(vec![
    Some(3),
    Some(4),
    Some(5),
    Some(6),
    None,
]);

let b = Int32Array::from(vec![
    Some(10),
    Some(11),
    None,
    Some(13),
    Some(14),
]);

let a = binary_mut(a, &b, |a, b| a + b);
```
produces
```
Ok(Ok(PrimitiveArray<Int32>
[
  13,
  15,
  null,
  19,
  null,
]))
```

**Expected behavior**
I would have expected the first case to produce
```
Ok(Ok(PrimitiveArray<Int32>
[
  13,
  15,
  17,
  19,
  null,
]))
```

**Additional context**

<details>
<summary>Additional cases</summary>

- Err case:

```
let a = Int32Array::from(vec![
    Some(3),
    Some(4),
    Some(5),
    Some(6),
    None,
    Some(8)
]);

let b = Int32Array::from(vec![
    Some(10),
    Some(11),
    Some(12),
    Some(13),
    Some(14),
    Some(15),
]);

let a = binary_mut(a, &b, |a, b| a + b);
```
produces
```
Err(PrimitiveArray<Int32>
[
  3,
  4,
  5,
  6,
  null,
  8,
])
```
- Ok case:
```
let a = Int32Array::from(vec![
    Some(3),
    Some(4),
    Some(5),
    Some(6),
    None,
    Some(8)
]);

let b = Int32Array::from(vec![
    Some(10),
    Some(11),
    Some(12),
    Some(13),
    Some(14),
    None,
]);

let a = binary_mut(a, &b, |a, b| a + b);
```
produces
```
Ok(Ok(PrimitiveArray<Int32>
[
  13,
  15,
  17,
  19,
  null,
  null,
]))
```
</details>

The errors seem to be associated with an uneven number of null values.

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #6374.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-arith/src/arity.rs [hunk 1]
```diff
@@ -313,7 +313,7 @@ where
         ))));
     }
 
-    let nulls = NullBuffer::union(a.logical_nulls().as_ref(), b.logical_nulls().as_ref());
```
Comment (viirya) [inline arrow-arith/src/arity.rs:316]: If only `a` has null buffer, `NullBuffer.union` will clone it which shares the underlying buffer that fails `into_mutable` call on the null buffer later.

File: arrow-arith/src/arity.rs [hunk 2]
```diff
@@ -435,6 +436,22 @@ where
...
+///
+/// The union of the nulls is the same as `NullBuffer::union(lhs, rhs)` but
+/// it does not increase the reference count of the null buffer.
+fn create_union_null_buffer(
+    lhs: Option<&NullBuffer>,
+    rhs: Option<&NullBuffer>,
+) -> Option<NullBuffer> {
+    match (lhs, rhs) {
+        (Some(lhs), Some(rhs)) => Some(NullBuffer::new(lhs.inner() & rhs.inner())),
+        (Some(n), None) | (None, Some(n)) => Some(NullBuffer::new(n.inner() & n.inner())),
```
Comment (alamb) [inline arrow-arith/src/arity.rs:450]: If I understand this correctly, it forces a copy of the null buffer's contents?

Comment (viirya) [reply arrow-arith/src/arity.rs:450]: Yes. Previously it did a clone that shares the underlying buffer.

File: arrow-arith/src/arity.rs (hunk 1 above)
Comment (viirya) [reply arrow-arith/src/arity.rs:316]: Hmm, let me see if it works.

Comment (viirya) [reply arrow-arith/src/arity.rs:316]: Hmm, for `binary_mut`, it is okay to defer the computation of union of two null buffers. It is because that we don't need to own the null buffers before invoking `op` on the two arrays.

Since the null buffer is not changed on the builder, we can compute the union after finishing the builder. So for `binary_mut`, we can avoid copying null buffer.

But for `try_binary_mut`, because we need to get the union of two null buffers before invoking `op` on the two arrays, we still need to copy it as this PR does.

Comment (viirya) [reply arrow-arith/src/arity.rs:316]: So I only avoid copying null buffer in `binary_mut`.

**Comment by MaxenceMaire** [comment]
Nice work, thanks @viirya and @alamb for looking into it!

File: arrow-arith/src/arity.rs (hunk 1 above)
Comment (alamb) [reply arrow-arith/src/arity.rs:316]: It still feels to me that we could remove the copy on try_binary_mut, but this seems like an improvement to me 🚀

File: arrow-arith/src/arity.rs [hunk 3]
```diff
@@ -557,6 +577,24 @@ mod tests {
...
+
+        let r1 = binary_mut(a, &b, |a, b| a + b).unwrap();
+
+        let a = Int32Array::from(vec![Some(3), Some(4), Some(5), Some(6), None]);
+        let b = Int32Array::new(
+            vec![10, 11, 12, 13, 14].into(),
+            Some(vec![true, true, true, true, true].into()),
+        );
+
+        let r2 = binary_mut(a, &b, |a, b| a + b).unwrap();
```
Comment (alamb) [inline arrow-arith/src/arity.rs:594]:
```suggestion
        // unwrap here means that no copying occured
        let r2 = binary_mut(a, &b, |a, b| a + b).unwrap();
```

File: arrow-arith/src/arity.rs [hunk 4]
```diff
@@ -587,6 +625,24 @@ mod tests {
...
+
+        let r1 = try_binary_mut(a, &b, |a, b| Ok(a + b)).unwrap();
+
+        let a = Int32Array::from(vec![Some(3), Some(4), Some(5), Some(6), None]);
+        let b = Int32Array::new(
+            vec![10, 11, 12, 13, 14].into(),
+            Some(vec![true, true, true, true, true].into()),
+        );
+
+        let r2 = try_binary_mut(a, &b, |a, b| Ok(a + b)).unwrap();
```
Comment (alamb) [inline arrow-arith/src/arity.rs:642]:
```suggestion
        // unwrap here means that no copying occured
        let r2 = try_binary_mut(a, &b, |a, b| Ok(a + b)).unwrap();
```

**Review by alamb — APPROVED** [review]
Thank you @viirya  -- this looks good to me

**Comment by viirya** [comment]
Thanks @alamb @MaxenceMaire

**Review by alamb — APPROVED** [review]
A copy of the NullBuffer in some cases seems a lot better than having to copy the entire array as was needed previously 

Let's go with this and iterate as a follow on

**Comment by viirya** [comment]
Thank you @alamb
