### PR TITLE
Canonicalize filesystem paths in user-facing APIs (#2370)

### LINKED ISSUE #2370: LocalFileSystem::new_with_prefix fails with relative path
**Describe the bug**

Calling `LocalFileSystem::new_with_prefix(".")` no longer works as of #2269  

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2370

# Rationale for this change
 
Users expect to be able to pass arbitrary paths to `LocalFileSystem::new_with_prefix` or `Path::from_filesystem_path` and for it to work correctly. This stopped working following #2269 as we stopped canonicalizing paths.

This PR therefore strikes a middle-ground, we canonicalize paths passed to the external interfaces, ensuring the above works. However, we otherwise continue to preserve symlinks, etc... whilst navigating the filesystem as part of object storage operation, thereby ensuring symlinks behave "as expected".

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: object_store/src/local.rs [hunk 1]
```diff
@@ -1286,4 +1300,15 @@ mod tests {
         assert_eq!(res.objects.len(), 1);
         assert_eq!(res.objects[0].location.as_ref(), filename);
     }
+
+    #[tokio::test]
+    async fn relative_paths() {
+        LocalFileSystem::new_with_prefix(".").unwrap();
+        LocalFileSystem::new_with_prefix("..").unwrap();
+        LocalFileSystem::new_with_prefix("../..").unwrap();
```
Comment (alamb) [inline object_store/src/local.rs:1308]: I guess this should be ok (`../..` will exist) -- as long as the test isn't run in the root of the file system 😆

**Review by alamb — APPROVED** [review]
