### PR TITLE
Fix csv writing of timestamps to show timezone.

### LINKED ISSUE #778: Timestamps don't round-trip through CSV writer/reader
**Describe the bug**

Create a `TimestampNanosecondArray` and write it to CSV.
Read the resulting CSV back and it will be parsed as `UTF-8` not `TimestampNanosecondType`.
Cast the parsed string to `TimestampNanosecondType::DATA_TYPE` and the value will be off by the local timezone offset.

I *think* the solution may be as simple as having the CSV writer append the `Z` suffix to indicate the timestamp is in GMT time, but I'm not sure.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by novemberkilo**
# Which issue does this PR close?

Closes #778 

# What changes are included in this PR?

- Round-trip test of csv writing and reading of timestamps  
- Fix to csv writer so that timestamps are written out in UTC.

# Are there any user-facing changes?

Yes. This changes the behaviour of the csv writer.

// @alamb @bjchambers

### CODE REVIEW

**Comment by novemberkilo** [comment]
@alamb @bjchambers I have made changes to the csv writer according to the proposal.

While doing so, I have noticed what I think is a bug in the temporal utilities in the kernel. Essentially, variations relating to daylight savings are not recognised at the moment. I have a failing test on a branch [here](https://github.com/novemberkilo/arrow-rs/commit/473e2e4eb4f3b47aa7110d1a23444647b1109665). I came up across this issue during this work as and had to implement https://github.com/novemberkilo/arrow-rs/blob/master/arrow/src/compute/kernels/temporal.rs#L98-L110 to correctly derive the offset for a timezone. 

I figure I should fix this bug separately -- should I file an issue to describe it and then put up a fix against that? Thanks.

**Comment by alamb** [comment]
> I figure I should fix this bug separately -- should I file an issue to describe it and then put up a fix against that? Thanks.

I think that would make the most sense to me @novemberkilo  -- thanks

**Comment by alamb** [comment]
Thanks @novemberkilo  -- I plan to review this more carefully hopefully today

File: arrow/src/compute/kernels/temporal.rs [hunk 1]
```diff
@@ -435,4 +452,78 @@ mod tests {
...
+        // When local daylight time was about to reach
+        // Sunday, 4 April 2021, 3:00:00 am clocks were turned backward 1 hour to
+        // Sunday, 4 April 2021, 2:00:00 am local standard time instead.
+
+        // Daylight savings starts
+        // When local standard time was about to reach
+        // Sunday, 3 October 2021, 2:00:00 am clocks were turned forward 1 hour to
+        // Sunday, 3 October 2021, 3:00:00 am local daylight time instead.
+
+        // Sydney 2021-04-04T02:30:00+11:00 is 2021-04-03T15:30:00Z
```
Comment (alamb) [inline arrow/src/compute/kernels/temporal.rs:488]: I really like the names of the variables and comments in this test 👍 . It makes them very easy to understand

File: arrow/src/csv/writer.rs [hunk 2]
```diff
@@ -258,6 +240,100 @@ impl<W: Write> Writer<W> {
...
+            Nanosecond => col
+                .as_any()
+                .downcast_ref::<TimestampNanosecondArray>()
+                .unwrap()
+                .value_as_datetime(row_index)
+                .unwrap(),
+        };
+        match time_zone {
+            None => Ok(format!("{}Z", datetime.format(&self.timestamp_format))),
+            Some(tzs) => match using_chrono_tz_and_utc_naive_date_time(tzs, datetime) {
```
Comment (alamb) [inline arrow/src/csv/writer.rs:319]: I think we can avoid some of this code duplication by following the model of

What would you think about following the model of `using_chrono_tz` -- and providing an implementation of `using_chrono_tz_and_utc_naive_date_time` that doesn't do any conversion of `chrono-tz` isn't available. 

Something like the following (not tested)

```rust
/// Ignore timezones if chrono-tz is not enabled and as utc
#[not(cfg(feature = "chrono-tz")]
pub fn using_chrono_tz_and_utc_naive_date_time(
    tz: &str,
    utc: chrono::NaiveDateTime,
) -> Option<FixedOffset> {
  Some(FixedOffset(0))
}
```

The code in `arrow/src/csv/writer.rs` could thenbe simpler and always call `using_chrono_tz_and_utc_naive_date_time` but if `chrono-tz` wasn't enabled then it would retain the current behavior

File: arrow/src/csv/writer.rs [hunk 3]
```diff
@@ -499,6 +582,83 @@ sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000,23:46:03,foo
         );
     }
 
+    #[cfg(feature = "chrono-tz")]
+    #[test]
+    fn test_write_csv() {
```
Comment (alamb) [inline arrow/src/csv/writer.rs:587]: What do you think about reducing the replication in the test by keeping a single `test_write_csv` function and instead conditionalize the expected output. This would not only reduce the replication, it would also make it clearer what was the expected difference

Something like (untested)
```rust
    #[test]
    fn test_write_csv() {
...
    #[cfg(not(feature = "chrono-tz"))]
    let expected = r#"c1,c2,c3,c4,c5,c6,c7
Lorem ipsum dolor sit amet,123.564532,3,true,,00:20:34,cupcakes
consectetur adipiscing elit,,2,false,2019-04-18T10:54:47.378000000,06:51:20,cupcakes
sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000,23:46:03,foo
Lorem ipsum dolor sit amet,123.564532,3,true,,00:20:34,cupcakes
consectetur adipiscing elit,,2,false,2019-04-18T10:54:47.378000000,06:51:20,cupcakes
sed do eiu
"#;

    #[cfg(feature = "chrono-tz")]
    let expected = r#"c1,c2,c3,c4,c5,c6,c7
Lorem ipsum dolor sit amet,123.564532,3,true,,00:20:34,cupcakes
consectetur adipiscing elit,,2,false,2019-04-18T10:54:47.378000000Z,06:51:20,cupcakes
sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000Z,23:46:03,foo
Lorem ipsum dolor sit amet,123.564532,3,true,,00:20:34,cupcakes
consectetur adipiscing elit,,2,false,2019-04-18T10:54:47.378000000Z,06:51:20,cupcakes
sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000Z,23:46:03,foo
"#;

assert_eq!(expected.to_string(), String::from_utf8(buffer).unwrap());
```

File: arrow/src/csv/writer.rs [hunk 4]
```diff
@@ -626,6 +787,134 @@ sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000,23:46:03,\n";
...
+                ),
+                true,
+            ),
+            Field::new("c2", DataType::Timestamp(TimeUnit::Millisecond, None), true),
+        ]);
+
+        let c1 = TimestampMillisecondArray::from_opt_vec(
+            // 1555584887 converts to 2019-04-18, 20:54:47 in time zone Australia/Sydney (AEST).
+            // The offset (difference to UTC) is +10:00.
+            // 1635577147 converts to 2021-10-30 17:59:07 in time zone Australia/Sydney (AEDT)
```
Comment (alamb) [inline arrow/src/csv/writer.rs:808]: 👍

File: arrow/src/csv/writer.rs [hunk 5]
```diff
@@ -626,6 +787,134 @@ sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000,23:46:03,\n";
...
+        let left = "c1,c2
+2019-04-18T20:54:47.378000000+10:00,2019-04-18T10:54:47.378000000Z
+2021-10-30T17:59:07.000000000+11:00,2021-10-30T06:59:07.000000000Z\n";
+        let right = writer.writer.into_inner().map(|s| s.to_string());
+        assert_eq!(Some(left.to_string()), right.ok());
+    }
+
+    #[cfg(feature = "chrono-tz")]
+    #[test]
+    fn test_export_csv_string() {
```
Comment (alamb) [inline arrow/src/csv/writer.rs:838]: is this testing anything that is not covered in `test_csv_writer()`?

File: arrow/src/csv/writer.rs [hunk 6]
```diff
@@ -675,4 +964,76 @@ sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000,23:46:03,\n";
         let expected = vec![Some(3), Some(2), Some(1)];
         assert_eq!(actual, expected);
     }
+
+    #[cfg(feature = "chrono-tz")]
+    #[test]
+    fn test_conversion_consistency() {
+        // test if we can serialize and deserialize whilst retaining the same type information/ precision
```
Comment (alamb) [inline arrow/src/csv/writer.rs:971]: 👍

File: arrow/src/csv/writer.rs [hunk 7]
```diff
@@ -675,4 +964,76 @@ sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000,23:46:03,\n";
...
+            .unwrap();
+
+        let actual = c1.into_iter().collect::<Vec<_>>();
+        let expected = vec![Some(3), Some(2), Some(1)];
+        assert_eq!(actual, expected);
+        let actual = c2.into_iter().collect::<Vec<_>>();
+        let expected = vec![Some(3), Some(2), Some(1)];
+        assert_eq!(actual, expected);
+        let actual = c3.into_iter().collect::<Vec<_>>();
+        let expected = vec![
```
Comment (alamb) [inline arrow/src/csv/writer.rs:1032]: I wonder if it would be possible to use the same vec in the creation of the input and the expected output which would make it explicit they were supposed to be the same

Something like 

```rust
        let c3 = TimestampNanosecondArray::from_vec(expected.clone(), None);
```

above, perhaps

**Review by alamb — COMMENTED** [review]
Thanks @novemberkilo  this is looking quite nice.

File: arrow/src/csv/writer.rs (hunk 5 above)
Comment (novemberkilo) [reply arrow/src/csv/writer.rs]: Good point thanks - removing.

**Comment by novemberkilo** [comment]
Thanks much for the feedback @alamb -- I have reviewed your comments and made changes accordingly. 

Something to note, instead of adding `Z` to indicate UTC, we now consistently use the same format string and show UTC as `+00:00`

File: arrow/src/csv/writer.rs [hunk 8]
```diff
@@ -675,4 +748,70 @@ sed do eiusmod tempor,-556132.25,1,,2019-04-18T02:45:55.555000000,23:46:03,\n";
...
+            .unwrap();
+
+        let actual = c1.into_iter().collect::<Vec<_>>();
+        let expected = vec![Some(3), Some(2), Some(1)];
+        assert_eq!(actual, expected);
+        let actual = c2.into_iter().collect::<Vec<_>>();
+        let expected = vec![Some(3), Some(2), Some(1)];
+        assert_eq!(actual, expected);
+        let actual = c3.into_iter().collect::<Vec<_>>();
+        let expected = nanoseconds.into_iter().map(|x| Some(x)).collect::<Vec<_>>();
```
Comment (alamb) [inline arrow/src/csv/writer.rs:814]: 👍

**Review by alamb — APPROVED** [review]
Looks great -- thank you @novemberkilo

**Comment by novemberkilo** [comment]
Thanks @alamb - once this is merged I will put up a PR for this https://github.com/apache/arrow-rs/issues/901

**Comment by alamb** [comment]
I'll plan to merge this tomorrow morning unless anyone else has any comments

**Comment by alamb** [comment]
Thanks again @novemberkilo
