### PR TITLE
Don't panic on invalid Azure access key (#4972)

### LINKED ISSUE #4972: Panic when using an azure object store with an invalid access key
**Describe the bug**

When using an azure object store configured with an invalid access key, attempting to use the store will result in a panic.

**To Reproduce**

Example:

```rust
use object_store::azure::MicrosoftAzureBuilder;
use object_store::{path::Path, ObjectStore};

#[tokio::main]
async fn main() {
    let store = MicrosoftAzureBuilder::new()
        .with_account("my_account")
        .with_container_name("my_container")
        .with_access_key("invalid")
        .build()
        .unwrap();

    let path = &Path::parse("/my_path").unwrap();
    let _res = store.get(&path).await;
}
```

Results in a panic during the `get`:

```
thread 'main' panicked at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/object_store-0.7.1/src/azure/credential.rs:189:56:
called `Result::unwrap()` on an `Err` value: InvalidPadding
```

**Expected behavior**

No panic and instead an error gets returned.

The easy fix is to just propagate the error up from here: https://github.com/apache/arrow-rs/blob/03d0505fc864c09e6dcd208d3cdddeecefb90345/object_store/src/azure/credential.rs#L170-L182

**Additional context**

Our use case is we configure object stores based on user provided values, and so a panic when provided with an invalid value is undesirable.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4972

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: object_store/src/azure/credential.rs [hunk 1]
```diff
@@ -93,13 +96,25 @@ impl From<Error> for crate::Error {
...
+}
+
 /// An Azure storage credential
 #[derive(Debug, Eq, PartialEq)]
 pub enum AzureCredential {
     /// A shared access key
     ///
     /// <https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key>
-    AccessKey(String),
+    AccessKey(AzureAccessKey),
```
Comment (tustvold) [inline object_store/src/azure/credential.rs:117]: This is an API change

File: object_store/src/azure/credential.rs [hunk 2]
```diff
@@ -174,10 +189,10 @@ fn generate_authorization(
     u: &Url,
     method: &Method,
     account: &str,
-    key: &str,
+    key: &AzureAccessKey,
 ) -> String {
     let str_to_sign = string_to_sign(h, u, method, account);
-    let auth = hmac_sha256(BASE64_STANDARD.decode(key).unwrap(), str_to_sign);
```
Comment (crepererum) [inline object_store/src/azure/credential.rs:180]: for other reviewers: this is the actual fix: the key decoding is moved from an unwrapping/panicky version here to early decoding as part of the API.

**Review by crepererum — APPROVED** [review]
