### PR TITLE
fix JSON decoder error checking for UTF16 / surrogate parsing panic

### LINKED ISSUE #7712: In arrow_json, Decoder::decode can panic if it encounters two high surrogates in a row.
**Describe the bug**

In arrow_json, `Decoder::decode` can panic if it encounters two high surrogates in a row. Since this method returns a `Result`, panics are not expected, even in error cases.

**To Reproduce**

The following program reproduces the bug:
```rust
use std::io::{BufRead, BufReader};
use std::sync::Arc;

use arrow::datatypes::{DataType, Field};
use arrow_json::ReaderBuilder;

fn main() {
    let mut decoder =
        ReaderBuilder::new_with_field(Arc::new(Field::new("test", DataType::Utf8, true)))
            .build_decoder()
            .unwrap();
    let s = r#"{"test": "\uD800\uD801"}"#;
    let mut reader = BufReader::new(s.as_bytes());
    let buf = reader.fill_buf().unwrap();
    let _ = decoder.decode(buf);
}
```

Running this gives:
```
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-json-55.1.0/src/reader/tape.rs:708:49:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:695:5
   1: core::panicking::panic_fmt
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:178:21
   3: arrow_json::reader::tape::char_from_surrogate_pair
             at [..]/arrow-json-55.1.0/src/reader/tape.rs:708:49
   4: arrow_json::reader::tape::TapeDecoder::decode
             at [..]/arrow-json-55.1.0/src/reader/tape.rs:514:37
   5: arrow_json::reader::Decoder::decode
             at [..]/arrow-json-55.1.0/src/reader/mod.rs:439:9
   6: arrow_panic::main
             at ./src/main.rs:15:13
   7: core::ops::function::FnOnce::call_once
             at [..]/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
```

**Expected behavior**

`decode` should return an error as the string is invalid, but it should not panic.

**Additional context**

### PR DESCRIPTION
**Pull request by nicklan**
# Which issue does this PR close?

- Closes #7712 .

# Rationale for this change

Shouldn't panic, especially in a fallible function.

# What changes are included in this PR?

Validate that the high and low surrogates are in the expected range, which guarantees that the subtractions won't overflow.

# Are there any user-facing changes?

No (well, things that used to panic now won't, but I don't think that counts)

### CODE REVIEW

File: arrow-json/src/reader/tape.rs [hunk 1]
```diff
@@ -705,9 +705,16 @@ fn err(b: u8, ctx: &str) -> ArrowError {
...
+    match (low, high) {
+        (0xDC00..=0xDFFF, 0xD800..=0xDBFF) => {
+            let n = (((high - 0xD800) as u32) << 10) | ((low - 0xDC00) as u32 + 0x1_0000);
+            char::from_u32(n)
+                .ok_or_else(|| ArrowError::JsonError(format!("Invalid UTF-16 surrogate pair {n}")))
+        }
+        _ => Err(ArrowError::JsonError(format!(
+            "Invalid UTF-16 surrogate pair. High: {high:#02X}, Low: {low:#02X}"
+        ))),
+    }
```
Comment (scovich) [inline arrow-json/src/reader/tape.rs:717]: Would a pair of [checked_sub](https://doc.rust-lang.org/std/primitive.u16.html#method.checked_sub) work?
```suggestion
    char_from_surrogate_pair_opt(low, high).ok_or_else(|| {
        ArrowError::JsonError(format!("Invalid UTF-16 surrogate pair: {lo:#02X}, {high:#02X}"))
    })
}
fn char_from_surrogate_pair_opt(low: u16, high: u16) -> Option<char> {
    let high = high.checked_sub(0xD800)? as u32;
    let low = low.checked_sub(0xDC00)? as u32;
    char::from_u32((high << 10) | (low + 0x1_0000))
```

Comment (nicklan) [reply arrow-json/src/reader/tape.rs:717]: I did consider this, and it does have the benefit of being more succinct. I opted for the range check because if one of the arguments was too high the checked sub would not catch it and I wasn't able to convince myself that only valid inputs would allow `char::from_u32` to succeed.

I could dig more into the calling layers to check if that's prevented there, but it still felt like more of a foot-gun than the simple range check.

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_arrow.sh) Running
Linux aal-dev 6.11.0-1015-gcp #15~24.04.1-Ubuntu SMP Thu Apr 24 20:41:05 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing fix-json-surrogate-parsing-panic (30170cebd4bf75c245cb32ceeb56e128ad92f125) to fbaf7cea2df2c21cfe47d0dcb77e0abce81be215 [diff](https://github.com/apache/arrow-rs/compare/fbaf7cea2df2c21cfe47d0dcb77e0abce81be215..30170cebd4bf75c245cb32ceeb56e128ad92f125)
BENCH_NAME=json_reader
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench json_reader 
BENCH_FILTER=
BENCH_BRANCH_NAME=fix-json-surrogate-parsing-panic
Results will be posted here when complete

**Comment by alamb** [comment]
Thank you @nicklan  and @scovich  -- I started the CI and some benchmarks on this PR

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                  fix-json-surrogate-parsing-panic       main
-----                                  --------------------------------       ----
large_bench_primitive                  1.00      2.3±0.01ms        ? ?/sec    1.04      2.4±0.00ms        ? ?/sec
small_bench_list                       1.00     12.9±0.03µs        ? ?/sec    1.03     13.2±0.07µs        ? ?/sec
small_bench_primitive                  1.01      6.6±0.04µs        ? ?/sec    1.00      6.5±0.04µs        ? ?/sec
small_bench_primitive_with_utf8view    1.00      6.2±0.04µs        ? ?/sec    1.04      6.5±0.09µs        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_arrow.sh) Running
Linux aal-dev 6.11.0-1015-gcp #15~24.04.1-Ubuntu SMP Thu Apr 24 20:41:05 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing fix-json-surrogate-parsing-panic (30170cebd4bf75c245cb32ceeb56e128ad92f125) to fbaf7cea2df2c21cfe47d0dcb77e0abce81be215 [diff](https://github.com/apache/arrow-rs/compare/fbaf7cea2df2c21cfe47d0dcb77e0abce81be215..30170cebd4bf75c245cb32ceeb56e128ad92f125)
BENCH_NAME=json_reader
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench json_reader 
BENCH_FILTER=
BENCH_BRANCH_NAME=fix-json-surrogate-parsing-panic
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                  fix-json-surrogate-parsing-panic       main
-----                                  --------------------------------       ----
large_bench_primitive                  1.00      2.3±0.01ms        ? ?/sec    1.05      2.4±0.01ms        ? ?/sec
small_bench_list                       1.00     13.1±0.05µs        ? ?/sec    1.01     13.2±0.04µs        ? ?/sec
small_bench_primitive                  1.00      6.5±0.03µs        ? ?/sec    1.02      6.6±0.03µs        ? ?/sec
small_bench_primitive_with_utf8view    1.00      6.2±0.02µs        ? ?/sec    1.05      6.5±0.04µs        ? ?/sec
```


</p>
</details>

File: arrow-json/src/reader/tape.rs (hunk 1 above)
Comment (alamb) [reply arrow-json/src/reader/tape.rs:717]: For what it is worth, I think the current way this is encoded is quite understandable and will generate clear error messages. I double checked and it conforms to my reading of UTF-16 on https://en.wikipedia.org/wiki/UTF-16

File: arrow-json/src/reader/tape.rs [hunk 2]
```diff
@@ -951,4 +958,15 @@ mod tests {
         let err = decoder.finish().unwrap_err().to_string();
         assert_eq!(err, "Json error: Encountered truncated UTF-8 sequence");
     }
+
+    #[test]
+    fn test_invalid_surrogates() {
```
Comment (alamb) [inline arrow-json/src/reader/tape.rs:963]: I verified this test panic's on main:
```
attempt to subtract with overflow
thread 'reader::tape::tests::test_invalid_surrogates' panicked at arrow-json/src/reader/tape.rs:708:49:
attempt to subtract with overflow
```

And the test actually fails to detect an error in release mode 
```

---- reader::tape::tests::test_invalid_surrogates stdout ----

thread 'reader::tape::tests::test_invalid_surrogates' panicked at arrow-json/src/reader/tape.rs:959:9:
assertion failed: res.is_err()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Review by alamb — APPROVED** [review]
Thank you @nicklan and @scovich  - this looks like a great change to me

**Comment by alamb** [comment]
If anything this seems faster than what is on main so it has a added bonus

**Comment by alamb** [comment]
Thanks again @nicklan and @scovich
