### PR TITLE
allocate enough bytes when writing booleans

### LINKED ISSUE #657: Writing Parquet with a boolean column fails
**Describe the bug**

When writing a parquet file with a boolean column I receive the error: `EOF: unable to put boolean value`.

**To Reproduce**

I don't yet have a minimal repro. For me I was writing batches of ~100k rows containing a uint64 column and a boolean column. The boolean column included null values.

**Expected behavior**

The boolean column to be correctly written.

**Additional context**

Based on debugging, I believe the problem may be the method used to extend the array:

```
            if bit_writer.bytes_written() + values.len() / 8 >= bit_writer.capacity() {
                bit_writer.extend(256);
            }
```

When my case fails, `values.len()` is 27054. I suspect that even *after* adding 256 bytes there isn't enough room for all of the values (256 bytes is 2048 bits). It would actually need to be extended with 3382 bytes to have enough capacity for all of those rows.

It should probably be extended with something like `min(256, values.len() / 8)` or `values.len() / 8` rounded up to a power of 2.

### PR DESCRIPTION
**Pull request by bjchambers**
# Which issue does this PR close?

Closes #657.

# Rationale for this change

Without this change, writing a batch with more than 2048 boolean values may fail to extend the bit vector enough.

# What changes are included in this PR?

* A test demonstrating the failure
* A change to allocate enough bytes for the boolean values being written
 
# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/data_type.rs [hunk 1]
```diff
@@ -674,7 +675,12 @@ pub(crate) mod private {
             bit_writer: &mut BitWriter,
         ) -> Result<()> {
             if bit_writer.bytes_written() + values.len() / 8 >= bit_writer.capacity() {
-                bit_writer.extend(256);
+                let bits_available =
+                    (bit_writer.capacity() - bit_writer.bytes_written()) * 8;
+                let bits_needed = values.len() - bits_available;
+                let bytes_needed = (bits_needed + 7) / 8;
+                let bytes_needed = round_upto_multiple_of_64(bytes_needed);
+                bit_writer.extend(bytes_needed);
```
Comment (alamb) [inline parquet/src/data_type.rs:683]: previously this extended by 256 bytes but now it will extend potentially by 64 byte chunks. Is that intentional? I wonder if  

```rust
                let bytes_needed = round_upto_multiple_of_64(bytes_needed) * 4;
```

Might be more appropriate / less of a behavior change?

**Review by alamb — APPROVED** [review]
Thank you @bjchambers 👍 . This looks good to me.

I also double checked the test case covers the bug. Without the code changes, it fails like this:

```
---- arrow::arrow_writer::tests::bool_large_single_column stdout ----
thread 'arrow::arrow_writer::tests::bool_large_single_column' panicked at 'called `Result::unwrap()` on an `Err` value: EOF("unable to put boolean value")', parquet/src/arrow/arrow_writer.rs:1224:39
```

I would like at least one other person to review this change too (perhaps @sunchao  or @nevi-me ) before we merge it

File: parquet/src/data_type.rs (hunk 1 above)
Comment (bjchambers) [reply parquet/src/data_type.rs:683]: Totally unintentional -- I wasn't sure what the desired growth pattern was beyond "it should grow by at least enough to hold everything". I'm happy to make a change like that, although it may be clearer to do `round_upto_power_of_2(bytes_needed, 256)`.

**Review by nevi-me — APPROVED** [review]
LGTM
