### PR TITLE
Fix RowSelection::intersection (#5036)

### LINKED ISSUE #5036: RowSelection::intersection Produces Invalid RowSelection
**Describe the bug**

An invariant of `RowSelection` is that it alternates select and skip, and does not contain empty `RowSelector`.

This is typically enforced when a RowSelection is created from a slice (or vec) of `RowSelector` by `from_selectors_and_combine`.

When intersect_row_selections was imported from DataFusion in https://github.com/apache/arrow-rs/pull/3047 and subsequently exposed as a member function in https://github.com/apache/arrow-rs/pull/3084/files#diff-7638a63d118da0ac5321c1948eb9acfc59f7acee56598879eba8338b2c22ff9eR334 a subtle bug was introduced.

`intersect_row_selections` does not produce a `Vec<RowSelector>` that obey the invariants of `RowSelection`, and yet the member function doesn't call `from_selectors_and_combine`.

This results in RowSelection of the form `[Skip(x), Skip(y)]`. The async reader determines what data to fetch based on what rows are selected, however, when reading the data it performs each operation in turn. In order to perform the first skip, the reader must set up the decoders to the relevant position within the pages (as it doesn't know that the next operation is another skip). This in turn causes it to request data that wasn't fetched, and the reader bails out with an offset index error.

**To Reproduce**

```
#[test]
fn test_intersection() {
    let selection = RowSelection::from(vec![RowSelector::select(1048576)]);
    let result = selection.intersection(&selection);
    assert_eq!(result, selection);
}
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #5036

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: parquet/src/arrow/arrow_reader/selection.rs [hunk 1]
```diff
@@ -64,25 +64,30 @@ impl RowSelector {
...
 /// ];
 ///
 /// let actual: Vec<RowSelector> = selection.into();
 /// assert_eq!(actual, expected);
 /// ```
 ///
+/// A [`RowSelection`] maintains the following invariants:
+///
+/// * It contains no [`RowSelector`] of 0 rows
+/// * Consecutive [`RowSelector`] alternate whether they skip or select rows
```
Comment (alamb) [inline parquet/src/arrow/arrow_reader/selection.rs:89]:
```suggestion
/// * Consecutive [`RowSelector`]s alternate skipping or selecting rows.
```

File: parquet/src/arrow/arrow_reader/selection.rs [hunk 2]
```diff
@@ -443,7 +417,36 @@ impl RowSelection {
...
+        if let Some(x) = filtered.next() {
+            selectors.push(x);
+        }
+
+        for s in filtered {
+            if s.row_count == 0 {
+                continue;
+            }
+
+            let last = selectors.last_mut().unwrap();
```
Comment (alamb) [inline parquet/src/arrow/arrow_reader/selection.rs:441]:
```suggestion
            // Combine adjacent skip/non-skip
            let last = selectors.last_mut().unwrap();
```

File: parquet/src/arrow/arrow_reader/selection.rs [hunk 3]
```diff
@@ -118,10 +123,13 @@ impl RowSelection {
         let mut last_end = 0;
         for range in ranges {
             let len = range.end - range.start;
+            if len == 0 {
```
Comment (alamb) [inline parquet/src/arrow/arrow_reader/selection.rs:126]: Is this the actual bug fix? It also looks like `from_selectors_and_combine` didn't remove zero length `RowSelector`s

File: parquet/src/arrow/arrow_reader/selection.rs [hunk 4]
```diff
@@ -465,64 +468,58 @@ impl From<RowSelection> for VecDeque<RowSelector> {
...
-                    res.push(RowSelector::skip(a.row_count));
-                    b.row_count -= a.row_count;
-                    l_iter.next().unwrap();
-                } else {
-                    res.push(RowSelector::skip(b.row_count));
-                    a.row_count -= b.row_count;
+                (_, Some(b)) if b.row_count == 0 => {
                     r_iter.next().unwrap();
                 }
+                (Some(a), Some(b)) => {
```
Comment (alamb) [inline parquet/src/arrow/arrow_reader/selection.rs:487]: I found the switch from `l,r` to `a,b` confusing -- can we use one consistently throughout this function? Either would be better than a mix

File: parquet/src/arrow/arrow_reader/selection.rs [hunk 5]
```diff
@@ -465,64 +468,58 @@ impl From<RowSelection> for VecDeque<RowSelector> {
...
-
-    if l_iter.peek().is_some() {
-        res.extend(l_iter);
-    }
-    if r_iter.peek().is_some() {
-        res.extend(r_iter);
-    }
-    res
-}
+    });
```
Comment (alamb) [inline parquet/src/arrow/arrow_reader/selection.rs:520]: I reviewed this logic carefully -- it is very cool

**Review by alamb — APPROVED** [review]
Thank you @tustvold  -- this is very nice.

> An invariant of RowSelection is that it alternates select and skip, and does not contain empty RowSelector.

I like how you have added documenting this assumption now. Can you explain where this assumption is used in the code?

cc @Ted-Jiang

File: parquet/src/arrow/arrow_reader/selection.rs (hunk 3 above)
Comment (tustvold) [reply parquet/src/arrow/arrow_reader/selection.rs:126]: It is part of it, the other part is actually invoking the from_selectors_and_combine logic whilst performing an intersection

**Comment by alamb** [comment]
> > Can you explain where this assumption is used in the code
> 
> From the linked ticket #5036
> 
> > The async reader determines what data to fetch based on what rows are selected, however, when reading the data it performs each operation in turn. In order to perform the first skip, the reader must set up the decoders to the relevant position within the pages (as it doesn't know that the next operation is another skip). This in turn causes it to request data that wasn't fetched, and the reader bails out with an offset index error.

I see -- so another potential fix would be to ignore zero length selections in the reader. I am not saying we should do this, only observing it might be a possiblility

**Comment by tustvold** [comment]
> ignore zero length selections in the reader

That would only half fix the problem, as if you have two consecutive skip, you will have the same problem

**Review by Ted-Jiang — APPROVED** [review]
👍
