### PR TITLE
Fix bug in page skipping

### LINKED ISSUE #2543: Panic when first data page is skipped using ColumnChunkData::Sparse
**Describe the bug**

If you have a row selection which skips the first data page, `SerializedPageReader` will error incorrectly. 

**To Reproduce**

Create a `ParquetRecordBatchStream` using a `RowFilter` that skips the first page in any column. 

**Expected behavior**

This should work.

**Additional context**

In `GenericColumnReader::has_next`, when `num_buffered_value` is 0, we call `GenericColumnReader::read_new_page`. In `GenericRecordReader::skip_records` we have to check if we are at the end of the column, this will always read the first data page. In cases where the selection skips that page, it will not be fetched so we get an error.

### PR DESCRIPTION
**Pull request by thinkharderdev**
# Which issue does this PR close?

Closes #2543 

# Rationale for this change
 

Discovered some small bugs while testing the page pruning logic in `ParquetRecordBatchStream`. We were improperly reading data pages when not necessary in a few cases. When we have only fetched the pages required for a given row selection this causes an error. 

# What changes are included in this PR?

We had a method `GenericColumnReader::has_next` which will check if the current page is fully decoded and then load the next page (if it exists). This method was used in a few places to test whether the column was exhausted. This can cause issues since it will load the next page, which may be skipped according to the current row selection. 

Added a method `GenericColumnReader::has_next` which will test whether the column is exhausted without loading the next page and changed a few places to use that. 

I think a slightly more thorough refactor is not a bad idea since the API is a bit confusing as is, but this should solve the immediate bugs. 

# Are there any user-facing changes?

No

### CODE REVIEW

File: arrow/src/json/reader.rs [hunk 1]
```diff
@@ -2623,7 +2623,7 @@ mod tests {
         let re = builder.build(Cursor::new(json_content));
         assert_eq!(
             re.err().unwrap().to_string(),
-            r#"Json error: Expected JSON record to be an object, found Array [Number(1), String("hello")]"#,
+            r#"Json error: Expected JSON record to be an object, found Array([Number(1), String("hello")])"#,
```
Comment (thinkharderdev) [inline arrow/src/json/reader.rs:2626]: Not sure what this is about but this test was failing for me so I fixed it

File: parquet/src/arrow/record_reader/mod.rs [hunk 2]
```diff
@@ -135,7 +135,11 @@ where
         loop {
             // Try to find some records from buffers that has been read into memory
             // but not counted as seen records.
-            let end_of_column = !self.column_reader.as_mut().unwrap().has_next()?;
+
+            // Check to see if the column is exhausted. Only peek the next page since in
+            // case we are reading to a page boundary and do not actually need to read
+            // the next page.
+            let end_of_column = !self.column_reader.as_mut().unwrap().peek_next()?;
```
Comment (thinkharderdev) [inline parquet/src/arrow/record_reader/mod.rs:142]: I think this should ultimately get cleaned up a bit. It is confusing since we need to `peek_next` but also call `has_next` below (since the next page needs to get loaded). It feels like the page-level logic wants to be encapsulated inside `GenericColumnReader` but it inevitable leaks out in places like this.

**Comment by thinkharderdev** [comment]
@Ted-Jiang @tustvold

**Comment by tustvold** [comment]
Not a fully formed thought, but perhaps we could avoid the has_next check by breaking if reading the next batch returns fewer than the expected number of rows?

File: parquet/src/arrow/arrow_reader/selection.rs [hunk 3]
```diff
@@ -595,5 +595,24 @@ mod tests {
 
         // assert_eq!(mask, vec![false, true, true, false, true, true, true]);
         assert_eq!(ranges, vec![10..20, 20..30, 40..50, 50..60, 60..70]);
+
+        let selection = RowSelection::from(vec![
+            // Skip first page
+            RowSelector::skip(10),
+            // Multiple selects in same page
+            RowSelector::select(3),
```
Comment (Ted-Jiang) [inline parquet/src/arrow/arrow_reader/selection.rs:603]: I run this test without this pr change, still passed🤔

Comment (thinkharderdev) [reply parquet/src/arrow/arrow_reader/selection.rs:603]: Yeah, this test is actually unrelated to the fix. I originally thought the bug was in the `scan_ranges` so I added this test. But it turned out to be unrelated and I figured I might as well leave another unit test in. Sorry for the confusion :)

**Comment by thinkharderdev** [comment]
Was testing with this fix and ran into another bug along similar lines. Not sure what is causing it just yet but I think we need to take a more holistic look at this.

**Comment by thinkharderdev** [comment]
> Was testing with this fix and ran into another bug along similar lines. Not sure what is causing it just yet but I think we need to take a more holistic look at this.

Sorry guys, got a bit distracted with other things. I think the latest commit should fix the last bug I could find. I've run this against some fairly large datasets and not seen any more issues so I think it should be good to go.

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
This appears to be failing on master - https://github.com/apache/arrow-rs/runs/8193393646?check_suite_focus=true could you possibly take a look?

**Comment by thinkharderdev** [comment]
> This appears to be failing on master - https://github.com/apache/arrow-rs/runs/8193393646?check_suite_focus=true could you possibly take a look?

Will do
