### PR TITLE
Enhance Date64 type documentation

### LINKED ISSUE #5288: Confusion over Date64 array values
**Which part is this question about**

Date64 array values.

**Describe your question**

Docs for Date64 type states:

https://github.com/apache/arrow-rs/blob/a61e824abdd7b38ea214828480430ff2a13f2ead/arrow-schema/src/datatype.rs#L150-L152

- Mirrored by `Schema.fbs` docs: https://github.com/apache/arrow/blob/37a8bf04bc713858a5b247d4424c1e8505e61947/format/Schema.fbs#L245-L253

> Values are evenly divisible by 86400000

This seems to suggest that Date64 should NOT store time, and should only represent days since UNIX epoch, akin to Date32 (but as milliseconds, not days).

What is the point of Date64 type, then? It would be the same as Date32 but multiplied by 86400000 **assuming it's used according to spec**.

The bold is important, as there are examples where you can set values that are not evenly divisible by the factor, and the printing code even shows the time as well:

https://github.com/apache/arrow-rs/blob/a61e824abdd7b38ea214828480430ff2a13f2ead/arrow-cast/src/pretty.rs#L476-L487

The C++ implementation seems to have a validate function, see https://github.com/apache/arrow/pull/12014

But I can still set 'invalid' values via PyArrow as this full validation is optional:

```python
>>> import pyarrow as pa
>>> days = pa.array([0, 1, 2], type=pa.date64())
>>> days
<pyarrow.lib.Date64Array object at 0x7f6810ecba60>
[
  1970-01-01,
  1970-01-01,
  1970-01-01
]
>>> days.validate()
>>> days.validate(full=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 1630, in pyarrow.lib.Array.validate
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: date64[ms] 1 does not represent a whole number of days
>>>
```

So I'm just wondering, even if we implement some sort of validation on these values (there is this old issue on the arrow repo: https://github.com/apache/arrow/issues/26853), if this is not made mandatory, then what is the point of having that restriction on Date64 type?

Do we need to implement this optional validation on arrow-rs too, and also fix the print code to not show the time for Date64? Or just embrace that Date64 will also store time, contrary to the docs (both in arrow-rs and the official arrow repo)?

**Additional context**

This might be a wider arrow discussion, I'm not sure if it's been had before, feel free to link if so.

Came across this whilst looking into https://github.com/apache/arrow-rs/issues/5266

As I wasn't sure, given the case of a Date64 array, whether extracting the millisecond part should always return 0 (assuming the array contains valid values) or should return the actual milliseconds part (though that would technically mean the  value is invalid?)

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5288

# Rationale for this change
 

# What changes are included in this PR?

Update docs of Date64 to hopefully clear up any confusion on its details.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Jefffrey** [comment]
I think doc update is sufficient to close the issue, can add in optional validation later if there is a use case for it

File: arrow-schema/src/datatype.rs [hunk 1]
```diff
@@ -145,10 +145,30 @@ pub enum DataType {
...
+    ///
+    /// According to the specification (see [Schema.fbs]), this should be treated as the number of
+    /// days, in milliseconds, since the UNIX epoch. Therefore, values must be evenly divisible by
+    /// `86_400_000` (the number of milliseconds in a standard day).
+    ///
+    /// The reason for this is historically for compatibility with other languages native libraries,
+    /// such as Java when it used to store dates as timestamps.
+    ///
+    /// Practically, validation that values of this type are evenly divisible by `86_400_000` is not enforced
+    /// by this library for performance and usability reasons. Date64 values will be treated similar to the
```
Comment (tustvold) [inline arrow-schema/src/datatype.rs:161]:
```suggestion
    /// by this library for performance and usability reasons. Date64 values will be treated similarly to the
```

File: arrow-schema/src/datatype.rs [hunk 2]
```diff
@@ -145,10 +145,30 @@ pub enum DataType {
...
     Date32,
     /// A signed 64-bit date representing the elapsed time since UNIX epoch (1970-01-01)
-    /// in milliseconds (64 bits). Values are evenly divisible by 86400000.
+    /// in milliseconds.
+    ///
+    /// According to the specification (see [Schema.fbs]), this should be treated as the number of
+    /// days, in milliseconds, since the UNIX epoch. Therefore, values must be evenly divisible by
+    /// `86_400_000` (the number of milliseconds in a standard day).
+    ///
+    /// The reason for this is historically for compatibility with other languages native libraries,
```
Comment (tustvold) [inline arrow-schema/src/datatype.rs:157]:
```suggestion
    /// The reason for this is for compatibility with other language's native libraries,
```

File: arrow-schema/src/datatype.rs [hunk 3]
```diff
@@ -145,10 +145,30 @@ pub enum DataType {
...
+    /// such as Java when it used to store dates as timestamps.
```
Comment (tustvold) [inline arrow-schema/src/datatype.rs:158]:
```suggestion
    /// such as Java, which historically lacked a dedicated date type
    /// and only supported timestamps.
```

**Review by tustvold — APPROVED** [review]
Just some minor copy tweaks
