### PR TITLE
Fix reading of dictionary encoded pages with null values (#1111)

### LINKED ISSUE #1111: ArrowArrayReader Reads Too Many Values From Bit-Packed Runs
**Describe the bug**

Originally reported in https://github.com/apache/arrow-datafusion/issues/1441 and encountered again in #1110, `ParquetFileArrowReader` appears to read incorrect data for string columns that contain nulls.

In particular the conditions required are for the column to be nullable, contain nulls, and multiple row groups. 

**To Reproduce**

Read [simple_strings.parquet.zip](https://github.com/apache/arrow-rs/files/7793788/simple_strings.parquet.zip) with the following code

```
#[test]
    fn test_read_strings() {
        let testdata = arrow::util::test_util::parquet_test_data();
        let path = format!("{}/simple_strings.parquet", testdata);
        let parquet_file_reader =
            SerializedFileReader::try_from(File::open(&path).unwrap()).unwrap();
        let mut arrow_reader = ParquetFileArrowReader::new(Arc::new(parquet_file_reader));
        let record_batch_reader = arrow_reader
            .get_record_reader(60)
            .expect("Failed to read into array!");

        let batches = record_batch_reader
            .collect::<arrow::error::Result<Vec<_>>>()
            .unwrap();

        assert_eq!(batches.len(), 1);
        let batch = batches.into_iter().next().unwrap();
        assert_eq!(batch.num_rows(), 6);

        let strings = batch
            .column(0)
            .as_any()
            .downcast_ref::<StringArray>()
            .unwrap();

        let strings: Vec<_> = strings.iter().collect();

        assert_eq!(
            &strings,
            &[
                None,
                Some("-1685637712"),
                Some("512814980"),
                Some("868743207"),
                None,
                Some("-1001940778")
            ]
        )
    }
```

Fails with

```
thread 'arrow::arrow_reader::tests::test_read_strings' panicked at 'assertion failed: `(left == right)`
  left: `[None, Some("-1685637712"), Some("512814980"), Some("-1685637712"), None, Some("868743207")]`,
 right: `[None, Some("-1685637712"), Some("512814980"), Some("868743207"), None, Some("-1001940778")]`', parquet/src/arrow/arrow_reader.rs:715:9
```

For comparison

```
$ python
> import duckdb
> duckdb.query("select * from 'simple_strings.parquet'").fetchall()
[(None,), ('-1685637712',), ('512814980',), ('868743207',), (None,), ('-1001940778',)]
```

The file consists of two row groups, each with 3 rows and was generated using #1110 

**Expected behavior**

The test should pass

### PR DESCRIPTION
**Pull request by yordan-pavlov**
# Which issue does this PR close?

Closes #1111.

# Rationale for this change
As explained in #1111 `RleDecoder` as used in `VariableLenDictionaryDecoder` as part of the implementation of `ArrowArrayReader`, incorrectly returns more keys than are actually available while at the same time, when the page contains NULLs `VariableLenDictionaryDecoder` is also requesting more keys than available because `num_values` is inclusive of NULLs. This then results in incorrectly decoding a dictionary-encoded page which also contains NULLs and returning more values than necessary.

# What changes are included in this PR?
This PR contains:
* a fix where the actual number of values (excluding NULLs) is calculated from def levels (if present) and is used (instead of `num_values` from the data page) when creating the value decoder, so that it knows how many values are actually available. This is then used in existing code in `VariableLenDictionaryDecoder` to limit how many keys are requested from the nested `RleDecoder`.
* a new test `test_arrow_array_reader_dict_enc_string` for `ArrowArrayReader`
* a new test `test_complex_array_reader_dict_enc_string` for `ArrayReader`

# Are there any user-facing changes?
No

@alamb @tustvold

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @yordan-pavlov  -- I plan to review / test this patch later today

**Comment by alamb** [comment]
FWIW I tested with datafusion on the case where we initially observed this issue and this patch fixes the issue: https://github.com/apache/arrow-datafusion/issues/1441#issuecomment-1004332824

File: parquet/src/arrow/arrow_array_reader.rs [hunk 1]
```diff
@@ -420,6 +456,24 @@ impl<'a, C: ArrayConverter + 'a> ArrowArrayReader<'a, C> {
         }
     }
 
+    fn count_def_level_values(
+        column_desc: &ColumnDescriptor,
+        level_decoder: crate::encodings::levels::LevelDecoder,
+        num_values: usize,
+    ) -> Result<usize> {
+        let mut def_level_decoder = LevelValueDecoder::new(level_decoder);
+        let def_level_array =
```
Comment (alamb) [inline parquet/src/arrow/arrow_array_reader.rs:465]: does this mean an entirely new array of definition levels is created for each column? Might this result in a non trivial amount of extra runtime overhead?

**Review by alamb — COMMENTED** [review]
Thank you so much @yordan-pavlov  -- as I mentioned, I verified that this change fixes the issues we had been seeing in DataFusion; 

The basic idea of this PR looks great and makes sense to me, but I am not comfortable enough with the implementation of the parquet reader to fully understand it.

I wonder if @tustvold, @sunchao  or @nevi-me  could have a look?

Also, I wonder if there are ay benchmark results to demonstrate the performance change related to this PR?

**Comment by yordan-pavlov** [comment]
> Also, I wonder if there are ay benchmark results to demonstrate the performance change related to this PR?

@alamb  there is a small (3% to 8% in my benchmark run) negative impact to performance from this change, see here: https://github.com/apache/arrow-rs/issues/1111#issuecomment-1003718555

File: parquet/src/arrow/arrow_array_reader.rs (hunk 1 above)
Comment (yordan-pavlov) [reply parquet/src/arrow/arrow_array_reader.rs:465]: Yes - def levels are decoded a second time for this fix and an i16 array and a boolean array are created to count the non-null values, but they only live for a very short time and the negative effect on performance is surprisingly small (3% to 8% in my benchmark run) see here: https://github.com/apache/arrow-rs/issues/1111#issuecomment-1003718555 ; even after this change the `ArrowArrayReader` is still often several times faster for decoding strings compared to the old `ArrayReader`, this hasn't changed much.

It's probably possible to make this more efficient, but it would require more thinking and more time for a bigger change.

**Comment by tustvold** [comment]
Thank you for this :tada:. I will take a look today if I have time

File: parquet/src/arrow/arrow_array_reader.rs (hunk 1 above)
Comment (alamb) [reply parquet/src/arrow/arrow_array_reader.rs:465]: makes sense -- thank you for running the numbers

File: parquet/src/arrow/arrow_array_reader.rs [hunk 2]
```diff
@@ -398,19 +416,37 @@ impl<'a, C: ArrayConverter + 'a> ArrowArrayReader<'a, C> {
                             offset,
                             def_levels_byte_len,
                         );
+                        let value_count = Self::count_def_level_values(
```
Comment (tustvold) [inline parquet/src/arrow/arrow_array_reader.rs:419]: You might be able to do `num_values - num_nulls` here as the DataPageV2 has this information. Unfortunately very few implementations in practice seem to produce such pages...

**Review by tustvold — COMMENTED** [review]
This change makes sense to me, and seems like a pragmatic quick fix for the bug :+1:

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @yordan-pavlov
