### PR TITLE
Accept parquet schemas without explicitly required Map keys

### LINKED ISSUE #5606: Cannot read Parquet files that do not specify Map keys as required
**Describe the bug**

The [Parquet Format](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#maps) specifies that:
> The `key` field encodes the map's key type. This field must have repetition `required` and must always be present.

I.e. 

```
<map-repetition> group <name> (MAP) {
  repeated group key_value {
    required <key-type> key;
    <value-repetition> <value-type> value;
  }
}
```

However, most implementations of the format do not appear to enforce this in the Thrift schema, and producers such as Hive/Spark/Presto/Trino/AWS Athena do not produce Parquet files like this. A huge number of such files are widely found on data lakes everywhere, and rewriting such files in order to comply with this does not seem feasable.

**To Reproduce**

```rs
        let url_str = "https://overturemaps-us-west-2.s3.us-west-2.amazonaws.com/release/2023-07-26-alpha.0/theme%3Dtransportation/type%3Dconnector/20230726_134827_00007_dg6b6_01b086fc-f35b-487c-8d4e-5cdbbdc1785d";
        let url = Url::parse(url_str).unwrap();
        let storage_container = Arc::new(HttpBuilder::new().with_url(url).build().unwrap());
        let location = Path::from("");
        let meta = storage_container.head(&location).await.unwrap();
        let mut reader = ParquetObjectReader::new(storage_container, meta);

        // Parquet schema can be printed
        let mut p_metadata = reader.get_metadata().await.unwrap();
        print_schema(&mut std::io::stdout(), p_metadata.file_metadata().schema());

        // Metadata cannot be loaded
        let metadata = ArrowReaderMetadata::load_async(&mut reader, Default::default())
            .await
            .unwrap();
```

Results in:

```
thread 'main' panicked at src/main.rs:79:10:
called `Result::unwrap()` on an `Err` value: ArrowError("Map keys must be required")
```

**Expected behavior**

Map keys are assumed to be required, regardless of explicit specification in the Thrift schema, and data is read accordingly.

**Additional context**

This has come up in a PyArrow issue: https://github.com/apache/arrow/issues/37389
Enforced here: https://github.com/apache/arrow-rs/blob/9fda7eab0c9fb55c90194865ca921c094b78dae9/parquet/src/arrow/schema/complex.rs#L289-L291

### PR DESCRIPTION
**Pull request by jupiter**
# Which issue does this PR close?

Closes #5606.

# Rationale for this change
 
The check is superfluous and restricts reading of a huge number of files produced without Map keys explicitly marked as required.

# What changes are included in this PR?

Reduces the check to only error on a value that would have to have been explicitly set to an invalid value.

# Are there any user-facing changes?

None found

### CODE REVIEW

**Comment by tustvold** [comment]
Can we add a test for this, I suspect the dremel shredding will not work correctly with just this change

**Comment by jupiter** [comment]
I've ensured that the field will always be non-nullable in Arrow, and added a test in the module, following the same pattern as other schema conversions. 

I can can provide a test file, but not sure how integration tests are written, and I'm not seeing any reference to the the files, other than in the Readme. Should I just add the file 'parquet-testing/data' and add an entry in the Readme?

**Comment by tustvold** [comment]
https://github.com/apache/parquet-testing/pull/45/files would be a good example

**Comment by jupiter** [comment]
Also see https://github.com/apache/parquet-testing/pull/47#issuecomment-2056584342

**Comment by tustvold** [comment]
I would like to see if we can get https://github.com/apache/parquet-testing/pull/47 in first so that we can get a full end-to-end test here. If things drag out though we can move ahead as is

**Comment by tustvold** [comment]
https://github.com/apache/parquet-testing/pull/47 was merged last week, so I think it should just be a case of updating this PR with an integration test based off that

**Comment by jupiter** [comment]
How does that look? I've added a test in what I think is an appropriate place, with similar tests. Let me know if there's something specific we should add to the test.

File: parquet/src/arrow/arrow_reader/mod.rs [hunk 1]
```diff
@@ -1436,6 +1436,35 @@ mod tests {
...
+                        Field::new("key", ArrowDataType::Utf8, false),
+                        Field::new("value", ArrowDataType::Utf8, true),
+                    ])),
+                    false,
+                )),
+                false.into(),
+            ),
+            true,
+        )]));
+        assert_eq!(batch.schema().as_ref(), &expected_schema);
```
Comment (tustvold) [inline parquet/src/arrow/arrow_reader/mod.rs:1465]: Could we perhaps check that the data is what we expect to be encoded in this file?

Comment (jupiter) [reply parquet/src/arrow/arrow_reader/mod.rs:1465]: I looked at this test for guidance on testing map data, but looks like it's not testing data: https://github.com/apache/arrow-rs/blob/08af4710fcd2b56a7624db9b9d97e6715a952cb0/parquet/src/arrow/arrow_reader/mod.rs#L2081-L2090

This worked apart from `MapArray::new_from_strings()` having hardcoded `keys` and `values` instead of `key` and `value`:
```rs
        assert_eq!(
            *batch.column(0).as_map(),
            MapArray::new_from_strings(
                vec!["parent", "name"].into_iter(),
                StringArray::from(vec!["another", "report"]).get().0,
                &[0, 2]
            )
            .unwrap()
        );
```

I could copy the implementation of `MapArray::new_from_strings()`, what do you think? Should I use another module like 'pretty'?

**Review by Jefffrey — COMMENTED** [review]
You'll need to bump the relevant submodule too in order to get that new test file

File: parquet/src/arrow/arrow_reader/mod.rs (hunk 1 above)
Comment (Jefffrey) [reply parquet/src/arrow/arrow_reader/mod.rs:1465]: Could perhaps build the expected MapArray using MapBuilder which allows specifying custom names?

https://github.com/apache/arrow-rs/blob/08af4710fcd2b56a7624db9b9d97e6715a952cb0/arrow-array/src/builder/map_builder.rs#L69-L93

Or maybe just extract the relevant values from the actual MapArray for comparison since it's such a small array :thinking:

Comment (jupiter) [reply parquet/src/arrow/arrow_reader/mod.rs:1465]: Thanks. Just comparing the keys and values now.

File: parquet/src/arrow/schema/complex.rs [hunk 2]
```diff
@@ -286,8 +286,8 @@ impl Visitor {
         let map_key = &map_key_value.get_fields()[0];
         let map_value = &map_key_value.get_fields()[1];
 
-        if map_key.get_basic_info().repetition() != Repetition::REQUIRED {
-            return Err(arrow_err!("Map keys must be required"));
+        if map_key.get_basic_info().repetition() == Repetition::REPEATED {
```
Comment (Jefffrey) [inline parquet/src/arrow/schema/complex.rs:289]: Maybe we can add a comment here to explain why this check is relaxed?

e.g.

```rust
// Relax check which expects key to have repetition REQUIRED as there exists
// parquet writers and files which do not conform to this standard.
// This allows us to consume a broader range of existing files even if they are
// out of spec.
```

**Review by Jefffrey — COMMENTED** [review]
I think just need to fix clippy then should be good to go?

**Review by Jefffrey — APPROVED** [review]

**Comment by tustvold** [comment]
Thank you for sticking with this :+1:
