### PR TITLE
Arrow Arithmetic: Subtract timestamps

### LINKED ISSUE #3964: Subtracting `Timestamp` from `Timestamp`  should produce a `Duration` (not `Timestamp`)
**Describe the bug**
Subtracting two `Timestamp` columns results in another Timestamp which is not correct

**To Reproduce**

```rust
fn subtract_timestamps() {
    let arr1 = TimestampNanosecondArray::from(vec![
        1_000,
        1_000_000,
        1_000_000_000,
        1_000_000_000_000,
        1_000_000_000_000_000,
        1_000_000_000_000_000_000,
    ]);

    let arr2 = TimestampNanosecondArray::from(vec![
        2_000,
        2_000_000,
        2_000_000_000,
        2_000_000_000_000,
        2_000_000_000_000_000,
        2_000_000_000_000_000_000,
    ]);

    println!(
        "input:\n{}\n{}",
        pretty_format_columns("arr1", &[Arc::new(arr1.clone()) as _]).unwrap(),
        pretty_format_columns("arr2", &[Arc::new(arr2.clone()) as _]).unwrap(),
    );

    let interval = subtract_dyn(&arr2, &arr1).unwrap();

    println!(
        "output{}:\n{}",
        interval.data_type(),
        pretty_format_columns("interval", &[Arc::new(interval.clone()) as _]).unwrap(),
    );
}
```

Which produces

```
input:
+----------------------------+
| arr1                       |
+----------------------------+
| 1970-01-01T00:00:00.000001 |
| 1970-01-01T00:00:00.001    |
| 1970-01-01T00:00:01        |
| 1970-01-01T00:16:40        |
| 1970-01-12T13:46:40        |
| 2001-09-09T01:46:40        |
+----------------------------+
+----------------------------+
| arr2                       |
+----------------------------+
| 1970-01-01T00:00:00.000002 |
| 1970-01-01T00:00:00.002    |
| 1970-01-01T00:00:02        |
| 1970-01-01T00:33:20        |
| 1970-01-24T03:33:20        |
| 2033-05-18T03:33:20        |
+----------------------------+
output Timestamp(Nanosecond, None):
+----------------------------+
| interval                   |
+----------------------------+
| 1970-01-01T00:00:00.000001 |
| 1970-01-01T00:00:00.001    |
| 1970-01-01T00:00:01        |
| 1970-01-01T00:16:40        |
| 1970-01-12T13:46:40        |
| 2001-09-09T01:46:40        |
+----------------------------+
```

**Expected behavior**
~I expect the output to be an interval of type `Interval(MonthDayNano)` (not Timestamp)~

Updated (after discussion with @tustvold ) I expect the output to be a duration of type `Duration(unit)` where `unit` is the same as the source `Timestamp(unit)` (not Timestamp) 

**Additional context**
Here is what postgres does:

```sql
postgres=# create table test as select now() - now();
SELECT 1
postgres=# \d test
                 Table "public.test"
  Column  |   Type   | Collation | Nullable | Default
----------+----------+-----------+----------+---------
 ?column? | interval |           |          |

postgres=#
```

### PR DESCRIPTION
**Pull request by mr-brobot**
# Which issue does this PR close?

Closes #3964 

# Rationale for this change
 

See #3964 

# What changes are included in this PR?

`subtract_dyn` and `subtract_dyn_checked` now support subtracting timestamps of the same resolution. The result is a duration of the same resolution as the timestamp operands.

# Are there any user-facing changes?

Expanded timestamp support for `subtract_dyn` and `subtract_dyn_checked`.

### CODE REVIEW

File: arrow-arith/src/arithmetic.rs [hunk 1]
```diff
@@ -4649,4 +4731,144 @@ mod tests {
         ]);
         assert_eq!(&expected, result);
     }
+
+    #[test]
+    fn test_timestamp_second_subtract_timestamp() {
```
Comment (tustvold) [inline arrow-arith/src/arithmetic.rs:4736]: I wonder if we could extract a generic function typed on the timestamp and duration types, this would avoid the duplication?

**Comment by tustvold** [comment]
> Subtracting timestamps of different resolutions is not supported

I think this is fine, we don't provide arithmetic between different integer precisions either - I think the responsibility is on the query engine to add type coercion logic where necessary :+1:

File: arrow-arith/src/arithmetic.rs [hunk 2]
```diff
@@ -1096,13 +1096,18 @@ pub fn subtract_dyn(left: &dyn Array, right: &dyn Array) -> Result<ArrayRef, Arr
                     let res = math_checked_op(l, r, TimestampSecondType::subtract_month_day_nano)?;
                     Ok(Arc::new(res.with_timezone_opt(l.timezone())))
                 }
+                DataType::Timestamp(TimeUnit::Second, _) => {
+                    let r = right.as_primitive::<TimestampSecondType>();
+                    let op = <TimestampSecondType as ArrowPrimitiveType>::Native::wrapping_sub;
+                    let res: PrimitiveArray<DurationSecondType> = binary(l, r, op)?;
```
Comment (tustvold) [inline arrow-arith/src/arithmetic.rs:1102]:
```suggestion
                    let res: PrimitiveArray<DurationSecondType> = binary(l, r, |a, b| a.wrapping_sub(b))?;
```
Perhaps?
