### PR TITLE
fix: decimal conversion looses value on lower precision

### LINKED ISSUE #6833: Casting Decimal128 to Decimal128 with smaller precision produces incorrect results in some cases
**Describe the bug**

If I try and cast floating-point value `12345.67` to `decimal(6,2)` then I get an error, as expected:

```
"1234567 is too large to store in a Decimal128 of precision 6. Max is 999999"
```

However, if I try and cast a `decimal(24,2)` value of  `12345.67` to `decimal(6,2)` then I do not get an error but instead have an invalid decimal value.

```
PrimitiveArray<Decimal128(6, 2)>
[
    1234567,
]
```

If I then convert this decimal to a string, it produces `1234.56` instead of `12345.67`

```
StringArray
[
  "1234.56",
]
```

**To Reproduce**

**Expected behavior**

**Additional context**

This is the root cause of https://github.com/apache/datafusion/issues/13492

### PR DESCRIPTION
**Pull request by himadripal**
# Which issue does this PR close?
Closes #6833 

Closes #.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by himadripal** [comment]
@andygrove @viirya @alamb please take a look.

File: arrow-cast/src/cast/decimal.rs [hunk 1]
```diff
@@ -112,8 +112,19 @@ where
     };
 
     Ok(match cast_options.safe {
```
Comment (andygrove) [inline arrow-cast/src/cast/decimal.rs:114]: It seems strange to `match` on a boolean rather than just using an `if` statement. I know this is how the existing code was, but perhaps we could improve this while we are here.

**Review by andygrove — APPROVED** [review]
LGTM. The logic now matches the logic in `cast_floating_point_to_decimal128`. Thanks @himadripal

File: arrow-cast/src/cast/mod.rs [hunk 2]
```diff
@@ -9827,4 +9827,72 @@ mod tests {
...
+        let input_type = DataType::Decimal128(24, 2);
+        let output_type = DataType::Decimal128(6, 2);
+        assert!(can_cast_types(&input_type, &output_type));
+        let mut options = CastOptions::default();
+        options.safe = false;
+
+        let result = cast_with_options(&array, &output_type, &options);
+
+        assert_eq!(result.unwrap_err().to_string(),
+                   "InvalidArgumentError(123456789 is too large to store in a Decimal128 of precision 6. Max is 999999)");
```
Comment (andygrove) [inline arrow-cast/src/cast/mod.rs:9845]: The error message format needs updating:

```
  left: "Invalid argument error: 123456789 is too large to store in a Decimal256 of precision 6. Max is 999999"
 right: "InvalidArgumentError(123456789 is too large to store in a Decimal256 of precision 6. Max is 999999)"
```

**Comment by andygrove** [comment]
There is a regression in `test_cast_decimal128_to_decimal256_negative`. The new validation check is correctly throwing an error, but it looks like we also need to add this validation when creating decimal arrays since the current test is creating invalid arrays before the cast:

```rust
let array = vec![Some(i128::MAX), Some(i128::MIN)];
let input_decimal_array = create_decimal_array(array, 10, 3).unwrap();
```

I would expect this to fail, so we probably need to add the same validation there.

**Comment by andygrove** [comment]
> There is a regression in `test_cast_decimal128_to_decimal256_negative`. The new validation check is correctly throwing an error, but it looks like we also need to add this validation when creating decimal arrays since the current test is creating invalid arrays before the cast:
> 
> ```rust
> let array = vec![Some(i128::MAX), Some(i128::MIN)];
> let input_decimal_array = create_decimal_array(array, 10, 3).unwrap();
> ```
> 
> I would expect this to fail, so we probably need to add the same validation there.

On second thoughts, it seems it was an intentional design decision not to validate this on array creation. Instead, an `array.validate_decimal_precision` method can optionally be called on the array to validate it aft er creation, so we should probably just update the test as needed (@alamb @tustvold perhaps you could correct me if I am wrong about this).

**Review by tustvold — COMMENTED** [review]
Have we run any benchmarks (I'm not sure if any actually exist) to confirm this doesn't significantly regress performance.

It seems unfortunate to be always performing overflow checks, when in many cases it should be possible to prove that precision overflow can't occur and need not be checked for

File: arrow-cast/src/cast/decimal.rs [hunk 3]
```diff
@@ -156,19 +179,9 @@ where
     T::Native: DecimalCast + ArrowNativeTypeOp,
 {
     let array: PrimitiveArray<T> = match input_scale.cmp(&output_scale) {
```
Comment (tustvold) [inline arrow-cast/src/cast/decimal.rs:181]: This could be changed to `<=`

File: arrow-cast/src/cast/decimal.rs [hunk 4]
```diff
@@ -112,8 +112,19 @@ where
...
+        true => {
+            array.unary_opt(|x| {
+                 f(x).filter(|v| O::is_valid_decimal_precision(*v, output_precision))
+            })
+        }
+        false => {
+            array.try_unary(|x| {
+                f(x).ok_or_else(|| error(x))
+                    .and_then(|v|{
+                        O:: validate_decimal_precision(v, output_precision).map(|_| v)
```
Comment (findepi) [inline arrow-cast/src/cast/decimal.rs:124]: Why not do this when computing the value (the code above), and only when this can fail?
(for example widening precision cannot fail, so no need to spend cycles on validating the produced values)

**Comment by andygrove** [comment]
> Have we run any benchmarks (I'm not sure if any actually exist) to confirm this doesn't significantly regress performance.
> 
> It seems unfortunate to be always performing overflow checks, when in many cases it should be possible to prove that precision overflow can't occur and need not be checked for

I'll create a separate PR (probably tomorrow) to add some criterion benchmarks

File: arrow-cast/src/cast/decimal.rs (hunk 4 above)
Comment (himadripal) [reply arrow-cast/src/cast/decimal.rs]: I thought about it, but then there are other examples where is it done this way, so kept it there. We can also do this as part of first error check point - inside this method 
```rust 
let error = cast_decimal_to_decimal_error::<I, O>(output_precision, output_scale);
```

**Comment by himadripal** [comment]
> > There is a regression in `test_cast_decimal128_to_decimal256_negative`. The new validation check is correctly throwing an error, but it looks like we also need to add this validation when creating decimal arrays since the current test is creating invalid arrays before the cast:
> > ```rust
> > let array = vec![Some(i128::MAX), Some(i128::MIN)];
> > let input_decimal_array = create_decimal_array(array, 10, 3).unwrap();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would expect this to fail, so we probably need to add the same validation there.
> 
> On second thoughts, it seems it was an intentional design decision not to validate this on array creation. Instead, an `array.validate_decimal_precision` method can optionally be called on the array to validate it after creation, so we should probably just update the test as needed (@alamb @tustvold perhaps you could correct me if I am wrong about this).
Changed the test to pass.

File: arrow-cast/src/cast/decimal.rs [hunk 5]
```diff
@@ -155,28 +163,24 @@ where
...
-            input_scale,
-            output_precision,
-            output_scale,
-            cast_options,
-        )?,
-        Ordering::Less => {
-            // input_scale < output_scale
+    let array: PrimitiveArray<T> = if input_scale <= output_scale {
+            // input_scale <= output_scale
+            // the scale doesn't change, but precision may change and cause overflow
```
Comment (viirya) [inline arrow-cast/src/cast/decimal.rs:168]: Why don't we also check precision and skip `convert_to_bigger_or_equal_scale_decimal` if it won't overflow?

Comment (himadripal) [reply arrow-cast/src/cast/decimal.rs:168]: won't it still has to go through the `convert_to_bigger_or_equal_scale_decimal` to add the zero at the end for bigger precision conversion. IMO, we can only skip the call if precision is less and scales are equal. Please correct me here.

Comment (viirya) [reply arrow-cast/src/cast/decimal.rs:168]: Oh, sorry, I mean to skip the check added in this PR.

Comment (viirya) [reply arrow-cast/src/cast/decimal.rs:168]: For example, original code simply returns the original array for same scale. If the precision is bigger, I think we can still do that, no?

Comment (himadripal) [reply arrow-cast/src/cast/decimal.rs:168]: lets assume, we are converting this  `12345` from (5, 3) -> (6,3), then it need to be `123450` - if we do array.clone() - wondering how it will add the 0 at the end.

Comment (himadripal) [reply arrow-cast/src/cast/decimal.rs:168]: decimal.slt - I added this and this is the output. Not sure if this is correct output.
```sql
select arrow_typeof(cast(cast(1.23 as decimal(10,3)) as decimal(12,3))),
       cast(cast(1.23 as decimal(10,3)) as decimal(12,3));
----
Decimal128(12, 3) 1.23
```

Comment (viirya) [reply arrow-cast/src/cast/decimal.rs:168]: 12345 in (5, 3) is 12.345. When casting to (6, 3), it is still 12345, why it needs to be 123450? 123450 in (6, 3) is 123.45. If I understand it correctly.

Comment (himadripal) [reply arrow-cast/src/cast/decimal.rs:168]: Yes, you are right.  How to I get the input_precision to check against output_precision? fn signature only has output_precision

Comment (viirya) [reply arrow-cast/src/cast/decimal.rs:168]: Yea

Comment (himadripal) [reply arrow-cast/src/cast/decimal.rs:171]: Done. @viirya please check.

**Comment by andygrove** [comment]
> Have we run any benchmarks (I'm not sure if any actually exist) to confirm this doesn't significantly regress performance.
> 
> It seems unfortunate to be always performing overflow checks, when in many cases it should be possible to prove that precision overflow can't occur and need not be checked for

I created a simple benchmark for decimal casting in https://github.com/apache/arrow-rs/pull/6850.

Unsurprisingly, validating that the results are correct is slower than not validating the results.

## before

```
cast_decimal            time:   [45.281 ns 45.549 ns 45.871 ns]
```

## after (this PR)

```
cast_decimal            time:   [247.97 ns 248.78 ns 249.78 ns]
                        change: [+435.06% +439.47% +443.15%] (p = 0.00 < 0.05)
```

We currently have the config option of `safe` on or off:

```
pub struct CastOptions<'a> {
    /// how to handle cast failures, either return NULL (safe=true) or return ERR (safe=false)
    pub safe: bool,
```

So, yes, it is a performance regression, but the previous behavior was incorrect. This PR now makes this work as advertised. 

@tustvold Is there a use case we need to support for faster casts without validating results per the CastOptions?

**Comment by tustvold** [comment]
> @tustvold Is there a use case we need to support for faster casts without validating results per the CastOptions?

No, the cast should be checked, apologies if that wasn't clear, my concern was the PR as originally formulated blindly performed the checked conversion regardless of the input type. Given the whole purpose of tracking precision is to avoid overflow checks, it seemed a little off.

I'll try to find some time to take another look at this PR as from a quick scan this looks to have been addressed

**Review by tustvold — APPROVED** [review]
This is still overly pessimistic, for example, if I increase both the precision and scale by the same amount I shouldn't need to perform any checks.

However, the kernel is already fallible (try_unary/unary_opt vs unary) and so this kernel already won't be vectorizing properly, and so it isn't like we're regressing a highly optimised kernel here. 

I've therefore instead opted to file https://github.com/apache/arrow-rs/issues/6877 and if people care they can action it.
