### PR TITLE
Increase upper wait time to reduce flakyness of test

### LINKED ISSUE #2141: object_store unit test might be flaky
**Describe the bug**

Saw a object_store unit test failure in CI:

```
---- throttle::tests::delete_test stdout ----
thread 'throttle::tests::delete_test' panicked at '206.888913ms must be < than 200ms', object_store/src/throttle.rs:313:9
```

**To Reproduce**

https://github.com/apache/arrow-rs/runs/7475787343?check_suite_focus=true
https://github.com/apache/arrow-rs/runs/7476237155?check_suite_focus=true

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #2141.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
cc @alamb

**Review by tustvold — APPROVED** [review]

File: object_store/src/throttle.rs [hunk 1]
```diff
@@ -275,7 +275,7 @@ mod tests {
 
     macro_rules! assert_bounds {
         ($d:expr, $lower:expr) => {
-            assert_bounds!($d, $lower, $lower + 1);
+            assert_bounds!($d, $lower, $lower + 2);
```
Comment (alamb) [inline object_store/src/throttle.rs:278]: 👍  thank you @viirya
