### PR TITLE
Document parquet writer memory limiting (#5450)

### LINKED ISSUE #5450: AsyncArrowWriter doesn't limit underlying ArrowWriter to respect buffer-size
`AsyncArrowWriter` created with default `WriterProperties` will have a config of `DEFAULT_MAX_ROW_GROUP_SIZE = 1024 * 1024`

It means that underlying `ArrowWriter` won't flush to disk until it's reached. 
It leads to the incredible memory consumption, because it will cache up to `DEFAULT_MAX_ROW_GROUP_SIZE` (1048576 by default) and will ignore `buffer_capacity` config at all.

Because the flushing condition of sync writer is:

```rust
if in_progress.buffered_rows >= self.max_row_group_size {
    self.flush()?
}
```

**To Reproduce**
Try to write many large rows to parquet with `AsyncArrowWriter`, you will see the memory consumption doesn't respect buffer size.

UPD: MRE was created https://github.com/apache/arrow-rs/issues/5450#issuecomment-1973921969

**Expected behavior**
Perfectly, it should respect buffer config. 
I.e flush on either buffer size or max row group is reached.

But even if it's expected for some reason, documentation should clearly highlight that.

**Additional context**

Btw, why default is `1024 * 1024`? Like it's byte unites

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #5450

# Rationale for this change
 

# What changes are included in this PR?

This adds an example showing how to limit the growth of the buffers within the arrow writers. I debated exposing a setting to control this, but the way it would only ever be a best effort limit felt a little off. Making it explicit in the client implementation at least makes it very obvious how it behaves.

# Are there any user-facing changes?

### CODE REVIEW

File: parquet/src/arrow/async_writer/mod.rs [hunk 1]
```diff
@@ -69,6 +69,29 @@ use tokio::io::{AsyncWrite, AsyncWriteExt};
...
 /// The buffered data will be flushed to the writer provided by caller when the
 /// buffer's threshold is exceeded.
+///
+/// ## Memory Limiting
+///
+/// The nature of parquet forces buffering of an entire row group before it can be flushed
+/// to the underlying writer. This buffering may exceed the configured buffer size
+/// of [`AsyncArrowWriter`]. Memory usage can be limited by prematurely flushing the row group,
+/// although this will have implications for file size and query performance. See [ArrowWriter]
+/// for more information.
```
Comment (DDtKey) [inline parquet/src/arrow/async_writer/mod.rs:79]: Great to have this documented! Thanks!

Should we refer to this in instantiation methods? (`try_new(_with_options)`)

**Review by DDtKey — COMMENTED** [review]
I still think would be nice to have an additional config(or method) to "enforce flush on buffer size". To be able to encapsulate this logic for user's code 🤔

But it can be done/discussed separately ofc

**Comment by tustvold** [comment]
> I still think would be nice to have an additional config(or method) to "enforce flush on buffer size"

No objections from me, FWIW my conclusion from the investigation under https://github.com/apache/arrow-rs/issues/5458 is we should probably encourage people to move away from `AsyncWrite` in general

File: parquet/src/arrow/async_writer/mod.rs (hunk 1 above)
Comment (alamb) [reply parquet/src/arrow/async_writer/mod.rs:79]: I agree it would help -- perhaps something like `try_new` in `try_new/try_new_with_options`

```rust
/// Please see the documentation on [`Self`] for details on memory usage.

File: parquet/src/arrow/arrow_writer/mod.rs [hunk 2]
```diff
@@ -80,6 +80,32 @@ mod levels;
 ///
 /// assert_eq!(to_write, read);
 /// ```
+///
+/// ## Memory Limiting
+///
+/// The nature of parquet forces buffering of an entire row group before it can be flushed
```
Comment (alamb) [inline parquet/src/arrow/arrow_writer/mod.rs:86]: Would it be worth suggesting to users that if they want to minimize memory overages when writing such data, they can send in smaller `RecordBatches` (e.g. split up via `RecordBatch::slice` for example) which gives the parquet writer more chances to check / flush?

**Review by alamb — APPROVED** [review]
Thank you @tustvold  -- this is an improvement in my mind. I filed https://github.com/apache/arrow-rs/issues/5484 to discuss additional API work

**Comment by alamb** [comment]
> But it can be done/discussed separately ofc

I filed https://github.com/apache/arrow-rs/issues/5484  to track / discuss this idea. Thank you @DDtKey

**Comment by mapleFU** [comment]
Hi, thanks for the document here, I think I can also copying this to C++ Parquet lib. By the way, do you think it's necessary to also noted that dictionary encoding might be memory consuming? (Since maybe a huge dict woule be allocated)

**Comment by tustvold** [comment]
> By the way, do you think it's necessary to also noted that dictionary encoding might be memory consumin

We have a maximum dictionary page size that I think should bound this, I believe the C++ parquet lib does something similar

**Comment by mapleFU** [comment]
Generally yeah, but in fact, when writing to a wide table with several hundreds of columns, it will still be a huge overhead...Velox will disable dictionary encoding when memory usage is high. I think we can also note that?
