### PR TITLE
fix date conversion if timestamp below unixtimestamp

### LINKED ISSUE #4211: Casting Timestamp to date is off by one day for dates before 1970-01-01
If casting a negative number of micros/millis to date, the cast method divides by the number of (micro/milli)seconds to get the number of days from the beginning of the epoch. 
For a timestamp like `1969/12/31 23:59:59.995` (in millis) the number of millis from beginning of the epoch is -5. The division by the number of seconds in a day yields `0` which is off by one day since it should be `-1`. 

**To Reproduce**
```
select '1969-12-31 00:00:01'::timestamp::date;
+-----------------------------+
| Utf8("1969-12-31 00:00:01") |
+-----------------------------+
| 1970-01-01                  |
+-----------------------------+
```
**Expected behavior**
```
select '1969-12-31 00:00:01'::timestamp::date;
+-----------------------------+
| Utf8("1969-12-31 00:00:01") |
+-----------------------------+
| 1960-12-31                  |
+-----------------------------+
```

### PR DESCRIPTION
**Pull request by comphead**
# Which issue does this PR close?

Closes #4211 .

# Rationale for this change
Fix date conversion if timestamp below unixtimestamp

# What changes are included in this PR?

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by comphead** [comment]
@parthchandra @viirya

File: arrow-cast/src/cast.rs [hunk 1]
```diff
@@ -1853,7 +1853,7 @@ pub fn cast_with_options(
                 if time_array.is_null(i) {
                     b.append_null();
                 } else {
-                    b.append_value((time_array.value(i) / from_size) as i32);
+                    b.append_value(f64::floor(time_array.value(i) as f64 / from_size as f64) as i32);
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:1856]: Perhaps we could use https://docs.rs/num/latest/num/integer/fn.div_floor.html or something?

File: arrow-cast/src/cast.rs [hunk 2]
```diff
@@ -9172,4 +9172,46 @@ mod tests {
...
+                safe: false,
+                format_options: FormatOptions::default(),
+            },
+        )
+        .unwrap();
+
+        let ts_array = casted_array
+            .as_any()
+            .downcast_ref::<TimestampNanosecondArray>()
+            .unwrap();
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:9198]:
```suggestion
        let ts_array = casted_array.as_primitive::<TimestampNanosecondType>();
```

File: arrow-cast/src/cast.rs [hunk 3]
```diff
@@ -9172,4 +9172,46 @@ mod tests {
...
+        let ts_array = ts_array
+            .values()
+            .iter()
+            .map(|ts| Some(ts / 1_000_000))
+            .collect::<Vec<_>>();
+        let array =
+            TimestampMillisecondArray::from(ts_array).with_timezone("UTC".to_string());
+
+        let casted_array = cast(&array, &DataType::Date32).unwrap();
+        let date_array = casted_array.as_any().downcast_ref::<Date32Array>().unwrap();
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:9209]:
```suggestion
        let date_array = casted_array.as_primitive::<Date32Type>();
```

File: arrow-cast/src/cast.rs [hunk 4]
```diff
@@ -9172,4 +9172,46 @@ mod tests {
...
+
+        let casted_array = cast(&date_array, &DataType::Utf8).unwrap();
+        let string_array = casted_array.as_any().downcast_ref::<StringArray>().unwrap();
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:9212]:
```suggestion
        let string_array = casted_array.as_string::<i32>();
```

File: arrow-cast/src/cast.rs [hunk 5]
```diff
@@ -1853,7 +1853,7 @@ pub fn cast_with_options(
                 if time_array.is_null(i) {
                     b.append_null();
                 } else {
-                    b.append_value((time_array.value(i) / from_size) as i32);
+                    b.append_value(num::integer::div_floor::<i64>(time_array.value(i), from_size) as i32);
```
Comment (parthchandra) [inline arrow-cast/src/cast.rs:1856]: Something like 
```
                    let pre_epoch_adjustment = if value(i) < 0 { -1 } else { 0 };
                    b.append_value(pre_epoch_adjustment + (time_array.value(i) / from_size) as i32);

```
might be faster (because it skips all the check made by `div_floor`) ?

Comment (comphead) [reply arrow-cast/src/cast.rs:1856]: Can this convo be resolved then?

**Review by tustvold — APPROVED** [review]
Thank you, looks good to me

File: arrow-cast/src/cast.rs [hunk 6]
```diff
@@ -9172,4 +9172,41 @@ mod tests {
         );
         assert!(casted_array.is_err());
     }
+
+    #[test]
+    fn test_cast_below_unixtimestamp() {
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:9177]: I confirmed this test fails on master

File: arrow-cast/src/cast.rs (hunk 5 above)
Comment (parthchandra) [reply arrow-cast/src/cast.rs:1856]: @tustvold you'er right. My ide led me to the BigInt implementation of div_floor which is necessarily more complex, but not relevant here.
