### PR TITLE
StructBuilder Validate Child Data (#4397)

### LINKED ISSUE #4397: StructBuilder::new Doesn't Validate Builder DataTypes
**Describe the bug**
When using filter_record_batch on a RecordBatch, one of whose types is a timestamp with timezone, it drops the timezone.

**To Reproduce**
A test that replicates this:

```rust
#[test]
fn filter_record_batch_maintains_timezones() -> Result<(), arrow::error::ArrowError> {
    let fields = vec![arrow::datatypes::Field::new(
        "timestamp",
        arrow::datatypes::DataType::Timestamp(
            arrow::datatypes::TimeUnit::Nanosecond,
            Some("UTC".to_owned().into()),
        ),
        false,
    )];

    let field_builders: Vec<Box<dyn arrow::array::ArrayBuilder>> =
        vec![Box::new(arrow::array::TimestampNanosecondBuilder::new())];

    let mut sa = arrow::array::StructBuilder::new(fields, field_builders);

    for i in 0..100 {
        sa.field_builder::<arrow::array::TimestampNanosecondBuilder>(0)
            .unwrap()
            .append_value(i);
        sa.append(true);
    }

    let struct_array = sa.finish();

    let rec: arrow::record_batch::RecordBatch = (&struct_array).into();

    let schema = rec.schema();

    let dt = schema.field(0);
    assert_eq!(
        &arrow::datatypes::DataType::Timestamp(
            arrow::datatypes::TimeUnit::Nanosecond,
            Some("UTC".to_owned().into())
        ),
        dt.data_type()
    );

    let filter: arrow::array::BooleanArray = vec![true; 100].into();

    let filtered = arrow::compute::filter_record_batch(&rec, &filter)?;

    let filtered_schema = filtered.schema();

    let filtered_dt = filtered_schema.field(0);
    assert_eq!(
        &arrow::datatypes::DataType::Timestamp(
            arrow::datatypes::TimeUnit::Nanosecond,
            Some("UTC".to_owned().into())
        ),
        filtered_dt.data_type()
    );

    Ok(())
}
```

**Expected behavior**
Test should pass.

**Additional context**
Tested on arrow `40` and `41`.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4397

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-array/src/builder/struct_builder.rs [hunk 1]
```diff
@@ -240,42 +240,24 @@ impl StructBuilder {
...
         let nulls = self.null_buffer_builder.finish();
-
-        let builder = ArrayData::builder(DataType::Struct(self.fields.clone()))
-            .len(length)
-            .child_data(child_data)
-            .nulls(nulls);
-
-        let array_data = unsafe { builder.build_unchecked() };
-        StructArray::from(array_data)
+        StructArray::new(self.fields.clone(), arrays, nulls)
```
Comment (tustvold) [inline arrow-array/src/builder/struct_builder.rs:245]: As ArrayBuilder doesn't expose a data_type we can't validate the builders eagerly, but we can at least verify on finish

File: arrow-array/src/builder/struct_builder.rs [hunk 2]
```diff
@@ -305,8 +287,8 @@ mod tests {
         let int_builder = Int32Builder::new();
 
         let fields = vec![
-            Field::new("f1", DataType::Utf8, false),
-            Field::new("f2", DataType::Int32, false),
+            Field::new("f1", DataType::Utf8, true),
```
Comment (tustvold) [inline arrow-array/src/builder/struct_builder.rs:290]: The builder will now also verify nullability

**Review by crepererum — APPROVED** [review]
