### PR TITLE
Fix checked i256 arithmetic (#3942) (#3941)

### LINKED ISSUE #3941: I256 Checked Multiply Overflows for i256::MIN
**Describe the bug**

The i256::checked_mul works by computing the absolute values, unfortunately this runs into an issue with `i256::MIN` as the absolute value overflows `i256`

**To Reproduce**

```
i256::MIN.checked_mul(i256::ONE).unwrap()
```

**Expected behavior**

The above should not panic

**Additional context**

### LINKED ISSUE #3942: I256 Checked Subtraction Overflows for i256::MINUS_ONE
**Describe the bug**

**To Reproduce**

```
i256::from_parts(0, i128::MAX).checked_sub(i256::MINUS_ONE).unwrap();
```

**Expected behavior**

Shouldn't panic

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3941
Closes #3942

# Rationale for this change
 

The previous logic would report overflow erroneously

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-buffer/src/bigint.rs [hunk 1]
```diff
@@ -243,9 +243,8 @@ impl i256 {
     /// Performs checked addition
     #[inline]
     pub fn checked_add(self, other: Self) -> Option<Self> {
-        let (low, carry) = self.low.overflowing_add(other.low);
-        let high = self.high.checked_add(other.high)?.checked_add(carry as _)?;
```
Comment (tustvold) [inline arrow-buffer/src/bigint.rs:247]: The mistake this makes is assuming that addition is transitive, in the case of overflow it is not. 

In particular consider the case

```
i256::from_parts(u128::MAX, i128::MIN)
            .checked_add(i256::from_parts(1, -1))
            .unwrap();
```

The carry is enough to increase `i128::MIN` enough that adding `-1` doesn't result in overflow

File: arrow-buffer/src/bigint.rs [hunk 2]
```diff
@@ -259,9 +258,8 @@ impl i256 {
     /// Performs checked subtraction
     #[inline]
     pub fn checked_sub(self, other: Self) -> Option<Self> {
-        let (low, carry) = self.low.overflowing_sub(other.low);
-        let high = self.high.checked_sub(other.high)?.checked_sub(carry as _)?;
-        Some(Self { low, high })
```
Comment (tustvold) [inline arrow-buffer/src/bigint.rs:264]: Consider the case

```
i256::from_parts(0, i128::MAX).checked_sub(i256::MINUS_ONE).unwrap();
```

The carry is enough to reduce `i128::MAX` enough that `i125::MINUS_ONE` does not result in overflow

File: arrow-buffer/src/bigint.rs [hunk 3]
```diff
@@ -303,13 +305,14 @@ impl i256 {
         let hl = (l_abs.high as u128).checked_mul(r_abs.low)?;
         let lh = l_abs.low.checked_mul(r_abs.high as u128)?;
 
-        let high: i128 = high.checked_add(hl)?.checked_add(lh)?.try_into().ok()?;
```
Comment (tustvold) [inline arrow-buffer/src/bigint.rs:306]: If `high == -i128::MIN` this would fail, as it is performed before reversing the absolute value conversion

File: arrow-buffer/src/bigint.rs [hunk 4]
```diff
@@ -398,6 +404,12 @@ impl i256 {
         // needless overflow.
         acc.wrapping_mul(base)
     }
+
+    /// Returns `true` if this [`i256`] is negative
+    #[inline]
+    pub fn is_negative(self) -> bool {
```
Comment (tustvold) [inline arrow-buffer/src/bigint.rs:410]: This matches the standard method - https://doc.rust-lang.org/std/primitive.i32.html#method.is_negative

File: arrow-buffer/src/bigint.rs [hunk 5]
```diff
@@ -791,14 +803,33 @@ mod tests {
...
+            i256::MIN,
+            i256::MAX,
+            i256::MIN >> 1,
+            i256::MAX >> 1,
+            i256::ONE << 127,
+            i256::ONE << 128,
+            i256::ONE << 129,
+            i256::MINUS_ONE << 127,
+            i256::MINUS_ONE << 128,
+            i256::MINUS_ONE << 129,
```
Comment (viirya) [inline arrow-buffer/src/bigint.rs:832]: Better coverage 👍

**Review by viirya — APPROVED** [review]

File: arrow-buffer/src/bigint.rs (hunk 1 above)
Comment (viirya) [reply arrow-buffer/src/bigint.rs:247]: Oh, this is tricky.
