### PR TITLE
Optimized writing of byte array to parquet (#1764) (2x faster)

### LINKED ISSUE #1753: Arrow Parquet BinaryArray Writer Ignores LevelInfo Indices
**Describe the bug**

The functions generated by `def_get_binary_array_fn` and used by the parquet writer, ignore the indices attached to the `LevelInfo`. This will result in them potentially writing the too many values if a parent StructArray contains a null, or incorrect values if a parent ListArray contains a non-empty null slice.

**To Reproduce**

TBC

**Expected behavior**

The functions should respect the indices on `LevelInfo`

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Part of #1764
Closes #1753

# Rationale for this change
 

```
write_batch primitive/4096 values string                                                                            
                        time:   [482.71 us 482.93 us 483.18 us]
                        thrpt:  [164.72 MiB/s 164.81 MiB/s 164.88 MiB/s]
                 change:
                        time:   [-51.256% -51.214% -51.172%] (p = 0.00 < 0.05)
                        thrpt:  [+104.80% +104.98% +105.16%]
                        Performance has improved.
write_batch primitive/4096 values string non-null                                                                            
                        time:   [497.39 us 497.69 us 498.02 us]
                        thrpt:  [157.85 MiB/s 157.96 MiB/s 158.05 MiB/s]
                 change:
                        time:   [-51.444% -51.392% -51.343%] (p = 0.00 < 0.05)
                        thrpt:  [+105.52% +105.73% +105.95%]
                        Performance has improved.
```

And there is still low-hanging fruit for optimisation here

# What changes are included in this PR?

Switches encoding arrow arrays to a specialized write path

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/column/writer/encoder.rs [hunk 1]
```diff
@@ -30,16 +30,21 @@ use crate::util::memory::ByteBufferPtr;
...
-    type T: ParquetValueType;
-
     /// The number of values in this collection
     fn len(&self) -> usize;
+}
 
-    /// Returns the min and max values in this collection, skipping any NaN values
-    ///
-    /// Returns `None` if no values found
-    fn min_max(&self, descr: &ColumnDescriptor) -> Option<(&Self::T, &Self::T)>;
```
Comment (tustvold) [inline parquet/src/column/writer/encoder.rs:42]: This is moved onto Encoder so that `ColumnValues` can be a type-erased type, e.g. ArrayRef. This will be critical to support dictionaries without needing GATs, as the TypedDictionary (#2136) contains a lifetime.

File: parquet/src/column/writer/encoder.rs [hunk 2]
```diff
@@ -152,17 +198,12 @@ impl<T: DataType> ColumnValueEncoder for ColumnValueEncoderImpl<T> {
...
-        }
+        self.write_slice(slice)
+    }
 
-        match &mut self.dict_encoder {
-            Some(encoder) => encoder.put(slice),
-            _ => self.encoder.put(slice),
-        }
+    fn write_gather(&mut self, values: &Self::Values, indices: &[usize]) -> Result<()> {
+        let slice: Vec<_> = indices.iter().map(|idx| values[*idx].clone()).collect();
```
Comment (tustvold) [inline parquet/src/column/writer/encoder.rs:205]: This is pushed down from get_numeric_array_slice in arrow writer

File: parquet/src/arrow/arrow_writer/byte_array.rs [hunk 3]
```diff
@@ -0,0 +1,537 @@
...
+
+/// Computes the min and max for the provided array and indices
+///
+/// This is a free function so it can be used with `downcast_op!`
+fn compute_min_max<T>(
+    array: T,
+    mut valid: impl Iterator<Item = usize>,
+) -> Option<(ByteArray, ByteArray)>
+where
+    T: ArrayAccessor,
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/byte_array.rs:523]: Using the new ArrayAccessor :smile:

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 4]
```diff
@@ -148,12 +148,7 @@ impl<T: DataType> DictEncoder<T> {
 
     #[inline]
     fn bit_width(&self) -> u8 {
-        let num_entries = self.num_entries();
-        if num_entries <= 1 {
-            num_entries as u8
-        } else {
-            num_required_bits(num_entries as u64 - 1)
-        }
+        num_required_bits(self.num_entries().saturating_sub(1) as u64)
```
Comment (tustvold) [inline parquet/src/encodings/encoding/dict_encoder.rs:151]: This logic was actually previously incorrect as it would return a bit_width of 1 for `num_entries == 1` when it only needed to be 0. This is largely harmless, but is worth fixing.

File: parquet/src/arrow/arrow_writer/byte_array.rs [hunk 5]
```diff
@@ -0,0 +1,537 @@
...
+    fallback: FallbackEncoder,
+    dict_encoder: Option<DictEncoder>,
+    num_values: usize,
+    min_value: Option<ByteArray>,
+    max_value: Option<ByteArray>,
+}
+
+impl ColumnValueEncoder for ByteArrayEncoder {
+    type T = ByteArray;
+    type Values = ArrayRef;
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/byte_array.rs:394]: Initially I had the concrete type here, i.e. `StringArray`. This works, however, would present difficulties in adapting this to preserve dictionaries, as TypedDictionary (#2136) will contain a lifetime, which would then require GATs here

File: parquet/src/arrow/arrow_writer/mod.rs [hunk 6]
```diff
@@ -399,48 +415,35 @@ fn write_leaf(
...
-                    let array = column
-                        .as_any()
-                        .downcast_ref::<arrow_array::UInt32Array>()
-                        .expect("Unable to get u32 array");
-                    let array = arrow::compute::unary::<_, _, arrow::datatypes::Int32Type>(
-                        array,
-                        |x| x as i32,
-                    );
-                    get_numeric_array_slice::<Int32Type, _>(&array, indices)
+                    let array: &[i32] = data.buffers()[0].typed_data();
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/mod.rs:435]: This is a cheaper way to do the reinterpret cast

File: parquet/src/arrow/arrow_writer/mod.rs [hunk 7]
```diff
@@ -619,55 +560,20 @@ fn write_leaf(
...
-                        None
-                    }
-                })
-                .collect()
-        }
-    };
-}
-
-// TODO: These methods don't handle non null indices correctly (#1753)
-def_get_binary_array_fn!(get_binary_array, arrow_array::BinaryArray);
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/mod.rs:649]: Removing these fixes #1753

File: parquet/src/arrow/arrow_writer/byte_array.rs [hunk 8]
```diff
@@ -0,0 +1,557 @@
...
+    }
+
+    /// Encode `values` to the in-progress page
+    fn encode<T>(&mut self, values: T, indices: &[usize])
+    where
+        T: ArrayAccessor + Copy,
+        T::Item: AsRef<[u8]>,
+    {
+        self.num_values += indices.len();
+        match &mut self.encoder {
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/byte_array.rs:181]: See https://github.com/apache/parquet-format/blob/master/Encodings.md for what the various encodings are. They are all relatively self-explantory

File: parquet/src/arrow/arrow_writer/mod.rs (hunk 6 above)
Comment (tustvold) [reply parquet/src/arrow/arrow_writer/mod.rs:435]: Yup, this simply reinterprets the bytes without modification, same as C++'s reinterpret cast
