### PR TITLE
Parquet: Avoid page-size overflows i32

### LINKED ISSUE #8263: Parquet: Avoid page size exceeds i32::MAX
**Describe the bug**

In Parquet, page size cannot exceeds i32, since it uses thirft to store `uncompressed_page_size` and `compressed_page_size`.

See: https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L802

It's unlikely to happen, since arrow-rs change page-size to 1MiB by default. However, when we enlarge batch-size and page size limit, it's likely to happen

**To Reproduce**

Trying to write huge blob to parquet

**Expected behavior**

Switching to smaller boundery > Throw error > Leaving bad parquet page

**Additional context**

No

### PR DESCRIPTION
**Pull request by mapleFU**
# Which issue does this PR close?

- Closes #8263

# Rationale for this change

See https://github.com/apache/arrow-rs/issues/8263

# What changes are included in this PR?

Avoid page overflows

# Are these changes tested?

* [x] Will add

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/column/page.rs [hunk 1]
```diff
@@ -207,7 +207,6 @@ impl CompressedPage {
             type_: page_type.into(),
             uncompressed_page_size: uncompressed_size as i32,
             compressed_page_size: compressed_size as i32,
-            // TODO: Add support for crc checksum
```
Comment (etseidl) [inline parquet/src/column/page.rs]: This change is unrelated. AFAICT CRCs still aren't implemented on write.

File: parquet/src/file/writer.rs [hunk 2]
```diff
@@ -966,7 +966,19 @@ impl<W: Write + Send> PageWriter for SerializedPageWriter<'_, W> {
         let mut spec = PageWriteSpec::new();
         spec.page_type = page_type;
         spec.uncompressed_size = page.uncompressed_size() + header_size;
+        if spec.uncompressed_size > i32::MAX as usize {
```
Comment (etseidl) [inline parquet/src/file/writer.rs]: I think we'll need this check everywhere `PageWriter` is implemented (namely also in `arrow/arrow_writer/mod.rs`). Perhaps it would be better to add some validation to the `PageWriteSpec` struct itself. Maybe add some setters?

Comment (mapleFU) [reply parquet/src/file/writer.rs]: This is a "final around" before writing. Before `uncompressed_size` is using usize. I thinked about checking it when building `spec` but I don't know would it be too heavy ( or forcing )

Comment (mapleFU) [reply parquet/src/file/writer.rs]: some setters is ok to me

Comment (mapleFU) [reply parquet/src/file/writer.rs]: Now I have time for this part of the code. `pub struct PageWriteSpec` is widely used and it already uses usize. Should I just add setters like:`fn set_sizes(compressed, uncompressed) -> Result<()>`, or set the uncompressed_size to private and add visitors?

Comment (mapleFU) [reply parquet/src/file/writer.rs]: Or I can checking it when consuming, like in `to_thrift_header`

```rust
 pub(crate) fn to_thrift_header(&self) -> PageHeader {
        let uncompressed_size = self.uncompressed_size();
        let compressed_size = self.compressed_size();
        let num_values = self.num_values();
        let encoding = self.encoding();
        let page_type = self.page_type();

        let mut page_header = PageHeader {
            type_: page_type.into(),
            uncompressed_page_size: uncompressed_size as i32,
            compressed_page_size: compressed_size as i32,
            // TODO: Add support for crc checksum
            crc: None,
            data_page_header: None,
            index_page_header: None,
            dictionary_page_header: None,
            data_page_header_v2: None,
        };
```

File: parquet/src/column/page.rs (hunk 1 above)
Comment (mapleFU) [reply parquet/src/column/page.rs]: Removed

**Comment by mapleFU** [comment]
I've change the logic to to_thrift_page ( which is just `pub(crate)` and commonly used) and add tests. Would you mind take a look again? @alamb @etseidl

**Review by etseidl — APPROVED** [review]
Looks good to me. Thanks @mapleFU!

~I'm a little sad that this is going in `to_thrift` since that will hopefully be removed soon (#5854). I'll be sure to merge this into my working branch.~

Nevermind...`CompressedPage::to_thrift_headr` actually remains 😅

**Comment by mapleFU** [comment]
Actually I just meets a file which is corrupt by this is issue, cry :-(

```
            {
              "compression": "zstd",
              "encoding": "delta_length_byte_array",
              "page_type": "data_page_v2",
              "offset": 5662247374,
              "compressed_bytes": 581761248,
              "uncompressed_bytes": -1963337762,
              "header_bytes": 34,
              "num_values": 10000
            },
```
