### PR TITLE
fix invalid null handling in filter

### LINKED ISSUE #295: Filter has inconsistent null handling
**Describe the bug**
When creating a boolean mask from a comparison operation on an array with null values, the filter kernel yields a different result than when that boolean mask, including null values, is created directly.

**To Reproduce**

```rust
    fn test_null_mask() -> Result<()> {
        use crate::compute::kernels::comparison;
        let a: PrimitiveArray<Int64Type> = PrimitiveArray::from(vec![Some(1), Some(2), None]);
        let mask0 = comparison::eq(&a, &a)?;
        let out0 = filter(&a, &mask0)?;
        let out_arr0 = out0.as_any().downcast_ref::<PrimitiveArray<Int64Type>>().unwrap();

        let mask1 = BooleanArray::from(vec![Some(true), Some(true), None]);
        let out1 = filter(&a, &mask1)?;
        let out_arr1 = out1.as_any().downcast_ref::<PrimitiveArray<Int64Type>>().unwrap();
        assert_eq!(mask0, mask1); // assert succes
        assert_eq!(out_arr0, out_arr1);  // assert false
        Ok(())
    }
```

**Expected behavior**
Null values in the predicate mask should be ignored and not yield a result. Which the kernel does correctly on boolean mask that are created directly.

### PR DESCRIPTION
**Pull request by ritchie46**
# Which issue does this PR close?

This fixes #295.

This is a very simple solution to the problem and doesn't change any filtering behavior (though we may simplify the filtering if this PR is ok). In case of `null` values in a boolean mask I do a `mask` & `null_bitmask` operation and create a new `boolean` predicate that has no null values (all nulls are `false`), due to the AND operation.

### CODE REVIEW

**Comment by Dandandan** [comment]
This looks cool! Also if we can simplify / speed up filters this way, that would be very interesting, there is still quite some optimization potential in the filter kernel I believe.

File: arrow/src/compute/kernels/filter.rs [hunk 1]
```diff
@@ -221,6 +223,23 @@ pub fn build_filter(filter: &BooleanArray) -> Result<Filter> {
...
+        let null_bitmap = array_data.null_buffer().unwrap();
+        let mask = filter.values();
+        let new_mask = mask.bitand(&null_bitmap)?;
+
+        let array_data = ArrayData::builder(DataType::Boolean)
+            .len(filter.len())
+            .add_buffer(new_mask)
+            .build();
+        let filter = BooleanArray::from(array_data);
+        // fully syntax, because we have an argument with the same name
```
Comment (Dandandan) [inline arrow/src/compute/kernels/filter.rs:239]:
```suggestion
        // fully qualified syntax, because we have an argument with the same name
```

File: arrow/src/compute/kernels/filter.rs [hunk 2]
```diff
@@ -221,6 +223,23 @@ pub fn build_filter(filter: &BooleanArray) -> Result<Filter> {
 /// # }
 /// ```
 pub fn filter(array: &Array, filter: &BooleanArray) -> Result<ArrayRef> {
+    if filter.null_count() > 0 {
+        // this greatly simplifies subsequent filtering code
+        // now we only have a boolean mask to deal with
+        let array_data = filter.data_ref();
+        let null_bitmap = array_data.null_buffer().unwrap();
```
Comment (jhorstmann) [inline arrow/src/compute/kernels/filter.rs:230]: I think this needs to take the offset of the array into account, similar to https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/util.rs#L45

Comment (ritchie46) [reply arrow/src/compute/kernels/filter.rs:230]: Good catch.

Comment (ritchie46) [reply arrow/src/compute/kernels/filter.rs:230]: I used `buffer_bin_and`, I assume it does a "binary and" operation?

**Comment by alamb** [comment]
@jhorstmann  / @Dandandan  do you think this one is ready to go?

**Comment by jhorstmann** [comment]
I checked out the branch to have a look with a bit more context. The logic looks good and makes this kernel a lot easier to use. The test looks good and should cover exactly this problem.

One minor thing: There is a doc comment with a warning about null values above the `filter` function, which is now out of data.

**Review by jhorstmann — APPROVED** [review]

**Comment by Dandandan** [comment]
One small future improvement might be not creating a new array for filters, but computing / passing the changed buffer instead.

But the removal of undefined behavior for this kernel is really good I would say :+1:

File: arrow/src/compute/kernels/filter.rs [hunk 3]
```diff
@@ -581,4 +602,27 @@ mod tests {
...
+            .unwrap();
+
+        let mask1 = BooleanArray::from(vec![Some(true), Some(true), None]);
+        let out1 = filter(&a, &mask1)?;
+        let out_arr1 = out1
+            .as_any()
+            .downcast_ref::<PrimitiveArray<Int64Type>>()
+            .unwrap();
+        assert_eq!(mask0, mask1);
+        assert_eq!(out_arr0, out_arr1);
```
Comment (alamb) [inline arrow/src/compute/kernels/filter.rs:625]: This check and test makes sense to me (that the result of filtering using the output of `eq` should equal the output of filtering with a boolean mask that has nulls) 👍 

I also ran this test with the change in this PR commented out and it failed (as expected) in this way:

```
---- compute::kernels::filter::tests::test_null_mask stdout ----
thread 'compute::kernels::filter::tests::test_null_mask' panicked at 'assertion failed: `(left == right)`
  left: `PrimitiveArray<Int64>
[
  1,
  2,
  null,
]`,
 right: `PrimitiveArray<Int64>
[
  1,
  2,
]`', arrow/src/compute/kernels/filter.rs:606:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So 👍

**Review by alamb — APPROVED** [review]

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
Rerunning the CI as part of it showed red for some reason.
