### PR TITLE
Fix the behavior of `from_fixed_size_list` when offset > 0

### LINKED ISSUE #1958: `DecimalArray::from_fixed_size_list_array` fails when `offset > 0`
**Describe the bug**
`from_fixed_size_list_array` cannot return a correct result when `array.offset() > 0`

**To Reproduce**
```rust

    #[test]
    fn test_decimal_array_from_fixed_size_list() {
        let value_data = ArrayData::builder(DataType::UInt8)
            .len(48)
            .add_buffer(Buffer::from_slice_ref(&[12_i128, 34, 56]))
            .build()
            .unwrap();
        
        let null_buffer = Buffer::from_slice_ref(&[0b_101]);

        // Construct a list array from the above two
        let list_data_type = DataType::FixedSizeList(
            Box::new(Field::new("item", DataType::UInt8, false)),
            16,
        );
        let list_data = ArrayData::builder(list_data_type.clone())
            .len(2)
            .null_bit_buffer(Some(null_buffer))
            .offset(1)
            .add_child_data(value_data.clone())
            .build()
            .unwrap();
        let list_array = FixedSizeListArray::from(list_data);
        let decimal = DecimalArray::from_fixed_size_list_array(list_array, 38, 0);

        assert_eq!(decimal.len(), 2);
        assert!(decimal.is_null(0));
        assert_eq!(decimal.value_as_string(1), "56".to_string());
    }
```
**Expected behavior**
Pass the test.

**Additional context**
The reason  of the failure is that we drop the `offset` when copying `value_buffer` and `null_buffer`:
https://github.com/apache/arrow-rs/blob/master/arrow/src/array/array_binary.rs#L846-L849

A straight way is to add the offset:
```rust
        let builder = ArrayData::builder(DataType::Decimal(precision, scale))
            .len(v.len())
            .add_buffer(v.data_ref().child_data()[0].buffers()[0].clone())
            .null_bit_buffer(v.data_ref().null_buffer().cloned())
            .offset(v.offset());
```

However, the answer is still not 100% correct when the offset of the child data  > 0. (Nested offsets always make me confused 😅).

The way I prefer is to build decimal array from `FixedSizeBinaryArray` and drop this method, so that we can avoid nested offsets. Maybe we can file another issue to track this.

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

Closes #1958 .

# Rationale for this change
 Consider the impact of the offset of the list array (also the offset of the child array) when building decimal array.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/array/array_binary.rs [hunk 1]
```diff
@@ -1677,6 +1681,37 @@ mod tests {
...
+
+        // Construct a list array from the above two
+        let list_data_type = DataType::FixedSizeList(
+            Box::new(Field::new("item", DataType::UInt8, false)),
+            16,
+        );
+        let list_data = ArrayData::builder(list_data_type)
+            .len(2)
+            .null_bit_buffer(Some(null_buffer))
+            .offset(1)
```
Comment (HaoYang670) [inline arrow/src/array/array_binary.rs:1703]: Add offset in the list array

File: arrow/src/array/array_binary.rs [hunk 2]
```diff
@@ -1677,6 +1681,37 @@ mod tests {
...
+            .add_child_data(value_data)
+            .build()
+            .unwrap();
+        let list_array = FixedSizeListArray::from(list_data);
+        let decimal = DecimalArray::from_fixed_size_list_array(list_array, 38, 0);
+
+        assert_eq!(decimal.len(), 2);
+        assert!(decimal.is_null(0));
+        assert_eq!(decimal.value_as_string(1), "56".to_string());
```
Comment (HaoYang670) [inline arrow/src/array/array_binary.rs:1712]: I think this is the expected result, because slicing a list array doesn't push down the offset to child

File: arrow/src/array/array_binary.rs [hunk 3]
```diff
@@ -831,22 +831,26 @@ impl DecimalArray {
...
             "DecimalArray can only be created from FixedSizeList<u8> arrays, mismatched data types."
         );
 
+        let list_offset = v.offset();
+        let child_offset = child_data.offset();
         let builder = ArrayData::builder(DataType::Decimal(precision, scale))
             .len(v.len())
-            .add_buffer(v.data_ref().child_data()[0].buffers()[0].clone())
-            .null_bit_buffer(v.data_ref().null_buffer().cloned());
+            .add_buffer(v.data_ref().child_data()[0].buffers()[0].slice(child_offset))
```
Comment (tustvold) [inline arrow/src/array/array_binary.rs:851]:
```suggestion
            .add_buffer(child_data.buffers()[0].slice(child_offset))
```

File: arrow/src/array/array_binary.rs [hunk 4]
```diff
@@ -831,22 +831,26 @@ impl DecimalArray {
         precision: usize,
         scale: usize,
     ) -> Self {
+        let child_data = &v.data_ref().child_data()[0];
```
Comment (tustvold) [inline arrow/src/array/array_binary.rs:834]: Somewhat tangential to this PR, but what happens to the child data's null buffer? Perhaps worth a docstring saying it is ignored?

**Review by tustvold — APPROVED** [review]
LGTM

File: arrow/src/array/array_binary.rs (hunk 4 above)
Comment (HaoYang670) [reply arrow/src/array/array_binary.rs:834]: Great Catch! 
I am not sure whether we should drop it or do `list_nulls & child_nulls`.

That's why I want to drop this function and build decimal array from `FixedSizeBinary` array instead.
