### PR TITLE
parquet_derive: update in working example for ParquetRecordWriter

### LINKED ISSUE #7732: [parquet_derive] Example for ParquetRecordWriter is broken.
**Describe the bug**

I tried to reproduce the example for `ParquetRecordWriter` and I failed to. It required some minor fixes, which I managed to do.

**To Reproduce**

error reproduction problems can be found in my [repro001](<https://github.com/LanHikari22/rs_repro/blob/main/src/repro_tracked/repro001_parquet_derive_example.rs>).

**To quickly test**

My new changes can be tested as `repro001` here:
```sh
git clone https://github.com/LanHikari22/rs_repro.git
cd rs_repro
cargo run --features "repro001"
```

**Expected behavior**

That the example works out of the box.

**Additional context**

My development journal for this can be found [here](<https://github.com/dism-exe/dism-exe-notes/blob/main/lan/llm/weekly/Wk%2025%20003%20Rust%20Parquet%20serialize%20and%20deserialize.md>).

### PR DESCRIPTION
**Pull request by LanHikari22**
# Which issue does this PR close?

Closes #7732.

# What changes are included in this PR?

Just the rust documentation for ParquetRecordWriter

# Are there any user-facing changes?

The documentation page.

### CODE REVIEW

File: parquet_derive/src/lib.rs [hunk 1]
```diff
@@ -50,45 +50,52 @@ mod parquet_field;
 /// Example:
 ///
 /// ```no_run
```
Comment (alamb) [inline parquet_derive/src/lib.rs]: Is there any way we can remove the `no_run` from the example so we can have this code automatically checked by CI?

**Review by alamb — COMMENTED** [review]
Thank you for this contribution @LanHikari22  -- I left a suggestion let me know what you think

File: parquet_derive/src/lib.rs (hunk 1 above)
Comment (LanHikari22) [reply parquet_derive/src/lib.rs]: Thank you for your feedback! Yes I have removed `no_run`. It is not necessary. I have added to the README that we can test the doctests using

```sh
cargo test --doc -- --show-output
```

This could be integrated into a CI pipeline on commit, or otherwise to ensure they remain working.

I also updated the example itself to be more comprehensive, writing to file and reading it back and checking content is identical. If any of that fails, the above command will trigger an error.

**Review by alamb — APPROVED** [review]
Thank you @LanHikari22 

I merged up from main and ran `cargo fmt` to resolve the CI falure. 

This s a very nice improvement in my opinion

Thanks again

**Comment by LanHikari22** [comment]
Thank you @alamb!

I would like to get it working with nested structs and enums, etc as per #7734.

Please let me know if you have any suggestions on that.

Thanks,
Lan

**Comment by alamb** [comment]
> Thank you @alamb!
> 
> I would like to get it working with nested structs and enums, etc as per #7734.
> 
> Please let me know if you have any suggestions on that.
> 
> Thanks, Lan

I don't have any specific suggestions, unfortunately. I am not very familiar with how parquet_derive works
