### PR TITLE
fix(select): handle `NullArray` in `nullif`

### LINKED ISSUE #4634: `arrow::compute::nullif` panics if `NullArray` is provided
**Describe the bug**
`arrow::compute::nullif` may panic if the input array is of type `DataType::Null`.

**To Reproduce**

```rust
assert_eq!(
    as_null_array(
        &nullif(
            &NullArray::new(3),
            &BooleanArray::from(vec![Some(false), Some(true), None]),
        )
        .unwrap()
    ),
    &NullArray::new(3)
);
```

```
thread '...' panicked at 'NullArray data should not contain a null buffer, as no buffers are required', arrow-array\src\array\null_array.rs:149:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library\std\src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library\core\src/panicking.rs:67:14
   2: <arrow_array::array::null_array::NullArray as core::convert::From<arrow_data::data::ArrayData>>::from
             at ...\arrow-rs\arrow-array\src\array\null_array.rs:149:9
   3: arrow_array::array::make_array
             at ...\arrow-rs\arrow-array\src\array\mod.rs:580:36
   4: arrow_select::nullif::nullif
             at .\src\nullif.rs:96:8
```

**Expected behavior**
Not panicking

**Additional context**

### PR DESCRIPTION
**Pull request by kawadakk**
# Which issue does this PR close?

Closes #4634.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-select/src/nullif.rs [hunk 1]
```diff
@@ -128,6 +128,27 @@ mod tests {
         assert_eq!(&expected, res);
     }
 
+    #[test]
+    fn test_nullif_null_array() {
+        assert_eq!(
+            as_null_array(
+                &nullif(&NullArray::new(0), &BooleanArray::new_null(0)).unwrap()
+            ),
```
Comment (tustvold) [inline arrow-select/src/nullif.rs:136]:
```suggestion
            nullif(&NullArray::new(0), &BooleanArray::new_null(0)).unwrap().as_ref(),
```
FWIW you don't need to downcast here

**Review by tustvold — APPROVED** [review]
Just a minor nit, otherwise looks good. Thank you

**Review by viirya — APPROVED** [review]

File: arrow-select/src/nullif.rs (hunk 1 above)
Comment (kawadakk) [reply arrow-select/src/nullif.rs]: I'll update another one as well.

**Review by jackwener — APPROVED** [review]
