### PR TITLE
fix: correct accounting in `DictEncoder::estimated_memory_size`, `Interner::estimated_memory_size`

### LINKED ISSUE #9719: Incorrect accounting in `DictEncoder::estimated_memory_size`
In parquet, the `estimated_memory_size` method of `DictEncoder` should estimate the actual usage of allocated memory, but instead it uses the data member counting the encoded size of dictionary data, and ignores the hash table memory usage added by the `Interner` member.

### PR DESCRIPTION
**Pull request by mzabaluev**
# Which issue does this PR close?

- Closes #9719, #9744.

# Rationale for this change

The returned value should estimate the actual memory usage, but instead it uses the evaluation of the encoded size of the dictionary data, and bypasses the hash table memory usage added by the `Interner` member. The implementation of `Storage::estimated_memory_size` implementation for the unique key storage was not correct as well, but it was unused.

# What changes are included in this PR?

Correct both problems by making the `KeyStorage`'s implementation of `estimated_memory_size` return the size of the allocated `uniques` vector added with the values' sizes if applicable, and make `DictEncoder::estimated_memory_size` delegate to the `interner`, which calls the method of `KeyStorage` and adds accounting for its own data structure.

# Are these changes tested?

Added tests verifying that at least the expected added amounts are accounted for when values are added. Overreporting is hard to disprove due to dependency on allocation behavior internal to other libraries.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by alamb** [comment]
Is there some way to add tests for this change?

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 1]
```diff
@@ -183,6 +183,6 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
     ///
     /// For this encoder, the indices are unencoded bytes (refer to [`Self::write_indices`]).
     fn estimated_memory_size(&self) -> usize {
-        self.interner.storage().size_in_bytes + self.indices.len() * std::mem::size_of::<usize>()
+        self.interner.estimated_memory_size() + self.indices.len() * std::mem::size_of::<usize>()
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs]: I think this is the right direction (in the sense of account for the size in the structures that hold the memory, rather than the wrapper)

However, it is not clear to me that KeyStorage includes the heap bytes for types like BYTE_ARRAY

I think we need to add some tests for this code to make sure we have it right

**Review by alamb — COMMENTED** [review]
Thanks for this @mzabaluev

**Comment by mzabaluev** [comment]
Nobody seems to have really tested these methods, because this `Interner` code is also wrong:
https://github.com/mzabaluev/arrow-rs/blob/19002abc3522af60b6eaa99c0d5d4999b70cd681/parquet/src/util/interner.rs#L82

It should multiply the table capacity by the number of keys, not add them.

**Comment by alamb** [comment]
> Nobody seems to have really tested these methods, because this `Interner` code is also wrong: https://github.com/mzabaluev/arrow-rs/blob/19002abc3522af60b6eaa99c0d5d4999b70cd681/parquet/src/util/interner.rs#L82
> 
> It should multiply the table capacity by the number of keys, not add them.

The fact there are no tests and the code is wrong is probably related

File: parquet/src/encodings/encoding/dict_encoder.rs (hunk 1 above)
Comment (mzabaluev) [reply parquet/src/encodings/encoding/dict_encoder.rs]: Testing upper bounds would require intimate knowledge of reallocation behavior of `Vec` and hashbrown, but I'll try to get some confirmation.

Comment (mzabaluev) [reply parquet/src/encodings/encoding/dict_encoder.rs]: Oh, you are correct about the byte arrays, I need to account for variable- and fixed length array values.

Comment (mzabaluev) [reply parquet/src/encodings/encoding/dict_encoder.rs]: I have accounted for the byte arrays' allocations and added some tests.

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 2]
```diff
@@ -183,6 +188,214 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
...
     /// For this encoder, the indices are unencoded bytes (refer to [`Self::write_indices`]).
     fn estimated_memory_size(&self) -> usize {
-        self.interner.storage().size_in_bytes + self.indices.len() * std::mem::size_of::<usize>()
+        self.interner.estimated_memory_size()
+            + self.indices.capacity() * std::mem::size_of::<usize>()
+    }
+}
+
+#[cfg(test)]
+mod tests {
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs:196]: Thank you @mzabaluev 

I ran these tests without your code change and they all passed. Thus I don't think the are covering whatever issue you have found

```diff
andrewlamb@Andrews-MacBook-Pro-3:~/Software/arrow-rs$ git diff
diff --git a/parquet/src/encodings/encoding/dict_encoder.rs b/parquet/src/encodings/encoding/dict_encoder.rs
index 37cfdb9ba1..2f32f9c0bb 100644
--- a/parquet/src/encodings/encoding/dict_encoder.rs
+++ b/parquet/src/encodings/encoding/dict_encoder.rs
@@ -64,12 +64,7 @@ impl<T: DataType> Storage for KeyStorage<T> {
     }

     fn estimated_memory_size(&self) -> usize {
-        let uniques_heap_bytes = match T::get_physical_type() {
-            Type::FIXED_LEN_BYTE_ARRAY => self.type_length * self.uniques.len(),
-            _ => <Self::Value as ParquetValueType>::variable_length_bytes(&self.uniques)
-                .unwrap_or(0) as usize,
-        };
-        self.uniques.capacity() * std::mem::size_of::<T::T>() + uniques_heap_bytes
+        self.size_in_bytes + self.uniques.capacity() * std::mem::size_of::<T::T>()
     }
 }

diff --git a/parquet/src/util/interner.rs b/parquet/src/util/interner.rs
index deae3720d5..34c7d1390f 100644
--- a/parquet/src/util/interner.rs
+++ b/parquet/src/util/interner.rs
@@ -77,7 +77,9 @@ impl<S: Storage> Interner<S> {
     /// Return estimate of the memory used, in bytes
     #[allow(dead_code)] // not used in parquet_derive, so is dead there
     pub fn estimated_memory_size(&self) -> usize {
-        self.storage.estimated_memory_size() + self.dedup.allocation_size()
+        self.storage.estimated_memory_size() +
+            // estimate size of dedup hashmap as just th size of the keys
+            self.dedup.capacity() + std::mem::size_of::<S::Key>()
     }

     /// Returns the storage for this interner
```

And then 

```shell
andrewlamb@Andrews-MacBook-Pro-3:~/Software/arrow-rs$ cargo test --lib -p parquet -- dict_encoder
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.10s
     Running unittests src/lib.rs (target/debug/deps/parquet-d5e640393e7492a1)

running 6 tests
test encodings::encoding::dict_encoder::tests::test_estimated_memory_size_primitive_with_duplicates ... ok
test encodings::encoding::dict_encoder::tests::test_estimated_memory_size_primitive_all_distinct ... ok
test encodings::encoding::dict_encoder::tests::test_estimated_memory_size_fixed_len_byte_array_with_duplicates ... ok
test encodings::encoding::dict_encoder::tests::test_estimated_memory_size_byte_array_with_duplicates ... ok
test encodings::encoding::dict_encoder::tests::test_estimated_memory_size_fixed_len_byte_array_all_distinct ... ok
test encodings::encoding::dict_encoder::tests::test_estimated_memory_size_byte_array_all_distinct ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 1051 filtered out; finished in 0.00s

andrewlamb@Andrews-MacBook-Pro-3:~/Software/arrow-rs$
```

Comment (mzabaluev) [reply parquet/src/encodings/encoding/dict_encoder.rs:196]: There was another change. This makes `ByteArray` and `FixedLenByteArray` tests fail:

```diff
@@ -188,8 +183,7 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
     ///
     /// For this encoder, the indices are unencoded bytes (refer to [`Self::write_indices`]).
     fn estimated_memory_size(&self) -> usize {
-        self.interner.estimated_memory_size()
-            + self.indices.capacity() * std::mem::size_of::<usize>()
+        self.interner.storage().size_in_bytes + self.indices.len() * std::mem::size_of::<usize>()
     }
 }
```

I have added more tests that fail with the baseline code.

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 3]
```diff
@@ -183,6 +188,282 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
     ///
     /// For this encoder, the indices are unencoded bytes (refer to [`Self::write_indices`]).
     fn estimated_memory_size(&self) -> usize {
-        self.interner.storage().size_in_bytes + self.indices.len() * std::mem::size_of::<usize>()
+        self.interner.estimated_memory_size()
+            + self.indices.capacity() * std::mem::size_of::<usize>()
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs]: Indices is `Vec<u64> 
```rust
    /// The buffered indices
    indices: Vec<u64>,
```

But this is using `usize`

```suggestion
            + self.indices.capacity() * std::mem::size_of::<u64>()
```

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 4]
```diff
@@ -183,6 +188,282 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
...
+
+        // Must account for the 3 unique dictionary entries.
+        let dict_entry_size = 3 * std::mem::size_of::<i32>();
+        assert!(
+            size >= empty_size + dict_entry_size,
+            "memory size {size} should grow by at least the dict storage ({dict_entry_size} bytes)"
+        );
+
+        // Must also account for the 9 buffered indices.
+        let indices_size = 9 * std::mem::size_of::<usize>();
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs]: similarly this should probably be `size_of<u64>`

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 5]
```diff
@@ -183,6 +188,282 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
...
+
+        // Must account for the 100 unique dictionary entries.
+        let dict_entry_size = 100 * std::mem::size_of::<i32>();
+        assert!(
+            size >= empty_size + dict_entry_size,
+            "memory size {size} should grow by at least the dict storage ({dict_entry_size} bytes)"
+        );
+
+        // Must also account for the 100 buffered indices.
+        let indices_size = 100 * std::mem::size_of::<usize>();
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs]: here too

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 6]
```diff
@@ -183,6 +188,282 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
...
+
+        // Must account for the 3 unique dictionary entries, including their heap-allocated bytes.
+        let dict_entry_size = 3 * std::mem::size_of::<ByteArray>() + 3 * 3; // 3 values × 3 bytes each
+        assert!(
+            size >= empty_size + dict_entry_size,
+            "memory size {size} should grow by at least the dict storage ({dict_entry_size} bytes)"
+        );
+
+        // Must also account for the 9 buffered indices.
+        let indices_size = 9 * std::mem::size_of::<usize>();
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs]: and here

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 7]
```diff
@@ -183,6 +188,282 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
...
+        // Must account for the 100 unique dictionary entries: struct overhead plus the
+        // fixed-length bytes allocated per entry.
+        let dict_entry_size = 100 * std::mem::size_of::<FixedLenByteArray>() + 100 * TYPE_LEN;
+        assert!(
+            size >= empty_size + dict_entry_size,
+            "memory size {size} should grow by at least the dict storage ({dict_entry_size} bytes)"
+        );
+
+        // Must also account for the 100 buffered indices.
+        let indices_size = 100 * std::mem::size_of::<usize>();
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs]: and here

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 8]
```diff
@@ -183,6 +188,282 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
...
+        // Must account for the 3 unique dictionary entries: struct overhead plus the
+        // fixed-length bytes allocated per entry.
+        let dict_entry_size = 3 * std::mem::size_of::<FixedLenByteArray>() + 3 * TYPE_LEN;
+        assert!(
+            size >= empty_size + dict_entry_size,
+            "memory size {size} should grow by at least the dict storage ({dict_entry_size} bytes)"
+        );
+
+        // Must also account for the 9 buffered indices.
+        let indices_size = 9 * std::mem::size_of::<usize>();
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs]: and here

File: parquet/src/encodings/encoding/dict_encoder.rs [hunk 9]
```diff
@@ -183,6 +188,282 @@ impl<T: DataType> Encoder<T> for DictEncoder<T> {
...
+
+        // Must account for the 100 unique dictionary entries, including their heap-allocated bytes.
+        let dict_entry_size = 100 * std::mem::size_of::<ByteArray>() + bytes_total;
+        assert!(
+            size >= empty_size + dict_entry_size,
+            "memory size {size} should grow by at least the dict storage ({dict_entry_size} bytes)"
+        );
+
+        // Must also account for the 100 buffered indices.
+        let indices_size = 100 * std::mem::size_of::<usize>();
```
Comment (alamb) [inline parquet/src/encodings/encoding/dict_encoder.rs]: and here

**Review by alamb — COMMENTED** [review]
Thanks @mzabaluev  - this looks really close

I think we need one more change to make sure this works on 32 bit architectures as well (`usize` --> `u32`)-- I am happy to make the changes if you agree, but I wanted to check with you first

File: parquet/src/encodings/encoding/dict_encoder.rs (hunk 3 above)
Comment (mzabaluev) [reply parquet/src/encodings/encoding/dict_encoder.rs]: Indeed, I did not notice that this was also wrong.

**Review by alamb — APPROVED** [review]
Thank you for sticking with this @mzabaluev  -- very finicky but a nice result overall
