### PR TITLE
`ArrowArray::try_from_raw` should not assume the pointers are from Arc

### LINKED ISSUE #1333: `ArrowArray::try_from_raw` should not assume the pointers are from Arc
**Describe the bug**

`ArrowArray::try_from_raw` now uses `Arc::from_raw` to construct the two pointers to the C Data Interface (ArrowArray and ArrowSchema) back to the structs.

But the two pointers could be from other language runtime (e.g. JVM). We've been using the ffi API to pass Arrow Arrays from JVM to Rust. Sometimes we see fatal error reported at JVM (`SIGILL`). After digging it deeper, we found that sometimes `Arc::from_raw` on the pointers gives a `Arc` pointer with strong reference count reaching the maximum limit.

As the pointer is from JVM, it is not produced by `Arc::into_raw`, the offset calculation in `Arc::from_raw` simply doesn't work and can get into wrong values for the `strong` value in `ArcInner`.

I think that `ArrowArray::try_from_raw` should not assume the pointers are from `Arc`. They should be considered as just raw pointers to the C Data Interface.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1333.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by sunchao** [comment]
Merged, thanks @viirya !

**Comment by viirya** [comment]
Thanks @sunchao !

File: arrow/src/ffi.rs [hunk 1]
```diff
@@ -721,9 +721,11 @@ impl ArrowArray {
                     .to_string(),
             ));
         };
+        let ffi_array = (*array).clone();
```
Comment (alamb) [inline arrow/src/ffi.rs:724]: I am not super familiar with this code but it makes sense to me. The clone here seems to just be a clone of the `FFI_ArrowArray` struct itself (which is some ints and pointers) which seems reasonable enough to me.

If someone seems performance issues from this code, we can always add a `try_from_raw_arc` or something

Comment (viirya) [reply arrow/src/ffi.rs:724]: > The clone here seems to just be a clone of the FFI_ArrowArray struct itself (which is some ints and pointers) which seems reasonable enough to me.

That's right.

Comment (viirya) [reply arrow/src/ffi.rs:724]: Thanks @alamb

**Comment by wangfenjin** [comment]
Guys, not sure if my understanding is right, but I think this commit will break the design and create memory leak.

If we clone the FFI struct, then it means we need to free the pointer by ourself, but if we free FFI_ArrowArray, then the data in this Array will also be free? Which means we can't free the pointer(until the data are used and ready to free, but in reality we can't hold this useless pointer in a big project for such a long time), which create memory leak.

As to the question @viirya raised in #1333 , when manage memory, the one who allocate it should free it, which means in our case, we need to alloc the struct in rust and pass the pointer to java and then also free the memory in rust.

* You can check my code in here: https://github.com/wangfenjin/duckdb-rs/blob/5083d39a4147f8017613304ae5f217a88ac42c2e/src/raw_statement.rs#L58
* When I try to upgrade to version 10, [memory leak detected](https://github.com/wangfenjin/duckdb-rs/runs/5506654342?check_suite_focus=true) and there is no easy way to fix it.

I suggest we revert this commit. cc @alamb @sunchao

**Comment by viirya** [comment]
> As to the question @viirya raised in https://github.com/apache/arrow-rs/issues/1333 , when manage memory, the one who allocate it should free it, which means in our case, we need to alloc the struct in rust and pass the pointer to java and then also free the memory in rust.

Simply said, I don't think this is correct. That is the whole point of C data interface. The release callback is designed to be called by not only the one allocates the C data interface structure.

**Comment by viirya** [comment]
> If we clone the FFI struct, then it means we need to free the pointer by ourself, but if we free FFI_ArrowArray, then the data in this Array will also be free? Which means we can't free the pointer(until the data are used and ready to free, but in reality we can't hold this useless pointer in a big project for such a long time), which create memory leak.

As the raw pointers are converted to `Arc`, they will be released correctly eventually. But the data is still there, so of course you should not release the pointers.
