### PR TITLE
Fix for primitive and boolean take kernel for nullable indices with an offset

### LINKED ISSUE #502: sliced null buffers lead to incorrect result in take kernel (and probably on other places)
**Describe the bug**
Sliced arrays lead to incorrect null buffers. I have found this in code where I copied the `null` buffer of one array to that of a new one (without offset). 

I could pinpoint this bug in the `take` kernel, but I think it may occur in other parts as well.

In the code snippet below, you see the output of the array having two zero values where that should be null. As these are the values that should not have their validity bits set, it could probably be any other value at runtime.

*I could also reproduce this with other StringArray*

**To Reproduce**
```rust
use arrow::array::{UInt32Array, Array, LargeStringArray, PrimitiveArray, Int32Array};
use arrow::compute::take;
use arrow::datatypes::UInt32Type;

fn main() {
    let idx0 = UInt32Array::from(vec![Some(0), Some(1), Some(2), Some(3), Some(4), Some(5), Some(6), None, None]);
    let sliced_idx_arr = idx0.slice(5, 4);
    let sliced_idx = sliced_idx_arr.as_any().downcast_ref::<UInt32Array>().unwrap();

    let idx1 = UInt32Array::from(vec![Some(5), Some(6), None, None]);

    println!("indices:\n{:?}\n{:?}\n\n\n", &idx1, &sliced_idx);
    // this is true
    assert_eq!(&sliced_idx.into_iter().collect::<Vec<_>>(), &idx1.into_iter().collect::<Vec<_>>());


    let array = Int32Array::from(vec![0, 1, 2, 3, 4, 5, 6, 7, 8]);
    let taken1_arr= take(&array, &idx1, None).unwrap();
    let sliced_taken_arr = take(&array, &sliced_idx, None).unwrap();

    let taken1 = taken1_arr.as_any().downcast_ref::<Int32Array>().unwrap();
    let sliced_taken = sliced_taken_arr.as_any().downcast_ref::<Int32Array>().unwrap();

    let vec1: Vec<_> = taken1.into_iter().collect();
    let sliced_vec: Vec<_> = sliced_taken.into_iter().collect();

    println!("taken arrays:\n{:?}\n{:?}", &taken1, &sliced_taken);

    assert_eq!(vec1, sliced_vec)
}
```

**Output**

```
indices:
PrimitiveArray<UInt32>
[
  5,
  6,
  null,
  null,
]
PrimitiveArray<UInt32>
[
  5,
  6,
  null,
  null,
]



taken arrays:
PrimitiveArray<Int32>
[
  5,
  6,
  null,
  null,
]
PrimitiveArray<Int32>
[
  5,
  6,
  0,
  0,
]
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[Some(5), Some(6), None, None]`,
 right: `[Some(5), Some(6), Some(0), Some(0)]`', src/main.rs:29:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Expected behavior**
I'd expect the sliced array to have the same result as the array that is not sliced.

**Additional context**
https://github.com/pola-rs/polars/issues/878

### PR DESCRIPTION
**Pull request by jhorstmann**
# Which issue does this PR close?

Closes #502.

While implementing the fix I noticed a similar issue in the boolean take kernel which is now also fixed.

# Rationale for this change

When reusing the validity buffer of an array for a newly created array the offsets of the original array have to be taken into account. The original array might have had an offset > 0 but the new array will usually start at 0 and so a slice of the validity buffer has to be taken.
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

No

### CODE REVIEW

File: arrow/src/compute/kernels/take.rs [hunk 1]
```diff
@@ -516,7 +522,7 @@ where
         nulls = match indices.data_ref().null_buffer() {
             Some(buffer) => Some(buffer_bin_and(
                 buffer,
-                0,
+                indices.offset(),
                 &null_buf.into(),
                 0,
```
Comment (alamb) [inline arrow/src/compute/kernels/take.rs:527]: Is it correct that this `0` is due to the fact that `null_buf` was constructed via 

```rust
        let mut null_buf = MutableBuffer::new(num_byte).with_bitset(num_byte, true);
```

in the same `else` clause?

File: arrow/src/compute/kernels/take.rs [hunk 2]
```diff
@@ -876,6 +900,48 @@ mod tests {
...
+        let index = index.slice(2, 4);
+        let index = index.as_any().downcast_ref::<UInt32Array>().unwrap();
+
+        assert_eq!(
+            index,
+            &UInt32Array::from(vec![Some(2), Some(3), None, None])
+        );
+
+        test_take_primitive_arrays_non_null::<Int64Type>(
+            vec![0, 1, 2, 3, 4, 5, 6],
```
Comment (alamb) [inline arrow/src/compute/kernels/take.rs:916]: Would it make sense to use different values here than the indices -- perhaps something like

```suggestion
            vec![0, 10, 20, 30, 40, 50, 60],
```

So it is clearer from just this context that just `20` and `30` should be returned

**Review by alamb — APPROVED** [review]
I reviewed the logic and the tests carefully and this looks great to me. Thank you @jhorstmann 


FYI @ritchie46

**Comment by ritchie46** [comment]
Nice. Great that this is fixed before the 5.0 release!

File: arrow/src/compute/kernels/take.rs (hunk 1 above)
Comment (jhorstmann) [reply arrow/src/compute/kernels/take.rs:527]: Yes, null_buf is newly constructed and initialized starting from 0, while the first buffer and offset pair are coming from the indices array which might have a non-0 offset.

There was a proposal before to push the offsets down into all buffers instead of storing it in the array. That way we wouldn't need to care about which array a buffer originally belonged too. But if we do that we'd still need a better abstraction for the validity bitmap and only access it via (chunked) iterators. I'm also not sure whether such a change would have an affect on FFI usage.

File: arrow/src/compute/kernels/take.rs (hunk 2 above)
Comment (jhorstmann) [reply arrow/src/compute/kernels/take.rs]: Good idea, done

**Review by alamb — APPROVED** [review]
Looking good -- thanks again @jhorstmann
