### PR TITLE
fix test bug and ensure that bloom filter metadata is serialized in `to_thrift`

### LINKED ISSUE #1319: test_column_chunk_metadata_thrift_conversion test bug
test_column_chunk_metadata_thrift_conversion doesn't check full thrift conversion. It only checks from_thrift as it comares two thrift objects. 

test_column_chunk_metadata_thrift_conversion passing didn't flag to_thrift wasn't altered to assign bloom_filter_offset as part as https://github.com/apache/arrow-rs/pull/1309.

### PR DESCRIPTION
**Pull request by shanisolomon**
# Which issue does this PR close?
Closes #1319.

# Rationale for this change
 test_column_chunk_metadata_thrift_conversion didn't check full thrift conversion. It only checked from_thrift as it compared two thrift objects.

I altered it to compare two `ColumnChunkMetaData` objects, thus checking both to_thrift and from_thrift.

### CODE REVIEW

File: parquet/src/file/metadata.rs [hunk 1]
```diff
@@ -739,17 +739,15 @@ mod tests {
...
-
         let col_chunk_res =
-            ColumnChunkMetaData::from_thrift(column_descr, col_chunk_exp.clone())
-                .unwrap()
-                .to_thrift();
+            ColumnChunkMetaData::from_thrift(column_descr, col_metadata.to_thrift())
+                .unwrap();
 
-        assert_eq!(col_chunk_res, col_chunk_exp);
+        assert_eq!(col_chunk_res, col_metadata);
```
Comment (alamb) [inline parquet/src/file/metadata.rs:750]: I thought a little about if there was any value it keeping the check that `col_chunk_res.to_thrift()` and `col_metadata.to_thrift()` were also equal, but I think that given that this PR is deriving `PartialEq` on `ColumnChunkMetadata` there is no extra value in comparing the thrift serialized version

**Review by alamb — APPROVED** [review]
LGTM -- thank you @shanisolomon
