### PR TITLE
Fix bug in temporal utilities due to DST being ignored.

### LINKED ISSUE #901: Temporal utilities miss variations due to daylight savings
```

    #[cfg(feature = "chrono-tz")]
    #[test]
    fn test_temporal_array_timestamp_hour_with_dst_timezone_using_chrono_tz() {
        //
        // 1635577147 converts to 2021-10-30 17:59:07 in time zone Australia/Sydney (AEDT)
        // The offset (difference to UTC) is +11:00. Note that daylight savings is in effect on 2021-10-30.
        // When daylight savings is not in effect, Australia/Sydney has an offset difference of +10:00.

        let a = TimestampMillisecondArray::from_opt_vec(
            vec![Some(1635577147000)],
            Some("Australia/Sydney".to_string()),
        );
        let b = hour(&a).unwrap();
        assert_eq!(17, b.value(0));
    }

```

This test [fails](https://github.com/novemberkilo/arrow-rs/commit/473e2e4eb4f3b47aa7110d1a23444647b1109665) - it returns 16 instead of 17 and demonstrates that the offset for the timezone is not correctly taking daylight savings into account.

__Originally posted by @novemberkilo in https://github.com/apache/arrow-rs/pull/849#issuecomment-955647565__

### PR DESCRIPTION
**Pull request by novemberkilo**
# Which issue does this PR close?

Closes #901 

# What changes are included in this PR?

Replaces the function `using_chrono_tz` with a function `using_chrono_tz_and_utc_naive_datetime`

The rationale for this is that an offset for a timezone depends on the point in time at which the offset is required -- it will vary depending on whether DST is in effect at that point in time or not.

# Are there any user-facing changes?

I'm not sure. `using_chrono_tz` is a publicly available function (albeit under the `chrono-tz` feature flag) so strictly speaking the API is changing? If this is a concern, we could have both functions appear (with `using_chrono_tz` remaining unused). 

What do you think @alamb ?

### CODE REVIEW

File: arrow/src/compute/kernels/temporal.rs [hunk 1]
```diff
@@ -47,23 +47,45 @@ macro_rules! extract_component_from_array {
...
             for i in 0..$array.len() {
                 if $array.is_null(i) {
                     $builder.append_null()?;
                 } else {
-                    match $array.$using(i, fixed_offset) {
-                        Some(dt) => $builder.append_value(dt.$extract_fn() as i32)?,
-                        None => $builder.append_null()?,
+                    match $array.value_as_datetime(i) {
+                        Some(utc) => {
+                            let fixed_offset = match parse(
```
Comment (alamb) [inline arrow/src/compute/kernels/temporal.rs:56]: As written, I think this code will try and parse `$tz` for each row in the array (even though the `$tz` is a constant). 

I wonder if it would be possible to try and parse `$tz` *once* to figure out if it was fixed (e.g. a `Some<FixedOffset>`, and then only check if that was `None` for each row before computing  `using_chrono_tz_and_utc_naive_date_time`

**Comment by alamb** [comment]
Thank you @novemberkilo  -- I appreciate the follow up

File: arrow/src/compute/kernels/temporal.rs (hunk 1 above)
Comment (novemberkilo) [reply arrow/src/compute/kernels/temporal.rs]: Thanks for picking this up @alamb - I have addressed this in a subsequent commit.

**Review by alamb — APPROVED** [review]
Looks good @novemberkilo -- thank you
