### PR TITLE
Fix reading null booleans from CSV

### LINKED ISSUE #3521: Unable to read CSV with null boolean value
See comment here https://github.com/apache/arrow-rs/pull/3365/files#r1069008088

Removing this block causes errors when parsing CSV files with null values.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3521

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-csv/src/reader/mod.rs [hunk 1]
```diff
@@ -2067,4 +2071,30 @@ mod tests {
             assert_eq!(b.num_rows(), expected, "{}", idx);
         }
     }
+
+    #[test]
+    fn test_null_boolean() {
+        let csv = "true,false\nFalse,True\n,True\n";
```
Comment (alamb) [inline arrow-csv/src/reader/mod.rs:2077]: I recommend also testing in the other column like

False,

**Review by alamb — APPROVED** [review]
Thanks @tustvold

**Review by Dandandan — APPROVED** [review]
