### PR TITLE
Fix CSV infinite loop and improve error messages

### LINKED ISSUE #3469: Infinite Loop If Skipping More CSV Lines than Present
**Describe the bug**

The CSV reader will get stuck in an infinite loop if asked to skip more lines than are present in the input

**To Reproduce**

```
#[test]
    fn test_skip_insufficient_rows() {
        let csv = "a\nv\n";
        let cursor = Cursor::new(csv.as_bytes());
        let mut reader = RecordReader::new(cursor, Reader::new(), 1);
        let err = reader.skip(3).unwrap_err().to_string();
        assert_eq!(err, "sdlkfs");
    }
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Part of #3467
Closes #3469 

# Rationale for this change
 

See tickets

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-csv/src/reader/records.rs [hunk 1]
```diff
@@ -42,19 +42,21 @@ impl<R: BufRead> RecordReader<R> {
...
+            line_number: 1,
             offsets: vec![],
             data: vec![],
         }
     }
 
-    fn fill_buf(&mut self, to_read: usize) -> Result<(), ArrowError> {
+    /// Clears and then fills the buffers on this [`RecordReader`]
+    /// returning the number of records read
+    fn fill_buf(&mut self, to_read: usize) -> Result<usize, ArrowError> {
```
Comment (tustvold) [inline arrow-csv/src/reader/records.rs:53]: I reworked this to return the quantity read as I thought this made for a slightly clearer API

**Review by viirya — APPROVED** [review]

File: arrow-csv/src/reader/records.rs [hunk 2]
```diff
@@ -135,28 +139,38 @@ impl<R: BufRead> RecordReader<R> {
...
 
-        Ok(())
+        self.line_number += read;
+
+        Ok(read)
     }
 
     /// Skips forward `to_skip` rows
-    pub fn skip(&mut self, mut to_skip: usize) -> Result<(), ArrowError> {
+    pub fn skip(&mut self, to_skip: usize) -> Result<(), ArrowError> {
```
Comment (viirya) [inline arrow-csv/src/reader/records.rs:148]: Maybe we can document the error behavior.
