### PR TITLE
Fix serialization of large integers in JSON (#5038)

### LINKED ISSUE #5038: Regression when serializing large json numbers
**Describe the bug**
Serializing and writing a json Number `Number(1699148028689)` to parquet using `arrow_json` the value is not preserved.
When the value is read back from the parquet file, we obtain `-1659020527`.

**To Reproduce**
```rust
    #[test]
    fn test_serde_field() {
        let field = Field::new("int", DataType::Int64, true);
        let mut decoder = ReaderBuilder::new_with_field(field)
            .build_decoder()
            .unwrap();
        decoder.serialize(&[1699148028689_u64, 2, 3, 4]).unwrap();
        let b = decoder.flush().unwrap().unwrap();
        let values = b.column(0).as_primitive::<Int64Type>().values();
        assert_eq!(values, &[1699148028689, 2, 3, 4]);
    }
```

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #5038

# Rationale for this change
 

When converting i32 to i64 by default Rust will sign extend, we don't want this behaviour

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-json/src/reader/tape.rs [hunk 1]
```diff
@@ -180,7 +180,7 @@ impl<'a> Tape<'a> {
             TapeElement::Null => out.push_str("null"),
             TapeElement::I64(high) => match self.get(idx + 1) {
                 TapeElement::I32(low) => {
-                    let val = (high as i64) << 32 | low as i64;
+                    let val = (high as i64) << 32 | (low as u32) as i64;
```
Comment (alamb) [inline arrow-json/src/reader/tape.rs:183]: Can you confirm this code is only used for debugging? it wasn't clear to me that this is covered by a test, but if it is only used in https://github.com/apache/arrow-rs/blob/08b8cba1c5e8876543fcbb4e73da6a891f8ec2f6/arrow-json/src/reader/tape.rs#L210 I don't think that is necessary

**Review by alamb — APPROVED** [review]
👨‍🍳 👌 

I also double checked and it seems like this pattern to use the unsigned variant is done for all other uses in arrow:

Screenshot 2023-11-06 at 8 56 11 AM

File: arrow-json/src/reader/tape.rs (hunk 1 above)
Comment (tustvold) [reply arrow-json/src/reader/tape.rs:183]: It's only used in error messages
