### PR TITLE
fix panic in `ParquetMetadata::memory_size`: check has_min_max_set before invoking min()/max()

### LINKED ISSUE #6091: Invoke min/max function before check min/max value exists leads to program panic
**Describe the bug**

In the 52.1.0 release of the parquet crate, new APIs were introduced to retrieve the heap size of parquet metadata. However, a potential issue has been identified in the implementation that could lead to unexpected panics. The problem lies in the file 'parquet/src/file/meta/memory.rs', specifically between lines 168-178. In this section, the code invokes the 'min' function without first verifying the presence of a value in an Option type. This lack of validation before unwrapping could result in a panic if the Option is None.

**To Reproduce**

Construct a  ValueStatistics<T> without min/max value, and invoke the heapsize function.

**Expected behavior**

return current heap_size

**Additional context**
NONE

### PR DESCRIPTION
**Pull request by Fischer0522**
# Which issue does this PR close?

Closes #6091.

# Rationale for this change
 When column is null in parquet,the ValueStatistics's min max will be set None,so if we call ValueStatistics.min()/max() directly, the program will panic

# What changes are included in this PR?
use `ValueStatistics.has_min_max_set()` to check before invoking min/max

# Are there any user-facing changes?

No

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thanks @Fischer0522. 

Can you please add a test to cover this code? 

I am surprised it `panic`s as I would expect the `Option` to be handled by https://github.com/apache/arrow-rs/blob/e61fb621d1723b768689092d00cbce38ff8dc813/parquet/src/file/metadata/memory.rs#L56-L60

**Comment by alamb** [comment]
I think I see the issue and this PR makes sense. Thank you. I still think we need to add test coverage

Perhaps we can add something here https://github.com/apache/arrow-rs/blob/9be0eb530de85a68358dc31c146f71ccb97739ca/parquet/src/file/metadata/mod.rs#L1288-L1287

Here is an issue that tracks making this API less easy to misuse: https://github.com/apache/arrow-rs/issues/6093

**Comment by Fischer0522** [comment]
I add test in https://github.com/apache/arrow-rs/blob/9be0eb530de85a68358dc31c146f71ccb97739ca/parquet/src/file/metadata/mod.rs#L1288-L1287, i check memory with and without statistics. Please review it @alamb

File: parquet/src/file/metadata/mod.rs [hunk 1]
```diff
@@ -1291,7 +1291,11 @@ mod tests {
         let columns = schema_descr
             .columns()
             .iter()
-            .map(|column_descr| ColumnChunkMetaData::builder(column_descr.clone()).build())
+            .map(|column_descr| {
```
Comment (alamb) [inline parquet/src/file/metadata/mod.rs:1294]: I verified this test covers the bug by running it without the changes in this PR and it panic'd

```
called `Option::unwrap()` on a `None` value
thread 'file::metadata::tests::test_memory_size' panicked at parquet/src/file/statistics.rs:542:27:
called `Option::unwrap()` on a `None` value
stack backtrace:
```

👍

**Review by alamb — APPROVED** [review]
Thank you for this contribution @Fischer0522 -- I pushed a commit to this PR to get the test passing.

**Comment by Fischer0522** [comment]
This test seems odd. In the code, I noticed that the heap size for types like i32 is set to 0, so I set my expected value to 1320. However, the result I got was 2024. When I reran the test, the result changed to 1320. Could you tell me what might be causing this ？@alamb

**Comment by alamb** [comment]
> This test seems odd. In the code, I noticed that the heap size for types like i32 is set to 0, so I set my expected value to 1320. However, the result I got was 2024. When I reran the test, the result changed to 1320. Could you tell me what might be causing this ？@alamb

I think it is because the heap size includes not just the size for the `Statistics` but also the size for the newly added `ColumnMetadata` and `RowGroupMetadata` as well

**Comment by Fischer0522** [comment]
> > This test seems odd. In the code, I noticed that the heap size for types like i32 is set to 0, so I set my expected value to 1320. However, the result I got was 2024. When I reran the test, the result changed to 1320. Could you tell me what might be causing this ？@alamb
> 
> I think it is because the heap size includes not just the size for the `Statistics` but also the size for the newly added `ColumnMetadata` and `RowGroupMetadata` as well

I got it, since all checks in CI are passed, can this PR be merged into main？

**Comment by alamb** [comment]
Thanks again @Fischer0522
