### PR TITLE
fix: regexp_match skips first match

### LINKED ISSUE #3803: regexp_match skips first match when returning match
**Describe the bug**

In some cases `regexp_match` will skip first and only match.

e.g. if pattern is `foo` and string to match is `foo` then should return single match `foo`. Currently returning empty array for the match (correctly finds there is a match, but doesn't return the match correctly).

**To Reproduce**

Example test in [arrow-string/src/regexp.rs](https://github.com/apache/arrow-rs/blob/79518cf67a6dd5fc391e271fd92c0c21ee7e8a74/arrow-string/src/regexp.rs)

```rust
    #[test]
    fn sandbox() {
        let array = StringArray::from(vec![Some("foo")]);
        let pattern = GenericStringArray::<i32>::from(vec![r"foo"]);
        let actual = regexp_match(&array, &pattern, None).unwrap();
        let result = actual.as_any().downcast_ref::<ListArray>().unwrap();
        let elem_builder: GenericStringBuilder<i32> = GenericStringBuilder::new();
        let mut expected_builder = ListBuilder::new(elem_builder);
        expected_builder.values().append_value("foo");
        expected_builder.append(true);
        let expected = expected_builder.finish();
        assert_eq!(&expected, result);
    }

```

Will panic with:

```
thread 'regexp::tests::sandbox' panicked at 'assertion failed: `(left == right)`
  left: `ListArray
[
  StringArray
[
  "foo",
],
]`,
 right: `ListArray
[
  StringArray
[
],
]`', arrow-string/src/regexp.rs:277:9
```

Can see the right (actual) has empty `StringArray[]` whereas expected contains the match: `StringArray["foo"]`

**Expected behavior**

Test should succeed.

**Additional context**

Seems its because by default skipping the first match in a capture group:

https://github.com/apache/arrow-rs/blob/79518cf67a6dd5fc391e271fd92c0c21ee7e8a74/arrow-string/src/regexp.rs#L210-L218

Where in the test example above, `caps` has value:

```
[arrow-string/src/regexp.rs:212] &caps = Captures(
    {
        0: Some(
            "foo",
        ),
    },
)
```

Relevant regex doc: https://docs.rs/regex/latest/regex/struct.Regex.html#method.captures

Specifically:

> Capture group `0` always corresponds to the entire match.

Original issue: https://github.com/apache/arrow-datafusion/issues/5479

### PR DESCRIPTION
**Pull request by Weijun-H**
# Which issue does this PR close?

Closes #3803

# Rationale for this change
 
The `regexp_match` function currently only ignores the first match when there are multiple group matches.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-string/src/regexp.rs [hunk 1]
```diff
@@ -182,6 +182,9 @@ pub fn regexp_match<OffsetSize: OffsetSizeTrait>(
                 .map(|pattern| pattern.map(|pattern| pattern.to_string())),
         ),
     };
+
+    dbg!(array);
+
```
Comment (tustvold) [inline arrow-string/src/regexp.rs:187]:
```suggestion
```

**Comment by tustvold** [comment]
I've left a comment on the ticket - https://github.com/apache/arrow-rs/issues/3803#issuecomment-1456357073

I'm not sure this is actually a bug
