### PR TITLE
Strip leading whitespace from flight_sql_client custom header values

### LINKED ISSUE #4270: flight_sql_client --header "key: value" yields a value with a leading whitespace
**Describe the bug**

`flight_sql_client --header "key: value"` issues a request with a grpc metadata entry whose value contains a leading whitespace, i.e. `" value`" instead of `"value"`.

**To Reproduce**

```console
$ flight_sql_client --host localhost  --port 8082 --headers 'database: foo' 'select * from bobby'
... Error: database  foo not found
```

**Expected behavior**

The server should receive a header/metadata with a key containing the `"database"` string and a value containing the `"foo"` string.

The server instead receives a value containing the `" foo"` string.

**Additional context**

While the HTTP/1.1 clearly states that the value in a whitespace leading to the header value must be ignored, in HTTP2 the header key and value are clearly delimited in the binary protocol and whitespace is not inherently ignore

The [gRPC spec](https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/PROTOCOL-HTTP2.md) states that the header (aka metadata) value should not have leading or trailing whitespace.

> ASCII-Value should not have leading or trailing whitespace. If it contains leading or trailing whitespace, it may be stripped. 

At least some gRPC libraries (such as Tonic) don't strip the leading whitespace.

I think these libraries are correct, since the leading whitespace is purely an artifact of a string encoding of the key+value pair, when  encoded in a HTTP/1.1-like way (i.e. "foo: value").

Unfortunately this encoding is very common and people are very used to it. It's used in many tools such as `curl` and even `grpcurl`.

In fact `grpcurl -H "database: foo"` will correctly set `key = "database"` and `value = "foo` when setting the metadata fields.

(I checked that with wireshark and with a dummy gRPC server)

### PR DESCRIPTION
**Pull request by mkmik**
# Which issue does this PR close?

Closes #4270

# What changes are included in this PR?

This PR fixes the code that parses the `key: value` pairs when parsing the `--headers` flag

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
A test would be nice, but CLIs are kind of hard to test so don't feel strongly

File: arrow-flight/src/bin/flight_sql_client.rs [hunk 1]
```diff
@@ -49,7 +49,7 @@ where
         match parts.as_slice() {
             [key, value] => {
                 let key = K::from_str(key).map_err(|e| e.to_string())?;
-                let value = V::from_str(value).map_err(|e| e.to_string())?;
+                let value = V::from_str(value.trim_start()).map_err(|e| e.to_string())?;
```
Comment (alamb) [inline arrow-flight/src/bin/flight_sql_client.rs:52]: Should we also be trimming trailing whitespace?

**Review by alamb — APPROVED** [review]
I agree a test would be nice so we don't break this in the future -- but given this code doesn't seem to have any tests at the moment, I think it isn't strictly necessary

File: arrow-flight/src/bin/flight_sql_client.rs (hunk 1 above)
Comment (mkmik) [reply arrow-flight/src/bin/flight_sql_client.rs:52]: Yeah I thought only leading whitespace was trimmed in HTTP/1.1 (upon which the CLI tools like curl are modelled on), but it turns out that trailing whitespace is optioinal too:

https://www.rfc-editor.org/rfc/rfc7230#appendix-B

```
OWS = *( SP / HTAB )
header-field  = field-name ":" OWS field-value OWS
field-value   = *( field-content / obs-fold )
field-content = field-vchar [ 1*( SP / HTAB ) field-vchar ]
field-vchar   = VCHAR / obs-text
```

Comment (mkmik) [reply arrow-flight/src/bin/flight_sql_client.rs]: Added commit that switches to `.trim()`
