### PR TITLE
Fix DeltaBitPack MiniBlock Bit Width Padding

### LINKED ISSUE #1416: DeltaBitPackEncoder Pads Miniblock BitWidths With Arbitrary Values
**Describe the bug**

https://github.com/apache/arrow-rs/blob/master/parquet/src/encodings/encoding.rs#L577 skips over the miniblock bit widths, and then only goes back and writes a value for the miniblocks that contain a non-zero number of values. The empty miniblocks are left with whatever value happens to be in the encoder's buffer.

**To Reproduce**

This is one of the underlying bugs behind https://github.com/apache/arrow-datafusion/issues/1976

**Expected behavior**

Whilst the specification technically allows for arbitrary padding, it seems like a good idea to avoid non-deterministic output where possible

### LINKED ISSUE #1417: DeltaBitPackDecoder Incorrectly Handles Non-Zero MiniBlock Bit Width Padding
**Describe the bug**

From the parquet [specification](https://github.com/apache/parquet-format/blob/master/Encodings.md).

> If, in the last block, less than <number of miniblocks in a block> miniblocks are needed to store the values, the bytes storing the bit widths of the unneeded miniblocks are still present, their value should be zero, but readers must accept arbitrary values as well.

This is particularly important at the moment because of #1416 which causes the padding to be arbitrary in the event an encoder is reused.

**To Reproduce**

This is one of the underlying bugs behind https://github.com/apache/arrow-datafusion/issues/1976

**Expected behavior**

The decoder should ignore the padded miniblock bit widths

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1416 
Closes #1417

# Rationale for this change
 
Fixes https://github.com/apache/arrow-datafusion/issues/1976

# What changes are included in this PR?

Makes DeltaBitPackEncoder padding deterministic, and makes DeltaBitPackDecoder resilient to non-zero padding

# Are there any user-facing changes?

Output that was previously somewhat non-deterministic, is now deterministic.

### CODE REVIEW

**Comment by tustvold** [comment]
I have tested Datafusion against this cherry-picked onto the 10.0.0 release and can confirm it fixes https://github.com/apache/arrow-datafusion/issues/1976. 

The branch is [here](https://github.com/tustvold/arrow-rs/tree/10.0.1). I do wonder if it might be an interesting exercise for me to help cut a patch release for this so I can get some exposure to this process, thoughts @alamb?

File: parquet/src/encodings/decoding.rs [hunk 1]
```diff
@@ -668,9 +667,9 @@ where
 
             read += batch_read;
             self.mini_block_remaining -= batch_read;
+            self.values_left -= batch_read;
```
Comment (tustvold) [inline parquet/src/encodings/decoding.rs:670]: This is the fix for #1417 - the problem was that as `self.value_left` was only decremented outside the loop, the code in `next_block` was unable to correctly determine when the bit widths were padding

File: parquet/src/encodings/encoding.rs [hunk 2]
```diff
@@ -581,6 +581,13 @@ impl<T: DataType> DeltaBitPackEncoder<T> {
             // values left
             let n = cmp::min(self.mini_block_size, self.values_in_block);
             if n == 0 {
+                // Decoders should be agnostic to the padding value, we therefore use 0xFF
```
Comment (tustvold) [inline parquet/src/encodings/encoding.rs:584]: This is the fix for #1416, I opted to pad with a non-zero value for tests so we have coverage of that scenario, but not produce such data outside of tests for better ecosystem-interop

**Comment by alamb** [comment]
@tustvold  is this a regression introduced in parquet? If so, which version was it introduced in (9.1 maybe?)

**Comment by alamb** [comment]
Was it introduced in https://github.com/apache/arrow-rs/pull/1284 maybe?

**Comment by tustvold** [comment]
#1417 was a regression introduced by #1284, #1416 was a pre-existing issue that has probably existing for a very long time

File: parquet/src/encodings/encoding.rs [hunk 3]
```diff
@@ -610,11 +617,7 @@ impl<T: DataType> DeltaBitPackEncoder<T> {
             self.values_in_block -= n;
         }
 
-        assert!(
```
Comment (alamb) [inline parquet/src/encodings/encoding.rs:613]: I don't understand this change -- the older assert seemed to be more specific, right?

**Review by alamb — COMMENTED** [review]
I think this PR needs some tests

**Comment by tustvold** [comment]
> I think this PR needs some tests

By making it pad with `0xFF` when running in test mode we now get coverage from the existing tests?

File: parquet/src/encodings/encoding.rs (hunk 3 above)
Comment (tustvold) [reply parquet/src/encodings/encoding.rs:613]: Aah - I was under the impression assert_eq! logged the textual representation of the arguments, but it does not - will fix

**Comment by tustvold** [comment]
I added a test for #1417 and whilst doing so fixed a bug where a truncated page could get the decoder stuck in an infinite loop

File: parquet/src/encodings/decoding.rs [hunk 4]
```diff
@@ -652,6 +652,14 @@ where
                 .bit_reader
                 .get_batch(&mut buffer[read..read + batch_to_read], bit_width);
 
+            if batch_read != batch_to_read {
```
Comment (tustvold) [inline parquet/src/encodings/decoding.rs:655]: Prior to this change, the decoder would get stuck in an infinite loop if given a truncated page. I discovered this by accident whilst writing `test_delta_bit_packed_padding`

File: parquet/src/encodings/decoding.rs [hunk 5]
```diff
@@ -1326,6 +1335,83 @@ mod tests {
...
+        assert_eq!(reader.get_vlq_int().unwrap(), 419);
+        assert_eq!(reader.get_vlq_int().unwrap(), 7);
+
+        // Test output buffer larger than needed and not exact multiple of block size
+        let mut output = vec![0_i32; 420];
+
+        let mut decoder = DeltaBitPackDecoder::<Int32Type>::new();
+        decoder.set_data(ptr.clone(), 0).unwrap();
+        assert_eq!(decoder.get(&mut output).unwrap(), 419);
+        assert_eq!(decoder.get_offset(), length);
```
Comment (tustvold) [inline parquet/src/encodings/decoding.rs:1403]: Without the fix for #1417 this would fail

File: parquet/src/encodings/decoding.rs [hunk 6]
```diff
@@ -444,7 +443,6 @@ pub struct DeltaBitPackDecoder<T: DataType> {
     values_per_mini_block: usize,
 
     // Per block info
-
```
Comment (sunchao) [inline parquet/src/encodings/decoding.rs:447]: nit: unnecessary change?

**Review by sunchao — APPROVED** [review]
The fix looks good to me. Thanks for identifying the bug!

+1 on having 9.1.1 and 10.0.1 branches for the fix.

File: parquet/src/encodings/decoding.rs (hunk 6 above)
Comment (tustvold) [reply parquet/src/encodings/decoding.rs]: I thought it was cleaner, but don't feel strongly so reverted

**Comment by alamb** [comment]
I am happy to make 9.1.1 and 10.0.1 branches and prepare the releases.

@sunchao  would you recommend we proactively release 9.1.1 and 10.0.1? If so I'll make a ticket and start the process. It is probably the right thing to do I suppose -- I was just dreading the voting process :)

**Comment by sunchao** [comment]
SGTM @alamb , although I'm not sure if we should wait for #1432 too for 10.0.1. BTW I can help on the release process too.

**Comment by alamb** [comment]
> SGTM @alamb , although I'm not sure if we should wait for https://github.com/apache/arrow-rs/pull/1432 too for 10.0.1. BTW I can help on the release process too.

If you could talk on creating the 9.1.1 and 10.0.1 releases that would be great! I'll file a ticket to start tracking it

**Comment by alamb** [comment]
https://github.com/apache/arrow-rs/issues/1442 tracking the patch releases

**Comment by alamb** [comment]
Thanks @tustvold
