### PR TITLE
fix: respect offset/length when converting ArrayData to StructArray

### LINKED ISSUE #6151: StructArray from ArrayData Ignores Offset
**Describe the bug**

In https://github.com/kylebarron/arro3 I'm exporting arrow-rs functionality for general Python use. I seem to have hit a bug importing sliced arrays.

In [`import_array_pycapsules`](https://github.com/kylebarron/arro3/blob/9673b62161f94d41a06c71f895abb8662b8e2864/pyo3-arrow/src/ffi/from_python/utils.rs#L72-L89) (which is vendored from arrow-rs code [here](https://github.com/apache/arrow-rs/blob/80ed7128510bac114c6feec08c34ef3beed3a44a/arrow/src/pyarrow.rs#L265-L275)) I have:

```rs
pub(crate) fn import_array_pycapsules(
    schema_capsule: &Bound<PyCapsule>,
    array_capsule: &Bound<PyCapsule>,
) -> PyResult<(ArrayRef, Field)> {
    validate_pycapsule_name(schema_capsule, "arrow_schema")?;
    validate_pycapsule_name(array_capsule, "arrow_array")?;

    let schema_ptr = unsafe { schema_capsule.reference::<FFI_ArrowSchema>() };
    let array = unsafe { FFI_ArrowArray::from_raw(array_capsule.pointer() as _) };

    let array_data = unsafe { arrow::ffi::from_ffi(array, schema_ptr) }
        .map_err(|err| PyTypeError::new_err(err.to_string()))?;
    dbg!(array_data.offset());

    let field = Field::try_from(schema_ptr).map_err(|err| PyTypeError::new_err(err.to_string()))?;
    let array = make_array(array_data);

    dbg!(array.offset());
    Ok((array, field))
}
```

Note the two `dbg!` macros. When invoked from Python with a pyarrow `StructArray`, the array offset is lost.

```py
import pyarrow as pa
import pytest
from arro3.compute import struct_field

a = pa.array([1, 2, 3])
b = pa.array([3, 4, 5])
struct_arr = pa.StructArray.from_arrays([a, b], names=["a", "b"])
sliced = struct_arr.slice(1, 2)
sliced.offset # 1
pa.array(struct_field(sliced, [0]))
# <pyarrow.lib.Int64Array object at 0x10fa94700>
# [
#   1,
#   2
# ]
```

Note that the _first two_ elements of `a` are kept, with the `offset` not used. I've isolated this to the two lines with `dbg!`. Those print:
```
[pyo3-arrow/src/ffi/from_python/utils.rs:84:5] array_data.offset() = 1
[pyo3-arrow/src/ffi/from_python/utils.rs:87:5] array.offset() = 0
```
In particular `make_array` does not check the `offset` from the base array:
https://github.com/apache/arrow-rs/blob/80ed7128510bac114c6feec08c34ef3beed3a44a/arrow-array/src/array/struct_array.rs#L296-L311

**To Reproduce**

Here's the way to reproduce the upstream bug
```
git clone https://github.com/kylebarron/arro3
cd arro3
git checkout 9673b62
poetry install
poetry run maturin develop -m arro3-core/Cargo.toml
poetry run maturin develop -m arro3-compute/Cargo.toml
poetry run pytest
```

I can _try_ to reproduce this in pure rust if needed, but that may not be possible because the `StructArray` seems to always export an `offset` of `0`, and so it may not be easy to reproduce this importing behavior.

**Expected behavior**

Expected the array offset to be maintained.

**Additional context**

### PR DESCRIPTION
**Pull request by westonpace**
# Which issue does this PR close?

- Closes #6151.

# Rationale for this change

See issue.  When converting arrays from arrow-cpp then sliced struct arrays may have an offset/length.  By ignoring these the resulting `StructArray` is incorrect. 

# What changes are included in this PR?

Changes the behavior of `StructArray::from::<ArrayData>`

# Are there any user-facing changes?

No.  It's hard to imagine any user would be relying on the past behavior as it was invalid.  There was one unit test that had to change because it was relying on this behavior to construct invalid arrays (to ensure the IPC could handle these invalid arrays).

### CODE REVIEW

File: arrow-array/src/array/struct_array.rs [hunk 1]
```diff
@@ -294,10 +294,34 @@ impl StructArray {
...
         let fields = data
             .child_data()
             .iter()
-            .map(|cd| make_array(cd.clone()))
+            .map(|cd| {
+                let child_offset = cd.offset();
+                let child_len = cd.len();
+                assert!(
+                    child_len >= parent_len + parent_offset,
+                    "struct array has offset {} and len {} but child array only has {} items",
```
[the remark this answers is not in the document]
Comment (westonpace) [reply arrow-array/src/array/struct_array.rs:308]: A good question but I do not believe this suggestion is not valid.  The child's length is "number of items after the offset" and so I do not believe we need to consider the child offset in this calculation.

File: arrow-array/src/array/struct_array.rs [hunk 2]
```diff
@@ -523,6 +547,55 @@ mod tests {
         assert_eq!(0, struct_array.offset());
     }
 
+    #[test]
```
Comment (alamb) [inline arrow-array/src/array/struct_array.rs:550]: I did verify that these tests fail without the code change in this PR

```


thread 'array::struct_array::tests::test_struct_array_from_data_with_offset_and_length' panicked at arrow-array/src/array/struct_array.rs:551:9:
assertion `left == right` failed
  left: StructArray
-- validity:
```

File: arrow-array/src/array/struct_array.rs [hunk 3]
```diff
@@ -523,6 +547,55 @@ mod tests {
...
+    fn test_struct_array_from_data_with_offset_and_length() {
+        let int_arr = Int32Array::from(vec![1, 2, 3, 4, 5]);
+        let int_field = Field::new("x", DataType::Int32, false);
+        let struct_nulls = NullBuffer::new(BooleanBuffer::from(vec![true, true, false]));
```
Comment (alamb) [inline arrow-array/src/array/struct_array.rs:554]: I am not entirely familiar with how struct array nulls are represented. Can you please confirm this is correct

Specifically, it seems like the ArrayData's offset does not apply to the `NullBuffer` -- so in this case the null buffer only has three elements `true, true, false`, so if the offset was applied to the nulls,  that would mean there were only two values for nulls. However, as the length of the Array data is three, this must be as intended

File: arrow-array/src/array/struct_array.rs [hunk 4]
```diff
@@ -294,10 +294,34 @@ impl StructArray {
...
+                    parent_len,
+                    child_len
+                );
+                // SAFETY: We have already checked that the child array has enough items and the
+                // only thing we are changing is the offset and length.  As long as the child data
+                // was previously valid, then the new child data is also valid.
+                let cd = unsafe {
+                    cd.clone()
+                        .into_builder()
+                        .offset(child_offset + parent_offset)
```
Comment (alamb) [inline arrow-array/src/array/struct_array.rs:319]: doesn't this require that  `child_offset + parent_offset + parent_len is >= child_len`?

The check above only verifies that parent_len + parent_offset is greater than child_len

**Review by alamb — COMMENTED** [review]
Thank you @westonpace  -- I have one question about the assert / safety check. Otherwise this seems like a nice fix to me

FYI @kylebarron and @tustvold

File: arrow-array/src/array/struct_array.rs (hunk 3 above)
Comment (westonpace) [reply arrow-array/src/array/struct_array.rs:554]: There's a bit of ambiguity / redundancy here.  Both `ArrayData` and `NullBuffer` can have an offset.  As best I can tell from the `ArrayData` code, it is meant to assume the offset is baked into the `NullBuffer` and the `ArrayData` offset does not apply to the `NullBuffer` (although I see another potential issue in the `validate` function, I'll open a new ticket to question that).

However, looking at the FFI code, it does appear what you'd normally get is...

```
let validity = BooleanBuffer::from(vec![true, true, true, false, true]);
validity = validity.slice(1, 3);
let struct_nulls = NullBuffer::new(validity);
```

I can update the test to more accurately reflect what happens in FFI.

File: arrow-array/src/array/struct_array.rs [hunk 5]
```diff
@@ -294,10 +294,34 @@ impl StructArray {
...
     fn from(data: ArrayData) -> Self {
+        let parent_offset = data.offset();
+        let parent_len = data.len();
+
         let fields = data
             .child_data()
             .iter()
-            .map(|cd| make_array(cd.clone()))
+            .map(|cd| {
+                let child_offset = cd.offset();
```
Comment (tustvold) [inline arrow-array/src/array/struct_array.rs:304]: Rather than this somewhat opaque logic, which I am also not sure is correct w.r.t nulls, I wonder if we could just do something along these lines

```
let child = make_array(cd.clone());
if (parent_offset != 0 || parent_len != cd .len()) {
    return child.slice(parent_offset, parent_len);
}
return child
```

File: arrow-array/src/array/struct_array.rs (hunk 3 above)
Comment (westonpace) [reply arrow-array/src/array/struct_array.rs:555]: I've added a test case for the sliced null buffer case.  I've also filed https://github.com/apache/arrow-rs/issues/7379 for a different, tangential error.

**Comment by westonpace** [comment]
It seems we've been blessed with a new version of Rust :laughing: 

I'll work on the clippy errors in a new PR.

File: arrow-array/src/array/struct_array.rs [hunk 6]
```diff
@@ -294,10 +294,19 @@ impl StructArray {
...
     fn from(data: ArrayData) -> Self {
+        let parent_offset = data.offset();
+        let parent_len = data.len();
+
         let fields = data
             .child_data()
             .iter()
-            .map(|cd| make_array(cd.clone()))
+            .map(|cd| {
+                if parent_offset != 0 || cd.len() != parent_len {
```
Comment (alamb) [inline arrow-array/src/array/struct_array.rs:304]: this is much nicer

File: arrow-array/src/array/struct_array.rs (hunk 3 above)
Comment (alamb) [reply arrow-array/src/array/struct_array.rs:540]: I made a PR to try and clarify the comments: 
- https://github.com/apache/arrow-rs/pull/7385

**Review by alamb — COMMENTED** [review]
Thanks @westonpace  -- this is looking very good. I have only one more question

File: arrow-array/src/array/struct_array.rs (hunk 6 above)
Comment (westonpace) [reply arrow-array/src/array/struct_array.rs]: Added test case.
