### PR TITLE
Fix NullArrayReader (#1245)

### LINKED ISSUE #1245: Parquet v8.0.0 panics when reading all null column to NullArray
**Describe the bug**
When reading a Parquet file with a single row, containing a single optional `int32` column containing `null` the parquet reader panics.

This was found when trying to upgrade to Arrow/Parquet v8.0.0. The original file contained additional columns but was reduced to this.

The referenced branch contains a Parquet file containing a single nullable Int32 value. In this case I produced it using the following Pandas code:

```
d = {'int32': [None]}
df = pd.DataFrame(data=d)
df.to_parquet("minimal.parquet")
```
The file loads correctly using `6.3.0`. With `8.0.0` it panics.

```
running 1 test
thread 'arrow::arrow_reader::tests::test_single_null_i32' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', parquet/src/arrow/record_reader/definition_levels.rs:102:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::assert_failed_inner
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:181:17
   3: core::panicking::assert_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:138:5
   4: parquet::arrow::record_reader::definition_levels::DefinitionLevelBuffer::set_len
             at ./src/arrow/record_reader/definition_levels.rs:102:9
   5: parquet::arrow::record_reader::GenericRecordReader<V,CV>::set_values_written
             at ./src/arrow/record_reader.rs:347:13
   6: parquet::arrow::record_reader::GenericRecordReader<V,CV>::read_one_batch
             at ./src/arrow/record_reader.rs:299:9
   7: parquet::arrow::record_reader::GenericRecordReader<V,CV>::read_records
             at ./src/arrow/record_reader.rs:196:31
   8: parquet::arrow::array_reader::read_records
             at ./src/arrow/array_reader.rs:137:33
   9: <parquet::arrow::array_reader::NullArrayReader<T> as parquet::arrow::array_reader::ArrayReader>::next_batch
             at ./src/arrow/array_reader.rs:209:13
  10: <parquet::arrow::array_reader::StructArrayReader as parquet::arrow::array_reader::ArrayReader>::next_batch::{{closure}}
             at ./src/arrow/array_reader.rs:1202:27
  11: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:91:28
  12: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:1995:21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:117:9
  14: <parquet::arrow::array_reader::StructArrayReader as parquet::arrow::array_reader::ArrayReader>::next_batch
             at ./src/arrow/array_reader.rs:1199:30
  15: <parquet::arrow::arrow_reader::ParquetRecordBatchReader as core::iter::traits::iterator::Iterator>::next
             at ./src/arrow/arrow_reader.rs:177:15
  16: parquet::arrow::arrow_reader::tests::test_single_null_i32
             at ./src/arrow/arrow_reader.rs:1000:22
  17: parquet::arrow::arrow_reader::tests::test_single_null_i32::{{closure}}
             at ./src/arrow/arrow_reader.rs:990:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test arrow::arrow_reader::tests::test_single_null_i32 ... FAILED
```

**To Reproduce**

Run the test from this branch.

https://github.com/bjchambers/arrow-rs/tree/repro-parquet-panic

https://github.com/bjchambers/arrow-rs/blob/repro-parquet-panic/parquet/src/arrow/arrow_reader.rs#L990

**Expected behavior**

Not a panic. The behavior in `6.3.0` was expected.

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1245.

# Rationale for this change
 
Originally reported by @bjchambers, a sanity check added in #1054 fires when reading NullArrays. 

This highlighted two problems:

* `NullArrayReader` has always been somewhat broken as it would never flush the accumulated null buffer, instead just growing it indefinitely
* There were literally no tests for NullArrayReader :scream: 

# What changes are included in this PR?

Fixes the panic, and adds a basic test of the `NullArrayReader`

# Are there any user-facing changes?

NullArrayReader should work again

### CODE REVIEW

File: parquet/src/arrow/array_reader.rs [hunk 1]
```diff
@@ -214,6 +214,10 @@ where
         // save definition and repetition buffers
         self.def_levels_buffer = self.record_reader.consume_def_levels()?;
         self.rep_levels_buffer = self.record_reader.consume_rep_levels()?;
+
+        // Must consume bitmap buffer
+        self.record_reader.consume_bitmap_buffer()?;
```
Comment (tustvold) [inline parquet/src/arrow/array_reader.rs:219]: Why this is even getting computed at all is definitely a valid question, but at the same time a workload where the speed of reading arrays of nulls is the bottleneck feels decidedly... niche :laughing:

Comment (bjchambers) [reply parquet/src/arrow/array_reader.rs:219]: One place it comes up is where you have multiple Parquet files representing a "table", with one or more columns being relatively sparse. If you have a file dropped every hour, then it may be that some of the files have a null column while others have a few values.

It doesn't seem likely it would be the bottleneck (the other columns in the file probably would be), but that's at least how it's come up for us.

Comment (tustvold) [reply parquet/src/arrow/array_reader.rs:219]: Yeah, I didn't mean to suggest NullArrayReader itself is niche, but rather there is probably a limited benefit to optimising it to not compute the bitmask unnecessarily :smile:

**Review by alamb — APPROVED** [review]
Thanks @tustvold  -- I'll get this out in arrow 9.0.0 next week; I can try to release a patchset sooner if you need @bjchambers

**Comment by bjchambers** [comment]
No need to rush. Next week should be fine. I can just wait to upgrade until
this is out. Thanks for the speedy fix!
