### PR TITLE
RecordBatchDecoder: skip RecordBatch validation when `skip_validation` property is enabled

### LINKED ISSUE #7508: The `read_record_batch` func of the `RecordBatchDecoder` does not respect the `skip_validation` property
**Describe the bug**

We created a `StreamReader` with `with_skip_validation(true)` and still ran into validation errors.

We noticed that not all validation steps are skipped. The [record_batch_reader](https://github.com/apache/arrow-rs/blob/1f15130414bdfc01c8989ec95702655bf553c5c5/arrow-ipc/src/reader.rs#L470)
function does not respect the `skip_validation` property and simply calls `RecordBatch::try_new_with_options` instead of `RecordBatch::new_unchecked`.

**To Reproduce**

**Expected behavior**
Skip the validation logic by calling `RecordBatch::new_unchecked` if `skip_validation` is set to true.

**Additional context**

### PR DESCRIPTION
**Pull request by nilskch**
# Which issue does this PR close?
This is kind of a niche issue, but at the very least there should be some performance gains. We have to deal with legacy files that don't exactly follow the spec, so we rely on skipping the validation not because of performance reasons, but because the spec is incorrectly implemented by custom legacy libs (on the consuming and the producing side).

Closes #7508.

# Rationale for this change
When you create a `StreamReader` with the unsafe config `with_skip_validation(true)`, the `RecordBatch`'es still get validated [here](https://github.com/nilskch/arrow-rs/blob/1f15130414bdfc01c8989ec95702655bf553c5c5/arrow-array/src/record_batch.rs#L300), because the `read_record_batch` func of the `RecordBatchDecoder` did not respect the `skip_validation` property.

# What changes are included in this PR?
The validation logic for creating `RecordBatch`es gets skipped if `skip_validation` is set to true.

# Are there any user-facing changes?
No, unless they relied on the validation logic even though they explicitly set the `skip_validation` property to true.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you for this contribution @nilskch 

>  but because the spec is incorrectly implemented by custom legacy libs (on the consuming and the producing side).

What is the problem you are hitting? I don't see anything fundamentally wrong with disabling this validation, but it would surprise me if it solved your actual problem 

Turning off validation is not going to solve incorrectly created data

Given the RecordBatch validation is pretty minimal (checking data types match) if any of those validations fails, it is likely some other call will error later on or maybe you'll silently get wrong answers

**Comment by nilskch** [comment]
Yeah this is a very unique issue. We have custom legacy Java code that implements the arrow spec and it is not correct in all edge cases. We use this lib to download those (slightly incorrect) files and write them to parquet and it works if we skip the validation step for some reason. We are working on getting rid of that custom legacy implementation.

I saw that you have an option to skip the validation and thought that you might be interested in this proposed change. It fixes a very specific error that a user reported, but it is not the long term solution for us.

File: arrow-ipc/src/reader.rs [hunk 1]
```diff
@@ -490,22 +490,44 @@ impl<'a> RecordBatchDecoder<'a> {
...
-                Arc::new(schema.project(projection)?),
-                arrays.into_iter().map(|t| t.1).collect(),
-                &options,
-            )
+
+            let schema = Arc::new(schema.project(projection)?);
+            let columns = arrays.into_iter().map(|t| t.1).collect::<Vec<_>>();
+
+            if self.skip_validation.get() {
+                unsafe {
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:500]: I think we typically add a comment to justify the use of any unsafe code. 
```suggestion
                // Safety: setting `skip_validation` requires `unsafe`, user assures data is valid
                unsafe {
```

File: arrow-ipc/src/reader.rs [hunk 2]
```diff
@@ -490,22 +490,44 @@ impl<'a> RecordBatchDecoder<'a> {
...
             // keep track of index as lists require more than one node
             for field in schema.fields() {
                 let child = self.create_array(field, &mut variadic_counts)?;
                 children.push(child);
             }
-            assert!(variadic_counts.is_empty());
-            RecordBatch::try_new_with_options(schema, children, &options)
+
+            if self.skip_validation.get() {
+                unsafe {
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:520]:
```suggestion
                // Safety: setting `skip_validation` requires `unsafe`, user assures data is valid
                unsafe {
```

**Review by alamb — APPROVED** [review]
I think this is a reasonable PR. Thank you @nilskch 

I would be interested in other maintainers opinions (cc @mbrobbel @Jefffrey @etseidl or @tustvold  for example)

**Review by mbrobbel — APPROVED** [review]

**Review by etseidl — APPROVED** [review]
Seems consistent with the intent of the flag.

**Comment by alamb** [comment]
Thanks again @nilskch and @etseidl
