### PR TITLE
Fix like regex escaping

### LINKED ISSUE #1069: Arrow comparison `LIKE`/`ILIKE`/`NLIKE` kernels do not escape all special characters
**Describe the bug**

Characters such as `[` and `.` are sometimes treated as regular expressions rather than literals in regular expressions

The arrow regular expression kernels such as `like_utf8` https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/comparison.rs#L311-L323 take limited SQL style string matching patterns (e.g. `%`). 

However, under the covers a regular expression matching library is used but special regular expression characters are not escaped. @ovr  added code to handle `(` and `)` in https://github.com/apache/arrow-rs/pull/1042 but there are other special characters as well

**To Reproduce**

```rust
    let array: StringArray = vec!["foo", "bar", "baz"]
        .into_iter()
        .map(Some)
        .collect();

    let comparison = arrow::compute::like_utf8_scalar(&array, "foo%.*").unwrap();

    let expected: BooleanArray = vec![false, false, false]
        .into_iter()
        .map(Some)
        .collect();

    assert_eq!(comparison, expected);
```

**Expected behavior**
This test should pass (is what postgres produces)

```sql
alamb=# select * from foo;
  x  
-----
 foo
 bar
 baz
(3 rows)

alamb=# select x, x like 'foo%.*' from foo;
  x  | ?column? 
-----+----------
 foo | f
 bar | f
 baz | f
(3 rows)
```

**Additional context**
Follow on to https://github.com/apache/arrow-rs/pull/1042 where @ovr  fixed the parenthesis issue

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #1069

# Rationale for this change
 
 

Fixes `like` not to handle regex syntax like `.*` and `.` but escapes it.  

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/compute/kernels/comparison.rs [hunk 1]
```diff
@@ -303,7 +303,7 @@ where
 /// use arrow::compute::like_utf8;
 ///
 /// let strings = StringArray::from(vec!["Arrow", "Arrow", "Arrow", "Ar"]);
-/// let patterns = StringArray::from(vec!["A%", "B%", "A.", "A."]);
+/// let patterns = StringArray::from(vec!["A%", "B%", "A.", "A_"]);
```
Comment (Dandandan) [inline arrow/src/compute/kernels/comparison.rs:306]: Lol - even the doctest here was relying on a non-escaped `.`

**Comment by jwdeitch** [comment]
thanks for the PR! looks good!
I think there may be an outstanding escaping issue in where right-hand side is '%%%' and you want to match on '(literal%)_(literal%)'.... but this problem may be outside the scope of this fix. :)

File: arrow/src/compute/kernels/comparison.rs [hunk 2]
```diff
@@ -259,14 +259,14 @@ where
     let mut result = BooleanBufferBuilder::new(left.len());
     for i in 0..left.len() {
         let haystack = left.value(i);
-        let pat = right.value(i);
-        let re = if let Some(ref regex) = map.get(pat) {
+        let pat = escape(right.value(i));
+        let re = if let Some(ref regex) = map.get(&pat) {
             regex
         } else {
             let re_pattern = pat.replace("%", ".*").replace("_", ".");
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:266]: Do we still need this `pat.replace` call?

Comment (Dandandan) [reply arrow/src/compute/kernels/comparison.rs:266]: Yeah to make a proper regex out of it (instead of literally matching on the percentage or underscore character).

Comment (Dandandan) [reply arrow/src/compute/kernels/comparison.rs]: But we could minimize some borrow / cloning by moving the `escape`... So now it looks more similar to the other places.

File: arrow/src/compute/kernels/comparison.rs [hunk 3]
```diff
@@ -259,14 +259,14 @@ where
...
     for i in 0..left.len() {
         let haystack = left.value(i);
-        let pat = escape(right.value(i));
-        let re = if let Some(ref regex) = map.get(&pat) {
+        let pat = right.value(i);
+        let re = if let Some(ref regex) = map.get(pat) {
             regex
         } else {
-            let re_pattern = pat.replace("%", ".*").replace("_", ".");
+            let re_pattern = escape(pat).replace("%", ".*").replace("_", ".");
```
Comment (alamb) [inline arrow/src/compute/kernels/comparison.rs:266]: 👍

**Review by alamb — APPROVED** [review]
Less code and fewer bugs -- now that is the sign of a great fix ❤️ 

Nice work -- looks great to me @Dandandan .

**Comment by alamb** [comment]
> I think there may be an outstanding escaping issue in where right-hand side is '%%%' and you want to match on '(literal%)_(literal%)'.... but this problem may be outside the scope of this fix. :)

We can file a follow on ticket, perhaps. If someone can whip up a reproducer that would be awesome 🤞

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-rs/issues/1087 to track the possible escaping problems
