### PR TITLE
[fix #5044] Support converting 'yyyymmdd' format to date

### LINKED ISSUE #5044: cast format 'yyyymmdd'  to Date32 give a error
**Describe the bug**
when cast string like '19990819' to Date32, it will give a error， but for '1999-08-19' it secceed

**To Reproduce**
In arrow-datafusion
For a date column run a query with the date in string format 'yyyymmdd' as shown below
```
--this query fails
select * from orders where o_orderdate = '19961006'
```
it get 
```
Arrow error: Cast error: Cannot cast string '19961006' to value of Date32 type
```

**Expected behavior**
This should return the correct result and not fail

**Additional context**

### PR DESCRIPTION
**Pull request by Tangruilin**
# Which issue does this PR close?
Closes #5044 .

# Rationale for this change
format "yyyymmdd" and "yymmdd" cannot be converted to DateType, which do not comply with the ISO standard
 
# What changes are included in this PR?
the way to parse "yyyymmdd" and "yymmdd" are added to parse_date

# Are there any user-facing changes?
no

### CODE REVIEW

File: arrow-cast/src/parse.rs [hunk 1]
```diff
@@ -560,7 +572,32 @@ fn parse_date(string: &str) -> Option<NaiveDate> {
...
+            8 => (
+                digits[0] as u16 * 1000
+                    + digits[1] as u16 * 100
+                    + digits[2] as u16 * 10
+                    + digits[3] as u16,
+                digits[4] * 10 + digits[5],
+                digits[6] * 10 + digits[7],
+            ),
+            _ => return None,
+        };
```
Comment (tustvold) [inline arrow-cast/src/parse.rs:599]:
```suggestion
        let (year, month, day) = match (mask, string.len()) {
            (0b111111, 6) => (
                parse_two_digit_year(digits[0] as i32 * 10 + digits[1] as i32) as u16,
                digits[2] * 10 + digits[3],
                digits[4] * 10 + digits[5],
            ),
            (0b11111111, 8) => (
                digits[0] as u16 * 1000
                    + digits[1] as u16 * 100
                    + digits[2] as u16 * 10
                    + digits[3] as u16,
                digits[4] * 10 + digits[5],
                digits[6] * 10 + digits[7],
            ),
            _ => return None,
        };
```

File: arrow-cast/src/parse.rs [hunk 2]
```diff
@@ -544,6 +544,18 @@ const EPOCH_DAYS_FROM_CE: i32 = 719_163;
 /// Error message if nanosecond conversion request beyond supported interval
 const ERR_NANOSECONDS_NOT_SUPPORTED: &str = "The dates that can be represented as nanoseconds have to be between 1677-09-21T00:12:44.0 and 2262-04-11T23:47:16.854775804";
 
+fn parse_two_digit_year(input_year: i32) -> i32 {
```
Comment (tustvold) [inline arrow-cast/src/parse.rs:547]: Could we get a doc comment explaining what this is doing, and perhaps linking to the docs of the system it is based on?

Comment (tustvold) [reply arrow-cast/src/parse.rs:547]: FWIW https://www.rfc-editor.org/rfc/rfc3339#section-3 explicitly disallows 2 digit years as they are ambiguous

**Comment by tustvold** [comment]
Marking as draft to show this isn't waiting on a review, feel free to unmark when you would like me to take another look

File: arrow-cast/src/parse.rs (hunk 2 above)
Comment (Tangruilin) [reply arrow-cast/src/parse.rs:547]: > FWIW https://www.rfc-editor.org/rfc/rfc3339#section-3 explicitly disallows 2 digit years as they are ambiguous

It refer to ![https://www.postgresql.org/docs/current/datatype-datetime.html]https://www.postgresql.org/docs/current/datatype-datetime.html.

Comment (Tangruilin) [reply arrow-cast/src/parse.rs:547]: > FWIW https://www.rfc-editor.org/rfc/rfc3339#section-3 explicitly disallows 2 digit years as they are ambiguous

image
Maybe you need to make a decision if two digit year should be supported, and I will finish this PR by the decision.

Comment (tustvold) [reply arrow-cast/src/parse.rs:547]: I think we should not support them

Comment (Tangruilin) [reply arrow-cast/src/parse.rs:547]: > I think we should not support them

Okey. I will modify the code. Thanks for suggestion

File: arrow-cast/src/parse.rs [hunk 3]
```diff
@@ -559,8 +559,30 @@ fn parse_date(string: &str) -> Option<NaiveDate> {
...
+        if string.len() != 8 {
+            return None;
+        }
+
+        for ch in string.bytes() {
+            if !ch.is_ascii_digit() {
+                return None;
+            }
+        }
+
```
Comment (tustvold) [inline arrow-cast/src/parse.rs:573]:
```suggestion
```

The mask already validates this

File: arrow-cast/src/parse.rs [hunk 4]
```diff
@@ -559,8 +559,30 @@ fn parse_date(string: &str) -> Option<NaiveDate> {
 
     const HYPHEN: u8 = b'-'.wrapping_sub(b'0');
 
+    //  refer to https://www.rfc-editor.org/rfc/rfc3339#section-3
     if digits[4] != HYPHEN {
-        return None;
+        if string.len() != 8 {
+            return None;
+        }
```
Comment (tustvold) [inline arrow-cast/src/parse.rs:566]:
```suggestion
```

**Review by tustvold — APPROVED** [review]
I took the liberty of removing some redundant checks, this looks good now thank you

**Comment by Tangruilin** [comment]
> I took the liberty of removing some redundant checks, this looks good now thank you

I modify the code as comment, now you can retry it
