### PR TITLE
Respect Page Size Limits in ArrowWriter (#2853)

### LINKED ISSUE #2853: `parquet::arrow::arrow_writer::ArrowWriter` ignores page size properties
**Describe the bug**

`ArrowWrites` ignores page size properties when writing to parquet. It also seems to always write just two pages, the first one a normal sized page and all the remaining data in the second page. 

**To Reproduce**

```
    #[test]
    fn arrow_writer_page_size() {
        let mut rng = thread_rng();
        let schema = Arc::new(Schema::new(vec![Field::new("col", DataType::Utf8, false)]));

        let mut builder = StringBuilder::with_capacity(10_000, 2 * 10_0000);

        for _ in 0..100_000 {
            let value = (0..200)
                .map(|_| rng.gen_range(b'a'..=b'z') as char)
                .collect::<String>();

            builder.append_value(value);
        }

        let array = Arc::new(builder.finish());

        let batch = RecordBatch::try_new(schema, vec![array]).unwrap();

        let file = tempfile::tempfile().unwrap();

        let props = WriterProperties::builder()
            .set_max_row_group_size(usize::MAX)
            .set_data_pagesize_limit(512)
            .set_write_batch_size(512)
            .build();

        let mut writer = ArrowWriter::try_new(
            file.try_clone().unwrap(),
            batch.schema(),
            Some(props),
        )
            .expect("Unable to write file");
        writer.write(&batch).unwrap();
        writer.close().unwrap();

        let reader = SerializedFileReader::new(file.try_clone().unwrap()).unwrap();

        let column = reader.metadata().row_group(0).columns();

        let page_locations = read_pages_locations(&file, column).unwrap();

        let offset_index = page_locations[0].clone();

        assert!(offset_index.len() > 2, "Expected more than two pages but got {:#?}", offset_index);
    }
```

This outputs 
```
thread 'arrow::arrow_writer::tests::arrow_writer_page_size' panicked at 'Expected more than two pages but got [
    PageLocation {
        offset: 1148953,
        compressed_page_size: 9595,
        first_row_index: 0,
    },
    PageLocation {
        offset: 1158548,
        compressed_page_size: 19251505,
        first_row_index: 5632,
    },
]'
```

**Expected behavior**

The writer should respect the page size properties and write similarly sized pages. 

**Additional context**

### LINKED ISSUE #2889: Overly Pessimistic RLE Size Estimation
**Describe the bug**

The size of RLE encoded data is routinely estimated as

```
RleEncoder::min_buffer_size(bit_width)
            + RleEncoder::max_buffer_size(bit_width, self.indices.len())
```

Where `RleEncoder::min_buffer_size` is defined as 

```
let max_bit_packed_run_size = 1 + bit_util::ceil(
    (MAX_VALUES_PER_BIT_PACKED_RUN * bit_width as usize) as i64,
    8,
);
let max_rle_run_size =
    bit_util::MAX_VLQ_BYTE_LEN + bit_util::ceil(bit_width as i64, 8) as usize;
std::cmp::max(max_bit_packed_run_size as usize, max_rle_run_size)
```
In practice this will almost always be `64 * bit_width`. 

```
let bytes_per_run = bit_width;
let num_runs = bit_util::ceil(num_values as i64, 8) as usize;
let bit_packed_max_size = num_runs + num_runs * bytes_per_run as usize;

let min_rle_run_size = 1 + bit_util::ceil(bit_width as i64, 8) as usize;
let rle_max_size =
    bit_util::ceil(num_values as i64, 8) as usize * min_rle_run_size;
std::cmp::max(bit_packed_max_size, rle_max_size) as usize
```

**To Reproduce**

It is unclear why min_buffer_size is included in the size estimation at all

**Expected behavior**

A more accurate size estimation of written RLE encoded data

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2853
Closes #2889 

# Rationale for this change
 

See tickets

# What changes are included in this PR?

Fixes an issue where size estimation was broken for primitive columns and dictionary encoded pages, which prevented the page size limit from being respected. Similar to #2854 

Also tweaks the RLE size estimation as it was overly pessimistic

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/column/writer/encoder.rs [hunk 1]
```diff
@@ -201,6 +201,7 @@ impl<T: DataType> ColumnValueEncoder for ColumnValueEncoderImpl<T> {
     }
 
     fn write_gather(&mut self, values: &Self::Values, indices: &[usize]) -> Result<()> {
+        self.num_values += indices.len();
```
Comment (tustvold) [inline parquet/src/column/writer/encoder.rs:204]: This is the fix for #2853

File: parquet/src/arrow/arrow_writer/byte_array.rs [hunk 2]
```diff
@@ -487,7 +484,10 @@ impl ColumnValueEncoder for ByteArrayEncoder {
     }
 
     fn num_values(&self) -> usize {
-        self.num_values
+        match &self.dict_encoder {
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer/byte_array.rs:487]: Without this, we would only ever have a single dictionary encoded page per column chunk. This is the other half of the fix in https://github.com/apache/arrow-rs/pull/2854

Comment (alamb) [reply parquet/src/arrow/arrow_writer/byte_array.rs:487]: maybe it is worth a comment

File: parquet/src/column/writer/mod.rs [hunk 3]
```diff
@@ -1825,7 +1825,7 @@ mod tests {
         let page_writer = Box::new(SerializedPageWriter::new(&mut writer));
         let props = Arc::new(
             WriterProperties::builder()
-                .set_data_pagesize_limit(15) // actually each page will have size 15-18 bytes
+                .set_data_pagesize_limit(10)
```
Comment (alamb) [inline parquet/src/column/writer/mod.rs:1828]: I don't understand this change

File: parquet/src/encodings/encoding/mod.rs [hunk 4]
```diff
@@ -888,7 +888,7 @@ mod tests {
         // DICTIONARY
         // NOTE: The final size is almost the same because the dictionary entries are
         // preserved after encoded values have been written.
-        run_test::<Int32Type>(Encoding::RLE_DICTIONARY, -1, &[123, 1024], 11, 68, 66);
+        run_test::<Int32Type>(Encoding::RLE_DICTIONARY, -1, &[123, 1024], 0, 2, 0);
```
Comment (alamb) [inline parquet/src/encodings/encoding/mod.rs:891]: can you explain these changes?

File: parquet/src/encodings/levels.rs [hunk 5]
```diff
@@ -38,13 +38,8 @@ pub fn max_buffer_size(
...
     let bit_width = num_required_bits(max_level as u64);
     match encoding {
-        Encoding::RLE => {
-            RleEncoder::max_buffer_size(bit_width, num_buffered_values)
-                + RleEncoder::min_buffer_size(bit_width)
-        }
-        Encoding::BIT_PACKED => {
-            ceil((num_buffered_values * bit_width as usize) as i64, 8) as usize
-        }
+        Encoding::RLE => RleEncoder::max_buffer_size(bit_width, num_buffered_values),
```
Comment (alamb) [inline parquet/src/encodings/levels.rs:41]: why is this different than the other estimated sizes?

File: parquet/src/encodings/rle.rs [hunk 6]
```diff
@@ -101,29 +100,33 @@ impl RleEncoder {
...
-        let max_bit_packed_run_size = 1 + bit_util::ceil(
-            (MAX_VALUES_PER_BIT_PACKED_RUN * bit_width as usize) as i64,
-            8,
-        );
-        let max_rle_run_size =
-            bit_util::MAX_VLQ_BYTE_LEN + bit_util::ceil(bit_width as i64, 8) as usize;
-        std::cmp::max(max_bit_packed_run_size as usize, max_rle_run_size)
+        let b = bit_width as usize;
+        let max_bit_packed_run_size = 1 + MAX_GROUPS_PER_BIT_PACKED_RUN * b;
+        let max_rle_run_size = 1 + bit_util::ceil(b, 8);
```
Comment (alamb) [inline parquet/src/encodings/rle.rs:107]: `max_rle_run_size` seems to have lost `bit_util::MAX_VLQ_BYTE_LEN` --  is that intentional?

Comment (alamb) [reply parquet/src/encodings/rle.rs:107]: I think it would also help either to name  the magic `1` constants or add comments explaining where they came from

File: parquet/src/encodings/rle.rs [hunk 7]
```diff
@@ -101,29 +100,33 @@ impl RleEncoder {
 
     /// Returns the minimum buffer size needed to use the encoder for `bit_width`.
     /// This is the maximum length of a single run for `bit_width`.
+    #[allow(unused)]
```
Comment (alamb) [inline parquet/src/encodings/rle.rs:103]: why is this unused?

File: parquet/tests/arrow_writer_layout.rs [hunk 8]
```diff
@@ -0,0 +1,472 @@
...
+    // Re-read file to decode column index
+    let read_options = ArrowReaderOptions::new().with_page_index(true);
+    let reader =
+        ParquetRecordBatchReaderBuilder::try_new_with_options(b.clone(), read_options)
+            .unwrap();
+
+    assert_layout(&b, reader.metadata().as_ref(), &test.layout);
+}
+
+fn assert_layout(file_reader: &Bytes, meta: &ParquetMetaData, layout: &Layout) {
```
Comment (alamb) [inline parquet/tests/arrow_writer_layout.rs:79]: 😮  -- very nice 🏆

File: parquet/tests/arrow_writer_layout.rs [hunk 9]
```diff
@@ -0,0 +1,472 @@
...
+                    }),
+                }],
+            }],
+        },
+    });
+}
+
+#[test]
+fn test_string() {
+    let array = Arc::new(StringArray::from_iter_values(
```
Comment (alamb) [inline parquet/tests/arrow_writer_layout.rs:315]: does this cover the code in `parquet/src/arrow/arrow_writer/byte_array.rs` ?

File: parquet/tests/arrow_writer_layout.rs [hunk 10]
```diff
@@ -0,0 +1,472 @@
...
+                            rows: 330,
+                            page_header_size: 34,
+                            compressed_size: 464,
+                            encoding: Encoding::RLE_DICTIONARY,
+                            page_type: PageType::DATA_PAGE,
+                        },
+                        Page {
+                            rows: 330,
+                            page_header_size: 34,
+                            compressed_size: 464,
```
Comment (alamb) [inline parquet/tests/arrow_writer_layout.rs:281]: is it ok / expected that the compressed sizes are lower than the limit (500)?

File: parquet/tests/arrow_writer_layout.rs [hunk 11]
```diff
@@ -0,0 +1,472 @@
...
+        .build();
+
+    do_test(LayoutTest {
+        props,
+        batches: vec![batch.clone()],
+        layout: Layout {
+            row_groups: vec![RowGroup {
+                columns: vec![ColumnChunk {
+                    pages: vec![
+                        Page {
```
Comment (alamb) [inline parquet/tests/arrow_writer_layout.rs:369]: why did this dictionary spill? It wasn't at the dictionary page limit (1000) or the data pagesize limit (10000) that I can tell

**Review by alamb — APPROVED** [review]
I had a bunch of questions, but based on the tests alone I am approving this PR. Nice work @tustvold 

I think we should get at least one more pair of eyes on this PR prior to merging it

cc @thinkharderdev and @Ted-Jiang @sunchao

File: parquet/src/column/writer/mod.rs (hunk 3 above)
Comment (tustvold) [reply parquet/src/column/writer/mod.rs:1828]: The RLE size estimation has changed, and so this test needed updating

File: parquet/src/encodings/encoding/mod.rs (hunk 4 above)
Comment (tustvold) [reply parquet/src/encodings/encoding/mod.rs:891]: The RLE size estimation was updated as part of #2889

File: parquet/src/encodings/rle.rs (hunk 7 above)
Comment (tustvold) [reply parquet/src/encodings/rle.rs:103]: Because it isn't used anywhere in the codebase, but theoretically this could be being used by someone making use of the experimental feature flag. I could just remove it?

File: parquet/src/encodings/levels.rs (hunk 5 above)
Comment (tustvold) [reply parquet/src/encodings/levels.rs:41]: What other estimated sizes, I think I updated them all?

File: parquet/tests/arrow_writer_layout.rs (hunk 10 above)
Comment (tustvold) [reply parquet/tests/arrow_writer_layout.rs:281]: Yeah, the limit is just a best guess and not strictly enforced

File: parquet/tests/arrow_writer_layout.rs (hunk 9 above)
Comment (tustvold) [reply parquet/tests/arrow_writer_layout.rs:315]: Yes

File: parquet/tests/arrow_writer_layout.rs (hunk 11 above)
Comment (tustvold) [reply parquet/tests/arrow_writer_layout.rs:369]: The dictionary is 1040 bytes and therefore spilled?

File: parquet/src/encodings/rle.rs (hunk 6 above)
Comment (tustvold) [reply parquet/src/encodings/rle.rs:107]: Tbh I don't really understand what this method was ever measuring... I will just remove it

File: parquet/src/arrow/arrow_writer/byte_array.rs (hunk 2 above)
Comment (tustvold) [reply parquet/src/arrow/arrow_writer/byte_array.rs:487]: The confusion was that we tracked num_values in two places, that is now gone so I'm not sure what to write in a comment...

File: parquet/tests/arrow_writer_layout.rs (hunk 11 above)
Comment (alamb) [reply parquet/tests/arrow_writer_layout.rs:369]: I must be missing something. The first page is 

```
                            page_header_size: 34,
                            compressed_size: 138,
```

though the actual dictionary page is 

```
                        page_header_size: 34,
                        compressed_size: 1040,
```

Comment (tustvold) [reply parquet/tests/arrow_writer_layout.rs:369]: The first page is the dictionary keys, i.e. the integers. The dictionary spills because the dictionary page, i.e. the string values exceeds the limit of 1000 set by `.set_dictionary_pagesize_limit(1000)`

**Comment by tustvold** [comment]
I'm going to get this in so that I can base some changes off it, I'll address any further review comments in follow up PRs
