### PR TITLE
fix: [9018]Fixed RunArray slice offsets(row, cast, eq)

### LINKED ISSUE #9018: Kernels don't account for slicing of `RunArray`s
**Describe the bug**

Certain kernels when operating on `RunArray`s don't account for them potentially being sliced, meaning they can return incorrect results.

**To Reproduce**

See following tests:

https://github.com/apache/arrow-rs/blob/addf74d72d88684dabac21822c22f35e803135c5/arrow-cast/src/cast/mod.rs#L11748-L11763

https://github.com/apache/arrow-rs/blob/addf74d72d88684dabac21822c22f35e803135c5/arrow-select/src/concat.rs#L1718-L1741

https://github.com/apache/arrow-rs/blob/addf74d72d88684dabac21822c22f35e803135c5/arrow-select/src/filter.rs#L1357-L1375

https://github.com/apache/arrow-rs/blob/addf74d72d88684dabac21822c22f35e803135c5/arrow-select/src/interleave.rs#L1174-L1198

These are not necessarily exhaustive; they are just the ones I found. The only other kernel I checked was take, which seemed fine:

https://github.com/apache/arrow-rs/blob/addf74d72d88684dabac21822c22f35e803135c5/arrow-select/src/take.rs#L2441-L2460

**Expected behavior**

Kernels should account for slicing when operating on `RunArray`s.

**Additional context**

In fixing these kernels we should see if we can enhance the RunArray/RunEndBuffer APIs to make it easier to handle sliced arrays; for example in https://github.com/apache/datafusion/pull/18981 I found it a bit confusing to try understand what's going on, since there was logic to manually slice the values ourselves.

### PR DESCRIPTION
**Pull request by manishkr**
# Which issue does this PR close?

- Closes #9018 .

# Rationale for this change

The existing implementation had issue for row or cast ops for RunArray. The equality implementation also did not support logical index-based comparisons.
# What changes are included in this PR?

1. Fixed RunArray row and cast handling
2. Added logical index based equality check for RunArray.
# Are these changes tested?

Yes
# Are there any user-facing changes?

No.

### CODE REVIEW

File: arrow-array/src/array/run_array.rs [hunk 1]
```diff
@@ -141,6 +141,9 @@ impl<R: RunEndIndexType> RunArray<R> {
     ///
     /// [`values`]: Self::values
     pub fn values_slice(&self) -> ArrayRef {
+        if self.len() == 0 {
```
Comment (Jefffrey) [inline arrow-array/src/array/run_array.rs]: Could we add a test case for this

File: arrow-buffer/src/buffer/run.rs [hunk 2]
```diff
@@ -199,9 +199,14 @@ where
     pub fn sliced_values(&self) -> impl Iterator<Item = E> + '_ {
         let offset = self.logical_offset;
         let len = self.logical_length;
-        let start = self.get_start_physical_index();
-        let end = self.get_end_physical_index();
-        self.run_ends[start..=end].iter().map(move |&val| {
+        let physical_slice = if len == 0 {
```
Comment (Jefffrey) [inline arrow-buffer/src/buffer/run.rs]: Thanks for this, I'll close my PR in favour of this (#9200)

Could you add the tests I had in my PR though

```rust
// arrow-array/src/array/run_array.rs
    #[test]
    fn test_run_array_empty() {
        let runs = new_empty_array(&DataType::Int16);
        let runs = runs.as_primitive::<Int16Type>();
        let values = new_empty_array(&DataType::Int64);
        let array = RunArray::try_new(runs, &values).unwrap();

        fn assertions(array: &RunArray<Int16Type>) {
            assert!(array.is_empty());
            assert_eq!(array.get_start_physical_index(), 0);
            assert_eq!(array.get_end_physical_index(), 0);
            assert!(array.get_physical_indices::<i16>(&[]).unwrap().is_empty());
            assert!(array.run_ends().is_empty());
            assert_eq!(array.run_ends().sliced_values().count(), 0);
        }

        assertions(&array);
        assertions(&array.slice(0, 0));
    }
```

File: arrow-data/src/equal/run.rs [hunk 3]
```diff
@@ -16,71 +16,122 @@
...
+    rhs: &ArrayData,
+    lhs_start: usize,
+    rhs_start: usize,
+    len: usize,
+) -> bool {
+    if len == 0 {
+        return true;
     }
+    // RunEndEncoded arrays are guaranteed to have at least 2 children [run_ends, values]
+    let lhs_run_ends_data = &lhs.child_data()[0];
```
Comment (Jefffrey) [inline arrow-data/src/equal/run.rs]: There is a lot of local variables in play in this function. Can we refactor to:

- Try eliminate local variables where possible (e.g. introduce small functions or blocks to clearly delineate where local variables are useful for)
- Look into using a struct to collate the field for left vs right (e.g a struct holding `values`, `run_ends`, etc. by reference) to make it easier to read the left vs right

File: arrow-array/src/array/run_array.rs [hunk 4]
```diff
@@ -1173,4 +1176,56 @@ mod tests {
         let values_slice2 = values_slice2.as_primitive::<Int32Type>();
         assert_eq!(values_slice2.values(), &[1]);
     }
+
+    #[test]
+    fn test_run_array_eq_diff_physical_same_logical() {
```
Comment (Jefffrey) [inline arrow-array/src/array/run_array.rs:1248]: Could we also add some cases checking empty run arrays

File: arrow-array/src/array/run_array.rs (hunk 1 above)
Comment (manishkr) [reply arrow-array/src/array/run_array.rs]: Done. Thanks

File: arrow-buffer/src/buffer/run.rs (hunk 2 above)
Comment (manishkr) [reply arrow-buffer/src/buffer/run.rs]: Done, Thanks. Also, added comment from your PR.

File: arrow-data/src/equal/run.rs (hunk 3 above)
Comment (manishkr) [reply arrow-data/src/equal/run.rs]: Thanks for suggestion. Refactored it.

File: arrow-array/src/array/run_array.rs (hunk 4 above)
Comment (manishkr) [reply arrow-array/src/array/run_array.rs:1248]: Done, Thanks.

File: arrow-data/src/equal/run.rs [hunk 5]
```diff
@@ -16,71 +16,148 @@
...
+    abs_start: usize,
+}
 
-    if lhs.len() != rhs.len() {
-        return false;
+impl<'a, T: ArrowNativeType + ToPrimitive> RunArrayData<'a, T> {
+    fn new(data: &'a ArrayData, start: usize) -> Self {
+        debug_assert!(
+            data.child_data().len() >= 2,
+            "RunEndEncoded arrays are guaranteed to have at least 2 children [run_ends, values]"
```
Comment (Jefffrey) [inline arrow-data/src/equal/run.rs]:
```suggestion
            data.child_data().len() == 2,
            "RunEndEncoded arrays are guaranteed to have 2 children [run_ends, values]"
```

File: arrow-data/src/equal/run.rs [hunk 6]
```diff
@@ -16,71 +16,148 @@
...
+        (l_start, r_start, l_end - l_start + 1, r_end - r_start + 1)
+    };
+
+    if l_runs == r_runs {
+        let physical_match = l_array.run_ends[l_start_phys..l_start_phys + l_runs - 1]
+            .iter()
+            .zip(&r_array.run_ends[r_start_phys..r_start_phys + r_runs - 1])
+            .all(|(l_re, r_re)| {
+                l_re.as_usize() - l_array.abs_start == r_re.as_usize() - r_array.abs_start
+            });
```
Comment (Jefffrey) [inline arrow-data/src/equal/run.rs]:
```suggestion
        let l_iter = l_array.run_ends.iter().skip(l_start_phys).take(l_runs);
        let r_iter = r_array.run_ends.iter().skip(r_start_phys).take(r_runs);
        let physical_match = l_iter.zip(r_iter).all(|(l_re, r_re)| {
            l_re.as_usize() - l_array.abs_start == r_re.as_usize() - r_array.abs_start
        });
```

It was a bit confusing to see `l_runs` calculated as `l_end - l_start + 1` but then here we essentially rebuild `l_ends` because we left it behind in the scope above. More clean this way using iterator API.

Also could we leave an explanation of what this check means? `physical_match` doesn't exactly describe what check is being done here 🤔

File: arrow-data/src/equal/run.rs [hunk 7]
```diff
@@ -16,71 +16,148 @@
...
-    if lhs.len() != rhs.len() {
-        return false;
+impl<'a, T: ArrowNativeType + ToPrimitive> RunArrayData<'a, T> {
+    fn new(data: &'a ArrayData, start: usize) -> Self {
+        debug_assert!(
+            data.child_data().len() >= 2,
+            "RunEndEncoded arrays are guaranteed to have at least 2 children [run_ends, values]"
+        );
+        let run_ends_data = &data.child_data()[0];
+        let run_ends = &run_ends_data.buffers()[0].typed_data::<T>()
```
Comment (Jefffrey) [inline arrow-data/src/equal/run.rs]: I do wonder if we're better off doing something like this:

```rust
        let raw_run_ends_buffer = &run_ends_data.buffers()[0];
        // SAFETY: we're reconstructing RunEndBuffer from a known valid RunArray
        let run_ends = unsafe {
            RunEndBuffer::<T>::new_unchecked(
                raw_run_ends_buffer.clone().into(),
                run_ends_data.offset(),
                run_ends_data.len(),
            )
        };
```

This way we can reuse the code to search for physical indices from `RunEndBuffer`, at the cost of a clone of `Buffer` (which is just an `Arc` and usize + ptr) 🤔

File: arrow-data/src/equal/run.rs [hunk 8]
```diff
@@ -16,71 +16,148 @@
...
+        processed += step;
+
+        if processed < len {
+            if l_array.abs_start + processed == l_run_end {
+                l_phys += 1;
+            }
+            if r_array.abs_start + processed == r_run_end {
+                r_phys += 1;
+            }
+        }
```
Comment (Jefffrey) [inline arrow-data/src/equal/run.rs:158]: Can we explain these steps? They don't seem clearly obvious to me, especially the multiple `min`

File: arrow-data/src/equal/run.rs (hunk 5 above)
Comment (manishkr) [reply arrow-data/src/equal/run.rs]: Changed. Thanks.

File: arrow-data/src/equal/run.rs (hunk 6 above)
Comment (manishkr) [reply arrow-data/src/equal/run.rs]: Changed it accordingly RunEndBuffer related struct changes. Thanks

File: arrow-data/src/equal/run.rs (hunk 7 above)
Comment (manishkr) [reply arrow-data/src/equal/run.rs]: Changed. Thanks

File: arrow-data/src/equal/run.rs (hunk 8 above)
Comment (manishkr) [reply arrow-data/src/equal/run.rs:158]: Added comment to explain it. Basically it's finding minimum chunk of sub-array that can be compared in equal_range, do you have any other idea in mind? Thanks.

File: arrow-data/src/equal/run.rs [hunk 9]
```diff
@@ -16,71 +16,149 @@
...
+    let l_array = RunArrayData::<T>::new(lhs, lhs_start, len);
+    let r_array = RunArrayData::<T>::new(rhs, rhs_start, len);
+
+    let (l_start_phys, l_end_phys) = l_array.get_start_end_physical_indices();
+    let (r_start_phys, r_end_phys) = r_array.get_start_end_physical_indices();
+    let l_runs = l_end_phys - l_start_phys + 1;
+    let r_runs = r_end_phys - r_start_phys + 1;
+
+    if l_runs == r_runs {
+        // When the boundaries align perfectly, we don't need the complex stepping loop that calculates overlaps.
```
Comment (Jefffrey) [inline arrow-data/src/equal/run.rs:107]: Thanks for these comments, they really helped my understanding of this code 👍

File: arrow-data/src/equal/run.rs [hunk 10]
```diff
@@ -16,71 +16,149 @@
...
+        //Find the smallest of these three to determine our step size
+        //The goal is to move the logical cursor (processed) forward as far as possible without:
+        //Crossing the boundary of a run in the left or right array (where the value might change).
+        //Going past the total length we were asked to compare.
+        let step = l_remaining_in_run
+            .min(r_remaining_in_run)
+            .min(remaining_in_range);
+        processed += step;
+
+        if processed < len {
```
Comment (Jefffrey) [inline arrow-data/src/equal/run.rs]: Can probably omit this if check? Because if `processed >= len` then next iteration will exit anyway

Comment (manishkr) [reply arrow-data/src/equal/run.rs]: Done, Thanks.

**Comment by alamb** [comment]
@brancz and @vegarsti  -- would you also be willing to review this PR as you have worked in this area recently?

**Comment by vegarsti** [comment]
> @brancz and @vegarsti -- would you also be willing to review this PR as you have worked in this area recently?

For sure!

**Comment by alamb** [comment]
Thank you @Jefffrey and @brancz

**Comment by vegarsti** [comment]
Sorry for not reviewing in time! Please don't give up on tagging me! 😄
