### PR TITLE
ObjectStore cleanup (#2587)

### LINKED ISSUE #2587: Unreleased Object Store Fails To Compile With Only GCP Feature
**Describe the bug**

Following #2509 the object_store crate no longer compiles with just the GCP feature enabled

**To Reproduce**

**Expected behavior**

It should compile and this should have been caught in CI

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2587

# Rationale for this change
 

Fixes compilation errors and warnings when building with only a subset of the features

# What changes are included in this PR?

Splits the oauth module into credential modules for the various object stores

# Are there any user-facing changes?

### CODE REVIEW

File: object_store/src/client/mod.rs [hunk 1]
```diff
@@ -18,8 +18,6 @@
 //! Generic utilities reqwest based ObjectStore implementations
 
 pub mod backoff;
-#[cfg(any(feature = "gcp", feature = "azure"))]
-pub mod oauth;
```
Comment (tustvold) [inline object_store/src/client/mod.rs:22]: The original hope of this module was that it would allow sharing code between the implementations, it transpires this isn't actually possible, so we might as well just split the module apart

**Comment by tustvold** [comment]
@roeap perhaps you would be able to give this a review?

**Comment by roeap** [comment]
I would! Currently still traveling, but should get it done this we.

File: object_store/src/client/mod.rs (hunk 1 above)
Comment (roeap) [reply object_store/src/client/mod.rs:22]: makes absolute sense. I have not yet lost all hope, as we may be able to share for equivalent auth methods. I.e. I am hoping to add certificate based auth as in gcp, as well as managed / workload identity that should be similar to what aws is doing with the ec2 instance like stuff. But we'll see how that works out.

File: object_store/src/azure/credential.rs [hunk 2]
```diff
@@ -38,6 +43,18 @@ pub(crate) static DELETE_SNAPSHOTS: HeaderName =
 pub(crate) static COPY_SOURCE: HeaderName = HeaderName::from_static("x-ms-copy-source");
 static CONTENT_MD5: HeaderName = HeaderName::from_static("content-md5");
 pub(crate) static RFC1123_FMT: &str = "%a, %d %h %Y %T GMT";
+const CONTENT_TYPE_JSON: &str = "application/json";
+
+#[derive(Debug, Snafu)]
+pub enum Error {
```
Comment (roeap) [inline object_store/src/azure/credential.rs:49]: More of a general question, since recently I have been wondering what errors should look like. Thus far I very much like the approach taken in object_store, having very specific errors internal to the modules, and surfacing it all in a single error type to the user. Users might still work with this local error via downcasting the genric type in the Generic folder, but i was wondering if the approach should be to make al interna errors private to the crate, and have top level variants, for everything we think the consumer might handle specifically.

**Review by roeap — APPROVED** [review]
LGTM! left some minor questions, but these may safely be ignored :)

Just for the sake of consistency with aws/azure, should the gcp.rs file be mod.rs in the gcp folder?

File: object_store/src/azure/credential.rs (hunk 2 above)
Comment (tustvold) [reply object_store/src/azure/credential.rs:49]: That is definitely the approach, this module is crate private and therefore so is the error.

**Comment by tustvold** [comment]
I intend to move the module as a follow up, I didn't to avoid messing up the diff (GitHub's UI is not very smart)
