### PR TITLE
Fix `Result` name collision in parquet_derive

### LINKED ISSUE #7547: Parquet derive fails to build when Result is aliased
**Describe the bug**
Right now 

**To Reproduce**

Attempting to compile something where `Result` is aliased to something with a different signature (which I feel is a common pattern), fails to compile bc the proc macro generates code that uses that type, rather than the `std::result::Result`. For example this code: 

```rust
use parquet_derive::ParquetRecordReader;

#[derive(Debug)]
enum MyInternalError {
    IForgotSomething,
    ExpectecNotEmpty,
}

pub type Result = std::result::Result<(), MyInternalError>;

#[derive(Debug, ParquetRecordReader)]
struct MyRecord {
    name: String,
    age: u32,
}

fn main() {
    println!("Hello, world!");
}

```

Fails to compile (`cargo b`) with this error (minor edits to remove some paths...)

```
error[E0107]: type alias takes 0 generic arguments but 2 generic arguments were supplied
  --> src/main.rs:13:17
   |
13 | #[derive(Debug, ParquetRecordReader)]
   |                 ^^^^^^^^^^^^^^^^^^^ expected 0 generic arguments
   |
note: type alias defined here, with 0 generic parameters
  --> src/main.rs:11:10
   |
11 | pub type Result = std::result::Result<(), MyInternalError>;
   |          ^^^^^^
   = note: this error originates in the derive macro `ParquetRecordReader` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0053]: method `read_from_row_group` has an incompatible type for trait
  --> src/main.rs:13:17
   |
13 | #[derive(Debug, ParquetRecordReader)]
   |                 ^^^^^^^^^^^^^^^^^^^ expected `ParquetError`, found `MyInternalError`
   |
   = note: expected signature `fn(&mut Vec<_>, &mut dyn RowGroupReader, _) -> std::result::Result<_, ParquetError>`
              found signature `fn(&mut Vec<_>, &mut dyn RowGroupReader, _) -> std::result::Result<_, MyInternalError>`
   = note: this error originates in the derive macro `ParquetRecordReader` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> src/main.rs:13:17
    |
13  | #[derive(Debug, ParquetRecordReader)]
    |                 ^^^^^^^^^^^^^^^^^^^
    |                 |
    |                 expected `MyInternalError`, found `ParquetError`
    |                 arguments to this enum variant are incorrect
    |
help: the type constructed contains `ParquetError` due to the type of the argument passed
   --> src/main.rs:13:17
    |
13  | #[derive(Debug, ParquetRecordReader)]
    |                 ^^^^^^^^^^^^^^^^^^^ this argument influences the type of `Err`
note: tuple variant defined here
   --> $HOME/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:537:5
    |
537 |     Err(#[stable(feature = "rust1", since = "1.0.0")] E),
    |     ^^^
    = note: this error originates in the derive macro `ParquetRecordReader` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `?` couldn't convert the error to `MyInternalError`
  --> src/main.rs:13:35
   |
13 | #[derive(Debug, ParquetRecordReader)]
   |                 ------------------^
   |                 |                 |
   |                 |                 the trait `From<ParquetError>` is not implemented for `MyInternalError`
   |                 this can't be annotated with `?` because it has type `Result<_, ParquetError>`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the trait `FromResidual<std::result::Result<Infallible, E>>` is implemented for `std::result::Result<T, F>`
   = note: required for `std::result::Result<(), MyInternalError>` to implement `FromResidual<std::result::Result<Infallible, ParquetError>>`
   = note: this error originates in the derive macro `ParquetRecordReader` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0053, E0107, E0277, E0308.
For more information about an error, try `rustc --explain E0053`.
error: could not compile `parquet_derive_test` (bin "parquet_derive_test") due to 4 previous errors

```

**Expected behavior**
Succesful compilation.

**Additional context**
None that I am aware of.

### PR DESCRIPTION
**Pull request by jspaezp**
# Which issue does this PR close?

Closes #7547

# Rationale for this change
 
Explained in the issue.

# What changes are included in this PR?

Pretty simple change from `Result` to `std::result::Result` to prevent the 'name collision' on the code/text generated from the macro.

# Are there any user-facing changes?

None that I can think of.

Please let me know if there is anything else you might want/need on my end! and thank you very much for this project.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you for the contribution @jspaezp 

This code looks good to me. Is there any chance you can make a test for this (that would fail if we accidentally broke this feature)? Perhaps you could make a small `parquet-derive/test/macro_hygene.rs` style test , similarly to https://github.com/apache/datafusion/blob/main/datafusion/core/tests/macro_hygiene/mod.rs

**Comment by jspaezp** [comment]
@alamb thanks for the fast reply! I added a test (added it in parquet_derive_test/src/lib.rs rather than parquet-derive/test/macro_hygene.rs).

LMK if this is what you had in mind!

File: parquet_derive_test/src/lib.rs [hunk 1]
```diff
@@ -347,6 +347,36 @@ mod tests {
...
+            pub type Result = std::result::Result<(), Box<dyn std::error::Error>>;
+
+            #[derive(ParquetRecordReader, ParquetRecordWriter, Debug)]
+            pub struct ARecord {
+                pub bool: bool,
+                pub string: String,
+            }
+
+            impl ARecord {
+                pub fn validate(&self) -> Result {
```
Comment (crepererum) [inline parquet_derive_test/src/lib.rs:366]:
```suggestion
                pub fn validate(&self) -> std::result::Result<(), Box<dyn std::error::Error>> {
```

(so it doesn't use our `Result` shadow)

**Review by crepererum — COMMENTED** [review]
I think we can make the test even harder. Other than that, solid fix!

**Review by alamb — APPROVED** [review]
Thank you @jspaezp and @crepererum ❤️

**Review by mbrobbel — APPROVED** [review]
