### PR TITLE
Ignore broken symlinks for LocalFileSystem object store

### LINKED ISSUE #2174: Test `local::tests::test_list_root` fails on main on macos
Ported from https://github.com/influxdata/object_store_rs/issues/49 by @mkmik 

**Describe the bug**
```console
$ cargo test
...
---- local::tests::test_list_root stdout ----
thread 'local::tests::test_list_root' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPath { source: Canonicalize { path: "/.VolumeIcon.icns", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', src/local.rs:692:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    local::tests::test_list_root

test result: FAILED. 29 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.30s
```

same commit works on linux

Reproducer on Linux:

```console
$ uname
Linux
$ sudo ln -s /foo /bad
$ cargo test
---- local::tests::test_list_root stdout ----
thread 'local::tests::test_list_root' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPath { source: Canonicalize { path: "/bad", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', src/local.rs:692:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    local::tests::test_list_root

test result: FAILED. 29 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.23s

error: test failed, to rerun pass '--lib'
```

basically the problem is that in my mac (and possibly other macs), there is a broken symlink in the root dir.

```console
$ file /.VolumeIcon.icns
/.VolumeIcon.icns: broken symbolic link to System/Volumes/Data/.VolumeIcon.icns
```

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by jccampagne**
# Which issue does this PR close?

Closes #2174.

# Rationale for this change
 

 

`convert_walkdir_result` now ignores broken symlinks.

Resolution follows suggestions in:
* https://github.com/influxdata/object_store_rs/issues/49#issuecomment-1182687242
* https://doc.rust-lang.org/std/path/struct.Path.html#see-also-5

# What changes are included in this PR?

`convert_walkdir_result` now tests if a `DirEntry` is a symlink and if it is broken or not, function ignores broken symlinks (return `Ok(None)`.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by alamb** [comment]
Thanks @jccampagne ❤️

**Review by alamb — APPROVED** [review]
Thanks @jccampagne  -- I found the code easy to follow and it made sense to me

I think some might say it is not "idomatic" Rust in that it doesn't use the more functional `map` / `ok` type style. I spent some time rewriting to use that style in order to provide some more useful feedback. What I came up with is below but actually think it is harder to understand what is happening than your version 🤷 

Thanks again

```rust

/// Convert walkdir results and converts not-found errors into `None`.
/// Convert broken symlinks to `None`.
fn convert_walkdir_result(
    res: std::result::Result<walkdir::DirEntry, walkdir::Error>,
) -> Result<Option<walkdir::DirEntry>> {
    match res {
        Ok(entry) => Ok(map_broken_symlink_to_none(entry)),
        Err(walkdir_err) => match walkdir_err.io_error() {
            Some(io_err) => match io_err.kind() {
                io::ErrorKind::NotFound => Ok(None),
                _ => Err(Error::UnableToWalkDir {
                    source: walkdir_err,
                }
                .into()),
            },
            None => Err(Error::UnableToWalkDir {
                source: walkdir_err,
            }
            .into()),
        },
    }
}



fn map_broken_symlink_to_none(entry: walkdir::DirEntry) -> Option<walkdir::DirEntry> {
    // To check for broken symlink: call symlink_metadata() - it does not traverse symlinks);
    // if ok: check if entry is symlink; and try to read it by calling metadata().
    symlink_metadata(entry.path())
        .map(|attr| {
            if attr.is_symlink() {
                metadata(entry.path())
                    // keep entry if metadata returned successfully
                    .map(|_| entry)
                    // discard error
                    .ok()
            }
            else {
                Some(entry)
            }
        })
        // discard the error from symlink etadata
        .ok()
        .flatten()
}

```

cc @tustvold

File: object_store/src/local.rs [hunk 1]
```diff
@@ -990,8 +1015,6 @@ mod tests {
     }
 
     #[tokio::test]
-    #[cfg(target_os = "linux")]
-    // macos has some magic in its root '/.VolumeIcon.icns"' which causes this test to fail
```
Comment (tustvold) [inline object_store/src/local.rs:994]: This was actually a red-herring, mac os doesn't always have this file. In particular in CI. I think it would be great if we could have an explicit test of a broken link so that we have some test coverage of this feature

File: object_store/src/local.rs [hunk 2]
```diff
@@ -804,11 +804,36 @@ fn convert_metadata(metadata: std::fs::Metadata, location: Path) -> Result<Objec
...
+            match symlink_metadata(entry.path()) {
+                Ok(attr) => {
+                    if attr.is_symlink() {
+                        let target_metadata = metadata(entry.path());
+                        match target_metadata {
+                            Ok(_) => {
+                                // symlink is valid
+                                Ok(Some(entry))
+                            }
+                            Err(_) => {
```
Comment (tustvold) [inline object_store/src/local.rs:824]: It might be nice to check the ErrorKind is NotFound

File: object_store/src/local.rs [hunk 3]
```diff
@@ -804,11 +804,36 @@ fn convert_metadata(metadata: std::fs::Metadata, location: Path) -> Result<Objec
...
+/// Convert broken symlinks to `None`.
 fn convert_walkdir_result(
     res: std::result::Result<walkdir::DirEntry, walkdir::Error>,
 ) -> Result<Option<walkdir::DirEntry>> {
     match res {
-        Ok(entry) => Ok(Some(entry)),
+        Ok(entry) => {
+            // To check for broken symlink: call symlink_metadata() - it does not traverse symlinks);
+            // if ok: check if entry is symlink; and try to read it by calling metadata().
+            match symlink_metadata(entry.path()) {
```
Comment (tustvold) [inline object_store/src/local.rs:815]: I wonder if we should invert the order here, to optimise for the common case of non-broken symlinks.

i.e. call `std::fs::metadata` if this fails with `ErrorKind::NotFound`, then call `symlink_metadata` to check if it is a broken symlink we should just ignore?

**Comment by tustvold** [comment]
> I think some might say it is not "idomatic" Rust in that it doesn't use the more functional map / ok type style

I think using structured matches as this PR does is idiomatic Rust and I'm happy with it, nice work :+1:. FWIW I don't think code needs to be written in a functional style to be considered idiomatic, it is frequently harder to understand, and very often the borrow checker prevents it anyway.

File: object_store/src/local.rs (hunk 1 above)
Comment (alamb) [reply object_store/src/local.rs:994]: I don't understand this comment -- the test fails with with this error on (macos) CI. I disabled the check on mac so the CI would pass....

Comment (tustvold) [reply object_store/src/local.rs:994]: Fantastic, I had understood that this couldn't be relied on, that's good that we can see the issue and get coverage of it in CI. 

However, I still think an explicit symlink test would be worthwhile, especially as I would not be surprised if Windows does something exciting, etc...

**Comment by jccampagne** [comment]
Thanks for the review and comments.
I'll try to add a specific test for broken links; instead of relying on MacOS's idiosyncrasies.

**Comment by tustvold** [comment]
@jccampagne so I started writing some tests for this behaviour, and actually symlinks behave in very unexpected ways in general - as they get canonicalised as part of path resolution. I'm currently coding something up which will simply ignore symlinks, as I don't think we can support them in a meaningful way without significant engineering effort

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-rs/issues/2206 to track writing testst

**Comment by tustvold** [comment]
Created https://github.com/apache/arrow-rs/pull/2207, please let me know what you both think :smile:
