### PR TITLE
Fix nullif when existing array has no nulls

### LINKED ISSUE #3031: Nullif with incorrect valid_count
**Describe the bug**
The [`nullif`] function in `compute/kernels/boolean.rs` has incorrect `valid_count` when the left's null_buffer is None. 

[`nullif`]: https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/boolean.rs#L525

**To Reproduce**
```rust 
let a = Int32Array::from(vec![Some(15), Some(7), Some(8), Some(1), Some(9)]);
let comp = BooleanArray::from(vec![Some(false), None, Some(true), Some(false), None]);
let res = nullif(&a, &comp).unwrap(); // panic here
```
**Why it happens**
`bitwise_unary_op_helper` will apply the `op` to the remainder bytes, the problem happens here. `valid_count` will take the ones that should be ignored into consideration.  

**Solution**
```rust
let left = Bitmap::new(len);
bitwise_bin_op_helper(left.buffer(), 0, &right, right_offset, len, |l, r| {
    let t = l & !r;
    valid_count += t.count_ones() as usize;
    t
})
```

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3031

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/compute/kernels/boolean.rs [hunk 1]
```diff
@@ -472,7 +472,7 @@ pub fn is_not_null(input: &dyn Array) -> Result<BooleanArray> {
 }
 
 /// Copies original array, setting validity bit to false if a secondary comparison
-/// boolean array is set to true or null
+/// boolean array is set to true
```
Comment (tustvold) [inline arrow/src/compute/kernels/boolean.rs:475]: I incorrectly changed this doc in https://github.com/apache/arrow-rs/pull/2940/files#diff-036c91a4b91e350837448f27da4ac4c0b43cfb477571330ac1f37654b0e2c172L471

File: arrow/src/compute/kernels/boolean.rs [hunk 2]
```diff
@@ -522,11 +522,19 @@ pub fn nullif(left: &dyn Array, right: &BooleanArray) -> Result<ArrayRef> {
...
+                let t = !b;
+                valid_count += t.count_ones() as usize;
+                t
+            });
+            // We need to compensate for the additional bits read from the end
+            let remainder_len = len % 64;
+            if remainder_len != 0 {
+                valid_count -= 64 - remainder_len
+            }
+            buffer
```
Comment (viirya) [inline arrow/src/compute/kernels/boolean.rs:536]: Should we also compensate valid_count for left_data.null_buffer() is Some case?

**Review by viirya — APPROVED** [review]

File: arrow/src/compute/kernels/boolean.rs (hunk 2 above)
Comment (tustvold) [reply arrow/src/compute/kernels/boolean.rs:536]: Shouldn't need to as remainder u64 is masked to be 0 in the trailing positions, which when and-ed will not yield valid bits
