### PR TITLE
Fix StructArrayReader handling nested lists (#1651) 

### LINKED ISSUE #1651: Parquet Reader Bails Out Reading Parquet File
**Describe the bug**

When reading the [parquet file](https://github.com/apache/arrow-datafusion/files/8626500/part-00000-f6337bce-7fcd-4021-9f9d-040413ea83f8-c000.snappy.parquet.zip) provided by @kesavkolla [here](https://github.com/apache/arrow-datafusion/issues/2439) the reader bails out with "Not all children array length are the same".

Interestingly if you just project column 32 i.e.

```
let mut reader = reader.get_record_reader_by_columns(vec![32], 1024).unwrap();
```

You get `ParquetError("Arrow: item_reader rep levels are None.")`

If you project 31 and 32 you get the above error.

**To Reproduce**

Run the test on the provided file

**Expected behavior**

The file should be read correctly

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1651.

# Rationale for this change
 
See ticket

# What changes are included in this PR?

Fixes handling of nested lists within StructArrayReader

# Are there any user-facing changes?

Files that used to fail to parse, now parse correctly

### CODE REVIEW

File: parquet/src/arrow/array_reader.rs [hunk 1]
```diff
@@ -742,80 +737,59 @@ impl ArrayReader for StructArrayReader {
...
 
-        if self.struct_def_level != 0 {
+        if self.nullable {
             // calculate struct def level data
-            let buffer_size = children_array_len * size_of::<i16>();
-            let mut def_level_data_buffer = MutableBuffer::new(buffer_size);
-            def_level_data_buffer.resize(buffer_size, 0);
 
-            // Safety: the buffer is always treated as `u16` in the code below
-            let def_level_data = unsafe { def_level_data_buffer.typed_data_mut() };
```
Comment (alamb) [inline parquet/src/arrow/array_reader.rs:752]: +1 for removing some `unsafe`

File: parquet/src/arrow/array_reader.rs [hunk 2]
```diff
@@ -1564,12 +1541,74 @@ mod tests {
...
+
+        let expected_l =
+            Arc::new(ListArray::from_iter_primitive::<Int32Type, _, _>(vec![
+                Some(vec![Some(1), Some(2), None]),
+                Some(vec![]),
+                None,
+                None,
+            ]));
+
+        let nulls = Buffer::from([0b00000111]);
```
Comment (alamb) [inline parquet/src/arrow/array_reader.rs:1571]: doesn't this set the first three elements in the struct array to `NULL`?

That doesn't seem consistent with the structure created in the comments above

File: parquet/src/arrow/array_reader/map_array.rs [hunk 3]
```diff
@@ -154,15 +150,15 @@ impl ArrayReader for MapArrayReader {
     }
 
     fn get_def_levels(&self) -> Option<&[i16]> {
-        self.def_level_buffer
-            .as_ref()
-            .map(|buf| unsafe { buf.typed_data() })
+        // Children definition levels should describe the same parent structure,
+        // so return key_reader only
+        self.key_reader.get_def_levels()
```
[the remark this answers is not in the document]
Comment (alamb) [reply parquet/src/arrow/array_reader/map_array.rs:155]: I am a big fan of less `unsafe` 👍

**Review by alamb — APPROVED** [review]
Thank you @tustvold 

I found this easier to review by ignoring whitespace https://github.com/apache/arrow-rs/pull/1700/files?w=1

As I am not a super expert in this code, I can't say I fully grok it but if it fixes the file from @kesavkolla sounds good to me.

I had one question on the tests, but I suspect it is my own mis-understanding

cc @paddyhoran  @nevi-me

File: parquet/src/arrow/array_reader.rs (hunk 2 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader.rs:1571]: Will rename to validity, it is an arrow null mask... I agree the naming is perpetually confusing

Comment (alamb) [reply parquet/src/arrow/array_reader.rs:1571]: aaah!
