### PR TITLE
Calculate n_buffers in FFI_ArrowArray by data layout

### LINKED ISSUE #1959: Incorrect n_buffers in FFI_ArrowArray
**Describe the bug**
We count `n_buffers` for `FFI_ArrowArray` by looking at `ArrayData` regarding with its `null_buffer`, and buffers. However, for NullType array, `n_buffers`  should be 0. But currently `n_buffers` is 1.

`n_buffers` should be based on the layout spec.

We found this bug when transferring a NullType array between Rust and Java. The ffi ArrowArray fails a check at Arrow Java.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1959.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao

File: arrow/src/ffi.rs [hunk 1]
```diff
@@ -450,7 +450,17 @@ impl FFI_ArrowArray {
         let buffers = iter::once(data.null_buffer().cloned())
             .chain(data.buffers().iter().map(|b| Some(b.clone())))
             .collect::<Vec<_>>();
-        let n_buffers = buffers.len() as i64;
+        let data_layout = layout(data.data_type());
+        // `n_buffers` is the number of buffers by the spec.
```
Comment (viirya) [inline arrow/src/ffi.rs:454]: https://arrow.apache.org/docs/format/CDataInterface.html#c.ArrowArray.n_buffers

File: arrow/src/ffi.rs [hunk 2]
```diff
@@ -450,7 +450,17 @@ impl FFI_ArrowArray {
...
+        let n_buffers = {
+            data_layout.buffers.len() + {
+                if data_layout.can_contain_null_mask {
+                    1
```
Comment (sunchao) [inline arrow/src/ffi.rs:458]: maybe add a comment explaining why we need to add 1 here (it is for the null buffer right?)

File: arrow/src/ffi.rs [hunk 3]
```diff
@@ -450,7 +450,17 @@ impl FFI_ArrowArray {
         let buffers = iter::once(data.null_buffer().cloned())
             .chain(data.buffers().iter().map(|b| Some(b.clone())))
             .collect::<Vec<_>>();
-        let n_buffers = buffers.len() as i64;
```
Comment (sunchao) [inline arrow/src/ffi.rs:453]: hmm why `n_buffers` would be 1 in the case of `NullArray`? in Rust the `null_buffer` is `None` right? is it different in Java?

File: arrow/src/ffi.rs (hunk 2 above)
Comment (viirya) [reply arrow/src/ffi.rs:458]: Yes

File: arrow/src/ffi.rs (hunk 3 above)
Comment (viirya) [reply arrow/src/ffi.rs:453]: `buffers` is a vector of `Option<Buffer>`.

Comment (sunchao) [reply arrow/src/ffi.rs:453]: I see. Do we need to keep `n_buffers` in sync with `buffers.len`? in the case of null array, `buffers.len` is 1 with a null pointer, while `n_buffers` becomes 0 after this PR.

Comment (viirya) [reply arrow/src/ffi.rs:453]: Oh, good point. We should not include null if the array doesn't have a null buffer by spec.

Comment (viirya) [reply arrow/src/ffi.rs:453]: It doesn't cause a problem at Java because Java will get buffer pointer by the number of buffers in ffi struct. But it might cause a problem for other language implementations.

Comment (sunchao) [reply arrow/src/ffi.rs:453]: Yea. According to the spec of `buffers`:

> Mandatory. A C array of pointers to the start of each physical buffer backing this array. Each void* pointer is the physical start of a contiguous buffer. There must be [ArrowArray.n_buffers](https://arrow.apache.org/docs/format/CDataInterface.html#c.ArrowArray.n_buffers) pointers.

**Comment by viirya** [comment]
Seems unrelated test failure.
```
FAILED TEST: datetime Java producing,  C# consuming
```

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Thanks @sunchao
