### PR TITLE
Fix Copy from percent-encoded path (#2353)

### LINKED ISSUE #2353: Azure/S3 Storage Fails to Copy Blob with URL-encoded Path
**Describe the bug**

https://github.com/apache/arrow-rs/runs/7713310841?check_suite_focus=true#step:8:330

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2353

# Rationale for this change
 

I added this test in #2352 and realised it was failing for the existing AWS implementation, and Azure. This fixes the behaviour

# What changes are included in this PR?

# Are there any user-facing changes?

No

### CODE REVIEW

File: object_store/src/azure.rs [hunk 1]
```diff
@@ -470,14 +470,15 @@ impl ObjectStore for MicrosoftAzure {
...
-            container: &self.container_name,
-        })?)
+    fn get_copy_from_url(&self, from: &Path) -> Result<Url> {
+        let mut url =
+            Url::parse(&format!("{}/{}", &self.blob_base_url, self.container_name))
+                .context(UnableToParseUrlSnafu {
+                    container: &self.container_name,
+                })?;
+
+        url.path_segments_mut().unwrap().extend(from.parts());
```
Comment (viirya) [inline object_store/src/azure.rs:480]: Don't need to encode the path here?

Comment (tustvold) [reply object_store/src/azure.rs:480]: That's what [`extend`](https://docs.rs/url/latest/url/struct.PathSegmentsMut.html#method.extend) does, and what this PR is changing. Sorry I should have called this out :smile:

Comment (viirya) [reply object_store/src/azure.rs:480]: Oh, I see. Thanks for pointing to the doc. 😄

**Review by viirya — APPROVED** [review]
