### PR TITLE
fix: don't panic in IPC reader if struct child arrays have different …

### LINKED ISSUE #6416: Invalid struct arrays in IPC data causes panic during read
**Describe the bug**
We're using Arrow Flight with a dotnet client. One of our client applications accidentally was sending StructArray's with different length child arrays. Not sure why the dotnet side batch building didn't catch it, but on the flight decode in IPC there is a panic. This causes the request task to die and the response to the flight client to be not helpful.

```
thread 'general' panicked at /.../arrow-array-52.2.0/src/array/struct_array.rs:90:46:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Incorrect array length for StructArray field \"field\", expected 2 got 1")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libunwind: stepWithCompactEncoding - invalid compact unwind encoding
```

**To Reproduce**
Create IPC data with different length child arrays in a struct. Attempt to read that data.

**Expected behavior**
Error is returned without panicing.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by alexwilcoxson-rel**
…lengths

# Which issue does this PR close?

Closes #6416 

# Rationale for this change
 
While we don't expect to receive invalid IPC data via flight. We would like to avoid panics if possible.

# What changes are included in this PR?

Use StructArray::try_new vs StructArray::from in ipc reader. StructArray::from impls use StructArray::new. new calls try_new but unwraps.

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by alexwilcoxson-rel** [comment]
Any advice on how to generate this type of invalid batch with arrow-rs for testing?

File: arrow-ipc/src/reader.rs [hunk 1]
```diff
@@ -31,7 +31,9 @@ use std::io::{BufReader, Read, Seek, SeekFrom};
 use std::sync::Arc;
 
 use arrow_array::*;
-use arrow_buffer::{ArrowNativeType, BooleanBuffer, Buffer, MutableBuffer, ScalarBuffer};
+use arrow_buffer::{
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:34]: Can we please get a test for this fix so that we don't break it again during some future refactoring?

**Review by alamb — COMMENTED** [review]
Thank you for the contribution @alexwilcoxson-rel

File: arrow-ipc/src/reader.rs (hunk 1 above)
Comment (alexwilcoxson-rel) [reply arrow-ipc/src/reader.rs]: just added, was able to write the invalid array to ipc buffer using ArrayDataBuilder::build_unchecked

File: arrow-ipc/src/reader.rs [hunk 2]
```diff
@@ -2235,4 +2237,50 @@ mod tests {
 
         assert_eq!(batch, roundtrip_batch);
     }
+
+    #[test]
+    fn test_invalid_struct_array_ipc_read_errors() {
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:2242]: I verified that this test panic's without the code changes in this PR, as expected

```
` value: InvalidArgumentError("Incorrect array length for StructArray field \"b\", expected 4 got 3")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1102:23
   4: arrow_array::array::struct_array::StructArray::new
             at /Users/andrewlamb/Software/arrow-rs/arrow-array/src/array/struct_array.rs:90:9
   5: <arrow_array::array::struct_array::StructArray as core::convert::From<alloc::vec::Vec<(alloc::sync::Arc<arrow_schema::field::Field>,alloc::sync::Arc<dyn arrow_array::array::Array>)>>>::from
             at /Users/andrewlamb/Software/arrow-rs/arrow-array/src/array/struct_array.rs:401:9
   6: arrow_ipc::reader::create_array
             at ./src/reader.rs:167:17
   7: arrow_ipc::reader::read_record_batch_impl

```

**Review by alamb — APPROVED** [review]
Thank you @alexwilcoxson-rel  -- this looks great to me
