### PR TITLE
[regression] Error with adaptive predicate pushdown: "Invalid offset in sparse column chunk data: 754, no matching page found."

### LINKED ISSUE #9239: [regression] Error with adaptive predicate pushdown: "Invalid offset in sparse column chunk data: 754, no matching page found."
## Describe the bug

Error:
```
Parquet error: Invalid offset in sparse column chunk data: 754, no matching page found.
If you are using a `SelectionStrategyPolicy::Mask`, ensure that the OffsetIndex is provided when creating the InMemoryRowGroup.
```

Occurs when:

1. A predicate uses `RowSelectionStrategy::Selectors` with a `RowSelector` list that skips an entire page.
2. Another predicate uses `RowSelectionStrategy::Mask` by triggering the [mask run-length threshold]
3. The column with `RowSelectionStrategy::Mask` is **not** in the output projection, so [`should_force_selectors`] does not force it to use `RowSelectionStrategy::Selectors`
4. The mask strategy attempts to fetch pages that were skipped, resulting in an error

## To Reproduce

A minimal reproducer is available at: https://github.com/erratic-pattern/parquet_mask_strategy_missing_pages

```bash
git clone https://github.com/erratic-pattern/parquet_mask_strategy_missing_pages
cd parquet_mask_strategy_missing_pages
cargo test
```

The test uses a parquet file with:
- 2 row groups, 300 rows each
- Tag column with values 'a', 'b', 'c' sorted (100 rows each)
- Time column with alternating in-range/out-of-range values
- Page size set so tag='b' section contains at least one full page

The test simulates a query like `SELECT tag WHERE tag IN ('a', 'c') AND time >= X AND time < Y` with three predicates:
1. `tag IN ('a', 'c')` - creates initial selection `[select 100, skip 100, select 100]`
2. `time >= X` - creates sparse selection, pages fetched as Sparse
3. `time < Y` - triggers Mask strategy due to sparse selection from predicate 2

## Additional context

- Introduced in parquet 57.1.0 via https://github.com/apache/arrow-rs/pull/8733
- Related to https://github.com/apache/arrow-rs/issues/8845

[mask run-length threshold]: https://github.com/apache/arrow-rs/blob/57.1.0/parquet/src/arrow/arrow_reader/selection.rs#L47
[`should_force_selectors`]: https://github.com/apache/arrow-rs/blob/57.1.0/parquet/src/arrow/arrow_reader/selection.rs#L275-L284

### PR DESCRIPTION
**Pull request by sdf-jkl**
# Which issue does this PR close?

- Closes #9239.

# Rationale for this change

Check issue

# What changes are included in this PR?

Added a copy of `override_selector_strategy_if_needed` to the filter application stage.

Now if we use mask selection, and there are skipped pages in predicate projection we enforce RLE selection.

# Are these changes tested?

Yes, using #9243

# Are there any user-facing changes?

### CODE REVIEW

**Comment by sdf-jkl** [comment]
@alamb that's it?

File: parquet/src/arrow/push_decoder/reader_builder/mod.rs [hunk 1]
```diff
@@ -437,6 +437,18 @@ impl RowGroupReaderBuilder {
                     .with_parquet_metadata(&self.metadata)
                     .build_array_reader(self.fields.as_deref(), predicate.projection())?;
```
Comment (alamb) [inline parquet/src/arrow/push_decoder/reader_builder/mod.rs:438]: This is a great fix -- and it makes total sense to me (basically that filter evaluation is a different path, so we need to revert the selector strategy on the filter path as well)

File: parquet/src/arrow/push_decoder/reader_builder/mod.rs [hunk 2]
```diff
@@ -437,6 +437,18 @@ impl RowGroupReaderBuilder {
...
+                //
+                // Note that the selection could have come without filters and applied manually
+                // We should keep another override_selector_strategy_if_needed in waiting_on_data state
+
+                plan_builder = override_selector_strategy_if_needed(
+                    plan_builder,
+                    predicate.projection(),
+                    self.row_group_offset_index(row_group_idx),
+                );
+
```
Comment (alamb) [inline parquet/src/arrow/push_decoder/reader_builder/mod.rs]: I think this could be a slightly less confusing comment:

```suggestion
                // Prepare to evaluate the filter. 
                // Note: first update the selection strategy to properly handle any pages
                // pruned during fetch
                plan_builder = override_selector_strategy_if_needed(
                    plan_builder,
                    predicate.projection(),
                    self.row_group_offset_index(row_group_idx),
                );
                // `with_predicate` actually evaluates the filter

```

**Review by alamb — APPROVED** [review]
Thank you @sdf-jkl  -- this is a great find and fix that makes total sense to me 🙏  I am going to keep working on some more testing to be extra confident, but overall I think this is a perfect PR for fixing the bug while we sort out the better solution

**Comment by alamb** [comment]
FYI @hhhizzz

**Comment by alamb** [comment]
Thank you again so much for all your help with this @sdf-jkl

**Comment by alamb** [comment]
Backport PR
- https://github.com/apache/arrow-rs/pull/9309
