### PR TITLE
fix: reset the offset of 'file_for_view'

### LINKED ISSUE #8380: [Avro] Example read_with_utf8view.rs fails to run with error "Error: ParseError("Unexpected EOF while reading Avro header")"
#### Describe the bug

Try to run the example for demonstrating how to use Utf8View support in the Arrow Avro reader. But failed.
The example reads an Avro file with string data twice - once with regular StringArray and once with StringViewArray as description.

The root cause is the clone 
```rust
    let file_for_view = file.try_clone()?;
```

In rust lib's doc, the 
```
Creates a new File instance that shares the same underlying file handle as the existing File instance. Reads, writes, and seeks will affect both File instances simultaneously.
```
So while try to decode the header of avro, the handle have moved the offset, then it will get 0 size header and failed.

```rust
    let file = File::open(file_path)?;
    let file_for_view = file.try_clone()?;

    let start = Instant::now();
    let reader = BufReader::new(file);
    let avro_reader = ReaderBuilder::new().build(reader)?;
    let schema = avro_reader.schema();
    let batches: Vec<RecordBatch> = avro_reader.collect::<Result<_, _>>()?;
    let regular_duration = start.elapsed();

    let start = Instant::now();
    // here the file handle will be consumed twice and lead to the error.
    let reader_view = BufReader::new(file_for_view);
    let avro_reader_view = ReaderBuilder::new()
        .with_utf8_view(true)
        .build(reader_view)?;
    let batches_view: Vec<RecordBatch> = avro_reader_view.collect::<Result<_, _>>()?;
    let view_duration = start.elapsed();
```

#### To Reproduce
```shell
(base) ➜  arrow-rs git:(main) ✗ cd arrow-avro 
(base) ➜  arrow-avro git:(main) ✗ cargo run --package arrow-avro --example read_with_utf8view -- test/data/nested_record_reuse.avro
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.33s
     Running `/Users/trevor.wang/Workspace/rust/arrow-rs/target/debug/examples/read_with_utf8view test/data/nested_record_reuse.avro`
Error: ParseError("Unexpected EOF while reading Avro header")
```

#### Expected behavior

Example can be executed successfully and give the performance result.

### PR DESCRIPTION
**Pull request by TrevorADHD**
# Which issue does this PR close?

- Closes #8380

# Rationale for this change

It will fix the example to help user get the result of utf8view performance.

# What changes are included in this PR?

Reset the file handle's offset before using it in next time.

# Are these changes tested?

```
arrow-avro/examples/read_with_utf8view.rs
```

The example can run successfully
```shell
(base) ➜  arrow-avro git:(fix/example_of_utf8view) cargo run --package arrow-avro --example read_with_utf8view -- test/data/nested_record_reuse.avro
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.30s
     Running `/Users/trevor.wang/Workspace/rust/fix-arrow-rs/arrow-rs/target/debug/examples/read_with_utf8view test/data/nested_record_reuse.avro`
Read 2 rows from test/data/nested_record_reuse.avro
Reading with StringArray: 2.095417ms
Reading with StringViewArray: 179.333µs
StringViewArray was 11.68x faster
```

# Are there any user-facing changes?

Every user will get the right result and run the example to get the perfomrance data.

### CODE REVIEW

File: arrow-avro/examples/read_with_utf8view.rs [hunk 1]
```diff
@@ -48,6 +48,7 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
     let batches: Vec<RecordBatch> = avro_reader.collect::<Result<_, _>>()?;
     let regular_duration = start.elapsed();
 
+    file_for_view.seek(SeekFrom::Start(0))?;
```
Comment (mbrobbel) [inline arrow-avro/examples/read_with_utf8view.rs:51]: Maybe the reader should seek to the start?

https://github.com/apache/arrow-rs/blob/aed2f3b6a72375acb06cf958c9e3ff3c6ecb760f/arrow-avro/src/reader/mod.rs#L226-L243

Comment (TrevorADHD) [reply arrow-avro/examples/read_with_utf8view.rs:51]: In my personal opinion, no need to modify the reader's logic. User who clone the file handle should know, realize and conscious control the file handle.

Comment (TrevorADHD) [reply arrow-avro/examples/read_with_utf8view.rs:51]: For example, i use confluent avro and apache avro tgt. So I can skip confluent magic byte + schema id , and pass it to reader.  But if reader reset the offset, it will become not convenient.

**Review by mbrobbel — APPROVED** [review]

**Comment by alamb** [comment]
Thank you @TrevorADHD @jecsand838 and @mbrobbel
