### PR TITLE
Fix: ViewType gc on huge batch would produce bad output

### LINKED ISSUE #8681: Array: ViewType gc() has bug when array sum length exceed i32::MAX
**Describe the bug**

This bug comes from this optimization: https://github.com/apache/arrow-rs/pull/7873

The reason is because, view layout, which is in https://arrow.apache.org/docs/format/Columnar.html#variable-size-binary-view-layout , would have only 4bytes for offset. If the sum off offset exceeds i32::MAX, the built array violates the StringView standard, which causing the bug.

See https://github.com/apache/arrow-rs/blob/94d51f4efc5e1817062aabad5c6301cbbee2ec61/arrow-array/src/array/byte_view_array.rs#L516 for detail

**To Reproduce**

Provide input which is longer than 2GiB, or 4GiB, the content would be buggy

**Expected behavior**

Produce valid data buffer

**Additional context**

No

### PR DESCRIPTION
**Pull request by mapleFU**
# Which issue does this PR close?

- Closes #8681.

# Rationale for this change

Previously, `gc()` will produce a single buffer. However, for buffer size greater than 2GiB, it would be buggy, since buffer-offset it's a 4-byte signed integer.

# What changes are included in this PR?

Add a GcCopyGroup type, and do gc for it.

# Are these changes tested?

Yes

# Are there any user-facing changes?

gc would produce more buffers

### CODE REVIEW

File: arrow-array/src/array/byte_view_array.rs [hunk 1]
```diff
@@ -512,18 +512,72 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+            let mut groups = vec![];
+            let mut current_length = 0;
+            let mut current_elements = 0;
 
-        // 4) Iterate over views and process each inline/non-inline view
-        let views_buf: Vec<u128> = (0..len)
-            .map(|i| unsafe { self.copy_view_to_buffer(i, &mut data_buf) })
-            .collect();
+            for view in self.views() {
+                let len = *view as u32;
```
Comment (mapleFU) [inline arrow-array/src/array/byte_view_array.rs:549]: This part is so slow, but it's right, I can make it faster(by handling the numbers via grouping or batching) if required

File: arrow-array/src/array/byte_view_array.rs [hunk 2]
```diff
@@ -1404,6 +1463,55 @@ mod tests {
         }
     }
 
+    #[test]
+    fn test_gc_huge_array() {
```
Comment (mapleFU) [inline arrow-array/src/array/byte_view_array.rs:1481]: This test requires about 5GiB memory, it's huge, I don't know would it affect the testing on some machines

**Comment by mapleFU** [comment]
@alamb Besides, I meet this bug when I have 4GiB StringViewArray, arrow-rs regard offset as u32, however, in arrow standard, this uses i32. So I limit it to 2GiB

There're other places uses `u32::MAX` in view handling, should I also fix them in other patch?

File: arrow-array/src/array/byte_view_array.rs [hunk 3]
```diff
@@ -512,18 +512,72 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+            }
+            groups
+        } else {
+            let gc_copy_group = GcCopyGroup {
+                total_buffer_bytes: total_large,
+                total_len: len,
+            };
+            vec![gc_copy_group]
+        };
+        assert!(gc_copy_groups.len() <= i32::MAX as usize);
```
Comment (mapleFU) [inline arrow-array/src/array/byte_view_array.rs]: This assertion can be removed, I just ensure it would pass

File: arrow-array/src/array/byte_view_array.rs (hunk 2 above)
Comment (mapleFU) [reply arrow-array/src/array/byte_view_array.rs:1481]: Previous code would meet bug only when buffer greater than 4GiB, the current code can be tested when > 2GiB.   Personally I think leave 2GiB for test is ok but 4GiB is also ok to me, decide on reviewer's idea.

Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs:1481]: I ran this test on my mac M3 and it takes 1.5 seconds so I think it is ok

```
running 1 test
test array::byte_view_array::tests::test_gc_huge_array ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 578 filtered out; finished in 1.58s
```

I also verified that without the code in this PR, the test fails like:
```
---- array::byte_view_array::tests::test_gc_huge_array stdout ----

thread 'array::byte_view_array::tests::test_gc_huge_array' panicked at arrow-array/src/array/byte_view_array.rs:1444:9:
assertion `left != right` failed: gc with huge buffer should not consolidate data into a single buffer
  left: 1
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File: arrow-array/src/array/byte_view_array.rs [hunk 4]
```diff
@@ -512,18 +512,71 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+                    total_len: current_elements,
+                });
+            }
+            groups
+        } else {
+            let gc_copy_group = GcCopyGroup {
+                total_buffer_bytes: total_large,
+                total_len: len,
+            };
+            vec![gc_copy_group]
```
Comment (alamb) [inline arrow-array/src/array/byte_view_array.rs]: I know it is probably a small thing, but could you please avoid this new allocation for the common case where there is a single buffer? Perhaps by creating the data bufs directly via a function call rather than a loop over the array

File: arrow-array/src/array/byte_view_array.rs (hunk 1 above)
Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs:549]: I am not sure how you would make this much faster - I think the code needs to find the locations to split in any event

File: arrow-array/src/array/byte_view_array.rs [hunk 5]
```diff
@@ -512,18 +512,71 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
             };
         }
 
-        // 3) Allocate exactly capacity for all non-inline data
-        let mut data_buf = Vec::with_capacity(total_large);
+        struct GcCopyGroup {
```
Comment (alamb) [inline arrow-array/src/array/byte_view_array.rs]: I found this somewhat confusing at first as it is just deferring the creation of the view buffers.

I think the code would be clearer (and faster) if you simply created the new buffers directly (with a branch for when the total length was too large)

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1017-gcp #18~24.04.1-Ubuntu SMP Tue Sep 23 17:51:44 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gc-fixing-huge-batch-bug (142284c34daed2219983d21010e5c1ba4d3c5b59) to a7572eb605c0314befa5ef6ffbe9e430127f27bb [diff](https://github.com/apache/arrow-rs/compare/a7572eb605c0314befa5ef6ffbe9e430127f27bb..142284c34daed2219983d21010e5c1ba4d3c5b59)
BENCH_NAME=view_types
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench view_types 
BENCH_FILTER=
BENCH_BRANCH_NAME=gc-fixing-huge-batch-bug
Results will be posted here when complete

**Comment by alamb** [comment]
The MIRI test is probably failing due to the massive memory use in https://github.com/apache/arrow-rs/actions/runs/18818674867/job/53690752815?pr=8694

I suggest we don't run that test under miri by disabling it, with something like 

```rust
    #[cfg_attr(miri, ignore)] // Takes too long
```

For example

https://github.com/apache/arrow-rs/blob/ba22a214b3c469da5466f60a74ab201a268bc0fc/arrow-array/src/array/boolean_array.rs#L789-L788

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                             gc-fixing-huge-batch-bug               main
-----                                             ------------------------               ----
gc view types all without nulls[100000]           1.05  1600.4±85.77µs        ? ?/sec    1.00  1527.4±58.01µs        ? ?/sec
gc view types all without nulls[8000]             1.07     68.0±3.35µs        ? ?/sec    1.00     63.5±1.04µs        ? ?/sec
gc view types all[100000]                         1.16    296.3±9.94µs        ? ?/sec    1.00    255.3±1.11µs        ? ?/sec
gc view types all[8000]                           1.14     21.5±0.32µs        ? ?/sec    1.00     18.9±0.11µs        ? ?/sec
gc view types slice half without nulls[100000]    1.06   552.7±15.42µs        ? ?/sec    1.00    520.1±7.45µs        ? ?/sec
gc view types slice half without nulls[8000]      1.06     28.9±0.20µs        ? ?/sec    1.00     27.2±0.15µs        ? ?/sec
gc view types slice half[100000]                  1.15    145.5±3.36µs        ? ?/sec    1.00    126.3±0.63µs        ? ?/sec
gc view types slice half[8000]                    1.14     11.0±0.12µs        ? ?/sec    1.00      9.6±0.05µs        ? ?/sec
view types slice                                  1.00    709.6±1.75ns        ? ?/sec    1.00    706.8±1.32ns        ? ?/sec
```


</p>
</details>

File: arrow-array/src/array/byte_view_array.rs (hunk 2 above)
Comment (mapleFU) [reply arrow-array/src/array/byte_view_array.rs:1481]: I have removed the single buffer limitation :-(

File: arrow-array/src/array/byte_view_array.rs (hunk 5 above)
Comment (mapleFU) [reply arrow-array/src/array/byte_view_array.rs]: I think this would making the fast path slower 🤔, a single copy-group is just as simple as previous code. Maybe I should just remove the allocation here ( https://github.com/apache/arrow-rs/pull/8694/files#r2470787503 )?

File: arrow-array/src/array/byte_view_array.rs (hunk 4 above)
Comment (mapleFU) [reply arrow-array/src/array/byte_view_array.rs]: This makes sense, a fixed-sized slice on stack might be better in this scenerio

File: arrow-array/src/array/byte_view_array.rs (hunk 1 above)
Comment (mapleFU) [reply arrow-array/src/array/byte_view_array.rs:549]: Even if the buffer size is greater than i32::MAX, it's possible that a single buffer is much smaller than i32::MAX, so this can find batch-by-batch, rather than just adding small buffer one-by-one?

File: arrow-array/src/array/byte_view_array.rs (hunk 3 above)
Comment (zhuqi-lucas) [reply arrow-array/src/array/byte_view_array.rs]: May be change to assert debug here.

File: arrow-array/src/array/byte_view_array.rs (hunk 5 above)
Comment (zhuqi-lucas) [reply arrow-array/src/array/byte_view_array.rs]: Does the struct will affect some performance? We can compare the benchmark.

File: arrow-array/src/array/byte_view_array.rs [hunk 6]
```diff
@@ -512,18 +512,71 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+            total_buffer_bytes: usize,
+            total_len: usize,
+        }
+
+        let gc_copy_groups = if total_large > i32::MAX as usize {
```
Comment (zhuqi-lucas) [inline arrow-array/src/array/byte_view_array.rs]: If we can add such as cold flag, since it's rare for the case?

**Review by zhuqi-lucas — APPROVED** [review]
Nice finding, thank you!

File: arrow-array/src/array/byte_view_array.rs [hunk 7]
```diff
@@ -541,7 +594,12 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
     ///   `buffer_index` reset to `0` and its `offset` updated so that it points
```
Comment (mapleFU) [inline arrow-array/src/array/byte_view_array.rs]:
```suggestion
    ///   `buffer_index` reset to `buffer_index` user pass in and its `offset` updated so that it points
```

File: arrow-array/src/array/byte_view_array.rs (hunk 6 above)
Comment (mapleFU) [reply arrow-array/src/array/byte_view_array.rs]: sounds ok to me ( But it's not in a loop so I think the improvement will not too much)

Comment (zhuqi-lucas) [reply arrow-array/src/array/byte_view_array.rs]: Ok, got it.

File: arrow-array/src/array/byte_view_array.rs [hunk 8]
```diff
@@ -512,18 +512,71 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+            }
+            if current_elements != 0 {
+                groups.push(GcCopyGroup {
+                    total_buffer_bytes: current_length as usize,
+                    total_len: current_elements,
+                });
+            }
+            &groups
+        } else {
+            one_group.as_slice()
```
Comment (mapleFU) [inline arrow-array/src/array/byte_view_array.rs]: I've add a `one_group` for gc-copy-group in stack, hopefully this avoids allocation

```rust
let one_group = [GcCopyGroup {
            total_buffer_bytes: total_large,
            total_len: len,
        }];
```

**Comment by mapleFU** [comment]
@alamb I've ran the new code on MacOS M4 Pro. Don't know whether the performance comes from unstable environment or other

<details> 

This patch:

```
view types slice        time:   [112.32 ns 112.44 ns 112.56 ns]
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) low severe
  1 (1.00%) low mild

gc view types all[100000]
                        time:   [246.89 µs 249.22 µs 251.63 µs]
Found 8 outliers among 100 measurements (8.00%)
  4 (4.00%) low mild
  4 (4.00%) high mild

gc view types slice half[100000]
                        time:   [79.469 µs 81.771 µs 84.060 µs]
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

gc view types all without nulls[100000]
                        time:   [406.50 µs 411.58 µs 417.23 µs]
Found 14 outliers among 100 measurements (14.00%)
  9 (9.00%) high mild
  5 (5.00%) high severe

gc view types slice half without nulls[100000]
                        time:   [373.40 µs 379.37 µs 385.93 µs]
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe

gc view types all[8000] time:   [11.603 µs 11.663 µs 11.729 µs]
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild

gc view types slice half[8000]
                        time:   [9.4269 µs 10.204 µs 11.012 µs]
Found 15 outliers among 100 measurements (15.00%)
  13 (13.00%) low severe
  2 (2.00%) low mild

gc view types all without nulls[8000]
                        time:   [27.001 µs 27.155 µs 27.368 µs]
Found 9 outliers among 100 measurements (9.00%)
  5 (5.00%) high mild
  4 (4.00%) high severe

gc view types slice half without nulls[8000]
                        time:   [13.570 µs 13.594 µs 13.621 µs]
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low severe
  2 (2.00%) high mild
  1 (1.00%) high severe
```

main:

```
view types slice        time:   [118.73 ns 121.33 ns 124.80 ns]
                        change: [+16.208% +20.497% +25.223%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild

gc view types all[100000]
                        time:   [175.56 µs 177.37 µs 179.60 µs]
                        change: [-26.662% -25.460% -24.243%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe

gc view types slice half[100000]
                        time:   [76.242 µs 76.520 µs 76.843 µs]
                        change: [-2.6612% -0.4692% +1.8536%] (p = 0.69 > 0.05)
                        No change in performance detected.
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) high mild
  7 (7.00%) high severe

gc view types all without nulls[100000]
                        time:   [385.38 µs 393.14 µs 401.00 µs]
                        change: [-3.7465% -2.3347% -0.8310%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 12 outliers among 100 measurements (12.00%)
  5 (5.00%) low mild
  4 (4.00%) high mild
  3 (3.00%) high severe

gc view types slice half without nulls[100000]
                        time:   [422.70 µs 426.62 µs 430.63 µs]
                        change: [+2.9492% +5.2722% +7.6808%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 6 outliers among 100 measurements (6.00%)
  1 (1.00%) low mild
  4 (4.00%) high mild
  1 (1.00%) high severe

gc view types all[8000] time:   [16.079 µs 17.457 µs 18.815 µs]
                        change: [+47.350% +57.679% +66.216%] (p = 0.00 < 0.05)
                        Performance has regressed.

gc view types slice half[8000]
                        time:   [14.127 µs 15.144 µs 16.037 µs]
                        change: [+26.202% +34.352% +42.179%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 9 outliers among 100 measurements (9.00%)
  9 (9.00%) low mild

gc view types all without nulls[8000]
                        time:   [27.309 µs 28.280 µs 29.285 µs]
                        change: [-2.8581% -1.0174% +0.8766%] (p = 0.29 > 0.05)
                        No change in performance detected.
Found 15 outliers among 100 measurements (15.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild
  11 (11.00%) high severe

gc view types slice half without nulls[8000]
                        time:   [15.009 µs 15.857 µs 16.825 µs]
```

</details>

File: arrow-array/src/array/byte_view_array.rs (hunk 2 above)
Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs:1481]: Sorry -- to be clear I was confirming that the test covers the code added in this PR . I think the test is good

File: arrow-array/src/array/byte_view_array.rs (hunk 1 above)
Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs:549]: I see -- you are saying you could potentially optimize the input by looking at each input buffer or something and gcing it individually or something. 

That would be interesting, though it would probably take a lot of care to make it fast.

**Review by alamb — APPROVED** [review]
Thank you @mapleFU  - I went through this again and it looks good to me.

I would like to run the benchmarks one more time before merging this (I have queued them up on my machine so hopefully they'll post to this PR in a few hours)

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1017-gcp #18~24.04.1-Ubuntu SMP Tue Sep 23 17:51:44 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gc-fixing-huge-batch-bug (fdefa5f9b98ed17b517541315706c4ef6bca40bd) to 2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b [diff](https://github.com/apache/arrow-rs/compare/2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b..fdefa5f9b98ed17b517541315706c4ef6bca40bd)
BENCH_NAME=view_types
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench view_types 
BENCH_FILTER=
BENCH_BRANCH_NAME=gc-fixing-huge-batch-bug
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                             gc-fixing-huge-batch-bug               main
-----                                             ------------------------               ----
gc view types all without nulls[100000]           1.15  1826.5±78.25µs        ? ?/sec    1.00  1592.5±58.43µs        ? ?/sec
gc view types all without nulls[8000]             1.08     70.4±3.71µs        ? ?/sec    1.00     65.2±2.12µs        ? ?/sec
gc view types all[100000]                         1.12    311.7±8.19µs        ? ?/sec    1.00    277.7±3.63µs        ? ?/sec
gc view types all[8000]                           1.08     23.1±0.20µs        ? ?/sec    1.00     21.4±0.11µs        ? ?/sec
gc view types slice half without nulls[100000]    1.10   589.6±17.27µs        ? ?/sec    1.00   535.4±22.47µs        ? ?/sec
gc view types slice half without nulls[8000]      1.01     28.4±0.23µs        ? ?/sec    1.00     28.2±0.26µs        ? ?/sec
gc view types slice half[100000]                  1.11    155.6±2.98µs        ? ?/sec    1.00    140.0±3.30µs        ? ?/sec
gc view types slice half[8000]                    1.11     11.8±0.13µs        ? ?/sec    1.00     10.6±0.08µs        ? ?/sec
view types slice                                  1.00    707.2±1.74ns        ? ?/sec    1.00    705.9±3.69ns        ? ?/sec
```


</p>
</details>

File: arrow-array/src/array/byte_view_array.rs [hunk 9]
```diff
@@ -512,18 +512,71 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+            // Slow-path: need to split into multiple copy groups
+            let mut current_length = 0;
+            let mut current_elements = 0;
+
+            for view in self.views() {
+                let len = *view as u32;
+                if len > MAX_INLINE_VIEW_LEN {
+                    if current_length + len > i32::MAX as u32 {
+                        // Start a new group
+                        groups.push(GcCopyGroup {
```
Comment (Dandandan) [inline arrow-array/src/array/byte_view_array.rs]: I think you can preallocate `groups` (with_capacity) or use `.collect`

File: arrow-array/src/array/byte_view_array.rs [hunk 10]
```diff
@@ -512,18 +512,71 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
 
-        // 4) Iterate over views and process each inline/non-inline view
-        let views_buf: Vec<u128> = (0..len)
-            .map(|i| unsafe { self.copy_view_to_buffer(i, &mut data_buf) })
-            .collect();
+            // Directly push views to avoid intermediate Vec allocation
+            for view_idx in current_view_idx..current_view_idx + gc_copy_group.total_len {
+                let view =
+                    unsafe { self.copy_view_to_buffer(view_idx, group_idx as i32, &mut data_buf) };
+                views_buf.push(view);
```
Comment (Dandandan) [inline arrow-array/src/array/byte_view_array.rs]: This can use `Vec::collect`

File: arrow-array/src/array/byte_view_array.rs [hunk 11]
```diff
@@ -512,18 +512,71 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+            }
+
+            data_blocks.push(Buffer::from_vec(data_buf));
```
Comment (Dandandan) [inline arrow-array/src/array/byte_view_array.rs]: This coul as well use collect.

File: arrow-array/src/array/byte_view_array.rs (hunk 10 above)
Comment (mapleFU) [reply arrow-array/src/array/byte_view_array.rs]: `views_buf` is preallocated once, would `Vec::collect` allocate more buffer than currently?

Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs]: I think using collect doesn't allocate additional memory, but it can be faster than `push` because `collect` does the capacity check once where `push` has to check capacity on each call

Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs]: However, since both `Vec`s are being modified at the same time, I couldn't figure out a way to use `collect` here -- I could use extend

**Comment by alamb** [comment]
Here is a proposal to avoid the performance drop in this PR: 
- https://github.com/mapleFU/arrow-rs/pull/1

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1018-gcp #19~24.04.1-Ubuntu SMP Wed Sep 24 23:23:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gc-fixing-huge-batch-bug (fdefa5f9b98ed17b517541315706c4ef6bca40bd) to 2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b [diff](https://github.com/apache/arrow-rs/compare/2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b..fdefa5f9b98ed17b517541315706c4ef6bca40bd)
BENCH_NAME=view_types
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench view_types 
BENCH_FILTER=
BENCH_BRANCH_NAME=gc-fixing-huge-batch-bug
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                             gc-fixing-huge-batch-bug               main
-----                                             ------------------------               ----
gc view types all without nulls[100000]           1.00  1598.1±86.02µs        ? ?/sec    1.00  1600.7±40.51µs        ? ?/sec
gc view types all without nulls[8000]             1.09     69.9±3.72µs        ? ?/sec    1.00     64.2±2.67µs        ? ?/sec
gc view types all[100000]                         1.20    310.4±6.89µs        ? ?/sec    1.00    258.7±4.62µs        ? ?/sec
gc view types all[8000]                           1.18     21.9±0.40µs        ? ?/sec    1.00     18.6±0.05µs        ? ?/sec
gc view types slice half without nulls[100000]    1.00   535.2±12.38µs        ? ?/sec    1.06   566.1±14.03µs        ? ?/sec
gc view types slice half without nulls[8000]      1.05     28.7±0.40µs        ? ?/sec    1.00     27.4±0.23µs        ? ?/sec
gc view types slice half[100000]                  1.20    152.3±2.72µs        ? ?/sec    1.00    127.0±2.12µs        ? ?/sec
gc view types slice half[8000]                    1.18     11.0±0.16µs        ? ?/sec    1.00      9.4±0.03µs        ? ?/sec
view types slice                                  1.00    706.0±1.90ns        ? ?/sec    1.00    704.2±1.79ns        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
The [performance results](https://github.com/mapleFU/arrow-rs/pull/1#issuecomment-3497059583) on 
- https://github.com/mapleFU/arrow-rs/pull/1

Seem to confirm it avoids the performance regression

File: arrow-array/src/array/byte_view_array.rs (hunk 10 above)
Comment (mapleFU) [reply arrow-array/src/array/byte_view_array.rs]: I also think collect is possible here, would do it after work tonight

File: arrow-array/src/array/byte_view_array.rs [hunk 12]
```diff
@@ -512,18 +512,85 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+
+            // 4) Iterate over views and process each inline/non-inline view
+            let views_buf: Vec<u128> = (0..len)
+                .map(|i| unsafe { self.copy_view_to_buffer(i, 0, &mut data_buf) })
+                .collect();
+            let data_block = Buffer::from_vec(data_buf);
+            let data_blocks = vec![data_block];
+            (views_buf, data_blocks)
+        } else {
+            // slow path, need to split into multiple buffers
```
Comment (mapleFU) [inline arrow-array/src/array/byte_view_array.rs:528]: Would it better if I extract this into a new function?

File: arrow-array/src/array/byte_view_array.rs [hunk 13]
```diff
@@ -512,18 +512,85 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+                );
+                views_buf.extend(new_views);
+
+                data_blocks.push(Buffer::from_vec(data_buf));
+                current_view_idx += gc_copy_group.total_len;
+            }
+            (views_buf, data_blocks)
+        };
 
         // 5) Wrap up buffers
```
Comment (mapleFU) [inline arrow-array/src/array/byte_view_array.rs]: Should this change?

File: arrow-array/src/array/byte_view_array.rs [hunk 14]
```diff
@@ -512,18 +512,85 @@ impl<T: ByteViewType + ?Sized> GenericByteViewArray<T> {
...
+                        total_len,
+                    }
+                }
+            }
 
-        // 4) Iterate over views and process each inline/non-inline view
-        let views_buf: Vec<u128> = (0..len)
-            .map(|i| unsafe { self.copy_view_to_buffer(i, &mut data_buf) })
-            .collect();
+            let mut groups = Vec::with_capacity(total_large / (i32::MAX as usize) + 1);
```
Comment (mapleFU) [inline arrow-array/src/array/byte_view_array.rs]: I think this might not good, and allocation count in this slow path might not matters?

Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs]: I think you are referring tot his comment
- https://github.com/mapleFU/arrow-rs/pull/1#discussion_r2506878313

I didn't quite follow the concern, see https://github.com/mapleFU/arrow-rs/pull/1#discussion_r2508175348

However that being said we can revert this part too -- I don't feel strongly about it and I agree that the allocation likely doesn't matter on the slow path

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1018-gcp #19~24.04.1-Ubuntu SMP Wed Sep 24 23:23:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gc-fixing-huge-batch-bug (7bab6068c30b48f01b5bdd2099c1690d8532522e) to 2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b [diff](https://github.com/apache/arrow-rs/compare/2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b..7bab6068c30b48f01b5bdd2099c1690d8532522e)
BENCH_NAME=view_types
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench view_types 
BENCH_FILTER=
BENCH_BRANCH_NAME=gc-fixing-huge-batch-bug
Results will be posted here when complete

File: arrow-array/src/array/byte_view_array.rs (hunk 12 above)
Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs:528]: I think so!

File: arrow-array/src/array/byte_view_array.rs (hunk 13 above)
Comment (alamb) [reply arrow-array/src/array/byte_view_array.rs]: to what?

**Review by alamb — APPROVED** [review]
I think this PR is now ready to go and doesn't regress performance. I started another benchmark just to make sure

Thanks @mapleFU  -- I think we can hone it a bit more too if you want (extract the slow path as a function, for example) but we could also do it as a follow on as well

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                             gc-fixing-huge-batch-bug               main
-----                                             ------------------------               ----
gc view types all without nulls[100000]           1.00  1547.1±45.23µs        ? ?/sec    1.06  1645.8±51.47µs        ? ?/sec
gc view types all without nulls[8000]             1.00     62.9±1.90µs        ? ?/sec    1.11     69.6±3.63µs        ? ?/sec
gc view types all[100000]                         1.05    289.0±7.28µs        ? ?/sec    1.00    276.1±7.07µs        ? ?/sec
gc view types all[8000]                           1.08     21.4±0.05µs        ? ?/sec    1.00     19.9±0.06µs        ? ?/sec
gc view types slice half without nulls[100000]    1.00   538.3±10.61µs        ? ?/sec    1.04   558.2±11.69µs        ? ?/sec
gc view types slice half without nulls[8000]      1.00     26.6±0.13µs        ? ?/sec    1.08     28.8±0.19µs        ? ?/sec
gc view types slice half[100000]                  1.12    143.5±1.88µs        ? ?/sec    1.00    128.4±0.49µs        ? ?/sec
gc view types slice half[8000]                    1.07     10.8±0.02µs        ? ?/sec    1.00     10.1±0.02µs        ? ?/sec
view types slice                                  1.00    707.4±1.61ns        ? ?/sec    1.00    704.3±1.20ns        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1018-gcp #19~24.04.1-Ubuntu SMP Wed Sep 24 23:23:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gc-fixing-huge-batch-bug (7bab6068c30b48f01b5bdd2099c1690d8532522e) to 2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b [diff](https://github.com/apache/arrow-rs/compare/2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b..7bab6068c30b48f01b5bdd2099c1690d8532522e)
BENCH_NAME=view_types
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench view_types 
BENCH_FILTER=
BENCH_BRANCH_NAME=gc-fixing-huge-batch-bug
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                             gc-fixing-huge-batch-bug               main
-----                                             ------------------------               ----
gc view types all without nulls[100000]           1.00  1536.3±42.37µs        ? ?/sec    1.00  1541.4±48.54µs        ? ?/sec
gc view types all without nulls[8000]             1.00     62.4±0.94µs        ? ?/sec    1.00     62.5±0.96µs        ? ?/sec
gc view types all[100000]                         1.11    291.5±7.29µs        ? ?/sec    1.00    263.6±8.16µs        ? ?/sec
gc view types all[8000]                           1.14     21.4±0.10µs        ? ?/sec    1.00     18.8±0.06µs        ? ?/sec
gc view types slice half without nulls[100000]    1.02   533.8±10.33µs        ? ?/sec    1.00    522.4±9.07µs        ? ?/sec
gc view types slice half without nulls[8000]      1.01     27.3±0.20µs        ? ?/sec    1.00     27.0±0.17µs        ? ?/sec
gc view types slice half[100000]                  1.10    140.8±2.45µs        ? ?/sec    1.00    128.6±3.44µs        ? ?/sec
gc view types slice half[8000]                    1.14     10.8±0.05µs        ? ?/sec    1.00      9.5±0.03µs        ? ?/sec
view types slice                                  1.01    708.5±4.41ns        ? ?/sec    1.00    704.3±1.54ns        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1018-gcp #19~24.04.1-Ubuntu SMP Wed Sep 24 23:23:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gc-fixing-huge-batch-bug (7bab6068c30b48f01b5bdd2099c1690d8532522e) to 2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b [diff](https://github.com/apache/arrow-rs/compare/2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b..7bab6068c30b48f01b5bdd2099c1690d8532522e)
BENCH_NAME=view_types
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench view_types 
BENCH_FILTER=
BENCH_BRANCH_NAME=gc-fixing-huge-batch-bug
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                             gc-fixing-huge-batch-bug               main
-----                                             ------------------------               ----
gc view types all without nulls[100000]           1.01  1596.9±64.40µs        ? ?/sec    1.00  1576.0±51.87µs        ? ?/sec
gc view types all without nulls[8000]             1.02     69.2±3.05µs        ? ?/sec    1.00     67.9±3.82µs        ? ?/sec
gc view types all[100000]                         1.13    292.3±5.13µs        ? ?/sec    1.00    258.7±4.55µs        ? ?/sec
gc view types all[8000]                           1.14     21.4±0.08µs        ? ?/sec    1.00     18.9±0.04µs        ? ?/sec
gc view types slice half without nulls[100000]    1.00    529.0±8.57µs        ? ?/sec    1.06    561.0±9.12µs        ? ?/sec
gc view types slice half without nulls[8000]      1.00     27.1±0.20µs        ? ?/sec    1.02     27.5±0.27µs        ? ?/sec
gc view types slice half[100000]                  1.09    139.2±1.63µs        ? ?/sec    1.00    128.2±2.86µs        ? ?/sec
gc view types slice half[8000]                    1.14     10.8±0.03µs        ? ?/sec    1.00      9.5±0.02µs        ? ?/sec
view types slice                                  1.00    706.5±1.44ns        ? ?/sec    1.00    705.4±1.97ns        ? ?/sec
```


</p>
</details>

**Comment by mapleFU** [comment]
I've just change two lines here, it's ready to merge for me now

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1018-gcp #19~24.04.1-Ubuntu SMP Wed Sep 24 23:23:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gc-fixing-huge-batch-bug (c5146eb702d2bf75d7da572cfee626e5b6f5ef06) to 2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b [diff](https://github.com/apache/arrow-rs/compare/2eabb595d20e691cf0c9c3ccf6a5e1b67472b07b..c5146eb702d2bf75d7da572cfee626e5b6f5ef06)
BENCH_NAME=view_types
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench view_types 
BENCH_FILTER=
BENCH_BRANCH_NAME=gc-fixing-huge-batch-bug
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                             gc-fixing-huge-batch-bug               main
-----                                             ------------------------               ----
gc view types all without nulls[100000]           1.00  1562.0±59.51µs        ? ?/sec    1.01  1573.4±55.76µs        ? ?/sec
gc view types all without nulls[8000]             1.00     65.1±2.27µs        ? ?/sec    1.01     65.9±3.62µs        ? ?/sec
gc view types all[100000]                         1.00    282.1±4.21µs        ? ?/sec    1.02    289.1±6.12µs        ? ?/sec
gc view types all[8000]                           1.00     21.5±0.06µs        ? ?/sec    1.00     21.6±0.04µs        ? ?/sec
gc view types slice half without nulls[100000]    1.00    535.1±9.02µs        ? ?/sec    1.05   560.0±12.08µs        ? ?/sec
gc view types slice half without nulls[8000]      1.00     27.2±0.17µs        ? ?/sec    1.02     27.8±0.22µs        ? ?/sec
gc view types slice half[100000]                  1.00    138.6±0.90µs        ? ?/sec    1.04    144.1±2.50µs        ? ?/sec
gc view types slice half[8000]                    1.00     10.9±0.03µs        ? ?/sec    1.01     11.0±0.02µs        ? ?/sec
view types slice                                  1.00    704.9±1.05ns        ? ?/sec    1.00    703.7±0.95ns        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
Thanks again @mapleFU  -- sorry this one took so long but I think it is quite great now
