### PR TITLE
Error if Remote Ignores HTTP Range Header

### LINKED ISSUE #4839: object-store: http shouldn't perform range requests unless `accept-ranges: bytes` header is present
**Describe the bug**
if you have a remote file `https://somewhere.com/file.parquet` and your server does not support ranges as specified by the `accept-ranges: bytes` header, the object store should not try to perform range scans. 
**To Reproduce**

```rust
#[tokio::main]
async fn main() {
    let http = HttpBuilder::new().with_url("https://not.arealwebsite.com/file.parquet");
    let store = http.build().unwrap();
    let path = Path::default();
    let mut options = GetOptions::default();
    let some_range = 100..2000;
    options.range = Some(some_range);
    let data = store.get_opts(&path, options).await.unwrap();
}
```

**Expected behavior**
the range is ignored as the server doesn't specify it can handle it. 

**Additional context**

### PR DESCRIPTION
**Pull request by universalmind303**
# Which issue does this PR close?

Closes #4839

# Rationale for this change
 

# What changes are included in this PR?

If a range was requested and the server returned a 200 instead of a 206, we error out as it means that the server didn't fulfill the request. 

# Are there any user-facing changes?

this could cause some backwards incompatibility with previously working queries no longer working as we are now a bit stricter about what we are expecting. 

Some examples that would no longer work
- a server _could_ satisfy the range request, but due to misconfiguration is still returning a `200`. 
- the server never satisfied the range request & we fetched the entire data multiple times. 

The latter example is the one this is aiming to prevent. If it can't fulfill the range request, we shouldn't continue on as nothing happened, we should error instead of overfetching data.

### CODE REVIEW

File: object_store/src/http/client.rs [hunk 1]
```diff
@@ -252,7 +256,20 @@ impl Client {
                     }
                 }
                 _ => Error::Request { source }.into(),
-            })
+            })?;
+
+        // We expect a 206 Partial Content response if a range was requested
+        // a 200 OK response would indicate the server did not fulfill the request
+        if has_range && res.status() == StatusCode::OK {
+            return Err(crate::Error::Generic {
```
Comment (tustvold) [inline object_store/src/http/client.rs:264]: I think this should possibly be the NotSupported variant

**Review by tustvold — APPROVED** [review]
Just a minor niggle

File: object_store/src/http/client.rs [hunk 2]
```diff
@@ -252,7 +256,19 @@ impl Client {
                     }
                 }
                 _ => Error::Request { source }.into(),
-            })
+            })?;
+
+        // We expect a 206 Partial Content response if a range was requested
+        // a 200 OK response would indicate the server did not fulfill the request
+        if has_range && res.status() == StatusCode::OK {
```
Comment (tustvold) [inline object_store/src/http/client.rs:263]:
```suggestion
        if has_range && res.status() != StatusCode::PARTIAL_CONTENT {
```
