### PR TITLE
Clear row buffer before reuse

### LINKED ISSUE #4741: Row is no longer comparable after reuse
**Describe the bug**

The `Row` is no longer comparable when the `Rows` get reused after `Rows::clear()`.

**To Reproduce**

```rs
    #[test]
    fn test_clear() {
        let mut converter =
            RowConverter::new(vec![SortField::new(DataType::Int32)]).unwrap();
        let mut rows = converter.empty_rows(3, 128);

        let first = Int32Array::from(vec![None, Some(2), Some(4)]);
        let second = Int32Array::from(vec![Some(2), None, Some(4)]);

        let arrays = vec![
            Arc::new(first) as ArrayRef,
            Arc::new(second) as ArrayRef
        ];

        for array in arrays.iter() {
            rows.clear();
            converter.append(&mut rows, &[array.clone()]).unwrap();
            let back = converter.convert_rows(&rows).unwrap();
            assert_eq!(&back[0], array);
        }

        let mut rows_expected = converter.empty_rows(3, 128);
        converter.append(&mut rows_expected, &arrays[1..]).unwrap();

        for (i, (actual, expected)) in rows.iter().zip(rows_expected.iter()).enumerate() {
            assert_eq!(actual, expected, "For row {}: expected {:?}, actual: {:?}", i, expected, actual);
        }
    }
```

The test fails with:

```
For row 1: expected Row { data: [0, 0, 0, 0, 0], config: RowConfig { fields: [SortField { options: SortOptions { descending: false, nulls_first: true }, data_type: Int32, preserve_dictionaries: true }], validate_utf8: false } }, actual: Row { data: [0, 128, 0, 0, 2], config: RowConfig { fields: [SortField { options: SortOptions { descending: false, nulls_first: true }, data_type: Int32, preserve_dictionaries: true }], validate_utf8: false } }

```

**Expected behavior**

Pass the test.

**Additional context**

Encontered this while working on https://github.com/apache/arrow-datafusion/pull/7426

### PR DESCRIPTION
**Pull request by yjshen**
# Which issue does this PR close?

Closes #4741.

# Rationale for this change
When reusing rows buffer, previous rows' fixed-length field content isn't cleared, causing the `Row` to become incomparable if a null value is written for the new row.

# What changes are included in this PR?

Fill the `Rows` buffer with zero to keep the row comparable after buffer reuse.

# Are there any user-facing changes?
No.

### CODE REVIEW

File: arrow-row/src/lib.rs [hunk 1]
```diff
@@ -981,6 +981,9 @@ impl Rows {
     /// Sets the length of this [`Rows`] to 0
     pub fn clear(&mut self) {
         self.offsets.truncate(1);
+        unsafe {
```
Comment (tustvold) [inline arrow-row/src/lib.rs:984]: self.buffer.clear()` I think would achieve the same thing?

**Comment by tustvold** [comment]
Thank you
