### PR TITLE
Fix equality of nested nullable FixedSizeBinary (#4637)

### LINKED ISSUE #4637: `List(FixedSizeBinary)` array equality check may return wrong result
**Describe the bug**
`<ListArray as PartialEq>::eq` returns `false` for two arrays of datatype `List(FixedSizeBinary(5))` containing identical values but physically differ.

**To Reproduce**
```rust
#[test]
fn test_list_excess_children_equal() {
    let a_values = create_fixed_size_binary_array([Some(b"11111"), Some(b"22222"), None]);
    //                                             ^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^
    //                                             a[0]            a[1]
    let a: ListArray = ArrayDataBuilder::new(DataType::List(Arc::new(Field::new(
        "item",
        a_values.data_type().clone(),
        true,
    ))))
    .len(2)
    .add_buffer(Buffer::from(vec![0i32, 1, 3].to_byte_slice()))
    .add_child_data(a_values.into_data())
    .null_bit_buffer(Some(Buffer::from(&[0b00000010])))
    .build()
    .unwrap()
    .into();

    let b_values = create_fixed_size_binary_array([Some(b"22222"), None]);
    //                                             ^^^^^^^^^^^^^^^^^^^^
    //                                             a[1]
    let b: ListArray = ArrayDataBuilder::new(DataType::List(Arc::new(Field::new(
        "item",
        b_values.data_type().clone(),
        true,
    ))))
    .len(2)
    .add_buffer(Buffer::from(vec![0i32, 0, 2].to_byte_slice()))
    .add_child_data(b_values.into_data())
    .null_bit_buffer(Some(Buffer::from(&[0b00000010])))
    .build()
    .unwrap()
    .into();

    a.to_data().validate_full().unwrap();
    b.to_data().validate_full().unwrap();

    assert_eq!(a, b);
}

// from `arrow/tests/array_equal.rs`
fn create_fixed_size_binary_array<U: AsRef<[u8]>, T: AsRef<[Option<U>]>>(
    data: T,
) -> FixedSizeBinaryArray {
    let mut builder = FixedSizeBinaryBuilder::with_capacity(data.as_ref().len(), 5);

    for d in data.as_ref() {
        if let Some(v) = d {
            builder.append_value(v.as_ref()).unwrap();
        } else {
            builder.append_null();
        }
    }
    builder.finish()
}
```

```
thread 'test_list_excess_children_equal' panicked at 'assertion failed: `(left == right)`
  left: `ListArray
[
  null,
  FixedSizeBinaryArray<5>
[
  [50, 50, 50, 50, 50],
  null,
],
]`,
 right: `ListArray
[
  null,
  FixedSizeBinaryArray<5>
[
  [50, 50, 50, 50, 50],
  null,
],
]`', arrow\tests\array_equal.rs:399:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
Returning `true` because they both contain `[null, [[50, 50, 50, 50, 50], null]]` as shown by the debug printing

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4637

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-data/src/equal/fixed_binary.rs [hunk 1]
```diff
@@ -80,7 +80,7 @@ pub(super) fn fixed_binary_equal(
                 lhs_start + lhs_nulls.offset(),
                 len,
             );
-            let rhs_nulls = lhs.nulls().unwrap();
+            let rhs_nulls = rhs.nulls().unwrap();
```
Comment (tustvold) [inline arrow-data/src/equal/fixed_binary.rs:83]: It is actually remarkably hard to construct a test case to exercise this, kudos to @kawadakk for finding one. The reason it is hard is at this point the null masks have already been checked for equality, so you need one side to have a different start offset from the other, such that when correctly offset the null buffers compare equal, but the underlying buffers themselves are not actually equal

**Review by jackwener — APPROVED** [review]

File: arrow-data/src/equal/fixed_binary.rs (hunk 1 above)
Comment (alamb) [reply arrow-data/src/equal/fixed_binary.rs:83]: 😮  -- nice find @kawadakk  and @tustvold

**Review by alamb — COMMENTED** [review]
love it ❤️
