### PR TITLE
Handle compressed empty DataPage v2

### LINKED ISSUE #7388: Reading empty DataPageV2 fails with `snappy: corrupt input (empty)`
**Describe the bug**
Reading a Parquet file that contains an empty DataPage v2 fails with `snappy: corrupt input (empty)`.
Such a page occurs when all values are null.

**To Reproduce**
Writing a Spark dataset that contains only `null` values in one column using `v2` Parquet writer:
```
./spark-3.5.5-bin-hadoop3/bin/spark-shell --conf spark.hadoop.parquet.writer.version="v2"
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.5.5
      /_/
         
Using Scala version 2.12.18 (OpenJDK 64-Bit Server VM, Java 11.0.26)
Type in expressions to have them evaluated.
Type :help for more information.

scala> Seq(Option.empty[Float]).toDS.write.parquet("parquet-v2-example.parquet")
```

**Expected behavior**
The Parquet file should be read.

**Additional context**
The issue is identical to this Apache Arrow issue: https://github.com/apache/arrow/issues/22459
The fix is identical to Apache Arrow fix: https://github.com/apache/arrow/pull/45252

### PR DESCRIPTION
**Pull request by EnricoMi**
# Which issue does this PR close?
- Closes #7388.

# Rationale for this change
An empty bytes buffer cannot be decompressed. Spark's Parquet writer stores a DataPage v2 with only `null` values as an empty byte buffer, rather than compressed bytes that decompress to zero bytes.

The code currently tries to decompress a 0 bytes buffer, which is not allowed. This causes an error:

    snappy: corrupt input (empty)

The issue is identical to this Apache Arrow issue: https://github.com/apache/arrow/issues/22459
The fix is identical to Apache Arrow fix: https://github.com/apache/arrow/pull/45252

# What changes are included in this PR?
Do not attempt to decompress the empty bytes buffer.
This is tested in a unit test and a small example Parquet file.
Requires https://github.com/apache/parquet-testing/pull/74.

# Are there any user-facing changes?
No.

### CODE REVIEW

File: parquet/src/file/serialized_reader.rs [hunk 1]
```diff
@@ -1321,6 +1320,108 @@ mod tests {
...
+            row_group_reader.num_columns(),
+            row_group_metadata.num_columns()
+        );
+        assert_eq!(
+            row_group_reader.metadata().total_byte_size(),
+            row_group_metadata.total_byte_size()
+        );
+
+        // Test page readers
+        // TODO: test for every column
```
Comment (adamreeve) [inline parquet/src/file/serialized_reader.rs:1376]: Does this TODO need to be done before merging the PR? I think it's sufficient to just test one column and this comment could be removed.

File: parquet/src/file/serialized_reader.rs [hunk 2]
```diff
@@ -452,21 +452,20 @@ pub(crate) fn decode_page(
...
+            let uncompressed_page_size = page_header.uncompressed_page_size as usize;
+            let decompressed_size = uncompressed_page_size - offset;
+            let mut decompressed = Vec::with_capacity(uncompressed_page_size);
             decompressed.extend_from_slice(&buffer.as_ref()[..offset]);
-            decompressor.decompress(
-                compressed,
-                &mut decompressed,
-                Some(uncompressed_size - offset),
-            )?;
+            if decompressed_size != 0 {
```
[the remark this answers is not in the document]
Comment (adamreeve) [reply parquet/src/file/serialized_reader.rs:459]: Should we add an extra check and return an error if `offset > uncompressed_page_size`?

File: parquet/src/file/serialized_reader.rs (hunk 1 above)
Comment (EnricoMi) [reply parquet/src/file/serialized_reader.rs:1376]: This is a copy of `test_file_reader_datapage_v2` above, including pending TODOs.

https://github.com/apache/arrow-rs/pull/7389/files#diff-d8c04f8d20f9c5ae22276e30243c1c099722a7b36d3cba3df00f6ee75ef52dcdR1226

Sine there is only one column in this test file, I can safely remove this TODO as DONE for my test.

**Comment by EnricoMi** [comment]
@mapleFU @pitrou this ports your bugfix https://github.com/apache/arrow/pull/45252 from Arrow C++ to Rust.

File: parquet/src/file/serialized_reader.rs [hunk 3]
```diff
@@ -452,21 +452,20 @@ pub(crate) fn decode_page(
     // maximum page header size and abort if that is exceeded.
     let buffer = match decompressor {
         Some(decompressor) if can_decompress => {
-            let uncompressed_size = page_header.uncompressed_page_size as usize;
-            let mut decompressed = Vec::with_capacity(uncompressed_size);
-            let compressed = &buffer.as_ref()[offset..];
+            let uncompressed_page_size = page_header.uncompressed_page_size as usize;
```
Comment (alamb) [inline parquet/src/file/serialized_reader.rs:455]: If we are going to be messing with this code anyways, maybe we can do a checked conversion from signed to unsigned as well:

```suggestion
            let uncompressed_page_size = usize::try_from(page_header.uncompressed_page_size)?;
```

File: parquet/src/file/serialized_reader.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (alamb) [reply parquet/src/file/serialized_reader.rs:459]: Yes please! Otherwise we may be susceptible to some sort of DOS / parquet bomb with malformed input

[the remark this answers is not in the document]
Comment (alamb) [reply parquet/src/file/serialized_reader.rs:459]: > I'd prefer

FWIW since `decompressed_size` is an unsigned integer I think they are equivalent you should do whatever you prefer / makes the most sense to you

File: parquet/src/file/serialized_reader.rs [hunk 4]
```diff
@@ -1321,6 +1320,107 @@ mod tests {
         assert_eq!(page_count, 2);
     }
 
+    #[test]
+    fn test_file_reader_empty_datapage_v2() {
+        let test_file = get_test_file("datapage_v2_empty_datapage.snappy.parquet");
```
Comment (alamb) [inline parquet/src/file/serialized_reader.rs:1325]: While we are adding tests, can you also add a test that `page_v2_empty_compressed.parquet` (added in https://github.com/apache/parquet-testing/pull/71)  works too ? It doesn't seem to be used yet https://github.com/search?q=repo%3Aapache%2Farrow-rs%20page_v2_empty_compressed.parquet&type=code

I know you say the current reader works ok with that file, but it would be nice to add additional automated coverage

File: parquet/src/file/serialized_reader.rs [hunk 5]
```diff
@@ -1321,6 +1320,107 @@ mod tests {
...
+                    assert!(is_compressed);
+                    assert!(statistics.is_none());
+                    true
+                }
+                _ => false,
+            };
+            assert!(is_expected_page);
+            page_count += 1;
+        }
+        assert_eq!(page_count, 1);
```
Comment (alamb) [inline parquet/src/file/serialized_reader.rs:1421]: I double checked that the added test fails as follows without the code changes in this PR
```
assertion `left == right` failed
  left: 0
 right: 1

Left:  0
Right: 1
<Click to see difference>

thread 'file::serialized_reader::tests::test_file_reader_empty_datapage_v2' panicked at parquet/src/file/serialized_reader.rs:1422:9:
assertion `left == right` failed
  left: 0
 right: 1
stack backtrace:
```

**Review by alamb — COMMENTED** [review]
Thank you @EnricoMi and @adamreeve

This is looking good.

File: parquet/src/file/serialized_reader.rs (hunk 5 above)
Comment (EnricoMi) [reply parquet/src/file/serialized_reader.rs:1525]: Changed the `while let Ok(Some(page)) = page_reader_0.get_next_page() {` to `while let Some(page) = page_reader_0.get_next_page().unwrap() {` so it is obvious why expected pages are not seen (now the error surfaces).

**Review by adamreeve — APPROVED** [review]

**Review by alamb — APPROVED** [review]
Thank you @EnricoMi and @adamreeve

**Comment by Dandandan** [comment]
Thanks @EnricoMi

**Comment by EnricoMi** [comment]
@Dandandan thanks! Will this be released as 56.0.0 and 55.0.1?

**Comment by alamb** [comment]
> @Dandandan thanks! Will this be released as 56.0.0 and 55.0.1?

It is scheduled to be released in 55.1.0 due in a few weeks
- #7393
