### PR TITLE
fix: ensure take_fixed_size_list can handle null indices

### LINKED ISSUE #5169: Take panics on a fixed size list array when given null indices
**Describe the bug**
When running `arrow_select::take::take` on a `FixedSizeListArray` and passing in indices that contain null then there is a panic:

```
thread 'take::tests::test_take_fixed_list_null_indices' panicked at arrow-data/src/data.rs:533:9:
assertion failed: (offset + length) <= self.len()
```

**To Reproduce**

```
    #[test]
    fn test_take_fixed_list_null_indices() {
        let indices = Int32Array::new(vec![0, 1].into(), Some(NullBuffer::from(vec![true, false])));
        let values = Arc::new(Int32Array::from(vec![0, 1, 2, 3]));
        let arr_field = Arc::new(Field::new("item", values.data_type().clone(), true));
        let values = FixedSizeListArray::try_new(arr_field, 2, values, None).unwrap();

        let r = take(&values, &indices, None).unwrap();
        let values = r
            .as_fixed_size_list()
            .values()
            .as_primitive::<Int32Type>()
            .into_iter()
            .collect::<Vec<_>>();
        assert_eq!(&values, &[Some(0), Some(1), None, None])
    }
```

**Expected behavior**
There is no panic and the take operation returns what is expected.

**Additional context**
I encountered this issue running full outer joins in datafusion on batches that have fixed size list arrays in the payloads.  The outer join implementation appears to materialize nulls (when one side doesn't match) by using take with null indices.

### PR DESCRIPTION
**Pull request by westonpace**
# Which issue does this PR close?

Closes #5169 

# Rationale for this change
 
See issue

# What changes are included in this PR?

The take implementation for fixed size list currently works by expanding the indices from "list indices" into "child indices".  In other words, if the list is a fixed size list of 3 and the indices are `[0, 5]` then it converts this into `[0, 1, 2, 15, 16, 17]`.  This process was ignoring null indices and the result was that the child array would be too short.  For example, `[0, null]` would turn into `[0, 1, 2]` which is too short.  This PR propagates the null into the child index list.  So now `[0, null]` turns into `[0, 1, 2, null, null, null]`.

# Are there any user-facing changes?

None

### CODE REVIEW

File: arrow-select/src/take.rs [hunk 1]
```diff
@@ -1985,6 +1987,23 @@ mod tests {
         assert_eq!(&values, &[Some(23), Some(4), None, None])
     }
 
+    #[test]
+    fn test_take_fixed_size_list_null_indices() {
+        let indices = Int32Array::new(vec![0, 1].into(), Some(NullBuffer::from(vec![true, false])));
```
Comment (wjones127) [inline arrow-select/src/take.rs:1992]: nit: maybe more straight forward to not separate values and nullability:
```suggestion
        let indices = Int32Array::from_iter([Some(1), None]);
```

File: arrow-select/src/take.rs
Comment (wjones127) [inline arrow-select/src/take.rs:1]: It would also be nice to pre-compute the `capacity` of the `values` vector here:

https://github.com/apache/arrow-rs/blob/932e0df1e7c888e56bae3eab3419ac33c87aa127/arrow-select/src/take.rs#L692

File: arrow-select/src/take.rs [hunk 2]
```diff
@@ -1985,6 +1987,23 @@ mod tests {
...
+        let values = FixedSizeListArray::try_new(arr_field, 2, values, None).unwrap();
+
+        let r = take(&values, &indices, None).unwrap();
+        let values = r
+            .as_fixed_size_list()
+            .values()
+            .as_primitive::<Int32Type>()
+            .into_iter()
+            .collect::<Vec<_>>();
+        assert_eq!(&values, &[Some(0), Some(1), None, None])
```
Comment (wjones127) [inline arrow-select/src/take.rs:2004]: nit: You can directly compare `&ScalarBuffer` and a slice.
```suggestion
        let values = r
            .as_fixed_size_list()
            .values()
            .as_primitive::<Int32Type>()
            .values();
        assert_eq!(values, &[Some(0), Some(1), None, None])
```

**Review by wjones127 — CHANGES_REQUESTED** [review]

File: arrow-select/src/take.rs (hunk 2 above)
Comment (westonpace) [reply arrow-select/src/take.rs]: You can compare `ScalarBuffer` with `[T]` but not with `[Option<T>]`

File: arrow-select/src/take.rs [hunk 3]
```diff
@@ -689,7 +689,7 @@ fn take_value_indices_from_fixed_size_list<IndexType>(
 where
     IndexType: ArrowPrimitiveType,
 {
-    let mut values = vec![];
+    let mut values = Vec::with_capacity(length as usize * indices.len());
```
Comment (wjones127) [inline arrow-select/src/take.rs:692]: On second thought, we should make this `PrimitiveBuilder`, since the conversion from `Vec` is no longer zero-copy when it's an Option.

Comment (westonpace) [reply arrow-select/src/take.rs]: Switched to a builder

**Review by wjones127 — APPROVED** [review]
