### PR TITLE
Fix parquet definition levels

### LINKED ISSUE #385: Crash when writing Parquet with non-nullable ListArray
Possibly related: #282, #270.

Minimal reproducing code [here](https://github.com/hohav/arrow-parquet-list-test).

Trying to write a Parquet file containing a variable-length array with non-nullable items results in this panic:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', .../parquet-4.1.0/src/util/bit_util.rs:332:9
```

### PR DESCRIPTION
**Pull request by nevi-me**
# Which issue does this PR close?

Relates to #385, but does not close it.

# Rationale for this change

While investigating #385, I noticed that there was a discrepancy between the max definitions calculated in `parquet::arrow::levels.` and what the parquet type system emits. So I kept digging, and found that my interpretation of the rules had errors.
 
- non-null primitive should have def = 0, was misinterpreting the spec
- list increments 1 if not null, or 2 if null

This fixes these issues, and updates the tests

# What changes are included in this PR?

Described above

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by nevi-me** [comment]
@hohav may you please point your test repro to my branch, write the file, then confirm if parquet tools sees the correct output.

I don't have the Java parquet tools, so it'll be quicker if you do that. Thanks

File: parquet/src/arrow/levels.rs [hunk 1]
```diff
@@ -334,37 +336,30 @@ impl LevelInfo {
...
         match (self.level_type, level_type) {
             (LevelType::List(_), LevelType::List(is_nullable)) => {
                 // parent is a list or descendant of a list, and child is a list
                 let reps = self.repetition.clone().unwrap();
                 // Calculate the 2 list hierarchy definitions in advance
-                // List is not empty, but null
-                let l2 = max_definition - is_nullable as i16;
-                // List is not empty, and not null
+
+                // TODO: Update this to be similar to the 1-level list
```
Comment (nevi-me) [inline parquet/src/arrow/levels.rs:356]: This TODO was because I was lazy, then ended up updating. I'll remove it

**Comment by hohav** [comment]
This branch does remove the assertion panic I initially ran into. `parquet cat` still crashes on the resulting file in all cases. Output from `parquet meta`:

* [v1](https://github.com/hohav/arrow-parquet-list-test/blob/master/src/main.rs): `count 6 / nulls 1`
* [v2](https://github.com/hohav/arrow-parquet-list-test/blob/v2/src/main.rs): `count 3 / nulls 1` (unchanged)
* [v3](https://github.com/hohav/arrow-parquet-list-test/blob/v3/src/main.rs): `count 2 / nulls 0` (previously `count 2 / nulls 2`)

**Comment by nevi-me** [comment]
Hi @hohav, I've looked at all 3 versions, and I see that while this PR fixes the repetition issue, it doesn't address your specific issue because of the writer bug that I indicated in #385.

I see that you also tested against

```toml
arrow = { git = "https://github.com/apache/arrow-rs.git" }
parquet = { git = "https://github.com/apache/arrow-rs.git" }
```

I might have not been clear enough, I had meant for you to test against

```toml
arrow = { git = "https://github.com/nevi-me/arrow-rs.git", branch = "parquet-fix-levels" }
parquet = { git = "https://github.com/nevi-me/arrow-rs.git", branch = "parquet-fix-levels" }
```

It's not an issue though, as I've cloned your repro repo, and installed parquet-mr tools to check what you're seeing.

The solution is two-fold, this PR, and then computing stats in #512 so that we avoid the column writer computing these stats.

I don't have enough bandwidth to drive #512, would you be able to help with it? I think the main tasks would be:

- checking that the stats for lists make sense (they should, but we probably need tests)
- adding stats for fixed-len binary where it makes sense.

It would be a good exercise in digging into the arrow compute code.

CC @alamb @jorgecarleitao for a review.

File: parquet/src/arrow/arrow_writer.rs [hunk 2]
```diff
@@ -712,6 +711,47 @@ mod tests {
...
+        // build a record batch
+        let batch =
+            RecordBatch::try_new(Arc::new(schema.clone()), vec![Arc::new(a)]).unwrap();
+
+        assert_eq!(batch.column(0).data().null_count(), 0);
+
+        let file = get_temp_file("test_arrow_writer_list_non_null.parquet", &[]);
+        let mut writer = ArrowWriter::try_new(file, Arc::new(schema), None).unwrap();
+        writer.write(&batch).unwrap();
+        writer.close().unwrap();
```
Comment (alamb) [inline parquet/src/arrow/arrow_writer.rs:752]: I noticed other tests like `arrow_writer_binary` also read data back from parquet and validate the results (and thus confirm data survives the roundtrip).

Would it make sense to have the same test here as well?

**Review by alamb — APPROVED** [review]
I don't fully grok the definition level details so I can't really say if this is correct or not, but I reviewed the tests and skimmed the code and it seems reasonable to me. 👍

File: parquet/src/arrow/arrow_writer.rs (hunk 2 above)
Comment (nevi-me) [reply parquet/src/arrow/arrow_writer.rs]: @alamb it's because `fn roundtrip` was added after these tests existed (and I think the reader was lagging behind the writer), so we never expanded it to them. I've now done so, removing quite a bit of duplication.

**Comment by hohav** [comment]
Hi @nevi-me, thanks again for taking a look at this. I did test against both your branch and master, though it's possible I messed up while juggling so many variants.

I can take a stab at #512 when I find time, but would that also address the crash in `parquet cat`? If not, do you know what's causing it?

File: parquet/src/arrow/arrow_writer.rs (hunk 2 above)
Comment (alamb) [reply parquet/src/arrow/arrow_writer.rs]: Looks much nicer 👍
