### PR TITLE
[Variant] feat: remove unnecessary unwraps in `Object::finish`

### LINKED ISSUE #8184: Make `ObjectBuilder::finish` signature infallible
Once 
* https://github.com/apache/arrow-rs/issues/8180 

is addressed, the method can no longer fail and no longer needs to return a `Result`.

### PR DESCRIPTION
**Pull request by Weijun-H**
# Which issue does this PR close?

- Closes #8184

# Rationale for this change

# What changes are included in this PR?

There is no need to duplicate the description in the issue here but it is sometimes worth providing a summary of the individual changes in this PR.

# Are these changes tested?
Yes

# Are there any user-facing changes?
`Object::finish` doesn't return `Result` anymore

### CODE REVIEW

File: parquet-variant/src/builder.rs [hunk 1]
```diff
@@ -1994,15 +1980,15 @@ mod tests {
         {
             let mut object_builder = list_builder.new_object();
             object_builder.insert("a", 1);
-            let _ = object_builder.finish();
```
Comment (scovich) [inline parquet-variant/src/builder.rs:2172]: Yipes -- the original code was buggy, ignoring a `Result`!

(fortunately it doesn't matter any more)

**Review by alamb — APPROVED** [review]
Thank you so much @Weijun-H  -- this is a really nice cleanup ❤️ 

And thank you @scovich  for the reviews

**Comment by alamb** [comment]
I pushed a commit to fix some logical conflicts too

**Comment by alamb** [comment]
Thanks again
