### PR TITLE
Fix: `date_part` to extract only the requested part (not the overall interval)

### LINKED ISSUE #7182: `date_part` using an interval returns an incorrect result
**Describe the bug**

It looks like `date_part` using an interval will return the whole interval instead of taking out the part.

**To Reproduce**

```rust
use arrow::array::{Int32Array, IntervalMonthDayNanoArray, TimestampSecondArray};
use arrow::compute::{date_part, DatePart};
use arrow::datatypes::IntervalMonthDayNano;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let array = TimestampSecondArray::from(vec![305]); // 5 minutes, 5 seconds
    let result = date_part(&array, DatePart::Second)?
        .as_any()
        .downcast_ref::<Int32Array>()
        .unwrap()
        .iter()
        .collect::<Vec<Option<i32>>>();
    assert_eq!(result, &[Some(5)]); // As expected

    let array = IntervalMonthDayNanoArray::from(vec![
        IntervalMonthDayNano::new(0, 0, 305 * 1_000_000_000), // 0 months, 0 days, 305 seconds
    ]);
    let res: Vec<Option<i32>> = date_part(&array, DatePart::Second)?
        .as_any()
        .downcast_ref::<Int32Array>()
        .unwrap()
        .iter()
        .collect::<Vec<Option<i32>>>();
    assert_eq!(res, &[Some(5)]); // Fails, result is 305

    Ok(())
}
```

**Expected behavior**

`date_part` returns the requested part.

**Additional context**

https://github.com/apache/datafusion/issues/14817

### PR DESCRIPTION
**Pull request by delamarch3**
# Which issue does this PR close?

- Closes #7182

# Rationale for this change
`date_part` with an interval returns results inconsistent with implementations in duckdb and postgres.
 

# What changes are included in this PR?
Parts are excluded from the interval: 
Milliseconds, microseconds and nanoseconds will exclude the minutes and hours from the date part, but not seconds, so `date_part('ms', interval '61s')` will return 1000
Seconds will exclude minutes and hours, so `date_part('s', interval '3600s')` will return 0
Hours will not exclude days, so `date_part('h', interval '25h')` returns 25
Months will exclude years, so `date_part('month', interval '13 months')` returns 1

# Are there any user-facing changes?
Yes, `date_part` with `IntervalDayTimeType` and `IntervalMonthDayNanoType` will return a different result

### CODE REVIEW

File: arrow-arith/src/temporal.rs [hunk 1]
```diff
@@ -488,25 +492,31 @@ impl ExtractDatePartExt for PrimitiveArray<IntervalMonthDayNanoType> {
     fn date_part(&self, part: DatePart) -> Result<Int32Array, ArrowError> {
         match part {
             DatePart::Year => Ok(self.unary_opt(|d: IntervalMonthDayNano| Some(d.months / 12))),
-            DatePart::Month => Ok(self.unary_opt(|d: IntervalMonthDayNano| Some(d.months))),
+            DatePart::Month => Ok(self.unary_opt(|d: IntervalMonthDayNano| Some(d.months % 12))),
```
Comment (delamarch3) [inline arrow-arith/src/temporal.rs:495]:
```sql
D SELECT datepart('year', interval '12 month');
┌────────────────────────────────────────────────┐
│ datepart('year', CAST('12 month' AS INTERVAL)) │
│                     int64                      │
├────────────────────────────────────────────────┤
│                       1                        │
└────────────────────────────────────────────────┘
D SELECT datepart('month', interval '12 month');
┌─────────────────────────────────────────────────┐
│ datepart('month', CAST('12 month' AS INTERVAL)) │
│                      int64                      │
├─────────────────────────────────────────────────┤
│                        0                        │
└─────────────────────────────────────────────────┘
```

File: arrow-arith/src/temporal.rs [hunk 2]
```diff
@@ -464,11 +464,15 @@ impl ExtractDatePartExt for PrimitiveArray<IntervalDayTimeType> {
...
-            DatePart::Nanosecond => Ok(self.unary_opt(|d| d.milliseconds.checked_mul(1_000_000))),
+            DatePart::Minute => Ok(self.unary_opt(|d| Some(d.milliseconds / (60 * 1_000) % 60))),
+            DatePart::Second => Ok(self.unary_opt(|d| Some(d.milliseconds / 1_000 % 60))),
+            DatePart::Millisecond => Ok(self.unary_opt(|d| Some(d.milliseconds % (60 * 1_000)))),
+            DatePart::Microsecond => {
+                Ok(self.unary_opt(|d| (d.milliseconds % (60 * 1_000)).checked_mul(1_000)))
+            }
+            DatePart::Nanosecond => {
+                Ok(self.unary_opt(|d| (d.milliseconds % (60 * 1_000)).checked_mul(1_000_000)))
+            }
```
Comment (delamarch3) [inline arrow-arith/src/temporal.rs:475]:
```sql
D SELECT datepart('m', interval '1m 61s 33ms 44us');
┌─────────────────────────────────────────────────────┐
│ datepart('m', CAST('1m 61s 33ms 44us' AS INTERVAL)) │
│                        int64                        │
├─────────────────────────────────────────────────────┤
│                          2                          │
└─────────────────────────────────────────────────────┘
D SELECT datepart('s', interval '1m 61s 33ms 44us');
┌─────────────────────────────────────────────────────┐
│ datepart('s', CAST('1m 61s 33ms 44us' AS INTERVAL)) │
│                        int64                        │
├─────────────────────────────────────────────────────┤
│                          1                          │
└─────────────────────────────────────────────────────┘
D SELECT datepart('ms', interval '1m 61s 33ms 44us');
┌──────────────────────────────────────────────────────┐
│ datepart('ms', CAST('1m 61s 33ms 44us' AS INTERVAL)) │
│                        int64                         │
├──────────────────────────────────────────────────────┤
│                         1033                         │
└──────────────────────────────────────────────────────┘
D SELECT datepart('us', interval '1m 61s 33ms 44us');
┌──────────────────────────────────────────────────────┐
│ datepart('us', CAST('1m 61s 33ms 44us' AS INTERVAL)) │
│                        int64                         │
├──────────────────────────────────────────────────────┤
│                       1033044                        │
│                    (1.03 million)                    │
└──────────────────────────────────────────────────────┘
```

File: arrow-arith/src/temporal.rs [hunk 3]
```diff
@@ -464,11 +464,15 @@ impl ExtractDatePartExt for PrimitiveArray<IntervalDayTimeType> {
             DatePart::Week => Ok(self.unary_opt(|d| Some(d.days / 7))),
             DatePart::Day => Ok(self.unary_opt(|d| Some(d.days))),
             DatePart::Hour => Ok(self.unary_opt(|d| Some(d.milliseconds / (60 * 60 * 1_000)))),
```
Comment (delamarch3) [inline arrow-arith/src/temporal.rs:466]:
```sql
D SELECT datepart('hour', interval '25 hour');
┌───────────────────────────────────────────────┐
│ datepart('hour', CAST('25 hour' AS INTERVAL)) │
│                     int64                     │
├───────────────────────────────────────────────┤
│                      25                       │
└───────────────────────────────────────────────┘
D SELECT datepart('day', interval '25 hour');
┌──────────────────────────────────────────────┐
│ datepart('day', CAST('25 hour' AS INTERVAL)) │
│                    int64                     │
├──────────────────────────────────────────────┤
│                      0                       │
└──────────────────────────────────────────────┘
```

File: arrow-arith/src/temporal.rs (hunk 1 above)
Comment (alamb) [reply arrow-arith/src/temporal.rs:495]: Postgres agrees

```sql
postgres=# SELECT extract (month from interval '12 month');
 extract
---------
       0
(1 row)
```

Before this PR arrow also currently says 12.

```sql
> SELECT datepart('month', interval '12 month');
+---------------------------------------------------------------------------------------------------------------+
| date_part(Utf8("month"),IntervalMonthDayNano("IntervalMonthDayNano { months: 12, days: 0, nanoseconds: 0 }")) |
+---------------------------------------------------------------------------------------------------------------+
| 12                                                                                                            |
+---------------------------------------------------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.001 seconds.
```

I think this change makes sense

**Review by alamb — APPROVED** [review]
Thank you @delamarch3  -- this makes sense to me


cc @Omega359 

Related
- https://github.com/apache/arrow-rs/issues/7182

Thank you very much

**Comment by Omega359** [comment]
I agree this change makes sense for consistency with established systems.

**Comment by tustvold** [comment]
As this is a behaviour change, even if the consensus appears to be that the current behaviour is somewhere between undesirable and a bug, should this wait until the next major release?

**Comment by alamb** [comment]
> As this is a behaviour change, even if the consensus appears to be that the current behaviour is somewhere between undesirable and a bug, should this wait until the next major release?

That probably makes sense

That will be in April so not that long:
- https://github.com/apache/arrow-rs/issues/7084

**Comment by alamb** [comment]
Marking with label

**Comment by alamb** [comment]
🚀  -- thank you for your patience @delamarch3
