### PR TITLE
fix(parquet): converting parquet schema with backward compatible repeated struct/primitive with provided arrow schema

### LINKED ISSUE #8495: providing the same schema that read from backward compatible parquet fails: incompatible arrow schema, expected struct got List
**Describe the bug**
When reading a file that was created with older parquet writer (parquet-mr specificlly) and passing a schema that got from `ArrowReaderMetadata` fails with:
```
ArrowError("incompatible arrow schema, expected struct got List(Field { name: \"col_15\", data_type: Struct([Field { name: \"col_16\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"col_17\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"col_18\", data_type: Struct([Field { name: \"col_19\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"col_20\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} })")
```

**To Reproduce**

I've added the file in:
- https://github.com/apache/parquet-testing/pull/96

#### 1 liner

Run this in datafusion-cli
```sql
select * from 'https://github.com/apache/parquet-testing/raw/6d1dae7ac5dfb23fa1ac1fed5b77d3b919fbb5f8/data/backward_compat_nested.parquet';
```

#### Only the relevant parts

This is the reproduction when taking from `datafusion` only the relevant parts that got to that error 

`Cargo.toml`:
```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "56.2.0"
parquet = "56.2.0"
bytes = "1.10.1"
```

`main.rs`:
```rust
use std::sync::Arc;
use bytes::Bytes;
use parquet::arrow::arrow_reader::{ArrowReaderMetadata, ArrowReaderOptions};

fn main() {
    // The file is the file that added here: https://github.com/apache/parquet-testing/pull/96
    let file_path = "/private/tmp/parquet-testing/data/backward_compat_nested.parquet".to_string();
    
    let mut data = Bytes::from(std::fs::read(file_path).unwrap());

    let mut options = ArrowReaderOptions::new();
    let reader_metadata = ArrowReaderMetadata::load(&mut data, options.clone()).unwrap();

    let physical_file_schema = Arc::clone(reader_metadata.schema());

    // Commenting this out will make the code work
    options = options
        .with_schema(Arc::clone(&physical_file_schema));

    ArrowReaderMetadata::try_new(Arc::clone(reader_metadata.metadata()), options)
            .unwrap();
}
```

**Expected behavior**
Should not fail

**Additional context**
this might be a bug in DataFusion rather than parquet reader here due to backward compatibility the schema was updated to the new version:
- https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#backward-compatibility-rules 

I've added the file in:
- https://github.com/apache/parquet-testing/pull/96

### PR DESCRIPTION
**Pull request by rluvaton**
# Which issue does this PR close?

- Closes #8495.

# Rationale for this change

Fix reading old parquet files

# What changes are included in this PR?

tests and the fix, but mostly tests.

# Are these changes tested?

yes

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/arrow/schema/complex.rs [hunk 1]
```diff
@@ -620,7 +725,690 @@ pub fn convert_type(parquet_type: &TypePtr) -> Result<ParquetField> {
...
+                        false,
+                    ))),
+                    true,
+                ),
+            ]),
+        )
+    }
+
+    #[test]
+    #[ignore = "not working yet"]
```
Comment (rluvaton) [inline parquet/src/arrow/schema/complex.rs:849]: Ignored as this is failing here and in main

File: parquet/src/arrow/schema/complex.rs [hunk 2]
```diff
@@ -620,7 +725,690 @@ pub fn convert_type(parquet_type: &TypePtr) -> Result<ParquetField> {
...
+                        required binary str (STRING);
+                    };
+                }
+            }
+        ",
+        )
+    }
+
+    #[test]
+    #[ignore = "not working yet"]
```
Comment (rluvaton) [inline parquet/src/arrow/schema/complex.rs:909]: Ignored as this is failing here and in main

File: parquet/src/arrow/schema/complex.rs [hunk 3]
```diff
@@ -620,7 +725,690 @@ pub fn convert_type(parquet_type: &TypePtr) -> Result<ParquetField> {
...
+            }
+        ",
+            Fields::from(vec![
+                // Rule 2: List<Tuple<String, Integer>> (nullable list, non-null elements)
+                Field::new(
+                    "my_list",
+                    DataType::List(Arc::new(Field::new(
+                        "element",
+                        DataType::Struct(Fields::from(vec![
+                            Field::new("str", DataType::Binary, false),
```
Comment (rluvaton) [inline parquet/src/arrow/schema/complex.rs]:
```suggestion
                            Field::new("str", DataType::Utf8, false),
```

File: parquet/src/arrow/schema/complex.rs [hunk 4]
```diff
@@ -72,6 +72,52 @@ impl ParquetField {
         }
     }
 
+    /// Converts `self` into an arrow list, with its current type as the field type
+    /// accept an optional `list_data_type` to specify the type of list to create
+    ///
+    /// This is used to convert deprecated repeated columns (not in a list), into their arrow representation
```
Comment (alamb) [inline parquet/src/arrow/schema/complex.rs]: Is there any reference we can add a link to (I am not familiar with the "deprecated repeated columns" you are referencing here

File: parquet/src/arrow/schema/complex.rs [hunk 5]
```diff
@@ -72,6 +72,52 @@ impl ParquetField {
...
+        self,
+        parquet_field_type: &Type,
+        list_data_type: Option<DataType>,
+    ) -> Result<Self, ParquetError> {
+        let arrow_field = match &list_data_type {
+            Some(DataType::List(field_hint))
+            | Some(DataType::LargeList(field_hint))
+            | Some(DataType::FixedSizeList(field_hint, _)) => Some(field_hint.as_ref()),
+            Some(_) => unreachable!(
+                "should be validated earlier that list_data_type is only a type of list"
```
Comment (alamb) [inline parquet/src/arrow/schema/complex.rs]: even though this should be impossible, I worry about panic'ing here because if there is a bug that error is more severe than "just an error"

ALso, while this may be true at the moment, I can imagine that some future refactor messes it up, in which case this may become reachable and the compiler won't complain

 I would prefer returning a `general_err!` with some sort of "Internal error: should be validated..." type message

File: parquet/src/arrow/schema/complex.rs (hunk 4 above)
Comment (alamb) [reply parquet/src/arrow/schema/complex.rs]: Maybe it is it https://github.com/apache/parquet-format/blob/9fd57b59e0ce1a82a69237dcf8977d3e72a2965d/LogicalTypes.md?plain=1#L718-L723 ?

**Review by alamb — COMMENTED** [review]
Thank you @rluvaton  -- I took a quick review of this PR and the code looks reasonable to me, but I don't understand the legacy inferring logic / problem so I can't really review this PR fully yet 

Can someone help me out with a link / document that describes what the legacy inferring is? Is it https://github.com/apache/parquet-format/blob/9fd57b59e0ce1a82a69237dcf8977d3e72a2965d/LogicalTypes.md?plain=1#L718-L723

Poking around that file, it looks like @etseidl  may know something about this as he authored several commits, for example
- https://github.com/apache/parquet-format/pull/466

File: parquet/src/arrow/schema/complex.rs (hunk 4 above)
Comment (etseidl) [reply parquet/src/arrow/schema/complex.rs]: I believe it's https://github.com/apache/parquet-format/blob/9fd57b59e0ce1a82a69237dcf8977d3e72a2965d/LogicalTypes.md?plain=1#L640-L643, and specifically https://github.com/apache/parquet-format/blob/9fd57b59e0ce1a82a69237dcf8977d3e72a2965d/LogicalTypes.md?plain=1#L649-L650.

Comment (rluvaton) [reply parquet/src/arrow/schema/complex.rs]: exactly, updated

File: parquet/src/arrow/schema/complex.rs (hunk 5 above)
Comment (rluvaton) [reply parquet/src/arrow/schema/complex.rs]: updated

**Comment by alamb** [comment]
I will try and find time tomorrow to review this

**Comment by rluvaton** [comment]
@alamb Ping :)

**Comment by alamb** [comment]
I see this one, thank you - unfortunately I have many other PRs ahead of it in the review queue. 

As I am not super familiar with this part of the spec it will likely take me longer to review as well - -maybe someone else who is more familiar can help out

File: parquet/src/arrow/schema/complex.rs [hunk 6]
```diff
@@ -219,12 +315,13 @@ impl Visitor {
                 rep_level,
                 def_level,
                 data_type,
+                treat_repeated_as_list_arrow_hint: true,
```
Comment (martin-g) [inline parquet/src/arrow/schema/complex.rs:347]:
```suggestion
                treat_repeated_as_list_arrow_hint: context.treat_repeated_as_list_arrow_hint,
```

File: parquet/src/arrow/schema/complex.rs
Comment (martin-g) [inline parquet/src/arrow/schema/complex.rs:761]: Should the extension type be added here too ? As for `None` below.
I.e. something like:

```suggestion
            let merged = field.with_metadata(hint.metadata().clone());
            try_add_extension_type(merged, parquet_type)
```

Comment (rluvaton) [reply parquet/src/arrow/schema/complex.rs:761]: I think we should but not part of this PR

File: parquet/src/arrow/schema/complex.rs (hunk 6 above)
Comment (rluvaton) [reply parquet/src/arrow/schema/complex.rs:347]: this will actually lead to a bug, added a comment ad wrote a test that fail with your suggestion and pass currently

**Comment by rluvaton** [comment]
> I see this one, thank you - unfortunately I have many other PRs ahead of it in the review queue.
> 
> As I am not super familiar with this part of the spec it will likely take me longer to review as well - -maybe someone else who is more familiar can help out

@alamb so can you please assign the relevant people, so we can merge this 4 months old PR

**Comment by alamb** [comment]
> @alamb so can you please assign the relevant people, so we can merge this 4 months old PR

I can't assign anyone as I have no actual authority over anyone's time --  All I can do is to beg and/or cajole others into helping do so. 

One thing that would help me review this pr (and perhaps others as well) is a more complete description / documentation of what this code does, with examples, as I am not all that familiar with the current schema representation of lists (and not at all familiar with the older one) would to help provide context  (ideally in comments) of what this PR is doing


For example, for me to understand comments like this, I need to go into the referenced URL and then try and match the terminology used there to what is used in this repo and PR. While I can do that  it will take time and time is the thing I seem to have the least of 

```rust
    /// This is used to convert [deprecated repeated columns] (not in a list), into their arrow representation
```

Maybe it could give an example so that the code was more self contained. For example, an example of the current List representation and the old (deprecated) representation?

File: parquet/src/arrow/schema/complex.rs [hunk 7]
```diff
@@ -114,6 +164,13 @@ struct VisitorContext {
     def_level: i16,
     /// An optional [`DataType`] sourced from the embedded arrow schema
     data_type: Option<DataType>,
+
+    /// Whether to treat repeated types as list from arrow types
```
Comment (alamb) [inline parquet/src/arrow/schema/complex.rs:168]: Should this also mention that it is for supporting "deprecated list representations" in parquet?

**Comment by etseidl** [comment]
I'm trying to come up to speed on this, but an early observation is that one test (`backward_compat_list_struct_with_nested_repeated_primitive_respects_arrow_hint`) appears to violate this line in the spec:

> For all fields in the schema, implementations should use either LIST and MAP annotations or unannotated repeated fields, but not both. When using the annotations, no unannotated repeated types are allowed.

From the test in question:
```rust
        // This is a backward-compatible LIST (rule 4) where the struct element contains
        // a repeated primitive. The arrow hint specifies that the inner repeated primitive
        // should be LargeList<Int32>.
        let message_type = "
            message schema {
                optional group my_list (LIST) {
                    repeated group my_list_tuple {
                        required binary str (STRING);
                        repeated int32 values;
                    }
                }
            }
        ";
```

That said, plugging the tests from this PR into `main` without the fix yields 
```
failures:
    arrow::schema::complex::tests::backward_compat_list_struct_with_nested_repeated_primitive_respects_arrow_hint
    arrow::schema::complex::tests::convert_schema_with_nested_repeated_struct_and_primitives
    arrow::schema::complex::tests::convert_schema_with_repeated_primitive_should_use_inferred_schema
    arrow::schema::complex::tests::convert_schema_with_repeated_primitive_should_use_inferred_schema_for_list_as_well
    arrow::schema::complex::tests::convert_schema_with_repeated_struct_and_inferred_schema
    arrow::schema::complex::tests::convert_schema_with_repeated_struct_and_inferred_schema_and_field_id

test result: FAILED. 24 passed; 6 failed; 0 ignored; 0 measured; 918 filtered out; finished in 0.64s
```

Other than the test mentioned above, the other failing tests seem like they should succeed.

File: parquet/src/arrow/schema/complex.rs (hunk 7 above)
Comment (rluvaton) [reply parquet/src/arrow/schema/complex.rs:168]: added

**Comment by rluvaton** [comment]
@etseidl updated, thanks for catching that!

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @rluvaton @etseidl and @martin-g

**Comment by alamb** [comment]
run benchmarks arrow_reader arrow_reader_clickbench

**Comment by rluvaton** [comment]
can we merge this PR?

**Comment by alamb** [comment]
Yes, merged!
