### PR TITLE
Fix record delimiting on row group boundaries (#2025)

### LINKED ISSUE #2025: Array reader for list columns fails to decode if batches fall on row group boundaries
This appears very similar to https://issues.apache.org/jira/browse/ARROW-9790, but specifically for list columns.

```
use arrow::array::{Int32Builder, ListBuilder};
use arrow::datatypes::{DataType, Field, Schema};
use arrow::record_batch::RecordBatch;
use parquet::arrow::{ArrowReader, ArrowWriter, ParquetFileArrowReader};
use parquet::file::properties::WriterProperties;
use parquet::file::reader::SerializedFileReader;
use std::error::Error;
use std::sync::Arc;
use tempfile::NamedTempFile;

fn main() -> Result<(), Box<dyn Error>> {
    let schema = Arc::new(Schema::new(vec![
        Field::new("int", DataType::Int32, false),
        Field::new(
            "list",
            DataType::List(Box::new(Field::new("item", DataType::Int32, true))),
            false,
        ),
    ]));
    let temp_file = NamedTempFile::new()?;

    let mut writer = ArrowWriter::try_new(
        temp_file.reopen()?,
        schema.clone(),
        Some(
            WriterProperties::builder()
                .set_max_row_group_size(8)
                .build(),
        ),
    )?;
    for _ in 0..2 {
        let mut int_builder = Int32Builder::new(10);
        let mut list_builder = ListBuilder::new(Int32Builder::new(10));
        for i in 0..10 {
            int_builder.append_value(i)?;
            list_builder.append(true)?;
        }
        let batch = RecordBatch::try_new(
            schema.clone(),
            vec![
                Arc::new(int_builder.finish()),
                Arc::new(list_builder.finish()),
            ],
        )?;
        writer.write(&batch)?;
    }
    writer.close()?;

    let file_reader = Arc::new(SerializedFileReader::new(temp_file.reopen()?)?);
    let mut file_reader = ParquetFileArrowReader::new(file_reader);
    let mut record_reader = file_reader.get_record_reader(8)?;
    assert_eq!(8, record_reader.next().unwrap()?.num_rows());
    assert_eq!(8, record_reader.next().unwrap()?.num_rows());
    assert_eq!(4, record_reader.next().unwrap()?.num_rows());
    Ok(())
}
```

Fails with `Error: ParquetError("Parquet error: Not all children array length are the same!")`

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2025

# Rationale for this change
 
The previous behaviour was incorrect

# What changes are included in this PR?

Fixes the delimiting logic in RecordReader

# Are there any user-facing changes?

No

### CODE REVIEW

File: parquet/src/arrow/array_reader/list_array.rs [hunk 1]
```diff
@@ -124,7 +124,7 @@ impl<OffsetSize: OffsetSizeTrait> ArrayReader for ListArrayReader<OffsetSize> {
 
         // The output offsets for the computed ListArray
         let mut list_offsets: Vec<OffsetSize> =
-            Vec::with_capacity(next_batch_array.len());
+            Vec::with_capacity(next_batch_array.len() + 1);
```
Comment (tustvold) [inline parquet/src/arrow/array_reader/list_array.rs:127]: Drive by fix

File: parquet/src/arrow/record_reader/mod.rs [hunk 2]
```diff
@@ -193,10 +180,7 @@ where
             };
 
             // Try to more value from parquet pages
-            let values_read = self.read_one_batch(batch_size)?;
-            if values_read < batch_size {
```
Comment (tustvold) [inline parquet/src/arrow/record_reader/mod.rs:197]: This is the cause of the bug, the end of the column chunk was being detected based on if read_on_batch returned less than the batch size. If the batch_size happens to exactly match the remaining values this would fail, and the reader would miss the last record in the chunk

File: .github/actions/setup-builder/action.yaml [hunk 3]
```diff
@@ -48,8 +48,8 @@ runs:
         # these represent compiled steps of both dependencies and arrow
         # and thus are specific for a particular OS, arch and rust version.
         path: /github/home/target
-        key: ${{ runner.os }}-${{ runner.arch }}-target-cache3-${{ inputs.rust-version }}-${{ hashFiles('**/Cargo.lock') }}
-        restore-keys: ${{ runner.os }}-${{ runner.arch }}-target-cache3-${{ inputs.rust-version }}-
+        key: ${{ runner.os }}-${{ runner.arch }}-target-cache-${{ inputs.rust-version }}-${{ hashFiles('**/Cargo.lock') }}
+        restore-keys: ${{ runner.os }}-${{ runner.arch }}-target-cache-${{ inputs.rust-version }}-
```
[the remark this answers is not in the document]
Comment (tustvold) [reply .github/actions/setup-builder/action.yaml:52]: I tried that, I've tried removing it, I've tried deleting it, I've tried commenting out all the caching from the CI. It is determined to use some stale file somewhere and I have absolutely no idea why.

**Comment by tustvold** [comment]
Turns out it was a combination of PEBCAC and a logical conflict when CI merged the lastest master in.

File: parquet/src/arrow/record_reader/mod.rs [hunk 4]
```diff
@@ -731,4 +739,48 @@ mod tests {
             assert_eq!(5000, record_reader.num_values());
         }
     }
+
+    #[test]
+    fn test_row_group_boundary() {
```
Comment (alamb) [inline parquet/src/arrow/record_reader/mod.rs:744]: This test passes on master, without the changes in this PR 🤔

File: parquet/src/arrow/arrow_reader.rs [hunk 5]
```diff
@@ -1528,4 +1528,57 @@ mod tests {
 
         assert_eq!(total_rows, expected_rows);
     }
+
+    #[test]
+    fn test_row_group_exact_multiple() {
```
Comment (alamb) [inline parquet/src/arrow/arrow_reader.rs:1533]: When I remove the code in this PR this test fails like the following (I was expecting the reader to miss the last record)

```

---- arrow::arrow_reader::tests::test_row_group_exact_multiple stdout ----
thread 'arrow::arrow_reader::tests::test_row_group_exact_multiple' panicked at 'called `Result::unwrap()` on an `Err` value: ParquetError("Parquet error: Not all children array length are the same!")', parquet/src/arrow/arrow_reader.rs:1581:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1078:23
   4: parquet::arrow::arrow_reader::tests::test_row_group_exact_multiple
             at ./src/arrow/arrow_reader.rs:1581:23
   5: parquet::arrow::arrow_reader::tests::test_row_group_exact_multiple::{{closure}}
             at ./src/arrow/arrow_reader.rs:1533:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

File: parquet/src/arrow/record_reader/mod.rs (hunk 4 above)
Comment (tustvold) [reply parquet/src/arrow/record_reader/mod.rs:744]: This is somewhat expected, I'll see if I can make it fail

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
@tustvold  lint failed !

**Comment by tustvold** [comment]
So the batch_size bug was a bug, but would be masked by the MIN_BATCH_SIZE setting of 1024. The actual cause of the failure was more subtle. The bug was that once exhausted RecordReader would continue to re-read the last record on subsequent calls to read_records. This would only occur if it returned exactly the batch_size number of records, when reaching the end of a chunk. This wouldn't actually read any new data and so would end up actually returning less records than it claimed to have read.

So `read_records` would do the following

* Read 8 records
* Return the corresponding values to the caller
* Read 1 phantom record
* Read 7 records
* Return this to the caller claiming it to be 8 records, but actually only being 7
