### PR TITLE
fix a bug in variable sized equality

### LINKED ISSUE #1208: Empty string arrays with no nulls are not equal
**Describe the bug**
Two string arrays containing only empty strings, where one has a validity map and the other doesn't (but no logical null values in either buffer) do not compare as equal.

**To Reproduce**
```rust
let s = StringArray::from(vec![Some(""), Some(""), Some("")]);

let string1 = s.data();

let string2 = ArrayData::builder(DataType::Utf8)
    .len(string1.len())
    .buffers(string1.buffers().to_vec())
    .build()
    .unwrap();

// string2 is identical to string1 except that it has no validity buffer
// but since there are no nulls, string1 and string2 are equal
assert_eq!(string1, string2);
```

This behavior happens in both IPC reader and parquet reader. If there are no nulls in the source buffer, the validity bitmap is skipped.
Consequently, a round-trip of empty strings fails equality like above.

**Expected behavior**
These arrays should be considered equivalent.

**Additional context**
Binary arrays and the large variants of strings and binary arrays exhibit the same behavior.

### PR DESCRIPTION
**Pull request by helgikrs**
# Which issue does this PR close?

Closes #1208.

# What changes are included in this PR?

A missing validity buffer was being treated as all values being null,
rather than all values being valid, causing equality to fail on some
equivalent string and binary arrays. This PR fixes the bug and adds tests.

# Are there any user-facing changes?

No.

### CODE REVIEW

File: arrow/src/array/equal/mod.rs [hunk 1]
```diff
@@ -1297,4 +1297,38 @@ mod tests {
...
+
+        let string1 = s.data();
+
+        let string2 = ArrayData::builder(DataType::Utf8)
+            .len(string1.len())
+            .buffers(string1.buffers().to_vec())
+            .build()
+            .unwrap();
+
+        // string2 is identical to string1 except that it has no validity buffer but since there
```
Comment (alamb) [inline arrow/src/array/equal/mod.rs:1313]: 👍

File: arrow/src/array/equal/variable_size.rs [hunk 2]
```diff
@@ -86,13 +86,13 @@ pub(super) fn variable_sized_equal<T: OffsetSizeTrait>(
             let lhs_pos = lhs_start + i;
             let rhs_pos = rhs_start + i;
 
-            // the null bits can still be `None`, so we don't unwrap
+            // the null bits can still be `None`, indicating that the value is valid.
```
Comment (alamb) [inline arrow/src/array/equal/variable_size.rs:89]: this is so tricky. I had to read it several times to convince myself it was correct (even with the great test case above @helgikrs ) 👍  thank you

File: arrow/src/array/equal/mod.rs [hunk 3]
```diff
@@ -1297,4 +1297,38 @@ mod tests {
...
+        // are no nulls, string1 and string2 are equal
+        test_equal(string1, &string2, true);
```
Comment (alamb) [inline arrow/src/array/equal/mod.rs:1315]: I verified that this test fails without the code change in this PR

```

---- array::equal::tests::test_non_null_empty_strings stdout ----
thread 'array::equal::tests::test_non_null_empty_strings' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`: 
ArrayData { data_type: Utf8, len: 3, null_count: 0, offset: 0, buffers: [Buffer { data: Bytes { ptr: 0x7fccacb04080, len: 16, data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, offset: 0 }, Buffer { data: Bytes { ptr: 0x80, len: 0, data: [] }, offset: 0 }], child_data: [], null_bitmap: Some(Bitmap { bits: Buffer { data: Bytes { ptr: 0x7fccacb04100, len: 1, data: [7] }, offset: 0 } }) }
ArrayData { data_type: Utf8, len: 3, null_count: 0, offset: 0, buffers: [Buffer { data: Bytes { ptr: 0x7fccacb04080, len: 16, data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, offset: 0 }, Buffer { data: Bytes { ptr: 0x80, len: 0, data: [] }, offset: 0 }], child_data: [], null_bitmap: None }', arrow/src/array/equal/mod.rs:506:9
```

**Review by alamb — APPROVED** [review]
Thank you @helgikrs
