### PR TITLE
Correct nullable in read_dictionary

### LINKED ISSUE #1892: Dictionary IPC writer appears to write incorrect schema
**Describe the bug**
PR https://github.com/apache/arrow-rs/pull/1890 seems to have exposed a bug where IPC-encoded dictionaries declare a field with an empty name that does not allow null values but then writes null values in that column.

**To Reproduce**
Remove the hacky workaround that was added in https://github.com/apache/arrow-rs/pull/1890

**Expected behavior**
encoded schema should be accurate

**Additional context**
None

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1892.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/ipc/reader.rs [hunk 1]
```diff
@@ -702,7 +702,11 @@ pub fn read_dictionary(
         DataType::Dictionary(_, ref value_type) => {
             // Make a fake schema for the dictionary batch.
             let schema = Schema {
-                fields: vec![Field::new("", value_type.as_ref().clone(), false)],
+                fields: vec![Field::new(
+                    "",
+                    value_type.as_ref().clone(),
+                    first_field.is_nullable(),
```
Comment (tustvold) [inline arrow/src/ipc/reader.rs:708]: Could you expand a bit on what is going on here and why? Whilst dictionary values can contain nulls, this and the null count describe the nullability of the values not the keys.

I'm basically a little confused what this record batch actually is, and why it isn't just an ArrarRef...

Comment (viirya) [reply arrow/src/ipc/reader.rs:708]: This is actually for #1890. As #1890 adds a validation for non-nullable field containing null values at RecordBatch. When we read the dictionary value as record batch by `read_record_batch`. It will fail the validation.  Dictionaries are encoded as a sequence of record batches, each having a single field, in IPC messages.

Comment (viirya) [reply arrow/src/ipc/reader.rs:708]: So we decode it as a record batch, and then get the single array from it.

Comment (tustvold) [reply arrow/src/ipc/reader.rs:708]: Should it not be nullable = true, as we don't actually know if the dictionary values may or may not contain nulls?

Comment (viirya) [reply arrow/src/ipc/reader.rs:708]: Okay, that sounds correct to me.

**Review by tustvold — APPROVED** [review]
