### PR TITLE
arrow-flight: generate dict_ids for dicts nested inside complex types

### LINKED ISSUE #9555: Flight encoding panics with "no dict id for field" with nested dict arrays
**Describe the bug**

Flight encoding panics with "no dict id for field" when sending dictionary-encoded arrays nested inside `RunEndEncoded`, `ListView`, `LargeListView`, `FixedSizeList`, or Dictionary-of-complex types (e.g. `Dict(Int8, Struct { dict: Dict(Int32, Utf8), int: Int32 })`). Only affects DictionaryHandling::Resend mode.

**To Reproduce**

Roundtrip these types.

**Expected behavior**

No panic

**Additional context**

### PR DESCRIPTION
**Pull request by asubiotto**
Some cases were missing.

# Which issue does this PR close?

- Closes #9555 .

# Rationale for this change

Fix flight encoding panic

# What changes are included in this PR?

Assigning dict ids properly to nested dicts

# Are these changes tested?

Yes. The same tests fail on main.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by asubiotto** [comment]
cc @brancz

**Comment by brancz** [comment]
cc @alamb

File: arrow-flight/src/encode.rs [hunk 1]
```diff
@@ -547,6 +562,44 @@ fn prepare_field_for_flight(
                 .with_metadata(field.metadata().clone())
             }
         }
+        DataType::ListView(inner) | DataType::LargeListView(inner) => {
```
Comment (alamb) [inline arrow-flight/src/encode.rs:565]: 👍  this makes sense to add handling for these nested types.

Comment (alamb) [reply arrow-flight/src/encode.rs:565]: It would probably be good to change the catch all at the bottom of the match statement to explicitly list out all remaining DataTypes as a way to audit that we didn't miss any additional nested types (either now or in the future)

```rust
        .with_metadata(field.metadata().clone()),
        _ => field.as_ref().clone(),
    }
```

File: arrow-flight/src/encode.rs [hunk 2]
```diff
@@ -1540,6 +1568,149 @@ mod tests {
...
+
+        builder.append_value(vec![Some("a"), None, Some("b")]);
+        let arr1 = builder.finish();
+
+        builder.append_value(vec![Some("c"), None, Some("d")]);
+        let arr2 = builder.finish();
+
+        let schema = Arc::new(Schema::new(vec![Field::new(
+            "dict_list_view",
+            DataType::ListView(Arc::new(Field::new_dictionary(
```
Comment (alamb) [inline arrow-flight/src/encode.rs]: it may make sense to add a test for LargeListView as well

**Review by alamb — APPROVED** [review]
Thank you -- makes sense to me @asubiotto and @brancz 

I left some non blocking comments. If you would like to address them let me know otherwise I'll plan to merge this PR tomorrow

**Comment by asubiotto** [comment]
Thanks for the review @alamb, I'm happy to address the comments.

File: arrow-flight/src/encode.rs (hunk 2 above)
Comment (asubiotto) [reply arrow-flight/src/encode.rs]: Done.

File: arrow-flight/src/encode.rs (hunk 1 above)
Comment (asubiotto) [reply arrow-flight/src/encode.rs:565]: Done.

**Comment by asubiotto** [comment]
Addressed the comments and rebased.

File: arrow-flight/src/encode.rs [hunk 3]
```diff
@@ -556,7 +609,37 @@ fn prepare_field_for_flight(
             field.is_nullable(),
         )
         .with_metadata(field.metadata().clone()),
-        _ => field.as_ref().clone(),
+        DataType::Null
```
Comment (alamb) [inline arrow-flight/src/encode.rs:612]: this is good -- it gives confidence we aren't missing another nested type 👍 

Thank you

**Review by alamb — APPROVED** [review]
Thanks @asubiotto and @brancz
