### PR TITLE
Refine the `bit_util` of Parquet.

### LINKED ISSUE #1901: `log2(0)` panicked at `'attempt to subtract with overflow', parquet/src/util/bit_util.rs:148:5`
**Describe the bug**
https://github.com/apache/arrow-rs/blob/master/parquet/src/util/bit_util.rs#L142-L155

**To Reproduce**
assert_eq!(log2(0), 0);

**Expected behavior**
Alter 1. remove it and replaced by `num_required_bits`
Alter 2: return `Some(n)` when `input > 0` and `None` when `input == 0`;
Alter 3: use the std function `core::num::log2` which has not been stable yet. https://doc.rust-lang.org/std/primitive.u64.html#method.log2
Alter 4: panic when `input == 0` (follow the behavior of `num::core::log2`)
Alter 5: return `0` when `input == 0` (follow the behavior of `num::core::log2`)

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
# Which issue does this PR close?

Closes #1901 .

# What changes are included in this PR?
1. Remove the function `log2`, because:
- The ceiling of `log2 (n)` == `num_required_bits(n - 1)`
- `log2` is unsafe, which panics when the input number is zero.
2. Change the return type of `num_required_bits` to u8
3. Use the std function `div_ceil`
4. optimize `trailing_bits`

# Are there any user-facing changes?
Yes.

### CODE REVIEW

**Review by jhorstmann — APPROVED** [review]
This looks good to me, nice improvement!

File: parquet/src/util/bit_util.rs [hunk 1]
```diff
@@ -133,38 +133,23 @@ where
...
 /// Returns the `num_bits` least-significant bits of `v`
 #[inline]
 pub fn trailing_bits(v: u64, num_bits: usize) -> u64 {
-    if num_bits == 0 {
-        return 0;
-    }
     if num_bits >= 64 {
-        return v;
+        v
+    } else {
```
Comment (tustvold) [inline parquet/src/util/bit_util.rs:150]: I'm not sure if this if block is actually necessary

File: parquet/src/encodings/encoding.rs [hunk 2]
```diff
@@ -307,12 +307,10 @@ impl<T: DataType> DictEncoder<T> {
...
         let num_entries = self.uniques.len();
-        if num_entries == 0 {
-            0
-        } else if num_entries == 1 {
-            1
+        if num_entries <= 1 {
+            num_entries as u8
         } else {
-            log2(num_entries as u64) as u8
+            num_required_bits(num_entries as u64 - 1)
```
Comment (tustvold) [inline parquet/src/encodings/encoding.rs:313]: Is this actually correct? Or was this a pre-existing bug. Why is the bit width here 1 less?

**Review by tustvold — APPROVED** [review]

File: parquet/src/util/bit_util.rs (hunk 1 above)
Comment (HaoYang670) [reply parquet/src/util/bit_util.rs:150]: `1<<num_bits` would overflow if num_bits >= 64

Comment (tustvold) [reply parquet/src/util/bit_util.rs:150]: Aah yes, forgot you can't just overflow. I presume LLVM is smart enough to turn the if into a mask, i.e.

```
v << (num_bits & 64)
```

File: parquet/src/encodings/encoding.rs (hunk 2 above)
Comment (HaoYang670) [reply parquet/src/encodings/encoding.rs:313]: This is because the ceiling of `log2(n)` is always equal to `num_required_bits(n-1)`
For example, 
`log2(8)` = 3 = `num_required_bits(7)`


You can see the log2 function:
```rust
pub fn log2(mut x: u64) -> i32 {
    if x == 1 {
        return 0;
    }
    x -= 1;
    let mut result = 0;
    while x > 0 {
        x >>= 1;
        result += 1;
    }
    result
}
```
I just move the `x -= 1;` outside the function.

File: parquet/src/util/bit_util.rs (hunk 1 above)
Comment (HaoYang670) [reply parquet/src/util/bit_util.rs:150]: Simple test:
```rust
    #[test]
    fn test() {
        let i = 1_u64;
        println!("{}", i << 65);
    }
```
Output:
```
error: this arithmetic operation will overflow
    --> arrow/src/array/array_binary.rs:1824:24
     |
1824 |         println!("{}", i << 65);
     |                        ^^^^^^^ attempt to shift left by `65_i32`, which would overflow
     |
     = note: `#[deny(arithmetic_overflow)]` on by default
```

It  seems like LLVM is not so smart.

Comment (HaoYang670) [reply parquet/src/util/bit_util.rs:150]: Simple test:
```rust
    #[test]
    fn test() {
        fn do_test(shift: i32) {
            let i = 1_u64;
            println!("{}", i << shift);
        }
        do_test(65);
    }
```
Output:
```
panicked at 'attempt to shift left with overflow'
```
