### PR TITLE
Panic instead of discarding nulls converting StructArray to RecordBatch -  (#3951)

### LINKED ISSUE #3952: RecordBatch From StructArray Silently Discards Nulls
**Describe the bug**

**To Reproduce**

```
#[test]
fn test_from_struct() {
    let s = StructArray::from(ArrayData::new_null(
        &DataType::Struct(vec![Field::new("foo", DataType::Int32, false)]),
        2,
    ));

    let batch = RecordBatch::from(&s);
    assert_eq!(batch.column(0).null_count(), 2);
}
```

**Expected behavior**

The above should fail

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3952

# Rationale for this change
 

Discarding the null buffer could potentially unmask nulls in non-nullable children, which would be ill-formed.

# What changes are included in this PR?

# Are there any user-facing changes?

Technically this may change the behaviour of code that was relying on the null buffers silently being discarded, in practice this code was ill-formed.

### CODE REVIEW

File: arrow-array/src/array/struct_array.rs [hunk 1]
```diff
@@ -89,6 +89,14 @@ impl StructArray {
         }
     }
 
+    /// Returns the [`Field`] of this [`StructArray`]
+    pub fn fields(&self) -> &[Field] {
```
Comment (alamb) [inline arrow-array/src/array/struct_array.rs:93]: I wonder if this needs to be updated to avoid a logical conflict with `FieldList`

File: arrow-array/src/record_batch.rs [hunk 2]
```diff
@@ -447,23 +447,28 @@ impl Default for RecordBatchOptions {
         Self::new()
     }
 }
+impl From<StructArray> for RecordBatch {
+    fn from(value: StructArray) -> Self {
+        assert_eq!(
+            value.null_count(),
+            0,
+            "Cannot convert nullable StructArray to RecordBatch"
```
Comment (alamb) [inline arrow-array/src/record_batch.rs:455]: I don't understand why this is an error

Wouldn't it make more sense to apply  the parent `StructArray` validity mask to each child's mask to form a new mask that is only non null if both the struct array and the child array were non null 🤔

Comment (alamb) [reply arrow-array/src/record_batch.rs:454]: 🤔  then it seems like we would have to update the schema to not simply be the schema of the Struct array itself

- I am not saying we have to implement this logic, but a hard panic seems like it may be overly drastic

Comment (tustvold) [reply arrow-array/src/record_batch.rs:454]: > to not simply be the schema of the Struct array itself

Not all child types are nullable, as a result of their encoding. This would not just be a schema-only operation. Taking a step back though, silently changing the schema based on the presence of nulls seems like a very unexpected behaviour? DataFusion would get very confused if one of its RecordBatch suddenly had a different schema?

TBC this conversion from RecordBatch to StructArray should only be being attempted at a top-level where you can statically guarantee there won't be any nulls present - e.g. the top-level of a parquet schema, panicking if you violate that invariant seems perfectly reasonable to me...

Comment (alamb) [reply arrow-array/src/record_batch.rs:454]: > panicking if you violate that invariant seems perfectly reasonable to me...

Is this invariant documented anywhere? I am just thinking of some case where the code "used to work" ( I realize not correctly) and now it still compiles but panic's at runtime.

Maybe we can just document the invariant better -- and I suppose as long as there is a workaround it should be fine

Comment (tustvold) [reply arrow-array/src/record_batch.rs:454]: > Is this invariant documented anywhere

Well yes, a RecordBatch can't contain nulls? I think I'm missing something as to why this is a controversial change?

Comment (tustvold) [reply arrow-array/src/record_batch.rs]: Following our discussion I've added some more docs in https://github.com/apache/arrow-rs/pull/3953/commits/a165ddc3d37ad274402164978aa09b0069330b0d PTAL

File: arrow-array/src/array/struct_array.rs [hunk 3]
```diff
@@ -24,6 +24,28 @@ use std::{any::Any, ops::Index};
...
+/// * [`StructArray`] can be nested within other [`Array`], including itself
+/// * [`RecordBatch`] can contain top-level metadata on its associated [`Schema`][arrow_schema::Schema]
+/// * [`StructArray`] can contain top-level nulls, i.e. `null`
+/// * [`RecordBatch`] can only represent nulls in its child columns, i.e. `{"field": null}`
+///
+/// [`StructArray`] is therefore a more general data container than [`RecordBatch`], and as such
+/// code that needs to handle both will typically share an implementation in terms of
+/// [`StructArray`] and convert to/from [`RecordBatch`] as necessary.
+///
+/// [`From`] implementations are provided to facilitate this conversion, however, converting
```
Comment (alamb) [inline arrow-array/src/array/struct_array.rs:45]: 👍 thank you -- this is much clearer now

**Review by alamb — APPROVED** [review]
