### PR TITLE
Fix empty Schema::metadata deserialization error

### LINKED ISSUE #241: schema: missing field `metadata` when deserialize
**Describe the bug**
In flight server/client mode, if the server schema is:
```
let schema = Schema::new(vec![
                Field::new("name", DataType::Utf8, false),
                Field::new("address", DataType::Utf8, false),
                Field::new("priority", DataType::UInt8, false),
            ])
```

The client will get an error:
`
status: Internal, message: "missing field `metadata` at line 1 column 431", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 30 Apr 2021 08:43:12 GMT"} }
`

If we change the server schema(placehold an empty metadta) to:
```
let metadata: HashMap<String, String> = [("Key".to_string(), "Value".to_string())].iter().cloned().collect();
let schema = Schema::new_with_metadata(vec![
                Field::new("name", DataType::Utf8, false),
                Field::new("address", DataType::Utf8, false),
                Field::new("priority", DataType::UInt8, false),
            ], metadata)
```
All is ok.

I have removed this line from my local crate, it works too:
https://github.com/apache/arrow-rs/blob/d008f31b107c1030a1f5144c164e8ca8bf543576/arrow/src/datatypes/schema.rs#L37

### PR DESCRIPTION
**Pull request by hulunbier**
Hope this fixes issue #241

# Which issue does this PR close?
Closes #241 

# Rationale for this change

De-serializing schema with empty metadata gives us a "missing field metadata..." error,  as stated in #241. returns an empty HashMap may be a better choice. 

# What changes are included in this PR?

Annotates field `Schema::metadata` with `#[serde(default)]`, which will give us a empty HashMap if metadata is empty.

# Are there any user-facing changes?

none.

### CODE REVIEW

File: arrow/src/datatypes/schema.rs [hunk 1]
```diff
@@ -335,3 +336,35 @@ struct MetadataKeyValue {
...
 }
+
+#[cfg(test)]
+mod tests {
+    use crate::datatypes::DataType;
+
+    use super::*;
+
+    #[test]
+    fn test_ser_de_metadata() {
```
Comment (alamb) [inline arrow/src/datatypes/schema.rs:347]: In case anyone else is wondering, this test fails with the following error on master:

```

---- datatypes::schema::tests::test_ser_de_metadata stdout ----
thread 'datatypes::schema::tests::test_ser_de_metadata' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `metadata`", line: 1, column: 284)', arrow/src/datatypes/schema.rs:355:53
```

**Review by alamb — APPROVED** [review]
Thank you @hulunbier  -- looks good to me. @nevi-me  any concerns about this

**Review by nevi-me — APPROVED** [review]
No concerns @alamb, looks good. Thanks @hulunbier
