### PR TITLE
Handle precision overflow when casting from integer to decimal

### LINKED ISSUE #3995: Handle overflow precision when casting from integer to decimal
**Describe the bug**

Although `cast` kernel uses `CastOptions` when casting from integer to decimal, its behavior on overflow-checking is incomplete.

For now, it'd check division or multiplication if overflowing on underlying decimal native types (i.e., i128 and i256). But it doesn't check if input integer is overflowing on decimal precision. This causes weird behavior when downstream project (e.g., DataFusion) uses `cast` kernel to cast integer to decimal.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #3995.

# Rationale for this change
 

Although `cast` kernel checks if division or multiplication overflows in such cast operation, it doesn't check precision overflow. This is somehow related to decimal operation convention in arrow-rs, that is let user handle invalid values in decimal arrays. But for `cast` kernel, because it provides `CastOptions` which defines null behavior for invalid case, the behavior of not checking precision overflow becomes a bit inconsistent.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-cast/src/cast.rs [hunk 1]
```diff
@@ -8132,4 +8145,24 @@ mod tests {
...
+        );
+        assert!(casted_array.is_ok());
+        assert!(casted_array.unwrap().is_null(0));
+
+        let casted_array = cast_with_options(
+            &array,
+            &DataType::Decimal128(7, 3),
+            &CastOptions { safe: false },
+        );
+        assert!(casted_array.is_err());
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:8166]: Perhaps could check the error

**Review by tustvold — APPROVED** [review]

File: arrow-cast/src/cast.rs [hunk 2]
```diff
@@ -358,13 +358,29 @@ where
 
     let array = if scale < 0 {
         match cast_options.safe {
-            true => array.unary_opt::<_, D>(|v| v.as_().div_checked(scale_factor).ok()),
-            false => array.try_unary::<_, D, _>(|v| v.as_().div_checked(scale_factor))?,
+            true => array.unary_opt::<_, D>(|v| {
```
Comment (comphead) [inline arrow-cast/src/cast.rs:361]: thanks for taking this
