### PR TITLE
Enforce struct nullability in JSON raw reader (#3900) (#3904)

### LINKED ISSUE #3900: Nullable field with nested not nullable map in json
**Which part is this question about**

New raw json decoder.

**Describe your question**

While trying to use the new json decoder in delta I stumbled over the following issue:

```rust
#[test]
fn test_delta_checkpoint() {
    let json = "{\"protocol\":{\"minReaderVersion\":1,\"minWriterVersion\":2}}";
    let schema = Arc::new(Schema::new(vec![
        Field::new(
            "protocol",
            DataType::Struct(vec![
                Field::new("minReaderVersion", DataType::Int32, true),
                Field::new("minWriterVersion", DataType::Int32, true),
            ]),
            true,
        ),
        Field::new(
            "add",
            DataType::Struct(vec![Field::new(
                "partitionValues",
                DataType::Map(
                    Box::new(Field::new(
                        "key_value",
                        DataType::Struct(vec![
                            Field::new("key", DataType::Utf8, false),
                            Field::new("value", DataType::Utf8, true),
                        ]),
                        false,
                    )),
                    false,
                ),
                false, // <-- when this is true the test passes
            )]),
            true,
        ),
    ]));

    let batches = do_read(json, 1024, true, schema);
    assert_eq!(batches.len(), 1);
}
```

This fails with:

```
thread 'raw::tests::test_delta_checkpoint' panicked at 'called `Result::unwrap()` on an `Err` value: JsonError("expected { got null")', arrow-json/src/raw/mod.rs:389:18
```

It is related to nested map being not nullable (see comment in the code snippet). I'd expect that if a field (in the example "add") is null, the inner "not nullables" should
not get checked. 

Does this work as expected or could this be a bug?

### LINKED ISSUE #3904: Raw JSON Reader Allows Non-Nullable Struct Children to Contain Nulls
**Describe the bug**

StructArrayDecoder currently is not correctly enforcing that children are only permitted nulls in positions masked by their parents

**To Reproduce**

```
#[test]
fn struct_nullability() {
    let do_test = |child: DataType| {
        // Test correctly enforced nullability
        let non_null = r#"{"foo": {}}"#;
        let schema = Arc::new(Schema::new(vec![Field::new(
            "foo",
            DataType::Struct(vec![Field::new("bar", child, false)]),
            true,
        )]));
        let mut reader = RawReaderBuilder::new(schema.clone())
            .build(Cursor::new(non_null.as_bytes()))
            .unwrap();
        assert!(reader.next().unwrap().is_err()); // Should error as not nullable

        // Test nulls in nullable parent can mask nulls in non-nullable child
        let null = r#"{"foo": null}"#;
        let mut reader = RawReaderBuilder::new(schema)
            .build(Cursor::new(null.as_bytes()))
            .unwrap();
        let batch = reader.next().unwrap().unwrap();
        assert_eq!(batch.num_columns(), 1);
        let foo = as_struct_array(batch.column(0).as_ref());
        assert_eq!(foo.len(), 1);
        assert!(foo.is_null(1));
        assert_eq!(foo.num_columns(), 1);

        let bar = foo.column(0);
        assert_eq!(bar.len(), 1);
        // Non-nullable child can still contain null as masked by parent
        assert!(bar.is_null(0));
    };

    do_test(DataType::Boolean);
    do_test(DataType::Int32);
    do_test(DataType::Utf8);
    do_test(DataType::Decimal128(1, 2));
    do_test(DataType::Timestamp(
        TimeUnit::Microsecond,
        Some("UTC".to_string()),
    ));
}
```

**Expected behavior**

**Additional context**

This is the flip side of https://github.com/apache/arrow-rs/issues/3900

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3900 
Closes #3904

# Rationale for this change
 

See tickets

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-json/src/raw/mod.rs [hunk 1]
```diff
@@ -1004,4 +1004,84 @@ mod tests {
...
+                        false,
+                    ),
+                    false,
+                )]),
+                true,
+            ),
+        ]));
+
+        let batches = do_read(json, 1024, true, schema);
+        assert_eq!(batches.len(), 1);
```
Comment (alamb) [inline arrow-json/src/raw/mod.rs:1042]: I wonder if asserting the contents with `assert_batches_eq` or similar would be helpful here 

Also would it help to verify that the key is not null is enforced. Like that this document errors` { add: { partition_values: [ foo: bar, null: baz ] } } `?

File: arrow-json/src/raw/mod.rs [hunk 2]
```diff
@@ -1004,4 +1004,84 @@ mod tests {
...
+                "foo",
+                DataType::Struct(vec![Field::new("bar", child, false)]),
+                true,
+            )]));
+            let mut reader = RawReaderBuilder::new(schema.clone())
+                .build(Cursor::new(non_null.as_bytes()))
+                .unwrap();
+            assert!(reader.next().unwrap().is_err()); // Should error as not nullable
+
+            // Test nulls in nullable parent can mask nulls in non-nullable child
```
Comment (alamb) [inline arrow-json/src/raw/mod.rs:1060]: Should we also verify that this case errors too?

```
            let null = r#"{"foo": {bar: null}}"#;

**Review by alamb — APPROVED** [review]
I had a few test suggestions, but otherwise looks good to me. Thank you @tustvold
