### PR TITLE
pyarrow: Preserve RecordBatch's schema metadata

### LINKED ISSUE #5354: RecordBatch conversion from pyarrow loses Schema's metadata
**Describe the bug**

When importing a pyarrow RecordBatch, we instantiate a `StructArray`, then convert it to a `RecordBatch`.
This loses the metadata from the original schema. This is not seen in the current tests, because pyarrow's
tests for equality on schemas ignores metadata.

https://github.com/apache/arrow-rs/blob/31cf5ce23febf076104f064358a24fe8af09ee4b/arrow/src/pyarrow.rs#L357-L358

**To Reproduce**

```python
# In arrow-pyarrow-integration-testing/tests/test_sql.py:470
batch = pa.record_batch([f32_array], ["tensor"], metadata={b'key1': b'value1'})
    b = rust.round_trip_record_batch(batch)
    assert b == batch  # OK
    assert b.schema == batch.schema  # OK
    assert b.schema.metadata == batch.schema.metadata  # Fails
```

**Expected behavior**
Imported RecordBatch's schema should keep its metadata.

### PR DESCRIPTION
**Pull request by atwam**
PyArrow's RecordBatch gets imported by using a StructArray, then transforming it into a RecordBatch. This was losing the Schema's metadata in the process (because a StructArray does not hold metadata).

This commit changes the test to show the issue, and fixes it.

# Which issue does this PR close?

Closes #5354.

# What changes are included in this PR?

Changes pyarrow tests to ensure that schema equality also checks for metadata equality.
Fixes `impl FromPyArrow for RecordBatch` to ensure that the resulting RecordBatch has the right schema

# Are there any user-facing changes?

No

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
Thank you. This seems plausible to me, but I'm not very familiar with this interface

File: arrow/src/pyarrow.rs [hunk 1]
```diff
@@ -355,7 +355,12 @@ impl FromPyArrow for RecordBatch {
                 ));
             }
             let array = StructArray::from(array_data);
-            return Ok(array.into());
+            // StructArray does not embed metadata from schema. We need to override
+            // the output schema with the schema from the capsule.
+            let schema = Arc::new(Schema::try_from(schema_ptr).map_err(to_py_err)?);
+            return RecordBatch::from(array)
+                .with_schema(schema)
+                .map_err(to_py_err);
```
Comment (kylebarron) [inline arrow/src/pyarrow.rs:363]: Instead of first inferring a schema from the record batch and then overwriting it, maybe it would be clearer to [access the columns](https://docs.rs/arrow-array/50.0.0/src/arrow_array/record_batch.rs.html#513) and then use `RecordBatch::try_new`?
```rs
let schema = Arc::new(Schema::try_from(schema_ptr).map_err(to_py_err)?);
let (_fields, columns, nulls) = array.into_parts();
// Assert null count is 0
return RecordBatch::try_new(schema, columns).map_err(to_py_err);
```

Comment (atwam) [reply arrow/src/pyarrow.rs]: Excellent point, I should have looked at the conversion code from `StructArray`. Fixed.

**Review by kylebarron — APPROVED** [review]

**Comment by atwam** [comment]
I have more changes pending that actually use `schema.equals(other, check_metadata=True)`, which seems to be a better test, but these fail until https://github.com/apache/arrow/issues/39865 is fixed (see discussion in #5355 )

**Comment by alamb** [comment]
Thanks everyone
