### PR TITLE
Truncate IPC record batch

### LINKED ISSUE #1528: RecordBatch: Serialization of sliced record using StreamWriter produces incorrect resut
When you slice `RecordBatch` and serialize it with `StreamWriter`, it produces an incorrect result. I'm using `arrow = "11.1.0"`

To reproduce once can use the following test:
```rust
#[cfg(test)]
mod tests {
    use std::sync::Arc;
    use arrow::array::{Int32Array, StringArray};
    use arrow::datatypes::{DataType, Field, Schema};
    use arrow::ipc::writer::StreamWriter;
    use arrow::record_batch::RecordBatch;

    #[test]
    fn it_works() {
        pub fn serialize(record: &RecordBatch) -> Vec<u8> {
            let buffer: Vec<u8> = Vec::new();
            let mut stream_writer = StreamWriter::try_new(buffer, &record.schema()).unwrap();
            stream_writer.write(record).unwrap();
            stream_writer.finish().unwrap();
            let serialized_batch = stream_writer.into_inner().unwrap();
            serialized_batch
        }

        fn create_batch(rows: usize) -> RecordBatch {
            let schema = Schema::new(vec![
                Field::new("a", DataType::Int32, false),
                Field::new("b", DataType::Utf8, false),
            ]);
            let expected_schema = schema.clone();

            let a = Int32Array::from(vec![1; rows]);
            let b = StringArray::from(vec!["a"; rows]);

            let record_batch = RecordBatch::try_new(Arc::new(schema), vec![Arc::new(a), Arc::new(b)])
                .unwrap();
            record_batch
        }
        let big_record_batch = create_batch(65536);
        println!("big_record_batch with dimension ({}, {}) (rows x cols) serialized as Apache Arrow IPC in {} bytes", big_record_batch.num_rows(),
                 big_record_batch.num_columns(), serialize(&big_record_batch).len());
        let length = 5;
        let small_record_batch = create_batch(length);
        println!("small_record_batch with dimension ({}, {}) (rows x cols) serialized as Apache Arrow IPC in {} bytes", small_record_batch.num_rows(),
                 small_record_batch.num_columns(), serialize(&small_record_batch).len());

        let offset = 2;
        let record_batch_slice = big_record_batch.slice(offset, length);
        println!("(Sliced): record_batch_slice with dimension ({}, {}) (rows x cols) serialized as Apache Arrow IPC in {} bytes", record_batch_slice.num_rows(),
                 record_batch_slice.num_columns(), serialize(&record_batch_slice).len());
    }
}
```
As you can see the sliced one has almost the same size as `big_record_batch`, but I would expect it to be the same size as `small_record_batch`:
```
big_record_batch with dimension (65536, 2) (rows x cols) serialized as Apache Arrow IPC in 606608 bytes
small_record_batch with dimension (5, 2) (rows x cols) serialized as Apache Arrow IPC in 464 bytes
(Sliced): record_batch_slice with dimension (5, 2) (rows x cols) serialized as Apache Arrow IPC in 590240 bytes
```

This can be related to [Add support for writing sliced arrays](https://github.com/apache/arrow-rs/issues/225) and [flight_data_from_arrow_batch sends too much data](https://github.com/apache/arrow-rs/issues/208)

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1528.
Closes https://github.com/apache/arrow-rs/issues/208

# Rationale for this change
 
 

When serialize RecordBatch through IPC, we should truncate it to only serialize the necessary part if the batch is sliced.

C++ implementation also truncates it:
https://github.com/apache/arrow/blob/master/cpp/src/arrow/ipc/writer.cc#L351
https://github.com/apache/arrow/blob/master/cpp/src/arrow/ipc/writer.cc#L327

# What changes are included in this PR?

Truncate arrays of record batch when serializing it through IPC. Following C++, we truncate arrays of numeric type, temporal types, fixed size binary type and base binary types (binary, string).

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/ipc/writer.rs [hunk 1]
```diff
@@ -861,6 +863,145 @@ fn has_validity_bitmap(data_type: &DataType, write_options: &IpcWriteOptions) ->
...
+    buffer: &Buffer,
+    spec: &BufferSpec,
+    min_length: usize,
+) -> bool {
+    if spec == &BufferSpec::AlwaysNull {
+        false
+    } else {
+        array_offset != 0 || min_length < buffer.len()
+    }
+}
```
Comment (HaoYang670) [inline arrow/src/ipc/writer.rs:879]: nit: (not tested)
```rust
spec != &BufferSpec::AlwaysNull && (array_offset != 0 || min_length < buffer.len())
```

File: arrow/src/ipc/writer.rs [hunk 2]
```diff
@@ -861,6 +863,145 @@ fn has_validity_bitmap(data_type: &DataType, write_options: &IpcWriteOptions) ->
...
+/// Returns the number of total bytes in base binary arrays.
+fn get_total_bytes(array_data: &ArrayData) -> usize {
+    if array_data.is_empty() {
+        return 0;
+    }
+    match array_data.data_type() {
+        DataType::Binary => {
+            let array: BinaryArray = array_data.clone().into();
+            let offsets = array.value_offsets();
+            (offsets[array_data.len()] - offsets[0]) as usize
```
Comment (HaoYang670) [inline arrow/src/ipc/writer.rs:899]: Is this corrent when `array_data.offset() > 0`?

File: arrow/src/ipc/writer.rs [hunk 3]
```diff
@@ -1507,4 +1702,60 @@ mod tests {
             IpcWriteOptions::try_new(8, false, MetadataVersion::V5).unwrap(),
         );
     }
+
+    #[test]
+    fn truncate_ipc_record_batch() {
+        pub fn serialize(record: &RecordBatch) -> Vec<u8> {
```
Comment (HaoYang670) [inline arrow/src/ipc/writer.rs:1708]: Why do we need this function to be public?

**Review by HaoYang670 — COMMENTED** [review]
I am not very familiar with IPC, so just give some small nits I find.

File: arrow/src/ipc/writer.rs (hunk 3 above)
Comment (viirya) [reply arrow/src/ipc/writer.rs:1708]: No need to be. I copied from the test provided in the issue. Let me remove it.

File: arrow/src/ipc/writer.rs (hunk 2 above)
Comment (viirya) [reply arrow/src/ipc/writer.rs:899]: Yes. `value_offsets` has considered `array_data`'s `offset`.

File: arrow/src/ipc/writer.rs [hunk 4]
```diff
@@ -894,12 +1031,66 @@ fn write_array_data(
...
+                &value_buffer.as_slice()[byte_offset..(byte_offset + buffer_length)];
+            offset = write_buffer(buffer_slice, buffers, arrow_data, offset);
+        } else {
+            array_data.buffers().iter().for_each(|buffer| {
+                offset = write_buffer(buffer.as_slice(), buffers, arrow_data, offset);
+            });
+        }
+    } else if DataType::is_numeric(data_type)
+        || DataType::is_temporal(data_type)
+        || matches!(array_data.data_type(), DataType::FixedSizeBinary(_))
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:1066]: I think this could also support DictionaryArray without modification?

File: arrow/src/ipc/writer.rs [hunk 5]
```diff
@@ -894,12 +1031,66 @@ fn write_array_data(
...
+    {
+        // Truncate values
+        let layout = layout(data_type);
+
+        array_data
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:1071]: This code could theoretically be simpler if it made the valid assertion that all these arrays only have a single buffer

File: arrow/src/ipc/writer.rs [hunk 6]
```diff
@@ -861,6 +863,141 @@ fn has_validity_bitmap(data_type: &DataType, write_options: &IpcWriteOptions) ->
...
+    buffer: &Buffer,
+    spec: &BufferSpec,
+    min_length: usize,
+) -> bool {
+    spec != &BufferSpec::AlwaysNull && (array_offset != 0 || min_length < buffer.len())
+}
+
+/// Returns byte width for a buffer spec. Only for `BufferSpec::FixedWidth`.
+#[inline]
+fn get_buffer_byte_width(spec: &BufferSpec) -> usize {
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:879]:
```suggestion
fn get_buffer_element_width(spec: &BufferSpec) -> usize {
```

File: arrow/src/ipc/writer.rs [hunk 7]
```diff
@@ -861,6 +863,141 @@ fn has_validity_bitmap(data_type: &DataType, write_options: &IpcWriteOptions) ->
...
+    match spec {
+        BufferSpec::FixedWidth { byte_width } => *byte_width,
+        _ => 0,
+    }
+}
+
+/// Returns the number of total bytes in base binary arrays.
+fn get_total_bytes(array_data: &ArrayData) -> usize {
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:887]:
```suggestion
fn get_binary_buffer_len(array_data: &ArrayData) -> usize {
```
Or something to make a bit clear what it is the total of?

File: arrow/src/ipc/writer.rs [hunk 8]
```diff
@@ -861,6 +863,141 @@ fn has_validity_bitmap(data_type: &DataType, write_options: &IpcWriteOptions) ->
...
+
+/// Rebase value offsets for given ArrayData to zero-based.
+fn get_zero_based_value_offsets(array_data: &ArrayData) -> Buffer {
+    match array_data.data_type() {
+        DataType::Binary => {
+            let array: BinaryArray = array_data.clone().into();
+            let offsets = array.value_offsets();
+            let start_offset = offsets[0];
+
+            let mut new_offsets = vec![0_i32; array_data.len() + 1];
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:924]: I don't think we need to zero-initialize here

File: arrow/src/ipc/writer.rs [hunk 9]
```diff
@@ -894,12 +1031,66 @@ fn write_array_data(
...
+        let value_buffer = &array_data.buffers()[1];
+        if buffer_need_truncate(
+            array_data.offset(),
+            value_buffer,
+            &BufferSpec::VariableWidth,
+            total_bytes,
+        ) {
+            // Rebase offsets and truncate values
+            let new_offsets = get_zero_based_value_offsets(array_data);
+            offset = write_buffer(new_offsets.as_slice(), buffers, arrow_data, offset);
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:1052]: Definitely something that could be left to another PR, but I do wonder if there might be some way to write the new offsets directly without buffering them first. I'm not very familiar with the IPC code so not sure how feasible this may be

**Review by tustvold — COMMENTED** [review]
Looking good, I think there is an issue with the way bitmaps are currently handled but I think this should just be a case of using `Buffer::bit_slice` or similar

**Comment by alamb** [comment]
❤️  -- thank you @viirya 

Note we have some code in IOx to workaround the lack of this feature (described in https://github.com/influxdata/influxdb_iox/issues/1133): 
 https://github.com/influxdata/influxdb_iox/blob/3592aa52d815e861ac14031186ba557c9290dfaf/arrow_util/src/optimize.rs#L97-L141

I wonder if this PR also closes https://github.com/apache/arrow-rs/issues/208?

**Comment by viirya** [comment]
Yes, flight data also uses IPC to encode record batch. This also closes #208 too.

File: arrow/src/ipc/writer.rs [hunk 10]
```diff
@@ -894,12 +1031,66 @@ fn write_array_data(
             Some(buffer) => buffer.clone(),
         };
 
-        offset = write_buffer(&null_buffer, buffers, arrow_data, offset);
+        offset = write_buffer(null_buffer.as_slice(), buffers, arrow_data, offset);
```
[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/ipc/writer.rs:1034]: Yea, although it is truncated at the offset, but the length is not considered. As null buffer is bit encoded, and different to other buffers here, it cannot be simply truncated by the length. Not aware of there is `bit_slice` that can be used.

[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/ipc/writer.rs:1034]: This seems not to be an (serious) issue? Null buffer is relatively small. One issue is the length of null buffer after IPC is not matched. But I don't see that we really care about it in current code?

File: arrow/src/ipc/writer.rs (hunk 4 above)
Comment (viirya) [reply arrow/src/ipc/writer.rs:1066]: Hmm, yea, seems so. Rechecked C++ implementation, it truncates DictionaryArray keys: https://github.com/apache/arrow/blob/master/cpp/src/arrow/ipc/writer.cc#L524-L527

File: arrow/src/ipc/writer.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/ipc/writer.rs:1034]: `null_buffer.as_slice()` already takes the slice from the offset from null buffer. I think it is you meant materializing the buffers (null buffer and value buffers)? The difference now is this also truncate the length from value buffers but not for null buffer (we can do it by using `bit_slice` then).

**Comment by alamb** [comment]
> Yes, flight data also uses IPC to encode record batch. This also closes https://github.com/apache/arrow-rs/issues/208 too.

Updated the PR description to match

File: arrow/src/ipc/writer.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (tustvold) [reply arrow/src/ipc/writer.rs:1034]: There are two offsets, the offset within the null buffer which `as_slice` applies, and the offset from the ArrayData which `as_slice` cannot possibly apply as it has no idea what it is (and it is an offset in bits and not bytes).

I would like to see a test of a nullable sliced array, it is possible I'm mistaken, but I am pretty certain this will break

[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/ipc/writer.rs:1034]: Yea, figured it out now. You're right. Array data's offset is not considered for null buffer yet. I'm fixing it and adding related test.

File: arrow/src/ipc/writer.rs [hunk 11]
```diff
@@ -861,6 +863,141 @@ fn has_validity_bitmap(data_type: &DataType, write_options: &IpcWriteOptions) ->
...
+            let array: BinaryArray = array_data.clone().into();
+            let offsets = array.value_offsets();
+            let start_offset = offsets[0];
+
+            let mut new_offsets = vec![0_i32; array_data.len() + 1];
+            for (idx, x) in offsets.iter().enumerate() {
+                new_offsets[idx] = x - start_offset;
+            }
+
+            Buffer::from_slice_ref(&new_offsets)
```
[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/ipc/writer.rs:929]: Doesn't `BufferBuilder.append_slice` also copy slice?

[the remark this answers is not in the document]
Comment (tustvold) [reply arrow/src/ipc/writer.rs:929]: Yes, but this is copying twice - once into the Vec and once here. If you used BufferBuilder instead of Vec you would eliminate one of these copies

[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/ipc/writer.rs]: Ah, I see.

File: arrow/src/ipc/writer.rs [hunk 12]
```diff
@@ -894,12 +1031,66 @@ fn write_array_data(
...
         };
 
-        offset = write_buffer(&null_buffer, buffers, arrow_data, offset);
+        offset = write_buffer(null_buffer.as_slice(), buffers, arrow_data, offset);
     }
 
-    array_data.buffers().iter().for_each(|buffer| {
-        offset = write_buffer(buffer, buffers, arrow_data, offset);
-    });
+    let data_type = array_data.data_type();
```
[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/ipc/writer.rs:1005]: It sounds reasonable.

[the remark this answers is not in the document]
Comment (viirya) [reply arrow/src/ipc/writer.rs:1015]: Added an option.

File: arrow/src/ipc/writer.rs [hunk 13]
```diff
@@ -894,12 +1004,88 @@ fn write_array_data(
             Some(buffer) => buffer.clone(),
         };
 
-        offset = write_buffer(&null_buffer, buffers, arrow_data, offset);
+        let sliced_null_buffer = if write_options.enable_truncate_array {
+            null_buffer.bit_slice(array_data.offset(), array_data.len())
+        } else {
+            null_buffer
+        };
+        offset = write_buffer(sliced_null_buffer.as_slice(), buffers, arrow_data, offset);
```
Comment (JasonLi-cn) [inline arrow/src/ipc/writer.rs:1012]: I think there should be processed like this: 
```rust
    if has_validity_bitmap(array_data.data_type(), write_options) {
        // write null buffer if exists
        let null_buffer = match array_data.null_buffer() {
            None => {
                // create a buffer and fill it with valid bits
                let num_bytes = bit_util::ceil(num_rows, 8);
                let buffer = MutableBuffer::new(num_bytes);
                let buffer = buffer.with_bitset(num_bytes, true);
                buffer.into()
            }
            Some(buffer) => {
                if write_options.enable_truncate_array {
                    buffer.bit_slice(array_data.offset(), array_data.len())
                } else {
                    buffer.clone()
                }
            }
        };

        offset = write_buffer(null_buffer.as_slice(), buffers, arrow_data, offset);
    }
```
Slice of RecordBatch which has no null_buffer may case Panic, for example: record_batch.num_rows() = 100,  let rb_slice = record_batch.slice(64, 36), process rb_slice will case Panic("the offset of the new Buffer cannot exceed the existing length") when call null_buffer.bit_slice(array_data.offset(), array_data.len()).

Comment (viirya) [reply arrow/src/ipc/writer.rs]: Good catch. The null buffer created is for `num_rows` so it is already truncated.

File: arrow/src/ipc/writer.rs [hunk 14]
```diff
@@ -1501,10 +1690,151 @@ mod tests {
...
+    #[test]
+    fn truncate_ipc_record_batch_with_nulls() {
+        fn create_batch() -> RecordBatch {
+            let schema = Schema::new(vec![
+                Field::new("a", DataType::Int32, true),
+                Field::new("b", DataType::Utf8, true),
+            ]);
+
+            let a = Int32Array::from(vec![Some(1), None, Some(1), None, Some(1)]);
+            let b = StringArray::from(vec![None, Some("a"), Some("a"), None, Some("a")]);
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:1784]:
```suggestion
            let a = Int32Array::from_iter_values(0..rows as i32);
            let b = StringArray::from_iter_values((0..rows).map(|i| i.to_string()));
```

File: arrow/src/ipc/writer.rs [hunk 15]
```diff
@@ -1501,10 +1690,151 @@ mod tests {
...
+
+        assert_eq!(
+            deserialize(serialize_with_truncate(&record_batch_slice)),
+            small_record_batch
+        );
+        assert_eq!(
+            deserialize(serialize_with_truncate(&record_batch_slice)),
+            record_batch_slice
         );
+
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:1767]:
```suggestion
        assert_eq!(
            deserialize(serialize_without_truncate(&record_batch_slice)),
            record_batch_slice
        );
```
Or something, basically I think the previous logic was wrong.

File: arrow/src/ipc/writer.rs (hunk 14 above)
Comment (tustvold) [reply arrow/src/ipc/writer.rs:1784]: This PR fails with the above change, which would suggest something isn't working quite right

File: arrow/src/ipc/writer.rs [hunk 16]
```diff
@@ -1501,10 +1690,151 @@ mod tests {
...
+    #[test]
+    fn truncate_ipc_record_batch() {
+        fn create_batch(rows: usize) -> RecordBatch {
+            let schema = Schema::new(vec![
+                Field::new("a", DataType::Int32, false),
+                Field::new("b", DataType::Utf8, false),
+            ]);
+
+            let a = Int32Array::from(vec![1; rows]);
+            let b = StringArray::from(vec!["a"; rows]);
```
Comment (tustvold) [inline arrow/src/ipc/writer.rs:1737]:
```suggestion
            let a = Int32Array::from_iter_values(0..rows as i32);
            let b = StringArray::from_iter_values((0..rows).map(|i| i.to_string()));
```

Comment (tustvold) [reply arrow/src/ipc/writer.rs:1737]: This PR fails with the above change, which would suggest something isn't quite right

**Comment by viirya** [comment]
That's said that we need to truncate it without the option. I don't find C++ implementation has an option for that actually.

**Comment by tustvold** [comment]
Perhaps we should make it non-optional then, I had thought the offset was separately preserved, given it isn't, there doesn't seem to be a reason to have the option

File: arrow/src/ipc/writer.rs (hunk 16 above)
Comment (viirya) [reply arrow/src/ipc/writer.rs:1737]: Oh, originally all elements are same in two arrays(int, string). So `small_record_batch` is equal to deserialized `record_batch_slice`. The change makes array elements different, so `small_record_batch` is different to deserialized `record_batch_slice` (e.g. [2, 3, 4, 5, 6] to [0, 1, 2, 3, 4]).

Comment (viirya) [reply arrow/src/ipc/writer.rs:1737]: Actually the check between `small_record_batch` and deserialized `record_batch_slice` is not necessary. Let me revise the test.

**Comment by viirya** [comment]
Unrelated error on Windows CI:

```
error: error: Invalid value for '<+toolchain>': Toolchain overrides must begin with '+'
```

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
I think there is more to be done in this vein, e.g. ListArray, StructArray, etc... but this is a good step forward. Thank you 🙂

**Comment by alamb** [comment]
> I think there is more to be done in this vein, e.g. ListArray, StructArray, etc... but this is a good step forward. Thank you 🙂


@tustvold  is the remaining work recorded anywhere? I am happy to write up a ticket but I don't understand the issue well enough to do so at this moment
