### PR TITLE
docs(variant): fix VariantObject::get documentation to reflect Option return type

### LINKED ISSUE #9105: [Variant] Documentation for `VariantObject::get` incorrectly references `Result` type
**Describe the bug**
[`VariantObject::get`](https://docs.rs/parquet/latest/parquet/variant/struct.VariantObject.html#method.get) has a doc string that states:
> `Ok(None)` means the field does not exist; `Err` means the search encountered an error.

However, `get` returns an `Option<Variant>` not a `Result<Option<Variant>>`

**Expected behavior**
I expect the doc string to describe possible behaviors

### PR DESCRIPTION
**Pull request by mohit7705**
### Which issue does this PR close?

Closes #9105

### Rationale for this change

The documentation for `VariantObject::get` previously described `Result`-style
semantics (`Ok(None)` / `Err`), but the method actually returns
`Option<Variant>`. This mismatch could confuse users of the API.

### What changes are included in this PR?

- Update the documentation for `VariantObject::get` to correctly describe its
  `Option` return type.
- No functional or behavioral changes are included.

### CODE REVIEW

**Comment by mohit7705** [comment]
hi @alamb 
can you check one more time ?

**Comment by mohit7705** [comment]
hi @alamb 
the checks are passed .
is their anything else to do ?

**Comment by alamb** [comment]
Nope -- thank you @mohit7705  -- I plan to merge this PR in a day or two. I will wait to give others a chance to review if they would like

File: parquet-variant/src/variant/object.rs [hunk 1]
```diff
@@ -390,7 +390,8 @@ impl<'m, 'v> VariantObject<'m, 'v> {
 
     /// Returns the value of the field with the specified name, if any.
     ///
-    /// `Ok(None)` means the field does not exist; `Err` means the search encountered an error.
+    /// Returns `Some(Variant)` if the field exists, or `None` if the field does not exist
+    /// or if the lookup fails safely.
```
Comment (Jefffrey) [inline parquet-variant/src/variant/object.rs]: What does failing unsafe mean? It'll panic?

Comment (mohit7705) [reply parquet-variant/src/variant/object.rs]: Good point — by “fails safely” I mean that `get` does not propagate errors or panic.
Any internal lookup failure (e.g. during binary search or name comparison) is handled by returning `None`. This method never returns `Err` and does not panic; panics are only possible with the infallible indexing APIs on unvalidated data, not with `get`.

Comment (Jefffrey) [reply parquet-variant/src/variant/object.rs]: I would remove the `safely` word as it can confuse readers to assume there is a panic condition here

Comment (alamb) [reply parquet-variant/src/variant/object.rs]: Rust also uses the word `safe` to mean particular things about memory safety / undefined behavior, so I agree removing the safely word would make this less confusing

**Comment by mohit7705** [comment]
hi @alamb    @Jefffrey 
Done — removed “safely” from the doc comment to avoid confusion with Rust’s safe/unsafe terminology. Thanks for the review!

**Comment by alamb** [comment]
Thanks again @mohit7705 and @Jefffrey
