### PR TITLE
Use c_char instead of i8 to compile on platforms where c_char = u8

### LINKED ISSUE #6571: Compilation fail where `c_char = u8`
**Describe the bug**
Arrow integration tests assume that `c_char` = `i8`. While this is true on most platforms, there are many where it is not true (such as arm linux and risc-v linux). This causes a compilation failure in arrow-integration-testing

**To Reproduce**
Compile on a target where `c_char` =  `u8` (e.g. `aarch64-unknown-linux-gnu`)

**Expected behavior**
It should compile fine

**Additional context**
I'll file a PR to fix this.

### PR DESCRIPTION
**Pull request by itsjunetime**
# Which issue does this PR close?

Closes #6571 

# Rationale for this change
 
`c_char` is what is actually required for these APIs, so we should uniformly use it where required.

# What changes are included in this PR?

Switches a bunch of `i8`s to `c_char`s

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by alamb** [comment]
Fascinating -- it appears `1.82` rust is scheduled to release tomorrow https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1820-2024-10-17

Maybe this is some sort of foreshadowing of what is to come

File: arrow-integration-testing/src/lib.rs [hunk 1]
```diff
@@ -165,7 +165,7 @@ pub fn read_gzip_json(version: &str, path: &str) -> ArrowJson {
 
 /// C Data Integration entrypoint to export the schema from a JSON file
 fn cdata_integration_export_schema_from_json(
-    c_json_name: *const i8,
+    c_json_name: *const c_char,
     out: *mut FFI_ArrowSchema,
 ) -> Result<()> {
     let json_name = unsafe { CStr::from_ptr(c_json_name) };
```
Comment (alamb) [inline arrow-integration-testing/src/lib.rs:171]: It is strange to me that the signature in `std::ffi` is `ptr: *const i8`, not `*const c_char` 🤔 

https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_ptr

Screenshot 2024-10-16 at 3 20 24 PM


Maybe it changed in 1.82 🤔

Comment (itsjunetime) [reply arrow-integration-testing/src/lib.rs:171]: So it does seem to say `*const i8` in the signature, but if you click through to the `source`, it shows `ptr: *const c_char`. I don't know what's up with that, it feels like  a docs.rs bug.

Comment (itsjunetime) [reply arrow-integration-testing/src/lib.rs:171]: https://github.com/rust-lang/rust/issues/113735

**Review by alamb — APPROVED** [review]
Thank you @itsjunetime  -- this makes sense to me

the CI failure on this PR is unrelated -- see https://github.com/apache/arrow-rs/issues/6568

**Review by mbrobbel — APPROVED** [review]

**Comment by alamb** [comment]
CI Integration failure is tracked with https://github.com/apache/arrow-rs/issues/6577

This PR basically uses a different typedef, so I don't think it is a breaking change

Thus 🚀

**Comment by alamb** [comment]
Thanks again @itsjunetime and @mbrobbel
