### PR TITLE
Fix disabling parquet statistics (#2185)

### LINKED ISSUE #2185: EnabledStatistics::None not working
**Describe the bug**
Take the code as an example, 
```rust
fn main() {
    let root_schema = Arc::new(Schema::new(vec![Field::new("a", DataType::Int64, false)]));

    let props = WriterProperties::builder()
        .set_statistics_enabled(EnabledStatistics::None)
        .build();

    let file = File::create("test.parquet").unwrap();
    let mut writer = ArrowWriter::try_new(
        file.try_clone().unwrap(),
        Arc::clone(&root_schema),
        Some(props),
    )
    .unwrap();

    let a = Int64Array::from(vec![1, 2, 3, 4, 5]);
    let batch = RecordBatch::try_new(Arc::clone(&root_schema), vec![Arc::new(a)]).unwrap();

    writer.write(&batch);
    writer.close();
}
```

When the default `statistics_enabled` is set to `EnabledStatistics::None`, if I read the metadata of `test.parquet` with code,

```rust
let f = File::open("test.parquet").unwrap();
let r = ParquetFileArrowReader::try_new(f).unwrap();
let m = r.metadata();
println!("{:#?}", m);
```

 I get:

```
...
statistics: Some(
  Int64(
    {min: Some(1), max: Some(5), distinct_count: None, null_count: 0, min_max_deprecated: false},
  ),
 ),
...
```

**Expected behavior**
```
...
statistics: None
...
```

**Additional context**
Tested against arrow 19.0.0.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2185

# Rationale for this change
 
 

# What changes are included in this PR?

Fixes the handling of this option, and adds some test coverage :smile: 

# Are there any user-facing changes?

This feature should now behave correctly

### CODE REVIEW

File: parquet/src/column/writer/mod.rs [hunk 1]
```diff
@@ -456,7 +456,8 @@ impl<'a, E: ColumnValueEncoder> GenericColumnWriter<'a, E> {
             for &level in levels {
                 if level == self.descr.max_def_level() {
                     values_to_write += 1;
-                } else if self.statistics_enabled == EnabledStatistics::Page {
+                } else {
+                    // We must always compute this as it is used to populate v2 pages
```
Comment (tustvold) [inline parquet/src/column/writer/mod.rs:460]: Previously this would cause an incorrect null count in the data page v2 header

File: parquet/src/column/writer/mod.rs [hunk 2]
```diff
@@ -746,26 +747,28 @@ impl<'a, E: ColumnValueEncoder> GenericColumnWriter<'a, E> {
...
             .set_total_compressed_size(total_compressed_size)
             .set_total_uncompressed_size(total_uncompressed_size)
             .set_num_values(num_values)
             .set_data_page_offset(data_page_offset)
-            .set_dictionary_page_offset(dict_page_offset)
-            .set_statistics(statistics)
-            .build()?;
+            .set_dictionary_page_offset(dict_page_offset);
+
+        if self.statistics_enabled != EnabledStatistics::None {
```
Comment (tustvold) [inline parquet/src/column/writer/mod.rs:760]: Previously we would still put the column statistics, even if we hadn't actually computed them :scream:

File: parquet/src/column/writer/mod.rs [hunk 3]
```diff
@@ -1639,6 +1642,56 @@ mod tests {
...
+
+        match &pages[1] {
+            Page::DataPageV2 {
+                num_values,
+                num_nulls,
+                num_rows,
+                statistics,
+                ..
+            } => {
+                assert_eq!(*num_values, 6);
```
Comment (tustvold) [inline parquet/src/column/writer/mod.rs:1686]: Confusingly in parquet num_values includes nulls, despite null values not actually be encoded :laughing:

**Review by viirya — APPROVED** [review]

**Review by alamb — APPROVED** [review]
I also verified that the newly added test does indeed fail without the code changes in this PR

```
---- column::writer::tests::test_disabled_statistics stdout ----
thread 'column::writer::tests::test_disabled_statistics' panicked at 'assertion failed: statistics.is_none()', parquet/src/column/writer/mod.rs:1689:17
stack backtrace:
```

🚢 🇮🇹
