### PR TITLE
Add tests and fixes for schema resolution bug

### LINKED ISSUE #9231: `ParseError("bad varint")` on reading array field as nullable
I get a `ParseError("bad varint")` on this test (added to `./arrow-avro/src/reader/mod.rs`):

```rust
    fn get_int_array_schema() -> AvroSchema {
        let schema = Schema::new(vec![Field::new(
            "int_array",
            DataType::List(Arc::new(Field::new("element", DataType::Int32, true))),
            true,
        )])
        .with_metadata(HashMap::from([("avro.name".into(), "table".into())]));
        AvroSchema::try_from(&schema).unwrap()
    }

    #[test]
    fn test_bad_varint_bug() {
        let path = arrow_test_data("avro/bad-varint-bug.avro");

        let schema = get_int_array_schema();

        let batch = read_alltypes_with_reader_schema(&path, schema);

        let int_list_col = batch.column(0).as_list::<i32>();
        let first_list = int_list_col.value(0);
        let expected_result = Arc::new(Int32Array::from_iter_values(vec![1i32, 2])) as _;
        assert_eq!(first_list, expected_result)
    }
```

The Avro file, readable by Spark: [bad-varint-bug.avro.gz](https://github.com/user-attachments/files/24724610/bad-varint-bug.avro.gz)

_Originally posted by @mzabaluev in https://github.com/apache/arrow-rs/issues/8930#issuecomment-3770381691_

### PR DESCRIPTION
**Pull request by jecsand838**
# Which issue does this PR close?

- Closes #9231.

# Rationale for this change

Avro schema resolution allows a reader schema to represent “nullable” values using a two-branch union (`["null", T]` or `[T, "null"]`) while still reading data written with the non-union schema `T` (i.e. without union discriminants in the encoded data).

In `arrow-avro`, resolving a non-union writer type against a reader union (notably for array/list item schemas like `items: ["null", "int"]`) could incorrectly treat the encoded stream as a union and attempt to decode a union discriminant. This would misalign decoding and could surface as `ParseError("bad varint")` for certain files (see #9231).

# What changes are included in this PR?

- Fix schema resolution when the *writer* schema is non-union and the *reader* schema is a union:
  - Special-case two-branch unions containing `null` to be treated as “nullable” (capturing whether `null` is first or second), and resolve against the non-null branch.
  - Improve matching for general reader unions by attempting to resolve against each union variant, preferring a direct match, and constructing the appropriate union resolution mapping for the selected branch.
  - Ensure promotions are represented at the union-resolution level (avoiding nested promotion resolution on the selected union child).

- Add regression coverage for the bug and the fixed behavior:
  - `test_resolve_array_writer_nonunion_items_reader_nullable_items` (schema resolution / codec)
  - `test_array_decoding_writer_nonunion_items_reader_nullable_items` (record decoding; ensures correct byte consumption and decoded values)
  - `test_bad_varint_bug_nullable_array_items` (end-to-end reader regression using a small Avro fixture)

- Add a small compressed Avro fixture under `arrow-avro/test/data/bad-varint-bug.avro.gz` used by the regression test.

# Are these changes tested?

Yes. This PR adds targeted unit/integration tests that reproduce the prior failure mode and validate correct schema resolution and decoding for nullable-union array items.

# Are there any user-facing changes?

Yes (bug fix): reading Avro files with arrays whose element type is represented as a nullable union in the reader schema (e.g. `items: ["null", "int"]`) now succeeds instead of failing with `ParseError("bad varint")`. No public API changes are intended.

### CODE REVIEW

File: arrow-avro/src/codec.rs [hunk 1]
```diff
@@ -1529,23 +1529,77 @@ impl<'a> Maker<'a> {
...
-                dt.resolution = Some(ResolutionInfo::Union(ResolvedUnion {
-                    writer_to_reader: Arc::from(vec![Some((reader_index, promotion))]),
-                    writer_is_union: false,
-                    reader_is_union: true,
-                }));
-                Ok(dt)
+                let null_position = reader_variants
+                    .iter()
+                    .position(|x| x == &Schema::TypeName(TypeName::Primitive(PrimitiveType::Null)));
+                if let (2, Some(null_idx)) = (reader_variants.len(), null_position) {
```
Comment (mzabaluev) [inline arrow-avro/src/codec.rs]: Would it be good to reuse the `nullable_union_variants` helper here?

File: arrow-avro/src/reader/mod.rs [hunk 2]
```diff
@@ -9081,4 +9081,46 @@ mod test {
...
     }
+
+    #[test]
+    fn test_bad_varint_bug_nullable_array_items() {
+        use flate2::read::GzDecoder;
+        use std::io::Read;
+        let manifest_dir = env!("CARGO_MANIFEST_DIR");
+        let gz_path = format!("{manifest_dir}/test/data/bad-varint-bug.avro.gz");
+        let gz_file = File::open(&gz_path).expect("test file should exist");
+        let mut decoder = GzDecoder::new(gz_file);
```
Comment (mzabaluev) [inline arrow-avro/src/reader/mod.rs:9092]: I actually had the file unpacked in my test suite branch, it's quite small. I only gzipped it to be able to post to GitHub. But since there's already a dependency on `flate2`, might as well use it.

File: arrow-avro/src/codec.rs [hunk 3]
```diff
@@ -1529,23 +1529,77 @@ impl<'a> Maker<'a> {
...
+                    let non_null_idx = 1 - null_idx;
+                    let non_null_branch = &reader_variants[non_null_idx];
+                    let mut dt =
+                        self.make_data_type(writer_non_union, Some(non_null_branch), namespace)?;
```
Comment (mzabaluev) [inline arrow-avro/src/codec.rs]: I'd call `resolve_type` directly here because that's what it always amounts to.

File: arrow-avro/src/codec.rs [hunk 4]
```diff
@@ -1529,23 +1529,77 @@ impl<'a> Maker<'a> {
...
+                    dt.nullability = Some(if null_idx == 0 {
+                        Nullability::NullFirst
+                    } else {
+                        Nullability::NullSecond
+                    });
+                    #[cfg(feature = "avro_custom_types")]
+                    if let Some(nb) = dt.nullability {
+                        Self::propagate_nullability_into_ree(&mut dt, nb);
+                    }
```
Comment (mzabaluev-flarion) [inline arrow-avro/src/codec.rs]:
```suggestion
                    let nullability = if null_idx == 0 {
                        Nullability::NullFirst
                    } else {
                        Nullability::NullSecond
                    };

                    #[cfg(feature = "avro_custom_types")]
                    Self::propagate_nullability_into_ree(&mut dt, nullability);

                    dt.nullability = Some(nullability);
```

**Comment by jecsand838** [comment]
@mzabaluev Thank you for the review! I just pushed up a commit that addresses your comments. Let me know what you think when you get a chance.

**Review by mzabaluev — APPROVED** [review]
Looks good!

**Comment by jecsand838** [comment]
@alamb @mbrobbel 

Would it be possible to get this bug fix in for the 58.0.0 release as well?

File: arrow-avro/test/data/bad-varint-bug.avro.gz
Comment (alamb) [inline arrow-avro/test/data/bad-varint-bug.avro.gz:1]: I unzipped this file and it looks fine to me

```
00000000  4f 62 6a 01 06 16 61 76  72 6f 2e 73 63 68 65 6d  |Obj...avro.schem|
00000010  61 84 02 7b 22 74 79 70  65 22 3a 22 72 65 63 6f  |a..{"type":"reco|
00000020  72 64 22 2c 22 6e 61 6d  65 22 3a 22 74 61 62 6c  |rd","name":"tabl|
00000030  65 22 2c 22 66 69 65 6c  64 73 22 3a 5b 7b 22 6e  |e","fields":[{"n|
00000040  61 6d 65 22 3a 22 69 6e  74 5f 61 72 72 61 79 22  |ame":"int_array"|
00000050  2c 22 74 79 70 65 22 3a  7b 22 74 79 70 65 22 3a  |,"type":{"type":|
00000060  22 61 72 72 61 79 22 2c  22 69 74 65 6d 73 22 3a  |"array","items":|
00000070  22 69 6e 74 22 2c 22 65  6c 65 6d 65 6e 74 2d 69  |"int","element-i|
00000080  64 22 3a 32 7d 2c 22 66  69 65 6c 64 2d 69 64 22  |d":2},"field-id"|
00000090  3a 31 7d 5d 7d 14 61 76  72 6f 2e 63 6f 64 65 63  |:1}]}.avro.codec|
000000a0  0e 64 65 66 6c 61 74 65  1c 69 63 65 62 65 72 67  |.deflate.iceberg|
000000b0  2e 73 63 68 65 6d 61 c8  02 7b 22 74 79 70 65 22  |.schema..{"type"|
000000c0  3a 22 73 74 72 75 63 74  22 2c 22 73 63 68 65 6d  |:"struct","schem|
000000d0  61 2d 69 64 22 3a 30 2c  22 66 69 65 6c 64 73 22  |a-id":0,"fields"|
000000e0  3a 5b 7b 22 69 64 22 3a  31 2c 22 6e 61 6d 65 22  |:[{"id":1,"name"|
000000f0  3a 22 69 6e 74 5f 61 72  72 61 79 22 2c 22 72 65  |:"int_array","re|
00000100  71 75 69 72 65 64 22 3a  74 72 75 65 2c 22 74 79  |quired":true,"ty|
00000110  70 65 22 3a 7b 22 74 79  70 65 22 3a 22 6c 69 73  |pe":{"type":"lis|
00000120  74 22 2c 22 65 6c 65 6d  65 6e 74 2d 69 64 22 3a  |t","element-id":|
00000130  32 2c 22 65 6c 65 6d 65  6e 74 22 3a 22 69 6e 74  |2,"element":"int|
00000140  22 2c 22 65 6c 65 6d 65  6e 74 2d 72 65 71 75 69  |","element-requi|
00000150  72 65 64 22 3a 74 72 75  65 7d 7d 5d 7d 00 24 70  |red":true}}]}.$p|
00000160  9c 93 05 f1 5e 13 2f c5  a0 60 cd 7a a0 35 02 0c  |....^./..`.z.5..|
00000170  63 61 62 61 00 00 24 70  9c 93 05 f1 5e 13 2f c5  |caba..$p....^./.|
00000180  a0 60 cd 7a a0 35                                 |.`.z.5|
```

**Comment by alamb** [comment]
Thanks @jecsand838
