### PR TITLE
Fix MutableArrayData::extend_nulls (#1230)

### LINKED ISSUE #1230: MutableArrayData::extend_nulls doesn't update null bitmask
**Describe the bug**

Noticed whilst working on #1225, calling `MutableArrayData::extend_nulls` doesn't update the null bitmask. This means the final array may have a shifted or completely invalid bitmask. 

#1225 changed it so that if `MutableArrayData` is created with nulls disabled, it panics if you try to append nulls. Unfortunately it would appear this is being exploited by `ArrowArrayReader` to avoid computing a bitmask.

**To Reproduce**

```
#[test]
    fn test_nulls() {
        let ints: ArrayRef = Arc::new(Int32Array::from(vec![1]));
        let mut data = MutableArrayData::new(vec![ints.data()], true, 3);
        data.extend_nulls(9);
        let data = data.freeze();
        
        assert_eq!(data.len(), 9);
        assert_eq!(data.null_buffer().unwrap().len(), 2);
    }
```

**Expected behavior**

Appending nulls should update the null bitmask, and it should panic if `MutableArrayData` is created without null support. Fixing this is likely blocked on #1197 as it relies on this behaviour

### LINKED ISSUE #4324: concat_batches panics with total_len <= bit_len assertion for records with lists
**Describe the bug**
`concat`, used by `concat_batches`, does not appear to allocate sufficient `capacities` when constructing the `MutableArrayData`. Concatenating records that contain lists of structs results in the following panic:
```
assertion failed: total_len <= bit_len
thread 'concat_test' panicked at 'assertion failed: total_len <= bit_len', /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-buffer-40.0.0/src/buffer/boolean.rs:55:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: arrow_buffer::buffer::boolean::BooleanBuffer::new
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-buffer-40.0.0/src/buffer/boolean.rs:55:9
   4: arrow_data::transform::_MutableArrayData::freeze::{{closure}}
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:81:25
   5: core::bool::<impl bool>::then
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/bool.rs:71:24
   6: arrow_data::transform::_MutableArrayData::freeze
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:80:21
   7: arrow_data::transform::MutableArrayData::freeze
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:656:18
   8: arrow_data::transform::_MutableArrayData::freeze
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:74:37
   9: arrow_data::transform::MutableArrayData::freeze
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:656:18
  10: arrow_data::transform::_MutableArrayData::freeze
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:74:37
  11: arrow_data::transform::MutableArrayData::freeze
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:656:18
  12: arrow_data::transform::_MutableArrayData::freeze
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:74:37
  13: arrow_data::transform::MutableArrayData::freeze
             at /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-40.0.0/src/transform/mod.rs:656:18
```

**To Reproduce**
Call `concat_batches` with `RecordBatch`s that contain lists of structs (on the order of 20–50 structs in the list per `RecordBatch`). If I modify [the capacity calculation in concat](https://github.com/apache/arrow-rs/blob/c295b172b37902d5fa41ef275ff5b86caf9fde75/arrow-select/src/concat.rs#L76-L82) to add a constant factor for lists, the error does not occur:
```rust
    let capacity = match d {
        DataType::Utf8 => binary_capacity::<Utf8Type>(arrays),
        DataType::LargeUtf8 => binary_capacity::<LargeUtf8Type>(arrays),
        DataType::Binary => binary_capacity::<BinaryType>(arrays),
        DataType::LargeBinary => binary_capacity::<LargeBinaryType>(arrays),
        DataType::List(_) => {
            Capacities::Array(arrays.iter().map(|a| a.len()).sum::<usize>() + 500) // <- 500 added here
        }
        _ => Capacities::Array(arrays.iter().map(|a| a.len()).sum()),
    };
```

**Expected behavior**
No panics when concatenating `RecordBatch`s with lists.

**Additional context**
Reproduced with Arrow versions 37–40.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1230
Closes #4324 

# Rationale for this change
 

MutableArrayData::extend_nulls doesn't update the null bitmask, and so has never worked correctly. Since #3775 it most likely will result in freeze panicking. It is surprising that nobody has hit this before, although we use `MutableArrayData` in very limited places, and `MutableArrayData::extend_nulls` in even fewer.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-data/src/transform/mod.rs [hunk 1]
```diff
@@ -53,7 +53,7 @@ struct _MutableArrayData<'a> {
     pub null_count: usize,
 
     pub len: usize,
-    pub null_buffer: MutableBuffer,
+    pub null_buffer: Option<MutableBuffer>,
```
Comment (tustvold) [inline arrow-data/src/transform/mod.rs:56]: This does add a branch on append, in practice appending to a null mask is so branch heavy anyway, not to mention already involving a dyn dispatch, I struggle to see how this could have an appreciable performance impact

File: arrow-data/src/transform/mod.rs [hunk 2]
```diff
@@ -624,13 +633,18 @@ impl<'a> MutableArrayData<'a> {
...
     pub fn extend_nulls(&mut self, len: usize) {
-        // TODO: null_buffer should probably be extended here as well
-        // otherwise is_valid() could later panic
-        // add test to confirm
+        self.data.len += len;
+        let bit_len = bit_util::ceil(self.data.len, 8);
+        let nulls = self.data.null_buffer();
+        nulls.resize(bit_len, 0);
         self.data.null_count += len;
         (self.extend_nulls)(&mut self.data, len);
```
Comment (tustvold) [inline arrow-data/src/transform/mod.rs:647]: Despite its name this extends the **values** with nulls, it doesn't do anything to the bit mask. I'm honestly not entirely sure why the separation, but :shrug:

File: arrow-data/src/transform/mod.rs [hunk 3]
```diff
@@ -624,13 +633,18 @@ impl<'a> MutableArrayData<'a> {
     }
 
     /// Extends this [MutableArrayData] with null elements, disregarding the bound arrays
+    ///
+    /// # Panics
+    ///
+    /// Panics if [`MutableArrayData`] not created with `use_nulls` or nullable source arrays
+    ///
     pub fn extend_nulls(&mut self, len: usize) {
-        // TODO: null_buffer should probably be extended here as well
```
Comment (alamb) [inline arrow-data/src/transform/mod.rs:628]: classic TODO

**Review by alamb — APPROVED** [review]
Makes sense to me -- thank you @tustvold

File: arrow-data/src/transform/mod.rs (hunk 3 above)
Comment (tustvold) [reply arrow-data/src/transform/mod.rs:628]: Yup, I remember adding it at the same time as I created #1230 - I then completely forgot about it :sweat_smile:
