### PR TITLE
Fix max and min value for decimal precision greater than 38

### LINKED ISSUE #2246: Fix maximum and minimum for decimal values for precision greater than 38
**Describe the bug**

I made a mistake when filling out `MAX_DECIMAL_FOR_LARGER_PRECISION` and `MIN_DECIMAL_FOR_EACH_PRECISION`. It is less one digit for each value.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #2246.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/datatypes/datatype.rs [hunk 1]
```diff
@@ -309,7 +309,6 @@ pub const MAX_DECIMAL_FOR_EACH_PRECISION: [i128; 38] = [
 /// `MAX_DECIMAL_FOR_LARGER_PRECISION[p]` holds the maximum integer value
 /// that can be stored in [DataType::Decimal256] value of precision `p` > 38
 pub const MAX_DECIMAL_FOR_LARGER_PRECISION: [&str; 38] = [
-    "99999999999999999999999999999999999999",
```
Comment (viirya) [inline arrow/src/datatypes/datatype.rs:312]: This is only 38 digits, it should be 39.

File: arrow/src/datatypes/datatype.rs [hunk 2]
```diff
@@ -395,7 +395,6 @@ pub const MIN_DECIMAL_FOR_EACH_PRECISION: [i128; 38] = [
 /// `MIN_DECIMAL_FOR_LARGER_PRECISION[p]` holds the minimum integer value
 /// that can be stored in a [DataType::Decimal256] value of precision `p` > 38
 pub const MIN_DECIMAL_FOR_LARGER_PRECISION: [&str; 38] = [
-    "-99999999999999999999999999999999999999",
```
Comment (viirya) [inline arrow/src/datatypes/datatype.rs:398]: ditto.

**Review by tustvold — APPROVED** [review]

**Comment by alamb** [comment]
(Integration testing for the win!)
