### PR TITLE
fix(object_store,gcp): test copy_if_not_exist

### LINKED ISSUE #3235: object_store(gcp): GCP complains about content-length for copy
**Describe the bug**

An error in the GCP `copy_if_not_exist` was reported upstream in delta-rs: https://github.com/delta-io/delta-rs/issues/878#issue-1404449207

```
PyDeltaTableError: Failed to read delta log object: Generic GCS error: Error performing copy request 
Error 411 (Length Required)
```

I haven't been able to reproduce this yet, but seems like it couldn't hurt to put `Content-Length: 0` in the request.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by wjones127**
# Which issue does this PR close?

Closes #3235.

# Rationale for this change
 
The `copy_if_not_exist` function was not tested, and didn't pass the test when enabled. It needed to return an `AlreadyExists` error if the destination already existed.

# What changes are included in this PR?

 * `copy_if_not_exist` returns `AlreadyExists` error when appropriate
 * GCP now tests `copy_if_not_exists` in integration tests
 * GCS copy commands send a `Content-Length` header now.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by wjones127** [comment]
I have run the integration tests for the gcs feature against my own GCS account and they all pass. ✅

File: object_store/src/gcp/mod.rs [hunk 1]
```diff
@@ -420,10 +430,25 @@ impl GoogleCloudStorageClient {
 
         builder
             .bearer_auth(token)
+            .header(header::CONTENT_LENGTH, 0)
```
Comment (tustvold) [inline object_store/src/gcp/mod.rs:433]: At least when testing against GCP this change does not seem to be required in order for the tests to pass?

**Review by tustvold — APPROVED** [review]

File: object_store/src/gcp/mod.rs (hunk 1 above)
Comment (wjones127) [reply object_store/src/gcp/mod.rs:433]: I think you are right. I originally got an error report suggesting this was necessary, but haven't been able to reproduce that specific error. I'd be fine with striking this until I can get a proper reproduction.
