### PR TITLE
Avoid use of `flatbuffers::size_prefixed_root`, fix validation error in arrow-flight

### LINKED ISSUE #7058: Incorrect IPC schema encoding for multiple dictionaries
**Describe the bug**

The following test case should pass, but it errors:

```
thread 'tests::test_dict_schema' panicked at arrow-flight/src/lib.rs:851:56:
called `Result::unwrap()` on an `Err` value: ParseError("Unable to convert flight info to a message: Type `i64` at position 100 is unaligned.\n\twhile verifying table field `id` at position 100\n\twhile verifying table field `dictionary` at position 76\n\twhile verifying vector element 1 at position 56\n\twhile verifying table field `fields` at position 44\n\t while verifying union variant `MessageHeader::Schema` at position 24\n\twhile verifying table field `header` at position 24\n\n")
```
**To Reproduce**

```rust
    #[test]
    fn test_dict_schema() {
        let schema = Schema::new(vec![
            Field::new(
                "a",
                DataType::Dictionary(Box::new(DataType::UInt16), Box::new(DataType::Utf8)),
                false,
            ),
            Field::new(
                "b",
                DataType::Dictionary(Box::new(DataType::UInt16), Box::new(DataType::Utf8)),
                false,
            ),
        ]);

        let flight_info = FlightInfo::new().try_with_schema(&schema).unwrap();

        let new_schema = Schema::try_from(flight_info).unwrap();
        assert_eq!(schema, new_schema);
    }
```
**Expected behavior**

If the schema only has one dictionary, it would work just fine.

**Additional context**

### PR DESCRIPTION
**Pull request by bkietz**
# Which issue does this PR close?

- Closes #7058

# Rationale for this change
 

[flatbuffers::size_prefixed_root](https://docs.rs/flatbuffers/latest/flatbuffers/fn.size_prefixed_root.html) does not seem to do what was originally expected. Replacing it with more explicit code for handling an encapsulated message prefix seems to resolve the case of interest.

# What changes are included in this PR?

Usage of `size_prefixed_root` ( there was only one call, introduced in https://github.com/apache/arrow-rs/pull/2586 ) is replaced with manual prefixed length wrangling. A unit test is added

# Are there any user-facing changes?

No

Maybe the error messages?

### CODE REVIEW

**Comment by XiangpengHao** [comment]
The change looks good to me, I've tested in in https://github.com/XiangpengHao/liquid-cache, and it indeed fixes the problem it tries fix

File: arrow-ipc/src/reader.rs [hunk 1]
```diff
@@ -2617,4 +2619,43 @@ mod tests {
         let err = read_ipc_with_decoder(buf).unwrap_err();
         assert_eq!(err.to_string(), expected_err);
     }
+
+    #[test]
+    fn test_roundtrip_schema() {
```
Comment (alamb) [inline arrow-ipc/src/reader.rs:2624]: Strangely this test passes for me on main (without the changes in this PR)

So I don't think it covers the issue somehow. I am looking into it a bit more

File: arrow-ipc/src/convert.rs [hunk 2]
```diff
@@ -255,32 +255,43 @@ pub fn try_schema_from_ipc_buffer(buffer: &[u8]) -> Result<Schema, ArrowError> {
...
+            return Err(ArrowError::ParseError(
+                "The buffer length is less than 8 and missing the length of buffer".to_string(),
+            ));
+        }
+        buffer[4..].split_at(4)
+    } else {
+        buffer.split_at(4)
+    };
+
+    let len = <i32>::from_le_bytes(len.try_into().unwrap());
```
Comment (alamb) [inline arrow-ipc/src/convert.rs:275]: this are very reasonable checks 👍

**Review by alamb — APPROVED** [review]
Thank you @bkietz and @XiangpengHao 

I took the liberty of merging this PR up from main as well as adding the test case from @XiangpengHao 's original issue https://github.com/apache/arrow-rs/issues/7058

The reason the test in this PR might not be failing might be related to how it sets up the dictionary tracker where arrow-flight does this:

```rust
    let mut dict_tracker =
        writer::DictionaryTracker::new_with_preserve_dict_id(false, options.preserve_dict_id());
```

https://github.com/apache/arrow-rs/blob/fc6936aff50b0b1c8bea984bba2d57dac68a98b3/arrow-flight/src/lib.rs#L147-L148
