### PR TITLE
Fix interval to duration casting (#4553)

### LINKED ISSUE #4553: Incorrect Interval to Duration Casting
**Describe the bug**

The cast from IntervalMonthDayNano to a duration interprets the interval value as `i128` instead of its parts, this results in peculiar overflow behaviour and is simply incorrect 

**To Reproduce**

**Expected behavior**

**Additional context**

https://github.com/apache/arrow-datafusion/pull/6832#issuecomment-1642604829

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4553

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-cast/src/cast.rs [hunk 1]
```diff
@@ -470,34 +461,19 @@ fn cast_interval_to_duration<D: ArrowTemporalType<Native = i64>>(
     };
 
     if cast_options.safe {
-        let iter = array.iter().map(|v| {
-            v.and_then(|v| {
-                let v = v / scale;
-                if v > i64::MAX as i128 {
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:476]: This formulation failed to handle negatives correctly

File: arrow-cast/src/cast.rs [hunk 2]
```diff
@@ -470,34 +461,19 @@ fn cast_interval_to_duration<D: ArrowTemporalType<Native = i64>>(
...
-                    None
-                } else {
-                    Some(v as i64)
-                }
-            })
-        });
+        let iter = array
+            .iter()
+            .map(|v| v.and_then(|v| (v >> 64 == 0).then(|| (v as i64) / scale)));
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:466]: As an added bonus we are now doing 64-bit division which should be cheaper than 128-bit

File: arrow-cast/src/cast.rs [hunk 3]
```diff
@@ -8658,10 +8621,6 @@ mod tests {
             &CastOptions::default(),
         )
         .unwrap();
-        assert_eq!(
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:8661]: These tests are redundant as they're already encoded in the types returned

File: arrow-cast/src/cast.rs [hunk 4]
```diff
@@ -447,20 +447,11 @@ fn cast_interval_day_time_to_interval_month_day_nano(
 }
 
 /// Cast the array from interval to duration
-fn cast_interval_to_duration<D: ArrowTemporalType<Native = i64>>(
+fn cast_month_day_none_to_duration<D: ArrowTemporalType<Native = i64>>(
```
Comment (alamb) [inline arrow-cast/src/cast.rs:450]: What is the meaning of the `_none_` in this name? I couldn't figure it out. Maybe it should be`_nano_` 🤔

File: arrow-cast/src/cast.rs [hunk 5]
```diff
@@ -470,34 +461,19 @@ fn cast_interval_to_duration<D: ArrowTemporalType<Native = i64>>(
...
-            v.and_then(|v| {
-                let v = v / scale;
-                if v > i64::MAX as i128 {
-                    None
-                } else {
-                    Some(v as i64)
-                }
-            })
-        });
+        let iter = array
```
Comment (alamb) [inline arrow-cast/src/cast.rs:464]: This is very clever ❤️

File: arrow-cast/src/cast.rs (hunk 3 above)
Comment (alamb) [reply arrow-cast/src/cast.rs:8661]: I don't understand this rationale. While the types are encoded in the return type (e,.g IntervalMonthDayNanoArray) they aren't checked by the test. Thus, if they changed to IntervalDayTime or something I don't think the compiler would fail.

Maybe we could add explicit types, like 

```rust
 let casted_array: IntervalMonthDayNanoArray = cast_from_duration_to_interval::<DurationSecondType>(...)
```

File: arrow-cast/src/cast.rs [hunk 6]
```diff
@@ -8788,125 +8733,95 @@ mod tests {
...
+            IntervalMonthDayNanoType::make_value(-1, 0, 0),
+            IntervalMonthDayNanoType::make_value(1, 1, 0),
+            IntervalMonthDayNanoType::make_value(1, 0, 1),
+            IntervalMonthDayNanoType::make_value(0, 0, -1),
+        ]
+        .into();
+        let casted_array =
+            cast_from_interval_to_duration::<DurationNanosecondType>(&array, &nullable)
+                .unwrap();
+        assert!(!casted_array.is_valid(0));
```
Comment (alamb) [inline arrow-cast/src/cast.rs:8820]: I think this test should also explicitly verify the values (not just that they are valid or not)

**Review by alamb — APPROVED** [review]
The code looks very nice to me. I have some questions / suggestions about the tests
