### PR TITLE
Respect max rowgroup size in Arrow writer

### LINKED ISSUE #257: Parquet `WriterProperties.max_row_group_size` not wired up
**Describe the bug**
This property (that can be set via the `WriterPropertiesBuilder`):

https://github.com/apache/arrow-rs/blob/508f25c10032857da34ea88cc8166f0741616a32/parquet/src/file/properties.rs#L99

can only be retrieved using this getter:

https://github.com/apache/arrow-rs/blob/508f25c10032857da34ea88cc8166f0741616a32/parquet/src/file/properties.rs#L132-L135

but this getter is never used. In fact quickly trying out this property has no effect. I think it should probably we wired up here:

https://github.com/apache/arrow-rs/blob/508f25c10032857da34ea88cc8166f0741616a32/parquet/src/arrow/arrow_writer.rs#L80-L101

where the incoming `RecordBatch` is split into batches of the configured size that will then fed into individual record batches.

**To Reproduce**

1. create a `RecordBatch` with 3 rows.
2. Set `WriterProperties.max_row_group_size` to 1
3. Create a parquet file
4. See the that parquet file has only 1 row group (should be 3).

**Expected behavior**
Record batches created from arrow should respect `WriterProperties.max_row_group_size`.

**Additional context**
Commit in question is `508f25c10032857da34ea88cc8166f0741616a32`.

### PR DESCRIPTION
**Pull request by nevi-me**
# Which issue does this PR close?

Closes #257.

# Rationale for this change
 
Parquet splits batches into row groups, which are normally determined by a `max_row_group_size` setting.
The Arrow writer could not respect this setting because we cannot slice into structs and arrays correctly.
The issue is that when using `array.slice(offset: usize, len: usize)`, we don't propagate and calculate the slice of child data, leading to only the top-level data being sliced.

# What changes are included in this PR?

We use the `LevelInfo` struct to keep track of its array's offset and length. This allows us to track nested arrays' offsets, and calculate the correct list offsets and lengths.

We then use the `arrow::array::slice` to perform 0-copy slices from a batch, to limit the row group size correctly.

I have changed all writer tests to use a max row group size, ensuring that we aren't introducing bugs when slicing.

Note that this is related to #225, but I don't think it quite covers all its use-cases.
If we have a sliced recordbatch per #343, we would need to account for its individual array offsets, as there is never a guarantee that a record batch has all child arrays starting from the same offset.

# Are there any user-facing changes?

No. All changes are crate-internal.

### CODE REVIEW

**Comment by nevi-me** [comment]
CC @crepererum @houqp (we've spoken about this before)

File: parquet/src/arrow/arrow_writer.rs [hunk 1]
```diff
@@ -87,17 +92,31 @@ impl<W: 'static + ParquetWriter> ArrowWriter<W> {
...
-        for (array, field) in batch.columns().iter().zip(batch.schema().fields()) {
-            let mut levels = batch_level.calculate_array_levels(array, field);
-            // Reverse levels as we pop() them when writing arrays
-            levels.reverse();
-            write_leaves(&mut row_group_writer, array, &mut levels)?;
+        // Track the number of rows being written in the batch.
+        // We currently do not have a way of slicing nested arrays, thus we
+        // track this manually.
+        let num_rows = batch.num_rows();
+        let batches = (num_rows + self.max_row_group_size - 1) / self.max_row_group_size;
```
Comment (crepererum) [inline parquet/src/arrow/arrow_writer.rs:99]: Do we ensure that `max_row_group_size > 0`?

Comment (nevi-me) [reply parquet/src/arrow/arrow_writer.rs:99]: I do it here: https://github.com/apache/arrow-rs/pull/381/files#diff-a0e33950f81a4d9d1217351c5f3a543d7e4b2ca4b705f41223bc7192386edacaR293

I can check if there's ways of bypassing that

Comment (crepererum) [reply parquet/src/arrow/arrow_writer.rs:99]: I think that's sufficient :)

Comment (alamb) [reply parquet/src/arrow/arrow_writer.rs:99]: Am I correct in thinking this code could result in non-uniform row group sizes?

like if we had `max_row_group_size=10` and wrote a `RecordBatch` with 25 rows,  would we get row groups like

```
(row_group 1: 10 rows)
(row_group 2: 10 rows)
(row_group 3: 5 rows)
(row_group 4: 10 rows)
(row_group 5: 10 rows)
(row_group 6: 5 rows)
```

? 

If so I think this is fine (in that it is technically respecting `max_row_group` but it might be unexpected from a user,  who might expect something more like

```
(row_group 1: 10 rows)
(row_group 2: 10 rows)
(row_group 3: 10 rows)
(row_group 4: 10 rows)
(row_group 5: 10 rows)
```

Perhaps it is worth a doc comment?

File: parquet/src/arrow/arrow_writer.rs [hunk 2]
```diff
@@ -1176,31 +1236,51 @@ mod tests {
         let raw_values: Vec<_> = (0..SMALL_SIZE as i64).collect();
         let values = Arc::new(TimestampSecondArray::from_vec(raw_values, None));
 
-        one_column_roundtrip("timestamp_second_single_column", values, false);
+        one_column_roundtrip(
```
Comment (alamb) [inline parquet/src/arrow/arrow_writer.rs:1239]: it might be worth at least one test that divides into "more than 2" batches as well.

File: parquet/src/arrow/levels.rs [hunk 3]
```diff
@@ -748,6 +784,8 @@ mod tests {
             array_mask: vec![true, true], // both lists defined
             max_definition: 0,
             level_type: LevelType::Root,
+            offset: 0,
```
Comment (alamb) [inline parquet/src/arrow/levels.rs:787]: It might be cool to add a test here where the offset was something other than `0` -- all the examples I see have `offset: 0`.

**Review by alamb — APPROVED** [review]
Thanks @nevi-me ! I had some minor additional test coverage suggestions, but otherwise this looks great!

File: parquet/src/arrow/arrow_writer.rs (hunk 1 above)
Comment (nevi-me) [reply parquet/src/arrow/arrow_writer.rs:99]: Yes, that's a fair observation. I think it's a bit tricky because we would need to get the other 5 records from the next batch.

If we passed all batches at once, we would be able to segment them into equal rows.

This is something we can think of, as I think it's a valid expectation from a user.

I can check if we are able to keep row groups open, so that when the next batch comes in, we take its 5 records

Comment (alamb) [reply parquet/src/arrow/arrow_writer.rs:99]: Maybe just adding a note in the docstring would be sufficient at this time

File: parquet/src/arrow/levels.rs (hunk 3 above)
Comment (nevi-me) [reply parquet/src/arrow/levels.rs:786]: I've added a test to `list_single_column` with an offset.

File: parquet/src/arrow/arrow_writer.rs (hunk 2 above)
Comment (nevi-me) [reply parquet/src/arrow/arrow_writer.rs]: I've changed the `SMALL_SIZE` to an odd number, and then changed the batch sizes of some tests.

File: parquet/src/arrow/arrow_writer.rs (hunk 1 above)
Comment (nevi-me) [reply parquet/src/arrow/arrow_writer.rs:103]: Added a note, thanks :)

**Comment by nevi-me** [comment]
I've addressed feedback, PTAL @alamb

File: parquet/src/arrow/levels.rs [hunk 4]
```diff
@@ -1275,17 +1274,17 @@ mod tests {
...
             repetition: None,
-            array_offsets: (0..=5).collect(),
-            array_mask: vec![true, true, true, true, true],
+            array_offsets: (0..=2).collect(),
+            array_mask: vec![true, true],
             max_definition: 0,
             level_type: LevelType::Root,
-            offset: 0,
-            length: 5,
+            offset: 2,
```
Comment (alamb) [inline parquet/src/arrow/levels.rs:1283]: 👍

**Review by alamb — APPROVED** [review]
Looks great @nevi-me

**Comment by alamb** [comment]
I could not automatically cherry pick this to active_release (what will become `4.3.0`) so if we want to do so we will have to do it manually

```
alamb@ip-10-0-0-124:~/Software/arrow-rs$ CHERRY_PICK_SHA=7ec3158     ARROW_GITHUB_API_TOKEN=$ARROW_GITHUB_API_TOKEN CHECKOUT_ROOT=/tmp/arrow-rs  python3 dev/release/cherry-pick-pr.py
CHERRY_PICK_SHA=7ec3158     ARROW_GITHUB_API_TOKEN=$ARROW_GITHUB_API_TOKEN CHECKOUT_ROOT=/tmp/arrow-rs  python3 dev/release/cherry-pick-pr.py
Using checkout in /tmp/arrow-rs
Creating cherry pick from 7ec3158b to cherry_pick_7ec3158b
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
From github.com:apache/arrow-rs
 * branch              master     -> FETCH_HEAD
From github.com:apache/arrow-rs
 * branch              active_release -> FETCH_HEAD
fatal: A branch named 'cherry_pick_7ec3158b' already exists.
Command failed: ['git', 'checkout', '-b', 'cherry_pick_7ec3158b']
With output:
--------------
b''
--------------
Traceback (most recent call last):
  File "/Users/alamb/Software/arrow-rs/dev/release/cherry-pick-pr.py", line 153, in <module>
    make_cherry_pick()
  File "/Users/alamb/Software/arrow-rs/dev/release/cherry-pick-pr.py", line 114, in make_cherry_pick
    run_cmd(['git', 'checkout', '-b', new_branch])
  File "/Users/alamb/Software/arrow-rs/dev/release/cherry-pick-pr.py", line 78, in run_cmd
    raise e
  File "/Users/alamb/Software/arrow-rs/dev/release/cherry-pick-pr.py", line 70, in run_cmd
    output = subprocess.check_output(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'checkout', '-b', 'cherry_pick_7ec3158b']' returned non-zero exit status 128.
alamb@ip-10-0-0-124:~/Software/arrow-rs$ 
```

**Comment by alamb** [comment]
Back ported in https://github.com/apache/arrow-rs/pull/430
