### PR TITLE
Fix unary_dyn for decimal scalar arithmetic computation

### LINKED ISSUE #3344: Decimal arithmetic computation fails to run because decimal type equality
**Describe the bug**

The functions like `unary_dyn` fails to compute if it finds inequality between array type and operation operand type:

For decimal types, just precision/scale can also fail the type equality. Because decimal types have default precision and scale, such check makes no sense for decimal types:

```
NotYetImplemented("Cannot perform unary operation of type Decimal128(38, 10) on array of type Decim
al128(38, 2)")'
```

This makes scalar arithmetic kernels cannot work on decimal types mostly.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #3344.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/compute/kernels/arity.rs [hunk 1]
```diff
@@ -135,14 +138,15 @@ where
     downcast_dictionary_array! {
         array => unary_dict::<_, F, T>(array, op),
         t => {
-            if t == &T::DATA_TYPE {
+            if t == &T::DATA_TYPE || (t.is_decimal() && T::DATA_TYPE.is_decimal())  {
```
Comment (tustvold) [inline arrow/src/compute/kernels/arity.rs:141]: Could we use discriminant instead - in the same way that we do `PrimitiveArray::from(ArrayData)`?

Comment (viirya) [reply arrow/src/compute/kernels/arity.rs:141]: Learnt about discriminant now. 👍

**Review by tustvold — APPROVED** [review]
