### PR TITLE
Make FlightSQL Support HTTPs

### LINKED ISSUE #3309: [FlightSQL] Support HTTPs
As pointed out by @martin-g  the current flight SQL client does not work with https

        Does it work with HTTPS ?

_Originally posted by @martin-g in https://github.com/apache/arrow-rs/pull/3207#discussion_r1033017456_

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #3309.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-flight/src/sql/client.rs [hunk 1]
```diff
@@ -71,6 +74,43 @@ impl FlightSqlServiceClient {
...
             .keep_alive_timeout(Duration::from_secs(20))
             .keep_alive_while_idle(true);
+
+        let channel = endpoint.connect().await.map_err(|e| {
+            ArrowError::IoError(format!("Cannot connect to endpoint: {}", e))
+        })?;
+        Ok(Self::new(channel))
+    }
+
+    /// Creates a new HTTPs FlightSql Client that connects via TCP to a server
```
Comment (alamb) [inline arrow-flight/src/sql/client.rs:84]: Very cool 👍

File: .github/workflows/arrow_flight.yml [hunk 2]
```diff
@@ -59,6 +59,9 @@ jobs:
       - name: Test --examples
         run: |
           cargo test -p arrow-flight  --features=flight-sql-experimental --examples
+      - name: Test --examples with TLS
```
Comment (alamb) [inline .github/workflows/arrow_flight.yml:62]: 👨‍🍳 👌 

Very nice -- thank you @viirya

File: arrow-flight/src/sql/client.rs [hunk 3]
```diff
@@ -71,6 +74,43 @@ impl FlightSqlServiceClient {
...
+        let tls_config = ClientTlsConfig::new()
+            .domain_name(domain)
+            .ca_certificate(server_ca)
+            .identity(client_ident);
+
+        let endpoint = endpoint
+            .tls_config(tls_config)
+            .map_err(|_| ArrowError::IoError("Cannot create endpoint".to_string()))?;
+
         let channel = endpoint.connect().await.map_err(|e| {
```
Comment (alamb) [inline arrow-flight/src/sql/client.rs:114]: FWIW my eventual plan is to change the signature of the FlightSQL client to be `fn new(channel: Channel)` (thus leaving the TLS configuration / setup up to the caller. It is great to have an example implementation / test in arrow-rs  however

**Review by alamb — APPROVED** [review]
Thank you @viirya

File: arrow-flight/src/sql/client.rs (hunk 3 above)
Comment (viirya) [reply arrow-flight/src/sql/client.rs:114]: Yea, this is basically similar signature as http version api. We can have a `fn new(channel: Channel)` for more customized usage.

Comment (alamb) [reply arrow-flight/src/sql/client.rs:114]: 👍  I am going to propose (in some future PR) that instead of these higher level  APIs we'll just have the Channel API and have doc examples showing how to configure the Channel for these usecases

**Comment by viirya** [comment]
Thank you @alamb
