### PR TITLE
fix: object store http header last modified

### LINKED ISSUE #4831: object-store: http-store fails when url doesn't have last-modified header on 0.7.0
**Describe the bug**
prior to `0.7.0` of object_store, you could fetch from urls that didn't have `last-modified` header, after 0.7.0 i get the error
```
 Unable to extract metadata from headers: Last-Modified Header missing from response
 ```

**To Reproduce**
cargo.toml
```toml
[package]
name = "object-store-mre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object_store = { version = "0.7.0", features = ["http", "aws", "azure", "gcp"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
```
main.rs
```rust
use object_store::http::HttpBuilder;
use object_store::path::Path;
use object_store::ObjectStore;

#[tokio::main]
async fn main() {
    let http = HttpBuilder::new().with_url("https://raw.githubusercontent.com/GlareDB/glaredb/main/testdata/sqllogictests_datasources_common/data/bikeshare_stations.ndjson");
    let store = http.build().unwrap();
    let path = Path::default();

    let res = store.get(&path).await.unwrap();
    println!("{:?}", res);
}
```

**Expected behavior**
works like it did in previous versions

**Additional context**

### PR DESCRIPTION
**Pull request by universalmind303**
# Which issue does this PR close?

Closes #4831

# Rationale for this change

object store 0.7.0 caused breaking changes in fetching from endpoints without `last_modified`
 

# What changes are included in this PR?

If the `last-modified` header is not present, it will default to the epoch. 

# Are there any user-facing changes?

### CODE REVIEW

File: object_store/src/client/header.rs [hunk 1]
```diff
@@ -53,19 +53,22 @@ pub enum Error {
...
+    let last_modified = headers.get(LAST_MODIFIED);
+    let last_modified = match last_modified {
+        Some(last_modified) => {
+            let last_modified = last_modified.to_str().context(BadHeaderSnafu)?;
+            DateTime::parse_from_rfc2822(last_modified)
+                .context(InvalidLastModifiedSnafu { last_modified })?
+                .with_timezone(&Utc)
+        }
+        // If the last modified header is missing, assume the object was created at the epoch
+        None => chrono::Utc.timestamp_nanos(0),
```
Comment (tustvold) [inline object_store/src/client/header.rs:65]: IIRC this method is deprecated and you will need to use timestamp_nanos_opt

**Comment by tustvold** [comment]
I need to think on this, it might be we need to loosen the requirements for HttpStore, ideally as a configurable option.

However, as written this PR will loosen the requirements for things like S3, etc... which I'm not sure is a good idea

File: object_store/src/client/header.rs (hunk 1 above)
Comment (universalmind303) [reply object_store/src/client/header.rs:65]: I think the deprecation was for `Datetime::timestamp_nanos` not `TimeZone::timestamp_nanos`. There doesn't appear to be a `TimeZone::timestamp_nanos_opt`

**Comment by universalmind303** [comment]
> However, as written this PR will loosen the requirements for things like S3, etc... which I'm not sure is a good idea

That makes sense. I just pushed up a refactor that changes `header_meta` to take in a new config struct that allows users to specify which fields are required. (last_modified, etag) being the two that are optional. 

This should leave the other object stores like S3 unaffected.

File: object_store/src/client/header.rs [hunk 2]
```diff
@@ -52,32 +74,55 @@ pub enum Error {
...
+                .with_timezone(&Utc);
+            last_modified
+        }
+        None => {
+            if cfg.last_modified_required {
+                return Err(Error::MissingLastModified);
+            } else {
+                chrono::Utc.timestamp_nanos(0)
+            }
+        }
```
Comment (tustvold) [inline object_store/src/client/header.rs:96]:
```suggestion
        None if cfg.last_modified_required => return Err(Error::MissingLastModified),
        None => Utc.timestamp_nanos(0),
```

File: object_store/src/client/header.rs [hunk 3]
```diff
@@ -52,32 +74,55 @@ pub enum Error {
...
+            let e_tag = e_tag.to_str().context(BadHeaderSnafu)?;
+            Some(e_tag.to_string())
+        }
+        None => {
+            if cfg.etag_required {
+                return Err(Error::MissingEtag);
+            } else {
+                None
+            }
+        }
```
Comment (tustvold) [inline object_store/src/client/header.rs:110]:
```suggestion
        None if cfg.etag_required => return Err(Error::MissingEtag),
        None => None,
```

File: object_store/src/client/header.rs [hunk 4]
```diff
@@ -52,32 +74,55 @@ pub enum Error {
...
+    headers: &HeaderMap,
+    cfg: HeaderConfig,
+) -> Result<ObjectMeta, Error> {
+    let last_modified = match headers.get(LAST_MODIFIED) {
+        Some(last_modified) => {
+            let last_modified = last_modified.to_str().context(BadHeaderSnafu)?;
+            let last_modified = DateTime::parse_from_rfc2822(last_modified)
+                .context(InvalidLastModifiedSnafu { last_modified })?
+                .with_timezone(&Utc);
+            last_modified
```
Comment (tustvold) [inline object_store/src/client/header.rs:88]:
```suggestion
            DateTime::parse_from_rfc2822(last_modified)
                .context(InvalidLastModifiedSnafu { last_modified })?
                .with_timezone(&Utc)
```

File: object_store/src/client/header.rs [hunk 5]
```diff
@@ -19,11 +19,33 @@
...
+    ///
+    /// Defaults to `true`
+    pub etag_required: bool,
+    /// Whether to require a Last-Modified header when extracting [`ObjectMeta`] from headers.
+    ///
+    /// Defaults to `true`
+    pub last_modified_required: bool,
+}
+
+impl Default for HeaderConfig {
```
Comment (tustvold) [inline object_store/src/client/header.rs:40]: FWIW you could avoid this and just `derive(Default)` if you the members were `last_modified_optional` instead of `required`

**Review by tustvold — APPROVED** [review]
This looks good to me, I tried to apply the changes to avoid a round-trip but it would appear your PR blocks edits by maintainers, so I've added them as suggestions instead
