### PR TITLE
[Parquet] Avoid fetching multiple pages when the predicate cache is disabled

### LINKED ISSUE #8542: [Parquet] Avoid fetching multiple pages when `max_predicate_cache_size`is 0
**Describe the bug**

#7850 introduced the cached array reader, which causes multiple data pages to be fetched if their size is less than the `batch_size`. Depending on the file, workload, and batch size, this might cause regressions in performance (e.g., https://github.com/apache/datafusion/issues/17575).

While setting `max_predicate_cache_size` to 0 essentially disables the predicate cache, multiple pages are still unnecessarily retrieved.

The sources of this issue are:
 - The `InMemoryRowGroup::fetch` will use the expanded selection based on the provided cache `ProjectionMask`.
 - The `ArrayReaderBuilder::build_reader` will use a `CachedArrayReader` instead of the regular reader, also based on the cache `ProjectionMask`.

Thus the most straight forward solution I've found is to return None in the `ReaderFactory::compute_cache_projection` if the `max_predicate_cache_size` is 0, causing the reader to fetch only the necessary pages:

```diff
    fn compute_cache_projection(&self, projection: &ProjectionMask) -> Option<ProjectionMask> {
+       if self.max_predicate_cache_size == 0 {
+           return None;
+       }
       ...
    }
```

The `ReaderFactory::read_row_group` remains the same, since it already expects the possibility of `compute_cache_projection` to return None:

```rust
        let cache_projection = match self.compute_cache_projection(&projection) {
            Some(projection) => projection,
            None => ProjectionMask::none(meta.columns().len()),
        };
```

@alamb @XiangpengHao what do you think? Is this the best way to solve the issue? If so I can open a PR.

**To Reproduce**

See https://github.com/apache/datafusion/issues/17575.

**Expected behavior**

Retrieve only the minimum required data pages if `max_predicate_cache_size` is set to 0.

**Additional context**

### PR DESCRIPTION
**Pull request by nuno-faria**
# Which issue does this PR close?

- Closes #8542.

# Rationale for this change

When the `max_predicate_cache_size` is set to 0 there is no need to select multiple data pages until `batch_size` is reached.

# What changes are included in this PR?

- Make `ReaderFactory::compute_cache_projection` return `None` if the cache is disabled, which will end up not retrieving multiple pages unnecessarily.
- Added a unit test to confirm the new behavior.

# Are these changes tested?

Yes.

# Are there any user-facing changes?
No.

### CODE REVIEW

File: parquet/src/arrow/async_reader/mod.rs [hunk 1]
```diff
@@ -2611,4 +2616,96 @@ mod tests {
...
+        writer.close().unwrap();
+
+        let data = Bytes::from(buf);
+        let metadata = ParquetMetaDataReader::new()
+            .with_page_index_policy(PageIndexPolicy::Required)
+            .parse_and_finish(&data)
+            .unwrap();
+        let parquet_schema = metadata.file_metadata().schema_descr_ptr();
+
+        // the filter is not clone-able, so we use a lambda to simplify
```
Comment (alamb) [inline parquet/src/arrow/async_reader/mod.rs:2644]: yeah, this is something that makes the filters very tricky to handle internally.  Nothing to change for this PR, I am just observing

**Review by alamb — APPROVED** [review]
Thank you @nuno-faria  -- this looks very great to me

**Comment by alamb** [comment]
FYI @XiangpengHao

**Review by XiangpengHao — APPROVED** [review]
Looks good to me, thank you @nuno-faria

**Comment by alamb** [comment]
Thanks again @nuno-faria and @XiangpengHao
