### PR TITLE
[Parquet] Improve speed of dictionary encoding NaN float values

### LINKED ISSUE #6952: Writing floating point values containing NaN to Parquet is slow when using dictionary encoding
**Describe the bug**

Writing f32 or f64 data to Parquet is a lot slower when there are many NaN values. This can be worked around by disabling dictionary encoding, but that's not always ideal.

**To Reproduce**

Example code that just writes a repeated NaN or zero value:

<details>

```rust
use arrow::array::Float32Array;
use arrow::datatypes::{DataType, Field, Schema};
use arrow::record_batch::RecordBatch;
use parquet::arrow::ArrowWriter;
use parquet::{
    basic::{Compression, ZstdLevel},
    file::properties::WriterProperties,
};

use std::fs::File;
use std::sync::Arc;
use std::time::Instant;

fn make_batch(count: usize, value: f32) -> RecordBatch {
    let schema = Arc::new(Schema::new(vec![Field::new(
        "value",
        DataType::Float32,
        false,
    )]));
    let vals = Float32Array::from(vec![value; count]);
    RecordBatch::try_new(schema, vec![Arc::new(vals)]).unwrap()
}

fn timed_write(num_rows: usize, value: f32) {
    let start = Instant::now();

    let writer_properties = WriterProperties::builder()
        .set_compression(Compression::ZSTD(ZstdLevel::try_new(3).unwrap()))
        .build();

    let batch = make_batch(num_rows, value);

    let file = File::create("data.parquet").unwrap();
    let mut writer = ArrowWriter::try_new(file, batch.schema(), Some(writer_properties)).unwrap();

    writer.write(&batch).expect("Writing batch");

    writer.close().unwrap();

    let us = start.elapsed().as_micros();
    let us_per_row = us as f64 / num_rows as f64;

    println!("value={value}, rows={num_rows}, us={us}, us/row={us_per_row}");
}

fn main() {
    let row_counts = vec![1_000, 2_000, 4_000, 8_000, 16_000, 32_000, 64_000, 128_000];

    for value in &vec![f32::NAN, 0f32] {
        for row_count in &row_counts {
            timed_write(*row_count, *value);
        }
    }
}
```

</details>

On my machine, this outputs:
```
value=NaN, rows=1000, us=1373, us/row=1.373
value=NaN, rows=2000, us=2483, us/row=1.2415                      
value=NaN, rows=4000, us=9043, us/row=2.26075                                  
value=NaN, rows=8000, us=37263, us/row=4.657875                                                                                                                
value=NaN, rows=16000, us=153460, us/row=9.59125             
value=NaN, rows=32000, us=695833, us/row=21.74478125
value=NaN, rows=64000, us=3164916, us/row=49.4518125
value=NaN, rows=128000, us=14855691, us/row=116.0600859375
value=0, rows=1000, us=8250, us/row=8.25  
value=0, rows=2000, us=122, us/row=0.061   
value=0, rows=4000, us=142, us/row=0.0355    
value=0, rows=8000, us=194, us/row=0.02425   
value=0, rows=16000, us=311, us/row=0.0194375    
value=0, rows=32000, us=512, us/row=0.016        
value=0, rows=64000, us=973, us/row=0.015203125
value=0, rows=128000, us=1724, us/row=0.01346875
```

You can see that as the number of rows increases, the time taken increases exponentially when writing NaNs, but close to linearly when writing 0.

**Expected behavior**

Writing NaNs should perform similarly to writing non-NaN floating point values.

**Additional context**

This is due to NaN == NaN being false here: https://github.com/apache/arrow-rs/blob/4f1f6e57c568fae8233ab9da7d7c7acdaea4112a/parquet/src/util/interner.rs#L69

So for each NaN value, a new entry is added to the dictionary key storage and hash table, and there will be many non-equal values in the hash table with the same hash.

Arrow C++ doesn't have this problem, as they specialise the comparison of floating point types to treat NaNs as equal to all other NaNs for hashing: https://github.com/apache/arrow/blob/5ad0b3e36f9302c4cf8dd5ab997f30bfab95e2d4/cpp/src/arrow/util/hashing.h#L132-L144

### PR DESCRIPTION
**Pull request by adamreeve**
# Which issue does this PR close?

Closes #6952

# Rationale for this change
 
This treats NaNs as equal to other NaNs of the same type for the purpose of dictionary encoding them when writing f32 or f64 Parquet physical values.

# What changes are included in this PR?

* Introduces a new `Intern` trait to define equality behaviour for interning, replacing the use of `PartialEq`.
* Adds a benchmark for writing floating point values with NaNs to Parquet.

# Are there any user-facing changes?

* Users should see improved performance when writing floating point data with many NaNs to Parquet

### CODE REVIEW

**Comment by adamreeve** [comment]
Benchmark results from the new benchmarks before changing the interning behaviour:
```
write_batch primitive/4096 values float with NaNs
                        time:   [5.6968 ms 5.7060 ms 5.7141 ms]
                        thrpt:  [9.6186 MiB/s 9.6324 MiB/s 9.6479 MiB/s]
Found 8 outliers among 100 measurements (8.00%)
  3 (3.00%) low severe
  4 (4.00%) low mild
  1 (1.00%) high mild
write_batch primitive/4096 values float with no NaNs
                        time:   [383.44 µs 383.65 µs 383.85 µs]
                        thrpt:  [143.18 MiB/s 143.26 MiB/s 143.34 MiB/s]
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```
This shows that writing with 50% NaN values is much slower than with no NaNs.

After the change, performance with NaNs is very similar to without NaNs:
```
write_batch primitive/4096 values float with NaNs
                        time:   [406.40 µs 406.63 µs 406.88 µs]
                        thrpt:  [135.08 MiB/s 135.16 MiB/s 135.24 MiB/s]
                 change:
                        time:   [-92.875% -92.861% -92.845%] (p = 0.00 < 0.05)
                        thrpt:  [+1297.6% +1300.7% +1303.5%]
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe
write_batch primitive/4096 values float with no NaNs
                        time:   [382.52 µs 384.16 µs 385.50 µs]
                        thrpt:  [142.58 MiB/s 143.07 MiB/s 143.68 MiB/s]
                 change:
                        time:   [+0.1803% +0.3520% +0.5192%] (p = 0.00 < 0.05)
                        thrpt:  [-0.5165% -0.3507% -0.1799%]
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) low severe
```

(I removed the `4096 values float with no NaNs` benchmark from this PR after running these benchmarks as I don't think there's a lot of value in keeping it)

File: parquet/src/util/interner.rs [hunk 1]
```diff
@@ -66,7 +70,7 @@ impl<S: Storage> Interner<S> {
             .dedup
             .entry(
                 hash,
-                |index| value == self.storage.get(*index),
+                |index| value.eq(self.storage.get(*index)),
```
Comment (adamreeve) [inline parquet/src/util/interner.rs:73]: Hmm, after opening this PR I realised a simpler approach would be to just compare the values by their byte representation here:
```rust
|index| value.as_bytes() == self.storage.get(*index).as_bytes()
```

I will check what effect that has on performance.

**Comment by alamb** [comment]
Thank you @adamreeve  -- is there any chance you could break out the benchmark into its own PR so it is easier to compare the before/after performance of this change?

**Review by etseidl — APPROVED** [review]
Nice catch! This seems like an elegant solution. Thanks!

**Comment by adamreeve** [comment]
> Thank you @adamreeve -- is there any chance you could break out the benchmark into its own PR so it is easier to compare the before/after performance of this change?

Sure, I've made #6955 to just add the benchmark and test, I'll make this PR a draft and rebase it once that is merged.

**Comment by adamreeve** [comment]
OK I've rebased this now and switched to comparing byte representations for all types rather than needing a new trait, which is a simpler solution and is consistent with how values are hashed. The performance was very similar between the two approaches on my machine.

**Comment by alamb** [comment]
Running benchmarks now

**Review by alamb — APPROVED** [review]
Thank you @adamreeve 

I think technically speaking this could be a behavior change as previously different Nan representations would be collapsed into a single dictionary entry, but now they will use different entries.

This actually seems like a better behavior to me as it means the parquet writer will produce exactly what went in (aka won't normalize the Nan representation)

I also ran the newly added benchmark and verified this approach appears to be much faster for NaNs (7.5x faster)

```
++ critcmp main nan-dict-encode
group                                                main                                   nan-dict-encode
-----                                                ----                                   ---------------
write_batch primitive/4096 values float with NaNs    7.53      8.3±0.09ms     6.6 MB/sec    1.00  1108.4±40.39µs    49.6 MB/sec
++ popd
~/datafusion-benchmarking
```

Thanks again

**Comment by alamb** [comment]
FYI @etseidl

**Review by tustvold — APPROVED** [review]

**Comment by adamreeve** [comment]
> I think technically speaking this could be a behavior change as previously different Nan representations would be collapsed into a single dictionary entry, but now they will use different entries.

I don't think this is true as the `NaN == NaN` test being false would have caused all NaN values to get separate entries in the dictionary, so behaviour shouldn't have changed. But it does differ from C++ Arrow which does collapse all NaNs to a single entry.

**Comment by alamb** [comment]
> > I think technically speaking this could be a behavior change as previously different Nan representations would be collapsed into a single dictionary entry, but now they will use different entries.
> 
> I don't think this is true as the `NaN == NaN` test being false would have caused all NaN values to get separate entries in the dictionary, so behaviour shouldn't have changed. But it does differ from C++ Arrow which does collapse all NaNs to a single entry.

I feel like there must be semantic difference between comparing Nans using .eq and comparing the bit patterns 🤔  

However, I suppose at this point it is just an intellectual execise 🤷

**Comment by tustvold** [comment]
> I feel like there must be semantic difference between comparing Nans using .eq and comparing the bit patterns

We generally use floating point total ordering, as described [here](https://docs.rs/arrow-ord/latest/arrow_ord/cmp/fn.gt.html). This is equivalent to byte-ordering when it comes to NaNs. As such IMO this is a bug fix.

**Comment by bkirwi** [comment]
In particular, this also fixes behaviour for negative and positive zero in floating point. Since these _do_ compare equal but have different bit representations, IIUC the old code would combine them into a single dictionary entry... but _only if they happened to hash to the same bucket. Since the hash function is randomly initialized, this was very rare, but I have observed it. (Normally the bits will hash to different buckets and they'll have separate entries in the dictionary.)

Comparing the bit representation solves this issue as well, since those are not bitwise identical and thus will reliably end up with different dict entries.

Mentioning here in case anyone else is searching for this issue. Thanks for the fix!
