### PR TITLE
arrow-select: fix MutableArrayData interleave for ListView

### LINKED ISSUE #9559: ListView interleave bug
**Describe the bug**

ListView interleave falls back to using MutableArrayData. However, the implementation does not extend the child buffers in the MutableArrayData, causing an OOB panic when trying to access a result of an interleave.

**To Reproduce**

Simple test interleaving two listviews. PR incoming.

**Expected behavior**

Correct behavior

**Additional context**

### PR DESCRIPTION
**Pull request by asubiotto**
The previous code did not extend child data buffers.

I'm preparing a PR for an optimized listview interleave, but wanted to make sure the fallback path was correct before comparing benchmarks.

# Which issue does this PR close?

- Closes #9559 
- Closes https://github.com/apache/arrow-rs/pull/9562
- https://github.com/apache/arrow-rs/issues/9561

# Rationale for this change

Fix a bug

# What changes are included in this PR?

Bugfix and test

# Are these changes tested?

Yes

# Are there any user-facing changes?

ListView interleaves did not succeed previously.

### CODE REVIEW

**Comment by asubiotto** [comment]
cc @alamb @brancz

**Comment by vegarsti** [comment]
Ha, funny timing! I have a PR for a native interleave here #9558. And I also discovered this bug yesterday 😄 #9561 My PR for this is https://github.com/apache/arrow-rs/pull/9562, but will close if/when this is merged.

**Comment by brancz** [comment]
I think I prefer https://github.com/apache/arrow-rs/pull/9562

**Comment by asubiotto** [comment]
Happy to go with whichever, my goal is to just fix this for MutableArrayData so we can compare the specialized interleave implementation fairly

**Comment by brancz** [comment]
Haha that was precisely my comment on https://github.com/apache/arrow-rs/pull/9558

**Comment by alamb** [comment]
> I think I prefer #9562

😆  I think I actually prefer this one as the behavior is "less surprising" to me

let me know what you think

File: arrow-data/src/transform/list_view.rs [hunk 1]
```diff
@@ -27,21 +27,21 @@ pub(super) fn build_extend<T: ArrowNativeType + Integer + CheckedAdd>(
...
+            for i in start..start + len {
+                let size = sizes[i].as_usize();
 
-            // sizes
-            for &size in &sizes[start..start + len] {
-                sizes_buffer.push(size);
-            }
+                mutable.buffer1.push(T::usize_as(new_offset));
+                mutable.buffer2.push(sizes[i]);
+                new_offset += size;
```
Comment (alamb) [inline arrow-data/src/transform/list_view.rs]: I think we should be using checked arithmetic here, similarly to

https://github.com/apache/arrow-rs/blob/d1ec77065c6b606bce97b7acd51b2079182822ad/arrow-data/src/transform/utils.rs#L43

Otherwise the offset could overflow when extending the list

**Review by alamb — COMMENTED** [review]
Thanks @asubiotto  (and @vegarsti and @brancz )

compared to https://github.com/apache/arrow-rs/pull/9558, for me this PR is easier to understand and more consistent with the rest of the codebase. Other than the potential offset overflow I think it looks good from my perspective.

Let me know what you think

**Comment by brancz** [comment]
Works for me, let’s go with this one.

**Comment by vegarsti** [comment]
I agree! Thanks @alamb!

File: arrow-data/src/transform/list_view.rs (hunk 1 above)
Comment (asubiotto) [reply arrow-data/src/transform/list_view.rs]: Done

**Comment by asubiotto** [comment]
Sounds good, thanks all. Addressed the overflow comment so this should be ready to merge. @vegarsti I'll let you take care of the specialized interleave

**Comment by vegarsti** [comment]
> Sounds good, thanks all. Addressed the overflow comment so this should be ready to merge. @vegarsti I'll let you take care of the specialized interleave

Nice, thanks!

**Review by alamb — APPROVED** [review]
Thank you @asubiotto @vegarsti and @brancz
