### PR TITLE
Validate ArrayData type when converting to Array (#2834)

### LINKED ISSUE #2834: Unsound ArrayData to Array Conversions
**Describe the bug**

Not all `Array` validate the `DataType` of the `ArrayData` they are being created from, which can potentially lead to unsound behaviour

**To Reproduce**

This should panic
```
#[test]
fn test_primitive_validation() {
    let foo = PrimitiveArray::<Int32Type>::from_iter([1, 2, 3]);
    PrimitiveArray::<Int64Type>::from(foo.into_data());
}
```

**Expected behavior**

All arrays should verify the type is as expected

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2834

# Rationale for this change
 

Arrays can assume that the provided ArrayData is valid, however, what that means depends on the data type of the ArrayData. We weren't always validating that the ArrayData had the expected data type, which could lead to unsoundness.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
Interestingly this is failing on timestamp casts, which is very fishy :sweat_smile:

File: arrow/src/compute/kernels/cast.rs [hunk 1]
```diff
@@ -1241,14 +1241,14 @@ pub fn cast_with_options(
...
+            let array = cast_with_options(array, &Int32, cast_options)?;
+            let time_array = as_primitive_array::<Int32Type>(array.as_ref());
             // note: (numeric_cast + SIMD multiply) is faster than (cast & multiply)
             let c: Int64Array = numeric_cast(&time_array);
             let from_size = time_unit_multiple(from_unit);
             let to_size = time_unit_multiple(to_unit);
             // from is only smaller than to if 64milli/64second don't exist
-            let mult = Int64Array::from(vec![to_size / from_size; array.len()]);
-            let converted = multiply(&c, &mult)?;
+            let converted = multiply_scalar(&c, to_size / from_size)?;
```
Comment (tustvold) [inline arrow/src/compute/kernels/cast.rs:1251]: Drive by cleanup

File: arrow-array/src/array/boolean_array.rs [hunk 2]
```diff
@@ -201,6 +201,13 @@ impl From<Vec<Option<bool>>> for BooleanArray {
 
 impl From<ArrayData> for BooleanArray {
     fn from(data: ArrayData) -> Self {
+        assert_eq!(
+            data.data_type(),
+            &DataType::Boolean,
+            "BooleanArray expected ArrayData with type {} got {}",
```
Comment (alamb) [inline arrow-array/src/array/boolean_array.rs:207]: 👍

File: parquet/src/arrow/array_reader/primitive_array.rs [hunk 3]
```diff
@@ -169,15 +170,21 @@ where
...
-            PhysicalType::INT64 => Arc::new(Int64Array::from(array_data)) as ArrayRef,
-            PhysicalType::FLOAT => Arc::new(Float32Array::from(array_data)) as ArrayRef,
-            PhysicalType::DOUBLE => Arc::new(Float64Array::from(array_data)) as ArrayRef,
-            PhysicalType::INT96 => {
-                Arc::new(TimestampNanosecondArray::from(array_data)) as ArrayRef
-            }
+        let array: ArrayRef = match T::get_physical_type() {
+            PhysicalType::BOOLEAN => Arc::new(BooleanArray::from(array_data)),
+            PhysicalType::INT32 => match array_data.data_type() {
+                ArrowType::UInt32 => Arc::new(UInt32Array::from(array_data)),
```
Comment (alamb) [inline parquet/src/arrow/array_reader/primitive_array.rs:176]: is this a bug fix? Seems like a good improvement to me

**Review by alamb — APPROVED** [review]
Very nice -- 💯  for the tests 🏆

File: parquet/src/arrow/array_reader/primitive_array.rs (hunk 3 above)
Comment (tustvold) [reply parquet/src/arrow/array_reader/primitive_array.rs:176]: Sort of, it doesn't actually matter as the PrimitiveArray is discarded by the parent StructArrayReader, which is only concerned with the ArrayData portion

Comment (alamb) [reply parquet/src/arrow/array_reader/primitive_array.rs:176]: I guess I was wondering "what is the rationale for this change"

Comment (tustvold) [reply parquet/src/arrow/array_reader/primitive_array.rs:176]: Oh, because now it would panic complaining that it was creating an Int32Array from DataType::UInt32 ArrayData.

**Comment by tustvold** [comment]
Parquet failure does not appear to relate to this PR
