### PR TITLE
Fix decimal repr in parquet schema printer

### LINKED ISSUE #713: Decimal logical type is formatted incorrectly by print_schema
**Describe the bug**
When printing out the schema of a parquet file (written by Spark) using Java implementation of `parquet-schema` I get:
```gql
message spark_schema {
  optional fixed_len_byte_array(9) price_usd (DECIMAL(19,4));
  ...
}
```
But when I use `parquet::schema::printer::print_schema` I get:
```gql
message spark_schema {
  OPTIONAL FIXED_LEN_BYTE_ARRAY (9) price_usd (DECIMAL4, 19);
  ...
}
```
Issues:
* The missing opening bracket (minor)
* The inversed order of precision and scale

Parquet spec doesn't seem to describe the textual representation of schema, and in Thrift file the order is [scale, precision](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L254-L255) but in SQL representation of DECIMAL (which Java implementation seems to be following) the order is `precision{, scale}`.

**To Reproduce**
Use `print_schema` on a Parquet file containing decimals.

**Expected behavior**
Logical type is correctly formatted and follows conventional style `DECIMAL(precision, scale)`

### PR DESCRIPTION
**Pull request by sergiimk**
# Which issue does this PR close?

Closes #713.

# Rationale for this change
 
 

Formatting of `DECIMAL` in schemas where only `ConvertedType` is present and not `LogicalType` was broken. 
This is the case for parquet files produced by Spark.

# What changes are included in this PR?

I also had to update `decimal_length_from_precision` function as the math there seemed off. 
When used as `.with_length(decimal_length_from_precision(19))` it resulted in a panic:
```
Cannot represent FIXED_LEN_BYTE_ARRAY as DECIMAL with length 8 and precision 19. The max precision can only be 18
```

# Are there any user-facing changes?
`print_schema` will no longer produce malformed results for decimals.

### CODE REVIEW

File: parquet/src/schema/printer.rs [hunk 1]
```diff
@@ -630,6 +633,20 @@ mod tests {
...
+                    PhysicalType::FIXED_LEN_BYTE_ARRAY,
+                )
+                .with_converted_type(ConvertedType::DECIMAL)
+                .with_precision(19)
+                .with_scale(4)
+                .with_length(decimal_length_from_precision(19))
+                .with_repetition(Repetition::OPTIONAL)
+                .build()
+                .unwrap(),
+                "OPTIONAL FIXED_LEN_BYTE_ARRAY (9) decimal (DECIMAL(19,4));",
```
Comment (alamb) [inline parquet/src/schema/printer.rs:648]: In case anyone is interested, I double checked that test fails  without the code change in this PR (unsurprisingly):

```

---- schema::printer::tests::test_print_flba_logical_types stdout ----
thread 'schema::printer::tests::test_print_flba_logical_types' panicked at 'called `Result::unwrap()` on an `Err` value: General("Cannot represent FIXED_LEN_BYTE_ARRAY as DECIMAL with length 8 and precision 19. The max precision can only be 18")', parquet/src/schema/printer.rs:644:18
```

**Review by alamb — APPROVED** [review]
Thank you for the contribution @sergiimk ! I can't say I am an expert in this area of the parquet but the test looks good so given CI passes, looks good to me

@sunchao FYI
