### PR TITLE
bugfix: correct offsets when serializing a list of fixed sized list and non-zero start offset

### LINKED ISSUE #7315: Round trip encoding of list of fixed list fails when offset is not zero
**Describe the bug**

If you have a List of FixedList and the top level list has an offset that is not zero, the encoded array contains the wrong values in the fixed list. See the example below to illustrate the problem.

**To Reproduce**

Add the following test within `arrow-ipc/src/writer.rs` test module:

```rust

    #[test]
    fn test_roundtrip_list_of_fixed_list() -> Result<(), ArrowError> {

        let l0_builder = Float32Builder::new();
        let l1_builder = FixedSizeListBuilder::new(l0_builder, 3);
        let mut l2_builder = ListBuilder::new(l1_builder);

        for point in [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]] {
            l2_builder.values().values().append_value(point[0]);
            l2_builder.values().values().append_value(point[1]);
            l2_builder.values().values().append_value(point[2]);

            l2_builder.values().append(true);
        }
        l2_builder.append(true);

        for point in [[10., 11., 12.]] {
            l2_builder.values().values().append_value(point[0]);
            l2_builder.values().values().append_value(point[1]);
            l2_builder.values().values().append_value(point[2]);

            l2_builder.values().append(true);
        }
        l2_builder.append(true);

        let array = Arc::new(l2_builder.finish()) as ArrayRef;

        let schema = Arc::new(Schema::new_with_metadata(
            vec![Field::new(
                "points",
                DataType::List(Arc::new(Field::new(
                    "item",
                    DataType::FixedSizeList(
                        Arc::new(Field::new("item", DataType::Float32, true)),
                        3,
                    ),
                    true,
                ))),
                true,
            )],
            HashMap::default(),
        ));

        let subarray_1 = array.slice(0, 1);
        let subarray_2 = array.slice(1, 1);

        let b1 = RecordBatch::try_new(schema.clone(), vec![subarray_1])?;
        let b2 = RecordBatch::try_new(schema.clone(), vec![subarray_2])?;

        let mut bytes = Vec::new();
        let mut writer = StreamWriter::try_new(&mut bytes, &schema)?;
        writer.write(&b1)?;
        writer.finish()?;

        let mut cursor = std::io::Cursor::new(bytes);
        let mut reader = StreamReader::try_new(&mut cursor, None)?;
        let b1_return = reader.next().unwrap()?;

        assert_eq!(b1, b1_return);

        let mut bytes = Vec::new();
        let mut writer = StreamWriter::try_new(&mut bytes, &schema)?;
        writer.write(&b2)?;
        writer.finish()?;

        let mut cursor = std::io::Cursor::new(bytes);
        let mut reader = StreamReader::try_new(&mut cursor, None)?;
        let b2_return = reader.next().unwrap()?;

        assert_eq!(b2, b2_return);

        Ok(())
    }
```

**Expected behavior**

Returned deserialized arrow array should match serialized.

**Additional context**

This is probably related to #6805

### PR DESCRIPTION
**Pull request by timsaucer**
# Which issue does this PR close?

- Closes #7315.

# Rationale for this change
 
This bug occurs when these conditions are all met:

- We have a generic list of fixed size list
- The offset of the outer generic list is non-zero
- We writing out (serializing) the arrays

# What changes are included in this PR?

This PR checks for the case of a fixed sized list and adjusts the offsets to the child arrays during write.

Unit tests added.

# Are there any user-facing changes?

None

### CODE REVIEW

File: arrow-ipc/src/writer.rs [hunk 1]
```diff
@@ -3075,4 +3098,111 @@ mod tests {
         assert_eq!(stream_bytes_written_on_flush, expected_stream_flushed_bytes);
         assert_eq!(file_bytes_written_on_flush, expected_file_flushed_bytes);
     }
+
+    #[test]
+    fn test_roundtrip_list_of_fixed_list() -> Result<(), ArrowError> {
```
Comment (alamb) [inline arrow-ipc/src/writer.rs:3103]: I verified that this test fails without the code in this PR

```shell

assertion `left == right` failed
  left: RecordBatch { schema: Schema { fields: [Field { name: "points", data_type: List(Field { name: "item", data_type: FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 3), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }, columns: [ListArray
[
  FixedSizeListArray<3>
[
  PrimitiveArray<Float32>
[
  10.0,
  11.0,
  12.0,
],
],
]], row_count: 1 }
 right: RecordBatch { schema: Schema { fields: [Field { name: "points", data_type: List(Field { name: "item", data_type: FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 3), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }, columns: [ListArray
[
  FixedSizeListArray<3>
[
  PrimitiveArray<Float32>
[
  1.0,
  2.0,
  3.0,
],
],
]], row_count: 1 }

<Click to see difference>

thread 'writer::tests::test_roundtrip_list_of_fixed_list' panicked at arrow-ipc/src/writer.rs:3150:9:
assertion `left == right` failed
  left: RecordBatch { schema: Schema { fields: [Field { name: "points", data_type: List(Field { name: "item", data_type: FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 3), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }, columns: [ListArray
[
  FixedSizeListArray<3>
[
  PrimitiveArray<Float32>
[
  10.0,
  11.0,
  12.0,
],
],
]], row_count: 1 }
 right: RecordBatch { schema: Schema { fields: [Field { name: "points", data_type: List(Field { name: "item", data_type: FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 3), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }, columns: [ListArray
[
  FixedSizeListArray<3>
[
  PrimitiveArray<Float32>
[
  1.0,
  2.0,
  3.0,
],
],
]], row_count: 1 }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:692:5
   1: core::panicking::panic_fmt
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/panicking.rs:75:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:364:5
   4: arrow_ipc::writer::tests::test_subarray
             at ./src/writer.rs:3150:9
   5: arrow_ipc::writer::tests::test_roundtrip_list_of_fixed_list
             at ./src/writer.rs:3127:9
   6: arrow_ipc::writer::tests::test_roundtrip_list_of_fixed_list::{{closure}}
             at ./src/writer.rs:3083:47
   7: core::ops::function::FnOnce::call_once
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

File: arrow-ipc/src/writer.rs [hunk 2]
```diff
@@ -3075,4 +3098,111 @@ mod tests {
...
+        // Test a variety of combinations that include 0 and non-zero offsets
+        // and also portions or the rest of the array
+        test_subarray(&array, &schema, 0, 1)?;
+        test_subarray(&array, &schema, 0, 2)?;
+        test_subarray(&array, &schema, 1, 1)?;
+
+        Ok(())
+    }
+
+    fn test_subarray(
```
Comment (alamb) [inline arrow-ipc/src/writer.rs:3152]: Minor nit is I would call this "test_slices" as it is testing sliced arrays

```suggestion
    fn test_slices(
```

File: arrow-ipc/src/writer.rs [hunk 3]
```diff
@@ -3075,4 +3098,111 @@ mod tests {
...
         assert_eq!(file_bytes_written_on_flush, expected_file_flushed_bytes);
     }
+
+    #[test]
+    fn test_roundtrip_list_of_fixed_list() -> Result<(), ArrowError> {
+        let l0_builder = Float32Builder::new();
+        let l1_builder = FixedSizeListBuilder::new(l0_builder, 3);
+        let mut l2_builder = ListBuilder::new(l1_builder);
+
+        for point in [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]] {
```
Comment (alamb) [inline arrow-ipc/src/writer.rs:3108]: Can you also add a test case that has nulls too? Like `4.0, NULL, 5.0` ? Maybe as a different test case

**Review by alamb — APPROVED** [review]
Thank you @timsaucer  -- this looks great to me

I think it would be better with a test for nullable data as well (to make sure the nulls are sliced correctly) but in my opinion this PR is better than what is on `main` so it could be merged in as is as well

I had some small other comments, but nothing required in my opinion

File: arrow-ipc/src/writer.rs (hunk 2 above)
Comment (timsaucer) [reply arrow-ipc/src/writer.rs]: Changed in latest push.

File: arrow-ipc/src/writer.rs (hunk 3 above)
Comment (timsaucer) [reply arrow-ipc/src/writer.rs:3108]: Added in latest push

**Comment by timsaucer** [comment]
Thanks @alamb . I've added the requested changes. I appreciate the rapid response.

**Comment by timsaucer** [comment]
Ah, I don't have merge approval for this repository since I'm not a committer on Arrow.

File: arrow-ipc/src/writer.rs [hunk 4]
```diff
@@ -3075,4 +3098,171 @@ mod tests {
...
+        let point = [Some(10.), None, None];
+        for p in point {
+            match p {
+                Some(p) => l2_builder.values().values().append_value(p),
+                None => l2_builder.values().values().append_null(),
+            }
+        }
+
+        l2_builder.values().append(true);
+        l2_builder.append(true);
```
Comment (viirya) [inline arrow-ipc/src/writer.rs:3183]: Hmm, I wonder why this point `[Some(10.), None, None]` needs to be separately appended? Cannot it be in the above loop too?

File: arrow-ipc/src/writer.rs [hunk 5]
```diff
@@ -3075,4 +3098,171 @@ mod tests {
...
+                "points",
+                DataType::List(Arc::new(Field::new(
+                    "item",
+                    DataType::FixedSizeList(
+                        Arc::new(Field::new("item", DataType::Float32, true)),
+                        3,
+                    ),
+                    true,
+                ))),
+                true,
```
Comment (viirya) [inline arrow-ipc/src/writer.rs:3138]: Looks like these values are not nullable? Maybe update the schema?

File: arrow-ipc/src/writer.rs [hunk 6]
```diff
@@ -3075,4 +3098,171 @@ mod tests {
...
+        let mut reader = StreamReader::try_new(&mut cursor, None)?;
+        let returned_batch = reader.next().unwrap()?;
+
+        assert_eq!(original_batch, returned_batch);
+
+        Ok(())
+    }
+
+    #[test]
+    fn test_roundtrip_fixed_list() -> Result<(), ArrowError> {
```
Comment (viirya) [inline arrow-ipc/src/writer.rs:3236]: Can we add another test with null value too?

File: arrow-ipc/src/writer.rs [hunk 7]
```diff
@@ -3075,4 +3098,171 @@ mod tests {
...
+            fixed_list_builder.append(true);
+        }
+
+        let array = Arc::new(fixed_list_builder.finish()) as ArrayRef;
+
+        let schema = Arc::new(Schema::new_with_metadata(
+            vec![Field::new(
+                "points",
+                DataType::FixedSizeList(Arc::new(Field::new("item", DataType::Int64, true)), 3),
+                true,
```
Comment (viirya) [inline arrow-ipc/src/writer.rs:3254]: There are no null values. Maybe update the schema to non-nullable?

**Review by viirya — APPROVED** [review]

File: arrow-ipc/src/writer.rs (hunk 4 above)
Comment (timsaucer) [reply arrow-ipc/src/writer.rs:3183]: To make this entry a different row of the outer list.

File: arrow-ipc/src/writer.rs (hunk 7 above)
Comment (timsaucer) [reply arrow-ipc/src/writer.rs:3295]: Updated unit test

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Thanks @timsaucer @alamb

**Comment by emilk** [comment]
I would very much like to see this in a bugfix release 🙏

**Comment by alamb** [comment]
> I would very much like to see this in a bugfix release 🙏

Thanks, i filed a ticket to track the idea. @timsaucer  also was interested I think 
- https://github.com/apache/arrow-rs/issues/7330
-
