### PR TITLE
fix NaN handling in parquet statistics

### LINKED ISSUE #225: Add support for writing sliced arrays
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-8424

The initial Parquet writer does not consider array offsets. This is to ensure that we add tests for offsets

### LINKED ISSUE #255: NaNs can break parquet statistics
**Describe the bug**
NaN can occur in parquet statistics and override all other possible values. This is very similar to [PARQUET-1225](https://issues.apache.org/jira/browse/PARQUET-1225) which was filed for the C++ implementation.

**To Reproduce**
Add the following tests:

```rust
#[test]
fn test_float_statistics_nan_middle() {
    let stats = statistics_roundtrip::<FloatType>(&[1.0, f32::NAN, 2.0]);
    assert!(stats.has_min_max_set());
    if let Statistics::Float(stats) = stats {
        assert_eq!(stats.min(), &1.0);
        assert_eq!(stats.max(), &2.0);
    } else {
        panic!("expecting Statistics::Float");
    }
}

#[test]
fn test_float_statistics_nan_start() {
    let stats = statistics_roundtrip::<FloatType>(&[f32::NAN, 1.0, 2.0]);
    assert!(stats.has_min_max_set());
    if let Statistics::Float(stats) = stats {
        assert_eq!(stats.min(), &1.0);
        assert_eq!(stats.max(), &2.0);
    } else {
        panic!("expecting Statistics::Float");
    }
}

#[test]
fn test_float_statistics_nan_only() {
    let stats = statistics_roundtrip::<FloatType>(&[f32::NAN, f32::NAN]);
    assert!(!stats.has_min_max_set());
    assert!(matches!(stats, Statistics::Float(_)));
}

fn statistics_roundtrip<T: DataType>(values: &[<T as DataType>::T]) -> Statistics {
    let page_writer = get_test_page_writer();
    let props = Arc::new(WriterProperties::builder().build());
    let mut writer = get_test_column_writer::<T>(page_writer, 0, 0, props);
    writer.write_batch(values, None, None).unwrap();

    let (_bytes_written, _rows_written, metadata) = writer.close().unwrap();
    if let Some(stats) = metadata.statistics() {
        stats.clone()
    } else {
        panic!("metadata missing statistics");
    }
}
```

**Note that while the tests are written for `f32`/float, this also applies to `f64`/double.**

**Expected behavior**
NaNs should be ignored during stats calculation. If only NaNs are present then min and max value should be unset.

**Additional context**
Tested commit was `8f030db53d9eda901c82db9daf94339fc447d0db`.

### PR DESCRIPTION
**Pull request by crepererum**
# Which issue does this PR close?
Closes #255.

 # Rationale for this change
Fixes NaN handling in parquet statistics. This is in line with the C++ stack:

https://github.com/apache/arrow/blob/b3e43987c47b2f01b204a2d954f882f7161616ef/cpp/src/parquet/statistics_test.cc#L1000-L1043

# What changes are included in this PR?
Filter out NaN values from statistics + tests.

# Are there any user-facing changes?
Yes: formally NaN were included in the stats but at "random" (i.e. when the data started with an NaN than the min/max values are NaN, otherwise min/max are non-NaN). Now the behavior is: NaN are excluded always. If the only NaN values are present, then min/max are unset.

### CODE REVIEW

File: parquet/src/column/writer.rs [hunk 1]
```diff
@@ -922,11 +922,14 @@ impl<T: DataType> ColumnWriterImpl<T> {
     }
 
     fn update_page_min_max(&mut self, val: &T::T) {
-        if self.min_page_value.as_ref().map_or(true, |min| min > val) {
-            self.min_page_value = Some(val.clone());
-        }
-        if self.max_page_value.as_ref().map_or(true, |max| max < val) {
-            self.max_page_value = Some(val.clone());
+        // simple "isNaN" check that works for all types
+        if val == val {
```
Comment (crepererum) [inline parquet/src/column/writer.rs:926]: Should we introduce some generic `T::is_nan` function into the data type abstraction layer (that basically returns `False` for every non-float/double type and calls `.is_nan()` for float/double) or is this local workaround good enough?

**Comment by alamb** [comment]
I believe this fixes #255 rather than #225 so I updated the description accordingly

**Review by alamb — APPROVED** [review]
The change (and tests) look really good to me. @sunchao  or @nevi-me  do you have any thoughts?

**Comment by alamb** [comment]
Thanks @crepererum !

File: parquet/src/column/writer.rs (hunk 1 above)
Comment (nevi-me) [reply parquet/src/column/writer.rs:927]: I don't think that's necessary. It'll just be adding overhead for us.

The compiler can figure out what we're trying to do, and will optimise out the branch for anything that's not a floating point number.

Look at this example: https://godbolt.org/z/z7M3Mfqzz

The `is_nan::<i32>()` always returns `false`, and the `ucomisd` does the floating point comparison

**Review by nevi-me — APPROVED** [review]
LGTM
