### PR TITLE
Fix "Incorrect Behavior of Collecting a filtered iterator to a BooleanArray"

### LINKED ISSUE #8505: Incorrect Behavior of Collecting a filtered iterator to a BooleanArray
**Describe the bug**

Collecting to a `BooleanArray` produces unintuitive results if the upper bound of the iterator is an over estimation. At least I think after looking at the code.

Is this intended behavior? If not, I could try to come up with a fix.

**To Reproduce**

Tested with Arrow v56.2.0 (via DataFusion 50)

The following test reproduces this:

```rust
    #[test]
    fn test_boolean_array_from() {
        let values = vec![Some(true), None, Some(true), Some(false)]
            .into_iter()
            .filter(Option::is_some)
            .collect::<BooleanArray>();
        assert_debug_snapshot!(values, @r"
        BooleanArray
        [
          true,
          true,
          false,
          null,
        ]
        ")
    }
```

**Expected behavior**

I'd have expected the following Array (without the null):

```
        BooleanArray
        [
          true,
          true,
          false,
        ]
```

**Additional context**

The result of the "same" operation on an Int64Array:

```rust
    #[test]
    fn test_int64_array_from() {
        let values = vec![Some(1), None, Some(2), Some(3)]
            .into_iter()
            .filter(Option::is_some)
            .collect::<Int64Array>();
        assert_debug_snapshot!(values, @r"
        PrimitiveArray<Int64>
        [
          1,
          2,
          3,
        ]
        ")
    }
```

### PR DESCRIPTION
**Pull request by tobixdev**
# Which issue does this PR close?

- Closes #8505 .

# Rationale for this change

Fix the bug and align `BooleanArray::from_iter` to `PrimitiveArray::from_iter`

In `BooleanArray::from_iter`:
Collecting to a `Vec` and then using `from_trusted_len_iter` was almost double as fast as using `BooleanBufferBuilder` on my machine.

# What changes are included in this PR?

- Use builders in `BooleanArray::from_iter` to fix the wrong behavior
- Introduce `BooleanArray::from_trusted_len_iter` for a more performant version (The old version of `BooleanArray::from_iter`, just with unsafe flavor of `bit_util::set_bit_raw`)
- Add `BooleanAdapter`, inspired by `NativeAdapter` from the `PrimitiveArray`. This allows also doing `BooleanArray::from_iter([true, false].into_iter())`. 

# Are these changes tested?

- New test to cover the initial bug 
- New test to cover `BooleanArray::from_trusted_len_iter` directly (old `BooleanArray::from_iter` also cover it indirectly)
- New test to document that you can directly collect `[false, true, ...]` (no `Option`)

# Are there any user-facing changes?

- `BooleanArray::from_iter` has a "slight" performance regression that users could observe.
- Allow directly collecting bools to a `BooleanArray`
- `BooleanArray::from_trusted_len_iter`

### CODE REVIEW

**Comment by tschwarzinger** [comment]
@alamb Could you run the `array_from` benchmarks? Thanks!

File: arrow-array/src/array/boolean_array.rs [hunk 1]
```diff
@@ -436,11 +436,78 @@ impl<'a> BooleanArray {
...
+    #[inline]
+    pub unsafe fn from_trusted_len_iter<I, P>(iter: I) -> Self
+    where
+        P: Into<BooleanAdapter>,
+        I: IntoIterator<Item = P>,
+    {
         let iter = iter.into_iter();
         let (_, data_len) = iter.size_hint();
-        let data_len = data_len.expect("Iterator must be sized"); // panic if no upper bound.
+        let data_len = data_len.expect("Iterator must be sized");
```
Comment (mbrobbel) [inline arrow-array/src/array/boolean_array.rs]: Maybe we can use the stable https://doc.rust-lang.org/std/iter/trait.ExactSizeIterator.html as bound?

File: arrow-array/src/array/boolean_array.rs [hunk 2]
```diff
@@ -436,11 +436,78 @@ impl<'a> BooleanArray {
...
+/// An optional boolean value
+///
+/// This struct is used as an adapter when creating `BooleanArray` from an iterator.
+/// `FromIterator` for `BooleanArray` takes an iterator where the elements can be `into`
+/// this struct. So once implementing `From` or `Into` trait for a type, an iterator of
+/// the type can be collected to `BooleanArray`.
+///
+/// See also [NativeAdapter](crate::array::NativeAdapter).
+#[derive(Debug)]
+pub struct BooleanAdapter {
```
Comment (mbrobbel) [inline arrow-array/src/array/boolean_array.rs]: I think we can avoid exposing this?
```suggestion
struct BooleanAdapter {
```

**Review by mbrobbel — COMMENTED** [review]
On my M1 Pro:
```
BooleanArray::from_iter
[26.169 µs 26.194 µs 26.222 µs]

BooleanArray::from_trusted_len_iter
[9.6375 µs 9.6519 µs 9.6659 µs]
```

File: arrow-array/src/array/boolean_array.rs (hunk 1 above)
Comment (tschwarzinger) [reply arrow-array/src/array/boolean_array.rs]: > Note that this trait is a safe trait and as such does not and cannot guarantee that the returned length is correct. This means that unsafe code must not rely on the correctness of [Iterator::size_hint](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint). The unstable and unsafe [TrustedLen](https://doc.rust-lang.org/std/iter/trait.TrustedLen.html) trait gives this additional guarantee.

We still can't make it a safe function but it could help in conveying the message.

Should we also change it for the `PrimitiveArray`?

File: arrow-array/src/array/boolean_array.rs (hunk 2 above)
Comment (tschwarzinger) [reply arrow-array/src/array/boolean_array.rs]: I followed the approach from `PrimitiveArray`, which also exposes `NativeAdapter`.

I think the rationale behind this is that users can implement `impl From<MyBoolNewType> for BooleanAdapter` in their crate which would allow collecting `MyBoolNewType` to a `BooleanArray`.

**Comment by tschwarzinger** [comment]
> On my M1 Pro:
> 
> ```
> BooleanArray::from_iter
> [26.169 µs 26.194 µs 26.222 µs]
> 
> BooleanArray::from_trusted_len_iter
> [9.6375 µs 9.6519 µs 9.6659 µs]
> ```

@mbrobbel Thanks for the review and running the benchmarks! Interessting how the performance differs on an ARM chip. Here are my numbers (Ryzen 3900X). 

```
BooleanArray::from_iter time:   [16.047 µs 16.097 µs 16.154 µs]
BooleanArray::from_trusted_len_iter:   [13.108 µs 13.140 µs 13.176 µs]
```

File: arrow-array/src/array/boolean_array.rs (hunk 1 above)
Comment (mbrobbel) [reply arrow-array/src/array/boolean_array.rs]: > We still can't make it a safe function but it could help in conveying the message.

Yes, and we can call `.len()` instead of using the upper bound of the size hint.

> Should we also change it for the PrimitiveArray?

We could do that in a different PR.

File: arrow-array/src/array/boolean_array.rs (hunk 2 above)
Comment (mbrobbel) [reply arrow-array/src/array/boolean_array.rs]: I would avoid exposing it until someone needs it, but that's just my preference, not a strong opinion.

**Comment by jhorstmann** [comment]
I think the benchmark results for `from_iter` might be a bit overly optimistic, the input in the benchmark seems to be already be in an `Vec<Option<bool>>`, the rust compiler would be able to optimize the intermediate vector allocation away. The performance for an arbitrary iterator might be worse. An implementation using the existing `BooleanBuilder` might be preferrable for the generic case, and users with an trusted iterator implementation should be directed to the new `unsafe` implementation.

```rust
impl<Ptr: std::borrow::Borrow<Option<bool>>> FromIterator<Ptr> for BooleanArray {
    fn from_iter<I: IntoIterator<Item = Ptr>>(iter: I) -> Self {
        let iter = iter.into_iter();
        let capacity = match iter.size_hint() {
            (lower, Some(upper)) if lower == upper => lower,
            _ => 0
        };
        let mut builder = BooleanBuilder::with_capacity(capacity);
        builder.extend(iter.map(|item| *item.borrow()));
        builder.finish()
    }
}
```

This is probably much slower than the current incorrect implementation, but any optimizations to `BooleanBuilder` would then also apply to this implementation.

**Comment by tschwarzinger** [comment]
@jhorstmann Thanks for your input. That was a flaw in my benchmarks you're right. I've adapted them to now use a `Box<dyn Iterator>`, such that we can hide the "iterator type information" from the compiler (at least I think). I think this also better captures the use case.

I really like the idea of re-using `BooleanBuilder`. However, collecting to a `Vec` and then using `from_trusted_len_iter` is more efficient on my machine at least (at the cost of allocating a `Vec`). What if we move this into the `Extend` implementation of the `BooleanBuilder`?

I've adapted the implementation so you can take a look.

**Comment by tschwarzinger** [comment]
With the new `Extend`:

```
BooleanArray::from_iter:   [46.030 µs 46.107 µs 46.196 µs]
BooleanArray::from_trusted_len_iter:   [39.073 µs 39.508 µs 39.973 µs]
```

With the old `Extend`:

```
BooleanArray::from_iter:   [76.143 µs 76.189 µs 76.247 µs]
BooleanArray::from_trusted_len_iter:   [40.139 µs 40.358 µs 40.620 µs]
```

File: arrow-array/src/array/boolean_array.rs (hunk 1 above)
Comment (tschwarzinger) [reply arrow-array/src/array/boolean_array.rs]: https://github.com/apache/arrow-rs/pull/8543/commits/36a2fac85fa79802a62bfa494c540af2bc4d104d

File: arrow-array/src/array/boolean_array.rs (hunk 2 above)
Comment (tschwarzinger) [reply arrow-array/src/array/boolean_array.rs]: https://github.com/apache/arrow-rs/pull/8543/commits/00c95d5ff5bfa8fcec4320b99e06563a293bde59

File: arrow-array/src/array/boolean_array.rs (hunk 1 above)
Comment (tschwarzinger) [reply arrow-array/src/array/boolean_array.rs]: Maybe I am doing something wrong. But somehow I get performance regressions when doing this switch. 

On the last commit (`78700b41c92e2fe00226dc7aa11682300e239119`). This reverts this change.

```
BooleanArray::from_iter time:   [45.610 µs 45.644 µs 45.683 µs]
BooleanArray::from_trusted_len_iter: [38.812 µs 39.013 µs 39.227 µs]
```

On the second to last commit (`4ef2ef231d733925c548f096b760e66ec72356c6`)

```
BooleanArray::from_iter:   [52.602 µs 52.630 µs 52.662 µs]
BooleanArray::from_trusted_len_iter:   [40.087 µs 40.244 µs 40.410 µs]
```

Could you maybe run these two versions on your machine? I find this difference very weird as, AFAIK, both versions should be monomorphized .

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1016-gcp #17~24.04.1-Ubuntu SMP Wed Sep  3 01:55:36 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing 8505-fix-from-iter (9ba0eebeebeef5e0e661926f631373587523fdcb) to f88921cb04d8dfdf3ed3f0c7d05b5065d124fc6b [diff](https://github.com/apache/arrow-rs/compare/f88921cb04d8dfdf3ed3f0c7d05b5065d124fc6b..9ba0eebeebeef5e0e661926f631373587523fdcb)
BENCH_NAME=array_from
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench array_from 
BENCH_FILTER=
BENCH_BRANCH_NAME=8505-fix-from-iter
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                  8505-fix-from-iter                     main
-----                                  ------------------                     ----
BooleanArray::from_iter                3.01     59.1±0.51µs        ? ?/sec    1.00     19.6±0.08µs        ? ?/sec
BooleanArray::from_trusted_len_iter    1.00     40.0±0.12µs        ? ?/sec  
Int64Array::from_iter                  2.29     91.4±0.80µs        ? ?/sec    1.00     39.9±0.08µs        ? ?/sec
Int64Array::from_trusted_len_iter      2.77     52.4±0.46µs        ? ?/sec    1.00     18.9±0.03µs        ? ?/sec
array_from_vec 128                     1.00    156.7±0.26ns        ? ?/sec    1.01    158.0±0.35ns        ? ?/sec
array_from_vec 256                     1.00    165.5±0.33ns        ? ?/sec    1.00    165.9±0.33ns        ? ?/sec
array_from_vec 512                     1.00    223.0±0.53ns        ? ?/sec    1.00    223.6±0.86ns        ? ?/sec
array_string_from_vec 128              1.00   1249.3±1.66ns        ? ?/sec    1.00   1254.3±4.35ns        ? ?/sec
array_string_from_vec 256              1.00  1985.8±21.82ns        ? ?/sec    1.03      2.0±0.00µs        ? ?/sec
array_string_from_vec 512              1.00      3.5±0.03µs        ? ?/sec    1.01      3.5±0.00µs        ? ?/sec
decimal128_array_from_vec 32768        1.00     98.9±1.26µs        ? ?/sec    1.00     99.3±0.26µs        ? ?/sec
decimal256_array_from_vec 32768        1.00      3.8±0.03µs        ? ?/sec    1.02      3.9±0.02µs        ? ?/sec
decimal32_array_from_vec 32768         1.01     86.0±0.23µs        ? ?/sec    1.00     85.5±0.15µs        ? ?/sec
decimal64_array_from_vec 32768         1.00     90.8±0.40µs        ? ?/sec    1.00     90.9±0.15µs        ? ?/sec
struct_array_from_vec 1024             1.00      8.5±0.03µs        ? ?/sec    1.05      8.9±0.02µs        ? ?/sec
struct_array_from_vec 128              1.00   1836.0±8.72ns        ? ?/sec    1.04   1914.3±5.43ns        ? ?/sec
struct_array_from_vec 256              1.00      2.7±0.03µs        ? ?/sec    1.08      2.9±0.01µs        ? ?/sec
struct_array_from_vec 512              1.00      4.5±0.05µs        ? ?/sec    1.08      4.9±0.01µs        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
🤔  The only one that looks suspicious is Int64Array::from_trusted_len_ter getting significantly slower

I will rerun to double check

```
Int64Array::from_trusted_len_iter      2.77     52.4±0.46µs        ? ?/sec    1.00     18.9±0.03µs        ? ?/sec
```

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1016-gcp #17~24.04.1-Ubuntu SMP Wed Sep  3 01:55:36 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing 8505-fix-from-iter (9ba0eebeebeef5e0e661926f631373587523fdcb) to f88921cb04d8dfdf3ed3f0c7d05b5065d124fc6b [diff](https://github.com/apache/arrow-rs/compare/f88921cb04d8dfdf3ed3f0c7d05b5065d124fc6b..9ba0eebeebeef5e0e661926f631373587523fdcb)
BENCH_NAME=array_from
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench array_from 
BENCH_FILTER=
BENCH_BRANCH_NAME=8505-fix-from-iter
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                  8505-fix-from-iter                     main
-----                                  ------------------                     ----
BooleanArray::from_iter                3.01     59.1±0.38µs        ? ?/sec    1.00     19.6±0.03µs        ? ?/sec
BooleanArray::from_trusted_len_iter    1.00     40.0±0.03µs        ? ?/sec  
Int64Array::from_iter                  2.29     91.4±0.21µs        ? ?/sec    1.00     40.0±0.09µs        ? ?/sec
Int64Array::from_trusted_len_iter      2.78     52.5±0.34µs        ? ?/sec    1.00     18.9±0.04µs        ? ?/sec
array_from_vec 128                     1.00    162.1±0.51ns        ? ?/sec    1.06    171.7±0.28ns        ? ?/sec
array_from_vec 256                     1.00    169.9±0.39ns        ? ?/sec    1.05    179.2±0.16ns        ? ?/sec
array_from_vec 512                     1.00    228.2±0.57ns        ? ?/sec    1.04    237.8±0.28ns        ? ?/sec
array_string_from_vec 128              1.00   1256.8±3.36ns        ? ?/sec    1.00   1252.9±1.49ns        ? ?/sec
array_string_from_vec 256              1.00   1985.9±4.60ns        ? ?/sec    1.03      2.0±0.00µs        ? ?/sec
array_string_from_vec 512              1.00      3.5±0.01µs        ? ?/sec    1.01      3.5±0.00µs        ? ?/sec
decimal128_array_from_vec 32768        1.00     98.7±0.58µs        ? ?/sec    1.01    100.0±0.23µs        ? ?/sec
decimal256_array_from_vec 32768        1.00      3.9±0.01µs        ? ?/sec    1.01      3.9±0.01µs        ? ?/sec
decimal32_array_from_vec 32768         1.00     85.9±0.60µs        ? ?/sec    1.00     85.5±0.12µs        ? ?/sec
decimal64_array_from_vec 32768         1.00     90.4±0.19µs        ? ?/sec    1.00     90.7±0.27µs        ? ?/sec
struct_array_from_vec 1024             1.00      8.6±0.02µs        ? ?/sec    1.03      8.9±0.01µs        ? ?/sec
struct_array_from_vec 128              1.00   1862.6±2.69ns        ? ?/sec    1.02   1905.5±5.29ns        ? ?/sec
struct_array_from_vec 256              1.00      2.8±0.02µs        ? ?/sec    1.05      2.9±0.00µs        ? ?/sec
struct_array_from_vec 512              1.00      4.6±0.01µs        ? ?/sec    1.05      4.8±0.01µs        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
🤔  

Int64Array::from_trusted_len_iter      2.78     52.5±0.34µs        ? ?/sec    1.00     18.9±0.04µs        ? ?/sec

File: arrow/benches/array_from.rs [hunk 3]
```diff
@@ -207,34 +206,47 @@ fn array_from_vec_benchmark(c: &mut Criterion) {
...
 }
 
 fn from_iter_benchmark(c: &mut Criterion) {
     const ITER_LEN: usize = 16_384;
 
     // All ArrowPrimitiveType use the same implementation
     c.bench_function("Int64Array::from_iter", |b| {
-        let values = gen_option_vector(1, ITER_LEN);
-        b.iter(|| hint::black_box(Int64Array::from_iter(values.iter())));
+        b.iter(|| hint::black_box(Int64Array::from_iter(gen_option_iter(1, ITER_LEN))));
```
Comment (alamb) [inline arrow/benches/array_from.rs]: Ah, I see you changed the benchmark in this PR as well -- it would help me asses the performance impact of just this change if you could make the benchmark change in a different PR

Comment (tschwarzinger) [reply arrow/benches/array_from.rs]: Yeah, that make sense. I'll extract the benchmark changes into a follow up on Monday.

File: arrow-array/src/array/boolean_array.rs (hunk 1 above)
Comment (tschwarzinger) [reply arrow-array/src/array/boolean_array.rs]: I've re-applied the commit as I cannot seem to reproduce this behavior on the old benchmarks. If you have any doubts that this could lead to a performance regression, we can investigate this further.

File: arrow/benches/array_from.rs (hunk 3 above)
Comment (tschwarzinger) [reply arrow/benches/array_from.rs]: @alamb The benchmarks are reverted and we should be able to re-run the benchmarks. Once this PR is merged I'll improve the benchmarks based on the feedback from @jhorstmann .

**Comment by alamb** [comment]
🤖 `./gh_compare_arrow.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/scripts/gh_compare_arrow.sh) Running
Linux aal-dev 6.14.0-1016-gcp #17~24.04.1-Ubuntu SMP Wed Sep  3 01:55:36 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing 8505-fix-from-iter (16c40593d2f06060262948659c4af413b642eee2) to f88921cb04d8dfdf3ed3f0c7d05b5065d124fc6b [diff](https://github.com/apache/arrow-rs/compare/f88921cb04d8dfdf3ed3f0c7d05b5065d124fc6b..16c40593d2f06060262948659c4af413b642eee2)
BENCH_NAME=array_from
BENCH_COMMAND=cargo bench --features=arrow,async,test_common,experimental --bench array_from 
BENCH_FILTER=
BENCH_BRANCH_NAME=8505-fix-from-iter
Results will be posted here when complete

File: arrow-array/src/builder/boolean_builder.rs [hunk 4]
```diff
@@ -234,9 +234,12 @@ impl ArrayBuilder for BooleanBuilder {
 impl Extend<Option<bool>> for BooleanBuilder {
     #[inline]
     fn extend<T: IntoIterator<Item = Option<bool>>>(&mut self, iter: T) {
-        for v in iter {
-            self.append_option(v)
-        }
+        let buffered = iter.into_iter().collect::<Vec<_>>();
+        let array = unsafe {
+            // SAFETY: buffered.into_iter() is a trusted length iterator
```
Comment (alamb) [inline arrow-array/src/builder/boolean_builder.rs]: I think technically `buffered` is a `Vec` which is a trusted length iterator

```suggestion
            // SAFETY: Vec is a trusted length iterator
```

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                  8505-fix-from-iter                     main
-----                                  ------------------                     ----
BooleanArray::from_iter                1.22     24.0±0.04µs        ? ?/sec    1.00     19.6±0.02µs        ? ?/sec
BooleanArray::from_trusted_len_iter    1.00     16.9±0.03µs        ? ?/sec  
Int64Array::from_iter                  1.00     39.8±0.08µs        ? ?/sec    1.00     40.0±0.14µs        ? ?/sec
Int64Array::from_trusted_len_iter      1.01     19.0±0.05µs        ? ?/sec    1.00     18.9±0.05µs        ? ?/sec
array_from_vec 128                     1.00    156.7±0.15ns        ? ?/sec    1.02    159.3±0.19ns        ? ?/sec
array_from_vec 256                     1.00    165.6±0.82ns        ? ?/sec    1.01    166.9±0.39ns        ? ?/sec
array_from_vec 512                     1.00    222.4±0.53ns        ? ?/sec    1.01    224.7±0.30ns        ? ?/sec
array_string_from_vec 128              1.00   1033.8±1.72ns        ? ?/sec    1.21   1249.9±4.58ns        ? ?/sec
array_string_from_vec 256              1.00   1766.5±5.77ns        ? ?/sec    1.15      2.0±0.00µs        ? ?/sec
array_string_from_vec 512              1.00      3.1±0.01µs        ? ?/sec    1.14      3.5±0.02µs        ? ?/sec
decimal128_array_from_vec 32768        1.00     99.7±0.31µs        ? ?/sec    1.00     99.4±0.44µs        ? ?/sec
decimal256_array_from_vec 32768        1.03      4.0±0.02µs        ? ?/sec    1.00      3.8±0.02µs        ? ?/sec
decimal32_array_from_vec 32768         1.00     85.7±0.38µs        ? ?/sec    1.00     85.7±0.17µs        ? ?/sec
decimal64_array_from_vec 32768         1.00     90.6±0.23µs        ? ?/sec    1.00     90.7±0.22µs        ? ?/sec
struct_array_from_vec 1024             1.00      8.2±0.01µs        ? ?/sec    1.08      8.9±0.12µs        ? ?/sec
struct_array_from_vec 128              1.00   1826.5±4.18ns        ? ?/sec    1.03   1887.2±3.92ns        ? ?/sec
struct_array_from_vec 256              1.00      2.8±0.00µs        ? ?/sec    1.05      2.9±0.01µs        ? ?/sec
struct_array_from_vec 512              1.00      4.6±0.01µs        ? ?/sec    1.06      4.9±0.01µs        ? ?/sec
```


</p>
</details>

**Comment by tschwarzinger** [comment]
> 🤖: Benchmark completed
> Details
> 
> ```
> group                                  8505-fix-from-iter                     main
> -----                                  ------------------                     ----
> BooleanArray::from_iter                1.22     24.0±0.04µs        ? ?/sec    1.00     19.6±0.02µs        ? ?/sec
> BooleanArray::from_trusted_len_iter    1.00     16.9±0.03µs        ? ?/sec  
> Int64Array::from_iter                  1.00     39.8±0.08µs        ? ?/sec    1.00     40.0±0.14µs        ? ?/sec
> Int64Array::from_trusted_len_iter      1.01     19.0±0.05µs        ? ?/sec    1.00     18.9±0.05µs        ? ?/sec
> [...]
> ```

Thanks! I think this is in-line with what I measured locally. `BooleanArray::from_iter` is a bit slower, but the new `BooleanArray::from_trusted_len_iter` is faster than the old implementation (here 16.9 µs vs 19.6 µs) due to the use of unsafe.

**Comment by alamb** [comment]
> > 🤖: Benchmark completed
> > Details
> > ```
> > group                                  8505-fix-from-iter                     main
> > -----                                  ------------------                     ----
> > BooleanArray::from_iter                1.22     24.0±0.04µs        ? ?/sec    1.00     19.6±0.02µs        ? ?/sec
> > BooleanArray::from_trusted_len_iter    1.00     16.9±0.03µs        ? ?/sec  
> > Int64Array::from_iter                  1.00     39.8±0.08µs        ? ?/sec    1.00     40.0±0.14µs        ? ?/sec
> > Int64Array::from_trusted_len_iter      1.01     19.0±0.05µs        ? ?/sec    1.00     18.9±0.05µs        ? ?/sec
> > [...]
> > ```
> 
> Thanks! I think this is in-line with what I measured locally. `BooleanArray::from_iter` is a bit slower, but the new `BooleanArray::from_trusted_len_iter` is faster than the old implementation (here 16.9 µs vs 19.6 µs) due to the use of unsafe.

Yes, I agree with your analysis -- and I think it is ok to take a hit of performance to make it correct 🤣

File: arrow-array/src/array/boolean_array.rs [hunk 5]
```diff
@@ -436,11 +436,84 @@ impl<'a> BooleanArray {
...
 
-impl<Ptr: std::borrow::Borrow<Option<bool>>> FromIterator<Ptr> for BooleanArray {
+/// An optional boolean value
+///
+/// This struct is used as an adapter when creating `BooleanArray` from an iterator.
+/// `FromIterator` for `BooleanArray` takes an iterator where the elements can be `into`
+/// this struct. So once implementing `From` or `Into` trait for a type, an iterator of
+/// the type can be collected to `BooleanArray`.
+///
+/// See also [NativeAdapter](crate::array::NativeAdapter).
```
Comment (alamb) [inline arrow-array/src/array/boolean_array.rs:446]: thank you for the reference to `NativeAdapter` -- I was wondering why this seemingly new pattern

Given it follows the existing pattern, I say 👍

File: arrow-array/src/array/boolean_array.rs [hunk 6]
```diff
@@ -436,11 +436,84 @@ impl<'a> BooleanArray {
...
+        let mut builder = BooleanBuilder::with_capacity(capacity);
+        builder.extend(iter.map(|item| item.into().native));
+        builder.finish()
+    }
+}
+
+impl BooleanArray {
+    /// Creates a [`BooleanArray`] from an iterator of trusted length.
+    ///
+    /// # Safety
```
Comment (alamb) [inline arrow-array/src/array/boolean_array.rs:497]: this is consistent with `PrimitiveArray::from_trusted_len_iter`: https://github.com/apache/arrow-rs/blob/9ba0eebeebeef5e0e661926f631373587523fdcb/arrow-array/src/array/primitive_array.rs#L1460-L1463

👍

**Review by alamb — APPROVED** [review]
Thank you @tobixdev  -- this code looks very nice and consistent with PrimitiveArray to me

@jhorstmann and @mbrobbel  perhaps you can give this PR a final review before we merge as well to make sure we haven't missed anything

File: arrow-array/src/builder/boolean_builder.rs (hunk 4 above)
Comment (tschwarzinger) [reply arrow-array/src/builder/boolean_builder.rs]: What about:
`Vec::into_iter()` returns a trusted length iterator

Otherwise, it could suggest that `Vec` directly implements `TrustedLen`. Or maybe that's the case and I don't fully understand `Vec`'s implementation.

File: arrow-array/src/array/boolean_array.rs (hunk 1 above)
Comment (tschwarzinger) [reply arrow-array/src/array/boolean_array.rs]: > > Should we also change it for the PrimitiveArray?
>
> We could do that in a different PR.

Should we open a ticket to discuss this further or just submit a PR?

Comment (alamb) [reply arrow-array/src/array/boolean_array.rs]: Either sounds good to me

Comment (tschwarzinger) [reply arrow-array/src/array/boolean_array.rs]: I'll create a follow-up PR together with benchmark changes once this one is merged.

File: arrow-array/src/builder/boolean_builder.rs (hunk 4 above)
Comment (mbrobbel) [reply arrow-array/src/builder/boolean_builder.rs]: `std::vec::IntoIter` implements `TrustedLen`: https://doc.rust-lang.org/stable/std/vec/struct.IntoIter.html#impl-TrustedLen-for-IntoIter%3CT,+A%3E

**Comment by jhorstmann** [comment]
Looks good. This clearly fixes the incorrect behavior, and adding `from_trusted_len_iter` makes this consistent with the primitive arrays. I would prefer if we did not need the intermediate vec allocation, but will write my thoughts on improvements to `BooleanBuilder` in a separate issue.

**Review by mbrobbel — APPROVED** [review]

**Comment by tschwarzinger** [comment]
> Looks good. This clearly fixes the incorrect behavior, and adding `from_trusted_len_iter` makes this consistent with the primitive arrays. I would prefer if we did not need the intermediate vec allocation, but will write my thoughts on improvements to `BooleanBuilder` in a separate issue.

Yes, I agree that it would be great to get similar / better performance without any heap allocations. Thanks for creating the issue!

**Comment by tschwarzinger** [comment]
I think all comments are resolved and some of them will be tackled in the follow-up PR / issue. Thanks for your input!
