### PR TITLE
Fix ilike_utf8_scalar kernals

### LINKED ISSUE #2544: Ilike_ut8_scalar kernals have incorrect logic
**Describe the bug**
Incorrect implemetation of ilike_utf8_scalars

**To Reproduce**
The below code fails
```
let left = StringArray::from(vec!["arrow", "parrow", "arrows", "arr"]);
let right = "ArroW";
let res = ilike_utf8_scalar(&left, right).unwrap();
assert!(res.value(0));
```

**Expected behavior**
The above code should pass

**Additional context**
In the equals path of ilike there is incorrect comparision

### PR DESCRIPTION
**Pull request by psvri**
# Which issue does this PR close?

Closes #2544 .

# Rationale for this change
 
Incorrect logic in equals path of ilike_utf8_scalar kernals

# What changes are included in this PR?

Bug fix

# Are there any user-facing changes?

### CODE REVIEW

File: arrow/src/compute/kernels/comparison.rs [hunk 1]
```diff
@@ -468,7 +468,7 @@ pub fn ilike_utf8_scalar<OffsetSize: OffsetSizeTrait>(
     if !right.contains(is_like_pattern) {
         // fast path, can use equals
         for i in 0..left.len() {
-            result.append(left.value(i) == right);
+            result.append(left.value(i).to_uppercase() == right.to_uppercase());
```
Comment (Dandandan) [inline arrow/src/compute/kernels/comparison.rs:471]: This needs to be done once only for the `right` scalar?

File: arrow/src/compute/kernels/comparison.rs [hunk 2]
```diff
@@ -551,7 +551,7 @@ pub fn nilike_utf8_scalar<OffsetSize: OffsetSizeTrait>(
     if !right.contains(is_like_pattern) {
         // fast path, can use equals
         for i in 0..left.len() {
-            result.append(left.value(i) != right);
+            result.append(left.value(i).to_uppercase() != right.to_uppercase());
```
Comment (Dandandan) [inline arrow/src/compute/kernels/comparison.rs:554]: Can be done once only

File: arrow/src/compute/kernels/comparison.rs (hunk 1 above)
Comment (psvri) [reply arrow/src/compute/kernels/comparison.rs:471]: Sorry, A bit confused.

Did you mean that the right.to_uppercase() and be extracted to outside the if block rather than doing it every time in the if else blocks ?

Comment (Dandandan) [reply arrow/src/compute/kernels/comparison.rs:471]: Yes, and also outside the inner loop. The compiler often won't find out that it's possible to do this.

Comment (psvri) [reply arrow/src/compute/kernels/comparison.rs]: Fixed in the latest commit

**Review by tustvold — APPROVED** [review]
Very nice :+1:
