### PR TITLE
Fix S3 query canonicalization (#2800)

### LINKED ISSUE #2800: S3 Signature Error Performing List With Prefix Containing Spaces
**Describe the bug**

Attempting to perform a list request using a prefix containing a space results in a signature error. 

```
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method
...
```

This is because IAM requires always percent encoding all spaces - https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

> Percent-encode all other characters with %XY, where X and Y are hexadecimal characters (0-9 and uppercase A-F). For example, the space character must be encoded as %20 (not using '+', as some encoding schemes do)

This is normally the case as we explicitly percent encode paths - https://github.com/apache/arrow-rs/blob/master/object_store/src/aws/client.rs#L471

However, we delegate to reqwest for percent encoding of query parameters, and it uses `+` instead of `%20`.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #2800
Contains tests for #2799 

# Rationale for this change
 

I was lazy when implementing query canonicalization, and figured we could just use the query from the URL provided they were in the correct order. Sadly this is not the case as AWS has specific requirements for percent encoding.

# What changes are included in this PR?

Implements request canonicalisation as per the spec

# Are there any user-facing changes?

No

### CODE REVIEW

File: object_store/src/lib.rs [hunk 1]
```diff
@@ -701,6 +701,20 @@ mod tests {
...
+        let files = flatten_list_stream(storage, Some(&Path::from("foo bar")))
+            .await
+            .unwrap();
+        assert_eq!(files, vec![path.clone()]);
+        storage.delete(&path).await.unwrap();
+
+        let files = flatten_list_stream(storage, Some(&Path::from("foo bar")))
+            .await
+            .unwrap();
+        assert!(files.is_empty(), "{:?}", files);
```
Comment (tustvold) [inline object_store/src/lib.rs:717]: This adds an explicit test of paths containing spaces, FYI @andygrove

**Comment by tustvold** [comment]
I opted to suppress the broken emulators, instead of working around the issue, as they are bugs in the emulators. Running against the real services behaves correctly.

* https://github.com/Azure/Azurite/issues/1696
* https://github.com/localstack/localstack/issues/6328

**Review by andygrove — APPROVED** [review]
Thanks @tustvold
