### PR TITLE
Use ArrayFormatter in cast kernel

### LINKED ISSUE #4669: Casting List to String Ignores Format Options
**Describe the bug**

**To Reproduce**

```
#[test]
    fn test_list_format_options() {
        let options = CastOptions {
            safe: false,
            format_options: FormatOptions::default().with_null("null"),
        };
        let array = ListArray::from_iter_primitive::<Int32Type, _, _>(vec![
            Some(vec![Some(0), Some(1), Some(2)]),
            Some(vec![Some(0), None, Some(2)]),
        ]);
        let a = cast_with_options(&array, &DataType::Utf8, &options).unwrap();
        let r: Vec<_> = a.as_string::<i32>().iter().map(|x| x.unwrap()).collect();
        assert_eq!(r, &["[0, 1, 2]", "[0, null, 2]"]);
    }
```

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4669

# Rationale for this change
 

# What changes are included in this PR?

Follow up to #4666 uses ArrayFormatter in more places instead of custom logic

# Are there any user-facing changes?

### CODE REVIEW

File: arrow-cast/src/cast.rs [hunk 1]
```diff
@@ -622,21 +622,6 @@ where
     Ok(Arc::new(array))
 }
 
-// cast the List array to Utf8 array
-macro_rules! cast_list_to_string {
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:626]: Changing to use ArrayFormatter is both faster, as it avoids intermediate string allocations, whilst also respecting format options

File: arrow-cast/src/cast.rs [hunk 2]
```diff
@@ -8989,4 +8950,19 @@ mod tests {
     fn test_const_options() {
         assert!(CAST_OPTIONS.safe)
     }
+
+    #[test]
+    fn test_list_format_options() {
```
Comment (tustvold) [inline arrow-cast/src/cast.rs:8955]: Test for #4669

**Review by viirya — APPROVED** [review]
It looks good that it removes custom logic in many places.
