### PR TITLE
Fix ObjectStore::get_range for GetResult::File (#4350)

### LINKED ISSUE #4350: Default ObjectStore::get_range Doesn't Apply Range to GetResult::File
**Describe the bug**

The default implementation of `ObjectStore::get_range` added in #4212 incorrectly handles if `GetResult::File` is returned, instead returning the entire byte range. This is incorrect

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4350

# Rationale for this change
 

I'm not a massive fan of this, as `GetResult::bytes()` not taking into account any range feels like a bit of a footgun, however, I couldn't see a way around this without making a breaking change. I may revisit this at a later date, but this at least fixes the bug.

# What changes are included in this PR?

Changes the default implementation of get_range to correctly handle a returned file

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
There appears to be a wasm failure: https://github.com/apache/arrow-rs/actions/runs/5157697965/jobs/9290441031?pr=4351

File: object_store/src/lib.rs [hunk 1]
```diff
@@ -359,10 +359,16 @@ pub trait ObjectStore: std::fmt::Display + Send + Sync + Debug + 'static {
     /// in the given byte range
     async fn get_range(&self, location: &Path, range: Range<usize>) -> Result<Bytes> {
         let options = GetOptions {
-            range: Some(range),
+            range: Some(range.clone()),
             ..Default::default()
         };
-        self.get_opts(location, options).await?.bytes().await
+        match self.get_opts(location, options).await? {
```
Comment (alamb) [inline object_store/src/lib.rs:365]: This doesn't seem quite right to me -- the issue is if `GetResult::File` returns a file in the first place, because `GetResult::File` doesn't have a way to represent a range of a file.

I think there are two better/cleaner ways:
1. Add an (optional) range to `GetResult::File`
2. Update `LocalFileSystem::get_opts` to to not return `GetResult::File` if there is a range and instead return a stream

I think 1 is cleaner but I think it would be an API change and thus require releasing object_store 0.7

Comment (tustvold) [reply object_store/src/lib.rs:365]: I considered 2. but aside from it also being a breaking change, it would make it hard to support a use-case where you want to do range requests if talking to a remote store to avoid fetching the entire file, but if a local filesystem want to get a file as then you can handle it directly.

I also considered 1. and it is where my thinking is headed, but I would rather not rush into something on Friday afternoon :laughing:

Comment (alamb) [reply object_store/src/lib.rs:365]: Let's
1. Document that this is a workaround in comments for our future selves (and others who find this)
2. Add a ticket to track (I can do so if you wish)

**Review by alamb — APPROVED** [review]
