### PR TITLE
Make ArrayFormatterFactory Send + Sync and add a test

### LINKED ISSUE #8875: (dyn ArrayFormatterFactory + 'static) can't be safely shared between threads
**Describe the bug**

When I tried the new version of arrow with DataFusion in this PR:
- https://github.com/apache/datafusion/pull/18820

Compilation fails like this:

```
 Compiling datafusion-sql v51.0.0 (/Users/andrewlamb/Software/datafusion/datafusion/sql)
error[E0277]: `(dyn ArrayFormatterFactory + 'static)` cannot be shared between threads safely
   --> datafusion/physical-expr/src/expressions/cast.rs:130:23
    |
130 | impl PhysicalExpr for CastExpr {
    |                       ^^^^^^^^ `(dyn ArrayFormatterFactory + 'static)` cannot be shared between threads safely
    |
    = help: within `CastExpr`, the trait `Sync` is not implemented for `(dyn ArrayFormatterFactory + 'static)`
    = note: required because it appears within the type `&'static (dyn ArrayFormatterFactory + 'static)`
note: required because it appears within the type `Option<&'static (dyn ArrayFormatterFactory + 'static)>`
   --> /Users/andrewlamb/.rustup/toolchains/1.91.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:594:10
    |
594 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type `arrow::util::display::FormatOptions<'static>`
   --> /Users/andrewlamb/.cargo/git/checkouts/arrow-rs-a228b2f48bc25539/f7d41c8/arrow-cast/src/display.rs:63:12
    |
 63 | pub struct FormatOptions<'a> {
    |            ^^^^^^^^^^^^^
note: required because it appears within the type `CastOptions<'static>`
   --> /Users/andrewlamb/.cargo/git/checkouts/arrow-rs-a228b2f48bc25539/f7d41c8/arrow-cast/src/cast/mod.rs:76:12
    |
 76 | pub struct CastOptions<'a> {
    |            ^^^^^^^^^^^
note: required because it appears within the type `CastExpr`
   --> datafusion/physical-expr/src/expressions/cast.rs:46:12
```

**To Reproduce**
See https://github.com/apache/datafusion/pull/18820

**Expected behavior**
I should be able to keep on compiling what previously worked
**Additional context**

### PR DESCRIPTION
**Pull request by tschwarzinger**
# Which issue does this PR close?

- Closes #8875 .

Ping @alamb 

# Rationale for this change

`FormatOptions` is no longer `Send` and `Sync`.

# What changes are included in this PR?

- Require `Send` + `Sync` for `ArrayFormatterFactory`
- Assertion that `FormatOptions` is `Send` + `Sync`

# Are these changes tested?

- Yes

# Are there any user-facing changes?

Yes, should fix the compiler error. I could compile DataFusion with the following patch adapted from the issue:

```
## Temporary arrow-rs patch until 57.1.0 is released

[patch.crates-io]
arrow = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-array = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-buffer = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-cast = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-data = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-ipc = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-schema = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-select = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-string = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-ord = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
arrow-flight = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
parquet = { git = "https://github.com/tobixdev/arrow-rs.git", branch = "custom-formatters" }
```

### CODE REVIEW

File: arrow-cast/src/display.rs [hunk 1]
```diff
@@ -1340,6 +1340,19 @@ mod tests {
         assert_eq!(TEST_CONST_OPTIONS.date_format, Some("foo"));
     }
 
+    /// See https://github.com/apache/arrow-rs/issues/8875
+    #[test]
+    fn test_options_send_sync() {
+        fn assert_send_sync<T>()
```
Comment (alamb) [inline arrow-cast/src/display.rs:1346]: ❤️
