### PR TITLE
Change parquet writers to use standard `std:io::Write` rather custom `ParquetWriter` trait (#1717) (#1163)

### LINKED ISSUE #1717: Trying to write parquet file in parallel results in corrupt file
**Describe the bug**
(from the mailing list)

Apparently, you can make a program that appears to write a parquet file in parallel, but it will   currently produce corrupt parquet data.

**To Reproduce**
Description in the email says:

> I was attempting to build a single Parquet from the batches in what I thought was a parallel manner using the ArrowWriter.  I tried to "parallelise" the following serial code. 

```rust
            let cursor = InMemoryWriteableCursor::default();
            let mut writer = ArrowWriter::try_new(cursor.clone(), schema, None)?;
            for batch in batches {
                writer.write(batch)?;
            }
            writer.close()?;
```

> I realised that although the compiler accepted my incorrect parallel version of this code, it in-fact was not sound which caused the corruption.

**Expected behavior**
The API should not allow corrupted data / produce a compiler error

Actually writing a parquet file in parallel is tracked in https://github.com/apache/arrow-rs/issues/1718

**Additional context**
Mailing list https://lists.apache.org/thread/rbhfwcpd6qfk52rtzm2t6mo3fhvdpc91

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #1717

Part of #1163 

# Rationale for this change
 
See tickets, but in short the current write path makes use of a lot of custom IO abstractions which can be hard to use correctly. In particular the use of TryClone can easily lead to races if used to share a file descriptor across threads.

# What changes are included in this PR?

This reworks the write path to use `std::io::Write` and nothing else. Unfortunately to achieve this requires a few changes:

* A TrackedWrite that keeps track of how many bytes have been written, allowing removal of Seek
* A callback based approach to get metadata from a child writer to its parent
* Lifetimes, lots of lifetimes...

This last point becomes a bit obnoxious when it interacts with the `RowGroupWriter` trait. In order to be object-safe, i.e. possible to construct `Box<dyn RowGroupWriter>`, `RowGroupWriter::close` cannot take `self` by value. This results in explicit scopes, or calls to `std::mem::drop` in order to truncate its lifetime.

I'm not entirely sure what the purpose of these traits is, but perhaps we could simplify things, and fix this slight lifetime annoyance by removing them? Maybe something for a follow up PR?

# Are there any user-facing changes?

Yes, this makes non-trivial changes to the parquet write API.

### CODE REVIEW

File: parquet/src/file/mod.rs [hunk 1]
```diff
@@ -48,12 +48,14 @@
 //! let props = Arc::new(WriterProperties::builder().build());
 //! let file = fs::File::create(&path).unwrap();
 //! let mut writer = SerializedFileWriter::new(file, schema, props).unwrap();
-//! let mut row_group_writer = writer.next_row_group().unwrap();
-//! while let Some(mut col_writer) = row_group_writer.next_column().unwrap() {
-//!     // ... write values to a column writer
-//!     row_group_writer.close_column(col_writer).unwrap();
+//! {
```
Comment (tustvold) [inline parquet/src/file/mod.rs:51]: This is an example of the somewhat unfortunate manual scoping... I personally think removing the trait indirection would make the code a lot easier to understand...

File: parquet/src/file/writer.rs [hunk 2]
```diff
@@ -393,39 +387,91 @@ impl<W: 'static + ParquetWriter> RowGroupWriter for SerializedRowGroupWriter<W>
...
+                on_close(metadata)?
+            }
         }
 
         let metadata = self.row_group_metadata.as_ref().unwrap().clone();
         Ok(metadata)
     }
 }
 
+/// A wrapper around a [`ColumnWriter`] that invokes a callback on [`Self::close`]
```
Comment (tustvold) [inline parquet/src/file/writer.rs:403]: I'm not a massive fan of this, but I was somewhat wary of making changes to the `ColumnWriter` plumbing as it is used in lots of places

File: parquet/src/arrow/arrow_writer.rs [hunk 3]
```diff
@@ -65,7 +67,7 @@ pub struct ArrowWriter<W: ParquetWriter> {
     max_row_group_size: usize,
 }
 
-impl<W: 'static + ParquetWriter> ArrowWriter<W> {
+impl<W: Write> ArrowWriter<W> {
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer.rs:70]: This seemingly small change means you can pass in `&mut std::io::Cursor<Vec<_>>` or any other construction which makes this much easier to use

File: parquet/src/arrow/arrow_writer.rs [hunk 4]
```diff
@@ -744,15 +748,15 @@ mod tests {
         let expected_batch =
             RecordBatch::try_new(schema.clone(), vec![Arc::new(a), Arc::new(b)]).unwrap();
 
-        let cursor = InMemoryWriteableCursor::default();
+        let mut cursor = Cursor::new(vec![]);
```
Comment (tustvold) [inline parquet/src/arrow/arrow_writer.rs:751]: :tada:

File: parquet/src/file/writer.rs [hunk 5]
```diff
@@ -92,102 +111,90 @@ pub trait FileWriter {
...
     ///
-    /// It is recommended to call this method before requesting another row group, but it
-    /// will be closed automatically before returning a new row group.
-    ///
     /// Can be called multiple times. In subsequent calls will result in no-op and return
     /// already created row group metadata.
     fn close(&mut self) -> Result<RowGroupMetaDataPtr>;
 }
 
+/// Callback invoked on closing a column chunk, arguments are:
```
Comment (tustvold) [inline parquet/src/file/writer.rs:131]: We have to move to a callback model as the child writers now mutably borrow from their parents, and so it would be impossible to keep the current interface. I also happen to think this is cleaner, you simply close the ColumnWriter when you are finished, vs passing the ColumnWriter back to the RowGroupWriter.

File: parquet/benches/arrow_writer.rs [hunk 6]
```diff
@@ -278,8 +276,8 @@ fn _create_nested_bench_batch(
 #[inline]
 fn write_batch(batch: &RecordBatch) -> Result<()> {
     // Write batch to an in-memory writer
-    let cursor = InMemoryWriteableCursor::default();
-    let mut writer = ArrowWriter::try_new(cursor, batch.schema(), None)?;
+    let buffer = vec![];
```
Comment (alamb) [inline parquet/benches/arrow_writer.rs:279]: here is a nice example of the new API in action: use something that does `std::io::Write`

File: parquet/src/util/cursor.rs [hunk 7]
```diff
@@ -133,68 +131,6 @@ impl Seek for SliceableCursor {
     }
 }
 
-/// Use this type to write Parquet to memory rather than a file.
-#[derive(Debug, Default, Clone)]
```
Comment (alamb) [inline parquet/src/util/cursor.rs:137]: In terms of easing the transition of this change, what would you think about marking this struct "deprecated" and keeping the code backwards compatible for a few releases (e.g. `impl Wite for InMemoryWriteableCursor`)? 

That might make the API change easier to manage and give users some time to remove it.

File: parquet/src/util/io.rs [hunk 8]
```diff
@@ -153,47 +153,6 @@ impl<R: ParquetReader> Length for FileSource<R> {
         self.end - self.start
     }
 }
-
-/// Struct that represents `File` output stream with position tracking.
-/// Used as a sink in file writer.
```
Comment (alamb) [inline parquet/src/util/io.rs:158]: Likewise, I recommend considering leaving this structure in (and marking it as "deprecated") for a release or two to give people a chance to update their code rather over time.

File: parquet_derive_test/src/lib.rs [hunk 9]
```diff
@@ -131,9 +131,13 @@ mod tests {
...
 
-        let mut row_group = writer.next_row_group().unwrap();
-        drs.as_slice().write_to_row_group(&mut row_group).unwrap();
-        writer.close_row_group(row_group).unwrap();
+        {
+            let mut row_group = writer.next_row_group().unwrap();
+            drs.as_slice()
+                .write_to_row_group(row_group.as_mut())
+                .unwrap();
+            row_group.close().unwrap();
```
Comment (alamb) [inline parquet_derive_test/src/lib.rs:139]: I do like this pattern better (close the row group writer rather than passing it back to the parquet file writer to close)

File: parquet/src/file/mod.rs (hunk 1 above)
Comment (alamb) [reply parquet/src/file/mod.rs:51]: Which trait indirection are you referring to?

Comment (alamb) [reply parquet/src/file/mod.rs:51]: Also, it seems to me like we could change this example to actually run (not sure why it is marked `norun` -- it just needs to pick a tempfile as target rather than `/path/to/sample.parquet`)

File: parquet/src/file/writer.rs [hunk 10]
```diff
@@ -65,15 +91,8 @@ pub trait FileWriter {
...
-    fn next_row_group(&mut self) -> Result<Box<dyn RowGroupWriter>>;
-
-    /// Finalises and closes row group that was created using `next_row_group` method.
-    /// After calling this method, the next row group is available for writes.
-    fn close_row_group(
-        &mut self,
-        row_group_writer: Box<dyn RowGroupWriter>,
-    ) -> Result<()>;
+    /// previous row group must be finalised and closed using `RowGroupWriter::close` method.
+    fn next_row_group(&mut self) -> Result<Box<dyn RowGroupWriter + '_>>;
```
Comment (alamb) [inline parquet/src/file/writer.rs:95]: It might help here to leave a link back to the docs in `parquet/src/file/mod.rs` to bring readers to an example

File: parquet/src/file/writer.rs [hunk 11]
```diff
@@ -92,102 +111,90 @@ pub trait FileWriter {
 /// All columns should be written sequentially; the main workflow is:
 /// - Request the next column using `next_column` method - this will return `None` if no
 /// more columns are available to write.
-/// - Once done writing a column, close column writer with `close_column` method - this
-/// will finalise column chunk metadata and update row group metrics.
+/// - Once done writing a column, close column writer with `close`
```
Comment (alamb) [inline parquet/src/file/writer.rs:114]: What is the reason to remove the rationale ('this will finalize column chunk metadata ...')?

File: parquet/src/file/writer.rs (hunk 5 above)
Comment (alamb) [reply parquet/src/file/writer.rs:131]: Also importantly, by keeping a mutable reference it lets the compiler prevent concurrent writes to the same writer, as reported in https://github.com/apache/arrow-rs/issues/1717

File: parquet/src/file/writer.rs [hunk 12]
```diff
@@ -196,13 +203,13 @@ impl<W: ParquetWriter> SerializedFileWriter<W> {
         };
 
         // Write file metadata
-        let start_pos = self.buf.seek(SeekFrom::Current(0))?;
+        let start_pos = self.buf.bytes_written();
```
Comment (alamb) [inline parquet/src/file/writer.rs:206]: ❤️

File: parquet/src/file/writer.rs [hunk 13]
```diff
@@ -214,7 +221,7 @@ impl<W: ParquetWriter> SerializedFileWriter<W> {
     }
 
     #[inline]
-    fn assert_closed(&self) -> Result<()> {
+    fn assert_not_closed(&self) -> Result<()> {
```
Comment (alamb) [inline parquet/src/file/writer.rs:224]: 👍

File: parquet/src/file/writer.rs [hunk 14]
```diff
@@ -270,69 +273,45 @@ impl<W: 'static + ParquetWriter> FileWriter for SerializedFileWriter<W> {
...
+    /// - `schema_descr` - the schema to write
+    /// - `properties` - writer properties
+    /// - `buf` - the buffer to write data to
+    /// - `on_close` - an optional callback that will invoked on [`Self::close`]
     pub fn new(
         schema_descr: SchemaDescPtr,
         properties: WriterPropertiesPtr,
-        buf: &W,
+        buf: &'a mut TrackedWrite<W>,
+        on_close: Option<OnCloseRowGroup<'a>>,
```
Comment (alamb) [inline parquet/src/file/writer.rs:299]: why is this `Option` -- shouldn't it always be required?

File: parquet/src/file/writer.rs [hunk 15]
```diff
@@ -270,69 +273,45 @@ impl<W: 'static + ParquetWriter> FileWriter for SerializedFileWriter<W> {
...
             column_index: 0,
-            previous_writer_closed: true,
             row_group_metadata: None,
             column_chunks: Vec::with_capacity(num_columns),
+            total_bytes_written: 0,
         }
     }
 
-    /// Checks and finalises current column writer.
-    fn finalise_column_writer(&mut self, writer: ColumnWriter) -> Result<()> {
```
Comment (alamb) [inline parquet/src/file/writer.rs:306]: This code appears to have been inlined into `next_column` below

**Review by alamb — APPROVED** [review]
Thank you @tustvold !

All in all I think this is a great improvement --  It is great to see that the API now reflects the "write only a single row group at a time" restriction in a way that the compiler can enforce. This also seems like a nice step towards tracking information (like bytes written) in a way that I can imagine actually parallelizing the encoding. 

I do think it might be worth a little more investment to make the change "less breaking" (by marking some structs as `deprecated` for a while) 

cc @pacman82 @manojkarthick @nevi-me

File: parquet/src/file/mod.rs (hunk 1 above)
Comment (tustvold) [reply parquet/src/file/mod.rs:51]: > Which trait indirection are you referring to?

We have FileWriter and RowGroupWriter traits which are then implemented by `SerializedFileWriter` and `SerializedRowGroupWriter`.

I'm not sure why you would ever want to override the default implementation, and the need to expose these as object-safe traits prevents `FileWriter::close(self)` or `RowGroupWriter::close(self)` which causes lifetime annoyances.

I also find the indirection very confusing in general :sweat_smile:

File: parquet/src/file/writer.rs (hunk 14 above)
Comment (tustvold) [reply parquet/src/file/writer.rs:299]: So these writers are technically public and I don't really know what people might be using them for, I thought this was a way to make the change less annoying - you can just pass `None` and move on...

Comment (alamb) [reply parquet/src/file/writer.rs:299]: makes sense

File: parquet/src/file/mod.rs (hunk 1 above)
Comment (tustvold) [reply parquet/src/file/mod.rs:51]: It would have been highly non-trivial to do this correctly before, and with the lifetime change in this PR it would actually be impossible, as `FileWriter::next_row_group` returns a mutable borrow of `FileWriter`

That being said, nothing would prevent creating a ParallelizedFileWriter, you just wouldn't be able to be generic over parallel and non-parallel implementations. I'm not sure this is actually a problem.

I personally think removing these traits as part of the PR would go a long way to making the change easy for users to understand, the lifetime errors are not very obvious unless you know what you are looking for.

Comment (alamb) [reply parquet/src/file/mod.rs:51]: I am not opposed to removing the `FileWriter` and  `RowGroupWriter`. I think it would help readability a lot. However I think other reviewers should weigh in.

If we are going to make such an API change, perhaps we should do it in the same release as this change to get it all over with at once.

File: parquet/src/file/writer.rs (hunk 11 above)
Comment (tustvold) [reply parquet/src/file/writer.rs:114]: This method no longer exists, and is instead on the ColumnWriter itself

File: parquet/src/arrow/arrow_writer.rs [hunk 16]
```diff
@@ -188,7 +190,7 @@ impl<W: 'static + ParquetWriter> ArrowWriter<W> {
             write_leaves(row_group_writer.as_mut(), &arrays, &mut levels)?;
         }
 
-        self.writer.close_row_group(row_group_writer)?;
+        row_group_writer.close().unwrap();
```
Comment (ahmedriza) [inline parquet/src/arrow/arrow_writer.rs:193]: Since this returns a `Result` anyway, is there a particular reason to call `unwrap` instead of using `?`

**Comment by ahmedriza** [comment]
This is a great step forwards, and makes it cleaner as well as let the compiler enforce invariants to avoid things like https://github.com/apache/arrow-rs/issues/1717 happening.

**Comment by tustvold** [comment]
I've removed the FileWriter and RowGroupWriter traits as discussed, and deprecated FileSink and InMemoryWriteableCursor.

Assuming CI doesn't find something I've missed I think this is now ready, unless anyone objects I intend to leave it open for another 24 hours and then get it merged.

**Comment by alamb** [comment]
It will be a nice feature in version 15 🎉

File: parquet/src/arrow/arrow_writer.rs (hunk 16 above)
Comment (tustvold) [reply parquet/src/arrow/arrow_writer.rs:190]: Good spot - pure oversight

**Comment by alamb** [comment]
👨‍🍳 👌  -- this will be a very nice improvement in arrow 15 ❤️  -- thank you @tustvold
